InsightSoftwareConsortium/ITK

circle.yml
Change-Id: I9fc2a35fb261e09012af771b5d57dd4f8bb7c37e
=> COMP: Fix CircleCI ITK data download file name

Testing/ContinuousIntegration/AzurePipelinesMacOS.yml, Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
See the [CONTRIBUTING](CONTRIBUTING.md) guide. Specifically:
Start ITK commit messages with a standard prefix (and a space):
* BUG: fix for runtime crash or incorrect result
* COMP: compiler error or warning fix
* DOC: documentation change
* ENH: new functionality
* PERF: performance improvement
* STYLE: no logic impact (indentation, comments)
* WIP: Work In Progress not ready for merge
Provide a short, meaningful message that describes the change you made.
When the PR is based on a single commit, the commit message is usually left as the PR message.
A [reference to a related issue or pull request](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests) in your repository. You can automatically [close a related issues using …
=> BUG: Remove apt-get install's from macOS Azure Pipeline's configuration

Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
See the [CONTRIBUTING](CONTRIBUTING.md) guide. Specifically:
Start ITK commit messages with a standard prefix (and a space):
* BUG: fix for runtime crash or incorrect result
* COMP: compiler error or warning fix
* DOC: documentation change
* ENH: new functionality
* PERF: performance improvement
* STYLE: no logic impact (indentation, comments)
* WIP: Work In Progress not ready for merge
Provide a short, meaningful message that describes the change you made.
When the PR is based on a single commit, the commit message is usually left as the PR message.
A [reference to a related issue or pull request](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests) in your repository. You can automatically [close a related issues using …
=> ENH: Use Release CMAKE_BUILD_TYPE for macOS Python CI builds

Modules/Remote/SmoothingRecursiveYvvGaussianFilter.remote.cmake
Update the `SmoothingRevursiveYvvGaussianFilter` remote module commit hash
to the latest commit.
=> ENH: Update the SmoothingRecursiveYvvGaussianFilter remote module hash.

Testing/ContinuousIntegration/AzurePipelinesLinux.yml, Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml
Avoid issues with unavailable old packages.
=> BUG: Run apt-get update for Linux Azure configuration

Modules/Core/Common/wrapping/itkImageToImageFilterB.wrap, Modules/Core/Common/wrapping/itkInPlaceImageFilterB.wrap
To address:
/Users/johnsonhj/Dashboard/src/ITK-bld/Wrapping/Typedefs/itkUnaryGeneratorImageFilter.i:72:
Warning 401: Nothing known about base class 'itk::InPlaceImageFilter<
itk::Image< std::complex< double >,2 >,itk::Image< std::complex< float
>,2 > >'. Ignored.
/Users/johnsonhj/Dashboard/src/ITK-bld/Wrapping/Typedefs/itkUnaryGeneratorImageFilter.i:72:
Warning 401: Maybe you forgot to instantiate 'itk::InPlaceImageFilter<
itk::Image< std::complex< double >,2 >,itk::Image< std::complex< float
>,2 > >' using %template.
/Users/johnsonhj/Dashboard/src/ITK-bld/Wrapping/Typedefs/itkUnaryGeneratorImageFilter.i:462:
Warning 401: Nothing known about base class 'itk::InPlaceImageFilter<
itk::Image< std::complex< double >,3 >,itk::Image< std::complex< float
>,3 > >'. Ignored. …
=> COMP: Wrap InPlaceImageFilter for complex float to complex double

Modules/Remote/Montage.remote.cmake
The updates include
* std::mutex refactoring
* Butterworth band-pass filtering of input tiles
* adjust to VXL2 changes
=> ENH: update Montage remote module

CONTRIBUTING.md
Note that the pull request has to be explicitly opened, which may not be obvious.
Remove the note about data -- we simplified the data upload process, and there is nothing to be concerned about when pushing anymore.
=> DOC: Note that a pull request has to be explicitly opened

Modules/Bridge/NumPy/include/itkPyBuffer.h, Modules/Bridge/NumPy/include/itkPyBuffer.hxx, Modules/Bridge/NumPy/wrapping/PyBuffer.i.in, Wrapping/Generators/Python/itkExtras.py, Wrapping/Generators/Python/itkTemplate.py
@thewtex These changes fixed the issue described on [discourse](https://discourse.itk.org/t/numpy-bridge-with-image-vectors/1422/2).
=> BUG: fix NumPy bridge for itk::Image with PixelType itk::Vector

Modules/ThirdParty/Eigen3/CMakeLists.txt
Also adds minimal versio when Eigen3 added support for modern cmake.
=> COMP: Add CONFIG to find_package(Eigen3)

Modules/Core/Common/include/itkHexahedronCell.h, Modules/Core/Common/include/itkHexahedronCell.hxx
3 is the cell dimension -- make this explicit.
Change-Id: I7f458d7517ddb0442c05a35dde1af8734f8786f4
=> STYLE: Improve readability of HexadedronCell::EvaluatePosition.

Modules/Filtering/ImageFeature/test/itkUnsharpMaskImageFilterTest.cxx, Modules/Filtering/ImageGrid/test/itkMirrorPadImageFilterTest.cxx, Modules/Numerics/Statistics/include/itkStatisticsAlgorithm.h, Modules/Segmentation/ConnectedComponents/test/itkHardConnectedComponentImageFilterTest.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/Common/gdcmCAPICryptographicMessageSyntax.cxx
=> COMP: compile with Visual Studio in conformance mode AKA /permissive-

Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.h, Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.hxx
=> Fix Ninja build with CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS

Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h, Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx
Dropped the implicit assumption that the buffered region of an image, passed as argument to one of the range constructors, starts at index zero. With this commit, ShapedImageNeighborhoodRange supports any arbitrary buffered region index (which is already supported by "old-school" ITK iterators, like itk::ConstNeighborhoodIterator).
=> ENH: ShapedImageNeighborhoodRange now supports any buffered region index

Documentation/ITK5MigrationGuide.md
When building Slicer against ITK for the first time, these are some
of the migrations that needed to be put into place.
=> DOC: Improved documentation for the migration guide

Documentation/UploadBinaryData.md
*This is a reminder of what a message in a pull request should minimally require. Please, **read the guidelines below**, and **delete** them so your pull request description only contains the intended message.*
=> DOC: Add missing CONTRIBUTING.md link in UploadBinaryData.md

Modules/IO/DCMTK/src/itkDCMTKFileReader.cxx
Dictionary locking/unlocking function
names changed.
=> ENH: DCMTK 3.6.4 api changes accomodated

Modules/Filtering/ImageFeature/include/itkHessianRecursiveGaussianImageFilter.h
=> DOC: removing long outdated comment

Modules/Remote/IsotropicWavelets.remote.cmake
```
git shortlog --no-merges \
53aba7e7e44fa3acd5d456e7239035163c823ea8..18bc3277cd21c2a6cd5097914f664fad3051f761
```
```
Jon Haitz Legarreta Gorroño (2):
DOC: Improve Python package information.
ENH: Improve the `README` file.
Pablo Hernandez-Cerdan (1):
ENH: Reset direction to identity before forward wavelet
```
=> ENH: Update IsotropicWavelets module

Modules/Remote/Montage.remote.cmake
git shortlog --no-merges 46cad95..d0994e6
Dženan Zukic (2):
BUG: updating test output path to allow testing as part of ITK
BUG: removing extraneous comma in documentation
Jon Haitz Legarreta Gorroño (1):
DOC: Improve Python package information.
=> ENH: updating Montage module

Documentation/CodeOfConduct/Enforcement.md
Adjust the CoC Committe to the 01/09/2019 meeting decision.
See the meeting notes at:
https://www.insightsoftwareconsortium.org/meetingnotes.html
=> DOC: Adjust the CoC Committe to the 01/09/2019 meeting decision.

Modules/Remote/IsotropicWavelets.remote.cmake
git shortlog --no-merges 18bc3277cd21c2a6cd5097914f664fad3051f761..
Pablo Hernandez-Cerdan (4):
ENH: Wrap StructureTensor and adds GetRotationMatrix
BUG: Fix origin of itkFFTPadPositiveIndexImageFilter
BUG: Fix level returning from IndexToLevelBandSteerablePyramid
STYLE: Add new lines in function declarations
=> ENH: Update IsotropicWavelets

Modules/Remote/Montage.remote.cmake
=> ENH: update ITKMontage: Fix crash when setting tiles from memory

Modules/Remote/IOMeshSTL.remote.cmake
git shortlog --no-merges e681a38aba1d89561eec89584d80f62dd2affa23..
Matt McCormick (6):
ENH: Rename repository to be consistent with ITK modules
ENH: Python package requires itk>4
BUG: Set PointDimension to 3
BUG: Fix wrapping module name
ENH: Make module name consistent with conventions
DOC: Fix AppVeyor badge and link after module name update
=> ENH: Update IOMeshSTL remote module and update name

Examples/DataRepresentation/Image/Image4.cxx
Following up discourse:
https://discourse.itk.org/t/solved-transformindextophysicalpoint-manually/1031/9
=> DOC: SoftwareGuide: improve TransformIndexToPhysicalPoint notation

Modules/Remote/IOFDF.remote.cmake
Update the ITKIOFDF remote module:
- Update to the new GitHub repository URL.
- Bump to the latest version.
=> ENH: Update the ITKIOFDF remote module.

Modules/ThirdParty/VNL/README.md
Increase the `VNL` ThirdParty module `README` file information accuracy:
- Update the documentation link.
- Provide a correct/valid link to look for instructions to update from
upstream.
- Improve readability addin Markdown syntax markup.
=> DOC: Increase `VNL` ThirdParty module `README` information accuracy.

Modules/Remote/Thickness3D.remote.cmake
Bump the latest version of the `ITKThickness3D` remote module.
=> ENH: Bump the latest version of the `ITKThickness3D` remote.

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Fix GitHub community template syntax errors.
=> BUG: Fix GitHub community template syntax errors.

Modules/Core/Common/include/itkBSplineDerivativeKernelFunction.h, Modules/Core/Common/include/itkBSplineKernelFunction.h, Modules/Core/Common/include/itkFrustumSpatialFunction.hxx, Modules/Core/Common/include/itkSymmetricEigenAnalysis.hxx, Modules/Core/Common/src/itkMemoryUsageObserver.cxx, Modules/Filtering/BiasCorrection/test/itkN4BiasFieldCorrectionImageFilterTest.cxx, Modules/Filtering/Denoising/include/itkPatchBasedDenoisingImageFilter.hxx, Modules/IO/TransformHDF5/include/itkHDF5TransformIO.hxx, Modules/Registration/Common/include/itkBlockMatchingImageFilter.hxx, Modules/Registration/RegistrationMethodsv4/test/itkQuasiNewtonOptimizerv4RegistrationTest.cxx, Modules/Registration/RegistrationMethodsv4/test/itkSimpleImageRegistrationTest.cxx, Modules/Registration/RegistrationMethodsv4/test/itkSimpleImageRegistrationTest2.cxx, Modules/Registration/RegistrationMethodsv4/test/itkSimpleImageRegistrationTest3.cxx, Modules/Registration/RegistrationMethodsv4/test/itkSimpleImageRegistrationTest4.cxx, Modules/Registration/RegistrationMethodsv4/test/itkSimpleImageRegistrationTestWithMaskAndSampling.cxx, Modules/Segmentation/LevelSets/include/itkLevelSetFunctionWithRefitTerm.hxx, Modules/Segmentation/LevelSetsv4/include/itkLevelSetSparseImage.hxx, Modules/Segmentation/LevelSetsv4/include/itkMalcolmSparseLevelSetImage.hxx, Modules/Segmentation/LevelSetsv4/include/itkShiSparseLevelSetImage.hxx
Fixed Visual Studio 2017 warning (level 4) C4702: unreachable code
=> COMP: Removed unreachable code, fixing VS2017 warning (level 4) C4702

Modules/ThirdParty/KWSys/CMakeLists.txt
=> ENH: add better support for Unicode by using UTF-8 by default in KWSys

Modules/Core/Common/include/itkTreeChangeEvent.h, Modules/IO/XML/src/itkXMLFile.cxx, Modules/ThirdParty/ZLIB/src/itkzlib/CMakeLists.txt
Trying to fix warnings in this build:
https://open.cdash.org/viewBuildError.php?type=1&buildid=5775220
=> Fix warnings

.github/ISSUE_TEMPLATE/coding_style_inconsistency_report.md, .github/ISSUE_TEMPLATE/compiler_support_report.md, .github/ISSUE_TEMPLATE/coverage_impact_report.md, .github/ISSUE_TEMPLATE/data_addition_request.md, .github/ISSUE_TEMPLATE/design_impact_report.md, .github/ISSUE_TEMPLATE/documentation_impact_report.md, .github/ISSUE_TEMPLATE/infrastructure_impact_report.md, .github/ISSUE_TEMPLATE/performance_impact_report.md, .github/ISSUE_TEMPLATE/regression_bug_report.md
Add new GitHub community issue templates.
=> ENH: Add new GitHub community issue templates.

.github/ISSUE_TEMPLATE/coverage_impact_report.md
Improve wording in coverage issue GitHub template name, and make it
consistent with the style of the rest of the templates.
=> STYLE: Improve coverage issue template name wording.

Modules/ThirdParty/Eigen3/CMakeLists.txt
Fix extracted from #562
Closes #566
Co-authored-by: John Muschelli <muschellij2@gmail.com>
=> BUG: Fix Eigen3 INSTALL_DIR

Documentation/ITK5MigrationGuide.md
Reorder a misplaced paragraph. Minor visual improvements.
=> DOC: Update ITK5MigrationGuide

Modules/Remote/IsotropicWavelets.remote.cmake
```
git shortlog --no-merges  02e14fce0..99d527a4
Pablo Hernandez-Cerdan (11):
ENH: Add example for riesz phase analysis
BUG: Fix dimension in riesz Phase analysis example
PERF: Add DynamicThreaded to RieszBankGenerator
PERF: Add DynamicThreaded to WaveletBankGenerator
ENH: Bump itk required version for python in setup.py
ENH: Travis: Do not restrict the python wheels for OSx
COMP: Increase epsilon in numerical comparisson in Utilities
COMP: Generate packages for python 2.7 and 3.7
ENH: Add multiplyWith methods to RieszRotationMatrix
Set up CI with Azure Pipelines
BUG: Fix wrong expected result on test of RieszRotationMatrix
```
=> ENH: Update Remote Module IsotropicWavelets

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/coding_style_inconsistency_report.md, .github/ISSUE_TEMPLATE/compiler_support_report.md, .github/ISSUE_TEMPLATE/coverage_impact_report.md, .github/ISSUE_TEMPLATE/data_addition_request.md, .github/ISSUE_TEMPLATE/design_impact_report.md, .github/ISSUE_TEMPLATE/documentation_impact_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/infrastructure_impact_report.md, .github/ISSUE_TEMPLATE/performance_impact_report.md, .github/ISSUE_TEMPLATE/regression_bug_report.md
Add emojis to GitHub issue templates.
=> DOC: Add emojis to GitHub community issue templates.

Modules/Bridge/NumPy/test/itkPyVnlTest.py, Wrapping/Generators/Python/CMakeLists.txt, Wrapping/Generators/Python/PyBase/pyBase.i
This PR adds a test to PR #601 as discussed on [discourse](https://discourse.itk.org/t/numpy-vnl-bridge-unexpected-behavior/1659).
=> Get vnl matrix reference

Modules/ThirdParty/VNL/src/vxl/CMakeLists.txt, Modules/ThirdParty/VNL/src/vxl/core/vxl_version.h, Modules/ThirdParty/VNL/src/vxl/vcl/CMakeLists.txt
Resolves #602 missing installed file MSVC builds.
=> Fix vxl install vcl msvc warnings

Modules/Remote/AnisotropicDiffusionLBR.remote.cmake, Modules/Remote/BSplineGradient.cmake, Modules/Remote/BoneMorphometry.remote.cmake, Modules/Remote/Cuberille.remote.cmake, Modules/Remote/LabelErodeDilate.remote.cmake, Modules/Remote/MeshNoise.remote.cmake, Modules/Remote/MinimalPathExtraction.remote.cmake, Modules/Remote/Montage.remote.cmake, Modules/Remote/PhaseSymmetry.remote.cmake, Modules/Remote/SkullStrip.remote.cmake, Modules/Remote/SmoothingRecursiveYvvGaussianFilter.remote.cmake, Modules/Remote/SplitComponents.remote.cmake, Modules/Remote/Strain.remote.cmake, Modules/Remote/Thickness3D.remote.cmake, Modules/Remote/WikiExamples.remote.cmake
Update a few remote modules to their latest commit versions.
=> ENH: Update a few remote modules to their latest commit versions

CONTRIBUTING.md
Improve the `CONTRIBUTING.md` guidelines document:
- Add further commit message guidelines.
- Describe the procedure to follow to make breaking changes.
- Describe the procedure to follow to make design changes.
- Explicitly mention and cross-ref the CI system used (Azure Pipelines)
and the CDash Github Checks.
=> DOC: Improve the CONTRIBUTING guidelines document

Modules/Core/Common/include/itkImageTransformer.h
=> DOC: Fix typo

.github/pull_request_template.md
Add checklist to PR template to:
- Remind users about the necessary parts for a good PR.
- Allow reviewers get a grasp of the PR at a glance.
=> DOC: Add checklist to PR template

CMake/ITKSetStandardCompilerFlags.cmake
Provide a mechanism for changing the default warning
and ABI/OPTIMIZATION flags.
The default ABI/Optimization flag settings are
set to:
```bash
-mtune=native # Tune the code for the computer used compile
-march=corei7 # Use ABI settings to support corei7
```
The defaults can easily be overriden from the cmake comand line with:
```bash
-DITK_C_OPTIMIZATION_FLAGS:STRING="-march=native"
-DITK_CXX_OPTIMIZATION_FLAGS:STRING="-march=native"
-DITK_C_WARNING_FLAGS:STRING="-Wall -Werror"
-DITK_CXX_WARNING_FLAGS:STRING="-Wall -Werror"
```
=> PERF: Allow overwriting ABI/Optimization & Warning flags

Utilities/Maintenance/WhatModulesITK.py
Required if e.g. itkMeshFileWriter is used
=> BUG: WhatModulesITK.py doesn't detect ITKMeshIO

Documentation/ITK5MigrationGuide.md, Documentation/ReleaseNotes/2.8.md, Modules/Filtering/LabelMap/include/itkLabelMap.h
=> DOC: change thorw -> throw spelling.

Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkMultithreadingTest.cxx
=> Minor refactoring

Modules/Remote/IOScanco.remote.cmake
An ITK module to read and write Scanco microCT .isq files.
=> ENH: Add IOScanco remote module

Modules/Core/Mesh/include/itkBinaryMask3DMeshSource.h
Reference [Email](https://public.kitware.com/pipermail/community/2017-August/013509.html)
=> WIP: BUG: index overflow in BinaryMask3DMeshSource

Modules/Remote/AnisotropicDiffusionLBR.remote.cmake, Modules/Remote/BioCell.remote.cmake, Modules/Remote/BoneMorphometry.remote.cmake, Modules/Remote/FixedPointInverseDisplacementField.remote.cmake, Modules/Remote/GenericLabelInterpolator.remote.cmake, Modules/Remote/HigherOrderAccurateGradient.remote.cmake, Modules/Remote/IOMeshSTL.remote.cmake, Modules/Remote/IOOpenSlide.remote.cmake, Modules/Remote/IOTransformDCMTK.remote.cmake, Modules/Remote/IsotropicWavelets.remote.cmake, Modules/Remote/LesionSizingToolkit.remote.cmake, Modules/Remote/MinimalPathExtraction.remote.cmake, Modules/Remote/MorphologicalContourInterpolation.remote.cmake, Modules/Remote/NeuralNetworks.remote.cmake, Modules/Remote/ParabolicMorphology.remote.cmake, Modules/Remote/PerformanceBenchmarking.remote.cmake, Modules/Remote/PrincipalComponentsAnalysis.remote.cmake, Modules/Remote/RLEImage.remote.cmake, Modules/Remote/SphinxExamples.remote.cmake, Modules/Remote/SplitComponents.remote.cmake, Modules/Remote/SubdivisionQuadEdgeMeshFilter.remote.cmake, Modules/Remote/TextureFeatures.remote.cmake, Modules/Remote/Thickness3D.remote.cmake, Modules/Remote/TwoProjectionRegistration.remote.cmake, Modules/Remote/VariationalRegistration.remote.cmake, Modules/Remote/WikiExamples.remote.cmake
=> ENH: Bump remote modules.

Documentation/ITK5MigrationGuide.md
Since MyBoundingBoxInObjectSpace is computed via Update(), it can be converted to a bounding itk::Region defined in IndexSpace.
Updated example code is provided.  It offers significant speed improvement by using the already-computed MyBoundingBoxInObjectSpace as a basis for the index space box.
=> DOC: Update recommendation for computing a Bounding Region in IndexSpace

Modules/Remote/AnisotropicDiffusionLBR.remote.cmake, Modules/Remote/HigherOrderAccurateGradient.remote.cmake, Modules/Remote/IOScanco.remote.cmake
Bump remote modules to latest commits:
- `AnisotropicDiffusionLBR`
- `HigherOrderAccurateGradient`
- `IOScanco`
=> ENH: Bump remote modules to latest commits

Modules/Remote/AnisotropicDiffusionLBR.remote.cmake, Modules/Remote/Montage.remote.cmake, Modules/Remote/SplitComponents.remote.cmake
Bump remote modules to their latest commits:
- `AnisotropicDiffusionLBR`
- `Montage`
- `SplitComponents`
=> ENH: Bump remote modules to their latest commits

Testing/ContinuousIntegration/AzurePipelinesBatch.yml
Also use CTEST_COVERAGE_COMMAND.
Hopefully this will address #702 .
=> BUG: Set dashboard_do_coverage in Azure configuration

itk_common.cmake
Closes #120 Use the refs/follow/nightly/master ref for Nightly builds
Build from yesterday:
https://open.cdash.org/buildSummary.php?buildid=5851274
Today:
https://open.cdash.org/buildSummary.php?buildid=5853452
=> Nightly ref

Modules/Core/SpatialObjects/include/itkMetaConverterBase.h, Modules/Core/SpatialObjects/include/itkMetaSceneConverter.h
=> COMP: missing override for destructors

Modules/ThirdParty/KWSys/src/KWSys/CMakeLists.txt, Modules/ThirdParty/KWSys/src/KWSys/Configure.h.in, Modules/ThirdParty/KWSys/src/KWSys/DynamicLoader.cxx, Modules/ThirdParty/KWSys/src/KWSys/DynamicLoader.hxx.in, Modules/ThirdParty/KWSys/src/KWSys/SystemTools.cxx, Modules/ThirdParty/KWSys/src/KWSys/SystemTools.hxx.in, Modules/ThirdParty/KWSys/src/KWSys/kwsysPlatformTestsCXX.cxx, Modules/ThirdParty/KWSys/src/KWSys/testDynamicLoader.cxx, Modules/ThirdParty/KWSys/src/KWSys/testDynloadImpl.c, Modules/ThirdParty/KWSys/src/KWSys/testDynloadImpl.h, Modules/ThirdParty/KWSys/src/KWSys/testDynloadUse.c
=> Updating KWSys

Modules/Remote/IsotropicWavelets.remote.cmake, Modules/Remote/Montage.remote.cmake, Modules/Remote/RTK.remote.cmake, Modules/Remote/SplitComponents.remote.cmake
Updating remote modules (with successful builds) as requested in #740.
=> ENH: Update remote modules

Modules/Core/Common/include/itkVectorContainer.hxx, Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMesh.h
Minor corner case compilation warnings.
=> Minor compiler error

Examples/SpatialObjects/SceneSpatialObject.cxx, Examples/SpatialObjects/SpatialObjectTransforms.cxx
Fix Software Guide line length too long warnings.
Fixes:
```
Examples/SpatialObjects/SceneSpatialObject.cxx:129:80: warning: Line
length too long for LaTeX printing
```
and
```
Examples/SpatialObjects/SpatialObjectTransforms.cxx:229:80: warning: Line
length too long for LaTeX printing
```
raised at:
http://testing.cdash.org/viewBuildError.php?type=1&buildid=5867675
=> COMP: Fix Software Guide line length too long warnings

Modules/Remote/TotalVariation.remote.cmake
https://github.com/InsightSoftwareConsortium/ITKTotalVariation
It contains the class itkProxTVImageFilter that wraps around the third
party library proxTV: https://github.com/albarji/proxTV
=> ENH: Add remote module TotalVariation

Modules/Core/SpatialObjects/include/itkMetaEvent.h, Modules/Core/SpatialObjects/include/itkSpatialObjectFactoryBase.h, Modules/Core/SpatialObjects/include/itkSpatialObjectProperty.h, Modules/Core/SpatialObjects/itk-module.cmake
=> COMP: Add export specification to ITKSpatialObjects

Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.hxx, Modules/Core/ImageFunction/wrapping/itkWindowedSincInterpolateImageFunction.wrap, Modules/Core/ImageFunction/wrapping/test/CMakeLists.txt
=> Wrap windowed sinc interpolators

Modules/Core/Common/include/itkFixedArray.h, Modules/Core/Common/test/itkFixedArrayGTest.cxx
Added Standard C++ Library (std) style reverse iterators to FixedArray.
Suggested by Pablo @phcerdan
=> ENH: Add std style reverse iterators to FixedArray

Modules/Core/Common/src/itkProcessObject.cxx
Simplified `ProcessObject::MakeNameFromIndex` by calling
`std::to_string`,
instead of using `globalIndexNames`.
Triggered by forum topic "Build ITK 5.0 in Windows", started by Sandro
Queiros,
who reported compile errors from VS2015 (before installing VS
updates), at
https://discourse.itk.org/t/build-itk-5-0-in-windows/1748 saying:
itkProcessObject.cxx(54): error C2440: ‘initializing’: cannot
convert from ‘const char [3]’ to ‘const char’.
Co-Author: Niels Dekker <N.Dekker@lumc.nl>
=> COMP: Address const char[] conversation warning

Utilities/Maintenance/UpdateRemoteModules.sh
Remove tab that slipped in commit b8a1416.
=> STYLE: Remove tab.

Documentation/Maintenance/Release.md
=> DOC: Improve ease of release note command execution

Modules/Core/Common/CMakeLists.txt, Modules/Core/Common/include/itkThreadSupport.h, Modules/Core/Common/src/itkConfigure.h.in
=> ENH: make ITK_MAX_THREADS configurable

Modules/Core/Common/test/itkThreadedIteratorRangePartitionerTest.cxx, Modules/Core/Common/test/itkThreadedIteratorRangePartitionerTest2.cxx
=> BUG: fix threading test bugs when ITK_DEFAULT_MAX_THREADS is over 256

Utilities/Maintenance/UpdateRemoteModules.sh, Utilities/Maintenance/UpdateRequiredITKVersionInRemoteModules.sh
Improve remote modules' maintenance scripts documentation.
=> DOC: Improve remote modules' maintenance scripts documentation

Modules/Core/GPUCommon/include/itkGPUImageDataManager.h, Modules/Core/GPUCommon/include/itkGPUKernelManager.h, Modules/Filtering/GPUImageFilterBase/include/itkGPUNeighborhoodOperatorImageFilter.hxx
=> COMP: compile GPU classes with legacies disabled

Modules/IO/PNG/src/itkPNGImageIO.cxx
=> Fix png leak on error

CMake/InsightValgrind-Ubuntu1804.supp
Suppressing valgrind defects from the system libraries.
=> ENH: Add Valgrind suppression file for Ubuntu 18.04 LTS

Documentation/ReleaseNotes/5.0rc02.md
=> DOC: Add ITK 5.0 RC 2 release notes

Documentation/ITK5MigrationGuide.md, Modules/Numerics/FEM/test/itkFEMElement2DC0LinearLineStressTest.cxx, Modules/Numerics/FEM/test/itkFEMElement2DC0LinearQuadrilateralMembraneTest.cxx, Modules/Numerics/FEM/test/itkFEMElement2DC0LinearQuadrilateralStrainItpackTest.cxx, Modules/Numerics/FEM/test/itkFEMElement2DC0LinearQuadrilateralStrainTest.cxx, Modules/Numerics/FEM/test/itkFEMElement2DC0LinearTriangleMembraneTest.cxx, Modules/Numerics/FEM/test/itkFEMElement2DC0LinearTriangleStrainTest.cxx, Modules/Numerics/FEM/test/itkFEMElement2DC0LinearTriangleStressTest.cxx, Modules/Numerics/FEM/test/itkFEMElement2DC0QuadraticTriangleStrainTest.cxx, Modules/Numerics/FEM/test/itkFEMElement2DC0QuadraticTriangleStressTest.cxx, Modules/Numerics/FEM/test/itkFEMElement2DC1BeamTest.cxx, Modules/Numerics/FEM/test/itkFEMElement2DTest.cxx, Modules/Numerics/FEM/test/itkFEMElement3DC0LinearHexahedronMembraneTest.cxx, Modules/Numerics/FEM/test/itkFEMElement3DC0LinearHexahedronStrainTest.cxx, Modules/Numerics/FEM/test/itkFEMElement3DC0LinearTetrahedronMembraneTest.cxx, Modules/Numerics/FEM/test/itkFEMElement3DC0LinearTetrahedronStrainTest.cxx, Modules/Numerics/FEM/test/itkFEMElement3DTest.cxx, Modules/Numerics/FEM/test/itkFEMLandmarkLoadImplementationTest.cxx, Modules/Numerics/FEM/test/itkFEMLoadBCMFCTest.cxx, Modules/Numerics/FEM/test/itkFEMLoadEdgeTest.cxx, Modules/Numerics/FEM/test/itkFEMLoadGravConstTest.cxx, Modules/Numerics/FEM/test/itkFEMSolverTest3D.cxx
Update to use the new GetGroup method which replaces the GetScene.
=> BUG: Update FEM test for new spatial objects

README.md, Testing/ContinuousIntegration/AzurePipelinesBatch.yml
This PR improves `AzurePipelinesBatch.yml` and should run hand in hand with `https://github.com/InsightSoftwareConsortium/ITK/pull/824` to ensure that the coverate tests are indeed run.
=> Improves AzurePipelinesBatch.yml

Modules/Core/Common/src/itkTBBMultiThreader.cxx
- 🚫 [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- 🚫 [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- 🚫 does not Adds the License notice to new files.
- 🚫 Adds Python wrapping.
- 🚫 Adds tests and baseline comparison (quantitative).
- 🚫 [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- 🚫 Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- 🚫 Adds Documentation.
=> COMP: Intel required static variable

Modules/Core/SpatialObjects/include/itkSpatialObjectFactoryBase.h
=> COMP: removing extraneous DLL specification from private member

Modules/Numerics/FEM/include/itkMetaFEMObjectConverter.hxx
=> COMP: follow-up on recent removal of METAIO_STL macro

Modules/Registration/Common/itk-module.cmake
=> COMP: add missing dependent module for ITKv3 examples

Examples/Filtering/SpatialObjectToImage1.cxx
This addresses valgrind defects related to using uninitialized values
related to the 3d component of the point being unset.
=> BUG: Set all component of 3D points

Modules/Bridge/NumPy/wrapping/PyBuffer.i.in, Wrapping/Generators/Python/itkExtras.py
=> BUG: Minor python wrapping fixes

Modules/IO/ImageBase/include/itkImageFileWriter.h, Modules/IO/ImageBase/include/itkImageFileWriter.hxx, Modules/IO/Meta/src/itkMetaImageIO.cxx
=> Expose compression level interface in MetaIO 

Modules/Filtering/FFT/src/itkFFTWGlobalConfiguration.cxx, Modules/Registration/Common/include/itkImageToImageMetric.h
These two commits fix the warnings of the dashboard results [here](https://my.cdash.org/viewBuildError.php?type=1&buildid=1649833) and [here](https://my.cdash.org/viewBuildError.php?type=1&buildid=1649889).
=> Fftw registration warnings

Modules/Remote/HigherOrderAccurateGradient.remote.cmake, Modules/Remote/IOMeshSTL.remote.cmake, Modules/Remote/IOScanco.remote.cmake, Modules/Remote/LesionSizingToolkit.remote.cmake, Modules/Remote/MinimalPathExtraction.remote.cmake, Modules/Remote/Montage.remote.cmake, Modules/Remote/PerformanceBenchmarking.remote.cmake, Modules/Remote/RLEImage.remote.cmake, Modules/Remote/RTK.remote.cmake, Modules/Remote/SphinxExamples.remote.cmake, Modules/Remote/TotalVariation.remote.cmake
=> ENH: updating remote modules

Modules/Core/Common/src/itkStreamingProcessObject.cxx
=> COMP: fix warning: 'return' will never be executed

Modules/Compatibility/Deprecated/include/itkBarrier.h
=> COMP: fix export specification of Barrier class

Documentation/CodeOfConduct/Enforcement.md, Documentation/CodeOfConduct/Reporting.md
Modify the CoC breach reporting procedure as agreed in the last ISC board
meeting.
Specifically:
- Use email communications instead of a form to report breaches.
- Change the composition of the committee so as to simplify forming a
committee.
- Fix some typos and cross-references.
- Improve the wording of some parts.
=> DOC: Modify the CoC breach reporting procedure

Modules/Remote/ParabolicMorphology.remote.cmake
to be compatible with #855
See also: https://github.com/InsightSoftwareConsortium/ITKParabolicMorphology/pull/26
=> ENH: Bump remote module ParabolicMorphology

Modules/ThirdParty/VNL/src/vxl/vcl/vcl_compiler.h
=> COMP: Add VXL support for GCC 9

Modules/Filtering/ImageStatistics/include/itkLabelStatisticsImageFilter.h, Modules/Filtering/ImageStatistics/include/itkMinimumMaximumImageFilter.h, Modules/Filtering/ImageStatistics/include/itkStatisticsImageFilter.h, Modules/Numerics/Statistics/include/itkImageToHistogramFilter.h, Modules/Numerics/Statistics/include/itkMaskedImageToHistogramFilter.h
Remove outdated comments, and add description for streaming to these
filters.
=> DOC: Update documentation for streaming statistics filters.

Examples/SpatialObjects/BlobSpatialObject.cxx, Examples/SpatialObjects/EllipseSpatialObject.cxx, Examples/SpatialObjects/SceneSpatialObject.cxx, Examples/SpatialObjects/SpatialObjectHierarchy.cxx, Examples/SpatialObjects/SpatialObjectTransforms.cxx, Modules/Core/SpatialObjects/include/itkDTITubeSpatialObject.h, Modules/Core/SpatialObjects/include/itkSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkTubeSpatialObject.h
This pull request is paired with a pull request for ITKSoftwareGuide (pull request has the same name) to update the tex/documentation of SpatialObjects to match the implementation in ITKv5
=> ENH: Updated Spatial Object tex to match ITKv5

Examples/RegistrationITKv4/test/CMakeLists.txt, Modules/Registration/Common/test/RegistrationITKv3/test/CMakeLists.txt
Remove last DART based CMake variables.
=> STYLE: Use CTEST_TEST_TIMEOUT

Wrapping/Generators/Python/CMakeLists.txt, Wrapping/Generators/Python/PyBase/pyBase.i
#951 cherry picked onto release branch.
=> BUG: ImageBase regions are returned as reference

Modules/Core/Common/include/itkDataObject.h, Modules/Core/Common/src/itkProcessObject.cxx, Modules/Core/Common/test/itkDataObjectAndProcessObjectTest.cxx
This but was encountered when setting an output to nullptr.
=> Demonstrate type in DataObject::MakeOutput

.gitattributes, Documentation/Maintenance/Release.md, GettingStarted.md, Modules/Core/Common/include/itkCovariantVector.h, Modules/Core/Common/include/itkImage.h, Modules/Core/Common/include/itkImageDuplicator.h, Modules/Core/Common/include/itkImageRegion.h, Modules/Core/Common/include/itkIndex.h, Modules/Core/Common/include/itkNumericTraits.h, Modules/Core/Common/include/itkOffset.h, Modules/Core/Common/include/itkPoint.h, Modules/Core/Common/include/itkPointSet.h, Modules/Core/Common/include/itkRGBPixel.h, Modules/Core/Common/include/itkSize.h, Modules/Core/Common/include/itkVector.h, Modules/Core/TestKernel/include/itkRandomImageSource.h, Modules/Filtering/ImageFeature/include/itkLaplacianImageFilter.h, Modules/Filtering/ImageGrid/include/itkConstantPadImageFilter.h, Modules/Filtering/ImageGrid/include/itkFlipImageFilter.h, Modules/Filtering/ImageGrid/include/itkMirrorPadImageFilter.h, Modules/Filtering/ImageGrid/include/itkResampleImageFilter.h, Modules/Filtering/ImageIntensity/include/itkMultiplyImageFilter.h, Modules/Filtering/ImageIntensity/include/itkSinImageFilter.h, Modules/Filtering/LabelMap/include/itkObjectByObjectLabelMapFilter.h, Modules/Filtering/Smoothing/include/itkMeanImageFilter.h, Modules/IO/ImageBase/include/itkImageFileReader.h, Modules/IO/ImageBase/include/itkImageFileWriter.h, Modules/IO/TIFF/include/itkTIFFImageIO.h, Utilities/Doxygen/doxygen.config.in
=> DOC: Prefer sphinx examples over wiki

CODE_OF_CONDUCT.md
As part of SimpleITK adopting the code of conduct found some minor
issues that are fixed by this commit.
=> DOC: Correcting some grammer and updating the toolkit name.

Modules/Core/ImageFunction/include/itkGaussianInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkGaussianInterpolateImageFunction.hxx, Modules/Core/ImageFunction/include/itkLabelImageGaussianInterpolateImageFunction.hxx, Modules/Core/ImageFunction/test/itkGaussianInterpolateImageFunctionTest.cxx
=> Support streaming in Gaussian interpolate image function

Utilities/Maintenance/UpdateRemoteModules.sh
Fix indentation in bash script.
=> STYLE: Fix indentation in bash script

Examples/SpatialObjects/ArrowSpatialObject.cxx, Examples/SpatialObjects/BlobSpatialObject.cxx, Examples/SpatialObjects/DTITubeSpatialObject.cxx, Examples/SpatialObjects/GaussianSpatialObject.cxx, Examples/SpatialObjects/ImageMaskSpatialObject.cxx, Examples/SpatialObjects/ImageSpatialObject.cxx, Examples/SpatialObjects/LandmarkSpatialObject.cxx, Examples/SpatialObjects/LineSpatialObject.cxx, Examples/SpatialObjects/MeshSpatialObject.cxx, Examples/SpatialObjects/ReadWriteSpatialObject.cxx, Examples/SpatialObjects/SceneSpatialObject.cxx, Examples/SpatialObjects/SpatialObjectHierarchy.cxx, Examples/SpatialObjects/SpatialObjectTransforms.cxx, Examples/SpatialObjects/SurfaceSpatialObject.cxx, Examples/SpatialObjects/TubeSpatialObject.cxx, Examples/SpatialObjects/VesselTubeSpatialObject.cxx
Updates to the ITKSoftwareGuide's chapter on SpatialObjects.   Updates correct the SoftwareGuide to match the API of ITKv5.
There is a corresponding pull request to the ITKSoftwareGuide repo.
=> DOC: Updates to itk software guide spatial objects

Documentation/ReleaseNotes/5.0.md
Co-authored-by: Dzenan Zukic <dzenan.zukic@kitware.com>
Co-authored-by: Matt McCormick <matt.mccormick@kitware.com>
=> DOC: Add ITK 5.0 release notes

Utilities/Maintenance/UpdateRequiredITKVersionInRemoteModules.sh
Fix wrong variable names in remote modules required ITK version update
script.
Refer …
=> BUG: Fix wrong variable names

Modules/Remote/FixedPointInverseDisplacementField.remote.cmake
To trigger Python builds for PR #1072.
=> WIP: DO NOT MERGE: CI testing uses Python 3

Wrapping/Generators/CastXML/CMakeLists.txt
=> WIP: NO NOT MERGE: BUG: Fix COMPILE_DEFINITIONS of castxml

Modules/IO/ImageBase/include/itkImageIOBase.h, Modules/IO/ImageBase/src/CMakeLists.txt, Modules/IO/ImageBase/src/itkRawImageIOUtilities.cxx, Modules/IO/RAW/include/itkRawImageIO.h, Modules/IO/RAW/include/itkRawImageIO.hxx, Modules/IO/RAW/itk-module.cmake
Avoid:
warning: unused function template 'itkReadRawBytesAfterSwappingMacro' [-Wunused-template]
=> COMP: Prefer anonymous namespace over static template function

Modules/Core/Common/src/itkPoolMultiThreader.cxx
There is one work unit passed through the queue now,
as work unit 0 is executed in current thread.
=> ENH: PoolMultiThreader uses one less thread

Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMesh.hxx, Modules/IO/ImageBase/test/itkUnicodeIOTest.cxx
Two commits that fix a few MSVC Warning Level 4 warnings.
=> Fix a few MSVC Warning Level 4 warnings

Documentation/SupportedCompilers.md
=> ENH: documenting supported compilers

Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMesh.h
This prevents compile errors when calling `BuildCellLinks()` on a `const` mesh pointer, which is needed for backwards compatibility with `itk::Mesh`
=> COMP: Make BuildCellLinks method const

Wrapping/Generators/CastXML/CMakeLists.txt
Adds ppc64le support to fix #1078.
=> COMP: Update CastXML to 2019-07-15 master

Modules/Filtering/Convolution/itk-module.cmake
Small changes to fix library dependancies and consistency.
=> Fix library dependancies

Modules/Filtering/ImageCompose/include/itkJoinSeriesImageFilter.h, Modules/Filtering/ImageGrid/include/itkChangeInformationImageFilter.h, Modules/Filtering/ImageGrid/include/itkInterpolateImagePointsFilter.h, Modules/Filtering/ImageGrid/include/itkPasteImageFilter.h, Modules/Filtering/ImageGrid/include/itkResampleImageFilter.h, Modules/Filtering/ImageGrid/include/itkTileImageFilter.h, Modules/Filtering/ImageGrid/include/itkWarpImageFilter.h, Modules/Filtering/ImageIntensity/include/itkHistogramMatchingImageFilter.h, Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFilter.h, Modules/Registration/PDEDeformable/include/itkMultiResolutionPDEDeformableRegistration.h
Fix documentation spelling error.
=> DOC: Fix spelling typo VeriyInput -> VerifyInput

Modules/Bridge/NumPy/wrapping/PyVnlVectorBuffer.i.in, Modules/Bridge/NumPy/wrapping/test/CMakeLists.txt, Modules/Core/Common/wrapping/test/CMakeLists.txt, Modules/Core/Common/wrapping/test/itkMatrixTest.py, Wrapping/Generators/Python/PyBase/pyBase.i
@zahilshanis please take a look.
Closes #1122
=> ENH: Directly set an itk.ImageBase Direction with a NumPy Array

Wrapping/Generators/Python/CMakeLists.txt
This PR may need more testing by I ran into issues when trying to use swig 4.0.0 (current master of the repo) and this patch addressed the problem).
=> Add swig include directory to command line

Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
To provide the NumPy interface for the itkImagePythonTest,
itkMatrixPythonTest.
=> BUG: Enable ITKBridgeNumPy for Windows CI builds

Modules/Filtering/ImageStatistics/include/itkAdaptiveHistogramEqualizationImageFilter.h
=> DOC: AdaptiveHistogramEqualizationImageFilter default radius

Modules/Core/Common/include/itkExtractImageFilter.h, Modules/Core/TestKernel/include/itkTestingExtractSliceImageFilter.h
Restore enum type_name from style:
typdef DirectionCollapseStrategyEnum {
...
} DirectionCollapseStrategyEnum
=> COMP: Add missing enum type_name from prior enum declaration style

Utilities/Debugger/ITK.natvis
Update was necessitated by 549a19c956bab2b41489816d8bb8d4bd09161583.
=> ENH: update Visual Studio debug visualizers

Modules/IO/TIFF/src/itkTIFFImageIO.cxx
- [] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [] :no_entry_sign: Adds the License notice to new files.
- [] :no_entry_sign: Adds Python wrapping.
- [] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [] :no_entry_sign: Adds Documentation. …
=> BUG: 256 colors of tiff palette were read, only correct for 8bit images

Modules/Registration/FEM/include/itkFEMRegistrationFilter.h
=> Fix fem registration missing include

Modules/Core/Transform/include/itkBSplineTransform.h, Modules/Core/Transform/include/itkBSplineTransformInitializer.hxx
=> DOC: spelling correction in BSpline documentation

CMake/ITKSetStandardCompilerFlags.cmake
This patch fixes #1114. It's been tested on a computer without AVX capabilities, it would be great to test it on a computer with AVX and AVX2 capabilities.
@hjmjohnson @dzenanz
- :no_entry_sign: Adds Examples to …
=> BUG: test for AVX compatibility to set MSVC optimization flags

Documentation/Doxygen/MainPage.dox, GettingStarted.md, NOTICE, Utilities/Doxygen/doxygen.config.in
As discussed with 199c38ed11da9fad4608d064767beaf0fd70efc8
925eb8fe771ae5edde2d2f4341c317dc11a9b96a
use the simpler and more widely known name 'Insight Toolkit (ITK)'.
=> DOC: Consistent naming for 'Insight Toolkit (ITK)'

Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.h, Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.hxx, Modules/Filtering/BiasCorrection/test/itkN4BiasFieldCorrectionImageFilterTest.cxx
=> N4minor optimization

Modules/Core/Mesh/wrapping/test/CMakeLists.txt, Wrapping/Generators/Python/Tests/CMakeLists.txt, Wrapping/Generators/Python/Tests/extras.py, Wrapping/Generators/Python/itkExtras.py, Wrapping/Generators/Python/itkTemplate.py
=> itk.meshread, itk.meshwrite

Modules/ThirdParty/GDCM/UpdateFromUpstream.sh
Utilities/C99 directory has been removed since :
d77e24c4a3e0 Remove C99 compat
=> ENH: Remove Utilities/C99 from GDCM sync script

Modules/IO/GDCM/src/itkGDCMImageIO.cxx
This [switch](https://github.com/InsightSoftwareConsortium/ITK/blob/970e7fa9ce42f9d3da78c47213a320abc382d613/Modules/IO/GDCM/src/itkGDCMImageIO.cxx#L514) is useless, forced Tag is (0028,0030), so entry is always from dictionary
`{0x0028,0x0030,VR::DS,VM::VM2,"Pixel Spacing","PixelSpacing",false },`
this switch was simply copy/pasted, s. [here](https://github.com/InsightSoftwareConsortium/ITK/blob/970e7fa9ce42f9d3da78c47213a320abc382d613/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageHelper.cxx#L1321) and dictionary lookup above is useless too, it is loop.
**Edit**:
`m_El.SetLength(entry.GetVM().GetLength() * entry.GetVR().GetSizeof())` is from dictionary and always 2 * 8 = 16.
=> STYLE: remove unused code from 168c457 in GDCM IO

Modules/Core/Common/test/itkMemoryProbesCollecterBaseTest.cxx, Modules/Core/ImageFunction/test/itkCentralDifferenceImageFunctionOnVectorTest.cxx, Modules/Core/SpatialObjects/include/itkTubeSpatialObject.hxx, Utilities/Maintenance/clang-format.bash
I guess the tube SO change was in a PR parallel to the style change, thus was missed by the new style. The other changes might be due to difference in versions 8.0.0 and 8.0.1 (which I have).
=> Clang format

Modules/Segmentation/RegionGrowing/include/itkConfidenceConnectedImageFilter.hxx
Improved the performance of `ConfidenceConnectedImageFilter` by
removing its local `MeanImageFunction` and `SumOfSquaresImageFunction`
variables, and doing the calculation of mean and sum of squares by using `Experimental::ShapedImageNeighborhoodRange`.
Using `ShapedImageNeighborhoodRange` this way will improve the
performance of `GenerateData()`, because the range does not do any
dynamic memory allocation, and the calculation of the mean and the sum
of squares of neighborhood pixels happens in one and the same iteration.
=> PERF: Use ShapedImageNeighborhoodRange in ConfidenceConnectedImageFilter

CMake/ITKModuleHeaderTest.cmake, Modules/Bridge/VtkGlue/wrapping/CMakeLists.txt, Wrapping/Generators/Python/CMakeLists.txt
Remove conditional code that is no longer valid for
old support of python 2.6.
=> STYLE: Only python > 3.5 is supported

Modules/IO/GDCM/include/itkGDCMImageIO.h
=> ENH: Mark deprecated GDCM API as ITK legacy remove

Modules/Numerics/Statistics/test/itkStatisticsAlgorithmTest.cxx
To fix the badge indicating build status of the project:
https://dev.azure.com/itkrobotbatch/ITK.Coverage/_build/latest?definitionId=3&branchName=master
=> ENH: disable test whose failure is not reproducible

Modules/IO/GDCM/include/itkGDCMImageIO.h
ITK headers need to be included before ITK_LEGACY_REMOVE is used for
consistent class declaration.
closes #1362 
=> BUG: Fix GDCMImageIO define order

Modules/Remote/Montage.remote.cmake, Modules/Remote/SphinxExamples.remote.cmake
=> ENH: update remote modules Montage and Examples

.circleci/config.yml
Python 2.7 is deprecated in 2020.
=> ENH: Update CircleCI docker image to python:3.7-stretch

Modules/Core/Common/include/itkNeighborhoodAlgorithm.hxx
`ImageBoundaryFacesCalculator` now reuses the region retrieved with its
first `GetBufferedRegion()` call, instead of calling this `virtual`
member function three times.
This commit also reduces the scope of some local  variables, removes the
`fRegion` variable, and avoids repeated `GetIndex()` and `GetSize()`
calls.
=> STYLE: Remove repeated GetBufferedRegion() calls from ImageBoundaryFaces

.github/FUNDING.yml
ENH: add NumFOCUS github sponsors button (recurring donations only)
This feature is launching today at GitHub Universe!
More info on sponsor buttons: https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository
cc @thewtex
=> ENH: Create FUNDING.yml

Modules/Core/Common/wrapping/itkStreamingImageFilter.wrap
Re-creation of #1427 because I could not reopen it.
=> ENH: wrap StreamingImageFilter for vector images

Modules/Core/Common/src/itkPoolMultiThreader.cxx
=> BUG: Wait for all threads when abort or exception occurs

Modules/Numerics/Statistics/wrapping/CMakeLists.txt, Modules/Numerics/Statistics/wrapping/itkKdTreeBasedKmeansEstimator.wrap, Modules/Numerics/Statistics/wrapping/itkKdTreeGenerator.wrap, Modules/Numerics/Statistics/wrapping/itkWeightedCentroidKdTreeGenerator.wrap
KdTreeBasedKmeansEstimator, KdTreeGenerator,
and WeightedCentroidKdTreeGenerator.
Discussed: https://discourse.itk.org/t/kdtree-python/2427
=> ENH: Wrap KdTree classes

Modules/Remote/BoneEnhancement.remote.cmake
Some of the filters are now streamable,
greatly reducing main filter's memory consumption.
=> ENH: update BoneEnhancement remote module

Modules/Core/Common/src/itkPoolMultiThreader.cxx
Replaces the macro's `ExceptionHandlingPrologue`, `WrapExceptionHandling`,
and `ExceptionHandlingEpilogue` by a class, `ExceptionHandling`, aiming
to improve code readability and maintainability.
Bradley @blowekamp encouraged pursuing such a "macro free" approach,
during the discussion following the merge of pull request #1434, "BUG:
Wait for all threads when abort or exception occurs".
=> STYLE: Replace macro's in PoolMultiThreader by ExceptionHandling class

Modules/IO/GDCM/test/itkGDCMImageReadWriteTest.cxx
=> ENH: support testing multi-frame DICOMs (3D images)

Modules/IO/HDF5/src/itkHDF5ImageIO.cxx
This commit removes the local dynamically allocated buffer `buf` from
both `HDF5ImageIO::WriteVector` and `HDF5ImageIO::ReadVector`, to
simplify the code, improve the performance, and exception safety.
It uses `std::unique_ptr` instead of a raw pointer in five other
`HDF5ImageIO` member functions, just to improve coding style and
exception safety.
This commit fixes eight warning C26407 messages from VS2017 Code Analysis:
> Prefer scoped objects, don't heap-allocate unnecessarily
Follow-up to pull request #1424, "PERF: Do not allocate buffer in
HDF5TransformIOTemplate::WriteParameters", Nov 18, 2019, SHA-1 f25d63a1ba565f457d66b0102cd054e1f75f1660
=> PERF: Do not allocate buffer in HDF5ImageIO WriteVector and ReadVector

Modules/Filtering/Deconvolution/test/itkRichardsonLucyDeconvolutionImageFilterTest.cxx
=> ENH: optionally write intermediate image in test

Modules/Filtering/Smoothing/include/itkDiscreteGaussianImageFilter.h, Modules/Filtering/Smoothing/test/itkDiscreteGaussianImageFilterTest.cxx
* add sigma setters and getters to DiscreteGaussianImageFilter
* make second template parameter equal to first one by default
=> ENH: DiscreteGaussian filter is compatible with SmoothingRecursive one

Modules/Core/Common/include/itkMath.h
Found by UBSan.
Removed a previous attempt to fix this (207a801f2).
Use the technique described in the already-referenced blog post to avoid overflow by first checking if the two floats being compared have different signs.
This will fix several unit test failures, example: itkDiscreteGaussianDerivativeImageFilterTest
=> BUG: Fixed signed overflow in float ULP comparisons

Modules/ThirdParty/GoogleTest/src/CMakeLists.txt
Removes Threads::Threads form exported libraries dependencies, to
simply exports.
Addresses #1502.
=> COMP: Disable GTest using threads

Modules/IO/GDCM/test/Baseline/itkGDCMImageReadWriteTest_RGB.mha.md5
Resulting from ./Utilities/Maintenance/ContentLinkSynchronization.sh
=> ENH: Update content links

CONTRIBUTING.md
=> DOC: Document how to re-run tests with a PR comment

Modules/Remote/Cuberille.remote.cmake
A commit was recently merged into the Cuberille remote module which makes it possible to save adjacent pixel data as CellData when extracting a mesh.  This commit bumps the remote Cuberille git commit, to make this functionality available in the main ITK trunk.
-  :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
-  :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
-  :no_entry_sign: Adds the License notice to new files.
-  :no_entry_sign: Adds Python wrapping.
-  :no_entry_sign: Adds tests and baseline comparison (quantitative).
-  :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master …
=> ENH: Bump Cuberille Commit Hash

Documentation/Maintenance/Release.md, Utilities/Maintenance/AuthorsChangesSince.py, Utilities/Maintenance/authors-since.py
To recognize contributors in release notes.
=> ENH: Add script to identify release authors and generate the changelog

Modules/Core/Common/test/itkImageIORegionGTest.cxx, Modules/Filtering/Smoothing/include/itkDiscreteGaussianImageFilter.h
=> STYLE: Updates for ImageIORegionGTest, DiscreteGaussianImageFilter

Modules/Core/Transform/include/itkTransformBase.h
Required to compile [ITKElastix](https://github.com/InsightSoftwareConsortium/ITKElastix).
=> COMP: expose TransformCategoryType under LEGACY

CMake/ITKModuleDoxygen.cmake, CMake/ITKModuleHeaderTest.cmake, CMakeLists.txt, Modules/ThirdParty/GoogleTest/src/itkgoogletest/googletest/cmake/internal_utils.cmake, Wrapping/Generators/SwigInterface/CMakeLists.txt
This patch consolidates the searching for python components
into the main CMakeLists.txt file.
=> Python search refinement

Wrapping/Generators/Python/itkBase.py
Remove unused import inspect in Wrapping/Generators/Python/itkBase.py
=> STYLE: Remove unused import inspect

Wrapping/Generators/SwigInterface/igenerator.py
id is a Python built-in function.
=> STYLE: Do not use id as variable in igenerator.py

Examples/RegistrationITKv4/DeformableRegistration15.cxx
=> ENH: update example to support non-overlapping images

Modules/Filtering/ImageGrid/test/CMakeLists.txt, Modules/Filtering/ImageGrid/test/itkExpandImageFilterTest2.cxx
=> ENH: Added explicit test of VectorImage with ExpandImageFilter

Modules/Segmentation/ConnectedComponents/include/itkRelabelComponentImageFilter.hxx, Modules/Segmentation/ConnectedComponents/test/CMakeLists.txt, Modules/Segmentation/ConnectedComponents/test/itkRelabelComponentImageFilterGTest.cxx
This issue was first reported in SimpleITK/SimpleITK#951
=> Fix relabel component no sort size

README.md
=> DOC: Add Citation section to README

Modules/Remote/Cuberille.remote.cmake
Recent patches to ITKCuberille have addressed a longstanding issue
which caused failures when generating itk::QuadEdgeMesh objects.
This commit updates the git commit hash, bringing this bugfix into
the master branch if ITK.
- …
=> BUG: Bump Cuberille Commit Hash

Modules/Filtering/Convolution/include/itkConvolutionImageFilterBase.h
=> BUG: Restore enum typedef name Convolution and Deconvolution filters

Documentation/ITK5MigrationGuide.md
Update of ITK5MigrationGuide.md to document new behaviour of NiftiImageIO wrt Analyze file format. Related to InsightSoftwareConsortium/ITK#1557
=> DOC: updated ITK5MigrationGuide on Analyze format support

CONTRIBUTING.md
Scraped from https://github.com/nipy/nibabel/blob/master/.github/CONTRIBUTING.md
@jhlegarreta I was following the links you sent, and this stood out. Kudos to the nibabel community.
=> DOC: Add welcome message to CONTRIBUTING.md

NOTICE, README.md
For more details, see the commit message in:
344e9bc58e69ed921f540c67d87dbb66fee4c466
https://github.com/InsightSoftwareConsortium/ITK/pull/1598
=> DOC: Update NOTICE and README.md copyright remarks

Modules/IO/PhilipsREC/include/itkPhilipsRECImageIO.h
Fixes #1629 when legacy code is disabled.
=> BUG: Incorrect type specified for enumeration

Modules/Bridge/VtkGlue/include/itkImageToVTKImageFilter.h
=> DOC: update example links in ImageToVTKImageFilter

.zenodo.json
Add `Hernandez-Cerdan, Pablo` orcid
=> DOC: Update .zenodo.json

Modules/Remote/PolarTransform.remote.cmake
Make use of PR to ITKPolarTransform: 
https://github.com/InsightSoftwareConsortium/ITKPolarTransform/pull/13
=> ENH: updating remote module PolarTransform

Modules/Video/BridgeOpenCV/src/itkOpenCVVideoIO.cxx
Updating variable references to new superclass member variable name
Updating enum names to match new style
=> COMP: Fixing compilation of ITK/OpenCV video bridge

CMake/ITKModuleRemote.cmake, Modules/Remote/AnalyzeObjectMapIO.remote.cmake, Modules/Remote/CMakeLists.txt, Modules/Remote/Deprecated/NeuralNetworks.remote.cmake, Modules/Remote/README.md, Modules/Remote/SphinxExamples.remote.cmake
SEE https://discourse.itk.org/t/remote-module-grading-ranking-system-needed/2750
Resolves issue #1655
=> ENH: Provide rating scale for ITK Remote modules

.zenodo.json
=> DOC: Add Lydia Ng's ORCID iD and affiliation

Modules/Remote/RTK.remote.cmake
This PR stems from SimonRit/RTK#313. Unfortunately, it seems that this PR will not solve the issue but it will at least set the current RTK status. We will do our best to fill the missing 4% code coverage of RTK to reach level 4 before ITK v5.1 is tagged because RTK cannot be easily compiled right now. I appreciate your efforts to improve ITK code and its remote modules but you are setting the bar quite high!
=> ENH: update RTK and set MODULE_COMPLIANCE_LEVEL to 3

Modules/IO/ImageBase/include/itkImageSeriesReader.hxx
BUG: Error happens when ImageSeriesReader is called with a single input file, then 
this->m_NumberOfDimensionsInImage = TOutputImage::ImageDimension
=> BUG: accessing array out of bounds in ImageSeriesReader

Modules/Core/Common/include/itkProgressReporter.h, Modules/Core/Common/include/itkTotalProgressReporter.h, Modules/Core/Common/src/itkTBBMultiThreader.cxx
The progress reporters only check for the AbortGenerateData flag, when
a reportable chuck is completed. When regions or chucks is smaller
than a reportable chunk, the abort flag must be checked.
This patch addresses new failing tests on the dashboard:
https://open.cdash.org/testSummary.php?project=2&name=itkAbortProcessObjectTest&date=2020-03-04
=> BUG: Explicitly check abort flag in TBB multi-threader

Modules/Core/Common/src/itkPoolMultiThreader.cxx
The progress reporter's CompletedPixel method may throw an
ProgressAborted exception. These call are now wrapped in the
ExceptionHandler class to catch and rethrow exceptions.
=> BUG: PoolMultiThreader catch and re-throw exceptions from progress

Modules/Remote/TubeTK.remote.cmake
This pull request adds ITKTubeTK as a remote module to ITK.  Compliance level is 3.
The github for ITKTubeTK is at:
[https://github.com/KitwareMedical/ITKTubeTK](https://github.com/KitwareMedical/ITKTubeTK)
The dashboard for ITKTubeTK at:
[https://open.cdash.org/index.php?project=TubeTK](https://open.cdash.org/index.php?project=TubeTK)
There are numerous publications and such that cover its capabilities.
The major features are demonstrated in Jupyter Notebooks in the ITKTubeTK/examples directory.
=> ENH: Add TubeTK as a remote module for ITK

Modules/Remote/SimpleITKFilters.remote.cmake
Update compliance level to 3.
Move repository to InsightSoftwareConsortium to easy community
maintenance.
Update git hash for ITK v5.1rc2 updates.
=> ENH: Update SimpleITKFilters remove module

Wrapping/Generators/Python/PyBase/pyBase.i, Wrapping/Generators/Python/Tests/PythonTypemapsTest.py
=> BUG: Implement __eq__ for sequence objects, e.g. itk.Size

Modules/Core/Common/include/itkImageAlgorithm.hxx, Modules/Core/Common/test/itkImageTest.cxx, Modules/Filtering/ImageGrid/include/itkResampleImageFilter.h, Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx, Modules/Filtering/ImageGrid/test/CMakeLists.txt, Modules/Filtering/ImageGrid/test/itkResampleImageTest8.cxx
Allow Rectangular Transform Type in ResampleImage Filter. Fixes #1512.  
=> ENH: Allow Transform with different Input and Output Dimensions.

Utilities/Doxygen/doxygen.config.in
=> COMP: fix Doxygen Illegal command in title section

.zenodo.json
Thanks for including modest contributors like me.
- [ x ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ x ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
=> DOC: add affiliation and orcid for Simon Rit

Modules/Filtering/AnisotropicSmoothing/include/itkCurvatureAnisotropicDiffusionImageFilter.h, Modules/Filtering/AnisotropicSmoothing/include/itkGradientAnisotropicDiffusionImageFilter.h, Modules/Filtering/DistanceMap/include/itkDanielssonDistanceMapImageFilter.h, Modules/Filtering/DistanceMap/include/itkSignedDanielssonDistanceMapImageFilter.h, Modules/Filtering/ImageFeature/include/itkLaplacianImageFilter.h
=> DOC: Add brief description to image filters

.zenodo.json
=> DOC: Add ORCID for Davis Vigneault

Modules/Filtering/ImageStatistics/include/itkLabelStatisticsImageFilter.h, Modules/Filtering/ImageStatistics/include/itkMinimumMaximumImageFilter.h, Modules/Numerics/Statistics/include/itkImageToHistogramFilter.h
The wrapping system is not correctly supporting "using
Superclass::SomeMethod", so we create a function to enable wrapping of
the Set/GetNumberOfStreamDivision methods.
Closes #977.
=> BUG: Use function call to change access of superclass methods

CMake/ITKModuleRemote.cmake
When the specified ITK remote module git tag string is "" then, don't
perform any git update. This allows work and commits to be done in the
ITK repository, with out the changes being reverted to a prior commit.
=> ENH: When REMOTE_GIT_TAG_{name} is empty do not update remote

CMake/ITKModuleRemote.cmake
Bug was introduced by d67ae98 due to an incomplete search and replace. @blowekamp  @hjmjohnson 
=> BUG: fix manual definition of git tag for remote modules

Modules/Core/Common/include/itkProgressReporter.h, Modules/Core/Common/include/itkTotalProgressReporter.h
Fix typos in progress reporter classes.
=> DOC: Fix typos in progress reporter classes

Modules/Remote/SimpleITKFilters.remote.cmake
$ git log --oneline d67058..3344aa
3344aa9 ENH: Throw exception when desired orientation is invalid.
a0b9eca ENH: Refactor enums into DICOMOrientation class
2fd3893 ENH: Add test demonstrating behavior of INVALID enum on execution
9240a0f Rename SetDesiredCoordinateDirection by string to ...Orientation
6d6c7a9 Fix up documentation and test compilation
24bc712 Update documentation and clean up unused code
455c241 Rename Given.. to InputCoordinateOrientation
9a74379 Add testing for DICOMOrientImageFilter
a3216d6 Refactoring of OrientImageFilter into DICOMOrientImageFilter
ef6dcac Renamed to DICOMOrientImageFilter
94b56ec Import existing itkOrientImageFilter
243bcab Restore atoi usage in test
e7bc846 Configure AZP to build pull requests
61d6ee1 Update AZP to macos-10.14
d8fac5c STYLE: Apply …
=> ENH: Update SimpleITKFilters remote module

Modules/Core/Common/include/itkOffset.h, Modules/Filtering/Convolution/include/itkNormalizedCorrelationImageFilter.h, Modules/Filtering/ImageFeature/include/itkLaplacianRecursiveGaussianImageFilter.h, Modules/Filtering/ImageGradient/include/itkGradientImageFilter.h, Modules/Filtering/ImageGradient/include/itkGradientRecursiveGaussianImageFilter.h, Modules/Filtering/Smoothing/include/itkMedianImageFilter.h, Modules/IO/ImageBase/include/itkImageIOBase.h, Modules/Segmentation/Voronoi/include/itkVoronoiDiagram2D.h, Modules/Segmentation/Watersheds/include/itkMorphologicalWatershedImageFilter.h
=> COMP: Fix typo with Doxygen sphinx macro

Modules/Remote/TubeTK.remote.cmake
Two major fixes in this bump:
TubeTK was missing specification of ArrayFire paths needed for
outside application to compile if ArrayFire was turned on when
ITK/TubeTK was compiled.
TubeTK attempted to install a file that is no longer included with
TubeTK
TubeTK can now build its applications. Requires building ITK with
TubeTK, building SlicerExecutionModel (which depends on ITK), and
then re-building ITK with it pointing to the build of
SlicerExecutionModel.   Ugly, but it works.
=> BUG: Bump TubeTK to fix use of ArrayFire and installation command

Modules/Filtering/Thresholding/include/itkHistogramThresholdImageFilter.h, Modules/Filtering/Thresholding/include/itkHistogramThresholdImageFilter.hxx, Modules/Filtering/Thresholding/include/itkOtsuThresholdImageFilter.h
Use the VerifyPreconditions method to check that the calculator is set
( in the base class ) and that it is a OtsuThresholdCalculator is the
OtsuThresholdImageFilter class.
=> BUG: Check if calculator is proper type

Modules/Filtering/Thresholding/include/itkIntermodesThresholdImageFilter.h
Use the parent class's calculator and override GenerateDate method to
update the derived calculators ivars. Store the calculator parameters
as filter ivar, with correct filter modified time management.
Closes #1720.
=> BUG: Use one calculator in ItermodesThresholder

Wrapping/Generators/Python/itkExtras.py
A simpler check that requires a 'c' dim explicitly.
=> ENH: Improve is_vector identification in image_from_xarray

README.md
Following website refactoring.
=> DOC: Update ITKBibliography.bib link

Modules/Remote/TubeTK.remote.cmake
This new version of TubeTK features
* Directory structure and build process mirrors ITKModuleTemplate
* Builds without special requirements beyond -DModule_TubeTK=On
* Does not rely on LibSVM or RandomForest - those options are now
eliminated because they did not add functionality
* Improved example scripts
* Only builds one library (TubeTK) - eliminating other TubeTKLibs
enables  packaging, installation, and usage outide of ITK
=> ENH: Upgrade version of TubeTK

Modules/Segmentation/ConnectedComponents/include/itkRelabelComponentImageFilter.hxx
Provide more expressive comment for the nature of the error
thrown.
=> DOC: Improve diagnostic message for exception

Documentation/Maintenance/Release.md, Utilities/Maintenance/AuthorsChangesSince.py
Visual Studio 2019 now comes with CMake.
=> DOC: Release process updates for v5.1rc03

Modules/Core/Common/src/itkTBBMultiThreader.cxx
See TBB Outdated and Redundant API documentation
https://software.intel.com/en-us/node/841353
Use global_context as a recommended replacement.
=> ENH: Remove use of deprecated, redundant interface

Modules/Bridge/NumPy/include/itkPyBuffer.h, Modules/Bridge/NumPy/include/itkPyBuffer.hxx, Modules/Bridge/NumPy/wrapping/PyBuffer.i.in, Modules/Bridge/NumPy/wrapping/test/itkPyBufferTest.py, Wrapping/Generators/Python/PyBase/pyBase.i
@brad-t-moore please try this branch re: #1757 .
=> Image view base

Wrapping/Generators/Python/itkExtras.py
To address:
UnboundLocalError: local variable 'ImageType' referenced before
assignment
with Python 3.7.
=> COMP: UnboundLocalError in _GetImageFromArray

Modules/Segmentation/Watersheds/include/itkWatershedSegmentTree.h
std::binary_function was deprecated in C++11 and removed in C++17. It only added typedefs. Since they were unused, it compiles fine without them. When building code enabling the latest C++ standards, the prior code would not compile.
=> COMP: Remove deprecated/removed std::binary_function

Documentation/ITK5MigrationGuide.md
Closes #1743
Co-authored-by: Stephen R. Aylward <stephen.aylward@kitware.com>
=> DOC: Document how to handle operator<< link errors from enum libraries

Modules/Filtering/LabelMap/include/itkBinaryReconstructionByDilationImageFilter.h, Modules/Filtering/LabelMap/include/itkBinaryReconstructionByDilationImageFilter.hxx, Modules/Filtering/LabelMap/include/itkBinaryReconstructionByErosionImageFilter.h, Modules/Filtering/LabelMap/include/itkBinaryReconstructionByErosionImageFilter.hxx, Modules/Filtering/LabelMap/include/itkBinaryReconstructionLabelMapFilter.h, Modules/Filtering/LabelMap/include/itkBinaryReconstructionLabelMapFilter.hxx, Modules/Filtering/MathematicalMorphology/include/itkReconstructionImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkReconstructionImageFilter.hxx
The filters had methods such as GetMarkerImage manually written. These
are mapped to named inputs and marked as required. This enabled the
use of standard Set/Get filter input macros for named inputs.
=> ENH: Use named pipeline inputs for morphological reconstruction

Modules/Remote/BioCell.remote.cmake, Modules/Remote/LabelErodeDilate.remote.cmake, Modules/Remote/MinimalPathExtraction.remote.cmake, Modules/Remote/RLEImage.remote.cmake, Modules/Remote/SimpleITKFilters.remote.cmake, Modules/Remote/SphinxExamples.remote.cmake, Modules/Remote/TotalVariation.remote.cmake
=> ENH: updating remote modules to latest versions

Wrapping/Generators/Python/Tests/extras.py, Wrapping/Generators/Python/itkExtras.py
For conversion to/from and itk.Image and a vtk.vtkImageData.
=> ENH: Add itk.vtk_image_from_image and itk.image_from_vtk_image

Modules/Core/SpatialObjects/wrapping/itkArrowSpatialObject.wrap
Wrapping of itk::ArrowSpatialObject and itk::CastSpatialObjectFilter
should be consistent. The warning was
itkCastSpatialObjectFilter: warning(4): ITK type not wrapped, or currently not known: itk::SmartPointer< itk::ArrowSpatialObject< 1 > >
=> COMP: fix itk::ArrowSpatialObject warning when compling 1D wrappings

Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshToQuadEdgeMeshFilter.h
=> STYLE: Prefer Early Return

Modules/Core/Common/include/itkQuadrilateralCell.h, Modules/Core/Common/include/itkTriangleCell.h, Modules/Core/Transform/include/itkTransform.h, Modules/Core/Transform/include/itkTransformBase.h
eb8ce3c6195b13878721ffc5475e1f32e183843a caused a link error with AppleClang 7 and 8.
It in turn was a follow up to:
af537fc3a75835475649d7fe9850000c4b6e0d46 and 1ad4e98c92e97b5b0aa16137ce1dfb4796eab5c1
which were working around similar link errors with old versions of GCC.
Since using =default doesn't win us so much, just don't use it with any version of GCC/clang in these four cases.
=> COMP: Fixed link error with old versions of AppleClang

CMake/itkOpenCL.cmake, Modules/Core/Common/include/itkMacro.h, Modules/Core/GPUCommon/include/itkGPUImageOps.h, Modules/Core/GPUCommon/include/itkGPUReduction.h, Modules/Core/GPUFiniteDifference/include/itkGPUDenseFiniteDifferenceImageFilter.h, Modules/Filtering/GPUAnisotropicSmoothing/include/itkGPUGradientNDAnisotropicDiffusionFunction.h, Modules/Filtering/GPUAnisotropicSmoothing/include/itkGPUScalarAnisotropicDiffusionFunction.h, Modules/Filtering/GPUImageFilterBase/include/itkGPUCastImageFilter.h, Modules/Filtering/GPUImageFilterBase/include/itkGPUNeighborhoodOperatorImageFilter.h, Modules/Filtering/GPUSmoothing/include/itkGPUMeanImageFilter.h, Modules/Filtering/GPUThresholding/include/itkGPUBinaryThresholdImageFilter.h, Modules/Registration/GPUPDEDeformable/include/itkGPUDemonsRegistrationFunction.h, Modules/Registration/GPUPDEDeformable/include/itkGPUPDEDeformableRegistrationFilter.h
Patch proposed by @Neumann-A. Closes #1381.
=> COMP: fix GPU compile errors when building as DLLs

Modules/Core/Mesh/wrapping/itkRegularSphereMeshSource.wrap, Modules/Core/Mesh/wrapping/itkSphereMeshSource.wrap, Modules/Core/Mesh/wrapping/test/CMakeLists.txt
This patch adds python wrappers for the itk::RegularSphereMeshSource
and itk::SphereMeshSource classes.  Additionally, tests are added
to ensure that the wrapped classes instantiate without error.
=> ENH: Add Python Wrappers for Mesh Source Classes

Testing/Data/ITKData.readme, Testing/Data/README.md
Transition `Testing/Data` `README` to Markdown syntax.
=> STYLE: Transition `Testing/Data` `README` to Markdown

Modules/Filtering/ImageStatistics/include/itkLabelStatisticsImageFilter.h, Modules/Filtering/ImageStatistics/include/itkMinimumMaximumImageFilter.h, Modules/Filtering/ImageStatistics/include/itkStatisticsImageFilter.h, Modules/Numerics/Statistics/include/itkImageToHistogramFilter.h
=> Fix set number of stream divisions const

Modules/Filtering/ImageNoise/include/itkAdditiveGaussianNoiseImageFilter.h, Modules/Filtering/ImageNoise/include/itkAdditiveGaussianNoiseImageFilter.hxx, Modules/Filtering/ImageNoise/include/itkSaltAndPepperNoiseImageFilter.h, Modules/Filtering/ImageNoise/include/itkSaltAndPepperNoiseImageFilter.hxx, Modules/Filtering/ImageNoise/include/itkShotNoiseImageFilter.h, Modules/Filtering/ImageNoise/include/itkShotNoiseImageFilter.hxx, Modules/Filtering/ImageNoise/include/itkSpeckleNoiseImageFilter.h, Modules/Filtering/ImageNoise/include/itkSpeckleNoiseImageFilter.hxx
=> BUG: Disable dynamic threading in noise filter.

Modules/ThirdParty/VNL/src/vxl/vcl/vcl_compiler.h
Change-Id: Ie2ad7c15a9166aa553c92a1075f7e6cc7aa05155
=> COMP: added vcl compiler detection for GCC 10.x

Modules/Remote/Cuberille.remote.cmake
Cuberille.remote.cmake has been updated to indicate improvements in
style, continuous integration, and testing coverage since the last
review.  Additionally, the git hash has been bumped to the most
recent commit.
=> ENH: Review Cuberille Remote Module Compliance

Modules/Core/QuadEdgeMesh/include/itkGeometricalQuadEdge.hxx
This patch causes an assertion to fail in debug mode when a filter
attempts to construct a QEMesh with invalid geometry.  This should
make testing clearer and more robust.  In release mode, this falls
back to a no-op, so code built for release should not be affected.
=> ENH: Assert in Debug Mode

Modules/Core/Transform/include/itkCompositeTransform.hxx, Modules/Core/Transform/test/itkCompositeTransformTest.cxx
Incorrect integer reverse iteration caused incorrect indexing when the
number of transform was zero. Fixed by changing to using reverse iterators.
=> BUG: Fix segfault with empty CompositeTransforms

Modules/Core/Transform/include/itkCompositeTransform.hxx, Modules/Core/Transform/test/itkCompositeTransformTest.cxx
=> Fix more segmentation faults related to empty composite transform

Modules/Core/SpatialObjects/test/itkCastSpatialObjectFilterTest.cxx
Closes #1619
This leak has been identified by the nightly valgrind.
=> BUG: Address memory leak in CastSpatialOpbjectTest

Modules/Core/Common/include/itkConceptChecking.h
=> DOC: fix description of Concept::SameDimensionOrMinusOne(OrTwo)

Modules/Filtering/QuadEdgeMeshFiltering/include/itkQuadEdgeMeshDecimationCriteria.h, Modules/Filtering/QuadEdgeMeshFiltering/include/itkSmoothingQuadEdgeMeshFilter.h, Modules/Filtering/QuadEdgeMeshFiltering/test/itkQuadricDecimationQuadEdgeMeshFilterTest.cxx, Modules/Filtering/QuadEdgeMeshFiltering/test/itkSmoothingQuadEdgeMeshFilterTest.cxx, Modules/Filtering/QuadEdgeMeshFiltering/test/itkSquaredEdgeLengthDecimationQuadEdgeMeshFilterTest.cxx
1.  Add missing Boolean macros where appropriate in the
QuadEdgeMeshFiltering module.
2.  Modify existing tests to exercise these macros.
3.  Update the associated tests to use ITK testing macros.
=> ENH: Add Missing Boolean Macros in QEFilters

Modules/Filtering/QuadEdgeMeshFiltering/test/itkSquaredEdgeLengthDecimationQuadEdgeMeshFilterTest.cxx
Sorry @DVigneault , I merged the previous patch pre-maturely.
=> COMP: Unused tc in SquaredEdgeLengthDecimationQuadEdgeMeshFilterTest

Modules/Remote/TubeTK.remote.cmake
* Update baselines
* Remove unused application
* Add new WriteTubesToPolyData method
=> BUG: Bump TubeTK

Modules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceImageFilter.h
…rse.itk.org/t/itkgpudemonsregistrationfiltertest-fails/3160)
=> BUG: Fix itkGPUDemonsRegistrationFilterTest fails

Modules/Core/Transform/include/itkCompositeTransform.hxx
=> STYLE: remove extraneous semi-colon after bracket

Modules/Registration/Common/wrapping/itkMatchCardinalityImageToImageMetric.wrap
Added a wrap file for ITK Match Cardinality Image to Image Metric.
Added newline at the end of file.
=> ENH: improve wrapping architecture

Modules/Filtering/QuadEdgeMeshFiltering/include/itkDelaunayConformingQuadEdgeMeshFilter.hxx, Modules/Filtering/QuadEdgeMeshFiltering/itk-module.cmake, Modules/Filtering/QuadEdgeMeshFiltering/test/CMakeLists.txt, Modules/Filtering/QuadEdgeMeshFiltering/test/itkDelaunayConformingQuadEdgeMeshFilterTest.cxx
=> BUG: Delaunay segfault

Examples/Filtering/BilateralImageFilter.cxx
For Information on the Issue see the Issue #146 in InsightSoftwareConsortium/ITKSoftwareGuide.
@jhlegarreta 
The issue cannot be closed automatically because it has been transferred to ITKSoftwareGuide even though the file to be corrected is part of the InsightSoftwareConsortium/ITK repository.
- [ x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ x] Added test (or behavior not changed)
- [ x] Updated API documentation (or API not changed)
- [ x] Added …
=> DOC: fixes issue in itkSoftwareGuide #146

Modules/ThirdParty/GDCM/src/gdcm/.gitattributes, Modules/ThirdParty/GDCM/src/gdcm/CMakeLists.txt, Modules/ThirdParty/GDCM/src/gdcm/Source/Common/gdcmDirectory.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/Common/gdcmSystem.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/Common/gdcmSystem.h, Modules/ThirdParty/GDCM/src/gdcm/Source/Common/gdcmTesting.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary/gdcmPrivateDefaultDicts.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition/gdcmBasicOffsetTable.h, Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition/gdcmExplicitDataElement.txx, Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition/gdcmImplicitDataElement.txx, Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition/gdcmReader.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition/gdcmWriter.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/InformationObjectDefinition/gdcmDefs.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmAnonymizer.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmDataSetHelper.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmFileExplicitFilter.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageHelper.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageWriter.h, Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmOverlay.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmPixelFormat.h, Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmStringFilter.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmStringFilter.h, Modules/ThirdParty/GDCM/src/gdcm/Utilities/gdcmjpeg/CMakeLists.txt, Modules/ThirdParty/GDCM/src/gdcm/Utilities/gdcmjpeg/jdpred.c, Modules/ThirdParty/GDCM/src/gdcm/Utilities/gdcmjpeg/jlossls.h, Modules/ThirdParty/GDCM/src/gdcm/Utilities/gdcmjpeg/jpegcmake.h.in
Fixes a bogus decompression for valid JPEG Lossless 16bits images.
@hjmjohnson @dzenanz @seanm
=> ENH: Update to GDCM 3.0.7

Modules/Core/Common/wrapping/itkExtractImageFilter.wrap, Modules/Core/Common/wrapping/itkInPlaceImageFilterA.wrap
=> BUG: Wrap ExtractImageFilter for UL

Modules/Filtering/ImageFilterBase/include/itkRecursiveSeparableImageFilter.h, Modules/Filtering/Smoothing/include/itkRecursiveGaussianImageFilter.h
This PR just fills in some missing reference information in the documentation to `RecursiveGaussianImageFilter`. 
To verify this is the right reference, I checked that the values in the code cited below match those in Table 3 of the paper:
https://github.com/InsightSoftwareConsortium/ITK/blob/ccf8132f1604ecf2937e92a1c3f7e3673c3137ff/Modules/Filtering/Smoothing/include/itkRecursiveGaussianImageFilter.hxx#L102-L119
=> DOC: update references for recursive Gaussian filters

.gitignore
=> MNT: Added .vs to .gitignore

Modules/Core/Common/include/itkCommand.h, Modules/Core/Common/include/itkObject.h, Modules/Core/Common/src/itkCommand.cxx, Modules/Core/Common/src/itkObject.cxx, Modules/Core/Common/test/itkCommandObserverObjectTest.cxx
=> Add lambda function command

.gitignore, Modules/Video/BridgeOpenCV/include/itkOpenCVImageBridge.h, Modules/Video/BridgeOpenCV/include/itkOpenCVImageBridge.hxx
BUG: Fix Mat to Image conversions for OpenCV 4.x; add support for int32
This fixes issue https://github.com/InsightSoftwareConsortium/ITK/issues/1651 in a lasting manner by introducing specific implementations for functions CVMatToITKImage and ITKImageToCVMat that no longer depend on the legacy C API while avoiding unnescessary memory copies.
This also fixes issue https://github.com/InsightSoftwareConsortium/ITK/issues/1906 by adding support for int pixel type (IPL_DEPTH_32S in the legacy C API, CV_32S in the C++ API) for both OpenCV legacy C and C++ APIs.
In addition, exceptions for pixel/component type mismatches and impossible conversions were added to both IplImageToITKImage and CVMatToITKImage functions. Some extra functions had to be introduced to ensure minimal code …
=> Opencv bridge update

Wrapping/Generators/Python/Tests/extras.py, Wrapping/Generators/Python/itkExtras.py
=> BUG: Empty image support in image_from_xarray

Modules/ThirdParty/pygccxml/src/UpdatepygccxmlFromUpstream.sh, Modules/ThirdParty/pygccxml/src/pygccxml/__init__.py, Modules/ThirdParty/pygccxml/src/pygccxml/declarations/calldef.py, Modules/ThirdParty/pygccxml/src/pygccxml/declarations/scopedef.py, Modules/ThirdParty/pygccxml/src/pygccxml/parser/config.py, Modules/ThirdParty/pygccxml/src/pygccxml/parser/source_reader.py, Modules/ThirdParty/pygccxml/src/pygccxml/utils/utils.py
@iMichka @bradking @billhoffman @tao558
=> Pygccxml update

Modules/Segmentation/ConnectedComponents/wrapping/itkConnectedComponentImageFilter.wrap, Modules/Segmentation/ConnectedComponents/wrapping/itkHardConnectedComponentImageFilter.wrap, Modules/Segmentation/ConnectedComponents/wrapping/itkScalarConnectedComponentImageFilter.wrap
Often the generated labels exceed 255.
=> BUG: Do not wrap unsigned char for connected component output

Modules/Remote/Montage.remote.cmake
Update `Montage` remote module to its latest commit.
=> ENH: Update `Montage` remote module

Modules/Core/Common/include/itkCommand.h
=> COMP: Fix ~FunctionCommand implicit override warning

Modules/IO/BMP/test/itkBMPImageIOTestExtension.cxx
=> COMP: fix error on IBM POWER9 ppcle64 arch

Modules/Core/Common/include/itkEventObject.h
=> Fix event macro override warnings

Modules/Core/Common/src/itkProcessObject.cxx
Filters derived from the ImageSink class frequently do not have a
primary output. This warning was emitted erroneously during the
PrintSelf method.
This issue was reported in SimpleITK/SimpleITK#1141.
=> BUG: Remove no output warning in ImageSink filters

Modules/Filtering/Thresholding/test/itkBinaryThresholdImageFilterTest.cxx
Fix typo in `itkBinaryThresholdImageFilterTest`.
=> STYLE: Fix typo in `itkBinaryThresholdImageFilterTest`

Modules/Remote/SimpleITKFilters.remote.cmake
The module update include the NPasteImageFilter and update to the CI
build system to Github Actions.
=> ENH: Bump SimpleITKFilters remote module

Modules/Core/Common/CMake/itkGenerateNewCompilerFeatureDetectionHeaders.cmake
When built with an environment variable (`ITK_ACCEPT_ALL_COMPILERS`) set,
pass arguments to the compiler version-check cmake utility that allow unknown
compilers. This will allow clang-tidy to be run on projects that consume ITK.
=> ENH: Let consuming projects build with clang-tidy.

Examples/Filtering/DiffusionTensor3DReconstructionImageFilter.cxx
Fix typos in DTI 3D reconstruction image filter example.
=> DOC: Fix typos in DTI 3D reconstruction image filter example

Modules/Core/SpatialObjects/include/itkContourSpatialObject.h, Modules/Core/SpatialObjects/include/itkMetaConverterBase.h, Modules/Core/SpatialObjects/include/itkMetaSceneConverter.h, Modules/Core/SpatialObjects/include/itkPolygonSpatialObject.h, Modules/Core/SpatialObjects/include/itkSpatialObjectToImageFilter.h, Modules/Core/SpatialObjects/include/itkTubeSpatialObject.h
Add boolean macros to `SpatialObjects` module boolean ivars.
=> ENH: Add boolean macros to `SpatialObjects` module boolean ivars

Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalClosingImageFilter.hxx, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalOpeningImageFilter.hxx, Modules/Filtering/MathematicalMorphology/include/itkMorphologicalGradientImageFilter.hxx
Turn commented unnecessary commands into useful comments.
=> STYLE: Turn commented unnecessary commands into useful comments

Modules/Remote/TubeTK.remote.cmake
Added helper functions that automate the segmentation of tubes
from grey scale and binary images.
Updated and re-organized examples
=> ENH: Bump TubeTK to offer updated examples and improved tube seg

Modules/Filtering/ImageLabel/include/itkBinaryContourImageFilter.hxx
addresses SimpleITK/SimpleITK#1213
=> Fix signed maurer distance map zero divide

Modules/Remote/AdaptiveDenoising.remote.cmake
=> ENH:  Add adaptive denoising module.

Modules/ThirdParty/HDF5/src/itk_H5Cpp.h.in, Modules/ThirdParty/HDF5/src/itkhdf5/H5Cpp.h, Modules/ThirdParty/HDF5/src/itkhdf5/cpp/H5Cpp.h
The aliasing for the build tree was incorrectly matched to
install tree file name directory for H5Cpp.h.
\#include "itkhdf5/itk_H5Cpp.h"
Resulted in an error of missing headerfile "itkhdf5/cpp/H5cpp.h"
when building against an installed version of ITK.
=> BUG: itkhdf5 installed paths were incorrect with recent hdf5 versions

Modules/Remote/SimpleITKFilters.remote.cmake
88f6dd2 Add wrapping for DICOMOrient and NPaste image filter
e383bad COMP: fix compilation error with SetDesiredCoordinateOrientation
=> COMP: Update SimpleITKFilters remote module

Modules/Remote/SimpleITKFilters.remote.cmake
4415840 DOC: tweak NPaste documentation
37ce190 ENH: Add NPasteImageFilter
a7a7f66 BUG: Remove old Azure Pipelines configuration
6a17aa5 ENH: Incorporate GitHub Actions from ITKModuleTemplate This
requires the incorporation of 2 yml scripts that will test the module
under various configurations for Windows, Linux and MacOS. These
scripts were copied from the ITKModuleTemplate.
e3dbeea ENH: Update ITK Python Package to 5.1.0.post2 in setup.py
043d96d ENH: CI build against ITK 5.1.0
c0cc6e4 BUG: Safely return INVALID in GetAsString
c8c4243 Initialized arrays in constructor, address valgrind defect
=> For Release - COMP: Updating ITKSimpleITKFilters remote module

Modules/Filtering/MathematicalMorphology/test/itkGrayscaleMorphologicalOpeningImageFilterTest2.cxx
Fix math morphology strongly typed `enum` scope-resolution.
=> BUG: Fix math morphology strongly typed `enum` scope-resolution

Modules/Filtering/MathematicalMorphology/test/CMakeLists.txt, Modules/Filtering/MathematicalMorphology/test/itkMathematicalMorphologyEnumsTest.cxx
Test streaming math morphology `enum class` types.
=> ENH: Test streaming math morphology `enum class` types

Modules/Filtering/ImageLabel/include/itkBinaryContourImageFilter.hxx
=> BUG: Address divide by zero error in SignedMaurerDistance

Modules/IO/GDCM/include/itkGDCMImageIO.h, Modules/IO/GDCM/src/itkGDCMImageIO.cxx
Fixed issue with GDCMImageIO doxygen (s. screenshot), updated one comment.
**No code changes.**
Before:
After:
=> DOC: Updated GDCMImageIO

Modules/Bridge/NumPy/wrapping/PyBuffer.i.in, Modules/Bridge/NumPy/wrapping/PyBuffer.i.init, Modules/Bridge/NumPy/wrapping/PyVnlVectorBuffer.i.in, Wrapping/Generators/Python/CMakeLists.txt, Wrapping/Generators/Python/ExternalProjectConfig.py.in, Wrapping/Generators/Python/Tests/pythonTestDriver.py.in, Wrapping/Generators/Python/itk/__init__.py, Wrapping/Generators/Python/itk/__init__.py.in, Wrapping/Generators/Python/itkBase.py, Wrapping/Generators/Python/itkBuildOptions.py.in, Wrapping/Generators/Python/itkConfig.py.in, Wrapping/Generators/Python/itkExtras.py, Wrapping/Generators/Python/itkHelpers.py, Wrapping/Generators/Python/itkLazy.py, Wrapping/Generators/Python/itkTemplate.py, Wrapping/Generators/Python/itkTypes.py, Wrapping/Generators/SwigInterface/igenerator.py
STYLE:  Address linting related warnings
First pass at cleaning up python files to address
potential issues identified by python linting tools
=> Fix python lint warnings - pass #1

Wrapping/Generators/Python/itkBase.py, Wrapping/Generators/Python/itkExtras.py, Wrapping/Generators/Python/itkTemplate.py, Wrapping/Generators/Python/itkTypes.py
Working through pylint warnings.
=> STYLE: Fix python lint warnings Phase 2

CMake/ITKSetStandardCompilerFlags.cmake
Use `-mtune=generic` to avoid build-time CPU detection of `-mtune=native`
to get reproducible build results.
See https://reproducible-builds.org/ for why this is good.
Fixes #1939
This PR was done while working on reproducible builds for openSUSE.
=> BUG: Fix issue #1939: Use -mtune=generic

Wrapping/Generators/Python/itk/__init__.py, Wrapping/Generators/Python/itkBase.py, Wrapping/Generators/Python/itkConfig.py.in, Wrapping/Generators/Python/itkExtras.py, Wrapping/Generators/Python/itkLazy.py, Wrapping/Generators/Python/itkTemplate.py
Next batch of pylint warnings.
=> STYLE: Fix python lint warnings p3

CMake/ITKModuleEnablement.cmake
Remote modules can now depend on one another when being built as part of ITK.
External builds do not cause ITK to be reconfigured with their dependencies, and throw a configure-time error if not all the required modules are turned on in the base ITK build. This is same as before, and I don't think it would be desirable to have ITK reconfigured (if needed by an externally built remote module).
Technically, built-in modules can now depend on remote modules, but we do not allow this as a matter of policy.
=> ENH: allow dependencies on remote modules

Wrapping/Generators/Python/CMakeLists.txt, Wrapping/Generators/Python/Tests/CMakeLists.txt, Wrapping/Generators/Python/Tests/extras.py, Wrapping/Generators/Python/Tests/nolazy.py, Wrapping/Generators/Python/itk/__init__.py, Wrapping/Generators/Python/itk/itkInitHelpers.py, Wrapping/Generators/Python/itkBase.py, Wrapping/Generators/Python/itkConfig.py.in, Wrapping/Generators/Python/itkExtras.py, Wrapping/Generators/Python/itkTemplate.py, Wrapping/Generators/Python/itkTypes.py
4th set of refactorings to the python infrastructure.  Still attempting to simplify the main itk package by removing circular dependencies.
=> Fix python lint warnings p4

Modules/Remote/AdaptiveDenoising.remote.cmake
- [] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)
=> ENH:  Add refactoring and more testing.

Wrapping/Generators/Python/CMakeLists.txt
=> BUG: Add '_d' POSTFIX to Windows Python Debug (#2050)

Modules/Filtering/Convolution/include/itkMaskedFFTNormalizedCorrelationImageFilter.hxx, Modules/Filtering/Deconvolution/include/itkLandweberDeconvolutionImageFilter.h, Modules/Filtering/Deconvolution/include/itkLandweberDeconvolutionImageFilter.hxx, Modules/Filtering/Deconvolution/include/itkParametricBlindLeastSquaresDeconvolutionImageFilter.h, Modules/Filtering/Deconvolution/include/itkParametricBlindLeastSquaresDeconvolutionImageFilter.hxx, Modules/Filtering/ImageFilterBase/include/itkBinaryGeneratorImageFilter.h, Modules/Filtering/ImageFilterBase/include/itkTernaryGeneratorImageFilter.h, Modules/Filtering/ImageFilterBase/include/itkTernaryGeneratorImageFilter.hxx, Modules/Filtering/ImageFilterBase/include/itkUnaryGeneratorImageFilter.h, Modules/Filtering/ImageFilterBase/test/itkGeneratorImageFilterGTest.cxx, Modules/Filtering/ImageIntensity/include/itkTernaryAddImageFilter.h, Modules/Filtering/ImageIntensity/include/itkTernaryMagnitudeImageFilter.h, Modules/Filtering/ImageIntensity/include/itkTernaryMagnitudeSquaredImageFilter.h, Modules/Filtering/ImageIntensity/include/itkTernaryOperatorImageFilter.h, Modules/Filtering/ImageIntensity/test/itkTernaryMagnitudeImageFilterTest.cxx, Modules/Filtering/ImageIntensity/test/itkTernaryMagnitudeSquaredImageFilterTest.cxx, Modules/Filtering/ImageIntensity/test/itkTernaryOperatorImageFilterTest.cxx
=> Add ternary generator image filter

CMake/ITKConfig.cmake.in
Supersedes and closes SimonRIT/RTK#389
=> COMP: export ITK_LIBRARY_BUILD_TYPE for external building of modules

Modules/Filtering/ImageFilterBase/wrapping/itkTernaryGeneratorImageFilter.wrap, Modules/Filtering/ImageIntensity/wrapping/itkTernaryAddImageFilter.wrap, Modules/Filtering/ImageIntensity/wrapping/itkTernaryMagnitudeImageFilter.wrap
=> ENH: Update ternary filter wrapping for generator base class

Modules/IO/DCMTK/test/itkDCMTKSeriesReadImageWrite.cxx
=> COMP: add missing parentheses

Modules/Core/Common/wrapping/itkVectorContainer.wrap
=> ENH: Add support for VectorContainer of float32

.circleci/config.yml, Modules/Bridge/NumPy/wrapping/test/itkImageMetaDataSetGetItem.py, Modules/Bridge/NumPy/wrapping/test/itkPyBufferMemoryLeakTest.py, Modules/Bridge/NumPy/wrapping/test/itkPyBufferPipelineTest.py, Modules/Core/Common/wrapping/test/itkMatrixTest.py, Wrapping/Generators/Python/Tests/extras.py
Python `numpy` is a required resource so we do not need alternate avenues in the case that it is not present.  Resolves #2055.
=> PERF: No need to handle absent Python numpy

Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshBaseIterator.h
=> COMP: Address unused other parameter in defaulted methods

Wrapping/Generators/Python/CMakeLists.txt
Closes #58
Co-authored-by: Niels Dekker <N.Dekker@lumc.nl>
=> PERF: Add IPO flags to Python libraries

README.md
Fix link to NumFOCUS ITK project website in `README`.
=> DOC: Fix link to NumFOCUS ITK project website in `README`

Examples/RegistrationITKv4/ImageRegistration5.py, Modules/Filtering/ImageGrid/wrapping/test/ResampleImageFilterTest.py, Wrapping/Generators/Python/Tests/PythonTypeTest.py, Wrapping/Generators/Python/Tests/findEmptyClasses.py, Wrapping/Generators/Python/Tests/getNameOfClass.py, Wrapping/Generators/Python/Tests/verifyGetOutputAPIConsistency.py, Wrapping/Generators/Python/Tests/verifyTTypeAPIConsistency.py, Wrapping/Generators/Python/itk/__init__.py, Wrapping/Generators/Python/itk/support/itkBase.py, Wrapping/Generators/Python/itk/support/itkBuildOptions.py, Wrapping/Generators/Python/itk/support/itkExtras.py, Wrapping/Generators/Python/itk/support/itkInitHelpers.py, Wrapping/Generators/Python/itk/support/itkLazy.py, Wrapping/Generators/Python/itk/support/itkTemplate.py, Wrapping/Generators/Python/itk/support/itkTypes.py, Wrapping/Generators/Python/itkConfig.py.in
Add type hinting and refactor code to be more transparent with improved meaningful variable names.
=> Mypy typing fixes

Modules/Bridge/NumPy/wrapping/test/CMakeLists.txt, Modules/Core/Common/wrapping/test/CMakeLists.txt, Modules/Filtering/ImageIntensity/wrapping/test/CMakeLists.txt
=> ENH: remove NumPy presence conditions from tests' CMakeLists.txt

CMake/ITKModuleTest.cmake
=> Fix compilation with Python and tests enabled on Visual Studio

Modules/IO/GDCM/src/itkGDCMImageIO.cxx
Adds support for non-compliant DICOM headers (but otherwise readable files) in Javascript (itk-js).
This PR aligns the GDCM IO behavior in Javascript with the one in C++ or Python.
A custom build with this works just fine for me.
Are there any other pending reasons for this stricter behavior only in js?
=> ENH: Support for non-compliant DICOM in itk-js

Modules/Remote/TubeTK.remote.cmake
TubeTK update addresses 
* PDF report generation
* Updated ComputeTangentsAndNormals() from ITK SpatialObjects
* Jupyter Notebook examples of data preprocessing and tube segmentation from multiple data sources such as MRA, CT Perfusion, CT Angiography, and Binary (thresholded digital subtraction angiography) data.
* Converting 3D to 4D images and vice versa
* Improvements in registration
* and misc bug fixes.
=> ENH: TubeTK release candidate for ITK v5.1.2

Wrapping/Generators/Python/CMakeLists.txt, Wrapping/Generators/Python/PyBase/pyBase.i, Wrapping/Generators/SwigInterface/CMakeLists.txt, Wrapping/Generators/SwigInterface/igenerator.py
Update SWIG to allow new documentation improvements for python introspections.
=> ENH: Update SWIG python documentation

Modules/Core/Common/include/itkHexahedronCell.hxx, Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx, Modules/Filtering/ImageGrid/wrapping/itkWarpImageFilter.wrap, Modules/Numerics/Eigen/include/itkEigenAnalysis2DImageFilter.hxx, Modules/Numerics/Eigen/test/itkEigenAnalysis2DImageFilterTest.cxx, Modules/Numerics/Eigen/wrapping/itkEigenAnalysis2DImageFilter.wrap, Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx, Modules/Registration/PDEDeformable/wrapping/itkDemonsRegistrationFilter.wrap, Modules/Registration/PDEDeformable/wrapping/itkLevelSetMotionRegistrationFilter.wrap, Modules/Registration/PDEDeformable/wrapping/itkPDEDeformableRegistrationFilter.wrap, Modules/Registration/PDEDeformable/wrapping/itkSymmetricForcesDemonsRegistrationFilter.wrap
=> COMP: Fix invalid wrap combinations

Modules/Filtering/ImageIntensity/include/itkShiftScaleImageFilter.h, Modules/Filtering/ImageIntensity/include/itkShiftScaleImageFilter.hxx
Change m_UnderflowCount and m_OverflowCount to SizeValue type to
prevent overfloat.
Modernize to use the dynamic-threading model. Replace per thread
arrays with thread local storage and mutexed reduce step.
Use in-class member initialization.
=> ENH: Moderinize ShiftScaleImageFilter

Documentation/Maintenance/UpdatingThirdParty.md
Fix verbatim block in `UpdatingThirdParty` doc file.
=> DOC: Fix verbatim block in `UpdatingThirdParty` doc file

Modules/IO/ImageBase/test/itkWriteImageFunctionGTest.cxx
=> COMP: Address brace initializer warning

Modules/Core/Common/test/itkSmartPointerGTest.cxx
=> ENH: Exercise converting Object::Pointer to Object::ConstPointer

Modules/Core/Common/test/itkCommandObserverObjectTest.cxx
The order of object deletion was causing a reference
to an object to be accessed from a lambda function
after the object was deleted.
=> BUG: ASAN identified use after delete bug

Modules/IO/ImageBase/test/itkImageSeriesWriterTest.cxx
Improve `itk::ImageSeriesWriter` class test file style:
- Use the `ITK_TRY_EXPECT_NO_EXCEPTION` and `ITK_TRY_EXPECT_EXCEPTION`
macros to avoid boilerplate code.
input argument checking and test finishing message).
=> STYLE: Improve `itk::ImageSeriesWriter` class test file style

Modules/IO/GDCM/test/itkGDCMSeriesStreamReadImageWriteTest.cxx
Improve coverage for `itk::GDCMSeriesFileNames` class:
- Test the exceptions.
=> ENH: Improve coverage for `itk::GDCMSeriesFileNames` class

Modules/Core/Common/include/itkOutputWindow.h, Modules/Core/Common/src/itkOutputWindow.cxx, Modules/Filtering/Thresholding/test/itkThresholdImageFilterTest.cxx
=> Output window as global singleton

Modules/IO/JPEG2000/test/CMakeLists.txt, Modules/IO/LSM/test/CMakeLists.txt, Modules/IO/TIFF/test/CMakeLists.txt
Corrected multiple tests writing to the same output file, causing
intermediate test failures.
=> BUG: Fix JPEG200Test6 file output clobbering

Modules/Bridge/VtkGlue/wrapping/VtkGlue.i
Compilation of VtkGlue with wrapping for Python fails due to a `module()` call with extra escape characters in the argument list.
Fixes issue https://github.com/InsightSoftwareConsortium/ITK/issues/2026
=> BUG: fix python module definition in VtkGlue wrap

Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx
Signed-off-by: Michael Jackson <mike.jackson@bluequartz.net>
=> COMP: Detect Apple Silicon arch for Floating Point exceptions

CMake/ITKSetPython3Vars.cmake, CMakeLists.txt
A usability improvement per [this suggestion](https://github.com/InsightSoftwareConsortium/ITK/issues/2252#issuecomment-761017163).
=> ENH: Python wrapping fixes

Modules/ThirdParty/PNG/UpdateFromUpstream.sh, Modules/ThirdParty/PNG/src/itkpng/CMakeLists.txt, Modules/ThirdParty/PNG/src/itkpng/arm/arm_init.c, Modules/ThirdParty/PNG/src/itkpng/arm/filter_neon.S, Modules/ThirdParty/PNG/src/itkpng/arm/filter_neon_intrinsics.c, Modules/ThirdParty/PNG/src/itkpng/arm/palette_neon_intrinsics.c, Modules/ThirdParty/PNG/src/itkpng/itk_png_mangle.h
Add ARM support to libpng to avoid linker errors with Clang.
=> libpng Apple Silicon ARM64 support

Modules/Numerics/Optimizersv4/itk-module.cmake, Modules/Numerics/Optimizersv4/wrapping/CMakeLists.txt, Modules/Numerics/Optimizersv4/wrapping/itkLBFGSBOptimizerv4.wrap, Modules/Numerics/Optimizersv4/wrapping/itkLBFGSOptimizerBaseHelperv4.wrap, Modules/Numerics/Optimizersv4/wrapping/itkLBFGSOptimizerBasev4.wrap, Modules/Numerics/Optimizersv4/wrapping/itkSingleValuedNonLinearVnlOptimizerv4.wrap, Modules/Numerics/Optimizersv4/wrapping/itkVnlTypes.wrap, Modules/Numerics/Optimizersv4/wrapping/test/CMakeLists.txt
=> ENH: Python wrapping for v4 Optimizers

Utilities/Maintenance/AuthorsChangesSince.py
Also ignore checkout of invalid hashes.
=> ENH: Generate a list of remote modules changed for release notes

Modules/Filtering/DisplacementField/wrapping/itkDisplacementFieldTransform.wrap
=> ENH: Wrap DisplacementFieldTransform for vector floats

Modules/Core/Common/CMakeLists.txt, Modules/Core/Common/src/itkConfigure.h.in, Modules/Core/Common/src/itkMultiThreaderBase.cxx
=> CMAKE multi threader configuration option

Modules/Filtering/ImageIntensity/include/itkSymmetricEigenAnalysisImageFilter.h, Modules/Filtering/ImageIntensity/test/itkSymmetricEigenAnalysisImageFilterTest.cxx
- STYLE: Add SymmetricEigenAnalysisImageFilter::SetOrderEigenValuesBy
- ENH: Set default dimension for SymmetricEigenAnalysisImageFilter
=> symmetric eigen dimension

Modules/Numerics/Optimizersv4/wrapping/itkGradientDescentOptimizerv4.wrap
=> ENH: Wrap GradientDescentOptimizerv4 for Python

Modules/Filtering/ImageFilterBase/wrapping/itkBinaryGeneratorImageFilter.wrap, Modules/Filtering/ImageIntensity/wrapping/itkAddImageFilter.wrap, Modules/Filtering/ImageIntensity/wrapping/test/itkImageFilterNumPyInputsTest.py, Wrapping/Generators/Python/itk/support/itkHelpers.py
=> ENH: supporting multi-channel tensors as inputs and outputs in Python

Modules/Filtering/GPUSmoothing/include/itkGPUMeanImageFilter.h, Modules/Filtering/GPUThresholding/include/itkGPUBinaryThresholdImageFilter.h, Modules/Registration/GPUPDEDeformable/include/itkGPUDemonsRegistrationFilter.h
Add ITK_MACROEND_NOOP_STATEMENT for GPU macros.
=> COMP: Use ITK_MACROEND_NOOP_STATEMENT for GPU macro ending.

Modules/Registration/Metricsv4/include/itkANTSNeighborhoodCorrelationImageToImageMetricv4GetValueAndDerivativeThreader.hxx
=> STYLE: Throw expression should throw anonymous temporary values instead

Modules/Filtering/FFT/include/itkFFTWHalfHermitianToRealInverseFFTImageFilter.hxx
warning: cast from 'const std::complex<float> *' to 'float (*)[2]' drops const qualifier [-Wcast-qual]
=> COMP: Preserve const qualifier for variable

Modules/ThirdParty/MetaIO/src/MetaIO/src/metaFEMObject.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaForm.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaImage.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaObject.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaTube.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaTube.h, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaUtils.cxx
Produced by running UpdateFromUpstream. Supersedes and closes #2313.
=> MetaIO 2021-02-12 (df6ad862)

Modules/Segmentation/Classifiers/include/itkImageGaussianModelEstimator.h, Modules/Segmentation/Classifiers/include/itkImageGaussianModelEstimator.hxx
Provide default initialization to constructor in header file in line with
the common practice in ITK.
=> STYLE: Provide default initialization to constructor in header file

Modules/Core/Common/include/itkSymmetricEigenAnalysis.h, Modules/Core/Common/include/itkSymmetricEigenAnalysis.hxx, Modules/Core/FiniteDifference/include/itkFiniteDifferenceFunction.h, Modules/Core/FiniteDifference/include/itkFiniteDifferenceFunction.hxx, Modules/Filtering/BiasCorrection/include/itkMRIBiasFieldCorrectionFilter.h, Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.h, Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.hxx, Modules/Filtering/ImageGrid/include/itkMirrorPadImageFilter.h, Modules/Filtering/ImageGrid/include/itkMirrorPadImageFilter.hxx, Modules/Segmentation/DeformableMesh/include/itkDeformableSimplexMesh3DGradientConstraintForceFilter.h, Modules/Segmentation/Voronoi/include/itkVoronoiSegmentationRGBImageFilter.h, Modules/Segmentation/Voronoi/include/itkVoronoiSegmentationRGBImageFilter.hxx
=> STYLE: Prefer const pointer

Testing/ContinuousIntegration/AzurePipelinesBatch.yml
The system does not have enough disk space for a coverage build.
=> BUG: Remove Azure coverage CI build

Modules/ThirdParty/HDF5/src/itkhdf5/config/cmake/H5pubconf.h.in, Modules/ThirdParty/HDF5/src/itkhdf5/src/H5config.h.in
@thewtex @dzenanz do you know what git thing I'm screwing up that I see 38 commits in this PR instead of just the 1 expected?  And how do I fix it?
=> Hdf5 universal long double

Modules/Core/Common/include/itkMathDetail.h
For compatability with Universal Binaries on macOS, change how #include <emmintrin.h> is done to test against __SSE2__.
Using a trycompile to check if #include <emmintrin.h> compiles doesn't work for UBs becuase the check will only be done for the native architecture, not both architectures (where indeed there would be the opposite answer).
Other parts of the codebase are already doing it this way, so it must work on other platforms too.
=> COMP: Changed conditional include of emmintrin.h to use __SSE2__

Wrapping/Generators/Python/Tests/extras.py, Wrapping/Generators/Python/itk/support/itkExtras.py
- ENH: imageio kwarg for imread, imwrite
- STYLE: black formatting on itkExtras.py
=> imread imwrite imageio

Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.h, Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.hxx
=> Reduce duplication in ContourExtractor2DImageFilter

CTestConfig.cmake
=> ENH: changed CTEST_DROP_METHOD from http to https

Modules/Core/Common/CMakeLists.txt, Modules/Core/Common/src/itkConfigure.h.in
Presumably they've since been replaced with C++11 atomics.
=> COMP: removed dead atomic operation checks

Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.hxx, Modules/Filtering/Path/test/itkContourExtractor2DImageFilterTest.cxx
=> COMP: Address gcc 4.8 compilation errors

Modules/Core/Common/include/itkOptimizerParameters.h, Modules/Core/Common/test/itkOptimizerParametersGTest.cxx
Eases constructing an `OptimizerParameters` object from the data of a
contiguous container, like `std::vector` or `std::array`.
Included a GTest, `OptimizerParameters.ConstructWithSpecifiedDataAndSize`.
=> ENH: Add explicit OptimizerParameters(data, dimension) constructor

Modules/ThirdParty/OpenJPEG/src/openjpeg/opj_includes.h
This closes #1967.
Co-authored-by: @spacelg <42860526+spacelg@users.noreply.github.com>
Fixes error:
> Error	C2169	'lrintf': intrinsic function, cannot be defined [M:\Dev\Plus\SPc\itk-bin\Modules\ThirdParty\OpenJPEG\src\openjpeg\itkopenjpeg.vcxproj]	itk	M:\Dev\Plus\SPc\itk\Modules\ThirdParty\OpenJPEG\src\openjpeg\opj_includes.h	106
=> COMP: Fix OpenJPEG build error with Visual Studio 16.9

Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5DataSpace.h, Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5Exception.h, Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5File.h, Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5Group.h, Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5Include.h, Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5Object.h
Backported 7501f96ab9605e11c58bc0c9e6412e4db30ba7db from upstream HDF5 to add C++11 override keyword where appropriate.
Fixes compiler warnings.
=> COMP: cherrypick HDF5 commit that added C++11 override keywords

Modules/Remote/BSplineGradient.remote.cmake, Modules/Remote/HigherOrderAccurateGradient.remote.cmake, Modules/Remote/IOScanco.remote.cmake, Modules/Remote/Montage.remote.cmake, Modules/Remote/MorphologicalContourInterpolation.remote.cmake, Modules/Remote/RLEImage.remote.cmake, Modules/Remote/RTK.remote.cmake, Modules/Remote/SphinxExamples.remote.cmake, Modules/Remote/SplitComponents.remote.cmake, Modules/Remote/Strain.remote.cmake, Modules/Remote/Thickness3D.remote.cmake, Modules/Remote/TotalVariation.remote.cmake
=> ENH: update remote modules using the script

Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.hxx
=> COMP: Address gcc4.8 warnings in itkContourExtractor2DImageFilter.hxx.

Modules/Nonunit/Review/wrapping/itkFastSymmetricForcesDemonsRegistrationFilter.wrap
=> COMP: Wrap FastSymmetricForcesDemonsRegistrationFilter like its parent class

Modules/Filtering/DistanceMap/include/itkDirectedHausdorffDistanceImageFilter.h, Modules/Filtering/DistanceMap/include/itkDirectedHausdorffDistanceImageFilter.hxx, Modules/Filtering/DistanceMap/include/itkHausdorffDistanceImageFilter.hxx
=> Fix directed hausdorff distance valgrind

Modules/Core/Common/test/itkOptimizerParametersGTest.cxx, Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.hxx
=> COMP: Replace Type{} with Type() for gcc4.

CMakeLists.txt, Modules/Remote/CMakeLists.txt
=> ENH: Mark most CMake variables as advanced

Modules/Remote/Ultrasound.remote.cmake
=> ENH: add Ultrasound remote module

Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.h, Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.hxx
=> COMP: Address ContourExtractor2DImageFilter valgrind defects

Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5DataSet.cpp, Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5DataSet.h
=> BUG: Fix reference counts for HDF5 DataSet assignment operator

Wrapping/Generators/Python/Tests/extras.py, Wrapping/Generators/Python/itk/__init__.py, Wrapping/Generators/Python/itk/support/extras.py, Wrapping/Generators/Python/itk/support/template_class.py, Wrapping/Generators/Python/itk/support/types.py
Support many basic itk types and add more type annotations for functions
in the extras module.
Use itk_types and complex_ to avoid conflicts with the types and complex
standard library module and builtin respectively.
=> ENH: Add typehints for itk types to extras

CMakeLists.txt
This is a follow-up to #2423 and #2425.
=> STYLE: mark ultrasound remote module enablement as advanced variable

.github/labeler.yml
Label PRs on filenames: add regex rules that apply to the filenames
changed in a PR.
=> ENH: Label PRs on filenames

Modules/Bridge/NumPy/wrapping/test/itkPyVectorContainerTest.py, Wrapping/Generators/Python/itk/support/extras.py
Add direct access to `itk.array_from_vector_container`, `itk.array_view_from_vector_container`, `itk.vector_container_from_array`.
Closes [Issue 2428](https://github.com/InsightSoftwareConsortium/ITK/issues/2428).
=> ENH: Expose numpy / vector container Python interface

Modules/Filtering/Smoothing/wrapping/test/MedianImageFilterTest.py, Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml, Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml, Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml, Wrapping/Generators/Python/Tests/extras.py, Wrapping/Generators/Python/itk/support/base.py, Wrapping/Generators/Python/itk/support/extras.py, Wrapping/Generators/Python/itk/support/helpers.py, Wrapping/Generators/Python/itk/support/init_helpers.py, Wrapping/Generators/Python/itk/support/lazy.py, Wrapping/Generators/Python/itk/support/template_class.py, Wrapping/Generators/Python/itk/support/types.py, Wrapping/Generators/SwigInterface/igenerator.py
- BUG: Add __all__ to itk.support.init_helpers
- ENH: Add typehints for itk functional filters
=> functional types

Modules/Bridge/NumPy/include/itkPyVectorContainer.h, Modules/Bridge/NumPy/include/itkPyVectorContainer.hxx, Modules/Bridge/NumPy/wrapping/itkPyVectorContainer.wrap, Modules/Bridge/NumPy/wrapping/test/itkPyVectorContainerTest.py, Wrapping/Generators/Python/itk/support/extras.py
Updated `PyVectorContainer` template arguments to allow conversion from `VectorContainer`s of index types other than `IdentifierType`. Wrapping, testing, and functional interface updates also included.
Note that `PyVectorContainer` still does not fully cover all possible `VectorContainer` inputs but this PR gets it much closer, wrapping for different index types as well as a variety of scalar, vector, and offset data types not previously covered.
This PR depends on [PR 2430](https://github.com/InsightSoftwareConsortium/ITK/pull/2430). Feedback welcome!
=> ENH: Add PyVectorContainer Wrappings to match VectorContainer

Modules/Filtering/DistanceMap/test/itkHausdorffDistanceImageFilterTest.cxx, Modules/Nonunit/Review/test/itkScalarChanAndVeseSparseLevelSetImageFilterTest1.cxx
Increase the code coverage:
- Remove explicit calls to the `Print` method and rely on the
basic method exercising macro call.
- Define as a constant expression the image dimensionality.
- Capitalize comment sentences.
in the `itkHausdorffDistanceImageFilterTest.cxx` file
=> ENH: Increase code coverage

Modules/Core/SpatialObjects/test/itkPolygonSpatialObjectIsInsideInObjectSpaceTest.cxx
=> STYLE: use convenience functions ReadImage and WriteImage

Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5DataSet.cpp
The code review at https://github.com/HDFGroup/hdf5/pull/503 changed the implementation.  This pull request mimics that.
=> STYLE: Mimic code that was reviewed for the upstream HDF5 source

Wrapping/Generators/Python/itk/support/extras.py, Wrapping/Generators/Python/itk/support/types.py
Added type hints to Python functional interface methods in `extras.py`. This will close [Issue 2446](https://github.com/InsightSoftwareConsortium/ITK/issues/2446).
=> ENH: Type hints in functional interface

Modules/Remote/IOFDF.remote.cmake, Modules/Remote/IOScanco.remote.cmake, Modules/Remote/SphinxExamples.remote.cmake, Modules/Remote/Ultrasound.remote.cmake
=> ENH: update remote modules by running the script

.zenodo.json
With the ITK/Utilities/Maintenance/UpdateZenodo.py script.
Add Lee N, Mihail I.
=> DOC: Update .zenodo

Modules/Core/Common/include/itkPhasedArray3DSpecialCoordinatesImage.h, Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx
Small code improvements within `LinearThreadedGenerateData`:
- Retrieved values from `largestPossibleRegion` only once, storing them
in local variables.
- Replaced `TransformPhysicalPointToContinuousIndex(point, index)` by
its faster overload, `TransformPhysicalPointToContinuousIndex(point)`.
- Replaced `(endIndex[i] - startIndex[i])` from inner `for` loop.
A performance improvement of `ResampleImageFilter::Update()` of about
4 percent was observed, using Visual C++ 2019 (Release).
Added missing convenience overloads of `Transform...` member functions
to `PhasedArray3DSpecialCoordinatesImage`, which were needed for 
this `LinearThreadedGenerateData` improvement.
=> PERF: Make `ResampleImageFilter::LinearThreadedGenerateData` faster

Modules/Numerics/Optimizersv4/include/itkLBFGS2Optimizerv4.h, Modules/Numerics/Optimizersv4/src/itkLBFGS2Optimizerv4.cxx, Modules/Numerics/Optimizersv4/test/itkLBFGS2Optimizerv4Test.cxx
Add support for local transforms.
Inherit from GradientDescentOptimizerv4 to add support for threaded scaling and fit it into the hierarchy of gradient descent based optimizers.
=> ENH: Adapt LBFGS2Optimizerv4 to inherit from GradientDescentOptimizerV4

Modules/IO/TransformFactory/src/itkTransformFactoryBaseRegister.hxx, Modules/IO/TransformFactory/test/itkTransformFactoryBaseTest.cxx
This is required to read and write the transform.
=> BUG: Register ComposeScaleSkewVersor3DTransform transform - for release branch

.github/workflows/label-pr.yml
=> ENH: Bump labeler action version

Modules/Core/Common/src/itkSpatialOrientationAdapter.cxx, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkSpatialOrientationAdaptorGTest.cxx, Modules/Filtering/ImageStatistics/include/itkLabelStatisticsImageFilter.h
The old algorithm could generate an invalid combinations of axes. The new algorithm is greedy by selecting the element in the matrix with the greatest magnitude, and eleminating invalid elements for further selection.
=> BUG: Fix SpatialOrientationAdapter::FromDirectionCosines

.github/labeler.yml
Fix labeler action file regexes.
=> BUG: Fix labeler action file regexes

Modules/Filtering/LabelMap/ITKKWStyleOverwrite.txt, Modules/Filtering/LabelMap/include/itkStatisticsLabelMapFilter.h, Modules/Filtering/LabelMap/include/itkStatisticsLabelMapFilter.hxx, Modules/Filtering/LabelMap/test/CMakeLists.txt, Modules/Filtering/LabelMap/test/itkStatisticsLabelMapFilterGTest.cxx
=> Test and improve StatisticsLabelMapFilter's median computation

Modules/Filtering/LabelMap/test/itkStatisticsLabelMapFilterGTest.cxx
Addresses warning on CDash:
https://open.cdash.org/viewBuildError.php?type=1&buildid=7198510
=> COMP: Address braces around initializer warning.

.github/labeler.yml
Add further regexes to PR labeler config file in order to match more use
cases.
=> ENH: Add further regexes to PR labeler config file

Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4GetValueAndDerivativeThreader.hxx
MattesMutualInformationImageToImageMetricv4 gave wrong results
if number of work units changed, because FixedImageMarginalPDF
was initialized with values from previous iteration instead
of zeros.
=> BUG: Fix initializing FixedImageMarginalPDF with garbage

Examples/IO/ImageReadExtractWrite.cxx
=> DOC: Fix usage information in ImageReadExtractWrite example

Modules/ThirdParty/HDF5/CMakeLists.txt, Modules/ThirdParty/HDF5/itk-module-init.cmake
=> Fix hdf5 installed find package - For Release

Modules/Segmentation/LevelSets/include/itkLevelSetFunction.hxx
=> BUG: Call Specialized Curvature Computation for 3D

Modules/IO/LSM/src/itkLSMImageIO.cxx, Modules/IO/TIFF/src/itkTIFFImageIO.cxx, Modules/IO/TIFF/src/itkTIFFReaderInternal.cxx
The libtiff int types are depricated in 4.3.0 and produce a warning.
=> COMP: Use C99 int types over libtiff's

Wrapping/Generators/Python/itk/support/lazy.py
- BUG: Do not create global multiprocessing RLock
This addresses:
> /opt/conda/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown len(cache))
Reported in Project-MONAI/MONAI#1629
Here we adopt the approach in tqdm:
tqdm/tqdm#617
to address the similar issues with PyTorch:
tqdm/tqdm#611
but for our use case. A global set of locks is added to the class on
first use.
We also add a threading lock in addition to a multiprocessing
lock.
=> no global mp lock

Modules/Remote/TubeTK.remote.cmake
Linux CI failing - needed apt-get update due to changes in
ubuntu repos.
=> COMP: Bump TubeTK to version the fixes linux CI

Modules/Filtering/MathematicalMorphology/include/itkMathematicalMorphologyEnums.h
Fix enum class name in documentation.
=> DOC: Fix enum class name in documentation

Testing/ContinuousIntegration/AzurePipelinesBatch.yml, Testing/ContinuousIntegration/AzurePipelinesLinux.yml, Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml, Testing/ContinuousIntegration/AzurePipelinesMacOS.yml, Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml, Testing/ContinuousIntegration/AzurePipelinesWindows.yml, Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
- ENH: Updated CI cached testing ExternalData to 5.2.0
=> ci external data version

Modules/Core/Common/src/itkSmapsFileParser.cxx, Modules/ThirdParty/VNL/src/vxl/core/vnl/algo/vnl_svd_fixed.h, Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.h, Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector.h
=> C++20 gcc-11 compatibility

Modules/Core/TestKernel/include/itkTestingHashImageFilter.h, Modules/IO/NIFTI/test/CMakeLists.txt, Modules/IO/NIFTI/test/itkNiftiImageIOTest12.cxx
=> ENH: Add nifti12 test that was not run

Modules/Numerics/Optimizersv4/include/itkOnePlusOneEvolutionaryOptimizerv4.hxx
When OnePlusOneEvolutionaryOptimizerv4::StopOptimization was manually
called the stop description incorrectly indicated that the maximum
number of iterations had been reached. Only over write stop condition
descriptions, when the maximum number of iterations have been
exceeded.
=> BUG: Correct stop condition description

Modules/Core/Common/include/itkMultiThreaderBase.h, Modules/Core/Common/include/itkTotalProgressReporter.h, Modules/Core/Common/src/itkMultiThreaderBase.cxx
=> Remove pixel count parameter which is no longer used

Wrapping/Generators/Python/Tests/extras.py, Wrapping/Generators/Python/itk/support/extras.py
I have added support for getting the VTK direction matrix when converting
it to an ITK image in Python and for setting it when going in the other direction.
=> ENH: add support for direction in VTK image

Modules/Remote/AnisotropicDiffusionLBR.remote.cmake, Modules/Remote/BSplineGradient.remote.cmake, Modules/Remote/BoneEnhancement.remote.cmake, Modules/Remote/BoneMorphometry.remote.cmake, Modules/Remote/Cuberille.remote.cmake, Modules/Remote/HigherOrderAccurateGradient.remote.cmake, Modules/Remote/IOFDF.remote.cmake, Modules/Remote/IOScanco.remote.cmake, Modules/Remote/IsotropicWavelets.remote.cmake, Modules/Remote/MinimalPathExtraction.remote.cmake, Modules/Remote/Montage.remote.cmake, Modules/Remote/RTK.remote.cmake, Modules/Remote/SimpleITKFilters.remote.cmake, Modules/Remote/SkullStrip.remote.cmake, Modules/Remote/SphinxExamples.remote.cmake, Modules/Remote/SplitComponents.remote.cmake, Modules/Remote/Strain.remote.cmake, Modules/Remote/TextureFeatures.remote.cmake, Modules/Remote/Thickness3D.remote.cmake, Modules/Remote/TotalVariation.remote.cmake, Modules/Remote/TubeTK.remote.cmake, Modules/Remote/Ultrasound.remote.cmake
=> ENH: update remote modules using the maintenance script

Utilities/SetupForDevelopment.sh
=> STYLE: enable git blame to use ignoreRevsFile by default
