Modules/Core/Common/include/itkConstNeighborhoodIterator.h
Modules/Core/Common/include/itkConstShapedNeighborhoodIterator.h
Modules/Core/Common/include/itkNeighborhoodIterator.h
Modules/Core/Common/include/itkShapedNeighborhoodIterator.h

Follow-up to pull request #2051, "DOC: Link region iterators to
ImageRegionRange, ImageRegionIndexRange".

DOC: Add Doxygen links from iterators to ShapedImageNeighborhoodRange

---

Modules/Core/TestKernel/include/itkTestingHashImageFilter.hxx
Modules/IO/ImageBase/include/itkImageFileWriter.hxx

Following the C++ Core Guidelines, which says (August 3, 2020):
> Don't cast between pointer types when the conversion could be implicit
...
> Don't use C-style (T)expression or functional T(expression) casts
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#prosafety-type-safety-profile

STYLE: Remove C-style (const void *) casts

---

Modules/Core/Common/include/itkPriorityQueueContainer.hxx

The default constructor of MinPriorityQueueElementWrapper cannot use `0` or `itk::NumericTraits<TElement>::ZeroValue()` for `TElement == itk::Index<2>` on some configurations.
Closes #2017.

BUG: MinPriorityQueueElementWrapper constructor doesn't work

---

Modules/Core/SpatialObjects/src/itkSpatialObjectProperty.cxx
Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx
Modules/IO/ImageBase/src/itkArchetypeSeriesFileNames.cxx
Modules/IO/ImageBase/src/itkNumericSeriesFileNames.cxx
Modules/IO/ImageBase/src/itkRegularExpressionSeriesFileNames.cxx
Modules/IO/SpatialObjects/src/itkPolygonGroupSpatialObjectXMLFile.cxx
Modules/Numerics/Optimizers/src/itkConjugateGradientOptimizer.cxx
Modules/Numerics/Optimizers/src/itkCumulativeGaussianCostFunction.cxx
Modules/Numerics/Optimizers/src/itkCumulativeGaussianOptimizer.cxx
Modules/Numerics/Optimizers/src/itkFRPROptimizer.cxx
Modules/Numerics/Optimizers/src/itkGradientDescentOptimizer.cxx
Modules/Numerics/Optimizers/src/itkLBFGSOptimizer.cxx
Modules/Numerics/Optimizers/src/itkLevenbergMarquardtOptimizer.cxx
Modules/Numerics/Optimizers/src/itkMultipleValuedNonLinearOptimizer.cxx
Modules/Numerics/Optimizers/src/itkMultipleValuedNonLinearVnlOptimizer.cxx
Modules/Numerics/Optimizers/src/itkOnePlusOneEvolutionaryOptimizer.cxx
Modules/Numerics/Optimizers/src/itkOptimizer.cxx
Modules/Numerics/Optimizers/src/itkPowellOptimizer.cxx
Modules/Numerics/Optimizers/src/itkQuaternionRigidTransformGradientDescentOptimizer.cxx
Modules/Numerics/Optimizers/src/itkRegularStepGradientDescentBaseOptimizer.cxx
Modules/Numerics/Optimizers/src/itkRegularStepGradientDescentOptimizer.cxx
Modules/Numerics/Optimizers/src/itkSingleValuedNonLinearOptimizer.cxx
Modules/Numerics/Optimizers/src/itkSingleValuedNonLinearVnlOptimizer.cxx
Modules/Numerics/Optimizers/src/itkVersorRigid3DTransformOptimizer.cxx
Modules/Numerics/Optimizers/src/itkVersorTransformOptimizer.cxx

Include guards (like `itkSomeFileName_h`) are specifically intended to
avoid problems with double inclusion of header files, so they should
only be used in *.h and *.hxx files.
Corresponding elastix pull request:
https://github.com/SuperElastix/elastix/pull/345

STYLE: Remove "include guards" from cxx files

---

Modules/Core/Common/include/itkWin32OutputWindow.h

Fixed two Clang-Tidy (LLVM 11.0) warnings:
> 'DisplayText' overrides a member function but is not marked 'override' [clang-diagnostic-inconsistent-missing-override]
> use '= default' to define a trivial default constructor [modernize-use-equals-default]

STYLE: Use C++11 override and `= default` in itkWin32OutputWindow.h

---

Modules/Core/Common/include/itkPolygonCell.hxx
Modules/Core/Common/src/itkObjectFactoryBase.cxx
Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshPolygonCell.h
Modules/Filtering/Thresholding/include/itkIntermodesThresholdCalculator.hxx
Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx
Modules/IO/MRC/test/itkMRCImageIOTest.cxx
Modules/IO/TransformMINC/src/itkMINCTransformIO.cxx
Modules/IO/VTK/test/itkVTKImageIO2Test.cxx
Modules/Nonunit/Review/src/itkVoxBoCUBImageIO.cxx
Modules/Numerics/Statistics/include/itkHistogram.hxx
Modules/Segmentation/KLMRegionGrowing/include/itkKLMRegionGrowImageFilter.hxx

Improved code readability and simplicity by using the member function `back()`.
With help from Perl scripts like:
find . \( -iname *.cxx -and ! -path *ThirdParty* \) -exec perl -pi -w -e 's/\[.+\.size\(\) - 1\]/.back()/g;' {} \;
Note: such adjustments could not be applied to itkTxtTransformIO.cxx,
itkQuadEdgeMeshDecimationQuadricElementHelper.h, and
itkN4BiasFieldCorrectionImageFilter.hxx, because they use `vnl_vector`,
which currently does not (yet) have a `back()` member function!

STYLE: Replace `container[container.size() - 1]` by `container.back()`

---

Wrapping/Generators/Python/Tests/CMakeLists.txt
Wrapping/Generators/Python/Tests/dicomSeries.py
Wrapping/Generators/Python/itkExtras.py

Adding feature to Python `imread` function.  If the filename provided is a directory then the directory is assumed to be for a DICOM image and the filename is replaced with list of DICOM filenames within that directory.

ENH: Read DICOM directory with Python imread

---

Modules/Filtering/ImageFilterBase/include/itkCastImageFilter.hxx
Modules/Filtering/ImageFilterBase/test/itkCastImageFilterTest.cxx

This pull request resolves the issue that the use of the `OutputPixelType` constructor in `itkCastImageFilter::DynamicThreadedGenerateDataDispatched` does not work when the pixel type is a `VariableLengthVector`.

ENH: Support for VariableLengthVector in CastImageFilter

---

Modules/Core/Transform/test/itkCenteredRigid2DTransformTest.cxx
Modules/Core/Transform/test/itkEuler2DTransformTest.cxx
Modules/Filtering/ImageGrid/test/itkCoxDeBoorBSplineKernelFunctionTest.cxx
Modules/Filtering/ImageGrid/test/itkCoxDeBoorBSplineKernelFunctionTest2.cxx
Modules/IO/TransformBase/test/itkTransformFileReaderTest.cxx
Modules/IO/TransformBase/test/itkTransformFileWriterTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkLevelSetDomainPartitionImageTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkLevelSetDomainPartitionImageWithKdTreeTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkLevelSetEquationBinaryMaskTermTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkLevelSetEquationOverlapPenaltyTermTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkMultiLevelSetDenseImageSubset2DTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkMultiLevelSetMalcolmImageSubset2DTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkMultiLevelSetShiImageSubset2DTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkMultiLevelSetWhitakerImageSubset2DTest.cxx

Various tests did fail directly on the condition `if (argc < 1)`, even
if they would not actually use any command-line argument.
This commit removed these checks from those tests, in order to allow
running such a test directly from the command-line by starting its
TestDriver executable and then entering its test number.

ENH: Allow running various tests without arguments

---

Modules/IO/TransformBase/src/itkTransformIOFactory.cxx

Removed the local `possibleTransformIO` variable from the member
function `TransformIOFactoryTemplate::CreateTransformIO`, as it appears
unnecessary to put all IO objects into that list, before finding the one
that can process the specified file path.
Reduced amount of duplicate code for read and write, and improved
const-correctness.

STYLE: Remove local possibleTransformIO from TransformIOFactoryTemplate

---

Modules/Bridge/NumPy/wrapping/test/itkPyVectorContainerTest.py
Modules/Core/Common/wrapping/itkVectorContainer.wrap

COMP: Breaks Continuous test; disable until debugged.
The Continuous test that is failing is `Modules/Bridge/NumPy/wrapping/test/itkPyVectorContainerTest.py`.
Also, revert the commit (Pull Request #2113) to `Modules/Core/Common/wrapping/itkVectorContainer.wrap` that was supposed to be the fix for `itkPyVectorContainerTest.py`, but wasn't.

COMP: Broken Continuous test; disable until debugged.

---

Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_vector.cxx
Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_vector_fixed_ref.cxx
Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector.h
Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector_fixed.h

Expand the vnl_vector and vnl_vector_fixed to include stl compatible "front" and "back" methods.

20201119 vxl update

---

Modules/IO/TransformInsightLegacy/src/itkTxtTransformIO.cxx

Before processing the content of its input file,
`TxtTransformIOTemplate::Read()` copied the content to a raw `char`
buffer, which was then inserted into to an output string stream, whose
string was then copied into `data`.
None of this appears necessary, as the content of the file can also be
processed line by line, by a `while (std::getline(in, line))` loop,
according to this commit.

STYLE: TxtTransformIO Read() no longer copy input file to data string

---

Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.hxx
Modules/Filtering/QuadEdgeMeshFiltering/include/itkQuadEdgeMeshDecimationQuadricElementHelper.h
Modules/IO/TransformInsightLegacy/src/itkTxtTransformIO.cxx

Follow-up to pull request #2099 (STYLE: Replace `container[container.size() - 1]` by `container.back()`), commit 5eb4697 (6 November 2020)
Discussed with Hans @hjmjohnson at https://github.com/InsightSoftwareConsortium/ITK/pull/2099#pullrequestreview-525170416

STYLE: Replace `vnl_vector[vnl_vector.size() - 1]` by vnl_vector.back(). Also add vnl_vector::front()

---

Modules/Core/Transform/include/itkMatrixOffsetTransformBase.hxx
Modules/Core/Transform/test/CMakeLists.txt
Modules/Core/Transform/test/itkMatrixOffsetTransformBaseGTest.cxx

When a user provided too few parameters as argument to
`MatrixOffsetTransformBase::SetFixedParameters`, the member function
would have undefined behavior, which would typically just cause a crash.
This issue affects transforms derived from `MatrixOffsetTransformBase`, including:
AffineTransform
AzimuthElevationToCartesianTransform
CenteredAffineTransform
Euler2DTransform
FixedCenterOfRotationAffineTransform
QuaternionRigidTransform
Rigid2DTransform
Rigid3DTransform
ScalableAffineTransform
ScaleLogarithmicTransform
ScaleSkewVersor3DTransform
ScaleTransform
ScaleVersor3DTransform
Similarity2DTransform
Similarity3DTransform
VersorRigid3DTransform
VersorTransform
A crash could occur when reading a transform from a transform file, when
this file has an insufficient number of fixed parameters. …

BUG: Fix MatrixOffsetTransformBase SetFixedParameters if too few params

---

Modules/Core/Transform/include/itkMatrixOffsetTransformBase.hxx
Modules/Core/Transform/test/CMakeLists.txt
Modules/Core/Transform/test/itkMatrixOffsetTransformBaseGTest.cxx

When the argument passed to `MatrixOffsetTransformBase` member function
`SetFixedParameters` would contain less than `NInputDimensions` values,
the member function would have undefined behavior, which would typically
just cause a crash.
This issue affects transforms derived from `MatrixOffsetTransformBase`, including:
AffineTransform
AzimuthElevationToCartesianTransform
CenteredAffineTransform
Euler2DTransform
FixedCenterOfRotationAffineTransform
QuaternionRigidTransform
Rigid2DTransform
Rigid3DTransform
ScalableAffineTransform
ScaleLogarithmicTransform
ScaleSkewVersor3DTransform
ScaleTransform
ScaleVersor3DTransform
Similarity2DTransform
Similarity3DTransform
VersorRigid3DTransform
VersorTransform
A crash could occur when reading a transform from a transform file, when
this file has an …

For release: BUG: Fix MatrixOffsetTransformBase SetFixedParameters if too few params

---

Modules/Core/Common/include/itkOptimizerParameters.h

Worked around an apparent compiler bug in GCC 4.8 (which seems to be
fixed with GCC 4.9.2), causing a compile error from GCC 4.8.4 at
https://open.cdash.org/viewBuildError.php?buildid=6897873 saying:
> Core/Common/include/itkOptimizerParameters.h:53:3:
> error: converting to 'std::unique_ptr< itk::OptimizerParametersHelper>'
> from initializer list would use explicit constructor...
Reported by Bradley Lowekamp (@blowekamp) at
https://github.com/InsightSoftwareConsortium/ITK/pull/2114#issuecomment-733741732

COMP: Work around GCC-4.8 error converting to OptimizerParametersHelper

---

Wrapping/Generators/CastXML/CMakeLists.txt

To address:
FAILED:
/home/matt/bin/ITK-Wrap-Release/Wrapping/elxParameterObject.xml cd /home/matt/bin/ITKElastix-Wrap-Release/Wrapping/Modules/Elastix && /home/matt/bin/ITKElastix-Wrap-Release/Wrapping/Generators/CastXML/castxml/bin/castxml -o /home/matt/bin/ITK-Wrap-Release/Wrapping/elxParameterObject.xml --castxml-gccxml --castxml-start _wrapping_ --castxml-cc-gnu "(" /usr/bin/c++ -Wno-aggressive-loop-optimizations -fopenmp -std=c++11 ")" -w -c @/home/matt/bin/ITK-Wrap-Release/Wrapping/Elastix.castxml.inc /home/matt/bin/ITK-Wrap-Release/Wrapping/elxParameterObject.cxx
In file included from /home/matt/bin/ITK-Wrap-Release/Wrapping/elxParameterObject.cxx:11:
In file included from /home/matt/src/ITK/Modules/Core/Common/include/itkSymmetricSecondRankTensor.h:29: …

COMP: Remove -fopenmp in castxml invocation

---

Wrapping/Generators/Python/Tests/extras.py
Wrapping/Generators/Python/itk/support/itkExtras.py

Resolves #1348 by adding `ttype` keyword parameter to the functions `_GetArrayFromImage`, `GetArrayFromImage`, `array_from_image`, `GetArrayViewFromImage`, `array_view_from_image`, `_GetImageFromArray`, `GetImageFromArray`, `image_from_array`, `GetImageViewFromArray`, `image_view_from_array`, `_GetArrayFromVnlObject`, `GetArrayFromVnlVector`, `array_from_vnl_vector`, `GetArrayViewFromVnlVector`, `GetArrayFromVnlMatrix`, `GetArrayViewFromVnlMatrix`, `array_from_vnl_matrix`, `_GetVnlObjectFromArray`, `GetVnlVectorFromArray`, `vnl_vector_from_array`, `GetVnlMatrixFromArray`, and `vnl_matrix_from_array`.

ENH: Support `ttype` parameter for numpy<->ITK conversions

---

Modules/Core/SpatialObjects/include/itkTubeSpatialObject.h

A function name was changed to correct grammar and improve clarity, but
it broke backwards compatibility.   This request adds a function
with the old name to restore backward compatibility.

COMP: Adds ComputeTangentAndNormals() function

---

Wrapping/Generators/Python/CMakeLists.txt

With MSVC 2019, even using the 64-bit host toolchain tools as suggested:
https://docs.microsoft.com/en-us/cpp/build/how-to-enable-a-64-bit-visual-cpp-toolset-on-the-command-line?view=msvc-160
The Python package build fails after enabling 4D image support with:
LINK: command "C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx86\x64\link.exe /nologo @CMakeFiles\ITKImageIntensityPython.rsp /out:Wrapping\Generators\Python\itk\_ITKImageIntensityPython.pyd /implib:lib\ITKImageIntensityPython.lib /pdb:Wrapping\Generators\Python\itk\_ITKImageIntensityPython.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO /INCREMENTAL:NO /LTCG /MANIFEST /MANIFESTFILE:Wrapping\Generators\Python\itk\_ITKImageIntensityPython.pyd.manifest" failed (exit code 1257) with the following output: …

COMP: Do not enable whole program optimization with MSVC

---

Testing/ContinuousIntegration/AzurePipelinesMacOS.yml
Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml

To work around:
> CMake Error: install(EXPORT "ITKTargets" ...) includes target "gdcmjpeg8" more than once in the export set.
Likely related to:
https://gitlab.kitware.com/cmake/cmake/-/issues/21529
Downgrade CMake from 3.19.1 to 3.18.4 until 3.19.2 is released.

COMP: Use CMake 3.18.4 in macOS CI builds

---

Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx

The class `InvalidImageMomentsError` appears unused, untested, and
undocumented. It is not defined in a .h file, so it is not a part of
the public API of ITK.
The class was introduced by Jim Miller, September 13, 2001,
"ENH: Modifications to pipeline to throw an exception...",
commit 78e889ed46d36131f5de552d76bd5326121222ae
Its uses were removed by Luis Ibanez, 26 April 2004,
"ENH: Explicit exception throws replaces with itkExceptionMacro...",
commit 96d0ce4317e1047de9b9ef2aa153a1ea98d24138
This commit removes the class to avoid conflicts between ITK and elastix,
which happened to have a copy of the very same class definition:
https://github.com/SuperElastix/elastix/blob/5.0.1/Common/Transforms/itkAdvancedImageMomentsCalculator.hxx#L29

COMP: Remove InvalidImageMomentsError from itkImageMomentsCalculator.hxx

---

Wrapping/Generators/Python/itk/support/itkTemplate.py

When exactly one type must be supplied via `ttype`, the following three are now equivalent
```python
ttype=ImageType
ttype=(ImageType,)
ttype=[ImageType]
```
so long as `ImageType` is itself a type, not a tuple or list.  When other than exactly one type needs to be supplied, it continues to be the case that only the tuple and list forms work.

ENH: ttype can be `ImageType` whenever `(ImageType,)` is accepted

---

Wrapping/Generators/Python/Tests/CMakeLists.txt
Wrapping/Generators/Python/Tests/PythonTypeTest.py
Wrapping/Generators/Python/Tests/findEmptyClasses.py
Wrapping/Generators/Python/Tests/multiprocess_lazy_loading.py
Wrapping/Generators/Python/itk/__init__.py
Wrapping/Generators/Python/itk/support/itkBuildOptions.py
Wrapping/Generators/Python/itk/support/itkExtras.py
Wrapping/Generators/Python/itk/support/itkLazy.py
Wrapping/Generators/Python/itk/support/itkTemplate.py

The loading of modules in python *must* occur as a
single atomic transaction in multiprocessing environments (i.e.
the module should only be loaded by one thread).
The LazyLoading of ITK did not treat the loading of
modules as an atomic transaction, and multiple threads
would attempt to load the cascading dependencies out of
order.
The `getattr` override that allows LazyLoading to work
in the case where the module is *not* loaded now blocks
while the first thread completes the delayed module loading.
After the first thread completes module load as an atomic
transaction, the other threads fall through (skip loading)
and return the value requested.
Need to use a recursive lock for thread ownership so that the
first thread can acquire a RLock as often as needed while
recursively processing …

BUG: Fix multiprocessing imread LazyLoading failures

---

Modules/IO/Meta/test/itkMetaImageIOMetaDataTest.cxx

Added a field whose value is a string of 32767 characters to the test,
to ensure that the following MetaIO improvement is included:
"ENH: MetaIO support reading strings of >= 500 chars (up to 32767 chars)"
Pull request https://github.com/Kitware/MetaIO/pull/93
Commit https://github.com/Kitware/MetaIO/commit/c9db10ecf0ee2193cfc57f8b01674ca0ef305316
No longer printed the content of a field in case of a correct test
result, as it would produce too much noise with such a large string.

ENH: Test that MetaIO supports a string value of up to 32767 chars

---

Modules/Core/Common/test/itkImageDuplicatorTest2.cxx
Modules/Core/Common/test/itkImageRandomIteratorTest2.cxx
Modules/Core/Common/test/itkStreamingImageFilterTest3.cxx
Modules/Core/Common/test/itkSymmetricSecondRankTensorImageReadTest.cxx
Modules/Core/Common/test/itkSymmetricSecondRankTensorImageWriteReadTest.cxx
Modules/Filtering/BiasCorrection/test/itkN4BiasFieldCorrectionImageFilterTest.cxx
Modules/IO/ImageBase/include/itkImageFileWriter.h

Inspired by #2102 and https://github.com/dzenanz/ITKMorphologicalContourInterpolation/commit/a9ac128f57078cb7c71d1abacd1ce8fce02f1c96.

ENH: add a convenience function WriteImage

---

Wrapping/Generators/Python/Tests/extras.py

ENH: test for ttype=`ImageType` instead of `(ImageType,)`
Adding testing for new functionality added with Pull Request #2141 (Commit 5741f877be0116190000fbe47f2679039c2eddbb).

ENH: add additional assertions for `ttype` parameter

---

.gitattributes

The ghostflow-check-master check failure needs to be
ignored for ThirdParty HDF5 large files.

ENH: Ignore huge file warning for HDF5 paths

---

Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMParser.cxx

Fixed the following warning from Visual C++ 2019:
> DICOMParser.cxx(830,14): warning C4834: discarding return value of
> function with 'nodiscard' attribute
Potentially a serious bug.

BUG: DICOMParser should use `&&` instead of comma in for-loop condition

---

Modules/Core/Common/include/itkMetaProgrammingLibrary.h
Modules/IO/ImageBase/ITKKWStyleOverwrite.txt
Modules/IO/ImageBase/include/itkImageFileWriter.h
Modules/IO/ImageBase/test/CMakeLists.txt
Modules/IO/ImageBase/test/itkWriteImageFunctionGTest.cxx

This is a follow-up to #2160 which was merged a bit too fast.

ENH: remove redundant WriteImage overloads

---

Modules/Core/ImageAdaptors/test/itkVectorImageTest.cxx
Modules/Core/Mesh/test/itkTriangleMeshToBinaryImageFilterTest.cxx
Modules/Core/Mesh/test/itkTriangleMeshToBinaryImageFilterTest1.cxx
Modules/Core/Mesh/test/itkTriangleMeshToBinaryImageFilterTest2.cxx
Modules/Core/Mesh/test/itkTriangleMeshToBinaryImageFilterTest3.cxx
Modules/Core/Mesh/test/itkTriangleMeshToBinaryImageFilterTest4.cxx
Modules/Core/SpatialObjects/test/itkBoxSpatialObjectTest.cxx
Modules/Core/TestKernel/src/itkTestDriverInclude.cxx
Modules/Core/Transform/test/itkBSplineDeformableTransformTest2.cxx
Modules/Core/Transform/test/itkBSplineDeformableTransformTest3.cxx
Modules/Core/Transform/test/itkBSplineTransformInitializerTest1.cxx
Modules/Core/Transform/test/itkBSplineTransformTest2.cxx
Modules/Core/Transform/test/itkBSplineTransformTest3.cxx

Replaced explicit creation of `itk::ImageFileWriter` objects by calling
the new `itk::WriteImage` convenience function. Aims to reduces the
amount of boilerplate code.

STYLE: Use the WriteImage convenience function anywhere in Modules/Core

---

Modules/Core/Common/include/itkHexahedronCell.h
Modules/Core/Common/include/itkHexahedronCell.hxx

When compiling with agressive IPO optimizations,
some invalid code constructs were identified where
the loop iterations did not match the size of the
objects being indexed.
The recent change to have Python compile for 4D cases
identified issues for code bases that are only valid
at exactly 3D code.
The HexahedronCell algorithms are only valid for 3D cases,
but the Spatial Object reader for Mesh instantiates all the
mesh objects (both those that are dimension agnostic, and those
with limited dimension support) to allow a consistent interface
implementation.
The solution here to avoid compiler warnings is to hard-code the
HexahedronCell algorithms to exactly 3D, add Exceptions if the
algorithms are used for other dimensions.
ITK/Modules/Core/Common/include/itkHexahedronCell.hxx: In member …

COMP: Avoid compiler warnings with IPO

---

Wrapping/Generators/CastXML/CMakeLists.txt

Incompatibilties with advanced compiler optimization
flags are not properly managed with CASTXML.
export FAILING_FLAG="-mfma"
ITK-bld/Wrapping/Modules/ITKCommon && \\
ITK-bld/Wrapping/Generators/CastXML/castxml/bin/castxml \\
-o ITK-bld/Wrapping/itkPointSetToImageFilter.xml --castxml-gccxml \\
--castxml-start _wrapping_ \\
--castxml-cc-gnu "(" /usr/bin/c++ ${FAILING_FLAG} ")" \\
-w \\
-c @ITK-bld/Wrapping/ITKCommon.castxml.inc ITK-bld/Wrapping/itkPointSetToImageFilter.cxx
In file included from ITK/Modules/ThirdParty/Eigen3/src/itkeigen/../itkeigen/Eigen/Core:391:
ITK/Modules/ThirdParty/Eigen3/src/itkeigen/../itkeigen/Eigen/src/Core/arch/AVX/PacketMath.h:169:54: error: invalid output size for constraint '+x'
__asm__("vfmadd231ps %[a], %[b], %[c]" : [c] "+x" (res) : [a] "x" (a), [b] "x" …

BUG: CASTXML fails with aggressive optimizer flags

---

Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeLists.txt

All outputs dependencies need to be listed for
the custom command.
ninja: error: 'cmake_object_order_depends_target_hdf5-shared_DEBUG',
needed by 'Modules/ThirdParty/HDF5/src/itkhdf5/shared/H5Tinit.c',
missing and no known rule to make it
Upstream HDF5 patch also submitted.
Issue present in "Ninja Multi-Config" builds with shared libraries turned on.

BUG: Missing output dependency shared/H5init.c

---

Modules/Numerics/Eigen/test/itkEigenAnalysis2DImageFilterTest.cxx

A newly added test that exercises 3D
support did not initialize the size
of the image in the 3rd dimension.
Changed 2D hard coded size to fill
in the size in all dimensions.

BUG: New test for 3D support

---

Modules/Core/SpatialObjects/include/itkContourSpatialObject.h

Make indentation in `itk::ContourSpatialObject.h` conform to the ITK
style.

STYLE: Make indentation in `itk::ContourSpatialObject.h` conform to ITK

---

CMakeLists.txt

Place the ITK library .dll's next to the CPython extension modules so
they can be loaded on Python import. To address the shared library
Windows Python CI test failures:
181: Loading ITKPyBase... done
181: Loading ITKCommon... Traceback (most recent call last):
181:   File "D:/a/1/s/Modules/Core/SpatialObjects/wrapping/test/SpatialObjectTest.py", line 24, in <module>
181:     SOType = itk.SpatialObject[dim]
181:   File "D:\a\1\s-build\Wrapping\Generators\Python\itk\support\itkLazy.py", line 78, in __getattribute__
181:     itkBase.itk_load_swig_module(module, namespace)
181:   File "D:\a\1\s-build\Wrapping\Generators\Python\itk\support\itkBase.py", line 102, in itk_load_swig_module
181:     itk_load_swig_module(dep, namespace)
181:   File …

COMP: Set runtime output directory for Windows Python tests

---

Modules/Core/Transform/include/itkEuler3DTransform.hxx
Modules/Core/Transform/test/CMakeLists.txt
Modules/Core/Transform/test/itkEuler3DTransformGTest.cxx

When the argument passed to `Euler3DTransform` member function
`SetFixedParameters` would contain less than `InputSpaceDimension`
values, the member function would have undefined behavior, which would
typically just cause a crash.
A crash could occur when reading a transform from a transform file, when
this file has an insufficient number of fixed parameters. It was
encountered when loading a transform within 3DSlicer (Preview Release
version 4.13.0-2020-12-15).
The fix consists of throwing an exception when the number of fixed
parameters is too small. A GoogleTest unit test is included.
Follow-up to:
"BUG: Fix MatrixOffsetTransformBase SetFixedParameters if too few params"
Pull request: https://github.com/InsightSoftwareConsortium/ITK/pull/2118
Commit: …

BUG: Fix Euler3DTransform::SetFixedParameters crash when too few params

---

Modules/Core/Common/include/itkEventObject.h
Modules/Core/Common/src/itkEventObject.cxx

Require that macros end with a semi-colon so that
the macros look function-like to the clang-format
configurations.
Requiring a semi-colon makes the code easier to
parse, format, and read.
Use ITK_LEGACY_REMOVE to disable old, slightly
incorrect code that is recommended not to be used.

STYLE: Fix clang-format styling require macro ';' end

---

Modules/Core/Common/test/itkEventObjectTest.cxx

VS2017 produces errors when compiling line 24 of itkEventObjectTest:
>> ITK\Modules\Core\Common\test\itkEventObjectTest.cxx(24): error C2065: 'TestEvent': undeclared identifier
>> ITK\Modules\Core\Common\test\itkEventObjectTest.cxx(24): error C2275: 'itk::UserEvent': illegal use of this type as an expression
Updating that test to use the preferred itkEventDefinitionMacro() and itkEventDeclarationMacro() fixes this issue.

BUG: Update itkEventObjectTest to use new event macros

---

Modules/Core/Common/include/itkImage.h
Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkImageGTest.cxx

Added `operator==` and `operator!=` overloads which tell whether or not
two images are equal, based on their value semantics (not just their
addresses in memory).
Allowed testing if two images (not just image pointers) compare equal or
unequal by using GoogleTest `EXPECT_EQ(image1, image2)` and
`EXPECT_NE(image1, image2)`.

ENH: Add operator== and operator!= to itk::Image

---

Modules/IO/DCMTK/src/itkDCMTKSeriesFileNames.cxx

Print all `itk::DCMTKSeriesFileNames` ivars in `PrintSelf`.
Take advantage of the commit to use the vector printing capabilities
offered by `itk::PrintHelper`.

ENH: Print all `itk::DCMTKSeriesFileNames` ivars in `PrintSelf`

---

Modules/IO/DCMTK/src/itkDCMTKSeriesFileNames.cxx

Fix `itk::DCMTKSeriesFileNames::GetOutputFileNames()` returned ivar.

BUG: Fix `itk::DCMTKSeriesFileNames::GetOutputFileNames()` returned ivar

---

Modules/Filtering/DisplacementField/test/itkInverseDisplacementFieldImageFilterTest.cxx

Improve coverage for `itk::InverseDisplacementFieldImageFilter` class:
input argument checking and test finishing message).

ENH: Improve coverage for `itk::InverseDisplacementFieldImageFilter` class

---

Modules/Core/ImageFunction/test/itkRayCastInterpolateImageFunctionTest.cxx

Improve coverage `itk::RayCastInterpolateImageFunction` class:
- Remove explicit calls to the `Print` method and rely on the basic
test finishing message).

ENH: Improve coverage for `itk::RayCastInterpolateImageFunction` class

---

Modules/IO/DCMTK/test/itkDCMTKSeriesReadImageWrite.cxx
Modules/IO/DCMTK/test/itkDCMTKSeriesStreamReadImageWrite.cxx

Improve coverage for `itk::DCMTKSeriesFileNames` class:
- Test the exceptions.

ENH: Improve coverage for `itk::DCMTKSeriesFileNames` class

---

Modules/IO/DCMTK/test/itkDCMTKSeriesReadImageWrite.cxx

Effectively test filename values causing exceptions in
`itk::DCMTKSeriesFileNames`.

ENH: Effectively test filename values causing exceptions

---

Modules/Filtering/MathematicalMorphology/test/itkClosingByReconstructionImageFilterTest.cxx
Modules/Filtering/MathematicalMorphology/test/itkGrayscaleConnectedClosingImageFilterTest.cxx
Modules/Filtering/MathematicalMorphology/test/itkGrayscaleConnectedOpeningImageFilterTest.cxx
Modules/Filtering/MathematicalMorphology/test/itkOpeningByReconstructionImageFilterTest.cxx
Modules/Filtering/MathematicalMorphology/test/itkOpeningByReconstructionImageFilterTest2.cxx

Improve coverage for `MathematicalMorphology` module classes:
- Remove explicit calls to the `Print` method and rely on the basic
input argument checking, test finishing message, make the types and
variables dwell closer to the place where they are instantiated, etc.)

ENH: Improve coverage for `MathematicalMorphology` module classes.

---

CMake/ITKSetPython3Vars.cmake

Support for Python 3.5 has been dropped.

COMP: Only search for Python 3.6 and above

---

Modules/Core/Common/include/itkFixedArray.h
Modules/Core/Common/include/itkFixedArray.hxx
Modules/Core/Common/test/itkFixedArrayGTest.cxx

Eases writing generic code that supports both `std::array` and `FixedArray`.
Follow-up to "ENH: Add data() and size() member functions to FixedArray"
pull request #1800 commit 38939ff86d97777e8d507963c13a2221e86b601e
by Pablo Hernandez-Cerdan (@phcerdan), May 10, 2020

ENH: Declare FixedArray::size() constexpr

---

Modules/Core/Common/test/itkImageDuplicatorTest2.cxx
Modules/Core/Common/test/itkImageRandomIteratorTest2.cxx
Modules/Core/Common/test/itkSymmetricSecondRankTensorImageReadTest.cxx
Modules/Core/Common/test/itkSymmetricSecondRankTensorImageWriteReadTest.cxx
Modules/IO/ImageBase/include/itkImageFileReader.h

Added `itk::ReadImage<TOutputImage>(const std::string & filename)`, to
allows simplifying the C++ code for reading an image.
Suggested by Dženan Zukić (@dzenanz) at
https://github.com/InsightSoftwareConsortium/ITK/pull/2102#issuecomment-723232937
Follow-up to:
"ENH: add a convenience function WriteImage"
Pull request: #2160
Commit: 60b0984d4196841844424e33963e161f3f0c709d
Replaced manual creation of `ImageFileReader` objects in Common tests by
calls to the new `itk::ReadImage` function. Also removed related
redundant try-catch blocks from SymmetricSecondRankTensorImage tests.

ENH: Add convenience function ReadImage

---

Modules/IO/ImageBase/test/itkWriteImageFunctionGTest.cxx

Tests that an image written by `itk::WriteImage` can be read back,
without loss of data.
Uses two recently added functions:
- `itk::ReadImage`: pull request #2184 commit aeea88b1925e400fa6df099871b149a37f1dee17
- `operator==` for images: pull request #2188 commit 7f3337d27ee684aa4ab6ccbd294603926895ee82
(`operator==` is called internally by GoogleTest `EXPECT_EQ`.)

ENH: Extend ITKWriteImageFunctionTest by reading the written image back

---

Modules/Core/Common/include/itkConceptChecking.h
Modules/Core/Common/include/itkConstantBoundaryCondition.hxx
Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx

warning: variable 'a' is uninitialized when passed as a const reference argument here [-Wuninitialized-const-reference]

COMP: Use of uninitialzed variable warning

---

Modules/IO/DCMTK/src/itkDCMTKSeriesFileNames.cxx
Modules/IO/DCMTK/test/itkDCMTKSeriesReadImageWrite.cxx
Modules/IO/DCMTK/test/itkDCMTKSeriesStreamReadImageWrite.cxx

Fix `itk::DCMTKSeriesFileNames` compilation issues:
- The filename and series UID container types seem not be overloaded for
printing.
- There was a call that was not checking the intended left-hand and
right-hand arguments in the `itkDCMTKSeriesReadImageWrite.cxx` test
- The `itkTestingMacros.h` had not beein include in
`itkDCMTKSeriesStreamReadImageWrite.cxx`.
Fixes:
```
/tmp/bld/ITK/Modules/IO/DCMTK/src/itkDCMTKSeriesFileNames.cxx: In member
function 'virtual void itk::DCMTKSeriesFileNames::PrintSelf(std::ostream&,
itk::Indent) const':
bld/ITK/Modules/IO/DCMTK/src/itkDCMTKSeriesFileNames.cxx:197:16: error:
cannot bind 'std::basic_ostream<char>' lvalue to
'std::basic_ostream<char>&&'
os << indent << "InputFileNames: " << m_InputFileNames << std::endl;
^ …
```

COMP: Fix `itk::DCMTKSeriesFileNames` compilation issues

---

Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.h

Minor, but annoying compiler warning suppression.

Vxl update

---

Modules/IO/MeshBase/test/CMakeLists.txt
Modules/IO/MeshBase/test/itkMeshFileReaderTest.cxx

Add test for `itk::MeshFileReader` class.

ENH: Add test for `itk::MeshFileReader` class

---

Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx

The macros now require a `;` at the end of their respective line. A PR was pushed updating the definitions to fit this requirement. However, the `DCMTK` module was not corrected. This verifies the `;` is placed accordingly.

BUG: Missing end-of line macro changes for DCMTK module

---

Modules/IO/DCMTK/test/itkDCMTKSeriesReadImageWrite.cxx

Fix `itkDCMTKSeriesREadImageWrite.cxx` test failures: the tested
conditions throw warnings and not exceptions. Do not expect an exception
and simply call the statement to exercise the warning condition.
Fixes:
```
Trying it->SetInputDirectory(inputDirectory)
WARNING: In /tmp/bld/ITK/Modules/IO/DCMTK/src/itkDCMTKSeriesFileNames.cxx,
line 58
DCMTKSeriesFileNames (0x55d8574bf600): You need to specify a directory
where the DICOM files are located
Failed to catch expected exception
In /tmp/bld/ITK/Modules/IO/DCMTK/test/itkDCMTKSeriesReadImageWrite.cxx,
line 60
```
Raised at:
https://open.cdash.org/viewTest.php?onlyfailed&buildid=6958922

BUG: Fix `itkDCMTKSeriesREadImageWrite.cxx` test failures

---

Modules/Core/Common/test/itkImageDuplicatorTest.cxx

Increase `itk::ImageDuplicator` class coverage:

ENH: Increase `itk::ImageDuplicator` class coverage

---

Modules/Core/Transform/test/itkScaleLogarithmicTransformTest.cxx

Increase `itk::ScaleLogarithmicTransform` class coverage:
Take advantage of the commit to use more meaningful variable names and
error messages.

ENH: Increase `itk::ScaleLogarithmicTransform` class coverage

---

Modules/Filtering/LabelMap/include/itkObjectByObjectLabelMapFilter.hxx

Remove unnecessary IO member filter name of class print calls in
`PrintSelf` method.
The related `itkObjectByObjectLabelMapFilterTest.cxx` test was segfaulting
when the `ITK_EXERCISE_BASIC_OBJECT_METHODS` macro was calling the
`PrintSelf` member. The segfaults were caused by the `m_InputFilter` and
`m_OutputFilter` members being initialized to the null pointer, and hence
calling the `GetNameOfClass()` method using a null pointer.
Fixes the segfault errors raised at:
https://open.cdash.org/viewTest.php?onlyfailed&buildid=6959862
https://open.cdash.org/viewTest.php?onlyfailed&buildid=6960004
https://open.cdash.org/viewTest.php?onlyfailed&buildid=6959902
Take advantage of the commit to remove the `GetPointer` call: the `<<`
operator is overloaded to print all relevant smart pointer data …

BUG: Remove unnecessary IO member filter name of class print calls

---

Modules/Filtering/ImageGrid/test/itkBSplineControlPointImageFunctionTest.cxx

Increase `itk::BSplineControlPointImageFunction` class coverage:

ENH: Increase `itk::BSplineControlPointImageFunction` class coverage

---

Modules/IO/DCMTK/test/itkDCMTKSeriesReadImageWrite.cxx

Fix undeclared identifier error.
Fixes:
```
bld/ITK/Modules/IO/DCMTK/test/itkDCMTKSeriesReadImageWrite.cxx:31:0:
/tmp/bld/ITK/Modules/IO/DCMTK/test/itkDCMTKSeriesReadImageWrite.cxx: In function 'int itkDCMTKSeriesReadImageWrite(int, char**)':
bld/ITK/Modules/IO/DCMTK/test/itkDCMTKSeriesReadImageWrite.cxx:61:50: error: 'inputDirectory' was not declared in this scope
ITK_TRY_EXPECT_EXCEPTION(it->SetInputDirectory(inputDirectory));
^
bld/ITK/Modules/Core/TestKernel/include/itkTestingMacros.h:94:5: note: in definition of macro 'ITK_TRY_EXPECT_EXCEPTION'
command;
\
^
bld/ITK/Modules/IO/DCMTK/test/itkDCMTKSeriesReadImageWrite.cxx:60:16: warning: unused variable 'pInputDirectory' [-Wunused-variable]
const char * pInputDirectory = nullptr;
^
```
Raised at: …

COMP: Fix undeclared identifier

---

Modules/Filtering/LabelMap/test/CMakeLists.txt
Modules/Filtering/LabelMap/test/itkObjectByObjectLabelMapFilterTest.cxx

Increase `itk::ObjectByObjectLabelMapFilter` class coverage:
- Add the corresponding test arguments to the appropriate
`CMakeLists.txt`test driver command.

ENH: Increase `itk::ObjectByObjectLabelMapFilter` class coverage

---

Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.h
Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest1.cxx
Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest2.cxx
Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest3.cxx

Use the `itkBooleanMacro` macro for the boolean ivars in
`itk::VectorGradientMagnitudeImageFilter` to avoid boilerplate code.
Mark the corresponding previous methods as deprecated.

STYLE: Use `itkBooleanMacro` to avoid boilerplate code

---

Modules/Filtering/ImageFeature/test/CMakeLists.txt
Modules/Filtering/ImageFeature/test/itkZeroCrossingBasedEdgeDetectionImageFilterTest.cxx
Modules/Filtering/ImageFeature/test/itkZeroCrossingImageFilterTest.cxx

Increase `ITKImageFeature` module classes coverage:
- Add the corresponding test arguments to the appropriate`CMakeLists.txt`
test driver command.
- Remove the global `try/catch` block and use the
`ITK_TRY_EXPECT_NO_EXCEPTION` macro around the statement that is
liable to throw and exception to avoid boilerplate code and to improve
readability.

ENH: Increase `ITKImageFeature` module classes coverage

---

Modules/Filtering/ImageGradient/test/CMakeLists.txt
Modules/Filtering/ImageGradient/test/itkGradientImageFilterTest.cxx
Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest1.cxx
Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest2.cxx
Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest3.cxx

Increase `ITKImageGradient` module classes coverage:
- Add the corresponding test arguments to the appropriate
`CMakeLists.txt` test driver command.
- Remove the global `try/catch` block and use the
`ITK_TRY_EXPECT_NO_EXCEPTION` macro around the statement that is liable
to throw and exception to avoid boilerplate code and to improve
readability.
- Remove explicit calls to the `Print` method and rely on the basic method
exercising macro call.

ENH: Increase `ITKImageGradient` module classes coverage

---

Wrapping/Generators/Python/CMakeLists.txt

With the module refactoring, these were installed directly into the
site-packages/ directory.

BUG: Python support module and __init__.py install location

---

Modules/ThirdParty/HDF5/src/itkhdf5/config/cmake_ext_mod/HDFMacros.cmake

The OUTPUT_NAME variants, e.g. OUTPUT_NAME_RELEASE, interfere with the
OUTPUT_NAME set by the itk_module_target_name macro.
libitkhdf5.so ->  libitkhdf5-shared-5.2.so
Closes #1971

BUG: Prevent HDF5 from overwritting ITK library names

---

Examples/IO/VisibleHumanPasteWrite.cxx

Update legacy boolean ivar set method call to current API: the
`itk::VectorGradientMagnitudeImageFilter::m_UseImageSpacing` ivar got the
boolean macro methods in commit c6610df51b741eac1dab172f58852ad79ffdf5a2,
and the former methods were marked as legacy code.
Fixes:
```
/Users/builder/externalExamples/IO/VisibleHumanPasteWrite.cxx:72:9:
error: no member named 'SetUseImageSpacingOn' in
'itk::VectorGradientMagnitudeImageFilter<itk::Image<itk::RGBPixel<unsigned char>, 2>, float, itk::Image<float, 2> >'
grad->SetUseImageSpacingOn();
~~~~  ^
1 error generated.
```
Raised for example at:
https://open.cdash.org/viewBuildError.php?buildid=6964751

COMP: Update legacy boolean ivar set method call to current API

---

Documentation/Maintenance/Release.md

Now on Kitware's computron system, in a different path.

DOC: Update macOS Python package Release build instructions

---

CMake/ITKModuleExternal.cmake

Example failure:
```text
dzenan@corista:~/ITKSplitComponents-deb$ make
[  3%] Built target ITKData
[  5%] Linking CXX executable ../Wrapping/bin/ITKSplitComponentsTestDriver
[  8%] Built target ITKSplitComponentsTestDriver
[ 10%] Linking CXX executable Wrapping/bin/SplitComponentsHeaderTest1
[ 13%] Built target SplitComponentsHeaderTest1
[ 13%] Built target SplitComponents-all
[ 27%] Built target ClangFormat
[ 41%] Built target KWStyle
[ 55%] Built target PCRE
[ 68%] Built target swig
[ 82%] Built target castxml
[ 84%] Built target SplitComponentsCastXML
[ 87%] Built target SplitComponentsSwig
Scanning dependencies of target SplitComponentsPython
[ 89%] Building CXX object Wrapping/Modules/SplitComponents/CMakeFiles/SplitComponentsPython.dir/itkSplitComponentsImageFilterPython.cpp.o
[ …
```

COMP: externally built remote module libs went in /lib or C:/lib

---

Modules/Filtering/ImageFilterBase/wrapping/itkTernaryGeneratorImageFilter.wrap
Modules/Filtering/ImageIntensity/wrapping/itkTernaryAddImageFilter.wrap
Modules/Filtering/ImageIntensity/wrapping/itkTernaryMagnitudeImageFilter.wrap
Modules/IO/MeshGifti/include/itkGiftiMeshIO.h
Modules/IO/MeshGifti/src/itkGiftiMeshIO.cxx

BUG: read data arrays with intent NIFTI_INTENT_NONE for point or cell data
fixes #2103

GIFTI format support for reading data arrays with intent NIFTI_INTENT_NONE

---

CMake/ITKModuleExternal.cmake

Addresses crashing test driver on Windows with shared libraries.

BUG: Set runtime output path for external module binaries

---

Modules/Core/Common/include/itkArray.h
Modules/Core/Common/include/itkArray.hxx
Modules/Core/Common/include/itkOptimizerParameters.h
Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkOptimizerParametersGTest.cxx

Added explicit constructors to `Array` and `OptimizerParameters`, allowing to specify the size (dimension) and the initial value of each element.
Both `std::vector` and `vnl_vector` have a similar constructor.
Included a GoogleTest unit test for `OptimizerParameters`.

ENH: Array, OptimizerParameters constructors with size and initial value

---

Modules/Core/Common/include/itkGaussianDerivativeOperator.h
Modules/Core/Common/include/itkImageRegion.h
Modules/Core/Common/include/itkImageToImageFilter.h
Modules/Core/Common/include/itkMinimumMaximumImageCalculator.h
Modules/Core/Common/include/itkNeighborhoodIterator.h
Modules/Core/Common/include/itkRGBAPixel.h
Modules/Core/Common/include/itkUnaryFunctorImageFilter.h
Modules/Core/Common/include/itkVectorImage.h
Modules/Core/SpatialObjects/include/itkSpatialObjectToImageFilter.h
Modules/Core/Transform/include/itkBSplineDeformableTransform.h
Modules/Filtering/ImageFeature/include/itkDerivativeImageFilter.h
Modules/Filtering/ImageFeature/include/itkDiscreteGaussianDerivativeImageFilter.h
Modules/Filtering/ImageFeature/include/itkHessian3DToVesselnessMeasureImageFilter.h
Modules/Filtering/ImageFilterBase/include/itkNoiseImageFilter.h
Modules/Filtering/ImageIntensity/include/itkEdgePotentialImageFilter.h
Modules/Filtering/LabelMap/include/itkLabelMap.h
Modules/IO/GDCM/include/itkGDCMImageIO.h
Modules/IO/MeshBase/include/itkMeshFileReader.h
Modules/Nonunit/Review/include/itkDiscreteGaussianDerivativeImageFunction.h
Modules/Nonunit/Review/include/itkDiscreteGradientMagnitudeGaussianImageFunction.h
Modules/Nonunit/Review/include/itkDiscreteHessianGaussianImageFunction.h
Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.h

First. several of the paths relating to the Sphinx Examples were incorrect. Many of these either contained spelling errors or the path had been changed.
Second, a few urls referenced in the Doxygen were unable to be found when the Sphinx Examples repository is built with Documentation `ON`. This required:
- Changing http://www.vicomtech.es to https://www.vicomtech.org/en
- Changing http://www.spl.harvard.edu/archive/spl-pre2007/pages/papers/yoshi/ to http://www.image.med.osaka-u.ac.jp/member/yoshi/paper/linefilter.pdf
- Removing https://hdl.handle.net/1926/1493
For https://hdl.handle.net/1926/1493, the web page does not exist when I checked my web browser.

BUG: Invalid URLs and Sphinx Example Paths in Doxygen

---

CMakeLists.txt

To use WrapITK.pth with a build tree, the .pyd files must be deposited
with the rest of the Python runtime tree. Force the runtime output
directory location. If initial configuration with the CMake GUI does not
have ITK_WRAP_PYTHON enabled, the correct value is not set.
Closes #2252

COMP: Force runtime output with Visual Studio and Python wrapping

---

Modules/Core/Common/include/itkNumberToString.h
Modules/Core/Common/include/itkNumberToString.hxx
Modules/Core/Common/src/itkNumberToString.cxx
Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkNumberToStringGTest.cxx

Supported calling a `const` NumberToString function object, by declaring all `NumberToString::operator()` overloads `const`.
Added various GoogleTest unit tests, which do call `const` NumberToString objects.
Did various style improvements, including a reduction of the `buf` size, and removal of `builder.Reset()` calls from the implementation of `NumberToString`.

ENH: Support calling a const NumberToString, add unit tests + style improvements

---

Wrapping/Generators/Python/itk/support/itkBase.py
Wrapping/Generators/SwigInterface/igenerator.py

Following up on
https://github.com/InsightSoftwareConsortium/ITK/commit/183cb1db67c5dbd30a25f279f913a4d2da5ea0b6
an `assert hasattr(this_module, "swig")` was added, but is true for most
classes, but this assertion causes issues when calling
`*init_docstring()` in the module. Replace the assert with a
condition.
Also, simplify the namespace `swig` initialization further on.
Closes #2064

BUG: Do not assert module swig attribute for init_docstring

---

Modules/Core/SpatialObjects/include/itkLineSpatialObject.h
Modules/Core/SpatialObjects/include/itkLineSpatialObjectPoint.h

This will accomplish the following:
- Reference the correct path to the `LineSpatialObject` example in the ITKExamples repository
- Include the `LineSpatialObject` example in the `itkLineSpatialObject` Doxygen in source ITK, as the example heavily uses the class and references it in its documentation
**NOTE:** The path to the `LineSpatialObject` example in ITKExamples is being updated in this PR as well: 
https://github.com/InsightSoftwareConsortium/ITKExamples/pull/185

ENH: Update SpatialObject and SpatialObjectPoint Sphinx

---

Modules/Core/Common/include/itkShapedNeighborhoodIterator.h

This hopefully should be the final change in ITK's Doxygen to get a clean Documentation build for the ITKExamples repository. Essentially, the code block cannot be properly highlighted as `c++` code, because `etc..` is not a valid `c++` command. This comments it out to allow proper highlighting and remove the warnings below.
```
ITKExamples-documentation-build/src/Core/Common/IterateOverARegionWithAShapedNeighborhoodIterator/Documentation.rst: WARNING: Could not lex literal_block as "c++". Highlighting skipped.
ITKExamples-documentation-build/src/Core/Common/IterateOverARegionWithAShapedNeighborhoodIteratorManual/Documentation.rst: WARNING: Could not lex literal_block as "c++". Highlighting skipped.
```
---------------------------
One can inspect the unhighlighted code at either of these …

BUG: Incorrect syntax for doxygen code block

---

Modules/Bridge/VTK/include/itkVTKImageImport.hxx
Modules/Filtering/ImageFilterBase/wrapping/itkCastImageFilter.wrap

COMP: remove CastImageFilter "template already defined" warnings
Addresses CastImageFilter "template already defined" warnings described in Issue #2083.

COMP: remove CastImageFilter "template already defined" warnings

---

Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.h
Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest1.cxx

Fix `itk::VectorGradientMagnitudeImageFilter`  uninitialized memory defect.
Fixes #2275.

BUG: Fix `itk::VectorGradientMagnitudeImageFilter` uninitialized memory defect

---

Modules/Bridge/NumPy/wrapping/PyBuffer.i.in
Modules/Core/Common/wrapping/itkImageDuplicator.wrap
Wrapping/Generators/Python/Tests/extras.py
Wrapping/Generators/Python/itk/support/itkExtras.py

- ENH: Support alternate dim orders in image_from_xarray
- ENH: NumPy and XArray conversion for 4D images

xarray dims

---

Utilities/Maintenance/update-third-party.bash

Use the CMake `Utilities/Scripts/update-third-party.bash` as of commit
`693f4c70ff`.  Manually preserve ITK's change from commit 5dccc2207e
(BUG: Do not gpg sign third party updates, 2018-11-19, `v5.0b02~82^2~1`).

ENH: Update to newer third-party update script from CMake

---

Wrapping/Generators/Python/itk/support/itkExtras.py

uint64 is unnecessary and in a JavaScript environment is not currently
supported on the Safari browser.

ENH: xarray_from_image "c" coords uint32 type

---

Modules/IO/GDCM/src/itkGDCMImageIO.cxx
Modules/IO/Stimulate/src/itkStimulateImageIO.cxx
Modules/IO/VTK/src/itkVTKImageIO.cxx

The floating point number encoding defaults to the C locale on the standard C++ std IO. The sscanf uses the OS dependent LC_NUMERIC value. This fixes that behavior
**EDIT**
Closes #2067

BUG: Fix number encoding to use C locale

---

Modules/Core/Common/include/itkSpatialOrientation.h
Modules/IO/IPL/include/itkGEImageHeader.h

ValidOriginFlags have not been used since 2003 version of
the GE image file reader.

STYLE: Remove deprecated orientation enumeration codes

---

Documentation/ITK5MigrationGuide.md
Modules/Core/Common/include/itkMacro.h

The error messages when ITK_FUTURE_LEGACY_REMOVE is used
can provide better diagnostic message to describe
how to fix the use of deprecated code.

ENH: Provide better failure diagnostics

---

Modules/Filtering/ImageStatistics/include/itkAdaptiveEqualizationHistogram.h
Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalOpeningImageFilter.h
Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalOpeningImageFilter.hxx
Modules/IO/CSV/include/itkCSVArray2DDataObject.h
Modules/IO/CSV/include/itkCSVArray2DDataObject.hxx

Converts a default constructor’s member initializers into the new
default member initializers in C++11. Other member initializers that match the
default member initializer are removed. This can reduce repeated code or allow
use of ‘= default’.

STYLE: Use default member initialization

---

Modules/Core/TestKernel/include/itkTestingMacros.h

Rename `ITK_EXERCISE_BASIC_OBJECT_METHODS` class names arguments in order
to make explicit their use within the macro.

STYLE: Rename `ITK_EXERCISE_BASIC_OBJECT_METHODS` class names arguments

---

Modules/Filtering/BiasCorrection/test/CMakeLists.txt
Modules/Filtering/ImageCompare/test/CMakeLists.txt

Use single forward slashes as data path separators in `CMakeLists.txt`
files.

STYLE: Use single forward slashes in `CMakeLists.txt` data paths

---

Wrapping/Generators/Python/Tests/extras.py

Resolves Issue #2293.  Uses `image` Python variable in lieu of no-longer-defined `vectorimage` variable.

BUG: Fix crash of PythonExtrasTest when extra types are wrapped

---

Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.h
Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.hxx

Improve array ivar initialization in
`itk::VectorGradientMagnitudeImageFilter` constructor using the static
`Fixed::Fill(const ValueType &)` method.
Avoids static casts and unnecessary boilerplate code.
Also, take advantage of the commit to perform such initialization in the
header file.

STYLE: Use the static `FixedArray::Filled` to initialize array ivars

---

Modules/IO/NIFTI/include/itkNiftiImageIO.h
Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
Modules/IO/NIFTI/src/itkNiftiImageIOConfigurePrivate.h.in
Modules/IO/NIFTI/test/itkNiftiImageIOTest.cxx
Modules/IO/NIFTI/test/itkNiftiImageIOTest.h
Modules/IO/NIFTI/test/itkNiftiImageIOTestHelper.cxx
Modules/IO/NIFTI/test/itkNiftiReadAnalyzeTest.cxx
Modules/IO/NIFTI/wrapping/itkNiftiImageIO.wrap

Use strongly typed enums to define the file formats readable by the
`itk::NiftiImageIO` class,

ENH: Use strongly typed enums for `itk::NiftiImageIO` readable formats

---

Utilities/Hooks/post-commit

This specifically lists all the ThirdParty modules and where to contribute to them on `Git`. If one is not listed, it isn't hosted on `Git` for contributions (that I could find). We may want to close #2328 and just merge this one? @hjmjohnson @thewtex @dzenanz

DOC: Add Git upstreams for post-commit hook

---

Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx
Modules/ThirdParty/HDF5/src/itkhdf5/src/CMakeLists.txt
Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fsuper.c
Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Odeprec.c
Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Oint.c
Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Rint.c
Modules/ThirdParty/MINC/src/libminc/libcommon/restructure.c
Modules/ThirdParty/MINC/src/libminc/libsrc2/hyper.c
Modules/ThirdParty/MINC/src/libminc/volume_io/Volumes/input_mgh.c
Modules/ThirdParty/MINC/src/libminc/volume_io/Volumes/input_nifti.c

- COMP: Remove invalid Emscripten HDF5 link flags
- COMP: Declare H5O__fsinfo_set_version
- COMP: Provide H5CX_set_apl declaration in H5Odeprec.c
- COMP: Provide H5CX_get_ohdr_flags declaration in H5Oint.c
- COMP: Declare H5CX_set_libver_bounds in H5Rint.c
- COMP: Add output redirection for H5Tinit.c, H5lib_settings.c generation
- BUG: Disable Emscripten exception for floating point exceptions
- COMP: Include stdio.h for printf

emscripten upstream

---

Modules/Core/Common/include/itkMacro.h

Deleted all special member functions of GPU kernel helper classes
defined by `itkGPUKernelClassMacro(kernel)`, by C++11 `= delete`.
Note that construction, destruction, copy, and move were previously
already disabled by declaring their special member functions `private`.
So this adjustment is just a style modernization, not an API change.
Made the destructor non-virtual, to avoid the definition of a virtual
table for these classes.

STYLE: Remove virtual from itkGPUKernelClassMacro, use C++11 `= delete`

---

Modules/IO/ImageBase/include/itkImageFileWriter.hxx
Modules/IO/ImageBase/include/itkImageIOBase.h
Modules/IO/ImageBase/test/itkImageIOBaseTest.cxx
Modules/IO/NIFTI/src/itkNiftiImageIO.cxx

This addresses:
- SetPixelTypeInfo for VariableLengthVector was set to VECTOR instead of VARIABLELENGTHVECTOR
- ImageFileWriter was identifying VariableLengthVector as SCALAR
- ARRAY, VARIABLESIZEMATRIX was missing from SetPixelTypeInfo

BUG: SetPixelTypeInfo for VARIABLELENGTHVECTOR, ARRAY, VARIABLESIZEMATRIX

---

Modules/Core/Common/include/itkMacro.h
Modules/Core/GPUCommon/include/itkGPUImageOps.h
Modules/Core/GPUCommon/include/itkGPUReduction.h
Modules/Core/GPUFiniteDifference/include/itkGPUDenseFiniteDifferenceImageFilter.h
Modules/Filtering/GPUAnisotropicSmoothing/include/itkGPUGradientNDAnisotropicDiffusionFunction.h
Modules/Filtering/GPUAnisotropicSmoothing/include/itkGPUScalarAnisotropicDiffusionFunction.h
Modules/Filtering/GPUImageFilterBase/include/itkGPUCastImageFilter.h
Modules/Filtering/GPUImageFilterBase/include/itkGPUNeighborhoodOperatorImageFilter.h
Modules/Filtering/GPUSmoothing/include/itkGPUMeanImageFilter.h
Modules/Filtering/GPUThresholding/include/itkGPUBinaryThresholdImageFilter.h
Modules/Registration/GPUPDEDeformable/include/itkGPUDemonsRegistrationFunction.h
Modules/Registration/GPUPDEDeformable/include/itkGPUPDEDeformableRegistrationFilter.h

Backward compatibility with ITK 5.0 and ITK 5.1 client code (including
SuperElastix/elastix) appears broken by the removal of the C++ `class`
keyword from the definition of `itkGPUKernelClassMacro(kernel)`, with
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/1814
commit 518349019984699b8d35a953bf4fc8a4324897fa
This commit restores the backward compatibility, and adds an extra
macro, `itkGPUKernelMacro(kernel)`, which defines the kernel without
`class` keyword.

COMP: Fix itkGPUKernelClassMacro(kernel) backward compatibility

---

Modules/Nonunit/Review/test/itkMultiphaseSparseFiniteDifferenceImageFilterTest.cxx

Fix `itkMultiphaseSparseFiniteDifferenceImageFilterTest`:
- Use the appropriate class instance to exercise basic object methods.
- Remove calls to protected methods.
Fixes:
```
Modules/Core/TestKernel/include/itkTestingMacros.h:69:63: error:
'itk::MultiphaseSparseFiniteDifferenceImageFilterTestHelper<itk::Image<double,
3>, itk::Image<float, 3>, itk::Image<unsigned char, 3>,
itk::ScalarChanAndVeseLevelSetFunction<itk::Image<double, 3>,
itk::Image<float, 3>,
itk::ConstrainedRegionBasedLevelSetFunctionSharedData<itk::Image<double,
3>, itk::Image<float, 3>,
itk::ScalarChanAndVeseLevelSetFunctionData<itk::Image<double, 3>,
itk::Image<float, 3> > > >, long unsigned int>::Superclass {aka
itk::MultiphaseSparseFiniteDifferenceImageFilter<itk::Image<double,
3>, itk::Image<float, 3>, …
```

BUG: Fix `itkMultiphaseSparseFiniteDifferenceImageFilterTest`

---

Modules/Nonunit/Review/include/itkMultiphaseDenseFiniteDifferenceImageFilter.h

Fix Superclass name in RTTI macro.

BUG: Fix Superclass name in RTTI macro

---

Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.h
Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.hxx
Modules/Filtering/Path/test/itkContourExtractor2DImageFilterTest.cxx

The previously existing function of ContourExtractor2DImageFilter is to trace the contour between regions of a 2-dimensional image defined by values that are higher and lower, respectively, than a specified contour value.  To that we add a `LabelContoursOn()` option; when set then every distinct value in the 2-dimensional image defines its own region, and boundaries for all such regions are generated.
At present this is WIP.  Please review for the API changes.  The implementation works, but is not performant; it needs additional work.

ENH: support multiple labels in ContourExtractor2DImageFilter

---

Modules/IO/LSM/test/itkLSMImageIOTest.cxx

The PR closes memory leak in _itkLSMImageIOTest_ , s. [dashboard](https://open.cdash.org/viewDynamicAnalysis.php?buildid=7070588).
Also added _try/catch_ for `lsmImageIO->Write(buffer)`, because the function can throw exception.

BUG: memory leak in LSMImageIOTest

---

Modules/Registration/Metricsv4/include/itkANTSNeighborhoodCorrelationImageToImageMetricv4GetValueAndDerivativeThreader.hxx

Fix uninitialized variable use in `ANTS` neighborhood correlation metric:
ensure that `fixedImageGradient` and `movingImageGradient` have valid
values before assigning them to the `scanMem` struct that scans over
images.
Fixes:
```
Run-Time Check Failure #3 - The variable 'fixedImageGradient' is being
used without being initialized.
```
The bug was affecting a number of tests in the
`ITKRegistrationMethodsv4Test` module.
Signaled at
https://open.cdash.org/viewTest.php?onlyfailed&buildid=7067466
and
https://open.cdash.org/viewTest.php?onlyfailed&buildid=7069241

BUG: Fix uninitialized variable use in `ANTS` neighborhood correlation metric

---

Modules/Core/Common/include/itkLightObject.h

Simplified the `LightObject::Clone()` implementation. The original
version did return `dynamic_cast<x*>(this->InternalClone().GetPointer())`,
as implemented by `itkCloneMacro(x)`. Obviously when `x` = `LightObject`,
the `dynamic_cast` and the `GetPointer()` call are unnecessary.

STYLE: Remove dynamic_cast and GetPointer() from LightObject::Clone()

---

Modules/Filtering/DistanceMap/include/itkDirectedHausdorffDistanceImageFilter.hxx
Modules/Filtering/ImageStatistics/include/itkImagePCAShapeModelEstimator.h
Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.h

Initialize member variables.
Fixes:
```
UMC ==4407== Conditional jump or move depends on uninitialised value(s)
==4407==    at 0xC3A9316:
double_conversion::DoubleToStringConverter::ToShortestIeeeNumber(double,
double_conversion::StringBuilder*,
double_conversion::DoubleToStringConverter::DtoaMode) const
(double-to-string.cc:172)
==4407==    by 0x6835CE6:
double_conversion::DoubleToStringConverter::ToShortest(double,
double_conversion::StringBuilder*) const (double-to-string.h:166)
==4407==    by 0x68354F6: (anonymous
namespace)::ConvertToShortest(double_conversion::DoubleToStringConverter
const&, double, double_conversion::StringBuilder&)
(itkNumberToString.cxx:31)
==4407==    by 0x68355F8: std::string (anonymous
namespace)::FloatingPointNumberToString(double) (itkNumberToString.cxx:55) …
```

BUG: Initialize member variables

---

Wrapping/Generators/Python/Tests/extras.py
Wrapping/Generators/Python/itk/support/itkExtras.py

Metadata is mapped to / from the itk.Image MetaDataDictionary and the
xarray.DataArray attrs. Exclude origin, spacing, direction as
appropriate because they are handled specially in itk and xarray.

ENH: xarray_from_image .attr, image_from_xarray MetaDataDictionary support

---

Modules/Bridge/VtkGlue/CMakeLists.txt
Modules/Bridge/VtkGlue/itk-module-init.cmake
Modules/Bridge/VtkGlue/test/CMakeLists.txt
Modules/Bridge/VtkGlue/wrapping/CMakeLists.txt

This enables specifying only the required modules in
test/CMakeLists.txt.
To address #2333

COMP: Migrate ITKVtkGlue library configuration to itk-module-init.cmake

---

Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.h
Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.hxx

Addresses Issue #2359, and type and const safety generally in `ContourExtractor2DImageFilter.h` and `ContourExtractor2DImageFilter.hxx`.  I am submitting this initially as a draft pull request to make sure that the new stringency doesn't break other platforms.

COMP: type and const safety in ContourExtractor2DImageFilter

---

Modules/Core/Common/src/itkProcessObject.cxx
Modules/Core/FiniteDifference/include/itkDenseFiniteDifferenceImageFilter.hxx
Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMesh.hxx
Modules/Core/Transform/include/itkCompositeTransform.hxx
Modules/Core/Transform/include/itkMultiTransform.hxx
Modules/Core/Transform/test/itkTransformCloneTest.cxx

Removed six "no-op" dynamic_casts that just cast pointers to their own compile-time type from Modules/Core.

STYLE: Remove 6 no-op dynamic_casts (casting T* to T*) from Modules/Core

---

Modules/Core/Common/src/itkLightObject.cxx

`LightObject::New()` did call `ObjectFactory<LightObject>::Create()`,
which would do a `dynamic_cast` from `LightObject*` to `LightObject*`
on the result of `ObjectFactoryBase::CreateInstance`.
With this commit, such a "no-op" cast is avoided, by calling
`ObjectFactoryBase::CreateInstance` directly.

STYLE: Avoid "no-op" dynamic_cast from inside LightObject::New()

---

Modules/Filtering/ImageFilterBase/include/itkUnaryGeneratorImageFilter.hxx
Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.hxx
Modules/Filtering/LabelMap/include/itkInPlaceLabelMapFilter.hxx
Modules/IO/TransformBase/src/itkTransformFileWriterSpecializations.cxx
Modules/Registration/Metricsv4/test/itkMetricImageGradientTest.cxx
Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx
Modules/Video/IO/include/itkVideoFileWriter.hxx

Removed nine "no-op" dynamic_casts that just cast pointers to their own
compile-time type.
Note: in those cases where `auto` was used to declare a variable
initialized by such a no-op `dynamic_cast`, this commit replaced
`auto` by the explicitly specified declaration type.

STYLE: Remove 9 no-op dynamic_casts (casting T* to T*)

---

Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.h

Fix deduced type initialization warning and operand mismatch error.
Fixes deduced type initialization warning on Apple clang:
```
/Users/builder/externalModules/Filtering/Path/include/itkContourExtractor2DImageFilter.h:285:33:
warning: direct list initialization of a variable with a deduced type will
change meaning in a future version of Clang; insert an '=' to avoid a
change in behavior [-Wfuture-compat]
auto                 value{ static_cast<SizeValueType>(std::fabs(mantissa)) };
^
=
```
raised at:
https://open.cdash.org/viewBuildError.php?buildid=7082817
and the operand mismatch error on Apple clang and gcc 4.6:
```
/Users/builder/externalModules/Filtering/Path/include/itkContourExtractor2DImageFilter.h:286:18:
error: invalid operands to binary expression ('int' and …
```

COMP: Fix deduced type initialization warning and operand mismatch error

---

Modules/Registration/Metricsv4/include/itkPointSetToPointSetMetricv4.hxx

Only updated PointLocators in PointSetToPointSetMetricv4 when necessary.

PERF: Avoid Superfluous PointsLocator Updates

---

Modules/Core/FiniteDifference/include/itkDenseFiniteDifferenceImageFilter.hxx

Fix image pointer casting error.
Fixes
```
ITK/Modules/Core/FiniteDifference/include/itkDenseFiniteDifferenceImageFilter.h:194:0,
from
ITK/Modules/Filtering/AnisotropicSmoothing/include/itkAnisotropicDiffusionImageFilter.h:21,
from
ITK/Modules/Filtering/AnisotropicSmoothing/include/itkGradientAnisotropicDiffusionImageFilter.h:21,
from
src/Filtering/AnisotropicSmoothing/ComputePeronaMalikAnisotropicDiffusion/Code.cxx:22:
/.../ITKExamples-build/ITK/Modules/Core/FiniteDifference/include/itkDenseFiniteDifferenceImageFilter.hxx:
In instantiation of
'void itk::DenseFiniteDifferenceImageFilter<TInputImage, TOutputImage>::CopyInputToOutput()
[with TInputImage = itk::Image<unsigned char, 2>; TOutputImage = itk::Image<float, 2>]': …
```

COMP: Fix image pointer casting error

---

Modules/Core/Common/wrapping/itkImageSource.wrap
Modules/Core/Common/wrapping/itkImageToImageFilterA.wrap
Modules/Filtering/ImageFilterBase/wrapping/itkCastImageFilter.wrap
Modules/IO/ImageBase/wrapping/itkImageFileReader.wrap
Modules/IO/ImageBase/wrapping/itkImageFileWriter.wrap
Modules/IO/ImageBase/wrapping/itkImageSeriesReader.wrap
Wrapping/Generators/Python/Tests/extras.py
Wrapping/WrapITKTypes.cmake

Even though 32 bit integer is often not enabled in the wrapping for the
entire toolkit, add minimial support so we can alway read / write / cast
files with this type in their native type.

ENH: Support 32 bit integer IO in wrapping

---

Modules/Core/Common/include/itkExceptionObject.h
Modules/Core/Common/include/itkMetaProgrammingLibrary.h
Modules/Core/Common/include/itkResourceProbe.h
Modules/Core/Common/src/itkExceptionObject.cxx
Modules/Core/Common/test/itkExceptionObjectTest.cxx
Modules/Core/Common/test/itkIntTypesTest.cxx

A major revision of one of my earliest contributions to ITK 😸  which aimed to make `itk::ExceptionObject` exception-safe, by introducing a rather complicated new internal data structure: 
Commit 8bfd356e80a8a68cf9211b4089dabaafd8eabd35, _"BUG: fixed issue 0007094: itk::ExceptionObject should never cause a crash. Removed ExceptionObject::UpdateWhat(), as discussed with Brad King and Bill Lorensen at [Insight-developers]"_, 28 May 2008.
This pull request proposes to very much simplify the implementation, while preserving its exception-safety.

Modernize the implementation of ExceptionObject

---

Modules/Filtering/DistanceMap/include/itkDirectedHausdorffDistanceImageFilter.h
Modules/Filtering/DistanceMap/include/itkDirectedHausdorffDistanceImageFilter.hxx

Update directed hausdorff distance

---

Modules/Core/Common/include/itkConstShapedNeighborhoodIterator.h
Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.h
Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.hxx
Modules/Filtering/Path/test/itkContourExtractor2DImageFilterTest.cxx

This pull request addresses the same issue as Pull Request #2371 of @dzenanz but I am submitting this new pull request because I am cautious about submitting to his pull request, I've rebased to merged master-branch commits in the same code, and I have built on his code to a fair degree.  It is probably best to **_not_** merge both that pull request and this pull request.
Much of this code is co-authored with @dzenanz.

PERF: Parallelize ContourExtractor2DImageFilter

---

Modules/Core/Common/include/itkImage.hxx

Fix missing initializer warning.
Fixes:
```
/tmp/bld/ITK/Modules/Core/Common/include/itkImage.hxx: In instantiation of
'unsigned int itk::Image<TPixel,
VImageDimension>::GetNumberOfComponentsPerPixel() const [with TPixel =
itk::Index<4u>; unsigned int VImageDimension = 4u]':
bld/ITK/Modules/Core/Common/test/itkConstNeighborhoodIteratorTest.cxx:427:1:
required from here
bld/ITK/Modules/Core/Common/include/itkImage.hxx:151:21: warning: missing
initializer for member 'itk::Index<4u>::m_InternalArray'
[-Wmissing-field-initializers]
const PixelType p{};
^
```
raised at:
https://open.cdash.org/viewBuildError.php?type=1&buildid=7088974
https://open.cdash.org/viewBuildError.php?type=1&buildid=7089276
https://open.cdash.org/viewBuildError.php?type=1&buildid=7089222

COMP: Fix missing initializer warning

---

Documentation/ITK5MigrationGuide.md

DOC: fix MutexLock-related broken links in the migration guide

---

Modules/Core/Common/include/itkExceptionObject.h
Modules/Core/Common/src/itkExceptionObject.cxx

`MemoryAllocationError`, `RangeError`, `InvalidArgumentError`, and
`IncompatibleOperandsError` may simply inherit the constructors from
their base class, `itk::ExceptionObject`.

STYLE: C++11 inheriting constructors and Rule of Zero for ExceptionObject derived classes

---

Modules/Core/Common/include/itkMacro.h
Modules/Core/Common/test/itkExceptionObjectGTest.cxx

Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2380
commit df0a977dd47467a82bfbfc76ed301c159d020a4c
"BUG: Remove duplicate "itk::ERROR: itk::ERROR: " from itkExceptionMacro"

BUG: Remove duplicate "itk::ERROR: " from itkSpecializedExceptionMacro

---

Modules/Core/FiniteDifference/include/itkDenseFiniteDifferenceImageFilter.hxx

Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2386
commit 1c25350c93c33578b11c83bce501496c306ff3b1
"COMP: Fix image pointer casting error"
Also removed an unused `#include <list>`.

STYLE: Use equal_to on pixel containers DenseFiniteDifferenceImageFilter

---

Modules/Core/Common/test/itkExceptionObjectGTest.cxx

Addressed Mac10.14-AppleClang-dbg-ASanUBSan warning:
> itkExceptionObjectGTest.cxx:29:9: warning: 'TestClass' has virtual
> functions but non-virtual destructor [-Wnon-virtual-dtor]
From https://open.cdash.org/viewBuildError.php?type=1&buildid=7093971
Reported by Jon Haitz Legarreta Gorroño (@jhlegarreta) at
https://github.com/InsightSoftwareConsortium/ITK/pull/2374#issuecomment-797546665
Also added an explicit default-constructor, and disallowed copy and move.

COMP: Add virtual destructor to TestClass in ExceptionObject unit test

---

.github/workflows/clang-format-linter.yml

To address:
reference is not a tree: 670863f3c88fad4d181fe9f59f8b154983c48bd5
lint
Git checkout failed with exit code: 128
lint
Exit code 1 returned from process: file name '/home/runner/runners/2.277.1/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
lint
Git checkout failed on shallow repository, this might because of git fetch with depth '1' doesn't include the checkout commit '670863f3c88fad4d181fe9f59f8b154983c48bd5'.
lint
Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see actions/virtual-environments/issues/1816
https://github.com/InsightSoftwareConsortium/ITK/actions/runs/646656228

BUG: Checkout full depths for clang-format-linter

---

Modules/Core/Common/include/itkMacro.h
Modules/Core/Common/test/itkExceptionObjectGTest.cxx

Previously, the description text of an exception thrown by
`itkSpecializedMessageExceptionMacro` would start with the text
"itk::ERROR", which seemed to suggest that it involved an `itk::ERROR`
object, function, or type. However, there is no such `ERROR` in the
`itk` namespace!
It appears clearer to use the text "ITK ERROR" instead, to indicate
that the error involves the ITK library.

STYLE: Replace "itk::ERROR" by "ITK ERROR" in description of exception

---

Modules/Core/Common/include/itkMacro.h
Modules/Core/Common/test/itkExceptionObjectGTest.cxx

Replaced the very general term "message" inside the definition of
`itkSpecializedMessageExceptionMacro` by a much more specific
identifier, "exceptionDescriptionOutputStringStream", to avoid naming
conflicts in user code.
Removed the unnecessary `std::string{ ... }` construction for the result
of `std::ostringstream::str()`, as it is an `std::string` already.
Did inherit the exception constructors inside `itkDeclareExceptionMacro`,
as a follow-up to pull request #2398 commit e41b2ef92196805ccac076115468d3d7d54f0cf5
"STYLE: C++11 inheriting constructors from ExceptionObject for 4 classes"
Removed unnecessary `ITK_MACROEND_NOOP_STATEMENT` calls from exception macro definitions.

Avoid "message" naming conflicts exception macro, inherit constructors, remove ITK_MACROEND_NOOP_STATEMENT calls

---

Modules/Segmentation/Classifiers/include/itkBayesianClassifierImageFilter.hxx

Removed the three "no-op" dynamic_casts of `this->GetPosteriorImage()`
from the implementation of `BayesianClassifierImageFilter`.
Follow-up to:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2365
commit 5089a04475583a723a41f92674e8127a265f9250
"STYLE: Remove 9 no-op dynamic_casts (casting T* to T*)"

STYLE: Remove dynamic_casts PosteriorImage BayesianClassifierImageFilter

---

Modules/Core/Common/include/itkExceptionObject.h
Modules/Core/Common/src/itkExceptionObject.cxx

Followed the C++ Rule of Five, instead of the Rule of Zero, for
`ExceptionObject`, and added the definition of its destructor to its CXX
file.
Aims to fix Visual C++ link errors (error LNK2005 "symbol was defined
more than once", fatal error LNK1169) reported by @SimonRit, and
confirmed by @LucasGandel, at "Modernize the implementation of
ExceptionObject", pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2374

COMP: Define ExceptionObject destructor out-of-line (doing Rule of Five)

---

Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx

Avoid creating a copy variable.
Fixes:
```
/Users/builder/externalModules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx:547:21:
warning: loop variable 'pixel' of type 'const
itk::ShapedImageNeighborhoodRange<const itk::Image<unsigned char,
2>, itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<const
itk::Image<unsigned char, 2> > >::PixelProxy<true, void>' creates
a copy from type 'const itk::ShapedImageNeighborhoodRange<const
itk::Image<unsigned char, 2>,
itk::ZeroFluxNeumannImageNeighborhoodPixelAccessPolicy<const
itk::Image<unsigned char, 2> > >::PixelProxy<true, void>'
[-Wrange-loop-analysis]
for (const auto pixel : range)
^
/Users/builder/externalModules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx:547:10: …
```

COMP: Avoid creating a copy variable

---

Modules/Filtering/MathematicalMorphology/test/itkTopHatImageFilterTest.cxx

Fix unreachable code warning.
Fixes:
```
/Users/builder/externalModules/Filtering/MathematicalMorphology/test/itkTopHatImageFilterTest.cxx:135:7:
warning: 'break' will never be executed [-Wunreachable-code-break]
break;
^~~~~
/Users/builder/externalModules/Filtering/MathematicalMorphology/test/itkTopHatImageFilterTest.cxx:150:7:
warning: 'break' will never be executed
[-Wunreachable-code-break]
break;
^~~~~
[CTest: warning suppressed] 2 warnings generated.
```
raised at:
https://open.cdash.org/viewBuildError.php?type=1&buildid=7109827

COMP: Fix unreachable code warning

---

Modules/Filtering/Denoising/include/itkPatchBasedDenoisingImageFilter.hxx

The semi-colons at the end of the arguments passed to
`itkExceptionMacro` calls in the implementation of
`PatchBasedDenoisingImageFilter` appear unnecessary.

STYLE: Remove `;` from itkExceptionMacro PatchBasedDenoisingImageFilter

---

.github/workflows/label-pr.yml

Change the `GitHub` webhook event to a `pull_request_target` event to
trigger the PR labeler workflows from forks.
See documentation:
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
and
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

ENH: Trigger PR labeler workflows from forks

---

Modules/ThirdParty/PNG/src/itkpng/CMakeLists.txt

Without this, building Universal Binary on an Intel Mac (but not on an ARM Mac) gives link errors for undefined symbols like _itk_png_do_expand_palette_rgb8_neon and a few others.
Introspecting the CPU type of the build machine is fundamentally incompatible with the idea of Universal Binaries.

COMP: fix link error building Universal Binary on Intel Mac

---

Modules/Core/Transform/test/itkAffineTransformTest.cxx
Modules/IO/HDF5/test/itkHDF5ImageIOTest.cxx
Modules/IO/MINC/test/itkMINCImageIOTest.cxx
Modules/IO/NIFTI/test/itkNiftiImageIOTest.h
Modules/IO/NIFTI/test/itkNiftiImageIOTest11.cxx

Fixed warnings from ITK.macOS Apple clang version 12.0.0
(clang-1200.0.32.29), saying:
> warning: unused variable 'myDirection' [-Wunused-variable]
> warning: unused variable 'inverse2' [-Wunused-variable]

COMP: Fix macOS clang warnings [-Wunused-variable] in test source files

---

Modules/IO/MINC/test/itkMINCImageIOTest.cxx

Fixed a warning from ITK.macOS Apple clang version 12.0.0
(clang-1200.0.32.29), saying:
> itkMINCImageIOTest.cxx:565:37: warning: unused variable 'myDirection' [-Wunused-variable]
Follow-up to:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2451
commit 24744f9ef427a05aa29175670a6ef9ac9ad04196
"COMP: Fix macOS clang warnings [-Wunused-variable] in test source files"

COMP: Fix macOS clang warning [-Wunused-variable] in itkMINCImageIOTest

---

Modules/Numerics/Optimizersv4/src/itkLBFGS2Optimizerv4.cxx

Based on report on the forum:
https://discourse.itk.org/t/multi-grid-bspline-image-registration-error/3980

DOC: improve description of LBFGSERR_ROUNDING_ERROR stopping condition

---

Modules/Core/Common/include/itkMatrix.h
Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkMatrixGTest.cxx

Defaulted the default-constructor of `itk::Matrix`, and added a
GoogleTest, to check that it does properly zero-initialize its elements.
Removed its user-defined copy-constructor and copy-assignment, following
the C++ "Rule of Zero". Tested that `itk::Matrix` has thereby become
"trivially copyable" for built-in element types.

ENH: Make itk::Matrix trivially copyable, following Rule of Zero

---

Modules/ThirdParty/PNG/src/itkpng/CMakeLists.txt

This is the value on the NVIDIA Jetson NX.

COMP: Build PNG arm sources for aarch64 CMAKE_SYSTEM_PROCESSOR

---

Modules/Filtering/Smoothing/wrapping/test/MedianImageFilterTest.py
Wrapping/Generators/SwigInterface/igenerator.py

Add an attribute on the functional filter interfaces that points back to
the associated itk.ProcessObject that the filter uses internally.

ENH: Add .process_object attribute to functional filters

---

Modules/Bridge/NumPy/wrapping/PyVectorContainerBuffer.i.in
Modules/Bridge/NumPy/wrapping/itkPyVectorContainer.wrap
Modules/Bridge/NumPy/wrapping/test/itkPyVectorContainerTest.py
Wrapping/Generators/Python/itk/support/extras.py

This is required in the CMake configure_file template to produce the
correct return type.

BUG: Set ElementType for wrapping PyVectorContainer

---

CMake/ITKSetStandardCompilerFlags.cmake

CMAKE_SYSTEM_PROCESSOR defines the target compilation architecture. When
we want x86_64 optimizations, e.g. -march=corei7, only add these flags
when building for this architecture. On Linux/macOS (GCC/AppleClang),
CMAKE_SYSTEM_PROCESSOR is "x86_64" and on Windows (Visual Studio) it is
"AMD64".

COMP: Constrain x86_64 optimization flags according to CMAKE_SYSTEM_PROCESSOR

---

Wrapping/Generators/Python/itk/support/extras.py

```text
File "M:\Dev\ITK-py\Wrapping\Generators\Python\itk\support\template_class.py", line 525, in __getitem__
this_item = self.__template__[key]
KeyError: (<itkCType float>, 4)
During handling of the above exception, another exception occurred:
File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1477, in _exec
pydev_imports.execfile(file, globals, locals)  # execute the script
File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.2.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "M:/Dev/Plus/UltrasoundPhantomSegmentation/ml_spect_supervised.py", …
```

BUG: Fix crash in itk.image_from_xarray if is_vector and Dimension==4

---

CMakeLists.txt

We will also have to update VNL after https://github.com/vxl/vxl/pull/833 is merged or otherwise addressed.

COMP: Fix CMake warning by setting policy 0120 to OLD

---

Modules/Core/Common/test/itkArrayTest.cxx

Array is intantiated and used throughout the toolkit and this
instantiation conflicts on macOS arm64 in symbol exports resulting in:
ld: warning: direct access in function 'itk::MetaDataObject<itk::Array<float> >::GetMetaDataObjectTypeName() const' from file 'lib/libITKCommon-5.2.a(itkMetaDataObject.cxx.o)' to global weak symbol 'typeinfo name for itk::Array<float>' from file 'Modules/Core/Common/test/CMakeFiles/ITKCommon1TestDriver.dir/itkArrayTest.cxx.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'itk::MetaDataObject<itk::Array<float> >::GetMetaDataObjectTypeName() const' from file 'lib/libITKCommon-5.2.a(itkMetaDataObject.cxx.o)' to …

COMP: Do not explicitly instantiate Array in itkArrayTest

---

Modules/Filtering/Smoothing/wrapping/test/MedianImageFilterTest.py
Wrapping/Generators/Python/itk/support/extras.py
Wrapping/Generators/Python/itk/support/types.py

We are using `from numpy.typing import ArrayLike` to create an `ArrayLike` Python type, but it is first available with `numpy==1.20`.  We fall back to using `from numpy import ndarray as ArrayLike` when `numpy.typing` is not available.

ENH: Support ArrayLike Python type with both numpy>=1.20 and numpy<1.20.

---

Modules/Core/Common/test/itkMatrixGTest.cxx

Worked around a compiler bug encountered with Clang 3.8.1 and
Mac10.10-AppleClang (which appears fixed with more recent Clang
compiler versions), saying:
> error: default initialization of an object of const type
> 'const itk::Matrix' without a user-provided default constructor
Reported by Jon Haitz Legarreta Gorroño (@jhlegarreta) at pull request
"ENH: Make itk::Matrix trivially copyable, following Rule of Zero"
https://github.com/InsightSoftwareConsortium/ITK/pull/2449

COMP: Workaround Clang 3 error default initialization const MatrixGTest

---

Modules/Core/Common/include/itkImageBase.h
Modules/Core/Common/include/itkImageBase.hxx
Modules/Core/Common/include/itkMatrix.h
Modules/Core/Common/test/itkImageBaseGTest.cxx
Modules/Core/Common/test/itkMatrixGTest.cxx

Used `itk::Matrix::GetIdentity()` to simplify and modernize the default-constructor of `ImageBase`.

ENH: Add static member function, `itk::Matrix::GetIdentity()`

---

Modules/Core/Common/include/itkVector.h
Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkVectorGTest.cxx

Added `itk::Vector` constructor, allowing to specify its elements by a
C++11 `std::array`. Added `itkVectorGTest` to test this constructor.
Follow-up to:
"ENH: Add explicit constructors Point and FixedArray for C++11 std::array"
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/748
commit 8080e037bc76755c5c5ac8d62ae2daf980542227

ENH: Add explicit `itk::Vector(const std::array &)` constructor

---

Modules/Core/Transform/include/itkResampleInPlaceImageFilter.h

Fixes:
```text
In file included from /Users/builder/externalModules/Core/Transform/test/itkResampleInPlaceImageFilterTest.cxx:19:
/Users/builder/externalModules/Core/Transform/include/itkResampleInPlaceImageFilter.h:100:3: error: static_assert failed "Replace deprecated ITK_DISALLOW_COPY_AND_ASSIGN with modern ITK_DISALLOW_COPY_AND_MOVE"
ITK_DISALLOW_COPY_AND_ASSIGN(ResampleInPlaceImageFilter);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[CTest: warning matched] /Users/builder/externalModules/Core/Common/include/itkMacro.h:394:5: note: expanded from macro 'ITK_DISALLOW_COPY_AND_ASSIGN'
static_assert(false, "Replace deprecated ITK_DISALLOW_COPY_AND_ASSIGN with modern ITK_DISALLOW_COPY_AND_MOVE")
^             ~~~~~
```

Use non-deprecated ITK_DISALLOW_COPY_AND_MOVE in ResampleInPlace

---

Modules/Core/Transform/include/itkTranslationTransform.hxx
Modules/Core/Transform/test/CMakeLists.txt
Modules/Core/Transform/test/itkTranslationTransformGTest.cxx

When the argument passed to `TranslationTransform` member function
`SetParameters` would contain less than `SpaceDimension` values,
the member function would have undefined behavior, which would typically
just cause a crash.
This commit avoids such undefined behavior by throwing an exception, in
this case. GoogleTest unit tests are included.
Follow-up to:
"BUG: Fix MatrixOffsetTransformBase SetFixedParameters if too few params"
Pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2118
Commit fcb85b3a1e4f78d3c9c3742f213e7acefb87314f

BUG: Avoid crash TranslationTransform::SetParameters when too few params

---

Modules/IO/TransformFactory/src/itkTransformFactoryBaseRegister.hxx
Modules/IO/TransformFactory/test/itkTransformFactoryBaseTest.cxx

This is required to read and write the transform.

BUG: Register ComposeScaleSkewVersor3DTransform transform

---

Modules/Bridge/VtkGlue/wrapping/CMakeLists.txt

Some targets (VTK libraries) didn't have the property INTERFACE_INCLUDE_DIRECTORIES
```bash
CMake Error in Modules/Bridge/VtkGlue/wrapping/CMakeLists.txt:
Found relative path while evaluating include directories of
"ITKVtkGluePython":
"_vtk_lib_include_dirs-NOTFOUND"
```
Triggered when compiling Slicer with `Slicer_BUILD_ITKPython:BOOL=ON`
aka `ITK_WRAP_PYTHON:BOOL=ON`.
Full error log with extra printing:
```bash
CMake Warning at Modules/Bridge/VtkGlue/wrapping/CMakeLists.txt:3 (message):
ITKVtkGlue_VTK_LIBRARIES:
VTK::IOImage;VTK::ImagingSources;VTK::WrappingPythonCore;VTK::CommonCore;VTK::CommonDataModel;VTK::kwiml;VTK::CommonExecutionModel;VTK::RenderingOpenGL2;VTK::RenderingFreeType;VTK::InteractionStyle;VTK::InteractionWidgets
CMake Warning at …
```

COMP: CastXML, ITKVtkGlue, include only when property exists

---

Modules/Core/Transform/include/itkResampleInPlaceImageFilter.h

Improve `itk::ResampleInPlaceImageFilter` documentation:
- Name itk filters with their classname so that Doxygen can automatically
generate links.
- Make use of Doxygen syntax to improve the readability of the code.
- Use the appropriate LaTeX equation environments to accept line breaks.
- Improve the layout of the documentation.
- Re-phrase some sentences.
- Fix some typos and inconsistencies in notation.

DOC: Improve `itk::ResampleInPlaceImageFilter` documentation

---

Modules/Core/Transform/test/itkResampleInPlaceImageFilterTest.cxx

Improve `itk::ResampleInPlaceImageFilter` class coverage: test the
exceptions.

ENH: Improve `itk::ResampleInPlaceImageFilter` coverage

---

Modules/Core/Transform/wrapping/itkResampleInPlaceImageFilter.wrap

Add Python wrapping for `itk::ResampleInPlaceImageFilter`.

ENH: Add Python wrapping for `itk::ResampleInPlaceImageFilter`

---

Testing/ContinuousIntegration/AzurePipelinesMacOS.yml
Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml

This reverts commit 414d4c05025236521f02141da096f022cc8ee7e8.
Closes #2492.

Revert "COMP: Use CMake 3.18.4 in macOS CI builds"

---

Modules/Core/Common/include/itkMatrix.h
Modules/Core/Common/test/itkMatrixGTest.cxx
Modules/Filtering/LabelMap/include/itkShapeLabelMapFilter.hxx

Declared the `Matrix(const vnl_matrix &)` constructor `explicit`, while
removing the `explicit` keyword from `Matrix(const InternalMatrixType &)`,
as the latter one is the safest constructor of the two.
(Note that `InternalMatrixType = vnl_matrix_fixed<T, NRows, NColumns>`.)
Added the corresponding static asserts to itkMatrixGTest.

STYLE: Matrix constructors vnl_matrix/vnl_matrix_fixed explicit/implicit

---

Wrapping/Generators/Python/CMakeLists.txt

- BUG: Add vnl_vector_from_array to extras __all__
- COMP: Do not add IPO to Python wrapping if not supported

clang python wrapping

---

Examples/Filtering/ResampleImageFilter.cxx

BUG: Fix wrong argument count comparison in ResampleImageFilter example

---

Wrapping/Generators/Python/itk/support/types.py

To address:
itk/support/types.py:137
`np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

COMP: Replace np.bool with np.bool8

---

Modules/Core/Common/include/itkMetaDataDictionary.h
Modules/Core/Common/include/itkMetaDataObject.h
Modules/Core/Common/include/itkMetaDataObjectBase.h
Modules/Core/Common/test/itkMetaDataDictionaryGTest.cxx

Follow-up to "ENH: Add operator== and operator!= to itk::Image"
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2188
commit 7f3337d27ee684aa4ab6ccbd294603926895ee82

ENH: Add operator==, operator!= to MetaDataObject and MetaDataDictionary

---

Modules/Filtering/LabelMap/include/itkBinaryImageToStatisticsLabelMapFilter.hxx
Modules/Filtering/LabelMap/include/itkLabelImageToStatisticsLabelMapFilter.hxx
Modules/Filtering/LabelMap/include/itkStatisticsLabelMapFilter.h

Addresses https://github.com/InsightSoftwareConsortium/ITK/pull/2514#issuecomment-830062366.  This pull request propagates the new behavior for the default `NumberOfBins` from `itk::StatisticsLabelMapFilter` to `itk::BinaryImageToStatisticsLabelMapFilter` and `itk::LabelImageToStatisticsLabelMapFilter`.

ENH: Propagate StatisticsLabelMapFilter's default NumberOfBins

---

Wrapping/Generators/SwigInterface/igenerator.py

Addresses #2520.
A `__eq__` method test for inequality with `...` (ellipsis) was failing because the test in question was implemented with `tuple(self) == tuple(other)`; and `tuple(...)` is an illegal operation because ellipsis is not an iterable.  This pull request replaces the test `!= ...` with `is not ...`.  This is in generated Python code for wrapping ITK objects and is part of the type hints mechanism.

BUG: Ellipsis is not iterable

---

.github/labeler.yml

Fix Python wrapping labeler action regex: make filename extensions
contain the `.py` string.

BUG: Fix Python wrapping labeler action regex

---

Modules/Filtering/LabelMap/ITKKWStyleOverwrite.txt
Modules/Filtering/LabelMap/include/itkBinaryImageToStatisticsLabelMapFilter.hxx
Modules/Filtering/LabelMap/include/itkLabelImageToStatisticsLabelMapFilter.hxx
Modules/Filtering/LabelMap/include/itkStatisticsLabelMapFilter.h
Modules/Filtering/LabelMap/include/itkStatisticsLabelMapFilter.hxx
Modules/Filtering/LabelMap/test/CMakeLists.txt
Modules/Filtering/LabelMap/test/itkStatisticsLabelMapFilterGTest.cxx

This pull request cherry picks the commits of Pull Requests #2514 and #2521 (from oldest to newest):
- c6da8be54ccff5ac4ca01813d8a17b1089f484f0 BUG: Add tests demonstration current behavior of histogram based median
- 208d7e32d75efe87df4c1537887f4b7ec8fd0c9a BUG: Fix StatisticsLabelMap median for even number of pixels
- 54675f3fbf7f7fd95c0fa15b8c3efafcdc1892e2 ENH: StatisticsLabelMapFilter use improve integer histogram
- bc95f51d9f2d17c0bbdfe16e9ed9c3b6baca9c76 ENH: Add additional testing for zero sized label object
- bb54bad6933f9c08f0882926573289c7f86fdba9 ENH: Propagate StatisticsLabelMapFilter's default NumberOfBins
from the master branch to the release branch.  The first four are from @blowekamp; the last is from @Leengit.

BUG: Fixes for median calculation

---

Modules/ThirdParty/HDF5/CMakeLists.txt
Modules/ThirdParty/HDF5/itk-module-init.cmake

Addresses instalation issue with ITK_USE_SYSTEM_HDF5 with a system HDF5 that does not provide a HDF5Config.cmake file. The wrong find_package signature was being generated in the ITKHDF5.cmake file.
This change is also needed in the release branch.

Fix HDF5 installed find package

---

Modules/Remote/TubeTK.remote.cmake

- Jupyter notebooks as examples
- More methods available in python
- Applications now published as examples - requires SlicerExecutionModel
- TubeTK_USE_VTK now on by default
- Github actions/CI publishes wheels automatically
- Github actions/CI includes VTK (static build) and SlicerExecutionModel

ENH: Bump TubeTK to TubeTK 0.9.0 rc1

---

Modules/Core/Common/include/itkAnnulusOperator.h
Modules/Core/SpatialObjects/include/itkMeshSpatialObject.h
Modules/Filtering/DisplacementField/include/itkLandmarkDisplacementFieldSource.hxx
Modules/Filtering/DistanceMap/include/itkContourDirectedMeanDistanceImageFilter.h
Modules/Filtering/DistanceMap/include/itkContourDirectedMeanDistanceImageFilter.hxx
Modules/Filtering/DistanceMap/include/itkDanielssonDistanceMapImageFilter.h
Modules/Filtering/DistanceMap/include/itkDirectedHausdorffDistanceImageFilter.h
Modules/Filtering/ImageGrid/include/itkPadImageFilterBase.h
Modules/Filtering/ImageStatistics/include/itkImagePCAShapeModelEstimator.h
Modules/Filtering/ImageStatistics/include/itkImagePCAShapeModelEstimator.hxx
Modules/Filtering/ImageStatistics/include/itkImageShapeModelEstimatorBase.h
Modules/Numerics/FEM/include/itkFEMObjectSpatialObject.h
Modules/Registration/Common/include/itkCompareHistogramImageToImageMetric.h
Modules/Registration/Common/include/itkCompareHistogramImageToImageMetric.hxx
Modules/Segmentation/Classifiers/include/itkImageGaussianModelEstimator.h
Modules/Segmentation/Classifiers/include/itkImageGaussianModelEstimator.hxx
Modules/Segmentation/Classifiers/include/itkImageKmeansModelEstimator.h
Modules/Segmentation/Classifiers/include/itkImageKmeansModelEstimator.hxx
Modules/Segmentation/Classifiers/include/itkScalarImageKmeansImageFilter.hxx

Improve style in miscellaneous files:
- Remove unnecessary separator comment lines to improve readability.
- Remove unnecessary comments at closing braces.
- Capitalize comment sentences.
- Improve the wording in some comments.
- Fix some typos.

STYLE: Improve style in miscellaneous files

---

Modules/Core/Transform/include/itkMatrixOffsetTransformBase.h
Modules/Core/Transform/include/itkMatrixOffsetTransformBase.hxx
Modules/Core/Transform/test/itkMatrixOffsetTransformBaseGTest.cxx

Replaced separate (`protected`) default-constructor and converting
constructor (from `unsigned int paramDims`) by a single `explicit`
constructor with default argument (still `protected` anyway).
Used C++11 in-class data member initializers.
Added extra GTest unit test to check `MatrixOffsetTransformBase::New()`.

STYLE: Combine code `MatrixOffsetTransformBase` constructors

---

Modules/Core/Common/include/itkAnnulusOperator.h
Modules/Core/Common/include/itkGaussianDerivativeOperator.h
Modules/Core/Common/include/itkGaussianOperator.h
Modules/Core/Common/include/itkImageKernelOperator.h
Modules/Core/Common/include/itkLaplacianOperator.h
Modules/Core/Common/include/itkNeighborhoodOperator.h
Modules/Core/Common/include/itkSobelOperator.h

Improve documentation in `Common` operator classes:
- Add documentation to type aliases/methods that are usually documented in
the same manner.
- Remove documentation from methods not needing it (e.g. the default
constructor).
- Remove excessive white spaces.
- Fix typos.
- Reduce the documentation block span if the documentation fits into a
single line.

DOC: Improve documentation in `Common` operator classes

---

Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest1.cxx
Modules/IO/MINC/test/itkMINCImageIOTest_2D.cxx
Modules/IO/MINC/test/itkMINCImageIOTest_4D.cxx
Modules/IO/MINC/test/itkMINCImageIOTest_Labels.cxx
Modules/IO/MRC/test/itkMRCImageIOTest.cxx
Modules/IO/MRC/test/itkMRCImageIOTest2.cxx
Modules/IO/MeshFreeSurfer/test/itkMeshFileReadWriteTest.cxx
Modules/IO/MeshGifti/test/itkMeshFileReadWriteTest.cxx
Modules/IO/MeshOBJ/test/itkMeshFileReadWriteTest.cxx
Modules/IO/MeshOFF/test/itkMeshFileReadWriteTest.cxx
Modules/IO/MeshVTK/test/itkMeshFileReadWriteTest.cxx
Modules/IO/Meta/test/itkMetaImageIOTest2.cxx
Modules/IO/NRRD/test/itkNrrdImageReadWriteTest.cxx
Modules/IO/RAW/test/itkRawImageIOTest3.cxx
Modules/IO/RAW/test/itkRawImageIOTest4.cxx
Modules/IO/RAW/test/itkRawImageIOTest5.cxx
Modules/Nonunit/Review/test/itkVoxBoCUBImageIOTest.cxx

Make test style more consistent:
- Use the ITK testing macros to reduce boilerplate code.
- Increase consistency in the missing argument check message and test
ending messages.
- Define the constant expressions (e.g. the image dimensionality) at a
single place at the beginning of the tests.
- Use the ITK C++ coding style (e.g. do not capitalize first letter in
local variable names, etc.).
Take advantage of the commit to fix some typos.

STYLE: Make test style more consistent

---

Modules/Filtering/DisplacementField/include/itkLandmarkDisplacementFieldSource.h
Modules/Filtering/DisplacementField/include/itkLandmarkDisplacementFieldSource.hxx
Modules/Filtering/DistanceMap/include/itkDanielssonDistanceMapImageFilter.h
Modules/Filtering/DistanceMap/include/itkDanielssonDistanceMapImageFilter.hxx
Modules/Filtering/ImageStatistics/include/itkImagePCAShapeModelEstimator.h
Modules/Filtering/ImageStatistics/include/itkImagePCAShapeModelEstimator.hxx
Modules/Filtering/ImageStatistics/include/itkImageShapeModelEstimatorBase.h
Modules/Filtering/ImageStatistics/include/itkImageShapeModelEstimatorBase.hxx
Modules/Filtering/LabelMap/include/itkBinaryNotImageFilter.h
Modules/IO/MINC/include/itkMINCImageIO.h
Modules/IO/MINC/src/itkMINCImageIO.cxx
Modules/Numerics/FEM/include/itkFEMObjectSpatialObject.h
Modules/Numerics/FEM/include/itkFEMObjectSpatialObject.hxx
Modules/Numerics/Statistics/include/itkVectorContainerToListSampleAdaptor.h
Modules/Numerics/Statistics/include/itkVectorContainerToListSampleAdaptor.hxx
Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFilter.hxx
Modules/Registration/RegistrationMethodsv4/include/itkSyNImageRegistrationMethod.h
Modules/Registration/RegistrationMethodsv4/include/itkSyNImageRegistrationMethod.hxx
Modules/Segmentation/Classifiers/include/itkImageGaussianModelEstimator.h
Modules/Segmentation/Classifiers/include/itkImageGaussianModelEstimator.hxx
Modules/Segmentation/Classifiers/include/itkImageKmeansModelEstimator.h
Modules/Segmentation/Classifiers/include/itkImageKmeansModelEstimator.hxx
Modules/Segmentation/ConnectedComponents/include/itkThresholdMaximumConnectedComponentsImageFilter.h
Modules/Segmentation/ConnectedComponents/include/itkThresholdMaximumConnectedComponentsImageFilter.hxx

Document members in header methods.
Transfer the documentation from the ivar or the method definition to the
header methods where the documentation was incomplete or missing.
- Improve the syntax of the existing documentation to stick to the
recommendations of the ITK SW Guide to generate the Doxygen
documentation (i.e. use the `/** <documentation.> */` convention).
- Improve the style of the existing documentation (e.g. capitals,
punctuation) to stick to the recommendations of the ITK SW Guide.
- Improve the wording of some comments.
- Remove the documentation of methods that are either not documented as
per the ITK SW Guide (e.g. constructors) or which are inherited members
whose purpose is not modified (e.g. `PrintSelf`).
- Remove the comments used to …

DOC: Document members in header methods

---

Modules/Core/Common/include/itkGaussianDerivativeOperator.h

Add missing getter method to `itk::GaussianDerivativeOperator` ivar.

ENH: Add missing getter method to `itk::GaussianDerivativeOperator` ivar

---

Modules/Core/Common/include/itkGaussianDerivativeOperator.h

Add run-time type information (RTTI) to the
`itk::GaussianDerivativeOperator` class.
Remove its `private` `GetNameOfClass` method: the RTTI macro defines it,
and it should be `public`.

ENH: Add RTTI information to `itk::GaussianDerivativeOperator`

---

Modules/Core/Common/include/itkIntTypes.h
Modules/Filtering/ImageNoise/include/itkAdditiveGaussianNoiseImageFilter.hxx
Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx
Modules/IO/TIFF/src/itkTIFFImageIO.cxx

Change itk namespace aliases from, for example,
```c++
using uint64_t = ::uint64_t;
```
to
```c++
using uint64_t = std::uint64_t;
```
Also, the version `uint64` is deprecated in favor of `uint64_t`.

COMP: Change ::uint32_t to std::uint32_t, uint32 to uint32_t, etc.

---

Modules/Core/Common/include/itkAnnulusOperator.h
Modules/Core/Common/include/itkDerivativeOperator.h
Modules/Core/Common/include/itkLaplacianOperator.h

Increase pixel type alias consistency in common operators:
- Make `PixelType` alias be public in `itk::AnnulusOperator`
- Prefer aliasing template pixel type in `common` operator classes

ENH: Increase pixel type alias consistency in common operators

---

Modules/Core/Common/include/itkLaplacianOperator.h

Add missing getter method to `itk::LaplacianOperator` class ivar.

ENH: Add missing getter method to `itk::LaplacianOperator` ivar

---

Modules/Core/Common/include/itkBackwardDifferenceOperator.h
Modules/Core/Common/include/itkDerivativeOperator.h
Modules/Core/Common/include/itkForwardDifferenceOperator.h
Modules/Core/Common/include/itkLaplacianOperator.h

Add run-time type information (RTTI) to `Common` operator classes.

ENH: Add RTTI information to `Common` operator classes

---

Modules/Segmentation/LevelSets/wrapping/wrap_itkNarrowBandCurvesLevelSetImageFilter.cmake.notwrapped

It is wrapped at:
Modules/Segmentation/LevelSets/wrapping/itkNarrowBandCurvesLevelSetImageFilter.wrap

DOC: Remove indication NarrowBandCurvesLevelSetImageFilter not wrapped

---

Modules/Filtering/FFT/include/itkForwardFFTImageFilter.h
Modules/Filtering/FFT/include/itkHalfHermitianToRealInverseFFTImageFilter.h
Modules/Filtering/FFT/include/itkInverseFFTImageFilter.h
Modules/Filtering/FFT/include/itkRealToHalfHermitianForwardFFTImageFilter.h

Without this fix, `ctest` tests on subclasses of these FFTImageFilter base classes will fail their run-time type information checks.

BUG: Add run-time type information to FFT filter base classes

---

Modules/Core/Common/test/itkAnnulusOperatorTest.cxx
Modules/Core/Common/test/itkDerivativeOperatorTest.cxx
Modules/Core/Common/test/itkGaussianDerivativeOperatorTest.cxx
Modules/Core/Common/test/itkNeighborhoodOperatorTest.cxx

Increase `Common` operator classes' code coverage:
- Remove explicit calls to the Print method and rely on the basic
input argument checking, test finishing message, make the types and
variables dwell closer to the place where they are instantiated, etc.)

ENH: Increase `Common` operators' code coverage

---

CMake/itkCompilerChecks.cmake
CMakeLists.txt
Documentation/SupportedCompilers.md
Modules/Core/Common/include/itkMacro.h
Wrapping/Generators/CastXML/CMakeLists.txt

Follow-up to commit babb6779b67a4b14f14cc5629da95105c8df4c83
"COMP: Enforce building ITK with C++11", Hans Johnson (@hjmjohnson), 19 January 2018
Discussion item: https://discourse.itk.org/t/may-we-start-using-c-14-at-the-master-branch/4172

ENH: Upgrade ITK from C++11 to C++14

---

Modules/Core/Common/include/itkOptimizerParameters.h
Modules/Filtering/DistanceMap/include/itkSignedMaurerDistanceMapImageFilter.hxx
Modules/Filtering/ImageFilterBase/include/itkTernaryGeneratorImageFilter.hxx
Modules/IO/TransformHDF5/src/itkHDF5TransformIO.cxx
Modules/Numerics/Optimizersv4/include/itkLBFGSOptimizerBasev4.hxx
Modules/Numerics/Optimizersv4/src/itkLBFGSBOptimizerv4.cxx

According to Clang-Tidy `modernize-make-unique`:
https://clang.llvm.org/extra/clang-tidy/checks/modernize-make-unique.html
C++ Core Guidelines, March 11, 2021, R.23: Use make_unique() to make unique_ptrs
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-make_unique

STYLE: Replace `new` by C++14 `std::make_unique`

---

Modules/Core/Common/include/itkImageBufferRange.h
Modules/Core/Common/include/itkImageRegionRange.h
Modules/Core/Common/include/itkIndexRange.h
Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h
Modules/Core/Common/include/itkSymmetricEigenAnalysis.h
Modules/Core/Common/include/itkThreadPool.h
Modules/Core/Common/test/itkNeighborhoodAllocatorGTest.cxx
Modules/Core/Transform/include/itkTransform.h
Modules/Core/Transform/include/itkTransform.hxx
Modules/Filtering/ImageFilterBase/include/itkCastImageFilter.h
Modules/Filtering/ImageFilterBase/include/itkCastImageFilter.hxx
Modules/Filtering/ImageFilterBase/test/itkCastImageFilterTest.cxx
Modules/Filtering/ImageGrid/include/itkBinShrinkImageFilter.h
Modules/IO/ImageBase/include/itkImageFileWriter.h

Replaced uses of nested types from `<type_traits>` (from C++11) by the
corresponding C++14 template aliases. Removed the corresponding `typename`
keywords that were originally necessary. Did so by running the following
command, at the GNU bash prompt, from the root of the ITK source tree:
find . \( -iname itk*.cxx -or -iname itk*.hxx -or -iname itk*.h \) -exec perl -pi -w -e 's/typename std::(\w+)<(.+)>::type/std::$1_t<$2>/g;' {} \;

STYLE: Use C++14 <type_traits> template aliases instead of nested types

---

Modules/Core/Common/include/itkLexicographicCompare.h

Simplified the implementation of `CoLexicographicCompare::operator()`.

STYLE: Use C++14 `make_reverse_iterator` inside `CoLexicographicCompare`

---

Modules/Registration/Common/include/itkImageToSpatialObjectMetric.h
Modules/Registration/Common/include/itkImageToSpatialObjectRegistrationMethod.h

Corrects the description of the motivation for SpatialObject registration.
In the particular case of ImageToSpatialObject registration, the
Transform to be computed is the one mapping points from the SpatialObject
into the Image.  This allows the SpatialObject to drive the location and
geometry of the measurements made in the image - thereby if the spatial
object is sparse and/or contains varying geometric features, the metric
applied to measure how well that object matches with the image can be
rapidly computed only at the sparse locations and using measures that
match the local geometry that should be at those locations in the image.
This is particularly useful for fast intra-operative registration when the
pre-operative data is used to define a SpatialObject and can anticipate
how that …

DOC: Fix description of SpatialObjectToImage registration

---

Modules/Bridge/NumPy/wrapping/test/itkPyBufferMemoryLeakTest.py

Add numbers (1, 2, 3) to the print messages in itkPyBufferMemoryLeakTest,
to ease analysis of the output from a test failure.

ENH: Add numbers to the three `itkPyBufferMemoryLeakTest` print messages

---

Modules/Core/Common/include/itkConnectedImageNeighborhoodShape.h

Simplified `GenerateConnectedImageNeighborhoodShapeOffsets()` by using
C++14 automatic return type deduction.

STYLE: C++14 auto return type for ConnectedImageNeighborhoodShapeOffsets

---

Modules/Core/Common/test/itkNeighborhoodOperatorTest.cxx

Prefer implicitly deriving the array size in
`itkNeighborhoodOperatorTest.cxx`.

STYLE: Prefer implicitly deriving array size in test

---

Modules/Core/Common/wrapping/itkImageDuplicator.wrap

This is a follow-up to #2554, suggested in
https://github.com/InsightSoftwareConsortium/ITK/pull/2578#issuecomment-855014914

ENH: Add support for long long pixel types to ImageDuplicator wrapping

---

Modules/Video/Core/include/itkVideoStream.h
Modules/Video/Core/include/itkVideoStream.hxx
Modules/Video/Core/wrapping/CMakeLists.txt
Modules/Video/Core/wrapping/itkRingBuffer.wrap
Modules/Video/Core/wrapping/itkTemporalDataObject.wrap
Modules/Video/Core/wrapping/itkTemporalRegion.wrap
Modules/Video/Core/wrapping/itkVideoStream.wrap

Wraps `itk::VideoStream` and related components in `ITKVideoCore` for Python.

ENH: Wrap ITKVideoStream

---

Modules/Core/Common/include/itkImage.h
Modules/Core/Common/test/itkImageGTest.cxx

The ability to instantiate `itk::Image<TPixel, VImageDimension>` for a
non-EqualityComparable pixel type was broken by:
"ENH: Add operator== and operator!= to itk::Image"
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2188
commit 7f3337d27ee684aa4ab6ccbd294603926895ee82
Reported by Bradley Lowekamp:
issue https://github.com/InsightSoftwareConsortium/ITK/issues/2583
"Explicit instantiation of itk::Image fails with 5.2 when pixel type
does not support operator=="
This commit fixes the issue by defining the `operator==` and `operator!=`
friend functions of `itk::Image` as function _templates_, rather than as
non-templates.

COMP: Support non-EqualityComparable pixels Image template instantiation

---

Modules/Core/Common/include/itkImageRegion.h
Modules/Core/ImageAdaptors/include/itkBluePixelAccessor.h
Modules/Core/ImageAdaptors/include/itkGreenPixelAccessor.h
Modules/Core/ImageAdaptors/include/itkRedPixelAccessor.h
Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshBaseIterator.h
Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshFrontIterator.h

Replaced hand-written definitions of `operator!=` member functions by
`ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION` macro calls, in Modules/Core.
Did some minor adjustments to corresponding `operator==` member
functions, where necessary, and removed non-const operator overloads.
Follow-up to commit 0ad6ef1b558f162e83562a3d420f24aca38fa8d8
"STYLE: Use `ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION` in Core/Common"

STYLE: Use `ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION` in Modules/Core

---

Modules/Bridge/VtkGlue/CMakeLists.txt
Modules/Bridge/VtkGlue/itk-module-init.cmake
Wrapping/Generators/Python/Tests/verifyGetOutputAPIConsistency.py

- BUG: Ignore ImageToVTKImageFilter in VerifyGetOutputAPIConsistency test
- ENH: Required VTK 8 or newer

vtk version

---

Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
Wrapping/Generators/Python/PyBase/pyBase.i
Wrapping/Generators/SwigInterface/igenerator.py

Python 3.6 will be deprecated by python.org by the end of the year.

COMP: Require Python 3.7 or newer

---

Modules/Core/ImageAdaptors/include/itkNthElementPixelAccessor.h
Modules/Filtering/ImageFusion/include/itkLabelOverlayFunctor.h
Modules/Filtering/ImageFusion/include/itkLabelToRGBFunctor.h
Modules/Filtering/ImageIntensity/include/itkAdaptImageFilter.h
Modules/Filtering/ImageIntensity/include/itkArithmeticOpsFunctors.h
Modules/Filtering/ImageIntensity/include/itkClampImageFilter.h
Modules/Filtering/ImageIntensity/include/itkClampImageFilter.hxx
Modules/Filtering/ImageIntensity/include/itkExpNegativeImageFilter.h
Modules/Filtering/ImageIntensity/include/itkIntensityWindowingImageFilter.h
Modules/Filtering/ImageIntensity/include/itkInvertIntensityImageFilter.h
Modules/Filtering/ImageIntensity/include/itkMatrixIndexSelectionImageFilter.h
Modules/Filtering/ImageIntensity/include/itkRescaleIntensityImageFilter.h
Modules/Filtering/ImageIntensity/include/itkSigmoidImageFilter.h
Modules/Filtering/ImageIntensity/include/itkVectorIndexSelectionCastImageFilter.h
Modules/Filtering/ImageIntensity/include/itkVectorRescaleIntensityImageFilter.h
Modules/Filtering/ImageIntensity/include/itkWeightedAddImageFilter.h
Modules/Filtering/ImageLabel/include/itkChangeLabelImageFilter.h
Modules/Filtering/LabelMap/include/itkLabelMap.h
Modules/Filtering/LabelMap/include/itkLabelObject.h
Modules/Filtering/Thresholding/include/itkBinaryThresholdImageFilter.h
Modules/Filtering/Thresholding/include/itkThresholdLabelerImageFilter.h

Two related commits:
- ENH: Add `NthElementPixelAccessor::operator==` 
- STYLE: Use ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION in Modules/Filtering
The `NthElementPixelAccessor::operator==` overloads appear necessary in order to implement `AccessorFunctor::operator==` by a simple `return m_Accessor == other.m_Accessor`.

Add `NthElementPixelAccessor::operator==`, use `ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION` in Filtering 

---

Modules/Core/Common/include/itkSliceIterator.h
Modules/Core/Common/test/itkSimpleFilterWatcherTest.cxx
Modules/Filtering/ImageFeature/include/itkUnsharpMaskImageFilter.h
Modules/Numerics/Statistics/include/itkHistogram.h
Modules/Numerics/Statistics/include/itkImageToListSampleAdaptor.h
Modules/Numerics/Statistics/include/itkImageToNeighborhoodSampleAdaptor.h
Modules/Numerics/Statistics/include/itkJointDomainImageToListSampleAdaptor.h
Modules/Numerics/Statistics/include/itkListSample.h
Modules/Numerics/Statistics/include/itkMembershipSample.h
Modules/Numerics/Statistics/include/itkPointSetToListSampleAdaptor.h
Modules/Numerics/Statistics/include/itkSubsample.h
Modules/Numerics/Statistics/include/itkVectorContainerToListSampleAdaptor.h
Modules/Segmentation/ConnectedComponents/include/itkScalarConnectedComponentImageFilter.h
Modules/Segmentation/LevelSetsv4/include/itkLevelSetContainerBase.h
Modules/Segmentation/LevelSetsv4/include/itkLevelSetEquationContainer.h
Modules/Segmentation/LevelSetsv4/include/itkLevelSetEquationTermContainer.h
Modules/Video/Core/include/itkTemporalRegion.h
Modules/Video/Core/src/itkTemporalRegion.cxx
Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx

And also used this macro in `UnsharpMaskingFunctor`, `SliceIterator`, and `TanHelper`.
Note: This should be the last "bulk PR" to add those `ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION` macro calls.

Use `ITK_UNEQUAL_OPERATOR_MEMBER_FUNCTION` in Numerics, Segmentation, Video 

---

Modules/Filtering/Colormap/include/itkColormapFunction.h

The `virtual` `ColormapFunction` member functions `operator!=` and
`operator==` appear incorrect, as they always just return `false` or
`true`, respectively, even while `ColormapFunction` has four values as
data members, and corresponding setters and getters.
The two member functions aren't used elsewhere in ITK, and they aren't
overridden by derived ITK classes. So instead of fixing them, it appears
preferable to just remove them.

BUG: Remove unused virtual operator!=, operator== from ColormapFunction

---

Modules/Compatibility/Deprecated/test/itkSimpleFastMutexLockTest.cxx

Fixed a Visual C++ 2019 error, saying:
> Deprecated\test\itkSimpleFastMutexLockTest.cxx(48,12): error C2039: 'cout': is not a member of 'std'

COMP: Add missing `#include <iostream>` to Deprecated module test

---

CMakeLists.txt

ce2efb1b9eeb439465ab0355a2445091fc2f2e52 broke runtime library setting
due to implicitly using `NEW` value for CMake policy CMP0091.
This caused dynamic runtime library even if /MT was present in
CMAKE_CXX_FLAGS_RELEASE and friends in CMake cache.
This a `release` branch clone of #2609.

COMP: Restore generation of static runtime library on MSVC

---

Modules/Core/Common/src/itkMultiThreaderBase.cxx

To address:
/ITK/Modules/Core/Common/src/itkMultiThreaderBase.cxx:538:17: warning:
variable 'pixelCount' set but not used [-Wunused-but-set-variable]
SizeValueType pixelCount = 1;

COMP: Remove MultiThreaderBase pixelCount

---

Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml
Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml

With numpy 1.21.0, PythonMedianImageFilterTest fails with:
2916: Traceback (most recent call last):
2916:   File "/home/matt/src/ITK/Modules/Filtering/Smoothing/wrapping/test/MedianImageFilterTest.py", line 56, in <module>
2916:     type_hints = get_type_hints(itk.median_image_filter, globalns= { 'itk': itk })
2916:   File "/home/matt/bin/miniconda/lib/python3.8/typing.py", line 1266, in get_type_hints
2916:     value = _eval_type(value, globalns, localns)
2916:   File "/home/matt/bin/miniconda/lib/python3.8/typing.py", line 272, in _eval_type
2916:     ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__)
2916:   File "/home/matt/bin/miniconda/lib/python3.8/typing.py", line 272, in <genexpr>
2916:     ev_args = tuple(_eval_type(a, globalns, localns) for a in t.__args__) …

COMP: Use numpy==1.20.3 for CI testing

---

Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx

To address:
In file included from /ITK/Modules/Core/Common/src/itkFloatingPointExceptions.cxx:127:
/ITK/Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx:147:22: error: use of undeclared identifier 'FE_DIVBYZERO'
itk_feenableexcept(FE_DIVBYZERO);
^
/ITK/Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx:148:22: error: use of undeclared identifier 'FE_INVALID'
itk_feenableexcept(FE_INVALID);
^
/ITK/Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx:169:23: error: use of undeclared identifier 'FE_DIVBYZERO'
itk_fedisableexcept(FE_DIVBYZERO);
^
/ITK/Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx:170:23: error: use of undeclared identifier 'FE_INVALID'
itk_fedisableexcept(FE_INVALID);
^
4 errors generated.
With Emscription 2.
Default values based on …

COMP: Provide default values for floating point macros

---

Modules/Compatibility/Deprecated/include/itkTreeIteratorClone.h
Modules/Core/Common/include/itkConstShapedNeighborhoodIterator.h
Modules/Core/Common/include/itkMacro.h
Modules/Core/Common/include/itkWeakPointer.h

Added an experimental macro to indicate that ITK makes use of C++20
automatically rewritten `operator!=`. Used this macro to fix various
GCC C++20 compile errors reported by Darren Thompson (@darrent1974) at
https://github.com/InsightSoftwareConsortium/ITK/pull/2589#issuecomment-867427430:
> itkWeakPointer.h:80:42: error: expected unqualified-id before ';' token
and:
> itkConstShapedNeighborhoodIterator.h:284:29: error: 'operator!=' has not been declared
Also used the macro for `TreeIteratorClone`.

ENH: Add `ITK_EXPERIMENTAL_CXX20_REWRITTEN_UNEQUAL_OPERATOR` macro

---

Modules/Core/Common/include/itkArray.h
Modules/Core/Common/include/itkArray.hxx

Most of the eight `Array` constructors initialize
`m_LetArrayManageMemory` as `true` anyway. Only
`Array(ValueType *, SizeValueType, bool = false)`
allows a different initial value.
Also somewhat fixed the documentation.

STYLE: Add default member initializer `true` to `m_LetArrayManageMemory`

---

Modules/Video/IO/wrapping/itkFileListVideoIO.wrap
Modules/Video/IO/wrapping/itkVideoFileReader.wrap
Modules/Video/IO/wrapping/itkVideoFileWriter.wrap
Modules/Video/IO/wrapping/itkVideoIOBase.wrap

Adding Python wrappings for `itkVideoFileReader`, `itkVideoFileWriter`, and `itkFileListVideoIO`.

ENH: Add wrappings for video IO

---

.git-blame-ignore-revs

This is the followup pull request to Pull Request #2608 that is described there.   To `.git-blame-ignore-revs`, add the hash for the commit that reformats Python code with `black`.

STYLE: Add Python-formatting commit's hash to .git-blame-ignore-revs.

---

Modules/Core/Transform/include/itkSimilarity3DTransform.hxx
Modules/Core/Transform/test/CMakeLists.txt
Modules/Core/Transform/test/itkSimilarityTransformGTest.cxx

Closes #2629 "Similarity3DTransform::SetScale should recompute m_Offset", which said:
> When `Similarity3DTransform::SetScale` is called, it does not compute
> `m_Offset`, which appears to cause an incorrect result from
> `similarity3DTransform.TransformPoint` when `TransformPoint` is called
> directly after `SetScale`.
Included a unit test (GoogleTest) to ensure that the issue is fixed.

BUG: Similarity3DTransform::SetScale should recompute m_Offset

---

Modules/Core/Mesh/wrapping/itkMeshToMeshFilter.wrap
Modules/Core/Mesh/wrapping/itkTransformMeshFilter.wrap
Modules/IO/MeshBase/wrapping/itkMeshFileWriter.wrap

MeshFileWriter was erroneously wrapped for
WRAP_ITK_REAL instead of WRAP_ITK_SCALAR.
```text
itk.meshwrite(mesh, file_path)
...
itk.support.extras.TemplateTypeError: itk.MeshFileWriter is not wrapped for input type `itk.Mesh[itk.UC,3]`.
To limit the size of the package, only a limited number of
types are available in ITK Python.
...
Supported input types:
itk.Mesh[itk.F,2]
itk.Mesh[itk.D,2]
itk.Mesh[itk.F,3]
itk.Mesh[itk.D,3]
```

COMP: add missing wrapping for MeshFileWriter

---

Modules/Core/Common/include/itkIndex.h
Modules/Core/Common/include/itkPoint.h
Modules/Core/Common/include/itkSize.h
Modules/Core/Common/include/itkVector.h
Modules/Core/Common/test/itkIndexGTest.cxx
Modules/Core/Common/test/itkPointGTest.cxx
Modules/Core/Common/test/itkSizeGTest.cxx
Modules/Core/Common/test/itkVectorGTest.cxx

Added a templated generalization of the overloaded `MakePoint`,
`MakeVector`, `MakeIndex`, and `MakeSize`, functions from
"itkGTestTypedefsAndConstructors.h", allowing them to be more widely
used.
Placed the function templates directly in the namespace `itk`.

ENH: Add MakePoint, MakeVector, MakeIndex, MakeSize function templates

---

Modules/Core/Transform/test/itkBSplineTransformGTest.cxx
Modules/Filtering/ImageGrid/test/itkSliceImageFilterTest.cxx
Modules/Filtering/ImageGrid/test/itkTileImageFilterGTest.cxx
Modules/Filtering/LabelMap/test/itkShapeLabelMapFilterGTest.cxx
Modules/Segmentation/ConnectedComponents/test/itkConnectedComponentImageFilterGTest.cxx
Modules/Segmentation/ConnectedComponents/test/itkRelabelComponentImageFilterGTest.cxx

Replaced calls to the `Make` functions from the namespace
`itk::GTest::TypedefsAndConstructors` by calls to the function templates
from `itk`, that were added by:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2633
commit 8aed68490b733ba45b36b2e8e84e99980db45948
"ENH: Add MakePoint, MakeVector, MakeIndex, MakeSize function templates"

STYLE: Use MakePoint, MakeVector, MakeIndex, MakeSize from itk namespace

---

Modules/Filtering/LabelMap/test/itkStatisticsLabelMapFilterGTest.cxx
Modules/IO/NIFTI/test/itkNiftiImageIOTest12.cxx
Modules/Video/Core/test/itkImageToVideoFilterTest.cxx

Resolves nightly exotic build warnings relating to `itk::Index` and `itk::Point` initialization by relying on `itk::MakeIndex` and `itk::MakePoint` helpers.
[Build information](https://open.cdash.org/viewBuildError.php?type=1&buildid=7339831):
Site: RogueResearch7
Build Name: Mac10.11-AppleClang-dbg-x86_64-static
Build Time: 2021-07-14 05:03:37
Warnings resolved:
> [CTest: warning matched] /Users/builder/externalModules/Filtering/LabelMap/test/itkStatisticsLabelMapFilterGTest.cxx:201:30: warning: suggest braces around initialization of subobject [-Wmissing-braces]
image->SetPixel(IndexType{ 0, 0 }, 32000);
...
> CTest: warning matched] /Users/builder/externalModules/Video/Core/test/itkImageToVideoFilterTest.cxx:122:49: warning: suggest braces around initialization of subobject …

BUG: Resolve warnings with MakeIndex and MakePoint

---

Modules/Core/TestKernel/include/itkGTestTypedefsAndConstructors.h
Modules/Core/TestKernel/test/itkGoogleTest.cxx

Removed the `Make` functions from the namespace
`itk::GTest::TypedefsAndConstructors` as they are superseded by:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2633
commit 8aed68490b733ba45b36b2e8e84e99980db45948
"ENH: Add MakePoint, MakeVector, MakeIndex, MakeSize function templates"
Adjusted itkGoogleTest.cxx accordingly.

STYLE: Remove `Make` functions from itk::GTest::TypedefsAndConstructors

---

Modules/Core/Common/test/itkMetaProgrammingLibraryTest.cxx

itkMetaProgrammingLibraryTest is testing itkStaticAssert,
which has been recently deprecated.
When ITK_LEGACY_REMOVE is turned on, it caused compiler errors
of the following style:
```text
Modules/Core/Common/test/itkMetaProgrammingLibraryTest.cxx line 33 (https://open.cdash.org/viewBuildError.php?type=0&amp;buildid=7345514
M:\Dashboard\ITK\Modules\Core\Common\test\itkMetaProgrammingLibraryTest.cxx(33): error C2065: 'Use': undeclared identifier [M:\Dashboard\ITK-build\Modules\Core\Common\test\ITKCommon2TestDriver.vcxproj]
```

COMP: test fails to compile when legacy support is removed

---

Modules/Core/Common/include/itkThreadPool.h
Modules/Core/Common/src/itkThreadPool.cxx

Closes #2069.
_Initial (**old**) description:_
This turns a hang into:
```text
(pyEnv) dzenan@corista:~/nn_work_dir$ python itkMultiProcessingMONAI.py 
main pid: 2578395 140116265719616
Resampling image_0.nii pid: 2578395 140116265719616...
Resampling image_0.nii pid: 2578404 140116265719616...
Resampling image_1.nii pid: 2578404 140116265719616...
In ThreadPool::atfork_prepareIn ThreadPool::atfork_resumeTraceback (most recent call last):
File "itkMultiProcessingMONAI.py", line 44, in <module>
p.map(f, paths)
File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: …
```

ENH: fix Python multi-processing hang on unix

---

Modules/Nonunit/Review/test/itkAreaClosingImageFilterTest.cxx
Modules/Nonunit/Review/test/itkAreaOpeningImageFilterTest.cxx
Modules/Nonunit/Review/test/itkConformalFlatteningMeshFilterTest.cxx
Modules/Nonunit/Review/test/itkLabelGeometryImageFilterTest.cxx
Modules/Nonunit/Review/test/itkOptMattesMutualInformationImageToImageMetricThreadsTest1.cxx
Modules/Nonunit/Review/test/itkScalarChanAndVeseDenseLevelSetImageFilterTest2.cxx
Modules/Nonunit/Review/test/itkScalarChanAndVeseDenseLevelSetImageFilterTest4.cxx
Modules/Nonunit/Review/test/itkScalarChanAndVeseSparseLevelSetImageFilterTest2.cxx
Modules/Nonunit/Review/test/itkStochasticFractalDimensionImageFilterTest.cxx

Increase `Review` module classes' code coverage:

ENH: Increase `Review` module classes' code coverage

---

Modules/Core/Transform/test/itkMatrixOffsetTransformBaseGTest.cxx

Comparing an `itk::FixedArray` to an `itk::Point` appears to cause C++20
compilation errors, as observed with Visual Studio 2019 ("/std:c++latest"),
reported by @QuellaZhang, issue https://github.com/InsightSoftwareConsortium/ITK/issues/2640
> itkMatrixOffsetTransformBaseGTest.i(390249): error C2666: 'itk::FixedArray<double,2>::operator ==': 2 overloads have similar conversions
> itkMatrixOffsetTransformBaseGTest.i(87990): note: could be 'bool itk::FixedArray<double,2>::operator ==(const itk::FixedArray<double,2> &) const'
> itkMatrixOffsetTransformBaseGTest.i(390240): note: or       'bool testing::internal::operator ==(testing::internal::faketype,testing::internal::faketype)'
> itkMatrixOffsetTransformBaseGTest.i(269102): note: or 'bool itk::Point<TParametersValueType,2>::operator …

COMP: Remove comparison to FixedArray in MatrixOffsetTransformBase GTest

---

Modules/Filtering/LabelMap/include/itkAttributeLabelObject.h

Initialize member in `itk::AttributeLabelObject`.
Fixes:
```
==6189== Command: /tmp/bld/ITK-build/bin/ITKLabelMapTestDriver
itkAttributeLabelObjectAccessorsTest1
/tmp/bld/ITK-build/ExternalData/Testing/Data/Input/cthead1Label.png
/tmp/bld/ITK-build/ExternalData/Testing/Data/Input/cthead1.png
==6189== Parent PID: 55
==6189==
UMC ==6189== Conditional jump or move depends on uninitialised value(s)
==6189==    at 0x91423DC: __printf_fp_l (in /usr/lib64/libc-2.17.so)
==6189==    by 0x91414D6: vfprintf (in /usr/lib64/libc-2.17.so)
==6189==    by 0x916C178: vsnprintf (in /usr/lib64/libc-2.17.so)
==6189==    by 0x8C5B63C: ??? (in /usr/lib64/libstdc++.so.6.0.19)
==6189==    by 0x8C61CA3: std::ostreambuf_iterator > std::num_put >
>::_M_insert_float(std::ostreambuf_iterator >, std::ios_base&, char, …
```

BUG: Initialize member in `itk::AttributeLabelObject`

---

Modules/Nonunit/Review/test/itkStochasticFractalDimensionImageFilterTest.cxx

To address https://open.cdash.org/viewBuildError.php?type=0&buildid=7354490:
```text
/Users/builder/externalModules/Nonunit/Review/test/itkStochasticFractalDimensionImageFilterTest.cxx:46:50: error: use of undeclared identifier 'StochasticFractalDimensionImageFilter'
EXERCISE_BASIC_OBJECT_METHODS(fractalFilter, StochasticFractalDimensionImageFilter, ImageToImageFilter);
^
/Users/builder/externalModules/Nonunit/Review/test/itkStochasticFractalDimensionImageFilterTest.cxx:46:89: error: use of undeclared identifier 'ImageToImageFilter'
EXERCISE_BASIC_OBJECT_METHODS(fractalFilter, StochasticFractalDimensionImageFilter, ImageToImageFilter);
^
2 errors generated.
```

COMP: add ITK_ prefix in itkStochasticFractalDimensionImageFilterTest

---

CMake/ITKModuleMacros.cmake

With CMake 3.20.4, this causes some sort of cache / module enablement
recursion issue resulting in the backtrace:
CMake Error at CMake/ITKModuleAPI.cmake:78 (message):
No such module: "ITKIOPNG"
CMake/ITKModuleAPI.cmake:31 (itk_module_load)
CMake/ITKModuleAPI.cmake:129 (_itk_module_config_recurse)
/home/kitware/Dashboards/Tests/ITK-build/CMakeTmp/ITKConfig.cmake:47 (itk_module_config)
Modules/Remote/AnisotropicDiffusionLBR/examples/CMakeLists.txt:5 (find_packag
We do not need the remote module examples for the Doxygen build, so do
not enable them by default in this case.

COMP: Do not enable remote module examples when building Doxygen docs

---

Modules/Core/SpatialObjects/include/itkMetaSceneConverter.hxx

The color of a SpatialObject was not being passed to the MetaObject used to write it to disk.  As a result, color info was lost on write.
This is tested in itkTubeTK, but the baselines were incorrect.  Updated baselines in itkTubeTK will verify these changes.

BUG: Write spatial object color

---

Modules/Core/SpatialObjects/include/itkTubeSpatialObject.h
Modules/Core/SpatialObjects/include/itkTubeSpatialObject.hxx

Calling CopyInformation on a TubeSpatialObject did not copy
member variables - defaulted to CopyInformation of a Superclass
instead.
This is tested in itkTubeTK, but the baselines were incorrect.  Updated baselines in itkTubeTK will verify these changes.

BUG: TubeSpatialObject missing CopyInformation

---

Modules/Core/SpatialObjects/include/itkMetaVesselTubeConverter.hxx

MetaVesselTubeConverter had a case mis-match on reading and writing "True" and "False" for Artery flag.  Fixed by making the argument test case insensitive.
This was already being tested in itkTubeTK, but the wrong baselines were used so incorrect results were being accepted.  Updates to itkTubeTK will include new baselines.

BUG: TubeSpatialObject didn't preserver Artery flag

---

Modules/Core/Common/CMake/itkCheckHasMallinfo2.cxx
Modules/Core/Common/CMakeLists.txt
Modules/Core/Common/include/itkMemoryUsageObserver.h
Modules/Core/Common/src/itkConfigure.h.in
Modules/Core/Common/src/itkMemoryUsageObserver.cxx

To address:
[2026/8057] Building CXX object Modules/Core/Common/src/CMakeFiles/ITKCommon.dir/itkMemoryUsageObserver.cxx.o
/home/matt/src/ITK/Modules/Core/Common/src/itkMemoryUsageObserver.cxx: In member function ‘virtual itk::MemoryUsageObserverBase::MemoryLoadType itk::MallinfoMemoryUsageObserver::GetMemoryUsage()’:
/home/matt/src/ITK/Modules/Core/Common/src/itkMemoryUsageObserver.cxx:450:36: warning: ‘mallinfo mallinfo()’ is deprecated [-Wdeprecated-declarations]
450 |   struct mallinfo minfo = mallinfo();
|                                    ^
In file included from /home/matt/src/ITK/Modules/Core/Common/src/itkMemoryUsageObserver.cxx:37:
/usr/include/malloc.h:118:24: note: declared here
118 | extern struct mallinfo mallinfo (void) __THROW __MALLOC_DEPRECATED;
| …

COMP: Use mallinfo2 when available

---

Modules/Remote/AdaptiveDenoising.remote.cmake

Preparing for future code builds with ITK_FUTURE_LEGACY=ON requires
that deprecated function names be replaced with new
names.  Replace SetUseImageSpacingOn() with SetUseImageSpacing(true)

COMP: Fix compilation for ITK_FUTURE_LEGACY=ON

---

Modules/Core/Transform/include/itkBSplineTransformInitializer.h
Modules/Core/Transform/include/itkBSplineTransformInitializer.hxx
Modules/Registration/Common/include/itkCenteredTransformInitializer.h
Modules/Registration/Common/include/itkCenteredTransformInitializer.hxx
Modules/Registration/Common/include/itkCenteredVersorTransformInitializer.h
Modules/Registration/Common/include/itkCenteredVersorTransformInitializer.hxx
Modules/Registration/Common/include/itkLandmarkBasedTransformInitializer.h
Modules/Registration/Common/include/itkLandmarkBasedTransformInitializer.hxx
Modules/Registration/Common/test/CMakeLists.txt
Modules/Registration/Common/test/itkTransformInitializersGTest.cxx

Declared the default-constructors of `BSplineTransformInitializer`,
`CenteredTransformInitializer`, and `LandmarkBasedTransformInitializer`
by `= default`.
Initialized data members of `TransformInitializer` classes by in-class
default-member-initializers.
Added itkTransformInitializersGTest.cxx to check that `New()` still
properly initializes a `TransformInitializer`, as it did before.

STYLE: TransformInitializers constructors = default; default-member-init

---

Modules/Core/SpatialObjects/include/itkMetaSceneConverter.h
Modules/Core/SpatialObjects/include/itkMetaSceneConverter.hxx
Modules/Core/SpatialObjects/include/itkSpatialObject.h
Modules/Core/SpatialObjects/include/itkSpatialObject.hxx
Modules/Core/SpatialObjects/include/itkSurfaceSpatialObjectPoint.h
Modules/Core/SpatialObjects/include/itkSurfaceSpatialObjectPoint.hxx
Modules/Core/SpatialObjects/test/itkSurfaceSpatialObjectTest.cxx
Modules/Core/SpatialObjects/wrapping/itkSpatialObjectBase.wrap
Modules/IO/SpatialObjects/include/itkSpatialObjectWriter.h

SpatialObjects can now return a const list of their children, and SpatialObjectWriter accepts a const object.
Furthermore, updated test...A spatial object point has a position in object space, but until it is added to a spatial object (which potentially exists in a hierarchy of objects with parent/child transforms) the point does not have a position in world space.  So, the test has been updated to add a point to an object before asking for that point's world space position.

COMP: Update SpatialObjects to correct const-ness

---

Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5PropList.cpp

Ref #2640.
Error message from MSVC with C++23 enabled:
F:\gitP\InsightSoftwareConsortium\ITK\Modules\ThirdParty\HDF5\src\itkhdf5\c++\src\H5PropList.cpp(558,1): error C2440: 'return': cannot convert from 'int' to 'std::basic_string<char,std::char_traits,std::allocator>' [F:\gitP\InsightSoftwareConsortium\ITK\build_x86\Modules\ThirdParty\HDF5\src\itkhdf5\c++\src\hdf5_cpp-static.vcxproj]

COMP: a method should not return an integer instead of an std::string

---

Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml
Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml

- COMP: Revert "COMP: Use numpy==1.20.3 for CI testing". Closes #2613.

numpy 1.21.1 testing

---

Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.h

Addresses visibility issues when building on macOS / static, e.g. with
the Python wrappings.

COMP: Add missing template export macro to SLICImageFilter

---

CMake/ITKInitializeCXXStandard.cmake
CMake/ITKModuleExternal.cmake
CMakeLists.txt

We now default to C++14, which is not the default standard on most compilers. Addresses:
Modules/Core/Common/include/itkMacro.h:192:6: error: "Apple LLVM < 5.1 (clang < 3.4) is not supported under ITKv5.3"
When building remote modules externally, which is triggered by too low of a C++ standard.

BUG: Initialize C++ standard for remote modules

---

Modules/Core/Common/include/itkMacro.h

This error could be confusing if a sufficiently new Clang version is
used but C++11 or C++03 is used.

DOC: Improve Apple Clang error to include C++14 requirement

---

Modules/IO/NIFTI/src/itkNiftiImageIO.cxx

Fixes #2674
NIFTI sform matrices were being called non-invertible if their determinant was <
10-5. Because the determinant scales with the product of the voxel spacings, any
image with voxels smaller than about 20 microns would not have its direction
cosines read from the sform. This caused errors when the header sform was valid,
but the qform transform was not available as a fallback.
Invertibility is now tested by checking the condition number of the singular
value decomposition. If this is above the float epsilon, the matrix will be
considered invertible.
An alternative solution would be to consider a matrix invertible whenever the
determinant is > 0, which is what itkMatrix does. The condition number test as
implemented is a bit more conservative, but should allow spacings down to a …

BUG: Fix matrix check rejecting NIFTI sform for small voxels

---

Modules/Core/Transform/wrapping/CMakeLists.txt

The wrapping of the new itkResampleInPlaceImageFilter was not
included in the CMakeLists.txt files.

BUG: Missed wrapping of itkResampleInPlaceImageFilter

---

Modules/Core/Common/include/itkFixedArray.h
Modules/Core/Common/include/itkFixedArray.hxx
Modules/Core/Common/include/itkIndex.h
Modules/Core/Common/include/itkSize.h
Modules/Core/Common/test/itkFixedArrayGTest.cxx
Modules/Core/Common/test/itkIndexGTest.cxx
Modules/Core/Common/test/itkSizeGTest.cxx

Declared the `Filled(value)` and `operator[](pos)` member functions of
`itk::FixedArray`, `itk::Index`, and `itk::Size` constexpr.

ENH: Declare Filled and operator[] of Index, Size, FixedArray constexpr

---

Documentation/ITK5MigrationGuide.md
Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h
Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.hxx
Modules/Core/Common/test/itkBSplineInterpolationWeightFunctionTest.cxx
Modules/Core/Transform/include/itkBSplineBaseTransform.h
Modules/Core/Transform/include/itkBSplineBaseTransform.hxx
Modules/Core/Transform/include/itkBSplineDeformableTransform.hxx
Modules/Core/Transform/include/itkBSplineTransform.hxx
Modules/Core/Transform/test/itkBSplineDeformableTransformTest.cxx
Modules/Core/Transform/test/itkBSplineTransformGTest.cxx
Modules/Core/Transform/test/itkBSplineTransformTest.cxx
Modules/Registration/Common/include/itkImageToImageMetric.hxx

Replaced the `GetNumberOfWeights()` member functions of both `BSplineBaseTransform` and `BSplineInterpolationWeightFunction` by static constexpr `NumberOfWeights` data members.
Allows using the number of weights at compile-time, for example to declare an `std::array` of those weights.

ENH: Replace GetNumberOfWeights() by static constexpr `NumberOfWeights`

---

Documentation/ITK5MigrationGuide.md
Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h
Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.hxx
Modules/Core/Common/test/itkBSplineInterpolationWeightFunctionTest.cxx
Modules/Core/Transform/include/itkBSplineDeformableTransform.hxx

Replaced the `GetSupportSize()` member function of
`BSplineInterpolationWeightFunction` by a static constexpr data member,
`SupportSize`.
Allows using this size at compile-time.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2709
commit 34f3db8d8ad0ba848cbbfee071edf327e09f6a96
"ENH: Replace GetNumberOfWeights() by static constexpr `NumberOfWeights`"

ENH: Replace BSpline GetSupportSize() by static constexpr `SupportSize`

---

Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h
Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.hxx

Because `NumberOfWeights` is a static constexpr data member of
`BSplineInterpolationWeightFunction`, it should not be printed by its
`PrintSelf` override. As was remarked by Jon Haitz Legarreta Gorroño (@jhlegarreta),
and confirmed by Hans Johnson (@hjmjohnson) and Dženan Zukić (@dzenanz).
Because `BSplineInterpolationWeightFunction::PrintSelf` did not do
anything else anymore than just calling the corresponding `Superclass`
member function, the override is no longer necessary either, and is
removed by this commit.
For the record, `NumberOfWeights` was introduced by:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2709
commit 34f3db8d8ad0ba848cbbfee071edf327e09f6a96
"ENH: Replace GetNumberOfWeights() by static constexpr NumberOfWeights"

BUG: BSplineInterpolationWeightFunction should not print NumberOfWeights

---

Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h
Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.hxx
Modules/Core/Common/test/itkBSplineInterpolationWeightFunctionTest.cxx
Modules/Core/Common/wrapping/itkFunctionBase.wrap
Modules/Core/Transform/include/itkBSplineBaseTransform.h
Modules/Core/Transform/include/itkBSplineBaseTransform.hxx
Modules/Core/Transform/include/itkBSplineDeformableTransform.hxx
Modules/Core/Transform/include/itkBSplineTransform.hxx
Modules/Core/Transform/test/itkBSplineDeformableTransformTest.cxx
Modules/Core/Transform/test/itkBSplineTransformTest.cxx
Modules/Registration/Common/include/itkImageToImageMetric.hxx
Wrapping/WrapITKTypes.cmake

Replaced `itk::Array` by `itk::FixedArray` as output type (array of
weights) of `itk::BSplineInterpolationWeightFunction`.
Observed a significant improvement of the runtime performance of a call to `itk::BSplineBaseTransform::TransformPoint`: the runtime duration appeared ~30% lower than before, from 1.5 sec. down to 1.0 sec. when calling `TransformPoint` 10'000'000 times. (Tested using Visual C++ 2019 Release).

PERF: Use FixedArray for BSplineInterpolationWeightFunction OutputType

---

CMake/ITKExternalData.cmake

- BUG: Remove slicer.kitware.com as a content link server

slicer content link

---

Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h
Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.hxx
Modules/Core/Common/include/itkBSplineKernelFunction.h

Added a static member function `BSplineKernelFunction::FastEvaluate(u)`. Equivalent to the existing `BSplineKernelFunction::Evaluate(u)` member function. Allows writing faster code, because it is non-virtual, and
because it does not require the creation of a `BSplineKernelFunction` object.
Removed the dynamically allocated `m_Kernel` data member from `BSplineInterpolationWeightFunction` and replaced the virtual function call `m_Kernel->Evaluate(x)` by a faster static member function call, to the newly added `BSplineKernelFunction::FastEvaluate` member function.

PERF: `BSplineKernelFunction::FastEvaluate(u)`: a faster way to evaluate BSplineKernelFunction

---

Modules/Core/Transform/include/itkTransformGeometryImageFilter.h
Modules/Core/Transform/include/itkTransformGeometryImageFilter.hxx
Modules/Core/Transform/test/CMakeLists.txt
Modules/Core/Transform/test/itkTransformGeometryImageFilterTest.cxx
Modules/Core/Transform/wrapping/CMakeLists.txt
Modules/Core/Transform/wrapping/itkTransformGeometryImageFilter.wrap

Community discussion and voting converged TransformGeometryImageFilter
is a more accurate name for the operation.
Renamed per the discussion: https://discourse.itk.org/t/simpleitk-euler3d-transform-adjust-image-origin-and-direction/3966/25

ENH: Rename ResampleInPlaceImage to TransformGeometryImageFilter

---

Modules/Core/Common/include/itkBSplineDerivativeKernelFunction.h
Modules/Core/Common/include/itkBSplineKernelFunction.h
Modules/Core/Common/include/itkGaussianKernelFunction.h
Modules/Filtering/ImageGrid/include/itkCoxDeBoorBSplineKernelFunction.hxx
Modules/Filtering/ImageSources/include/itkGaborKernelFunction.h

Replaced `static_cast<TRealValueType>(x)` by `TRealValueType{ x }`,
following C++ Core Guidelines, August 19, 2021, "Don’t use static_cast
for arithmetic types", from
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Pro-type-arithmeticcast
The syntax `TRealValueType{ x }` is more type-safe than
`static_cast<TRealValueType>(x)`, as it prevents against accidental
narrowing (lossy) conversions.
Also replaced `ZeroValue()` and `OneValue()` calls by the corresponding
`TRealValueType{ x }` syntax.

STYLE: Use modern C++ `TRealValueType{ x }` syntax

---

Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h
Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.hxx

Replaced `itk::Array2D` by `itk::FixedArray`, used as private `TableType`
of `BSplineInterpolationWeightFunction`. This is the type of a table,
used internally by its `Evaluate` member function.
Declared this table `const`, and initialized the table by an in-class
default-member-initializer. Defaulted the default-constructor.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2712
commit bc7c5dff2d6a29815bce50cbe7fd8bb5476a4a2b
"PERF: Use FixedArray for BSplineBaseTransform ParameterIndexArrayType"
commit 9bf745bda51044c90208c7b0776e87d7c86adb11
"PERF: Use FixedArray for BSplineInterpolationWeightFunction OutputType"

PERF: Use FixedArray for table within BSplineInterpolationWeightFunction

---

Modules/Core/Common/wrapping/itkBSplineInterpolationWeightFunction.wrap
Modules/Core/Common/wrapping/itkFunctionBase.wrap
Wrapping/WrapITKTypes.cmake

Avoid build errors when we wrap for 4-D images.

BUG: Improve dimension-dependent BSplineInterpolationWeightFunction wrapping

---

Modules/Core/Transform/include/itkTransformGeometryImageFilter.h
Modules/Core/Transform/include/itkTransformGeometryImageFilter.hxx
Modules/Core/Transform/test/itkTransformGeometryImageFilterTest.cxx

Im proves the conformance to expected ITK pipeline behaviors. 
Addresses bug related to:
-  output information being update at the incorrect phase
- composition pipeline execution escaping the GenerateData method
- Not correctly updating region filter indicates it will
Derive class from InPlaceImageFilter, and set the default "RunInPlace" to true.
Made RigidTransform a pipeline object.

Refactor TransformGeometryImageFilter

---

Modules/Core/TestKernel/include/itkTestingMacros.h

GCC is not resolving `object->Superclass` in some cases even though the
definition is available and other compilers are resolving the
definition.
xref https://github.com/InsightSoftwareConsortium/ITK/issues/2676

COMP: Avoid Superclass type alias GCC compile errors

---

Modules/Core/Common/include/itkBSplineDerivativeKernelFunction.h
Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.h
Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.hxx
Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4.h
Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4.hxx
Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4GetValueAndDerivativeThreader.hxx

Added static member function `FastEvaluate(u)` to `BSplineDerivativeKernelFunction`, just like the one added to `BSplineKernelFunction`.
Used the `FastEvaluate(u)`  member functions of both `BSplineKernelFunction` _and_ `BSplineDerivativeKernelFunction` inside the implementation of `MattesMutualInformationImageToImageMetric` and `MattesMutualInformationImageToImageMetricv4`.
Follow-up to pull request #2716 "PERF: `BSplineKernelFunction::FastEvaluate(u)`: a faster way to evaluate BSplineKernelFunction"

FastEvaluate(u) for both BSplineKernelFunction _and_ BSplineDerivativeKernelFunction 

---

Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx

itk::FloatingPointExceptions::Disable()
In this commit, a flag is added to disable all floating-point exceptions, rather than just two exceptions. This bug was identified in the following discussion thread: https://discourse.itk.org/t/itk-not-loading-nrrd-files-any-more/4224/10. This fix will resolve an exception that occurs when loading NRRD images.

BUG: Disable all floating point exceptions 

---

Modules/Core/Transform/include/itkIdentityTransform.h

`m_ZeroJacobian` appeared to be used only as a source object to copy to
a `jacobian` parameter. As an `Array2D`, it was using dynamically
allocated memory.

PERF: Remove unnecessary `IdentityTransform::m_ZeroJacobian`

---

Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h

Copied the constexpr static data member `SupportSize` to a local
variable, to prevent Clang linker errors, like:
> Undefined symbols for architecture x86_64:
> "itk::BSplineInterpolationWeightFunction::SupportSize", referenced from:
> itk::BSplineInterpolationWeightFunction::'lambda'()::operator()() const in itkBSplineInterpolationWeightFunctionTest.cxx.o
From Mac10.13-AppleClang-dbg-x86_64-static https://open.cdash.org/viewBuildError.php?type=0&buildid=7457677, reported by Sean McBride (@seanm).

COMP: Copy BSplineInterpolationWeightFunction::SupportSize within lambda

---

Modules/Core/Transform/include/itkTransform.h

Observed ~29% reduction of `sizeof(itk::Transform<double>)`, from 248
bytes (before this commit) down to 176 bytes, using Visual C++ 2019
64-bit Release.
Follow-up to commit c42fb3f468c1acfd9b8ebd2fb99fe1d07e5b7e6b
"BUG: Remove extra m_DirectionChange from Transform." by Matt McCormick (@thewtex),
13 April 2012

PERF: Remove protected `itk::Transform` data member `m_DirectionChange`

---

CMake/itkExternal_FFTW.cmake

FFTW 3.3.10
Sep 15th, 2021
Fix bug that would cause 2-way SIMD (notably SSE2 in double precision)
to attempt unaligned accesses in certain obscure cases, causing
segfaults.  The following test triggers the bug (SSE2, double
precision): ./tests/bench -oexhaustive r4*2:5:3
This test computes a pair of length-4 real->complex transforms where
the second input is 5 real numbers away from the first input. That is,
there is a gap of one real number between the first and second input
array.  The -oexhaustive level allow FFTW to attempt to compute this
transform by reducing it to a pair of complex transforms of length 2,
but now the second input is not aligned to a complex-number boundary.
The fact that 5 is odd is the problem.
The bug cannot occur in complex->complex transforms because the …

ENH: Update FFTW to 3.3.10

---

Modules/Core/Common/src/itkImageRegionSplitterDirection.cxx
Modules/Core/Common/src/itkImageRegionSplitterSlowDimension.cxx
Modules/Core/Common/test/itkImageRegionSplitterDirectionTest.cxx
Modules/Core/Common/test/itkImageRegionSplitterSlowDimensionTest.cxx
Modules/Filtering/LabelMap/test/itkLabelImageToLabelMapFilterTest.cxx

When the image had a zero size, undefined results of division by zero
occoured. For both the ImageRegionSplitterSlowDimension and the
ImageRegionSplitterDirection classes when a region's size is zero, the
region has one "split" region of a zero sized region.
closes #2741

BUG: Fix ImageRegionSplitters with zero sized image

---

Modules/Filtering/ImageFeature/test/itkLaplacianImageFilterTest.cxx

Fix missing initialization braces warning.
Fixes:
```
/Users/builder/externalModules/Filtering/ImageFeature/test/itkLaplacianImageFilterTest.cxx:62:35:
warning: suggest braces around initialization of subobject [-Wmissing-braces]
itk::Vector<float, 2> spacing({ 0.5, 5.0 });
^~~~~~~~
{       }
[CTest: warning suppressed] 1 warning generated.
```
reported at:
https://open.cdash.org/viewBuildError.php?type=1&buildid=7468732

COMP: Fix missing initialization braces warning

---

Modules/Nonunit/Review/test/itkMultiphaseDenseFiniteDifferenceImageFilterTest.cxx

Provide missing template parameter to superclass.
Fixes:
```
/Modules/Nonunit/Review/test/itkMultiphaseDenseFiniteDifferenceImageFilterTest.cxx:
In instantiation of
'class itk::MultiphaseDenseFiniteDifferenceImageFilterTestHelper<
itk::Image<double, 3>, itk::Image<float, 3>, itk::Image<unsigned char, 3>,
itk::ScalarChanAndVeseLevelSetFunction<
itk::Image<double, 3>, itk::Image<float, 3>,
itk::ConstrainedRegionBasedLevelSetFunctionSharedData<
itk::Image<double, 3>, itk::Image<float, 3>,
itk::ScalarChanAndVeseLevelSetFunctionData<itk::Image<double, 3>, itk::Image<float, 3> > > >,
long unsigned int>':
/Modules/Nonunit/Review/test/itkMultiphaseDenseFiniteDifferenceImageFilterTest.cxx:103:13:
required from here
/Modules/Nonunit/Review/test/itkMultiphaseDenseFiniteDifferenceImageFilterTest.cxx:5 …
```

BUG: Provide missing template parameter to superclass

---

Modules/Nonunit/Review/test/itkMultiphaseSparseFiniteDifferenceImageFilterTest.cxx

COMP: fixed compile errors due to incorrect superclass identification

---

.circleci/config.yml

cimg are the new CircleCI images based on Ubuntu.
This may address:
> Error message was: SSL certificate problem: certificate has expired
on CDash submission.
Due to:
https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

COMP: Update CircleCI image to cimg/python:3.9

---

Modules/Core/Common/include/itkImageSink.h
Modules/Core/Common/include/itkMacro.h
Modules/Filtering/ImageFilterBase/include/itkBinaryGeneratorImageFilter.h
Modules/Filtering/ImageGrid/test/itkResampleImageTest8.cxx

Removed the remaining calls to itkStaticConstMacro and itkGetStaticConstMacro. Most of them were removed already by Hans Johnson (@hjmjohnson): 
Commit 5c14741e1e063a132ea7e7ee69c5bd0a4e49af74 2 February 2018: "STYLE: Replace itkStaticConstMacro with static constexpr", 
Commit d72d28f5a1f405f740fe7f296d0f308793263ab2 4 March 2018: "STYLE: Do not use itkGetStaticConstMacro in ITK"
Declared both macro's `ITK_FUTURE_LEGACY_REMOVE`.

Remove (ITK_FUTURE_LEGACY_REMOVE) itkStaticConstMacro and itkGetStaticConstMacro

---

Modules/Filtering/ImageCompare/test/itkSimilarityIndexImageFilterTest.cxx

Improve `itk::SimilarityIndexImageFilter` class test file style:
- Use the `ITK_TRY_EXPECT_NO_EXCEPTION` macro to avoid boilerplate code
when updating a filter that can trigger exceptions.

STYLE: Improve `itk::SimilarityIndexImageFilter` class test file style

---

Modules/Registration/Common/test/itkCompareHistogramImageToImageMetricTest.cxx

Increase `itk::KullbackLeiblerCompareHistogramImageToImageMetric` coverage:
Take advantage of the commit to improve the style:
- Only enclose within the `ITK_TRY_EXPECT_NO_EXCEPTION` macro the filter
update calls that may throw exceptions.
- Add braces to control flow blocks even if composed with a single
statement to comply with the ITK style.
- Mark the test ending according to the ITK style.

ENH: Improve KLCompareHistogramImageToImageMetric coverage

---

Modules/Filtering/LabelMap/test/itkLabelImageToLabelMapFilterTest.cxx

Make `itkLabelImageToLabelMapFilterTest` style consistent with the
ITK style:
- Remove the test input argument check due to the absence of required
arguments other than the test name.
- Comply with the ITK style in the test ending message.
- Capitalize the first letter for constant-valued names.
- Remove the explicit call to the Print method and rely on the basic

STYLE: Make `itkLabelImageToLabelMapFilterTest` style consistent

---

Modules/Core/Common/include/itkNeighborhood.hxx
Modules/Filtering/Convolution/include/itkConvolutionImageFilterBase.hxx
Modules/Filtering/DisplacementField/include/itkLandmarkDisplacementFieldSource.hxx
Modules/Filtering/FFT/include/itkFFTPadImageFilter.hxx
Modules/Filtering/ImageGrid/include/itkPadImageFilterBase.hxx
Modules/Filtering/ImageStatistics/include/itkImageShapeModelEstimatorBase.hxx
Modules/Numerics/FEM/include/itkFEMObjectSpatialObject.hxx
Modules/Numerics/Statistics/include/itkVectorContainerToListSampleAdaptor.hxx
Modules/Registration/Common/include/itkCompareHistogramImageToImageMetric.hxx
Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFilter.hxx
Modules/Segmentation/Classifiers/include/itkClassifierBase.hxx
Modules/Segmentation/LevelSets/include/itkNarrowBandCurvesLevelSetImageFilter.hxx

Improve the ivar printing in `PrintSelf` methods in miscellaneous classes:
- Use the `itkPrintSelfObjectMacro` macro to avoid boilerplate code when
printing smart pointers/objects that can be null pointers.
- Take advantage of the overload of the ostream operator to print
strongly typed enum class members.
- Print the member variable names verbatim to conform to the ITK SW Guide.

STYLE: Improve the ivar printing in `PrintSelf` methods

---

Modules/Registration/Metricsv4/include/itkANTSNeighborhoodCorrelationImageToImageMetricv4.h
Modules/Registration/Metricsv4/wrapping/itkANTSNeighborhoodCorrelationImageToImageMetricv4.wrap

Adds Python wrapping for `itk::ANTSNeighborhoodCorrelationMetricToMetricv4`.

ENH: Add ANTSNeighborhoodCorrelation metric wrapping

---

Wrapping/Generators/Python/PyBase/pyBase.i
Wrapping/Generators/Python/Tests/extras.py
Wrapping/Generators/Python/itk/support/extras.py
Wrapping/Generators/Python/itk/support/helpers.py

This PR adds pickle support to ITK images. We want this so that ITK images can be serialized for use with Dask arrays.
Closes https://github.com/InsightSoftwareConsortium/ITK/issues/1091
cc @thewtex 

ENH: pickle serialization for itk images (issue 1091)

---

Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h
Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.hxx

Reason: Prior to C++17 one must  provide the definition of the static
constexpr member as well as the declaration. The declaration and the
initializer go inside the class definition, but the member definition
has to be separate.
FAILED: bin/ITKCommon2TestDriver
Undefined symbols for architecture x86_64:
"itk::BSplineInterpolationWeightFunction<float, 2u, 1u>::SupportSize", referenced from:
itk::BSplineInterpolationWeightFunction<float, 2u, 1u>::GetSupportSize() const in itkBSplineInterpolationWeightFunctionTest.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1081/1334] Building CXX object Modules/Registration/RegistrationMethodsv4/test/CMakeFiles/ITKRegistrationMethodsv4TestDriver.dir/itkSimpleImageRegis …

BUG: Fix constexpr linkage issue

---

Modules/Filtering/FFT/include/itkComplexToComplex1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkFFTWComplexToComplex1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkFFTWInverse1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkForward1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkInverse1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkVnlComplexToComplex1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkVnlForward1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkVnlInverse1DFFTImageFilter.h

Fixes issue where some 1D FFT image filters moved from ITKUltrasound still referenced the Ultrasound group in header comments. This causes issues in Python module wrappings as the FFT module tries to load the Ultrasound module at init.

BUG: Fix 1D FFT doxygen groups

---

.gitignore

CMake now provides a mechanism for defining preset confiurations
for selecting and building based on user preferences.
CMakeUserPresets.json should NOT be checked into a version control system.
CMakePresets.json may be tracked in git, but
CMakeUserPresets.json should be added to the .gitignore.

ENH: Allow users to have a CMakeUserPresets.json file

---

Modules/Core/Common/test/itkNumericTraitsTest.cxx

Compiletime evaluated always true if statements were
converted to compile-time static_asserts.
Unused value settings were removed.
Constant values were varied from zero to avoid
the warning caused by using value to select a template
type.

STYLE: Address clang-tidy warnings in file

---

Modules/Core/GPUCommon/include/itkGPUReduction.hxx
Modules/Filtering/FFT/test/itkComplexToComplexFFTImageFilterTest.cxx
Modules/IO/MINC/test/itkMINCImageIOTest_2D.cxx
Modules/IO/NIFTI/test/itkNiftiImageIOTest.h
Modules/IO/TransformMINC/include/itkMINCTransformAdapter.h

Removed code that would produce MSVC warning C4702, "unreachable code"
(if this warning would have been enabled), from Visual Studio 2019.
Explicitly deleted (`= delete`) the function template
`PreFillDirection()`, which also had unreachable code.
Most of these changes were already suggested by Lee Newberg (@Leengit) at
https://github.com/InsightSoftwareConsortium/ITK/pull/2865#issuecomment-966483880
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2865
commit ad64a79f657ecbf59fec980ca37c700222008ebc
"STYLE: Do not do `return;` directly after throwing an exception"

COMP: Remove unreachable code

---

Modules/Core/Common/test/itkTimeProbesTest.cxx
Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectTest2.cxx
Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectTest3.cxx
Modules/Filtering/DisplacementField/test/itkDisplacementFieldTransformTest.cxx
Modules/Filtering/DisplacementField/test/itkInverseDisplacementFieldImageFilterTest.cxx
Modules/Filtering/ImageFeature/test/itkHessianRecursiveGaussianFilterScaleSpaceTest.cxx
Modules/Filtering/ImageGrid/test/itkExpandImageFilterTest.cxx
Modules/Filtering/ImageGrid/test/itkOrientedImageProfileTest1.cxx
Modules/Filtering/ImageGrid/test/itkOrientedImageProfileTest2.cxx
Modules/Filtering/ImageGrid/test/itkOrientedImageProfileTest3.cxx
Modules/Filtering/ImageIntensity/test/itkVectorExpandImageFilterTest.cxx
Modules/Filtering/LabelMap/include/itkShapePositionLabelMapFilter.h
Modules/Registration/Common/test/itkBlockMatchingImageFilterTest.cxx
Modules/Registration/Common/test/itkImageToSpatialObjectRegistrationTest.cxx
Modules/Segmentation/LevelSets/test/itkBinaryMaskToNarrowBandPointSetFilterTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkMultiLevelSetDenseImageSubset2DTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkMultiLevelSetMalcolmImageSubset2DTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkMultiLevelSetShiImageSubset2DTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkMultiLevelSetWhitakerImageSubset2DTest.cxx
Modules/Segmentation/LevelSetsv4/test/itkSingleLevelSetWhitakerImage2DWithCurvatureTest.cxx

Replaced `image->TransformPhysicalPointToIndex(point, index)` calls by
`image->TransformPhysicalPointToIndex(point)`, which is slightly faster,
as it does not figure out whether or not the point is inside the image.
Follow-up to pull request #993
commit 0703516
"STYLE: Use image->TransformPhysicalPointToIndex(point), returning index"

Use the faster `TransformPhysicalPointToIndex` overload

---

Modules/Filtering/FFT/include/itkFFTWCommonExtended.h

Follow up to #2866 removing lingering Ultrasound dependency for 1D FFT.
Unlike the classes addressed in #2866, `itk::ComplexToComplexProxy` is not wrapped for Python so the Doxygen group will only affect documentation and not load dependencies.

DOC: Remove lingering Ultrasound dependency

---

Modules/Core/Common/src/itkProcessObject.cxx
Modules/Core/Common/test/itkDataObjectAndProcessObjectTest.cxx

fetch_add returns the value before the increment, not after.
Closes #2874.

BUG: fix filter progress overflowing due to bad logic in atomic add

---

Modules/ThirdParty/DCMTK/CMakeLists.txt

Hi everyone,
Pull request related to issue #2877 as suggested by @dzenanz. 
CMakeLists for DCMTK ExtProject has been modified as suggested in the issue thread.
Reminder of the issue:
When building the ITKDCMTK_ExtProject with DCMTK_USE_ICU set to OFF, the configuration doesn't overwrite the DCMTK_WITH_ICU (DCMTK-side) variable. On system where ICU libraries are present, this lead to DCMTK finding and setting itself to DCMTK_WITH_ICU=ON, which in turn lead to linking error when trying to build an application.
The CMakeLists.txt for the project doesn't set anything in case the DCMTK_USE_ICU is OFF.
PR add the following to the CMakeLists
```
if(DCMTK_USE_ICU)
[...]
else(DCMTK_USE_ICU)
set(CHARSET_CONVERSION_ARGS
-DDCMTK_WITH_ICU:BOOL=OFF
)
endif()
```

BUG: Add an else clause for DCMTK_USE_ICU variable to overwrite the DCMTK configuration when set to false

---

Modules/Numerics/Statistics/include/itkScalarImageToCooccurrenceMatrixFilter.h
Modules/Numerics/Statistics/include/itkScalarImageToCooccurrenceMatrixFilter.hxx
Modules/Numerics/Statistics/include/itkScalarImageToTextureFeaturesFilter.h
Modules/Numerics/Statistics/include/itkScalarImageToTextureFeaturesFilter.hxx
Modules/Numerics/Statistics/test/itkScalarImageToTextureFeaturesFilterTest.cxx

Currently `ScalarImageToCooccurrenceMatrixFilter` assumes that the mask image would be the same type as the gray value image. This is not ideal because masks do not necessarily have to be of the same type. This limits the usability of the current design. What is more important is that forcing the mask to be of the same type can be problematic when working with floating-point types.
This PR extends `ScalarImageToCooccurrenceMatrixFilter` to add a template parameter for the mask image type, and uses the updated filter in `ScalarImageToTextureFeaturesFilter`.
This is my first contribution to ITK and I do not feel confident to say if the PR is breaking the API. It *does* add a new template parameter (with a default value) in front of an existing template parameter. So people that used both …

ENH: Added template parameter for texture mask type

---

Modules/IO/NIFTI/test/itkNiftiImageIOTest.h

Pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2869 commit af32a779c4586304e52ddc27eb81656b949c9eeb ("COMP: Remove unreachable code") "deleted" the `PreFillDirection()` function template definition, by `= delete`. This appeared to cause compilation errors on the following sites/builds:
Site: RogueResearch7
Build Name: Mac10.11-AppleClang-rel-x86_64-static
Build Name: Mac10.11-AppleClang-dbg-x86_64-static
As reported by Jon Haitz Legarreta Gorroño (@jhlegarreta) at https://github.com/InsightSoftwareConsortium/ITK/pull/2869#issuecomment-970306179
The error messages included:
/Users/builder/externalModules/IO/NIFTI/test/itkNiftiImageIOTest.cxx:26:1: error: redefinition of 'PreFillDirection'
PreFillDirection<1>()
^ …

COMP: No longer delete (`= delete`) PreFillDirection() function template

---

Modules/Registration/Common/include/itkBlockMatchingImageFilter.hxx

Fixes warning seen in `PythonGetNameOfClass` test.
Prevous behavior: `SetPrimaryInputName` calls `AddRequiredInputName` internally after `AddRequiredInputName` was already called for the same input one line previous, leading to warning about duplicate behavior:
```
WARNING: In /Users/runner/work/1/s/Modules/Core/Common/src/itkProcessObject.cxx, line 852
BlockMatchingImageFilter (0x7fc9c38ab070): Input already "FeaturePoints" already required!
```
Updated behavior: Duplicate `AddRequiredInputName` is removed so that `SetPrimaryInputName` alone adds the input.
Warning does not appear to be reported in CDash by default and does not cause the test to fail. Uncovered in [CTest logs](https://open.cdash.org/test/540703555) from in-progress #2864. …

BUG: Remove duplicate required input in BlockMatchingImageFilter

---

Modules/Filtering/LabelMap/include/itkStatisticsLabelMapFilter.hxx

COMP: Fix sign comparison to unsigned warning

---

Modules/Core/Common/src/itkGaussianDerivativeOperator.cxx
Modules/Core/QuadEdgeMesh/src/itkQuadEdgeMeshEulerOperatorFlipEdgeFunction.cxx
Modules/Core/SpatialObjects/src/itkContourSpatialObject.cxx
Modules/Core/TestKernel/src/itkTestingHashImageFilter.cxx
Modules/Filtering/FFT/src/itkComplexToComplexFFTImageFilter.cxx
Modules/Filtering/FastMarching/src/itkFastMarchingBase.cxx
Modules/Filtering/FastMarching/src/itkFastMarchingImageFilter.cxx
Modules/Filtering/FastMarching/src/itkFastMarchingReachedTargetNodesStoppingCriterion.cxx
Modules/Filtering/ImageFeature/src/itkMultiScaleHessianBasedMeasureImageFilter.cxx
Modules/Filtering/QuadEdgeMeshFiltering/src/itkBorderQuadEdgeMeshFilter.cxx
Modules/Filtering/QuadEdgeMeshFiltering/src/itkLaplacianDeformationQuadEdgeMeshFilter.cxx
Modules/Filtering/QuadEdgeMeshFiltering/src/itkNormalQuadEdgeMeshFilter.cxx
Modules/Numerics/Statistics/src/itkExpectationMaximizationMixtureModelEstimator.cxx
Modules/Registration/FEM/src/itkFEMRegistrationFilter.cxx
Modules/Registration/PDEDeformable/src/itkESMDemonsRegistrationFunction.cxx
Modules/Registration/PDEDeformable/test/itkESMDemonsRegistrationFunctionTest.cxx
Modules/Registration/RegistrationMethodsv4/src/itkImageRegistrationMethodv4.cxx
Modules/Segmentation/DeformableMesh/src/itkDeformableSimplexMesh3DGradientConstraintForceFiler.cxx
Modules/Segmentation/MarkovRandomFieldsClassifiers/src/itkMRFImageFilter.cxx
Modules/Segmentation/RegionGrowing/src/itkConnectedThresholdImageFilter.cxx

Removing relative imports from files in Modules including Filtering, Core, IO, Numerics, Registration, Segmentation.
Four more files remaining under ThirdParty/KWIML/src/itkkwiml/test.

ENH: Removing relative header imports from multiple cxx files

---

.github/workflows/clang-format-linter.yml

Use latest `checkout` release in `clang-format linter` workflow.

ENH: Use latest `checkout` release in `clang-format linter` workflow

---

Modules/Core/ImageAdaptors/include/itkImageAdaptor.h
Modules/Core/ImageAdaptors/test/CMakeLists.txt
Modules/Core/ImageAdaptors/test/itkImageAdaptorGTest.cxx

Added the four missing single parameter overloads of point/index/vector
conversion member functions to `ImageAdaptor`, which were already there
for `ImageBase` with ITK version 5.0:
TransformPhysicalPointToIndex
TransformPhysicalPointToContinuousIndex
TransformContinuousIndexToPhysicalPoint
TransformIndexToPhysicalPoint
Included a GoogleTest unit test.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/868
commit 65233e36b64ac7835fe2b80de2a6b981204554f4
"ENH: Convenience overloads for ImageBase Transform member functions" (by me)
And pull request https://github.com/InsightSoftwareConsortium/ITK/pull/1207
commit 55f8ac2b2701a6138c91615c2ca20006cd3e65e8
"BUG: Missing ImageAdapter function signatures" by Hans Johnson (@hjmjohnson)

BUG: Add missing single argument ImageAdaptor Transform member functions

---

Wrapping/Generators/SwigInterface/CMakeLists.txt
Wrapping/Generators/SwigInterface/igenerator.py

Wrapped Python classes and methods, have introspection enabled typehints to allow auto-completion in IDE's.
Logic was added to the igenerator.py file to produce stubs for wrapped ITK classes in Python.
A large number of available ITK classes are currently supported by this feature, with more being worked on.
The itk-stubs directory is created with a __init__.pyi file that provides all the interface stubs to tools that can utilize stub files. The included interface files provide information needed for IDE's like Pycharm. Once built there should be no extra setup needed to get the hinting functionality.  The hints for type selection factories use Template and Proxy names  appended to them to differentiate them from the actual ITK classes. The  interfaces may provide hints for types that are …

ENH: Added interface files for wrapped Python classes and methods.

---

Modules/Core/Mesh/include/itkTriangleMeshCurvatureCalculator.h
Modules/Core/Mesh/test/itkTriangleMeshCurvatureCalculatorTest.cxx

Compilation error when future legacy is enabled.
In file included from ../Modules/Core/Mesh/src/itkTriangleMeshCurvatureCalculator.cxx:18:
../Modules/Core/Mesh/include/itkTriangleMeshCurvatureCalculator.h:110:3: error: use of undeclared identifier purposeful_error
itkGetObjectMacro(GaussCurvatureData, DoubleVectorContainer);
^
../Modules/Core/Common/include/itkMacro.h:1128:7: note: expanded from macro itkGetObjectMacro
purposeful_error("itkGetObjectMacro should be replaced with itkGetModifiableObjectMacro.");

COMP: Use modern macro name for GetModifiableObjectMacro

---

Modules/Core/Common/include/itkTimeStamp.h
Modules/Core/Common/test/itkTimeStampTest.cxx

Allowed the compiler to generate the default-constructor and assignment
operator of `TimeStamp` implicitly, followed C++ Core Guidelines,
August 19, 2021:
"If you can avoid defining default operations, do"
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c20-if-you-can-avoid-defining-default-operations-do
Added compile-time checks of the type traits of the special member
functions of `TimeStamp`.

STYLE: Remove `TimeStamp` default-constructor, assignment (Rule of Zero)

---

Modules/Core/Common/include/itkImageAlgorithm.hxx
Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.h
Modules/Core/ImageFunction/include/itkExtrapolateImageFunction.h
Modules/Core/ImageFunction/include/itkGaussianBlurImageFunction.hxx
Modules/Core/ImageFunction/include/itkImageFunction.h
Modules/Core/ImageFunction/include/itkInterpolateImageFunction.h
Modules/Core/ImageFunction/include/itkVectorInterpolateImageFunction.h
Modules/Core/Mesh/include/itkTriangleMeshToBinaryImageFilter.hxx
Modules/Core/Transform/include/itkBSplineBaseTransform.hxx
Modules/Core/Transform/include/itkBSplineDeformableTransform.hxx
Modules/Core/Transform/include/itkBSplineTransform.hxx
Modules/Filtering/DisplacementField/include/itkDisplacementFieldToBSplineImageFilter.hxx
Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.hxx
Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx
Modules/Numerics/Optimizersv4/include/itkRegistrationParameterScalesFromIndexShift.hxx
Modules/Registration/Common/include/itkImageToImageMetric.hxx
Modules/Registration/Common/include/itkKappaStatisticImageToImageMetric.hxx
Modules/Registration/Common/include/itkMeanReciprocalSquareDifferencePointSetToImageMetric.hxx
Modules/Registration/Common/include/itkMeanSquaresPointSetToImageMetric.hxx
Modules/Registration/Common/include/itkNormalizedCorrelationImageToImageMetric.hxx
Modules/Registration/Common/include/itkNormalizedCorrelationPointSetToImageMetric.hxx

Replaced `image->TransformPhysicalPointToContinuousIndex(point, index)`
calls by `image->TransformPhysicalPointToContinuousIndex<T>(point)`,
which is slightly faster, as it does not figure out whether or not the
point is inside the image.
Declared variables that are initialized by
`image->TransformPhysicalPointToContinuousIndex<T>(point)` `const`, when
possible.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2873
commit eb6ac88c8209ff6cfb3f280bb25e8388f236e211
"PERF: Use the faster TransformPhysicalPointToIndex overload in filter"

PERF: Use the faster `TransformPhysicalPointToContinuousIndex` overload

---

Modules/Registration/RegistrationMethodsv4/wrapping/itkImageRegistrationMethodv4.wrap

Python wrapping for ImageRegistrationMethodv4 with Mesh is needed for ThinShellDemons based Mesh Registration.
Transform and Mesh are wrapped only with Double to reduce combinations.

ENH: Adding Python Wrapping for itkImageRegistrationMethodv4 with Mesh

---

Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.h
Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.hxx

Moved the `threadId` specific member function definitions of `BSplineInterpolateImageFunction` into its class template definition.
Used `unique_ptr` for threaded `BSplineInterpolateImageFunction` data

Move `BSplineInterpolateImageFunction` member function definitions into class, use `unique_ptr`

---

Testing/ContinuousIntegration/AzurePipelinesLinux.yml

It has happened several times that ITK fails to build
on one of the dashboard machines which has ITK_LEGACY_REMOVE=ON.
This could be avoided if we had a CI build without legacy.

ENH: add a new ContinuousIntegration build: LinuxLegacyRemoved

---

Modules/Registration/Common/wrapping/itkGradientDifferenceImageToImageMetric.wrap

Add wrapping for `itk::GradientDifferenceImageToImageMetric`.

ENH: Add wrapping for `itk::GradientDifferenceImageToImageMetric`

---

CMake/ITKModuleExternal.cmake
CMakeLists.txt
Wrapping/Generators/SwigInterface/CMakeLists.txt
Wrapping/Generators/SwigInterface/igenerator.py

Resolved a few small bugs causing `make` builds to fail when python wrapping is enabled. 
The following was changed:
1. The itk-stubs directory is generated via cmake during build configuration before igenerator.py is ran.
2. The .pyi output files in the igenerator custom command were corrected. 
3. The typehint generation code was reformatted to prevent duplicate definitions from being saved to several files. 
This should fix #2908.

BUG: Resolve ITK `make` build error with Python Wrappings. 

---

Modules/Core/Transform/include/itkMatrixOffsetTransformBase.h
Modules/Core/Transform/include/itkMatrixOffsetTransformBase.hxx
Modules/Core/Transform/test/itkAffineTransformTest.cxx

itk::MatrixOffsetTransformBase::ComputeInverseJacobianWithRespectToPosition was returning directly m_Matrix, the same as the (non-inverse) ComputeJacobianWithRespectToPosition. This has been corrected to return the inverse matrix.
This correction has required also the correction of a few function return and parameters' Types. 
Those corrected Types were inconsistent when instantiated with input and output of different dimensions.
In addition, the generation of the inverse transformation required declaring the same template class, but with the input and output dimensions interchanged, as friend class.
Apparently the bug was inadvertently introduced in 
Change-Id: Ib4d253de1a592693ed253a3e7e95ddbe21df76c4 (PERF: Improve MatrixOffset Jacobian computation performance)
and subsequently not …

BUG: Wrong inverse matrix in MatrixOffsetTransformBase::ComputeInverseJacobianWithRespectToPosition

---

Modules/Core/Common/include/itkBresenhamLine.h
Modules/Core/Common/include/itkBresenhamLine.hxx
Modules/Core/Common/test/itkBresenhamLineTest.cxx

While this PR changes the signature, it should only grow the size of the `length` parameter.
Closes #2926.

BUG: BresenhamLine was producing more indices than necessary

---

Modules/Registration/Common/wrapping/itkPointSetToPointSetMetric.wrap
Modules/Registration/Common/wrapping/itkPointSetToPointSetRegistrationMethod.wrap

PointSetToPointSetMetric and PointSetToPointSetRegistrationMethod Python wrapping added as requested in [ITK Discourse](https://discourse.itk.org/t/bspline-free-form-deformable-registration/4586/56?u=dzenanz).

ENH: Wrap PointSet To PointSet Metric and RegistrationMethod

---

Modules/Core/Common/test/itkImageBaseGTest.cxx

Increase `itk::ImageBase` coverage: test exceptions.

ENH: Increase `itk::ImageBase` coverage

---

Wrapping/Generators/Python/itk/__init__.py

Modules __init__ files are now renamed to avoir conflicts upon installation (see [ITKPythonPackage#183](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/183)). Make sure the renamed files are loaded and executed in ITK's __init__ file.

ENH: Load and execute modules __init__ file

---

Modules/Numerics/FEM/src/dsrc2c.c
Modules/Numerics/FEM/src/itkFEMElement3DC0LinearHexahedron.cxx

Fix `abs` method not being found:
- Include `itkMath.h` to have `abs` available.
- Use the standard library `abs` where ITK objects are not used.
Fixes:
```
\Modules\Numerics\FEM\src\itkFEMElement3DC0LinearHexahedron.cxx(223):
error C2039:
'Math': is not a member of 'itk' [M:\Dashboard\ITK-build\Modules\Numerics\FEM\src\ITKFEM.vcxproj]
```
https://open.cdash.org/viewBuildError.php?buildid=7619926
Introduced in 716822e.

COMP: Fix `abs` method not being found

---

Modules/Filtering/MathematicalMorphology/include/itkSharedMorphologyUtilities.hxx

The implicit conversion for computing the P2 variable
using unsigned integers occurs if directly converting
to floating-point values.  This caused underflow
computation errors.
Explicitly convert values to consistently use
floating-point computations to avoid many implicit
type conversions between signed and unsigned values.

COMP: Remove implicit conversions

---

Modules/Core/Mesh/test/itkTriangleMeshCurvatureCalculatorTest.cxx

Minor modification in the itkTriangleMeshCurvatureCalculatorTest to avoid memory leak.
GetCell is called before SetCell to avoid memory leak while inserting Tetrahedron Cell.
Refer to [SetCell](https://itk.org/Doxygen/html/classitk_1_1Mesh.html) documentation. 

COMP: GetCell before SetCell to avoid memory leak

---

.clang-tidy
CMake/ITKClangTidySetup.cmake
CMakeLists.txt

Recent versions of cmake allow running clang-tidy as
part of the compilation process.
A <LANG>_CLANG_TIDY target property and supporting
CMAKE_<LANG>_CLANG_TIDY variable were introduced to tell the Makefile
Generators and the Ninja generator to run clang-tidy along with the
compiler for C and CXX languages.  Supported in cmake 3.6+.

STYLE: Allow use of clang-tidy as part of cmake compilation

---

Examples/DataRepresentation/Mesh/MeshCellVisitor.cxx
Examples/DataRepresentation/Mesh/MeshCellVisitor2.cxx
Modules/Core/Common/include/VNLIterativeSparseSolverTraits.h
Modules/Core/Common/include/VNLSparseLUSolverTraits.h
Modules/Core/ImageFunction/test/makeRandomImageBsplineInterpolator.h
Modules/Filtering/ImageGrid/include/itkOrientImageFilter.hxx
Modules/IO/NIFTI/test/BigEndian_hdr.h
Modules/IO/NIFTI/test/BigEndian_img.h
Modules/IO/NIFTI/test/LittleEndian_hdr.h
Modules/IO/NIFTI/test/LittleEndian_img.h
Modules/Nonunit/IntegratedTest/test/itkShrinkImagePreserveObjectPhysicalLocations.cxx
Modules/Video/BridgeVXL/include/vidl_itk_istream.hxx
Wrapping/Generators/Explicit/Explicit.cxx.in
Wrapping/Generators/SwigInterface/igenerator.py

From Programming in C++, Rules and Recommendations : The use of two
underscores (`__') in identifiers is reserved for the compiler's
internal use according to the ANSI-C standard.

STYLE: Do not use double underscore defines

---

Modules/ThirdParty/VNL/src/vxl/CMakeLists.txt
Modules/ThirdParty/VNL/src/vxl/core/vnl/algo/vnl_levenberg_marquardt.cxx

New assertions for recently added caused test_levenberg_marquardt
test to fail when run in debug mode.  Fixed assertions to allow test to pass.

Fix vxl debug test failure

---

Examples/DataRepresentation/Mesh/MeshCellVisitor.cxx
Examples/DataRepresentation/Mesh/MeshCellVisitor2.cxx

The class name and the #define symbol must have
different values to avoid preprocessing
the name to an invalid value.

COMP: Duplicate symbol name with #define

---

Modules/Core/Mesh/wrapping/test/CMakeLists.txt
Modules/Core/Mesh/wrapping/test/itkMeshArrayPixelTypeTest.py

Added test in Python to demonstrate the usage of Array PixelType in Mesh.
Usage of Array allows to change the size of pixeldata as per requirements later.
Using Array, however breaks the API support for SetElement and SetPointData in PointSet.
The only way to alter the data is through reference and for that CreateElementAt method is
used in the VectorContainer.

ENH: Adding Test for Array PixelType in Mesh Wrapping

---

Modules/Filtering/Smoothing/wrapping/test/MedianImageFilterTest.py

Make code imported from Python 3.8+ features an
optional testcase.
Resolves: #2963.

BUG: Conditional python 3.8 code optional

---

Modules/Core/Mesh/wrapping/test/itkMeshArrayPixelTypeTest.py

Fix for Python test in Windows platform.
itk.ULL is used in windows while itk.UL is used in Ubuntu and MacOS. Refer: [WrapBasicTypes.cmake](https://github.com/InsightSoftwareConsortium/ITK/blob/047fa6934ac32711d1d7b84fa6eb81c72db01960/Wrapping/WrapBasicTypes.cmake#L190)
In another test, a message is printed if the required wrapping is un-available, Refer: [itkPyVectorContainerTest](https://github.com/InsightSoftwareConsortium/ITK/blob/895fc718e814527aa156f7ff63ca8d5e15761d26/Modules/Bridge/NumPy/wrapping/test/itkPyVectorContainerTest.py#L44)
This is a follow-up to #2953 and #2957.

COMP: Use itk.ULL in Windows Platform

---

Modules/Core/Mesh/wrapping/itkMeshBase.wrap

Adding Python wrapping for VectorContainer of CellInterface for Array Pixel Type in Mesh.
Required as warnings are seen during compilation stage in Windows Platform and CI was failing due to it. 
Refer: PR [2953](https://github.com/InsightSoftwareConsortium/ITK/pull/2953)
Have to check why warning was not raised for linux.
@jhlegarreta @dzenanz 

ENH: Adding Python wrapping for CellInterface VectorContainer

---

Modules/IO/GDCM/src/itkGDCMImageIO.cxx

It is safer to reset internal variables on _InternalReadImageInformation_,
because a user can re-use the IO.
Example of such re-using from this [post](https://discourse.itk.org/t/encountering-undefined-behavior-when-writing-dicom-images/4587?u=mihail.isakov)
```
ImageIOType::Pointer dcmIOsingleFiles = ImageIOType::New();
// Read files one by one
// Read all headers of all DICOM files in fileNames
for (std::string filename : fileNames) {
dcmIOsingleFiles->SetFileName(filename);
dcmIOsingleFiles->ReadImageInformation();
```

BUG: GDCM IO: reset internal variables

---

Modules/IO/JPEG/src/itkJPEGImageIO.cxx

Commits are intentionally not squashed.
Follow-up of https://github.com/InsightSoftwareConsortium/ITK/pull/2933

BUG: updated JPEG IO

---

Modules/Core/Transform/include/itkTransform.h
Modules/Core/Transform/include/itkTransform.hxx
Modules/Core/Transform/test/CMakeLists.txt
Modules/Core/Transform/test/itkTransformGTest.cxx

Defaulted (`= default`) the `Transform` default-constructor, ensuring
that it will make both its `Parameters` and its `FixedParameters` empty.
Allowed calling this default-constructor from a derived transform class
without getting a `itkWarningMacro`.

ENH: Make Parameters empty, do not warn in Transform default-constructor

---

Modules/Filtering/DisplacementField/include/itkTimeVaryingVelocityFieldIntegrationImageFilter.h
Modules/Filtering/DisplacementField/include/itkTimeVaryingVelocityFieldIntegrationImageFilter.hxx
Modules/Filtering/DisplacementField/test/itkTimeVaryingVelocityFieldIntegrationImageFilterTest.cxx

The aimed normalization of the time apparently messed up the Runge-Kutta 
implementation resulting in a wrong algorithm. The implementation has been corrected to remove this bug. 
The existing test (itkTimeVaryingVelocityFieldIntegrationImageFilterTest) only tested for the integration of a homogeneous and constant velocity field, where the error could not be detected.
I have extended the test adding the case of a non-trivial (inhomogeneous and time-variaying) velocity field. This test is not passed by the previous implementation.
Added boolean flag to control the interpretation of LowerTimeBound and UpperTimeBound as rates 
in the velocity field time span. If true, it is equivalent to consider that the velocity field is defined in the normalized time interval [0, 1], ignoring the input …

BUG: Runge-Kutta wrong TimeBounds implementation

---

Modules/Core/Common/include/itkBuildInformation.h

Fix `itk::BuildInformation` class documentation typo.

DOC: Fix `itk::BuildInformation` class documentation typo

---

Modules/Filtering/DisplacementField/include/itkInvertDisplacementFieldImageFilter.h
Modules/Filtering/DisplacementField/test/itkInvertDisplacementFieldImageFilterTest.cxx

Add run-time type information to `itk::InvertDisplacementFieldImageFilter`.
Exercise the basic object methods using the

ENH: Add RTTI to `itk::InvertDisplacementFieldImageFilter`

---

Modules/Segmentation/Watersheds/include/itkWatershedBoundary.h
Modules/Segmentation/Watersheds/include/itkWatershedBoundaryResolver.h
Modules/Segmentation/Watersheds/include/itkWatershedEquivalenceRelabeler.h
Modules/Segmentation/Watersheds/include/itkWatershedRelabeler.h
Modules/Segmentation/Watersheds/include/itkWatershedSegmentTable.h
Modules/Segmentation/Watersheds/include/itkWatershedSegmentTree.h
Modules/Segmentation/Watersheds/include/itkWatershedSegmentTreeGenerator.h
Modules/Segmentation/Watersheds/include/itkWatershedSegmenter.h

Fix `Watersheds` module classes class names in `itkTypeMacro`.

BUG: Fix class names in `itkTypeMacro`

---

Modules/Segmentation/Watersheds/include/itkWatershedBoundary.h
Modules/Segmentation/Watersheds/include/itkWatershedBoundaryResolver.h
Modules/Segmentation/Watersheds/include/itkWatershedEquivalenceRelabeler.h
Modules/Segmentation/Watersheds/include/itkWatershedSegmentTree.h
Modules/Segmentation/Watersheds/include/itkWatershedSegmentTreeGenerator.h

Use the `ITK_DISALLOW_COPY_AND_MOVE` macro in the `Watersheds` module to
enhance consistency across the toolkit when disallowing the copy
constructor and the assign operator.
Move the `ITK_DISALLOW_COPY_AND_MOVE` calls to public section following
the discussion in
https://discourse.itk.org/t/noncopyable
Following the changes:
https://github.com/InsightSoftwareConsortium/ITK/commit/b0f183b04fd78062afafea26636b4dc597651b88
https://github.com/InsightSoftwareConsortium/ITK/commit/10429ae6b86c8d1f1578fe32c25180425f14a95d
https://github.com/InsightSoftwareConsortium/ITK/commit/7d177ca0c77aedb38cc8cf5561b785317617c315

COMP: Use and move ITK_DISALLOW_COPY_AND_MOVE calls to public section

---

Modules/Filtering/ImageStatistics/include/itkLabelStatisticsImageFilter.h
Modules/Filtering/ImageStatistics/include/itkMinimumMaximumImageFilter.h
Modules/Filtering/ImageStatistics/include/itkStatisticsImageFilter.h
Modules/Filtering/ImageStatistics/test/itkLabelOverlapMeasuresImageFilterTest.cxx
Modules/Filtering/ImageStatistics/test/itkLabelStatisticsImageFilterTest.cxx
Modules/Filtering/ImageStatistics/test/itkMinimumMaximumImageFilterTest.cxx
Modules/Filtering/ImageStatistics/test/itkStatisticsImageFilterTest.cxx

- ENH: Increase coverage for `ImageStatistics` module classes 
- BUG: Fix superclass name in `itkTypeMacro`

ENH: Increase coverage for `ImageStatistics` module classes

---

Modules/Filtering/DisplacementField/include/itkTimeVaryingVelocityFieldIntegrationImageFilter.hxx
Modules/Video/IO/include/itkVideoFileReader.hxx

Use `itkPrintSelfObjectMacro` to print objects that can be null.

ENH: Use `itkPrintSelfObjectMacro` to print objects that can be null

---

Modules/Core/Common/test/itkCMakeConfigurationTest.cxx
Modules/Core/ImageFunction/test/itkCentralDifferenceImageFunctionOnVectorSpeedTest.cxx
Modules/Core/ImageFunction/test/itkCentralDifferenceImageFunctionSpeedTest.cxx
Modules/Filtering/ImageFeature/test/itkMaskFeaturePointSelectionFilterTest.cxx
Modules/Filtering/ImageFeature/test/itkUnsharpMaskImageFilterTest.cxx
Modules/Filtering/ImageGradient/test/itkGradientRecursiveGaussianFilterSpeedTest.cxx
Modules/Filtering/ImageGrid/test/itkMirrorPadImageFilterTest.cxx
Modules/Filtering/QuadEdgeMeshFiltering/test/itkDiscreteGaussianCurvatureQuadEdgeMeshFilterTest.cxx
Modules/Filtering/QuadEdgeMeshFiltering/test/itkDiscreteMaximumCurvatureQuadEdgeMeshFilterTest.cxx
Modules/Filtering/QuadEdgeMeshFiltering/test/itkDiscreteMeanCurvatureQuadEdgeMeshFilterTest.cxx
Modules/Filtering/QuadEdgeMeshFiltering/test/itkDiscreteMinimumCurvatureQuadEdgeMeshFilterTest.cxx
Modules/IO/DCMTK/test/itkDCMTKMultiFrame4DTest.cxx
Modules/IO/ImageBase/test/itkImageFileReaderDimensionsTest.cxx
Modules/IO/MeshVTK/test/itkMeshFileWriteReadTensorTest.cxx
Modules/IO/Meta/test/itkMetaImageIOMetaDataTest.cxx
Modules/Registration/Common/test/itkBlockMatchingImageFilterTest.cxx
Modules/Video/IO/test/itkFileListVideoIOFactoryTest.cxx

Use the `itkNameOfTestExecutableMacro` macro to get the test name
instead of hard-coding the test name.

STYLE: Use the `itkNameOfTestExecutableMacro` macro in tests

---

Modules/Core/Transform/include/itkIdentityTransform.h
Modules/Filtering/ImageGrid/test/itkResampleImageTest8.cxx
Modules/IO/TransformMINC/include/itkMINCTransformAdapter.h

Adjusted the default-constructor of `IdentityTransform`,
`MINCTransformAdapter`, and `ProjectTransform` to use the
default-constructor of `Transform`, instead of its
`Transform(NumberOfParametersType)` constructor, as in each of these
cases, both `Parameters` and `FixedParameters` should just be empty.
Follow-up to:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2983
commit 20249ece000a22347dd363df4cdeb6fccdedaae4
"ENH: Make Parameters empty, do not warn in Transform default-constructor"

STYLE: Use `Transform` default-constructor instead of `Transform(0)`

---

Modules/IO/SpatialObjects/include/itkSpatialObjectWriter.h
Modules/IO/SpatialObjects/test/itkReadWriteSpatialObjectTest.cxx

Add boolean macros to `itk::SpatialObjectWriter` boolean ivars.
Exercise the boolean macros and the boolean ivar Set/Get methods.
Take advantage of the commit to simplify and improve the style and
readability around such testing: use the `ITK_TRY_EXPECT_NO_EXCEPTION`
macro to avoid boilerplate code when updating a filter that can trigger
exceptions, and take out the rest of the statements of the `try/catch`
block.

ENH: Add boolean macros to `itk::SpatialObjectWriter` boolean ivars

---

Modules/IO/JPEG/include/itkJPEGImageIO.h
Modules/IO/JPEG/test/itkJPEGImageIOCMYKTest.cxx
Modules/IO/JPEG/test/itkJPEGImageIODegenerateCasesTest.cxx
Modules/IO/JPEG/test/itkJPEGImageIOTest.cxx

- STYLE: Improve the `JPEG` module tests' style
- ENH: Add boolean macros for `itk::JPEGImageIO` boolean ivars
- ENH: Exercise basic object methods for `itk::JPEGImageIO`

ENH: Improve `JPEG` module tests

---

Modules/Core/TestKernel/include/itkTestingMacros.h

Addresses #3008 by weakening `ITK_EXERCISE_BASIC_OBJECT_METHODS` so that `object->GetNameOfClass()` no longer needs to match the user-defined string value for testing. `object->Self::GetNameOfClass()` is queried instead. This allows the check to succeed for subclasses which have been upcast to the expected class, which is a necessary function of object factory instantiation.

ENH: Query class name rather than subclass in test macro

---

Modules/Core/Common/include/itkSingleton.h
Modules/Core/Common/src/itkSingleton.cxx
Modules/Core/Common/src/itkStreamingProcessObject.cxx
Modules/Filtering/FFT/include/itkInverse1DFFTImageFilter.h
Modules/Numerics/Optimizers/src/itkSPSAOptimizer.cxx

Did check all itk*.cxx, itk*.h, and itk*.hxx source files.
Follow-up to:
"STYLE: removing void if used in place of empty parameter list"
by Dženan Zukić (@dzenanz), 11 September 2018
https://github.com/InsightSoftwareConsortium/ITK/commit/60807f4abcfd7c4d42ddf93796d6acf272aa442b
"STYLE: Remove redundant void argument lists"
by Hans Johnson (@hjmjohnson), 20 February 2020
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/1628
https://github.com/InsightSoftwareConsortium/ITK/commit/e6d859ecae955a4e2a44b9e60677093dc254a4ca

STYLE: Remove remaining `void` from empty function parameter lists

---

Modules/Bridge/NumPy/wrapping/PyBuffer.i.init
Modules/Bridge/NumPy/wrapping/test/itkPyBufferTest.py

This is to address an image loading issue from the MONAI tutorial:
https://github.com/Project-MONAI/tutorials/issues/494
In addition to the potential `ImportError`, `from distributed.protocol import
dask_serialize, dask_deserialize` may raise a RuntimeError due to the
system availability. This commit tries to catch the exception. The test
case is also updated accordingly.
relevant logs:
<details>
```
/home/jenkins/agent/workspace/Monai-notebooks/MONAI/monai/data/image_reader.py in _get_array_data(self, img)
327         """
--> 328         np_img = itk.array_view_from_image(img, keep_axes=False)
329         if img.GetNumberOfComponentsPerPixel() == 1:  # handling spatial images
/opt/conda/lib/python3.8/site-packages/itk/support/extras.py in GetArrayViewFromImage(image_or_filter, keep_axes, …
```

ENH: Ignore RuntimeErrors when import `from distributed.protocol`

---

Modules/Core/Common/include/itkBuildInformation.h
Modules/Core/Common/src/itkBuildInformation.cxx.in
Modules/Core/Common/test/itkBuildInformationGTest.cxx

Added a check that for each entry from the map retrieved by `GetMap()`,
both `GetValue(key)` and `GetDescription(key)` return the expected
string.

Fix BuildInformation GetValue, GetDescription `key` parameter type, extend its test

---

Modules/IO/TIFF/src/itkTIFFImageIO.cxx

Add warning for the suboptimal case described in #2959.

BUG: warning in TIFFImageIO with component bit depth reduction

---

Modules/Core/Transform/test/itkRigid3DPerspectiveTransformTest.cxx
Modules/Filtering/FastMarching/test/itkFastMarchingTest.cxx

Fix call to basic object method exercise macro and array initialization
compilation errors.
Fixes:
```
/Users/builder/external/ITK-AppleClang-dbg-Universal/Modules/ThirdPartysrc/vxl/vcl/vcl_compiler.h:2:9:
warning: macro name is a reserved identifier [-Wreserved-id-macro]
^
/Users/builder/externalModules/Core/Transform/test/itkRigid3DPerspectiveTransformTest.cxx:62:46:
error: use of undeclared identifier 'Rigid3DPerspectiveTransform'
EXERCISE_BASIC_OBJECT_METHODS(transform, Rigid3DPerspectiveTransform, Transform);
^
/Users/builder/externalModules/Core/Transform/test/itkRigid3DPerspectiveTransformTest.cxx:62:75:
error: use of undeclared identifier 'Transform'
EXERCISE_BASIC_OBJECT_METHODS(transform, Rigid3DPerspectiveTransform, Transform);
^
[CTest: warning …
```

COMP: Fix testing macro call and array initialization errors

---

Modules/Filtering/Smoothing/include/itkSmoothingRecursiveGaussianImageFilter.h

The missing comment of `SetNumberOfWorkUnits` function made Doxygen match a wired comment for it.
See: https://itk.org/Doxygen/html/classitk_1_1SmoothingRecursiveGaussianImageFilter.html#a09bfdb8fa9278129bcf017a20554a1c7
And it seems like that this problem also occurs with other classes with uncommented `SetNumberOfWorkUnits` function.

DOC: Add comment for `SetNumberOfWorkUnits` to correct documentation.

---

CMakeLists.txt

Configure MSVC_STATIC_RUNTIME only if using MSVC environment

STYLE: Disable MSVC settings for non-MSVC

---

Modules/Core/Common/include/itkImageSink.hxx
Modules/Filtering/Convolution/include/itkMaskedFFTNormalizedCorrelationImageFilter.hxx
Modules/Filtering/DisplacementField/include/itkInverseDisplacementFieldImageFilter.hxx
Modules/Video/Core/include/itkVideoToVideoFilter.hxx
Modules/Video/Filtering/include/itkFrameAverageVideoFilter.hxx
Modules/Video/Filtering/include/itkFrameDifferenceVideoFilter.hxx

Follow-up to:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3021
commit ac3156140b29e64467f87725f9a0bb0a12602d15
"STYLE: Declare local `ImageRegion` variables `const`"

STYLE: Clean-up default-constructed local `inputRegion` variables

---

Documentation/Doxygen/DoxygenFooter.html
Documentation/Doxygen/DoxygenHeader.html
Utilities/Doxygen/CMakeLists.txt
Utilities/Doxygen/build_text.js.in
Utilities/Doxygen/datetime.py
Utilities/Doxygen/doxygen.config.in

Three things are done in the PR:
- Use SVG file format for class graphs
- Use mathjax javascript to render math latex on the client side
- Replace static datetime stamp in footer with value dynamically set via javascript
The following changes reduce the HTML from 2.7GB to 884MB a 67%  reduction in size. Additionally, without the daily file modifications of the time stamps few files are modified each night, improving client side cache and enabling committing to gh-pages with little daily churn.
Sample GH repo hosting Doxygen:
https://github.com/blowekamp/ITKDoxygen
https://blowekamp.github.io/ITKDoxygen/
SimpleITK has been using these Doxygen changes on GH pages:
https://simpleitk.org/doxygen/latest/html/index.html
Additionally, the ITKDoxygen repo provides a Dockerfile to reproduce the …

Doxygen Generation Improvements

---

Modules/ThirdParty/OpenJPEG/itk-module.cmake

ITKGDCM build doesn't depend on and doesn't automatically enable _ThirdParty/OpenJPEG_ module.

STYLE: OpenJPEG: removed outdated comment

---

Modules/Core/Common/include/itkBresenhamLine.hxx
Modules/Core/Common/include/itkConstNeighborhoodIterator.hxx
Modules/Core/Common/include/itkConstNeighborhoodIteratorWithOnlyIndex.hxx
Modules/Core/Common/include/itkConstantBoundaryCondition.hxx
Modules/Core/ImageFunction/include/itkLinearInterpolateImageFunction.h
Modules/Core/SpatialObjects/include/itkMetaImageConverter.hxx
Modules/Core/TestKernel/include/itkRandomImageSource.hxx
Modules/Filtering/Convolution/include/itkMaskedFFTNormalizedCorrelationImageFilter.hxx
Modules/Filtering/FastMarching/include/itkFastMarchingImageFilter.hxx
Modules/Filtering/ImageGrid/include/itkRegionOfInterestImageFilter.hxx
Modules/Filtering/ImageGrid/include/itkSliceImageFilter.hxx
Modules/Filtering/ImageGrid/include/itkTileImageFilter.hxx
Modules/Filtering/Path/include/itkExtractOrthogonalSwath2DImageFilter.hxx
Modules/Filtering/Path/include/itkPathToImageFilter.hxx
Modules/IO/ImageBase/include/itkImageFileReader.hxx
Modules/IO/ImageBase/include/itkImageSeriesReader.hxx
Modules/Numerics/Statistics/include/itkImageToNeighborhoodSampleAdaptor.hxx
Modules/Registration/Common/include/itkImageRegistrationMethodImageSource.h
Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.hxx
Modules/Registration/Metricsv4/include/itkJointHistogramMutualInformationImageToImageMetricv4.hxx
Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4GetValueAndDerivativeThreader.hxx
Modules/Segmentation/Classifiers/include/itkImageClassifierBase.hxx
Modules/Segmentation/ConnectedComponents/include/itkHardConnectedComponentImageFilter.hxx
Modules/Segmentation/KLMRegionGrowing/include/itkKLMRegionGrowImageFilter.hxx
Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkMRFImageFilter.hxx
Modules/Segmentation/Voronoi/include/itkVoronoiSegmentationRGBImageFilter.hxx
Modules/Video/IO/include/itkVideoFileReader.hxx

Replaced lines of code which look like the following:
IndexType index;
index.Fill(0);
With:
constexpr IndexType index = { { 0 } };
In accordance with C++ Core Guidelines, January 3, 2022:
"By default, make objects immutable"
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rconst-immutable
"Declare an object `const` or `constexpr` unless you want to modify its
value later on"
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-const

STYLE: Declare local zero-filled `Index` variables `constexpr`

---

Modules/Core/Common/include/itkConstNeighborhoodIterator.hxx
Modules/Core/Common/include/itkConstNeighborhoodIteratorWithOnlyIndex.hxx
Modules/Core/Common/include/itkConstantBoundaryCondition.hxx
Modules/Core/SpatialObjects/include/itkMetaImageConverter.hxx
Modules/Core/TestKernel/include/itkRandomImageSource.hxx
Modules/Filtering/Convolution/include/itkMaskedFFTNormalizedCorrelationImageFilter.hxx
Modules/Filtering/FastMarching/include/itkFastMarchingImageFilter.hxx
Modules/Filtering/ImageGrid/include/itkRegionOfInterestImageFilter.hxx
Modules/Filtering/ImageGrid/include/itkSliceImageFilter.hxx
Modules/Filtering/ImageGrid/include/itkTileImageFilter.hxx
Modules/Filtering/Path/include/itkExtractOrthogonalSwath2DImageFilter.hxx
Modules/Filtering/Path/include/itkPathToImageFilter.hxx
Modules/IO/ImageBase/include/itkImageFileReader.hxx
Modules/IO/ImageBase/include/itkImageSeriesReader.hxx
Modules/Numerics/Statistics/include/itkImageToNeighborhoodSampleAdaptor.hxx
Modules/Registration/Common/include/itkImageRegistrationMethodImageSource.h
Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.hxx
Modules/Registration/Metricsv4/include/itkJointHistogramMutualInformationImageToImageMetricv4.hxx
Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4GetValueAndDerivativeThreader.hxx
Modules/Segmentation/Classifiers/include/itkImageClassifierBase.hxx
Modules/Segmentation/ConnectedComponents/include/itkHardConnectedComponentImageFilter.hxx
Modules/Segmentation/KLMRegionGrowing/include/itkKLMRegionGrowImageFilter.hxx
Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkMRFImageFilter.hxx
Modules/Segmentation/Voronoi/include/itkVoronoiSegmentationRGBImageFilter.hxx
Modules/Video/IO/include/itkVideoFileReader.hxx

Made use of the fact that the default-constructor of `ImageRegion`
already properly zero-initializes its index and size. Preferred using
the `ImageRegion(const SizeType &)` constructor, rather than
`ImageRegion(const IndexType &, const SizeType &)`, when its index must
be zero-filled.
Follow-up to:
Pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3036
commit c46354736b0723ae4a7c66b03b6203c643754659
"STYLE: Declare local zero-filled `Index` variables `constexpr`"
Addresses a suggestion from Hans Johnson (@hjmjohnson) by passing `{ {0} }` directly
as index or size to `ImageRegion`.

STYLE: Code clean-up initializing local `ImageRegion` variables

---

Modules/Core/Common/include/itkProgressAccumulator.h
Modules/Core/Common/include/itkSimpleFilterWatcher.h
Modules/Core/Common/src/itkPoolMultiThreader.cxx
Modules/Core/Common/src/itkProgressAccumulator.cxx
Modules/Core/Common/src/itkProgressReporter.cxx
Modules/Filtering/ImageFilterBase/include/itkBinaryGeneratorImageFilter.h
Modules/Filtering/ImageGradient/include/itkGradientMagnitudeRecursiveGaussianImageFilter.hxx
Modules/Filtering/ImageGradient/test/itkGradientMagnitudeRecursiveGaussianFilterTest.cxx
Modules/Filtering/LabelMap/include/itkAttributeUniqueLabelMapFilter.hxx
Modules/Filtering/LabelMap/include/itkLabelImageToLabelMapFilter.hxx
Modules/Filtering/LabelMap/include/itkLabelMapFilter.hxx

Progress reporting improvements

---

Modules/Remote/MeshToPolyData.remote.cmake

This module converts an ITK Mesh to a simple data structure compatible with vtkPolyData.

ENH: Add MeshToPolyData remote module

---

Modules/Core/Common/include/itkConstNeighborhoodIterator.h
Modules/Core/Common/include/itkConstNeighborhoodIterator.hxx
Modules/Core/Common/include/itkConstNeighborhoodIteratorWithOnlyIndex.h
Modules/Core/Common/include/itkConstNeighborhoodIteratorWithOnlyIndex.hxx

Added in-class default member initializers to data members of
`ConstNeighborhoodIterator` and `ConstNeighborhoodIteratorWithOnlyIndex`.
Removed the apparently redundant `ResetBoundaryCondition()` call from
the default-constructor of `ConstNeighborhoodIterator`.
Defaulted (`= default`) the default-constructor of
`ConstNeighborhoodIteratorWithOnlyIndex`.
In accordance with C++ Core Guidelines, January 3, 2022: "Prefer
in-class initializers to member initializers in constructors for
constant initializers"
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-in-class-initializer
Related Clang-Tidy check:
https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-default-member-init.html

STYLE: ConstNeighborhoodIterator in-class default member initializers

---

Modules/Core/Common/include/itkHexahedronCell.hxx

This resolves the following uninitialized compiler warning for the HexahedronCell:
```
/localscratch/Users/kjweimer/ITK/Modules/Core/Common/include/itkHexahedronCell.hxx:385:34: warning: ‘derivs[16]’ is used uninitialized in this function [-Wuninitialized]
385 |         tcol[j] += pt[j] * derivs[i + 2 * Self::NumberOfPoints];
|                                  ^ 
```

COMP: Initialized derivs array to zero.

---

Modules/Numerics/Optimizersv4/src/itkLBFGSBOptimizerv4.cxx

Do not print non-self member variables in `PrintSelf`.
Fixes
```
CurrentPosition: ITK test driver caught an ITK exception:
itk::ExceptionObject (0x55be11155e70)
Location: "unknown"
File: /home/vsts/work/1/s/Modules/Numerics/Optimizersv4/src/itkObjectToObjectOptimizerBase.cxx
Line: 201
Description: ITK ERROR: LBFGSBOptimizerv4(0x55be11150c00): m_Metric has not been assigned. Cannot get parameters.
```
raised in:
https://open.cdash.org/test/583682381

BUG: Do not print non-self member variables in `PrintSelf`

---

Modules/Numerics/Optimizersv4/include/itkObjectToObjectMetricBase.hxx

Rely on strongly typed enum class ostream operator overload for member
variable value printing purposes.

STYLE: Use strongly typed enum class ostream overload in `PrintSelf`

---

Modules/Filtering/DisplacementField/include/itkDisplacementFieldToBSplineImageFilter.h
Modules/Filtering/DisplacementField/test/itkDisplacementFieldToBSplineImageFilterTest.cxx

Add run-time type information to
`itk::DisplacementFieldToBSplineImageFilter`.
Exercise the basic object methods using the

ENH: Add RTTI to `itk::DisplacementFieldToBSplineImageFilter`

---

Modules/Core/Common/include/itkOctree.h
Modules/Core/Common/test/itkOctreeTest.cxx
Modules/Core/ImageFunction/include/itkNearestNeighborExtrapolateImageFunction.h
Modules/Core/ImageFunction/test/itkNearestNeighborExtrapolateImageFunctionTest.cxx
Modules/Filtering/BinaryMathematicalMorphology/include/itkFastIncrementalBinaryDilateImageFilter.h
Modules/Filtering/BinaryMathematicalMorphology/test/itkBinaryDilateImageFilterTest2.cxx
Modules/Filtering/ImageFusion/include/itkLabelMapContourOverlayImageFilter.h
Modules/Filtering/ImageFusion/test/itkLabelMapContourOverlayImageFilterTest1.cxx
Modules/Numerics/Optimizersv4/include/itkGradientDescentOptimizerv4.h
Modules/Numerics/Optimizersv4/include/itkLBFGSBOptimizerv4.h
Modules/Numerics/Optimizersv4/include/itkLBFGSOptimizerv4.h
Modules/Numerics/Optimizersv4/include/itkPowellOptimizerv4.h
Modules/Numerics/Optimizersv4/test/itkGradientDescentOptimizerv4Test.cxx
Modules/Numerics/Optimizersv4/test/itkLBFGSBOptimizerv4Test.cxx
Modules/Numerics/Optimizersv4/test/itkLBFGSOptimizerv4Test.cxx
Modules/Numerics/Optimizersv4/test/itkPowellOptimizerv4Test.cxx
Modules/Registration/Common/include/itkCenteredVersorTransformInitializer.h
Modules/Registration/Common/include/itkNormalizedCorrelationImageToImageMetric.h
Modules/Registration/Common/test/itkCenteredVersorTransformInitializerTest.cxx
Modules/Registration/Common/test/itkNormalizedCorrelationImageMetricTest.cxx
Modules/Segmentation/ConnectedComponents/include/itkRelabelComponentImageFilter.h
Modules/Segmentation/ConnectedComponents/test/itkRelabelComponentImageFilterTest.cxx

- BUG: Fix superclass name in `itkTypeMacro` 
- BUG: Use the superclass name in `itkTypeMacro`

BUG: Fix superclass name in `itkTypeMacro`

---

Modules/Core/Mesh/include/itkConnectedRegionsMeshFilter.hxx
Modules/Core/Mesh/itk-module.cmake
Modules/Core/Mesh/test/CMakeLists.txt
Modules/Core/Mesh/test/itkConnectedRegionsMeshFilterTest1.cxx
Modules/Core/Mesh/test/itkConnectedRegionsMeshFilterTest2.cxx
Modules/Core/Mesh/wrapping/test/CMakeLists.txt
Modules/Core/Mesh/wrapping/test/itkConnectedRegionsMeshFilterTest.py

Fix for correct number of cells in the output mesh. A counter while inserting cell
is used. Earlier the same cell id as in original mesh is used and due to that while counting total number of cells it was
giving wrong result.
Also added a test in Python for testing number of connected components and count of cells in the
largest connected component. Serves the purpose of demonstrating the usage of ConnectedRegionsMeshFilter as well.

BUG: Fix for incorrect number of cells in ConnectedRegionsMeshFilter output

---

Modules/Core/Common/include/itkProcessObject.h
Modules/Core/Common/src/itkProgressReporter.cxx
Modules/Core/Common/src/itkTotalProgressReporter.cxx

This is a follow-up to #3014. Closes #2875.

Better progress reporting

---

Modules/Core/Common/src/CMakeLists.txt

While cmake respects SOURCE_DATE_EPOCH, the timezone may still change
the embedded timestamp used.
https://reproducible-builds.org/docs/source-date-epoch/
Closes #3072. Forwarded by @tillea.

ENH: Use UTC timestamp in CONFIGURE_DATE.

---

Modules/Filtering/FFT/include/itkFFTImageFilterFactory.h

Instead of manually listing the FFT filter dimensions to regisiter,
use a recursive function templated over an integer. This in the future
can easily enable the maximum FFT dimension to be registered as some
type of configuration parameter.

STYLE: Use recursive FFT registration for N to 1

---

Modules/Numerics/Optimizersv4/include/itkMultiGradientOptimizerv4.h
Modules/Numerics/Optimizersv4/test/itkMultiGradientOptimizerv4Test.cxx

Use the superclass name instead of the `Superclass` alias in
`itkTypeMacro`.

STYLE: Use the superclass name in itkTypeMacro

---

Modules/Core/Common/include/itkLogger.h
Modules/IO/TransformBase/include/itkTransformFileReader.h

Fix superclass name in `itkTypeMacro`.
Fixes:
```
Name of Class = Logger
Name of Superclass = LoggerBase
Class name is correct
Superclass name provided does not match object's Superclass::NameOfClass
```
and
```
Name of Class = TransformFileReaderTemplate
Name of Superclass = Object
Class name is correct
Superclass name provided does not match object's Superclass::NameOfClass
```
https://dev.azure.com/itkrobotwindow/ITK.Windows/_build/results?buildId=7533&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=77aad734-2057-5694-9ae2-ee1f5f26eae8&l=45617
and
https://dev.azure.com/itkrobotwindow/ITK.Windows/_build/results?buildId=7533&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=77aad734-2057-5694-9ae2-ee1f5f26eae8&l=120728

BUG: Fix superclass name in itkTypeMacro

---

Modules/Core/ImageFunction/include/itkBSplineDecompositionImageFilter.h
Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.h
Modules/Nonunit/Review/include/itkComplexBSplineInterpolateImageFunction.h

Fix spline order return type in getter macro: use `unsigned int` to
match the type of the member variable.
Fixes:
```
/home/vsts/work/1/s/Modules/Core/ImageFunction/test/itkBSplineInterpolateImageFunctionTest.cxx:34:0:
/home/vsts/work/1/s/Modules/Core/ImageFunction/test/itkBSplineInterpolateImageFunctionTest.cxx:
In function 'int test2DSpline()':
/home/vsts/work/1/s/Modules/Core/TestKernel/include/itkTestingMacros.h:220:44:
warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
CLANG_SUPPRESS_Wfloat_equal if (variable != command) CLANG_PRAGMA_POP \
/home/vsts/work/1/s/Modules/Core/ImageFunction/test/itkBSplineInterpolateImageFunctionTest.cxx:341:5:
note: in expansion of macro 'ITK_TEST_SET_GET_VALUE'
ITK_TEST_SET_GET_VALUE(splineOrder, …
```

COMP: Fix spline order return type in getter macro

---

Modules/ThirdParty/HDF5/src/itkhdf5/src/itk_hdf5_mangle.h

So these 3 functions exist or not depending on preprocessing:
- the first two are wrapped in #ifndef NDEBUG
- the last one in #if H5C_DO_TAGGING_SANITY_CHECKS
I guess to be fully correct, when generating the mangling, we need to do it for release and debug, on different OSes, and with different build options, and merge the results.

COMP: Added mangling for 3 HDF5 functions that were missed

---

Modules/Filtering/Thresholding/include/itkThresholdLabelerImageFilter.hxx

Guarantee array contains enough elements for access in loop.
Specifically, the array must contain at least two elements so that the
sorting can take place.

BUG: Guarantee array contains enough elements for access in loop

---

Modules/Core/Common/include/itkObjectFactoryBase.h
Modules/Core/Common/src/itkObjectFactoryBase.cxx
Modules/Filtering/Convolution/wrapping/test/CMakeLists.txt
Modules/Filtering/Convolution/wrapping/test/FFTConvolutionImageFilterTest.py
Modules/Filtering/FFT/src/itkFFTWFFTImageFilterFactories.cxx
Modules/Filtering/FFT/src/itkVnlFFTImageFilterFactories.cxx
Modules/Filtering/FFT/wrapping/test/CMakeLists.txt
Modules/Filtering/FFT/wrapping/test/FFTObjectFactoryTest.py
Wrapping/Generators/Python/CMakeLists.txt
Wrapping/Generators/Python/itkPyITKCommonCAPI.h

Addresses #2909 to make the object factory behave as a singleton across Python modules.
The ITK object factory is used to provide alternate class implementations at runtime, such as adding support for new image/mesh/transform formats in `ImageRead()` and `ImageWrite()` or (more recently) swapping out backends for accelerated FFT computations. In theory "the object factory" should be treated as a global singleton within ITK, allowing any module or library to define class overrides that are then picked up at program execution by any other filter or class within ITK. In implementation "object factories" are defined and registered to a common `ObjectFactoryBase` object, which can then be accessed with `ObjectFactory<T>::Create()` to yield a subclass instance upcast to type `T`.
ITK Python …

BUG: Synchronize the object factory across Python modules

---

Modules/Filtering/FFT/include/itkComplexToComplex1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkForward1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkInverse1DFFTImageFilter.h

These are no longer required since we use the factory mechanism.

STYLE: Remove old FFT 1D implementation includes

---

Modules/Core/TestKernel/include/itkTestingMacros.h
Modules/Filtering/FFT/test/itkComplexToComplex1DFFTImageFilterTest.cxx
Modules/Filtering/FFT/test/itkComplexToComplexFFTImageFilterTest.cxx
Modules/Filtering/FFT/test/itkVnlComplexToComplexFFTImageFilterTest.cxx

Follow-up to #3010 removing support to check base class names via `ITK_EXERCISE_BASIC_OBJECT_METHODS` when compiled with GCC. This follows from discussion in #2676 where GCC cannot resolve `object->Self` or `object->Superclass` while other compilers have no such issue.
Also uncomments checks in FFT tests relying on this change.

BUG: Fix testing macro for unix platforms and uncomment FFT checks

---

Modules/Core/Common/include/itkMacro.h
Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkObjectFactoryOnlyNewTest.cxx
Modules/Filtering/FFT/include/itkComplexToComplex1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkComplexToComplex1DFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkComplexToComplexFFTImageFilter.h
Modules/Filtering/FFT/include/itkComplexToComplexFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkForward1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkForward1DFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkForwardFFTImageFilter.h
Modules/Filtering/FFT/include/itkForwardFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkHalfHermitianToRealInverseFFTImageFilter.h
Modules/Filtering/FFT/include/itkHalfHermitianToRealInverseFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkInverse1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkInverse1DFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkInverseFFTImageFilter.h
Modules/Filtering/FFT/include/itkInverseFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkRealToHalfHermitianForwardFFTImageFilter.h
Modules/Filtering/FFT/include/itkRealToHalfHermitianForwardFFTImageFilter.hxx

Adds `itkFactoryOnlyNewMacro` as an alternative to `itkNewMacro` and `itkFactorylessNewMacro` for defining the `New()` method for constructing object smart pointers.
The ITK object factory can be used for overriding class constructors and implicitly returning specialized constructs. [`itkNewMacro(Self)`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkMacro.h#L310) is commonly used to define a `New()` method for instantiating objects by first checking for factory methods and then relying on simple instantiation with the `new` keyword if (when) no factory is found. This is suitable for most classes which define their own concrete implementation; however, FFT filters specifically are structured such that the base class does not fully define a …

ENH: Add `itkFactoryOnlyNewMacro` to selectively catch factory instantiation failures

---

Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5ArrayType.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5AtomType.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5Attribute.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5CompType.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5DaccProp.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5DataSet.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5DataSpace.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5DataType.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5DcreatProp.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5DxferProp.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5EnumType.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5FaccProp.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5FcreatProp.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5File.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5FloatType.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5IntType.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5LaccProp.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5LcreatProp.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5OcreatProp.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5PredType.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5PropList.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5StrType.h
Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5VarLenType.h

This fixes numerous warnings about missing override keywords.
These are all already fixed in upstream HDF5 but were not fixed by our recent update to HDF5 1.12.1 because the fixes post-date that release (which is the current release).

COMP: add C++11 override to various HDF5 methods that indeed override

---

Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt

Triggered using clang with std>=17
The warning is correct, in Eigen/x/arch/SSE the functions are used.
However in other archs the functions might be unused.
This patch hacks CMake to ignore it while waiting for resolution upstream.
Reported here: https://gitlab.com/libeigen/eigen/-/issues/2416
Another option to explore suggested by @seanm:
If we assume that ITK would only use the SSE arch we could remove the unused attribute.

COMP: Disable Eigen3 warning Wused-but-marked-unused

---

CMake/ITKFactoryRegistration.cmake
CMake/ITKModuleMacros.cmake
CMake/UseITK.cmake

Addresses the following build error:
CMake Error at CMake/UseITK.cmake:43 (itk_generate_factory_registration):
Unknown CMake command "itk_generate_factory_registration".
This error occurs with the following configuration:
cmake -DBUILD_EXAMPLES=ON -DModule_Montage:BOOL=ON ~/src/ITK

Fixes ITK factory registration CMake

---

Wrapping/Generators/Python/PyBase/pyBase.i
Wrapping/Generators/Python/Tests/extras.py

The itk.Image shape should be consistent for Fortran-order np.ndarray views.
Check the .base attr recursively and its .f_contiguous flag status.
This only applies to GetImageViewFromArray -- GetImageFromArray creates
a copy that is C-order.

BUG: Provide consistent shape on Fortran-order np.ndarray views

---

Modules/Filtering/ImageCompare/test/itkTestingComparisonImageFilterTest.cxx
Modules/Registration/Metricsv4/test/itkMattesMutualInformationImageToImageMetricv4Test.cxx

Fix expected variable type and syntax errors in `ITK_TEST_SET_GET_VALUE`
calls.
Fixes:
```
/Users/builder/externalModules/Filtering/ImageCompare/test/itkTestingComparisonImageFilterTest.cxx:71:21: error:
called object type 'const char [55]' is not a function or function pointer
TEST_SET_GET_VALUE(differenceThreshold, filter->GetDifferenceThreshold());
~~~~~~~~~~~~~~~~~~^
/Users/builder/externalModules/Filtering/ImageCompare/test/itkTestingComparisonImageFilterTest.cxx:75:21:
error: called object type 'const char [55]' is not a function or function pointer
TEST_SET_GET_VALUE(toleranceRadius, filter->GetToleranceRadius());
~~~~~~~~~~~~~~~~~~^
2 errors generated.
```
and
```
/Users/builder/externalModules/Registration/Common/test/itkMattesMutualInformationImageToImageMetricTest.cxx:223:84: …
```

COMP: Fix variable type and syntax errors

---

Modules/Core/Mesh/include/itkConnectedRegionsMeshFilter.hxx

The `count` variable was set but unused when the itkDebugMacro does nothing.  So wrapped the whole thing based on NDEBUG.

COMP: fixed -Wset-but-unused warning building in Release

---

Modules/Registration/Common/include/itkCompareHistogramImageToImageMetric.h
Modules/Registration/Common/test/itkCompareHistogramImageToImageMetricTest.cxx

Add getter macro to `itk::CompareHistogramImageToImageMetric` class
ivar.

ENH: Add getter macro to ivar

---

Modules/Numerics/Optimizers/include/itkExhaustiveOptimizer.h
Modules/Registration/Common/test/itkMultiResolutionImageRegistrationMethodTest.cxx

- BUG: Initialize `itk::ExhaustiveOptimizer` ivars 
- BUG: Initialize `itk::Array` variable values in test

BUG: Initialize variables

---

Modules/Core/ImageFunction/test/itkRayCastInterpolateImageFunctionTest.cxx
Modules/Numerics/Statistics/test/itkImageToHistogramFilterTest.cxx
Modules/Segmentation/LabelVoting/test/itkMultiLabelSTAPLEImageFilterTest.cxx

Increase coverage for miscellaneous classes:
- Use other testing macros to check the expected value of a number of
ivars and method return values.
- Test exceptions using the `ITK_TRY_EXPECT_EXCEPTION` macro.
- Remove explicit calls to the `Print` method and rely on the basic

ENH: Increase coverage for miscellaneous classes

---

Wrapping/Generators/CastXML/CMakeLists.txt

Addresses GCC 11.2.0 build errors.

COMP: Update CastXML x86_64 binaries for LLVM 13.0.0

---

Modules/Core/Common/include/itkNeighborhood.h
Modules/Core/Common/include/itkNeighborhood.hxx

Added in-class default member initializers, in accordance with C++ Core
Guidelines, January 3, 2022: "Prefer in-class initializers to member
initializers in constructors for constant initializers"
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-in-class-initializer
Defaulted its default constructor, copy-constructor, and copy-assignment
operator.
No longer optimized self-assignment (`neighborhoodX = neighborhoodX`).
Note that this commit still supports self-assignment correctly. It just
does not have optimized code anymore for this very specific use case. In
accordance with C++ Core Guidelines, January 3, 2022: "Make copy
assignment safe for self-assignment"
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c62-make-copy-assignment-safe-for-self-assignment

STYLE: Default (`= default`) special member functions of `Neighborhood`

---

Modules/Core/Common/include/itkImageScanlineConstIterator.h
Modules/Core/Common/include/itkImageScanlineConstIterator.hxx

`ImageScanlineConstIterator::Increment()` was only called once, by
`ImageScanlineConstIterator::NextLine()`.

STYLE: Remove private `ImageScanlineConstIterator` member `Increment()`

---

Modules/Numerics/Optimizers/include/itkExhaustiveOptimizer.h

Provide an initial value to the
`itk::ExhaustiveOptimizer::m_MinimumMetricValue` ivar.
Fixes:
```
UMC ==18288== Conditional jump or move depends on uninitialised value(s)
==18288==    at 0x663E1F8:
__printf_fp_l (printf_fp.c:387)
==18288==    by 0x6659639:
__vfprintf_internal (vfprintf-internal.c:1687)
==18288==    by 0x666E119:
__vsnprintf_internal (vsnprintf.c:114)
==18288==    by 0x64D4C3F:
??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==18288==    by 0x6506245:
std::ostreambuf_iterator > std::num_put > >::
_M_insert_float(std::ostreambuf_iterator >, std::ios_base&, char, char, double) const
(in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==18288==    by 0x6514972:
std::ostream& std::ostream::_M_insert(double) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28)
==18288== …
```

BUG: Initialize `itk::ExhaustiveOptimizer::m_MinimumMetricValue`

---

Modules/Core/Common/include/itkOutputWindow.h
Modules/Core/Common/src/itkOutputWindow.cxx

TSan otherwise complained when multiple threads use OutputWindow::DisplayText at the same time, such as in the itkSLICImageFilterTest3 test. This I don't really understand though, since C++11 cerr usage is supposed to be thread safe. But even if strictly thread-safe, output can get interleaved, and a mutex solves both that and the TSan complaint.

BUG: Protect itk::OutputWindow cerr usage with a mutex

---

Modules/Core/Common/include/itkImageRegion.h

Combining conditions into a single statement may allow the compiler to optimize better.  More concise and easier to read.  Updated the comment in the code to report the (past and updated) behavior that the region is inclusive on all sides.

PERF: Combine conditions in ImageRegion::IsInside(index).

---

Modules/ThirdParty/NIFTI/src/nifti/CMakeLists.txt

The command adds overhead and it is not the right repository when
bundled. Also, in distribution outside Git, there is no repository.

BUG: Do not use git call-outs to obtain Nifti version

---

Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/src/Core/util/DisableStupidWarnings.h

Cherry-picking commit by @seanm improving warnings supressions. Closes #3132

COMP: Update eigen3.4 fix warning supressions

---

Modules/Core/Common/include/itkCellInterface.h
Modules/Core/Common/include/itkImageBufferRange.h
Modules/Core/Common/include/itkIndexRange.h
Modules/Core/Common/test/ClientTestLibraryA.cxx
Modules/Core/Common/test/ClientTestLibraryB.cxx
Modules/Core/Common/test/ClientTestLibraryC.cxx
Modules/Filtering/MathematicalMorphology/test/itkFlatStructuringElementTest2.cxx
Modules/Registration/Common/include/itkLandmarkBasedTransformInitializer.h

This pull request changes the 23 instances of `constexpr static` to be like the 2322 instances of `static constexpr`.
```bash
cd ITK
fgrep -Rl 'constexpr static' *
| egrep '\.(c|h|cc)(xx|pp|)$'
| fgrep -v ThirdParty
| xargs sed -i -r \
-e 's/([^A-Za-z0-9_])constexpr static([^A-Za-z0-9_])/\1static constexpr\2/g'
```

STYLE: Change `constexpr static` to `static constexpr`.

---

Modules/Core/Common/include/itkImageRegion.h
Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkImageRegionGTest.cxx

As documented by commit a872710c63ab223e78f45de8d3e4bc435172867d "STYLE: Documenting the behavior of the IsInside() method when the argument region has zero size in any of its dimensions", by Luis Ibanez (@luisibanez), 18 December 2009:
> Test if a region (the argument) is completely inside of this region. If the region that is passed as argument to this method, has a size of value zero, then it will not be considered to be inside of the current region, even its starting index is inside.
Included GoogleTest unit tests for both zero-sized and one-sized regions as argument.
---
This pull request competes with pull request #3108 "DOC: Remove mistake from `ImageRegion::IsInside(region)` documentation" I think there is a choice to be made! There is a disagreement between the code and the …

BUG: region.IsInside(zeroSizedRegion) should always return false

---

Wrapping/Generators/Python/itk/support/extras.py

Currently, **itk.vector_container_from_array** does not work in Ubuntu due to the absence of itk.ULL key in 
the list of PyVectorContainer wrapping. It throws the error message
**"No suitable template parameter can be found"**
The correct key would be itk.UL.
Also, the test is not performed in Linux for itkPyVectorContainerTest
where we give the message "Insufficient wrapping to perform itkPyVectorContainerTest" and just skip the test.
Also refer https://github.com/InsightSoftwareConsortium/ITK/pull/2970.
Are there any issues with the approach in this PR that I am not aware of?
Opening for getting comments as we need this support for mesh serialization.

WIP: Linux support for vector_container_from_array

---

CMakeLists.txt
Wrapping/CMakeLists.txt
Wrapping/Generators/Python/itk/__init__.pyi.in
Wrapping/Generators/Python/itk/_proxies.pyi.in
Wrapping/Generators/SwigInterface/CMakeLists.txt
Wrapping/Generators/SwigInterface/igenerator.py

There are a few problems remaining with the Python Stub interface (.pyi) file generation.
1. `__init__.pyi` generation
The function call that generated this file was removed in an earlier commit.
Instead of recreating the old behavior, the `__init__.pyi` file generation was
moved into CMake configuration files. The previous implementation was unreliable
in parallel builds and would often be missing a few imports. The new implementation
should work better in a parallel build environment.
2. Missing imports for dependent .pyi files. 
In the original implementation Python hints were contained in just two files. To resolve parallelization issues the .pyi files were split into many separate files that were generated in parallel and then imported into a main `__init__.pyi` file. Some of these …

WIP: BUG: Fixed __init__.pyi generation and import issues for python stub files.

---

Modules/Filtering/FFT/include/itkFFTImageFilterFactory.h
Modules/Filtering/FFT/include/itkFFTWComplexToComplex1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkFFTWComplexToComplexFFTImageFilter.h
Modules/Filtering/FFT/include/itkFFTWForward1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkFFTWForwardFFTImageFilter.h
Modules/Filtering/FFT/include/itkFFTWHalfHermitianToRealInverseFFTImageFilter.h
Modules/Filtering/FFT/include/itkFFTWInverse1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkFFTWInverseFFTImageFilter.h
Modules/Filtering/FFT/include/itkFFTWRealToHalfHermitianForwardFFTImageFilter.h
Modules/Filtering/FFT/include/itkVnlComplexToComplex1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkVnlComplexToComplexFFTImageFilter.h
Modules/Filtering/FFT/include/itkVnlForward1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkVnlForwardFFTImageFilter.h
Modules/Filtering/FFT/include/itkVnlHalfHermitianToRealInverseFFTImageFilter.h
Modules/Filtering/FFT/include/itkVnlInverse1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkVnlInverseFFTImageFilter.h
Modules/Filtering/FFT/include/itkVnlRealToHalfHermitianForwardFFTImageFilter.h

Moves FFT filter image dimensions into existing trait objects in order
to decouple FFT factory overrides from fixed dimension lists. This will
allow other, external FFT implementations that may not be valid for
higher-dimension overrides to reuse the FFT factory class.
Future changes may replace the explicit dimension lists with CMake
variables to avoid registering unnecessary factories.
Motivation for these changes comes from developing accelerated FFT filter overrides in the [ITKVkFFTBackend](https://github.com/InsightSoftwareConsortium/ITKVkFFTBackend) external module.

ENH: Expose FFT filter dimension traits

---

Modules/Filtering/Smoothing/test/itkFFTDiscreteGaussianImageFilterTest.cxx

Adds test step for streaming `FFTDiscreteGaussianImageFilterEnums` which was previously [not covered](https://open.cdash.org/viewCoverageFile.php?buildid=7717739&fileid=49970264).

COMP: Increase test coverage for `FFTDiscreteGaussianImageFilter`

---

Modules/ThirdParty/DoubleConversion/CMakeLists.txt

ITK requires double-conversion >=3.1.6. This commit adds the minimum
version for the case where `ITK_USE_SYSTEM_DOUBLECONVERSION=ON`

COMP: Add minimum version for double-conversion

---

Modules/Filtering/FFT/include/itkComplexToComplex1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkComplexToComplex1DFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkFFTWCommonExtended.h
Modules/Filtering/FFT/include/itkFFTWComplexToComplex1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkFFTWComplexToComplex1DFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkFFTWForward1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkFFTWForward1DFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkFFTWInverse1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkFFTWInverse1DFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkForward1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkForward1DFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkInverse1DFFTImageFilter.h
Modules/Filtering/FFT/include/itkInverse1DFFTImageFilter.hxx
Modules/Registration/Common/include/itkMatchCardinalityImageToImageMetric.h
Modules/Registration/Common/include/itkMatchCardinalityImageToImageMetric.hxx

STYLE: Prefer default constructors

---

Modules/Remote/AdaptiveDenoising.remote.cmake

The AdaptiveDenoising project had a bug when processing images with small floating point
values (i.e. images with range of 0-1).

BUG: Fix bug for remote AdaptiveDenoising

---

.git-blame-ignore-revs

Follow up to Pull Request #3161, so that `git blame` ignores that pull request.

STYLE: Make `git blame` ignore STYLE commit.

---

Modules/Numerics/Optimizersv4/include/itkQuasiNewtonOptimizerv4.h

vector<bool> is not thread safe due to the possibility of multiple bits being packed together in the same memory location.   Found by TSan.

BUG: fixed threading bug, don't use vector<bool> from multiple threads

---

Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.hxx
Modules/Filtering/DisplacementField/test/itkDisplacementFieldTransformTest.cxx

In the previous version, the limits, spacing, and direction of the displacement field were incorrectly managed. This pull amends all of them, providing the correct behaviour.
The test itkDisplacementFieldTransformTest has been modified to include anisotropic spacing and non-trivial grid direction. The test is not passed by the previous version.

BUG: Limits, spacing, and direction in ComputeJacobianWithRespectToPosition

---

Modules/Core/Common/include/itkArray.h
Modules/Core/Common/include/itkArray.hxx
Modules/Core/Common/include/itkArray2D.h
Modules/Core/Common/include/itkArray2D.hxx
Modules/Core/Common/include/itkMatrix.h
Modules/Core/Common/include/itkOptimizerParameters.h
Modules/Core/Common/include/itkVariableSizeMatrix.h
Modules/Core/Common/include/itkVersor.h
Modules/Core/Common/include/itkVersor.hxx
Modules/Filtering/FastMarching/include/itkFastMarchingImageFilter.h

Removed the "const" from `const Self &` return types of assignment
operators.
In accordance with C++ Core Guidelines, January 3, 2022: "Make copy
assignment non-virtual, take the parameter by const&, and return by
non-const&"
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c60-make-copy-assignment-non-virtual-take-the-parameter-by-const-and-return-by-non-const

STYLE: Let assignment operators return a non-const reference

---

Modules/IO/GDCM/test/itkGDCMImageOrientationPatientTest.cxx

Future codebases will require a semi-colon after
the use of macros for consistent formatting
purposes.

COMP: Missing semi-colon after macro

---

Modules/Numerics/FEM/include/itkImageToRectilinearFEMObjectFilter.h
Modules/Numerics/FEM/include/itkImageToRectilinearFEMObjectFilter.hxx
Modules/Numerics/FEM/include/itkMetaFEMObjectConverter.hxx

Commit 4b43536c8b22bb716a4f0b76a0582a99d6d8911d "STYLE: Change template parameter name prefix N to V" intended to change template parameter names but mistakenly changed a member variable's name.  This commit fixes that.
I don't have permission to push to #3201, so this pull request is intended to replace it.

BUG: FEM module has incorrect public member name

---

Modules/Filtering/ImageGrid/test/itkWarpImageFilterTest.cxx
Modules/Filtering/ImageGrid/test/itkWarpVectorImageFilterTest.cxx

The != operator was ambiguously overloaded with C++20
CMAKE_CXX_STANDARD:STRING=20 build.
Modules/Filtering/ImageGrid/test/itkWarpImageFilterTest.cxx:214:3: error: use of overloaded operator '!=' is ambiguous (with operand types 'itk::FixedArray<double, ImageDimension>' and 'const itk::WarpImageFilter<itk::Image<float, 2>, itk::Image<float, 2>, itk::Image<itk::Vector<float, 2>, 2> >::PointType' (aka 'const Point<double, Self::ImageDimension>'))
ITK_TEST_SET_GET_VALUE(array, warper->GetOutputOrigin());
^                      ~~~~~  ~~~~~~~~~~~~~~~~~~~~~~~~~
Modules/Core/TestKernel/include/itkTestingMacros.h:226:44: note: expanded from macro 'ITK_TEST_SET_GET_VALUE'
CLANG_SUPPRESS_Wfloat_equal if (variable != command) CLANG_PRAGMA_POP \
~~~~~~~~ ^  ~~~~~~~ …

COMP: C++20 ambiguous overloaded operator

---

Modules/Core/Common/include/itkBooleanStdVector.h
Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkBooleanStdVectorGTest.cxx
Modules/Core/FiniteDifference/include/itkDenseFiniteDifferenceImageFilter.h
Modules/Core/FiniteDifference/include/itkFiniteDifferenceImageFilter.h
Modules/Core/FiniteDifference/include/itkFiniteDifferenceImageFilter.hxx
Modules/Core/FiniteDifference/include/itkFiniteDifferenceSparseImageFilter.h
Modules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceImageFilter.h
Modules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceImageFilter.hxx
Modules/Numerics/NarrowBand/include/itkNarrowBandImageFilterBase.h
Modules/Numerics/NarrowBand/include/itkNarrowBandImageFilterBase.hxx
Modules/Numerics/Optimizersv4/include/itkQuasiNewtonOptimizerv4.h
Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.h

Follow-up to pull request #3166 commit 915b8e48d8ff7d9f5b943eb673826ad85bf74a8c "BUG: fixed threading bug, don't use vector<bool> from multiple threads", by Sean McBride (@seanm) (merged on 8 February 2022).

Add a type alias, `BooleanStdVectorType`, for `std::vector<uint8_t>`

---

Modules/Core/Common/include/itkContinuousIndex.h
Modules/Core/Common/include/itkCovariantVector.h
Modules/Core/Common/include/itkFixedArray.h
Modules/Core/Common/include/itkPoint.h
Modules/Core/Common/include/itkRGBAPixel.h
Modules/Core/Common/include/itkRGBPixel.h
Modules/Core/Common/include/itkSymmetricSecondRankTensor.h
Modules/Core/Common/include/itkVector.h

Removed the explicitly-defaulted definitions of the copy-constructor,
copy-assignment operator, move-constructor, move-assignment operator,
and destructor of `itk::FixedArray<TValue, VLength>` and derived classes,
as they might as well be defaulted implicitly.
Following previous commits that apply the "Rule of Zero", including:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2896
commit 83f6cab3c4b8e87374147363bdf7f75f9cf7addf
"STYLE: Remove `TimeStamp` default-constructor, assignment (Rule of Zero)"
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2449
commit 59ebc33c6e835bd8ed52e54e40ee15a7fa24377e
"ENH: Make itk::Matrix trivially copyable, following Rule of Zero"
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/325
commit …

STYLE: Apply C++ "Rule of Zero" to `itk::FixedArray` and derived classes

---

Modules/Core/Common/include/itkColorTable.h
Modules/Core/Common/include/itkColorTable.hxx
Modules/Core/Common/test/itkColorTableTest.cxx

Aims to avoid confusion, as the pixel type in this context is
`RGBPixel<TComponent>`, which is _not_ the template parameter of `ColorTable`.

STYLE: Rename `ColorTable` template parameter `TPixel` to `TComponent`

---

Modules/Core/Common/test/itkColorTableTest.cxx

It appears that `ColorTableTestSpecialConditionChecker<TComponent>()`
mixed up color component and pixel types, when it assigned the result of
two `GetColorComponent` calls to a `pixel` variable. `GetColorComponent`
returns a component value, rather than a pixel value.
This bug was found by declaring the `RGBPixel(const ComponentType &)`
constructor `explicit` (locally, temporarily), to detect accidental
implicit conversions from a component value to an `RGBPixel` value.
Follow-up to:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3221
commit 9cfaf8fbdaba802e3b6406db300581e25ddec9ff
"STYLE: Rename `ColorTable` template parameter `TPixel` to `TComponent`"

BUG: Fix `ColorTableTestSpecialConditionChecker` component/pixel mix-up

---

Modules/Core/SpatialObjects/include/itkContourSpatialObject.hxx

`ContourSpatialObject::Update()` appears to have an assignment to
`newPoint`, in the `case InterpolationMethodEnum::LINEAR_INTERPOLATION`
section, which was meant to assign just a single element `newPoint[d]`.
As was confirmed by Stephen Aylward (@aylward) at issue https://github.com/InsightSoftwareConsortium/ITK/issues/3222,
"`ContourSpatialObject<TDimension>::Update()` LINEAR_INTERPOLATION case
may need some adjustment".
Some more adjustment may still be needed, as `newPoint` now still gets
modified multiply times (rather than just once), before it eventually
gets used.

BUG: Quick-fix ContourSpatialObject::Update(), LINEAR_INTERPOLATION case

---

Modules/Core/SpatialObjects/test/itkEllipseSpatialObjectTest.cxx
Modules/Filtering/ImageFeature/test/itkCannyEdgeDetectionImageFilterTest.cxx
Modules/Filtering/ImageFeature/test/itkCannyEdgeDetectionImageFilterTest2.cxx
Modules/Filtering/ImageGrid/test/itkBSplineControlPointImageFilterTest.cxx
Modules/Filtering/ImageSources/test/itkGaborImageSourceTest.cxx

The C++ copy-initialization syntax `T var = value` suggests that the
value at the right side is implicitly converted to the target type `T`.
When the target type `T` is a `FixedArray<TValue, VLength>`, or one of
its derived types, `T var = elementValue` _fills_ the variable with the
specified `elementValue`, by assigning the `elementValue` to each of its
elements. In this case, the C++ direct-initialization syntax
`T var(elementValue)` appears more appropriate.
Occurrences of `T var = elementValue` were found by locally temporarily
declaring the corresponding constructors `explicit`.

STYLE: Avoid `T var = elementValue` syntax to initialize a filled array

---

Modules/Core/ImageFunction/include/itkRayCastInterpolateImageFunction.hxx
Modules/Filtering/DisplacementField/include/itkTransformToDisplacementFieldFilter.hxx

An subtraction of the form `point1 - point2` yields a `Vector`, not a `Point`. Adjusted both `TransformToDisplacementFieldFilter::NonlinearThreadedGenerateData` and `RayCastInterpolateImageFunction::Evaluate` accordingly.
These two little flaws were found by locally (temporarily) declaring converting constructors of `Point` "explicit".

BUG: Fix code that treated `point1 - point2` as Point rather than Vector

---

Modules/Filtering/ImageGrid/test/itkResampleImageTest5.cxx
Modules/IO/HDF5/test/itkHDF5ImageIOStreamingReadWriteTest.cxx

Replaced cases of implicit conversion from RGB component value to
`RGBPixel` in unit tests by explicit pixel variable declarations,
direct-initializing them by the specified component value.
Aims to make clear that those conversions were really intended.
Especially because such a conversion may easily take place
unintentionally, implicitly, for example as addressed by pull request #3223
commit 490ef8ce90b44a61089a41054180ad203f36b2d4 "BUG: Fix `ColorTableTestSpecialConditionChecker` component/pixel mix-up"

STYLE: Use direct-initialization for component-to-RGBPixel conversion

---

Modules/Core/Common/include/itkPoint.h

Prevented implicit conversion of a value to `Point`. Aims to avoid
possible flaws, like the ones addressed by:
Pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3225
commit 5b71d63a88cc80547e8584eae59e945fbbf51e5d
"BUG: Quick-fix ContourSpatialObject::Update(), LINEAR_INTERPOLATION case"
Pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3228
commit 12a501cddc3f4c4c93190cb2e64bb2b9c1f558c0
"BUG: Fix `SetCenterInObjectSpace` calls in Registration test"
Pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3231
commit e4841aaba2fd67dabda95189bc1a93da4fa146c3
"STYLE: Clarify estimation ray position `RayCastInterpolateImageFunction`"
Deleted `Point(nullptr_t)`, especially to avoid `PointType p = 0`.

ENH: Declare converting `Point(v)` constructors `explicit`

---

Modules/Core/Common/include/itkRGBAPixel.h
Modules/Core/Common/include/itkRGBPixel.h

Prevents implicit conversion of a component value to `RGBPixel` or
`RGBAPixel`. Aims to avoid possible flaws, like the one addressed by:
Pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3223
commit 490ef8ce90b44a61089a41054180ad203f36b2d4
"BUG: Fix `ColorTableTestSpecialConditionChecker` component/pixel mix-up"
Added _deleted_ `RGBPixel(nullptr_t)` and `RGBAPixel(nullptr_t)`
constructors, especially to avoid erroneous user code like
`RGBPixel pixel = 0`.

ENH: Declare RGBPixel, RGBAPixel constructors from component `explicit`

---

Modules/Core/Common/include/itkIntTypes.h

Reduced code redundancy by replacing type alias declarations of the form
`using` _type_ `= std::`_type_ with the equivalent `using`-declarations.

STYLE: Replace type aliases with `using`-declarations, in itkIntTypes.h

---

Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkSpatialOrientationTest.cxx

Test streaming `itk::SpatialOrientation` enum class types.
Spatial orientation enums were refactored and turned into strongly typed
enums in commit 182c018.

ENH: Test streaming `itk::SpatialOrientation` enum class types

---

Modules/Core/ImageFunction/test/itkSumOfSquaresImageFunctionGTest.cxx

- ENH: Increase `itk::SumOfSquaresImageFunction` class coverage
- STYLE: Prefer using `EXPECT_EQ` in GTest value check
- ENH: Check GTest test method return value

ENH: Increase `itk::SumOfSquaresImageFunction` class coverage

---

Documentation/ITK5MigrationGuide.md
Modules/Core/Common/include/itkVector.h
Modules/Core/SpatialObjects/include/itkSpatialObject.h
Modules/Numerics/Statistics/include/itkMahalanobisDistanceMembershipFunction.h
Modules/Registration/Metricsv4/test/itkMeanSquaresImageToImageMetricv4VectorRegistrationTest.cxx

Follow-up to commit a8909625948547989f97385fd0b06c9f331606eb "ENH: Make Vector construction from scalar value explicit" by Brian Helba (@brianhelba), January 26, 2015
Analog to: pull request #3237 commit 8825834406356a66705437b74c843a54a47c57c3 "ENH: Declare converting `Point(v)` constructors `explicit`"

Remove implicit conversion from a single scalar value to `itk::Vector`

---

Wrapping/Generators/CastXML/CMakeLists.txt
Wrapping/Generators/Doc/CMakeLists.txt
Wrapping/Generators/Python/CMakeLists.txt
Wrapping/TypedefMacros.cmake

WRAPPER_MODULE_NAME is no longer available with the recent wrapping
macro refactoring.
Addresses:
```
CMake Error:
Running
'/usr/bin/ninja' '-C' '/work/ITK-cp39-cp39-manylinux2014_x64' '-t' 'recompact'
failed with:
ninja: error: build.ninja:56497: multiple rules generate Wrapping/Typedefs/_doc.i [-w dupbuild=err]
```
that occurs when building the Python packages when ITK_WRAP_DOC is
enabled.

BUG: Provide module name with ITK_WRAP_DOC enabled

---

CONTRIBUTING.md

Remove the period at the end of the subject line in the bullet immediately following the bullet that indicates `Do not end the subject line with a period.`

DOC: Do not end the subject line with a period

---

Modules/Segmentation/LevelSets/include/itkVectorThresholdSegmentationLevelSetImageFilter.h

For VectorThresholdSegmentationLevelSetImageFilter.  Otherwise the VectorType is set to `double` rather than `itk::Vector<double, N>`.
Similar to c679de253e80e2512fa0c072911414c9068f33e3.

COMP: Add #include "itkNumericTraitsVectorPixel.h"

---

CMake/ITKExternalData.cmake
CMake/ITKSetStandardCompilerFlags.cmake
CMakeLists.txt
Modules/Core/TestKernel/src/CMakeLists.txt

- COMP: Add an option to not build the itkTestDriver executable
- COMP: Do not enable ITK_DYNAMIC_LOADING by default with Emscripten, WASI

wasm fixes

---

Modules/Core/Common/test/itkImageBufferRangeGTest.cxx
Modules/Core/Common/test/itkImageRegionRangeGTest.cxx
Modules/Core/Common/test/itkRangeGTestUtilities.h
Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx

Fixed clang warnings from `IteratorIsDefaultConstructible` checks like
`EXPECT_TRUE(defaultConstructedIterator == defaultConstructedIterator)`
saying:
> warning: self-comparison always evaluates to true [-Wtautological-compare]
Fixed by avoiding such checks whenever the iterator is a pointer.
Reported by issue https://github.com/InsightSoftwareConsortium/ITK/issues/3268
"Minor compiler warning.", from Hans Johnson (@hjmjohnson).
Also reduced the amount of duplicate code from the three
`IteratorIsDefaultConstructible` GoogleTest unit tests.

COMP: Fix ImageBufferRange GTest clang `tautological-compare` warnings

---

Modules/Core/Common/include/itkNumericTraitsCovariantVectorPixel.h
Modules/Core/Common/include/itkNumericTraitsDiffusionTensor3DPixel.h
Modules/Core/Common/include/itkNumericTraitsFixedArrayPixel.h
Modules/Core/Common/include/itkNumericTraitsPointPixel.h
Modules/Core/Common/include/itkNumericTraitsRGBAPixel.h
Modules/Core/Common/include/itkNumericTraitsRGBPixel.h
Modules/Core/Common/include/itkNumericTraitsTensorPixel.h
Modules/Core/Common/src/itkNumericTraitsDiffusionTensor3DPixel.cxx
Modules/Core/Common/src/itkNumericTraitsRGBAPixel.cxx
Modules/Core/Common/src/itkNumericTraitsRGBPixel.cxx
Modules/Core/ImageAdaptors/test/itkImageAdaptorGTest.cxx
Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectGTest.cxx
Modules/Core/Transform/include/itkKernelTransform.hxx
Modules/Core/Transform/test/itkRigid3DPerspectiveTransformTest.cxx
Modules/Core/Transform/test/itkSimilarityTransformGTest.cxx
Modules/Filtering/Denoising/include/itkPatchBasedDenoisingImageFilter.hxx
Modules/Filtering/FastMarching/test/itkFastMarchingTest.cxx
Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx
Modules/Filtering/ImageGrid/test/itkResampleImageTest5.cxx
Modules/Filtering/ImageIntensity/include/itkPolylineMaskImageFilter.hxx
Modules/Filtering/ImageSources/include/itkGenerateImageSource.hxx
Modules/Filtering/ImageSources/test/itkPhysicalPointImageSourceTest.cxx
Modules/Registration/RegistrationMethodsv4/test/itkSimpleImageRegistrationTest3.cxx
Modules/Segmentation/ConnectedComponents/test/itkConnectedComponentImageFilterTest.cxx
Modules/Segmentation/ConnectedComponents/test/itkConnectedComponentImageFilterTestRGB.cxx
Modules/Segmentation/ConnectedComponents/test/itkMaskConnectedComponentImageFilterTest.cxx
Modules/Segmentation/ConnectedComponents/test/itkScalarConnectedComponentImageFilterTest.cxx

Follow-up to:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3262
commit 82001f3024cbc879fce5a68b5f69f6bb5d5c9ea7
"STYLE: Use MakeFilled, () or {}, instead of `Vector(const ValueType &)`"

STYLE: Use MakeFilled, () or {}, instead of `Point(const ValueType &)`

---

Modules/Remote/TubeTK.remote.cmake

ITK has updated the API for PDE functions since ITKv5.3rc03.  This pull requests updates ITK to use the version of TubeTK that supports those changes to the PDE functions.   This should allow TubeTK wheels to be built from this version of ITK, when ITKv5.3rc04 is released.
The changes to ITK's PDE API are breaking changes.  As a result, this version of ITK+TubeTK no longer supports building wheels that are compatible with ITKv5.3rc03.

ENH: Update to TubeTK that supports itk::BooleanStdVector in prep for ITKv5.3rc04

---

Modules/IO/NIFTI/src/itkNiftiImageIO.cxx

bug #3241: In f38b1dd I accidentally changed some behaviour. Specifically, the value of pixdim[0] in itk::NiftiImageIO metadata is different before and after the change.
Previous to the change, SetImageIOMetadataFromNIfTI() was populated from the nifti_1_header structure. After the change, it is populated from the nifti_image structure. The latter is created from the former with nifti_convert_nhdr2nim(). Most of the fields used in SetImageIOMetadataFromNIfTI() have 1-to-1 correspondences in these two structures. I expected all 8 elements of the pixdim array were the same in both structures, but in fact no; element 0 is special. nifti_convert_nhdr2nim() unconditionally sets pixdim[0] to 0.0 (by virtue of allocating the structure with calloc).
In my own app, I was using pixdim[0] (retrieved …

ENH: bug #3241: Add qfac and qto_xyz to itkNiftiImageIO metadata

---

Modules/Core/Common/include/itkNumberToString.h
Modules/Core/Common/test/itkNumberToStringGTest.cxx

Specialized `NumberToString<TValue>` for `TValue` = `void`, allowing users to convert a number of any type to string without having to specify the type of the number, passed as parameter.
Inspired by the `std::less<T>` function object, which has a similar `std::less<>` specialization: https://en.cppreference.com/w/cpp/utility/functional/less 
Aims to make `NumberToString` more appealing, especially for users who would rather not explicitly specify the type of every number they need to convert.  Otherwise those users might rather use `std::ostream` (`<<`) or `std::to_string`, which might be a pity, because `NumberToString` offers full precision (lossless) conversion.

ENH: Add `NumberToString<>` specialization, deducing its parameter type

---

Wrapping/Generators/Python/Tests/verifyGetOutputAPIConsistency.py

#3156 introduced a Python mechanism for loading object factory overrides alongside modules at load time. `load_factories` is an implementation detail and may not be suitable to be called directly.
Issue #3261 exhibits an instance of this where a few templates such as `_Num_base` are not loaded correctly into the `itk` namespace when `load_factories` is called by the client program before other modules are loaded. Removing the `load_factories()` call and relying on `force_load()` to instead load in both modules and factories results in successful namespace population.
Resolves #3261.

BUG: Fix `PythonVerifyGetOutputAPIConsistency` test on Windows

---

Wrapping/Generators/Python/CMakeLists.txt
Wrapping/TypedefMacros.cmake

The name of the file generatd by swig has a
"Python" suffix.
% ninja -d explain /home/johnsonhj/Dashboard/src/ITK/cmake-debug-PythonDebugWrapping_cxx14-build/Wrapping/Generators/Python/itk/itkVariableSizeMatrix.py
ninja explain: output build.ninja older than most recent input ../Wrapping/Generators/Python/CMakeLists.txt (1647177499575465604 vs 1647261272321982426)
The filename for the output of the swig command had been
incorrectly specified, thus causing continous rebuilds.

BUG: Fix generated file name pattern

---

Modules/Core/Common/wrapping/test/itkPointSetSerializationTest.py
Modules/Core/Mesh/wrapping/test/itkMeshSerializationTest.py

Use `itk.ULL` for Python windows test. Closes #3310.

BUG: Use itk.ULL type for Python Windows test

---

Modules/Core/Mesh/wrapping/test/CMakeLists.txt
Modules/Core/Mesh/wrapping/test/itkMeshSerializationTest.py
Wrapping/Generators/Python/itk/support/extras.py

Added conditional long type in itk.support.extras._get_itk_pixelid for Windows.
The failing MeshSerialization test is also modified.
Refer https://github.com/InsightSoftwareConsortium/ITK/issues/3310

ENH: Handle itk.ULL in _get_itk_pixelid for Windows

---

Examples/Iterators/ImageRegionIterator.cxx
Examples/Iterators/ImageRegionIteratorWithIndex.cxx
Examples/Iterators/ImageSliceIteratorWithIndex.cxx

Refactors 3 iterator examples to use the itk:ReadImage and itk:WriteImage convenience functions as directed by #2802

STYLE: Use ReadImage and WriteImage in a few iterator examples

---

Modules/Core/Common/include/itkMatrix.h
Modules/Core/Common/test/itkMatrixGTest.cxx

Allows constructing an `itk::Matrix` by passing a C-style array of
arrays, of the corresponding value type and dimensions.

ENH: Add explicit `Matrix(const RawDataArrayType &)` constructor

---

Modules/Core/Common/include/itkMetaDataObject.h
Modules/Core/Common/include/itkMetaDataObject.hxx
Modules/Core/Common/test/itkMetaDataDictionaryGTest.cxx

Allows passing a N-dimensional C-style array as value, when calling
`itk::EncapsulateMetaData(dictionary, key, value)`.

ENH: Support C-style arrays as MetaDataObjectType for MetaDataDictionary

---

Wrapping/Generators/Python/Tests/CMakeLists.txt
Wrapping/Generators/Python/Tests/nodefaultfactories.py
Wrapping/Generators/Python/itk/support/base.py
Wrapping/Generators/Python/itk/support/lazy.py
Wrapping/Generators/Python/itkConfig.py.in

Allow user to disable default loading of object factory override methods in Python. This is primarily intended to assist in debug investigations where factory overrides are suspected of interfering with expected behavior.
Behavior can be configured in two lines:
```py
import itkConfig
itkConfig.DefaultFactoryLoading = False
```
With default factory loading disabled a developer is responsible for manually supplying any implementations of abstract classes that previously relied on factory instantiation. For example, `itk.ImageFileReader` relies on factory overrides of `ImageIO` to read files based on their extension, so with no factories registered the developer must supply a suitable `ImageIO` object, i.e. : 
```py
image = itk.imread('path/to/image.mha', imageio=itk.MetaImageIO.New())
``` …

ENH: Add configuration to disable Python factory loading

---

CMake/ITKSetStandardCompilerFlags.cmake
Modules/Core/GPUCommon/test/CMakeLists.txt
Modules/Filtering/GPUAnisotropicSmoothing/test/CMakeLists.txt
Modules/Filtering/GPUImageFilterBase/test/CMakeLists.txt
Modules/Filtering/GPUSmoothing/test/CMakeLists.txt
Modules/Filtering/GPUThresholding/test/CMakeLists.txt
Modules/Registration/GPUPDEDeformable/test/CMakeLists.txt

ITKv5.3 requires at least MSVC version 1910 (Visual Studio 2017) now, so it is no longer useful to check if `MSVC_VERSION GREATER_EQUAL 1600`, or `1800`, or `MSVC_VERSION GREATER 1310`.
Checks on `CMAKE_COMPILER_2005` (Visual Studio 2005) are also obsolete.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2563 commit 4e812d60743a3ed7c09647e7f3f0e8498583c2da "COMP: Require compiler versions that support C++14" (merged on 3 June 2021)

STYLE: Remove CMake checks on old MSVC versions (before version 1910)

---

Modules/Core/Common/include/itkMetaDataObject.h
Modules/Core/Common/src/itkMetaDataObject.cxx
Modules/IO/NIFTI/src/itkNiftiImageIO.cxx

Using `itk::Matrix<float, 4, 4>` (instead of `std::vector<float>`) to store the "qto_xyz" data from m_NiftiImage, as this `Matrix` template instantiation more closely resembles the original niftilib `mat44` data structure.
Follow-up to pull request #3242 commit 9eb4c1209d215eed244e5e0a1d8f15942a61cb76 "ENH: bug #3241: Add qfac and qto_xyz to itkNiftiImageIO metadata" by Sean McBride (@seanm), which was merged on March 17, 2022.

STYLE: Encapsulate NiftiImage qto_xyz mat44 data as `Matrix<float,4,4>`

---

CMake/ITKModuleMacros.cmake
CMake/ITKSetStandardCompilerFlags.cmake

Follow-up to pull request #2563 commit 4e812d60743a3ed7c09647e7f3f0e8498583c2da "COMP: Require compiler versions that support C++14" (merged on 3 June 2021)

Remove obsolete CMake code for old GCC and Clang compilers

---

Modules/Core/Common/src/itkObjectFactoryBase.cxx

For the use case of Slicer using ITK Python wheels, ITK_AUTOLOAD_PATH
is set, and the Python wheel binaries will load the Slicer ITK binaries,
which will cause a crash.
Dynamic loading in Python is unnecessary and can be performed in a more
explicit and controlled manner by Python scripting, so disable this
feature by default when ITK_WRAP_PYTHON is set.

COMP: Do not use ITK_AUTOLOAD_PATH when ITK_WRAP_PYTHON is set

---

Modules/Core/GPUCommon/test/CMakeLists.txt
Modules/Filtering/GPUAnisotropicSmoothing/test/CMakeLists.txt
Modules/Filtering/GPUImageFilterBase/test/CMakeLists.txt
Modules/Filtering/GPUSmoothing/test/CMakeLists.txt
Modules/Filtering/GPUThresholding/test/CMakeLists.txt
Modules/Registration/GPUPDEDeformable/test/CMakeLists.txt

This MSVC specific compiler flag is already added to `CMAKE_CXX_FLAGS`,
by the "CMakeLists.txt" file in the root directory of ITK (as it is part
of `ITK_REQUIRED_CXX_FLAGS`).

STYLE: Remove duplicate MSVC `/bigobj` flags from GPU test projects

---

Modules/Core/Mesh/include/itkMesh.hxx
Modules/Filtering/BiasCorrection/include/itkMRASlabIdentifier.h
Modules/Filtering/DiffusionTensorImage/include/itkDiffusionTensor3DReconstructionImageFilter.h
Modules/Filtering/MathematicalMorphology/test/itkClosingByReconstructionImageFilterTest.cxx
Modules/Filtering/MathematicalMorphology/test/itkOpeningByReconstructionImageFilterTest.cxx
Modules/Filtering/MathematicalMorphology/test/itkOpeningByReconstructionImageFilterTest2.cxx
Modules/IO/DCMTK/include/itkDCMTKSeriesFileNames.h
Modules/IO/GDCM/include/itkGDCMSeriesFileNames.h
Modules/Numerics/Optimizersv4/include/itkLBFGS2Optimizerv4.h
Modules/Segmentation/Classifiers/test/itkSupervisedImageClassifierTest.cxx

- DOC: Fix typos and grammar in class and method documentation
- DOC: Increase `itk::MRASlabIdentifier` description Doxygen syntax use
- DOC: Fix typo in warning macro message
- DOC: Fix typos in miscellaneous comments
- DOC: Fix typo in variable names in test input argument usage
- STYLE: Allow a whitespace after variable in warning macro message

DOC: Fix typos and grammar

---

Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml

Needed for itkTransformSerializationTest.
Other transforms (AffineTransform, Rigid3DTransform, BSplineTransform, QuaternionRigidTransform) are inside 
core so not an issue.

ENH: Adding Module Dependency for Windows Python Test

---

Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.h
Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.hxx
Modules/Filtering/DisplacementField/include/itkVelocityFieldTransform.h
Modules/Filtering/DisplacementField/test/itkDisplacementFieldTransformTest.cxx
Modules/Filtering/DisplacementField/wrapping/test/CMakeLists.txt
Modules/Filtering/DisplacementField/wrapping/test/itkDisplacementFieldTransformTest.py
Wrapping/WrapITKTypes.cmake

`itk::DisplacementFieldTransform` is typically set from an array of displacement vectors. Previously only inputs of `itk::Image[itk::Vector[<type>,<VectorDimension>],<ImageDimension>]` were accepted. 
This PR aims to expose a method for setting the transform from an input of type `itk::VectorImage[<type>,<ImageDimension>]` . 
The difference between an "image of vectors" and a "vector image" is that the former has compile-time fixed-length vector pixels whereas the latter has variable-length vector pixels which have been fixed at a certain length at runtime. 

COMP: Allow setting DisplacementField with a VectorImage

---

Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx

Moved duplicate code into a lambda, replacing two unsafe C-style
pointer casts by a static_cast, and removing two unnecessary
`static_cast<unsigned int>` casts.

STYLE: Remove casts from `MersenneTwisterRandomVariateGenerator::hash`

---

Modules/Registration/Common/include/itkImageRegistrationMethodImageSource.h

Fix class name in RTTI.
Fixes:
```
Name of Class = Image
Name of Superclass = Object
Class name provided does not match object's NameOfClass
```
https://open.cdash.org/test/667512903

BUG: Fix class name in RTTI

---

Modules/Core/Common/include/itkBitCast.h
Modules/Core/Common/src/itkPlatformMultiThreaderWindows.cxx
Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkBitCastGTest.cxx

`bit_cast` helps to avoid undefined behavior when doing a bitwise cast.

Add `bit_cast`, and use it for `_beginthreadex` calls

---

Modules/Registration/FEM/include/itkMIRegistrationFunction.hxx

Fix so that the build no longer (correctly) complains that an `unsigned int` is cast to `double` in a context where narrowing casts are prohibited.

COMP: Fix overly narrow cast

---

Wrapping/Generators/CastXML/CMakeLists.txt

Update castXML to v0.45 on Windows to support Windows 11 and ninja compiler tool
See castXML source at
https://data.kitware.com/#item/622961504acac99f42134aab
See bug report at #3216 
CastXML update provided by @thewtex

BUG: Use CastXML 0.45 hash for Windows to support Windows 11 and ninja compiler tool

---

Modules/Compatibility/Deprecated/test/itkSpawnThreadTest.cxx
Modules/Core/Common/include/itkIsConvertible.h
Modules/Core/Common/include/itkThreadSupport.h
Modules/Core/Common/src/itkMemoryUsageObserver.cxx
Modules/Core/Common/test/itkTimeStampTest.cxx
Modules/Core/TestKernel/include/itkTestDriverInclude.h
Modules/Filtering/FFT/include/itkComplexToComplex1DFFTImageFilter.h
Modules/IO/GE/src/Ge5xHdr.h
Modules/IO/ImageBase/include/itkIOCommon.h
Modules/IO/LSM/src/itkLSMImageIO.cxx
Modules/IO/Siemens/include/itkSiemensVisionImageIO.h
Modules/Numerics/NarrowBand/include/itkNarrowBand.h
Modules/Registration/Metricsv4/include/itkANTSNeighborhoodCorrelationImageToImageMetricv4GetValueAndDerivativeThreader.h

In C, it might be useful to add such type aliases to `struct` and `enum` definitions (using `typedef`), but it is unnecessary in C++.
This pull request also removed duplicate lines of code from the definition of `ConditionVariableType`.

STYLE: Remove unnecessary `using` type aliases from struct and enum definitions

---

Modules/Core/Common/src/itkPlatformMultiThreaderWindows.cxx

It appears that commit 548b45f46dc9459bd9e6273a88485482794c3eaa ("BUG: Replace
C-style casts from `_beginthreadex` with `bit_cast<HANDLE>`", from pull request
https://github.com/InsightSoftwareConsortium/ITK/pull/3380) was wrong:
`bit_cast<HANDLE>` might do a different conversion than the corresponding
C-style cast, `(HANDLE)`.
The C-style cast `(HANDLE)` behaves exactly like `reinterpret_cast<HANDLE>`, by
definition.
`reinterpret_cast<HANDLE>` does an implementation-defined conversion, as was
explained by Jonathan Wakely at https://github.com/isocpp/CppCoreGuidelines/issues/1517#issuecomment-1104120989
(issue "Favor bit_cast over reinterpret_cast").
Fixed by replacing all `bit_cast<HANDLE>` calls with `reinterpret_cast<HANDLE>`.

BUG: Replace `bit_cast<HANDLE>` calls with `reinterpret_cast<HANDLE>`

---

Modules/Registration/Metricsv4/wrapping/itkMetricv4Types.wrap

Resolves [https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/issues/349](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/issues/349) in ITKSphinxExamples where `itk.RegistrationParameterScalesFromPhysicalShift` is wrapped only for `itk.JensenHavrdaChandraTsallisPointSetToPointSetMetricv4` inputs that are templated over `itk.PointSet[itk.SS,2]`.
Fixes template wrappings such that scales classes are templated over pointset-to-pointset metrics including real types (`itk.F`) and more than two dimensions if configured. Previously only the first template list entry was being parsed by the `_add_pointset_types` macro.

BUG: Re-add coverage for `itk::RegistrationParameterScales` types

---

Modules/Core/Common/include/itkMath.h

P.S.
**Not related** to this PR, just FYI, unfortunately actual documentation (itk.org,18 Jan 2022) for [itk::Math](https://itk.org/Doxygen/html/namespaceitk_1_1Math.html#a7c40db0dddb83464c99f3d859abf7faf) is partially affected by the bug #2058 , e.g. `abs()`methods

DOC: typo in itkMath comment

---

Documentation/Doxygen/Modules.dox

Improve Doxygen modules documentation:
- Add a new `DataReadWrite` group to contain the `WriterObjects` group.
- Use a compact wording for the group name.
- Avoid redundant wording like "This category", "This group", "Filters
on this category", etc.
- Fix typos, and improve wording.
- Use "ITK" to refer to the toolkit instead of other forms.
Remove references to non-existing classes/objects such as `Pixel`,
`PhysicalImage´, and fix/update the class name for
`BinaryMorphologicalFilterBase` to the current
`itk::BinaryMorphologyImageFilter`.
Take advantage of the commit to adopt a consistent style:
- Use lower cases when referring to technical ITK terms that do not link to
the class name.
- Use lower cases for Doxygen markup, following the Doxygen documentation.
- Link to ITK classes where …

DOC: Improve Doxygen modules documentation

---

Modules/IO/MeshBase/test/CMakeLists.txt
Modules/IO/MeshBase/test/itkMeshFileReaderWriterTest.cxx

- ENH: Prefer using existing file for unsupported format test
- STYLE: Remove unnecessary `nullptr` assignment to smart pointer

ENH: Prefer using existing file for unsupported format test

---

Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkXMLFileOutputWindowTest.cxx

The XMLFileOutputWindowTest only passed on the iniital run
of the test.  Subsequent runs would append to the file and
cause incorrect file line counts.  Merged two test scenerios
into one test run, and explicitly define the testing environment.

BUG: XMLFileOutputWindowTest failed subsequent runs

---

Modules/Remote/TubeTK.remote.cmake

Bump TubeTK version to support generation of 4D images in python.
TubeTK provides ITK classes that simplify reading/writing 4D images as lists of 3D images, even if ITK's Python API wasn't compiled with 4D image support (which is the default).   The TubeTK classes, however, accepted ITK image smartpointers as member function arguments, but to support python wrapping, they should instead accepted ITK image raw pointers.  This has been fixed in TubeTK in the tag given here.

ENH: Update TubeTK to support Write3DImagesAs4DImage in python

---

Modules/Core/SpatialObjects/include/itkSurfaceSpatialObject.h
Modules/Core/SpatialObjects/include/itkSurfaceSpatialObject.hxx

By templating over point type, derived surface classes can specify new point types with additional meta data. This is the same design patter used for TubeSpatialObjects.
Also, updated the normal computation to work for 2D data, instead of just 3D data, and marked old code as Legacy.

ENH: SurfaceSpatialObject templated over point type

---

Modules/Filtering/ImageNoise/include/itkAdditiveGaussianNoiseImageFilter.hxx
Modules/Filtering/ImageNoise/include/itkShotNoiseImageFilter.hxx

Instead of doing `*reinterpret_cast<const int32_t *>(&seed)`, which appears
more complicated.

STYLE: Use `bit_cast` to convert random seeds from uint32_t to int32_t

---

Modules/Core/Common/include/itkByteSwapper.h
Modules/Core/Common/include/itkByteSwapper.hxx

Declared the first parameter of its "SwapWrite" member functions pointer-to-const, and made various other `ByteSwapper` style improvements

Add const to first parameter of "SwapWrite" member functions, and other ByteSwapper style improvements

---

Modules/IO/GE/src/itkGE4ImageIO.cxx

And declare `sun_num` unsigned, to avoid unsigned-to-signed conversion.

STYLE: Use `constexpr` and `bit_cast` within `GE4ImageIO::MvtSunf(int)`

---

Modules/Core/Common/src/itkRealTimeClock.cxx

Removed estimation of `FILETIME` for January 1, 1601 (`ft1`), as it is entirely
zero anyway, according to the Windows API specification.
Converted `FILETIME` to seconds without old-style LARGE_INTEGER/memcpy magic.
Removed redundant `this->` and `static_cast<__int64>`.
Used an empty pair of braces, `{}`, to zero-initialize SYSTEMTIME.

STYLE: Clean-up code Windows version default-constructor `RealTimeClock`

---

Documentation/Doxygen/DoxygenFooter.html

Chrome will fail to download because the web pages are served via https.

BUG: Doxygen tarball links must be https

---

Modules/Core/Common/include/itkGaussianOperator.hxx

`itk::GaussianOperator` can be set with a `MaximumKernelWidth` parameter
such that a kernel that would otherwise overflow this size is cropped to
the maximum width. Cropping to the set maximum width happens frequently
in cases such as Gaussian blurring for multiscale pyramid generation and
is expected behavior, but the previous warning message makes it seem
like a failure case. This commit reduces the verbosity of the message
from a warning to a debug printout so that developers can get insights
into kernel cropping when needed, but are not alarmed by default warning
printouts.
Previous behavior: Warning whenever Gaussian kernel is correctly truncated to user specifications.
> WARNING: In C:\P\IPP\ITK-source\ITK\Modules\Core\Common\include\itkGaussianOperator.hxx, line 57
GaussianOperator …

PERF: Reduce verbosity of `itk::GaussianOperator` warning

---

Modules/Core/Common/include/itkGaussianOperator.h
Modules/Core/Common/include/itkGaussianOperator.hxx
Modules/Core/Common/include/itkMacro.h

Resolves #3430 by mimicking `itk::Object` debug interface methods so that `itkDebugMacro` implements valid debug code in `itk::GaussianOperator`.
`itk::GaussianOperator` inherits from the base `itk::Neighborhood` which is a lightweight object not inheriting from `itk::Object` or `itk::LightObject`. `itk::GaussianOperator` is more complex than other neighborhoods in that it takes in several user parameters and dynamically generates a discrete ND kernel function. In order to preserve the lightweight design of other `itk::Neighborhood` derivative classes while providing insight into the more complex inner workings of `itk::GaussianOperator`, it is reasonable to re-implement the `itk::Object` debug interface at the `itk::GaussianOperator` level.
Depends on #3431 hotfix.
Refer to the [ITK …

BUG: Add `itk::GaussianOperator` debug methods

---

Modules/Core/Common/include/itkGaussianOperator.hxx

Hotfix for failing Linux/macOS builds where itkDebugMacro is not
supported in `itk::GaussianOperator`.
Partially addresses [https://github.com/InsightSoftwareConsortium/ITK/issues/3430](https://github.com/InsightSoftwareConsortium/ITK/issues/3430).

BUG: Remove broken warning in `itk::GaussianOperator`

---

Wrapping/Generators/Python/Tests/test_xarray.py
Wrapping/Generators/Python/itk/support/xarray.py

Previously observed behavior where ITK data was released after ITK
Python filter went out of scope, resulting in cascading and difficult to
trace fatal memory r/w error on xarray access. This change makes data
copy the default behavior while exposing `in_place` option for cases
where operations are contained within a single block and behavior
benefits from in-place operations.
Addresses discussion in [https://github.com/spatial-image/multiscale-spatial-image/issues/44](https://github.com/spatial-image/multiscale-spatial-image/issues/44)

BUG: Copy to xarray by default

---

Modules/IO/NIFTI/test/itkNiftiImageIOTest13.cxx

ENH: Simplify Nifti IO test 13 using ReadImage and testing macros

---

Modules/IO/ImageBase/include/itkImageFileWriter.hxx
Modules/IO/MeshBYU/src/itkBYUMeshIO.cxx
Modules/IO/MeshBYU/test/CMakeLists.txt
Modules/IO/MeshBYU/test/itkBYUMeshIOTest.cxx
Modules/IO/MeshBase/include/itkMeshFileTestHelper.h
Modules/IO/MeshBase/include/itkMeshIOBase.h
Modules/IO/MeshBase/include/itkMeshIOTestHelper.h
Modules/IO/MeshFreeSurfer/test/CMakeLists.txt
Modules/IO/MeshFreeSurfer/test/itkFreeSurferMeshIOTest.cxx
Modules/IO/MeshGifti/src/itkGiftiMeshIO.cxx
Modules/IO/MeshGifti/test/CMakeLists.txt
Modules/IO/MeshGifti/test/itkGiftiMeshIOTest.cxx
Modules/IO/MeshOBJ/test/CMakeLists.txt
Modules/IO/MeshOBJ/test/itkOBJMeshIOTest.cxx
Modules/IO/MeshOFF/test/CMakeLists.txt
Modules/IO/MeshOFF/test/itkOFFMeshIOTest.cxx
Modules/IO/MeshVTK/src/itkVTKPolyDataMeshIO.cxx
Modules/IO/MeshVTK/test/CMakeLists.txt
Modules/IO/MeshVTK/test/itkMeshFileReadWriteVectorAttributeTest.cxx
Modules/IO/MeshVTK/test/itkPolylineReadWriteTest.cxx
Modules/IO/MeshVTK/test/itkVTKPolyDataMeshIOTest.cxx

- STYLE: Make style consistent with the ITK style
- STYLE: Use the `itkNameOfTestExecutableMacro` macro in tests
- DOC: Fix typos in documentation, comments and exception messages
- STYLE: Improve wording in `itk::GiftiMeshIO` exception messages
- ENH: Add boolean macros to `itk::MeshIOBase` data update ivars
- BUG: Avoid querying about null variable size
- BUG: Fix test driver name for `MeshOBJ` and `MeshOFF`
- ENH: Increase coverage for `MeshIO` classes

ENH: Increase `MeshIO` classes coverage

---

Modules/IO/MeshBYU/test/itkBYUMeshIOTest.cxx
Modules/IO/MeshBase/include/itkMeshIOTestHelper.h
Modules/IO/MeshFreeSurfer/test/itkFreeSurferMeshIOTest.cxx
Modules/IO/MeshGifti/test/itkGiftiMeshIOTest.cxx
Modules/IO/MeshOBJ/test/itkOBJMeshIOTest.cxx
Modules/IO/MeshOFF/test/itkOFFMeshIOTest.cxx
Modules/IO/MeshVTK/test/itkVTKPolyDataMeshIOTest.cxx

Let AllocateBuffer (from MeshIOTestHelper) return a `std::shared_ptr<void>`,
instead of producing a void pointer, to ensure that it is deleted correctly,
automatically.
Aims to fix Valgrind errors, saying:
> Mismatched free() / delete / delete []
As reported and discussed by Jon Haitz Legarreta Gorroño (@jhlegarreta) and Mihail Isakov (@issakomi) at pull request #3459

BUG: Let MeshIOTestHelper AllocateBuffer return `std::shared_ptr<void>`

---

Modules/Registration/Metricsv4/include/itkManifoldParzenWindowsPointSetFunction.hxx

Call the superclass `PrintSelf` method in the child `PrintSelf` method.

ENH: Call superclass `PrintSelf` method in child `PrintSelf`

---

Modules/IO/GDCM/test/CMakeLists.txt
Modules/IO/GDCM/test/itkGDCMSeriesStreamReadImageWriteTest.cxx

Increase coverage for `itk::GDCMSeriesFileNames`:
- Refactor the test to accept more input parameters to allow checking
the class under a broader range of conditions.

ENH: Increase coverage for `itk::GDCMSeriesFileNames`

---

Modules/Compatibility/Deprecated/include/itkAtomicInt.h
Modules/Core/Common/include/itkIndex.h
Modules/Core/Common/include/itkOffset.h
Modules/Core/Common/include/itkSize.h
Modules/IO/ImageBase/include/itkImageSeriesReader.hxx

This commit fixes a regression likely introduced in c173dfd80 (STYLE: Remove `std::` prefix from types that work without it) to support building ITK wheels using manylinux_2_24 providing gcc 6.3.
It fixes build error like the following:
```
In file included from /work/ITK-source/ITK/Modules/Core/Common/include/itkImageRegion.h:33:0,
from /work/ITK-source/ITK/Modules/Core/Common/include/itkMultiThreaderBase.h:35,
from /work/ITK-source/ITK/Modules/Core/Common/src/itkTotalProgressReporter.cxx:19:
/work/ITK-source/ITK/Modules/Core/Common/include/itkSize.h:242:27: error: ‘ptrdiff_t’ does not name a type
using difference_type = ptrdiff_t;
^~~~~~~~~
```
cc: @Leengit

COMP: Fix older gcc build error including "cstddef" for "ptrdiff_t"

---

Modules/IO/GDCM/src/itkGDCMImageIO.cxx

It should have been removed in 14fbe528a78efb5696b3526de3c3968b14dcbe71, but was missed.

STYLE: removed obsolete and confusing old comment

---

Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.hxx

See https://discourse.itk.org/t/n4biasfieldcorrectionimagefilter-getlogbiasfieldasimage-wrap-bsplinecontrolpointimagefilter-alternatives/5142/2
If (for some reason) the input requested region is different than the largest possible region, the code was
- first reconstructing the bias field using the largest possible region
- then setting all regions to `inputImage->GetRequestedRegion()`, which doesn't make sense
To reduce the change to a minimum I still set the requested region based on `inputImage->GetRequestedRegion()`, but  probably we could just remove the line completely.

BUG: all regions set to requested in ReconstructBiasField

---

Modules/Remote/MinimalPathExtraction.remote.cmake

Critical update to MinimalPathExtraction addresses changes
to ITK's FastMarching methods. Updating is required to avoid
exception being thrown.

ENH: Bump ITKMinimalPathExtraction tag

---

Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
Modules/IO/NIFTI/test/CMakeLists.txt
Modules/IO/NIFTI/test/itkNiftiWriteCoerceOrthogonalDirectionTest.cxx

ENH: Issue warning when NIFTI IO coerces matrix to orthogonal.

---

Wrapping/Generators/Python/PyBase/pyBase.i
Wrapping/Generators/Python/itkPyITKCommonCAPI.h
Wrapping/Generators/SwigInterface/igenerator.py
Wrapping/macro_files/itk_end_wrap_module.cmake

Addresses:
```
ImportError: PyCapsule_Import could not import module "_ITKCommonPython"
```
That can occur when unpickling for Dask, for example.
According to the `PyCapsule_Import` documentation, internally it calls
`PyImport_ImportModule`. According to the `PyImport_ImportModule`
documentation, this requires the absolute path -- we add the `itk.`
prefix.
In most other contexts, the `_ITKCommonPython` module is likely to
already be imported. Since `_ITKCommonPython` gets loaded via
PyImport_ImportModule, it is not registered with the ITK lazy loading
module system, so we add `from . import _ITKCommon`.

BUG: Use absolute module path PyCapsule_Import

---

Modules/Filtering/ImageStatistics/include/itkLabelOverlapMeasuresImageFilter.h
Modules/Filtering/ImageStatistics/include/itkLabelOverlapMeasuresImageFilter.hxx
Modules/Filtering/ImageStatistics/test/itkLabelOverlapMeasuresImageFilterTest.cxx

Add definition of false discovery rate
Separate FalsePositiveError with FPR and FDR
Indicate members of the confusion matrix in code comments
Support test for GetFalseDiscoveryRate() function
From @Joeycho. Closes #3490.

ENH: Improve LabelOverlapMeasuresImageFilter

---

Modules/Core/Common/include/itkEventObject.h
Modules/Core/Common/include/itkExceptionObject.h
Modules/Core/Common/test/itkByteSwapTest.cxx
Modules/Core/Common/test/itkSliceIteratorTest.cxx
Modules/Core/Common/test/itkVariableSizeMatrixTest.cxx
Modules/Filtering/AnisotropicSmoothing/test/itkCurvatureAnisotropicDiffusionImageFilterTest.cxx
Modules/Filtering/AnisotropicSmoothing/test/itkGradientAnisotropicDiffusionImageFilterTest.cxx
Modules/Filtering/AnisotropicSmoothing/test/itkVectorAnisotropicDiffusionImageFilterTest.cxx
Modules/Filtering/DistanceMap/test/itkIsoContourDistanceImageFilterTest.cxx
Modules/Filtering/ImageFeature/test/itkBilateralImageFilterTest.cxx
Modules/Filtering/ImageFilterBase/test/itkNeighborhoodOperatorImageFilterTest.cxx
Modules/Filtering/ImageFilterBase/test/itkVectorNeighborhoodOperatorImageFilterTest.cxx
Modules/Filtering/Smoothing/test/itkSmoothingRecursiveGaussianImageFilterOnImageAdaptorTest.cxx
Modules/Filtering/Smoothing/test/itkSmoothingRecursiveGaussianImageFilterOnImageOfVectorTest.cxx
Modules/Filtering/Smoothing/test/itkSmoothingRecursiveGaussianImageFilterOnVectorImageTest.cxx
Modules/Numerics/NarrowBand/test/itkNarrowBandImageFilterBaseTest.cxx

Replace all occurrences of `(&x)->Print` with `x.Print`

---

Modules/Filtering/FastMarching/include/itkFastMarchingUpwindGradientImageFilter.hxx
Modules/IO/CSV/include/itkCSVNumericObjectFileWriter.hxx
Modules/IO/ImageBase/include/itkIOTestHelper.h
Modules/Numerics/Optimizers/src/itkGradientDescentOptimizer.cxx
Modules/Numerics/Optimizers/src/itkRegularStepGradientDescentBaseOptimizer.cxx
Modules/Numerics/Optimizers/src/itkSPSAOptimizer.cxx
Modules/Numerics/Optimizersv4/include/itkConjugateGradientLineSearchOptimizerv4.hxx
Modules/Numerics/Optimizersv4/include/itkGradientDescentLineSearchOptimizerv4.hxx
Modules/Numerics/Optimizersv4/include/itkGradientDescentOptimizerv4.hxx
Modules/Numerics/Optimizersv4/include/itkMultiGradientOptimizerv4.hxx
Modules/Numerics/Optimizersv4/include/itkQuasiNewtonOptimizerv4.hxx
Modules/Numerics/Optimizersv4/include/itkRegularStepGradientDescentOptimizerv4.hxx
Modules/Registration/Common/include/itkImageRegistrationMethod.hxx
Modules/Registration/Common/include/itkImageToSpatialObjectRegistrationMethod.hxx
Modules/Registration/Common/include/itkMultiResolutionImageRegistrationMethod.hxx
Modules/Registration/Common/include/itkPointSetToImageRegistrationMethod.hxx
Modules/Registration/Common/include/itkPointSetToPointSetRegistrationMethod.hxx
Modules/Segmentation/Classifiers/include/itkBayesianClassifierInitializationImageFilter.hxx
Modules/Video/Core/src/itkTemporalProcessObject.cxx

Following C++ Core Guidelines, April 10, 2022, which says:
> To rethrow a caught exception use `throw;` not `throw e;`
At https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#e15-throw-by-value-catch-exceptions-from-a-hierarchy-by-reference
Found by the regular expression, `catch \(const [^\s]+ & (\w+)\).+  throw \1;`

STYLE: Rethrow caught exceptions just by `throw;` without argument

---

Wrapping/Generators/Python/CMakeLists.txt

As [PEP 632](https://peps.python.org/pep-0632/) describes, we should use the `sysconfig` module instead of `distutils.sysconfig `.
Without this commit, we need to set `PY_SITE_PACKAGES_PATH`, see also related issue #2960.

COMP: use sysconfig.get_path as PEP 632 deprecate distutils module

---

Testing/ContinuousIntegration/AzurePipelinesMacOS.yml
Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml

Switch Azure Pipelines macOS environment version to `macos-11`.
Fixes:
```
Warning
The macOS-10.15 environment is deprecated, consider switching to macos-11(macos-latest), macos-12 instead.
For more details see https://github.com/actions/virtual-environments/issues/5583
```
reported for example at:
https://dev.azure.com/itkrobotmacos/ITK.macOS/_build/results?buildId=8641&view=results

ENH: Switch Azure Pipelines macOS environment version

---

Modules/IO/HDF5/include/itkHDF5ImageIO.h
Modules/IO/HDF5/src/itkHDF5ImageIO.cxx
Modules/IO/HDF5/test/itkHDF5ImageIOStreamingReadWriteTest.cxx
Modules/IO/ImageBase/include/itkIOTestHelper.h
Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
Modules/IO/NIFTI/test/itkNiftiImageIOTest.h
Modules/IO/NIFTI/test/itkNiftiImageIOTest5.cxx

Ensure that attempts to write to invalid file paths causes error to be reported. Ref #1958.

BUG: Allow nifti load to fail

---

Modules/Remote/MinimalPathExtraction.remote.cmake

* BUG: It is .post2, not -post2, for ITK 5.3 rc4 in setup.py
* https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/pull/94
* COMP: Remove inclusion of .hxx files as headers by @hjmjohnson in
* https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/pull/86
* COMP: Modules need updated version of ITK by @hjmjohnson in
* https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/pull/87
* BUG: Set FastMarching targets prior to reach mode by @aylward in
* https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/pull/90
* ENH: Bump ITK and replace http with https using script by @tbirdso in
* https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/pull/89
* ENH: Update Python package for itk-5.3rc4 by @thewtex in
* …

ENH: Bump MinimalPathExtraction module to v1.2.2

---

Modules/Remote/MinimalPathExtraction.remote.cmake
Modules/Remote/TubeTK.remote.cmake

TubeTK 1.3.2 and MinimalPathExtraction 1.2.3 have been updated to build wheels against ITKv5.3rc04.post2
This necessary since external module wheels built using previous versions of ITK are not compatible with ITKv5.4rc04.post2 or later versions.
See https://github.com/InsightSoftwareConsortium/ITK/issues/3528

ENH: Bump TubeTK and MinimalPathExtraction for v5.3rc04.post2 wheels

---

CMake/ITKSetStandardCompilerFlags.cmake

Addresses:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.0/../../../../include/c++/12.1.0/bits/new_allocator.h:158:2: error: call to '__builtin_operator_delete' selects non-usual deallocation function
_GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
```
Fixes #3452

COMP: Add -fno-sized-deallocation for GCC 12

---

Modules/IO/NIFTI/src/itkNiftiImageIO.cxx

Should fix the small regression after
https://github.com/InsightSoftwareConsortium/ITK/commit/63590b85bbe5016ecb863a27007ce22979c27bc9
https://open.cdash.org/viewDynamicAnalysisFile.php?id=9648918
https://open.cdash.org/viewDynamicAnalysisFile.php?id=9648919
https://open.cdash.org/viewDynamicAnalysisFile.php?id=9648921
https://open.cdash.org/viewDynamicAnalysisFile.php?id=9648923
https://open.cdash.org/viewDynamicAnalysisFile.php?id=9648924
CC   @hjmjohnson

BUG: fixed memory leak in Nifti IO

---

Modules/IO/MeshVTK/include/itkVTKPolyDataMeshIO.h
Modules/IO/MeshVTK/src/itkVTKPolyDataMeshIO.cxx

`MeshFileReader`/`VTKPolyDataMeshIO` did hang forever when trying to read an
ASCII .vtk file that contained non-numeric chars in "POINTS" section, for
example "Infinity" or "NaN".
With this commit, "inf" and "Infinity" will be interpreted as the floating point
value infinity, while "nan" and "NaN" will be interpreted as Not-A-Number. Other
strings of non-numeric characters in the list of point components (coordinates)
will cause the reader to throw an appropriate `itk::ExceptionObject`.
Addresses issue https://github.com/InsightSoftwareConsortium/ITK/issues/3539
"MeshFileReader/VTKPolyDataMeshIO hangs forever on non-numeric chars in "POINTS"
section (including "Infinity" and "NaN")"

BUG: VTKPolyDataMeshIO should not hang on inf and NaN in ASCII .vtk file

---

Modules/IO/MINC/src/itkMINCImageIO.cxx

MINC IO does not free allocations before throwing an exception sometimes,
s. discussion https://github.com/InsightSoftwareConsortium/ITK/pull/3529
https://open.cdash.org/viewDynamicAnalysis.php?buildid=8097352
(reviewed _writing_ an image).

BUG: fixed memory leaks in MINC IO

---

Modules/IO/MeshVTK/test/CMakeLists.txt
Modules/IO/MeshVTK/test/itkVTKPolyDataMeshIOGTest.cxx

Added `VTKPolyDataMeshIO` GoogleTest, having the following unit tests:
- LosslessWriteAndReadOfPoints
- SupportWriteAndReadOfNaNCoordValues

ENH: Add VTKPolyDataMeshIO GTest tests, testing lossless write and read

---

CMakeLists.txt

COMP: Set CMake Policy 135 to NEW to suppress warnings in CMake 3.24

---

Modules/IO/MeshBase/include/itkMeshFileReader.h
Modules/IO/MeshBase/include/itkMeshFileReader.hxx

Reduced the amount of code duplication from 26 `case`s of `switch` statements,
within `MeshFileReader::GenerateData()`. Removed `delete[]` statements,
following C++ Core Guidelines, April 10, 2022, "Use unique_ptr or shared_ptr to
avoid forgetting to delete objects created using new"
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-smart

STYLE: Clean up code by ReadPointsUsingMeshIO(), ReadCellsUsingMeshIO()

---

Modules/IO/MeshBase/include/itkMeshFileReader.hxx
Modules/IO/MeshVTK/src/itkVTKPolyDataMeshIO.cxx
Modules/IO/MeshVTK/test/itkVTKPolyDataMeshIOGTest.cxx

`itk::MeshFileWriter` does allow writing non-3D points to a .vtk file, so it
appears both reasonable and useful for `itk::MeshFileReader` to allow reading
those points back.
Implemented by setting the PointDimension within MeshFileReader::GenerateData(),
and tested by GTest `VTKPolyDataMeshIO.SupportsAnyPointDimensionGreaterThanZero`.
Related to issue https://github.com/slicersalt/ITKShape/issues/8 "Add 2D mesh support" by Matt McCormick (@thewtex).

ENH: Support reading a mesh of non-3D points from a .vtk PolyData file

---

Modules/Core/Common/wrapping/itkMetaDataObject.wrap
Modules/Core/Common/wrapping/test/itkMetaDataDictionaryTest.py

Needed to convert image to xarray. Dict method on image fails without these wrappings.

ENH: Add MetaDataObject Python wrapping with Matrix

---

Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx

The suggested member function does not exist.  Use one of the two
available member functions to suggest the correct behavior for
using the reference image information.

Fix exception message

---

Testing/ContinuousIntegration/AzurePipelinesLinux.yml
Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml

Switch Azure Pipelines Linux environment version to `ubuntu-20.04`.
Fixes:
```
Warning
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest),
or ubuntu-22.04 instead.
For more details see https://github.com/actions/virtual-environments/issues/6002
```
reported for example at:
https://dev.azure.com/itkrobotlinux/ITK.Linux/_build/results?buildId=8765&view=results
Install the `lxml` Python package. Fixes:
```
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/5d2d781b-9e71-4c0a-ab4d-2837ae79d6f9.sh
File "/usr/local/lib/python3.8/dist-packages/anyci/ctest_junit_formatter.py", line 4, in <module>
from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```
reported for example at: …

ENH: Switch Azure Pipelines Linux environment version

---

Modules/Core/Common/include/itkEllipsoidInteriorExteriorSpatialFunction.h
Modules/Core/Common/include/itkEllipsoidInteriorExteriorSpatialFunction.hxx

Declared the private (internal) EllipsoidInteriorExteriorSpatialFunction data
member `m_Orientations` as a `vnl_matrix_fixed`, instead of a raw pointer to
dynamically allocated memory.
Defaulted the `EllipsoidInteriorExteriorSpatialFunction` destructor, as it now
no longer needs to `delete` internal data pointers anymore.
Following C++ Core Guidelines, April 10, 2022, "Prefer scoped objects, don’t
heap-allocate unnecessarily",
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r5-prefer-scoped-objects-dont-heap-allocate-unnecessarily

STYLE: Declare Ellipsoid SpatialFunction orientations as a fixed matrix

---

Modules/Filtering/Path/include/itkOrthogonalSwath2DPathFilter.h
Modules/Filtering/Path/include/itkOrthogonalSwath2DPathFilter.hxx

Also "defaulted" both its default-constructor and its destructor. Made use of
modern C++ in-class data member initialization.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2897
commit 3c6f2984df2085f3465edd0c941ab222834fccca
"STYLE: Use `unique_ptr` for `ImageToImageMetric` data members"

STYLE: Use `unique_ptr` for `OrthogonalSwath2DPathFilter` data members

---

Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.h
Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.hxx

Declared the private (internal) WindowedSincInterpolateImageFunction data
members `m_WeightOffsetTable` and `m_WeightOffsetTable` as fixed-size C-style
arrays, instead of raw pointers to dynamically allocated memory.
Declared the private data members `m_WindowSize` and `m_OffsetTableSize` both
`static constexpr`, to ensure compile-time evaluation.
Defaulted the default-constructor and destructor of
`WindowedSincInterpolateImageFunction`, as they now no longer need to
explicitly manage the internal data.
Following C++ Core Guidelines, April 10, 2022, "Prefer scoped objects, don’t
heap-allocate unnecessarily",
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r5-prefer-scoped-objects-dont-heap-allocate-unnecessarily
Somewhat similar to pull request #3564 "STYLE: Declare Ellipsoid …

STYLE: Declare WindowedSincInterpolateImageFunction data as fixed arrays

---

Modules/Numerics/Statistics/include/itkNormalVariateGenerator.h
Modules/Numerics/Statistics/src/itkNormalVariateGenerator.cxx

Declared the private (internal) NormalVariateGenerator data member `m_Vec1` as
a fixed-size C-style array, instead of a raw pointer to dynamically allocated
memory.
Declared the private data members `m_ELEN`, `m_LEN`, `m_LMASK`, and `m_TLEN`
`static constexpr`, to ensure compile-time evaluation.
Defaulted the destructor of `NormalVariateGenerator`.
Following C++ Core Guidelines, April 10, 2022, "Prefer scoped objects, don’t
heap-allocate unnecessarily",
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r5-prefer-scoped-objects-dont-heap-allocate-unnecessarily

STYLE: Declare `NormalVariateGenerator::m_Vec1` as fixed array

---

.github/workflows/apply-clang-format.yml

Attempt to enable the pull request clang format action to work on forked pull
requests.
Background:
- https://github.com/actions/labeler/issues/12
- https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/

BUG: Add permissions to apply clang format action

---

.github/workflows/label-pr.yml

Attempt to enable the pull request labeler to work on forked pull
requests.
Background:
- https://github.com/actions/labeler/issues/12
- https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/

BUG: Add GitHub Action permissions for the labeller

---

Modules/Core/Common/test/itkVariableLengthVectorTest.cxx
Modules/Core/SpatialObjects/include/itkMetaDTITubeConverter.hxx
Modules/Core/SpatialObjects/include/itkMetaEllipseConverter.hxx
Modules/Core/SpatialObjects/include/itkMetaSceneConverter.hxx
Modules/Core/SpatialObjects/test/itkSpatialObjectDuplicatorTest.cxx
Modules/Filtering/FFT/include/itkFFTWCommon.h
Modules/Filtering/ImageFilterBase/include/itkMovingHistogramImageFilter.hxx
Modules/Filtering/MathematicalMorphology/include/itkMaskedMovingHistogramImageFilter.hxx
Modules/IO/SpatialObjects/test/itkReadWriteSpatialObjectTest.cxx

Changed the type of local variables that were declared as pointer and
initialized by `new T[N]`, to the corresponding fixed size C-style array type,
`T[N]`. Removed the corresponding `delete []` statements.
Cases found by the following regular expressions:
new \w+\[\d\]
new \w+\[V\w+\]
new \w+\[\w*Dimension\]
Aims to increase code readability, and may (possibly) improve the run-time
performance.
Following C++ Core Guidelines, April 10, 2022, "Prefer scoped objects, don’t
heap-allocate unnecessarily",
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r5-prefer-scoped-objects-dont-heap-allocate-unnecessarily

STYLE: Replace pointers initialized by `new T[N]` with fixed arrays

---

Modules/Filtering/ImageFeature/include/itkCannyEdgeDetectionImageFilter.h

The information was outdated, and could
simply document the trivial behavior of
the functions.
Simple documentation change to superceede : #3575

DOC: Remove outdated migration information

---

Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/src/Core/arch/NEON/PacketMath.h

Addresses:
Modules/ThirdParty/Eigen3/src/itkeigen/../itkeigen/Eigen/src/Core/arch/NEON/PacketMath.h:1671:9: warning: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘Eigen::internal::Packet4c’ {aka ‘struct Eigen::internal::eigen_packet_wrapper<int, 2>’} from an array of ‘const int8_t’ {aka ‘const signed char’} [-Wclass-memaccess]
with GCC 11.2.0 on ARM/Linux.
Explicit cast to void * to indicate that the call was intentional.
Upstream update expected with next Eigen upgrade, discussed:
https://gitlab.kitware.com/phcerdan/eigen/-/issues/3.

COMP: ARM Eigen copying an object of non-trivial type

---

.github/workflows/clang-format-linter.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.h

The full error message is:
```log
M:\Dashboard\ITK\Modules\Core\ImageFunction\include\itkWindowedSincInterpolateImageFunction.h(346): error C2397: conversion from 'TReturnType' to 'const unsigned int' requires a narrowing conversion [M:\Dashboard\ITK-build\Modules\Core\Common\test\ITKCommon1TestDriver.vcxproj]
M:\Dashboard\ITK\Modules\Core\Common\test\itkPhasedArray3DSpecialCoordinatesImageTest.cxx(96): note: see reference to class template instantiation 'itk::WindowedSincInterpolateImageFunction<Image,3,itk::Function::HammingWindowFunction<3,double,double>,itk::ZeroFluxNeumannBoundaryCondition<TInputImage,TInputImage>,double>' being compiled
```
Dashboard build: https://open.cdash.org/viewBuildError.php?buildid=8124742

COMP: Fix compile error on Visual Studio 2017

---

Modules/Core/Common/include/itkMakeUniqueForOverwrite.h
Modules/Core/Common/src/itkWin32OutputWindow.cxx
Modules/Core/Common/src/itkXMLFileOutputWindow.cxx
Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkMakeUniqueForOverwriteGTest.cxx
Modules/IO/BioRad/src/itkBioRadImageIO.cxx
Modules/IO/GDCM/src/itkGDCMImageIO.cxx
Modules/IO/GIPL/src/itkGiplImageIO.cxx
Modules/IO/ImageBase/src/itkNumericSeriesFileNames.cxx
Modules/IO/ImageBase/src/itkRawImageIOUtilities.cxx
Modules/IO/LSM/src/itkLSMImageIO.cxx
Modules/IO/MINC/src/itkMINCImageIO.cxx
Modules/IO/MeshFreeSurfer/src/itkFreeSurferAsciiMeshIO.cxx
Modules/IO/MeshFreeSurfer/src/itkFreeSurferBinaryMeshIO.cxx
Modules/IO/MeshOBJ/src/itkOBJMeshIO.cxx
Modules/IO/MeshOFF/src/itkOFFMeshIO.cxx
Modules/IO/MeshVTK/src/itkVTKPolyDataMeshIO.cxx
Modules/IO/Meta/src/itkMetaImageIO.cxx
Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
Modules/IO/Stimulate/src/itkStimulateImageIO.cxx
Modules/IO/TIFF/src/itkTIFFImageIO.cxx
Modules/IO/VTK/src/itkVTKImageIO.cxx
Modules/IO/XML/src/itkXMLFile.cxx

Replaced `new T[n]` with `make_unique_for_overwrite<T[]>(n)` in code that basically looks like: 
auto * data = new T[n];
Do things...
delete [] data;
Doing so fixes some potential memory leaks, when the things being done before the `delete [] data` might throw an exception.
`make_unique_for_overwrite` is introduced with C++20: https://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique It is hereby mimicked for dynamic array allocation as `itk::make_unique_for_overwrite`

Add `make_unique_for_overwrite` from C++20, and replace `new T[n]` with `make_unique_for_overwrite<T[]>(n)` calls

---

Modules/Nonunit/Review/test/itkMultiphaseDenseFiniteDifferenceImageFilterTest.cxx

Fix variable spelling mistake in `Review` module
`itk::MultiphaseDenseFiniteDifferenceImageFilter` class test file.
Fixes:
```
/Nonunit/Review/test/itkMultiphaseDenseFiniteDifferenceImageFilterTest.cxx:115:47:
error: use of undeclared identifier 'flter'; did you mean 'filter'?
ITK_TEST_SET_GET_VALUE(reinitializeCounter, flter->GetReinitializeCounter());
^~~~~
filter
```
introduced in commit 669a39c.
Raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=8135692

BUG: Fix variable typo `MultiphaseDenseFiniteDifferenceImageFilter` test

---

Modules/Core/Common/include/itkSymmetricEigenAnalysis.hxx
Modules/Filtering/DistanceMap/include/itkFastChamferDistanceImageFilter.hxx
Modules/Filtering/GPUAnisotropicSmoothing/include/itkGPUScalarAnisotropicDiffusionFunction.hxx
Modules/Filtering/ImageCompare/include/itkSTAPLEImageFilter.hxx
Modules/IO/MeshBase/include/itkMeshFileWriter.hxx
Modules/IO/MeshBase/include/itkMeshIOBase.h
Modules/IO/MeshFreeSurfer/include/itkFreeSurferAsciiMeshIO.h
Modules/IO/MeshFreeSurfer/include/itkFreeSurferBinaryMeshIO.h
Modules/IO/MeshOFF/include/itkOFFMeshIO.h
Modules/IO/MeshVTK/include/itkVTKPolyDataMeshIO.h
Modules/Numerics/Statistics/include/itkHistogramToTextureFeaturesFilter.hxx
Modules/Numerics/Statistics/include/itkScalarImageToRunLengthFeaturesFilter.hxx
Modules/Segmentation/Classifiers/include/itkImageKmeansModelEstimator.hxx
Modules/Segmentation/ConnectedComponents/include/itkHardConnectedComponentImageFilter.hxx
Modules/Segmentation/LabelVoting/include/itkMultiLabelSTAPLEImageFilter.hxx
Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.hxx
Modules/Segmentation/Voronoi/include/itkVoronoiDiagram2DGenerator.hxx
Modules/Video/IO/include/itkVideoFileReader.hxx

Replaced `new T[n]` with `make_unique_for_overwrite<T[]>(n)` calls, for the
initialization of local variables in ITK library files (*.h, *.hxx), and
removed the corresponding `delete[]` statements.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3590
commit 15d09d6c756b46b4d1c296d8bb13b85f82654ef9
"STYLE: Replace `new T[n]` with `make_unique_for_overwrite` in cxx files"

STYLE: More make_unique_for_overwrite, less delete[], on local variables

---

Modules/Core/Common/include/itkAnnulusOperator.hxx
Modules/Core/Common/include/itkImageKernelOperator.hxx
Modules/Core/Common/include/itkLaplacianOperator.hxx
Modules/Core/Common/include/itkNeighborhoodOperator.hxx

Might speed up the "Fill" member functions of AnnulusOperator, ImageKernelOperator, LaplacianOperator, and NeighborhoodOperator.

STYLE: Let Operator Fill allocate temp_slice on the stack, without `new`

---

Modules/Core/Common/include/itkImageBase.hxx
Modules/Core/Common/include/itkPointSet.hxx
Modules/Core/Common/src/itkDataObject.cxx
Modules/Core/SpatialObjects/include/itkSpatialObject.hxx
Modules/Segmentation/LevelSetsv4/include/itkLevelSetBase.hxx

When calling `GetSource()` twice on the same data object, debug output may appear duplicated, and it may cause unnecessary reference counting (both up and down) of the source object.
For clarification, the debug output may come from the `itkDebugMacro` call inside `DataObject::GetSource()`, and the reference counting comes from converting m_Source to a `SmartPointer`, here:
https://github.com/InsightSoftwareConsortium/ITK/blob/c1839700a9d28946d1313caf91795e4ce160eb13/Modules/Core/Common/src/itkDataObject.cxx#L247-L252

Each `UpdateOutputInformation()` member function should call `GetSource()` just once

---

Modules/Core/Common/include/itkDataObject.h
Modules/Core/Common/src/itkDataObject.cxx
Modules/Registration/Common/include/itkCenteredTransformInitializer.hxx
Modules/Registration/Common/include/itkCompareHistogramImageToImageMetric.hxx
Modules/Registration/Common/include/itkImageToImageMetric.hxx
Modules/Registration/Common/include/itkImageToSpatialObjectMetric.hxx
Modules/Registration/Common/include/itkPointSetToImageMetric.hxx
Modules/Registration/Common/include/itkPointSetToPointSetMetric.hxx
Modules/Registration/Metricsv4/include/itkImageToImageMetricv4.hxx
Modules/Registration/Metricsv4/include/itkPointSetToPointSetMetricWithIndexv4.hxx

`DataObject::UpdateSource()` offers a more efficient, more concise alternative to the following common pattern:
if (x->GetSource())
{
x->GetSource()->Update();
}
Calling `DataObject::UpdateSource()` instead is more efficient, because it internally calls `DataObject::GetSource()` just once, instead of twice.
Replaced all (15) occurrences of the pattern with  `x->UpdateSource()` calls.
Follow-up to pull request #3602 "Each `UpdateOutputInformation()` member function should call `GetSource()` just once"

Add `DataObject::UpdateSource()`, replacing `GetSource()->Update()` calls

---

Modules/Filtering/FastMarching/include/itkFastMarchingImageToNodePairContainerAdaptor.h
Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterRealTest2.cxx

- ENH: Add `FastMarchingImageToNodePairContainerAdaptor` getter methods
- STYLE: Use `ITK_TRY_EXPECT_NO_EXCEPTION` macro in tests

ENH: Add `FastMarchingImageToNodePairContainerAdaptor` getter methods

---

Modules/Core/Common/include/itkDirectory.h
Modules/Core/Common/src/itkDirectory.cxx

Removed the extra heap allocation for the internal data of `Directory`, and "defaulted" its default-constructor and destructor.

STYLE: Allocate `Directory::m_Internal` without `new`

---

Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.h
Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.hxx

Declared m_LabelStatus, m_Region, and m_RegionCount as `unique_ptr<T[]>`, which improved exception-safety. Defaulted the destructor of `RGBGibbsPriorFilter`.

STYLE: Declare `RGBGibbsPriorFilter` data members as `unique_ptr<T[]>`

---

Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.h
Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.hxx
Modules/Registration/Common/include/itkMeanSquaresImageToImageMetric.h
Modules/Registration/Common/include/itkMeanSquaresImageToImageMetric.hxx
Modules/Registration/Metricsv4/include/itkCorrelationImageToImageMetricv4GetValueAndDerivativeThreader.h
Modules/Registration/Metricsv4/include/itkCorrelationImageToImageMetricv4GetValueAndDerivativeThreader.hxx
Modules/Registration/Metricsv4/include/itkCorrelationImageToImageMetricv4HelperThreader.h
Modules/Registration/Metricsv4/include/itkCorrelationImageToImageMetricv4HelperThreader.hxx
Modules/Registration/Metricsv4/include/itkImageToImageMetricv4GetValueAndDerivativeThreaderBase.h
Modules/Registration/Metricsv4/include/itkImageToImageMetricv4GetValueAndDerivativeThreaderBase.hxx
Modules/Registration/Metricsv4/include/itkJointHistogramMutualInformationComputeJointPDFThreaderBase.h
Modules/Registration/Metricsv4/include/itkJointHistogramMutualInformationComputeJointPDFThreaderBase.hxx
Modules/Registration/Metricsv4/include/itkJointHistogramMutualInformationGetValueAndDerivativeThreader.h
Modules/Registration/Metricsv4/include/itkJointHistogramMutualInformationGetValueAndDerivativeThreader.hxx

Declared registration metric "per thread" data members as `unique_ptr<T[]>` (similar to pull request #3613 and #3614), and removed `mutable` keywords from their declarations.

 Declare metric "per thread" data members as `unique_ptr<T[]>`, remove `mutable`

---

Modules/Registration/RegistrationMethodsv4/test/itkSimpleImageRegistrationTest.cxx
Modules/Registration/RegistrationMethodsv4/test/itkSimpleImageRegistrationTest2.cxx
Modules/Registration/RegistrationMethodsv4/test/itkSimplePointSetRegistrationTest.cxx

Increase coverage for `itk::ImageRegistrationMethodv4`:
- Test other getter methods by serializing the data to the standard output.

ENH: Increase coverage for `itk::ImageRegistrationMethodv4`

---

Modules/Segmentation/LabelVoting/test/itkMultiLabelSTAPLEImageFilterTest.cxx

- BUG: Set the maximum number of iterations to a non-zero value in test
- ENH: Increase `itk::MultiLabelSTAPLEImageFilter` coverage
- STYLE: Use `ITK_TRY_EXPECT_NO_EXCEPTION` macro in tests
- STYLE: Improve style in `itkMultiLabelSTAPLEImageFilterTest` file
- DOC: Conform to ITK SW Guidelines in comments

ENH: Increase `itk::MultiLabelSTAPLEImageFilter` coverage

---

Modules/IO/GE/src/itkGE5ImageIO.cxx

`GE5ImageIO::ReadHeader` appeared to have unreachable code in `if`-clauses like this:
buffer = new char[N];
if (buffer == nullptr)
{
f.close();
itkExceptionMacro("GE5ImageIO:Unable to allocate memory...!");
}
This pull request proposes to remove those unreachable lines of code, and replace locally declared raw pointers by `unique_ptr`, in GE5ImageIO.

Remove unreachable code from GE5ImageIO and use unique_ptr

---

Modules/Filtering/ImageCompare/test/CMakeLists.txt

Fix `itk::STAPLEImageFilter` test argument order.
Set the `maximumIterations` and `confidenceWeight` arguments to the
wrong order in commit aa76dfb, which made it so that `maximumIterations`
was being set to 0, which in turn caused the code coverage to drop.

BUG: Fix `itk::STAPLEImageFilter` test argument order

---

Modules/Core/Common/src/itkObject.cxx

`SubjectImplementation::InvokeEventRecursion` (an internal helper function of
`Object::InvokeEvent`) tried to "find" a *possibly* dangling pointer `o` in its
list of `Observer` pointers.
It appears more secure to check if an observer is still in the list by
comparing its tag to the tags of the other observers.
----
FYI A dangling `Observer` pointer `o` actually occurs when running the test function `testDeleteObserverDuringEvent()` from [CommandObserverObjectTest](https://github.com/InsightSoftwareConsortium/ITK/blob/2f2b29cbbe3fe91474933e0194db8d581d5b3247/Modules/Core/Common/test/itkCommandObserverObjectTest.cxx), while executing the following line of code:
https://github.com/InsightSoftwareConsortium/ITK/blob/2f2b29cbbe3fe91474933e0194db8d581d5b3247/Modules/Core/Common/test/itkCommandOb …

BUG: `Object::InvokeEvent` should not use a dangling Observer pointer

---

Modules/Core/Common/src/itkObject.cxx

`SubjectImplementation` is an internal (hidden) helper class of `itk::Object`, which only uses the non-const overload of `SubjectImplementation::AddObserver`.
Removing this unused overload reduces maintenance.
----
Ubuntu2004 Coverage 8 appears to indicate that indeed, the `const` overload of `SubjectImplementation::AddObserver` was not covered: https://open.cdash.org/viewCoverageFile.php?buildid=8162114&fileid=52190897 (line 143-150) @jhlegarreta Can you please confirm that, Jon?

STYLE: Remove `const` overload of `SubjectImplementation::AddObserver`

---

Modules/Filtering/ImageCompare/test/CMakeLists.txt
Modules/Filtering/ImageCompare/test/itkImageFileReaderIOToRequestedRegionMismatchTest.cxx

- ENH: Test `itk::ImageFileReader` image IO to requested region mismatch
- STYLE: Break `ImageCompare` module test command into multiple lines

ENH: Test `itk::ImageFileReader` image IO to requested region mismatch

---

Modules/Core/Common/include/itkObject.h
Modules/Core/Common/src/itkObject.cxx

- Declared the observers of `itk::Object` as list of `Observer` objects (instead of a list of raw pointers).
- Declared both `m_SubjectImplementation` and `m_MetaDataDictionary` as an `std::unique_ptr`.
- Declared `Observer::m_Event` as unique_ptr

Use `unique_ptr` internally in the implementation of `itk::Object`

---

Modules/Core/Common/include/itkObject.h

Worked around a GCC bug which produced the following error:
> unique_ptr.h:79:16: error: invalid application of ‘sizeof’ to incomplete type
The issue https://github.com/InsightSoftwareConsortium/ITK/issues/3643 "Compilation fails with GCC 8.4." was reported by Max Aehle  (@maxaehle). The GCC bug appears to be fixed with GCC 9.2.
The workaround (removing "`{ nullptr }`") was also suggested by Max Aehle.
Closes #3643

COMP: Work around GCC <= 9.1 "error: invalid application of ‘sizeof’..."

---

Modules/ThirdParty/NIFTI/src/nifti/niftilib/nifti1.h
Modules/ThirdParty/NIFTI/src/nifti/niftilib/nifti1_io.c
Modules/ThirdParty/NIFTI/src/nifti/niftilib/nifti1_io.h
Modules/ThirdParty/NIFTI/src/nifti/niftilib/nifti1_tool.c
Modules/ThirdParty/NIFTI/src/nifti/niftilib/nifti1_tool.h
Modules/ThirdParty/NIFTI/src/nifti/niftilib/nifti_tester001.c
Modules/ThirdParty/NIFTI/src/nifti/znzlib/znzlib.h

---
Update nifti clib:
```
8f7ecce Fix reading subregions of large files
36e8df3 Renamed private _PrintTest to PrintTest_eng
a2d25c4 Removed use of __DATE__ to allow for reproducible builds
53d64db Fixed some -Wconditional-uninitialized with an assert
2012da3 Fixed all -Wunused-macros warnings
4e800b8 Fixed all but one -Wmissing-prototypes warnings
d05a71e Fixed all clang -Wreserved-id-macro warnings
376161c Removed used _NIFTI_TOOL_C_ defines to fix -Wreserved-id-macro some warnings
```
Fixes  #3625

Update nifti clib 2022-09-19 (8f7ecce7)

---

Modules/Core/Common/include/itkSingletonMacro.h
Modules/Core/Common/src/itkObjectFactoryBase.cxx

The lifetime of lambda's passed as argument to the function `Singleton<T>` does not need to be extended beyond the function call, as these arguments directly get converted to `std::function` objects.

STYLE: Declare lambda's created for Singleton `const`, but non-static

---

Modules/Core/Common/include/itkObject.h
Modules/Core/Common/src/itkObject.cxx

- Moved `Observer` into an unnamed namespace
- Made `SubjectImplementation` a private nested type of itk::Object
- Made protected `SubjectImplementation` members private
- Made iteration over observers "const"

Make `itk::Object` implementation more private, more hidden, more const

---

Modules/Core/Common/src/itkObjectFactoryBase.cxx
Modules/Core/Mesh/include/itkConnectedRegionsMeshFilter.hxx
Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx

Method local variables should not have `m_` prefix.  That prefix is reserved for class member variables.

STYLE: Method local variables should not have `m_` prefix

---

Modules/Filtering/BiasCorrection/include/itkMRASlabIdentifier.h
Modules/IO/MeshOBJ/include/itkOBJMeshIO.h
Modules/IO/NIFTI/include/itkNiftiImageIO.h

Fix miscellaneous Doxygen warnings.
Fixes:
```
Modules/Filtering/BiasCorrection/include/itkMRASlabIdentifier.h:161:
warning:
Reached end of file while still inside a (nested) comment.
Nesting level 1 (probable line reference: 27)
Modules/Filtering/BiasCorrection/include/itkMRASlabIdentifier.h:64:
warning:
End of comment block while inside formula.
```
and
```
Modules/IO/NIFTI/include/itkNiftiImageIO.h:162:
warning:
argument 'fileName' of command @param is not found in the argument list of itk::NiftiImageIO::CanWriteFile(const char *FileNameToWrite)
Modules/IO/NIFTI/include/itkNiftiImageIO.h:168:
warning:
The following parameters of itk::NiftiImageIO::CanWriteFile(const char *FileNameToWrite) are not documented:
parameter 'FileNameToWrite'
Modules/IO/NIFTI/include/itkNiftiImageIO.h:162: …
```

DOC: Fix miscellaneous Doxygen warnings

---

.github/ISSUE_TEMPLATE/documentation_impact_report.md
.github/labeler.yml

Fix the `Documentation`PR title identification: avoid having two entries for the `area:Documentation` label, and use the newly created `type:Documentation` for the PR title regex.

ENH: Fix the `Documentation` PR title identification

---

Modules/Filtering/ImageCompare/include/itkSTAPLEImageFilter.h

Clamp `STAPLEImageFilter` maximum iterations to avoid setting a 0 value, and thus giving rise dynamic memory defects when querying about non-existing vector indices for the sensitivity and specifity.
Related to commit 5b5d85e.
Fixes #3644.

ENH: Clamp `STAPLEImageFilter` maximum iterations

---

Modules/Core/Common/include/itkObjectFactoryBase.h
Modules/Core/Common/src/itkObjectFactoryBase.cxx

Moved the forward-declaration of both `OverRideMap` and `ObjectFactoryBasePrivate` into the class definition of `ObjectFactoryBase`, as they are just part of the internal private implementation of `ObjectFactoryBase`.
Follow-up to commit 4c0526e4abd40b0157ad05645a8b32aab8d9e733, "STYLE: Make `SubjectImplementation` a private nested type of itk::Object".

STYLE: Make OverRideMap, ObjectFactoryBasePrivate private nested classes

---

Modules/IO/PhilipsREC/src/itkPhilipsRECImageIO.cxx

Fixed a compile error, which appeared when enabling `Module_ITKIOPhilipsREC`:
> itkPhilipsRECImageIO.cxx(390,3): error C3861: 'iff': identifier not found
This obvious typo was introduced with pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3664 commit 2b1b5312fadf1a156882d06dc2e7c6b2a2290044 "STYLE: Remove space between class and member names (follow-up)", and reported by Bradley Lowekamp (@blowekamp).

COMP: Fix typo (compile error) in `PhilipsRECImageIO` constructor

---

CMake/ITKGroups.cmake

Fix ITK class namespace spelling in `Core` group description.

DOC: Fix ITK class namespace spelling in `Core` group description

---

Modules/Core/Common/include/itkObject.h
Modules/Core/Common/src/itkObject.cxx

Removed the `const_cast` from the const overload of `Object::AddObserver`, and removed duplicate code by having the non-const overload call the const overload.
Following C++ Core Guidelines, September 23, 2022, "Don’t cast away const", at http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es50-dont-cast-away-const
Added a note on why the non-const overload is still there.
----
This pull request partially supersedes #3636 "STYLE: Remove non-const overload of `Object::AddObserver`, add `mutable`" (but it does not remove the overload).

STYLE: Remove const_cast, make `Object::m_SubjectImplementation` mutable

---

Modules/Segmentation/Classifiers/include/itkImageKmeansModelEstimator.hxx
Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.hxx

Might slightly speedup the code.
Note that those two local buffers were already there before `make_unique_for_overwrite` was introduced.

Remove unused local dynamically allocated `double[]` buffers from Segmentation module 

---

Modules/Core/Common/src/itkImageIORegion.cxx
Modules/Core/Common/test/itkImageIORegionGTest.cxx

This commit ensures that `ImageIORegion::IsInside` returns false whenever its argument is an `ImageIORegion` that contains no pixels at all.
Following the adjustment of `itk::ImageRegion::IsInside(const Self &)` from pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3110 commit 1295d239397f111bd008c1093d9ddc5a3867669a
"BUG: `region.IsInside(zeroSizedRegion)` should always return false", which was included with ITK v5.3rc04
See also "What bool value should `imageRegion.IsInside(zeroSizedRegion)` return?" at https://discourse.itk.org/t/what-bool-value-should-imageregion-isinside-zerosizedregion-return/4734

BUG: ImageIORegion::IsInside should return false for a zero-sized region

---

Modules/Core/Common/include/itkSymmetricEigenAnalysis.hxx
Modules/Core/Mesh/include/itkTriangleMeshCurvatureCalculator.hxx
Modules/Numerics/Statistics/include/itkHistogramToTextureFeaturesFilter.hxx
Modules/Numerics/Statistics/include/itkScalarImageToRunLengthFeaturesFilter.hxx
Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.hxx

Replaced `make_unique_for_overwrite<T[]>` calls with `std::make_unique<T[]>`, whenever the elements of the allocated buffer need to be zero-initialized. Removed "post-initializations" which did assign zero to these elements.

STYLE: Use `std::make_unique<T[]>` to zero-initialize the elements

---

Modules/Filtering/ImageGrid/include/itkBSplineScatteredDataPointSetToImageFilter.h
Modules/Filtering/ImageGrid/include/itkBSplineScatteredDataPointSetToImageFilter.hxx

H/t to @NitramNimod and @chrisadamsonmcri for pointing out the computational bottleneck that precipitated this contribution.  Further discussion is [here.](https://github.com/ANTsX/ANTs/issues/1017)
Two improvements:
1) Eliminate unnecessary calls to UpdatePointSet()
2) Multi-thread UpdatePointSet() (Now called ThreadedGenerateDataForUpdatePointSetValues()).
For single-level approximation, no calls to UpdatePointSet are needed.  This effects well-used code (e.g., N4 bias field correction) so I want to be cautious in submitting but the computational improvements should be relatively significant.  For @thewtex , this would affect your B-spline image gradient module so please take a look if you have time.

PERF: Remove unnecessary computations and parallelize function.

---

Modules/ThirdParty/VNL/CMakeLists.txt

When ITK specifies removing support for LEGACY code uses, then VXL should also remove support.
This patch sets "VXL_USE_HISTORICAL_IMPLICIT_CONVERSIONS=OFF" when ITK_LEGACY_REMOVE or ITK_LEGACY_FUTURE_REMOVE is requested.

COMP: Remove deprecated uses of vxl for LEGACY ITK

---

Modules/Core/Common/test/CMakeLists.txt
Modules/Core/Common/test/itkFloatingPointExceptionsTest.cxx

"OverFlow" and "UnderFlow" should not have capital "F" characters.

STYLE: Change Over/UnderFlow to Over/Underflow

---

Modules/Core/Common/include/itkObjectFactoryBase.h
Modules/Core/Common/src/itkObjectFactoryBase.cxx

The uppercase 'R' in the identifier `OverRideMap` appears unusual. Note that this nested type is just a private implementation detail, so this change does not affect of the API.
Also removed the internal type alias `StringOverMap`, which was only used once.

STYLE: Rename nested ObjectFactoryBase type OverRideMap to `OverrideMap`

---

Modules/IO/ImageBase/src/itkImageIOBase.cxx

Removed _itkWarningMacro_ just before _itkExceptionMacro_ with exactly the same messages.
Looks rather unusual and highly likely not useful.

STYLE: removed duplicated messages

---

CMakeLists.txt

Changed _ITKv5_ to _ITKv6_ in cmake comment for ITK_FUTURE_LEGACY_REMOVE.

DOC: updated comment for ITK_FUTURE_LEGACY_REMOVE

---

Modules/Filtering/ImageGrid/include/itkBSplineScatteredDataPointSetToImageFilter.h
Modules/Filtering/ImageGrid/include/itkBSplineScatteredDataPointSetToImageFilter.hxx

Follow-up to the [related pull-request](https://github.com/InsightSoftwareConsortium/ITK/pull/3681).  This corrects a long-standing minor bug (minor in the sense that it was probably not encountered much, if at all with normal usage).  Instead of overwriting the input point data in the case of multi-level fitting, this copies the input data for processing.

BUG:  Copy input data instead of overwriting.

---

Modules/Core/Common/include/itkDomainThreader.hxx
Modules/Core/Common/test/itkMemoryProbesCollecterBaseTest.cxx
Modules/Filtering/FFT/include/itkVnlComplexToComplexFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkVnlForwardFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkVnlHalfHermitianToRealInverseFFTImageFilter.hxx
Modules/Filtering/FFT/include/itkVnlInverseFFTImageFilter.hxx
Modules/Filtering/ImageGrid/test/itkResampleImageTest2Streaming.cxx
Modules/Filtering/LabelMap/test/itkStatisticsRelabelLabelMapFilterTest1.cxx
Modules/Filtering/Thresholding/test/itkRenyiEntropyMaskedThresholdImageFilterTest.cxx
Modules/IO/CSV/src/itkCSVFileReaderBase.cxx
Modules/IO/CSV/test/itkCSVArray2DFileReaderTest.cxx
Modules/IO/CSV/test/itkCSVNumericObjectFileWriterTest.cxx
Modules/IO/ImageBase/include/itkImageFileReader.hxx
Modules/IO/ImageBase/include/itkImageFileWriter.hxx
Modules/IO/TIFF/test/itkTIFFImageIOCompressionTest.cxx
Modules/Numerics/Statistics/test/itkMahalanobisDistanceMetricTest.cxx
Modules/Segmentation/Classifiers/test/itkImageClassifierFilterTest.cxx
Modules/Segmentation/Classifiers/test/itkSampleClassifierFilterTest1.cxx
Modules/Segmentation/Classifiers/test/itkSampleClassifierFilterTest3.cxx
Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.hxx

Avoided unintended concatenations, like "PartitionDomainreturned", "hasonly", "regionRequested", "regionPaste", and "sparsefield", which appeared in exception and warning messages, when inserting multiple literal strings consecutively into an output stream. Separated those concatenated words either by a single space character, or by a period _and_ a space (whichever is appropriate).

BUG: Remove unintended `<<` concatenation of literal words in messages and test output

---

Modules/Core/Common/include/itkNeighborhoodAllocator.h
Modules/Filtering/Path/include/itkOrthogonalSwath2DPathFilter.hxx
Modules/IO/MRC/src/itkMRCImageIO.cxx
Modules/Registration/Common/include/itkImageToImageMetric.hxx

Replaced `\.reset\(new (\w+)\[(.+)\]\);` with ` = make_unique_for_overwrite<$1[]>($2);`, using regular expressions in Visual Studio 2019.
Following C++ Core Guidelines, September 23, 2022, "Avoid calling `new` and `delete` explicitly", from http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-newdelete

STYLE: Replace `reset(new T[n])` with make_unique_for_overwrite<T[]>(n)

---

Modules/IO/NIFTI/test/CMakeLists.txt
Modules/IO/NIFTI/test/itkNiftiLargeImageRegionReadTest.cxx

Add a test to check reading large `NIfTI` image subregions.
Resolves #3625.

ENH: Add a test to check reading large `NIfTI` image subregions

---

Modules/Numerics/Statistics/include/itkDistanceMetric.h
Modules/Numerics/Statistics/include/itkMeasurementVectorTraits.h
Modules/Numerics/Statistics/include/itkMembershipFunctionBase.h
Modules/Numerics/Statistics/include/itkSample.h

Fix uninitialized vector warnings.
Fixes:
```
Modules/Numerics/Statistics/include/itkDistanceMetric.h:101:45:
warning: 'm' may be used uninitialized [-Wmaybe-uninitialized]
```
and
```
Modules/Numerics/Statistics/include/itkMeasurementVectorTraits.h:70:72:
warning: 'm' may be used uninitialized [-Wmaybe-uninitialized]
```
and
```
Modules/Numerics/Statistics/include/itkMembershipFunctionBase.h:97:45:
warning: 'm' may be used uninitialized [-Wmaybe-uninitialized]
```
and
```
Modules/Numerics/Statistics/include/itkSample.h:121:45:
warning: 'm' may be used uninitialized [-Wmaybe-uninitialized]
```
https://open.cdash.org/viewBuildError.php?type=1&buildid=8240358

COMP: Fix uninitialized vector warnings

---

.github/FUNDING.yml
README.md

NumFOCUS has moved to Open Collective to handle donations / accounts.

DOC: Update donation link to Open Collective

---

Modules/Numerics/Statistics/include/itkDistanceMetric.h
Modules/Numerics/Statistics/include/itkDistanceMetric.hxx
Modules/Numerics/Statistics/include/itkImageToListSampleFilter.hxx
Modules/Numerics/Statistics/include/itkMembershipFunctionBase.h
Modules/Numerics/Statistics/include/itkSample.h

It appears unnecessary to use a local variable as function argument of
`IsResizable(const TVectorType &)`. In three cases, such a local variable
could simply be removed.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3707 commit d81a02cc23e08a4ddaa3a3c4468f2093cbf9cf5a "COMP: Fix uninitialized vector warnings" by Jon Haitz Legarreta Gorroño (@jhlegarreta).

STYLE: Use `{}` as `MeasurementVectorTraits::IsResizable` argument

---

Modules/Core/Common/include/itkVectorNeighborhoodInnerProduct.hxx

Moved the retrieval of neighbor pixels out of the inner `for` loops of both `VectorNeighborhoodInnerProduct<TImage>::operator()` overloads. A reduction of more than 8 % of the duration of `itkSyNPointSetRegistrationTest` was observed, running a Visual Studio 2019 Release build.
Used `{}` to zero-initialize the local `sum` variables, instead of having a `for` loop to assign zero to each element.
Initialized `o_it` directly at its begin value, avoiding an extra assignment.

`VectorNeighborhoodInnerProduct`: Move pixel retrieval out of its inner loops and zero-initialize its `sum` by `{}`

---

Modules/Registration/Common/test/itkKullbackLeiblerCompareHistogramImageToImageMetricTest.cxx

The `KullbackLeiblerCompareHistogramImageToImageMetric` test appeared to be the most time consuming test of ITK's test framework, taking more than 9 seconds on Windows, on GitHub Actions. Originally it had test images of 100 x 100 pixels, with commit de0f47aee76c3ee69504c5663ba284e32ba03e44 "Tests for the CompareHistogramImageToImageMetric class and the KullbackLieblerCompareHistogramImageToImageMetric class", Luis Ibanez (@luisibanez), 29 Dec 2003. However, the same code coverage may be achieved with images of 16 x 16.
---
Current top 25 of most time consuming tests (on GitHub Actions running Windows): https://github.com/InsightSoftwareConsortium/ITK/pull/3702#issuecomment-1295786873

PERF: Use smaller (16x16) images in KullbackLeibler metric test

---

Modules/Core/Common/include/itkImage.hxx
Modules/Filtering/ImageCompose/include/itkComposeImageFilter.hxx
Modules/Numerics/Statistics/include/itkCovarianceSampleFilter.hxx
Modules/Numerics/Statistics/include/itkDistanceMetric.h
Modules/Numerics/Statistics/include/itkDistanceMetric.hxx
Modules/Numerics/Statistics/include/itkImageToListSampleFilter.hxx
Modules/Numerics/Statistics/include/itkMeanSampleFilter.hxx
Modules/Numerics/Statistics/include/itkMeasurementVectorTraits.h
Modules/Numerics/Statistics/include/itkMembershipFunctionBase.h
Modules/Numerics/Statistics/include/itkSample.h
Modules/Numerics/Statistics/include/itkStandardDeviationPerComponentSampleFilter.hxx

It appears unnecessary to use a local variable as function argument of `NumericTraits::GetLength(const T &)`, when this local variable is a "dummy", that is only just default-initialized, or initialized by `T()` or `{}`.
This commit removes such local "dummy" variables, and passes `{}` to those `NumericTraits::GetLength` calls that had such a dummy as argument.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3710 commit be8cb4233b6510f436333213b7cac7c9ab7c07a7
"STYLE: Use `{}` as `MeasurementVectorTraits::IsResizable` argument"

STYLE: Use `{}` instead of dummy as `NumericTraits::GetLength` argument

---

Testing/ContinuousIntegration/AzurePipelinesBatch.yml
Testing/ContinuousIntegration/AzurePipelinesLinux.yml
Testing/ContinuousIntegration/AzurePipelinesMacOS.yml
Testing/ContinuousIntegration/AzurePipelinesWindows.yml

Pin Python version in non-Python Azure pipelines so that the required Python package versions used match those used in the Azure pipelines testing the Python wrapping.
Additionally, install the `lxml` Python package explicitly in the
Windows build.
Addresses:
```
File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\anyci\ctest_junit_formatter.py", line 4, in <module>
from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```
raised in:
https://dev.azure.com/itkrobotwindow/ITK.Windows/_build/results?buildId=9122&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=3f67303d-caa6-535b-2055-750b67f1a4bf&l=17

ENH: Pin Python version in non-Python Azure pipelines

---

CMake/ITKModuleExternal.cmake

This commit fixes a regression introduced in 5b09d5466 (`COMP: Allow install lib directory name changes`).
Client project not explicitly setting `CMAKE_INSTALL_LIBDIR` (or including the "GNUInstallDirs" CMake module) would fail to find externally build ITK module.
This commit addresses this by setting `CMAKE_INSTALL_LIBDIR` default value to "lib". This approach is consistent with how the `CMAKE_INSTALL_LIBDIR `default value is set in the top-level `CMakeLists.txt`.
Before this change, there was discrepancy between the value of "/path/to/<module>.cmake" used when configuring the file and the one used when looking up the file following a call to `find_package(ITK COMPONENTS <module>)`.
For example:
```
Location of the configured file: …
```

COMP: Ensure client project can find externally build ITK module

---

Modules/Core/ImageFunction/test/itkBSplineDecompositionImageFilterTest.cxx
Modules/Filtering/ImageGrid/test/itkResampleImageTest2Streaming.cxx
Modules/Filtering/Thresholding/test/itkOtsuThresholdCalculatorVersusOtsuMultipleThresholdsCalculatorTest.cxx
Modules/IO/BMP/test/itkBMPImageIOTest3.cxx
Modules/IO/BMP/test/itkBMPImageIOTest4.cxx
Modules/IO/BMP/test/itkBMPImageIOTest5.cxx
Modules/Numerics/Statistics/test/itkCovarianceSampleFilterTest.cxx
Modules/Numerics/Statistics/test/itkDenseFrequencyContainer2Test.cxx
Modules/Numerics/Statistics/test/itkDistanceToCentroidMembershipFunctionTest.cxx
Modules/Numerics/Statistics/test/itkImageToListSampleAdaptorTest.cxx
Modules/Numerics/Statistics/test/itkImageToListSampleFilterTest.cxx
Modules/Numerics/Statistics/test/itkJointDomainImageToListSampleAdaptorTest.cxx
Modules/Numerics/Statistics/test/itkListSampleTest.cxx
Modules/Numerics/Statistics/test/itkMeanSampleFilterTest.cxx
Modules/Numerics/Statistics/test/itkMembershipFunctionBaseTest.cxx
Modules/Numerics/Statistics/test/itkPointSetToListSampleAdaptorTest.cxx
Modules/Numerics/Statistics/test/itkSampleTest.cxx
Modules/Numerics/Statistics/test/itkScalarImageToCooccurrenceListSampleFilterTest.cxx
Modules/Numerics/Statistics/test/itkScalarImageToCooccurrenceMatrixFilterTest.cxx
Modules/Numerics/Statistics/test/itkScalarImageToTextureFeaturesFilterTest.cxx
Modules/Numerics/Statistics/test/itkStandardDeviationPerComponentSampleFilterTest.cxx
Modules/Numerics/Statistics/test/itkSubsampleTest.cxx
Modules/Numerics/Statistics/test/itkWeightedCovarianceSampleFilterTest.cxx
Modules/Numerics/Statistics/test/itkWeightedCovarianceSampleFilterTest2.cxx
Modules/Numerics/Statistics/test/itkWeightedMeanSampleFilterTest.cxx

Follow-up to pull request #3713 "Remove backslash (+ indent) from string literals", but now applied to tests (`itk*Test*.cxx` files).
Removes unwanted (unintentional) spaces from test output messages, which were caused by an indentation after a backslash continuation character.

Remove backslash (+ indent) from string literals in tests

---

Modules/Filtering/ImageIntensity/test/CMakeLists.txt
Modules/Filtering/ImageIntensity/test/itkRoundImageFilterTest.cxx

Increase coverage for `itk::RoundImageFilter`:
- Exercise basic object methods using the `ITK_EXERCISE_BASIC_OBJECT_METHODS` macro.
- Test the output of the filter.

ENH: Increase coverage for `itk::RoundImageFilter`

---

Documentation/Maintenance/Release.md

Adds language to clarify the difference between ITK wheel archives which contain loadable Python packages and ITK build archives which cache build artifacts for use in subsequent module builds.
Based on discussion in https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/216

DOC: Clarify Python release documentation

---

Wrapping/macro_files/itk_auto_load_submodules.cmake

_castxml_depends already adds this dependency per:
https://github.com/InsightSoftwareConsortium/ITK/blob/ca9917d1501b56cdf4ab49402cc5cacd7377a5df/Wrapping/macro_files/itk_auto_load_submodules.cmake#L12-L15

COMP: Do not depend on castxml target when using system version

---

Modules/Bridge/NumPy/wrapping/PyBuffer.i.in
Wrapping/Generators/Python/itk/support/extras.py

There's a bit of a foot-gun in GetImageViewFromArray, where if you pass it a non-contiguous array, it makes a contiguous copy of that array and returns an image view of that copy. The copy is then stored in the .base member of the returned image, to keep it from being garbage collected. This behavior is used by GetImageFromArray, which should be able to get images from non-contiguous arrays. 
However, the .base member can be lost if the returned image is passed to, for example, a SetTransform method in itk, and then no longer referenced from python. This can cause surprise segfaults.
This pull request adds a warning to GetImageViewFromArray that is displayed when it is not actually returning a view, which can be suppressed with a keyword argument. 
Another possibility would be to move the …

DOC: warning for calling GetImageViewFromArray on non-contiguous array

---

Modules/Bridge/NumPy/wrapping/PyBuffer.i.init
Wrapping/Generators/Python/PyBase/pyBase.i
Wrapping/Generators/Python/Tests/extras.py
Wrapping/Generators/Python/itk/support/extras.py
Wrapping/Generators/Python/itk/support/types.py

Updates Python wrappings and extras to primarily use `np.dtype` objects for mapping from NumPy to ITK types.
Follows discussion in https://github.com/SimpleITK/SimpleITK/issues/1685 and addresses
https://github.com/InsightSoftwareConsortium/ITK/issues/3544 .

BUG: Use NumPy `dtype`s for type mapping

---

Modules/Core/Common/include/itkProcessObject.h

COMP: Add includes for uint32_t in wrapping

---

Modules/Core/Common/test/CMakeLists.txt

Use unique names for `itk::SobelOperator` test output files: using the same name for output files across different tests is likely to cause access conflicts (e.g. if tests run in parallel).
Fixes:
```
Test finished.
Exception detected while reading
/tmp/bld/ITK-build/Testing/Temporary/itkSobelOperatorImageConvolutionHorizTest.png :
ITK ERROR: PNGImageIO(0x55ec6cd3c660): Error while reading file:
/tmp/bld/ITK-build/Testing/Temporary/itkSobelOperatorImageConvolutionHorizTest.png
```
reported for example in:
https://open.cdash.org/test/864373640

BUG: Use unique names for `itk::SobelOperator` test output files

---

Modules/IO/NIFTI/test/itkNiftiLargeImageRegionReadTest.cxx

Significantly reduce memory usage of the test.

ENH: less memory pressure in itkNiftiLargeImageRegionReadTest

---

Wrapping/Generators/Python/itk/support/extras.py

Without this, a file-system-backed zarr container
is attempted to be read as a DICOM directory:
```py
image2 = itk.imread("C:/Dev/ITKIOOME-py/Testing/Temporary/cthead1py.zarr", imageio=imageio)
```
```log
WARNING: In C:\Dev\ITK-git\Modules\IO\GDCM\src\itkGDCMSeriesFileNames.cxx, line 100 GDCMSeriesFileNames (0000027927F2B7E0): No Series were found
File "<stdin>", line 1, in <module>
File "C:\Dev\ITK-py\Wrapping\Generators\Python\itk\support\extras.py", line 1194, in imread
raise FileNotFoundError(f"no DICOMs in: {filename}.")
FileNotFoundError: no DICOMs in: C:/Dev/ITKIOOME-py/Testing/Temporary/cthead1py.zarr.
```

BUG: use DICOM for reading directories only if imageio is not specified

---

Modules/Core/Common/include/itkFixedArray.h
Modules/Core/Common/include/itkMacro.h
Modules/Core/Common/test/itkMatrixGTest.cxx

GCC 4 support was dropped with pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2563 commit 4e812d60743a3ed7c09647e7f3f0e8498583c2da
"COMP: Require compiler versions that support C++14", June 3, 2021

STYLE: Remove obsolete `__GNUC__` macro checks for GCC version 4

---

Modules/Core/Mesh/test/itkMeshTest.cxx

Fixed memory leak in _itkMeshTest_
https://open.cdash.org/viewDynamicAnalysisFile.php?id=9809009
Re-using of the mesh after this [line](https://github.com/InsightSoftwareConsortium/ITK/blob/ce57f309f4f4142b80367fd89a88f8dac9d6943a/Modules/Core/Mesh/test/itkMeshTest.cxx#L267) caused the memory leak. The cells data was not deleted.
The change is minimal even if it is difficult to see (I split into 2 local scopes, this shifted most lines, use "hide whitespace").

BUG: fixed memory leak in itkMeshTest

---

Wrapping/Generators/CastXML/CMakeLists.txt
Wrapping/Generators/SwigInterface/CMakeLists.txt

Set `DOWNLOAD_EXTRACT_TIMESTAMP` to `TRUE`: the timestamps of the
extracted files will reflect the timestamps in the archive.
Configure/autoconf based projects like SWIG and PCRE have timestamped
files for their auto configuration dependencies. Thus, they depend on
the timestamps of the extracted files, and the external projects require
setting `DOWNLOAD_EXTRACT_TIMESTAMP` to `TRUE` to build robustly.
Set the `CMP0135` policy to `NEW` for the CastXML CMake-based project.
Suppresses CMake warnings in wrapping modules.
Fixes:
```
CMake Warning (dev) at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3074 (message):
The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
not set.  The policy's OLD behavior will be used.  When using a URL
download, the timestamps …
```

COMP: Set `DOWNLOAD_EXTRACT_TIMESTAMP` to `TRUE` in wrapping modules

---

Modules/Numerics/Optimizers/include/itkLBFGSBOptimizer.h
Modules/Numerics/Optimizers/include/itkSingleValuedNonLinearVnlOptimizer.h
Modules/Numerics/Optimizersv4/include/itkLBFGSBOptimizerv4.h
Modules/Numerics/Optimizersv4/include/itkObjectToObjectOptimizerBase.h
Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx

Not all optimizers support scale weights.  The
itkImageRegistrationMethodv4 was unconditionally
setting the scales and causing a confusing warning message to be presented (identified in python, but also present in c++).  Providing an overridable member function that returns the support for weighting scales allow suppression of the warnings.

ENH: Add check if optimizer supports scales

---

Wrapping/Generators/CastXML/CMakeLists.txt
Wrapping/Generators/SwigInterface/CMakeLists.txt

- COMP: Set `DOWNLOAD_EXTRACT_TIMESTAMP` to `TRUE` for Windows wrapping
- DOC: Document the wrapping modules' extraction/archived timestamp flags

COMP: Set `DOWNLOAD_EXTRACT_TIMESTAMP` to `TRUE` for Windows wrapping

---

Wrapping/Generators/CastXML/CMakeLists.txt

Addresses runtime error:
The code execution cannot proceed because zlib1__.dll waws not found.
Reinstall the program may fix this problem.

COMP: Add CastXML binary for Windows 11

---

.github/labeler.yml

Apply the `type:Infrastructure` labeler class when changing the CI config files located in `Testing/ContinuousIntegration`.

ENH: Apply the `type:Infrastructure` label to CI config files

---

Modules/IO/ImageBase/include/itkConvertPixelBuffer.hxx

Removed the four local `diff` variables from ConvertPixelBuffer. These variables appeared unnecessary, after commit f8e3d3b3979529373d6cf1559073c4027c186d34 ("ERR: ++ replaced with +1, +2, etc. to avoid possible compiler problems.", Bill Lorensen (@lorensen), 2002-09-03). Removing them fixed a few Visual Studio 2019 16.11.21 Code Analysis warnings, saying:
> warning C26451: Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2)
Replaced the five `(size_t)inputNumberOfComponents` casts inside ConvertPixelBuffer with `static_cast<size_t>(inputNumberOfComponents)`.

Remove `diff` variables from ConvertPixelBuffer, replace `(size_t)` casts

---

Modules/Core/Common/test/itkNumberToStringGTest.cxx

A few small improvements of NumberToStringGTest, triggered by the `NumberToString.DecimalNotationUpTo21Digits` failures reported by @yurivict at issue https://github.com/InsightSoftwareConsortium/ITK/issues/3739 saying:
/disk-samsung/freebsd-ports/science/InsightToolkit/work/ITK-5.2.1/Modules/Core/Common/test/itkNumberToStringGTest.cxx:87: Failure
Expected equality of these values:
numberToString(power_of_ten)
Which is: "100000010000"
'1' + std::string(exponent, '0')
Which is: "100000000000"

NumberToStringGTest: add #include, avoid narrowing conversion pow, mention floating point type on an expect failure 

---

Documentation/ITK5MigrationGuide.md
Modules/Core/Common/include/itkNumericTraits.h
Modules/Core/Common/src/itkNumericTraits.cxx
Modules/Core/Common/test/itkMathTest.cxx
Modules/Core/Common/test/itkNumericTraitsTest.cxx
Modules/Filtering/ImageFrequency/test/itkFrequencyFFTLayoutImageRegionIteratorWithIndexTest.cxx

Example error message:
`M:\Dashboard\ITK\Modules\Core\Common\src\itkNumericTraits.cxx(77,85): warning C4996: 'std::complex<char>::complex': warning STL4037: The effect of instantiating the template std::complex for any type other than float, double, or long double is unspecified. You can define _SILENCE_NONFLOATING_COMPLEX_DEPRECATION_WARNING to suppress this warning. [M:\Dashboard\ITK-build\Modules\Core\Common\src\ITKCommon.vcxproj]`

Fix new warning STL4037 raised by VS2022

---

Modules/Core/Common/src/itkConfigure.h.in

If the argument `-msse2` is used for 32-bits x86 build, then __SSE2__ is defined. This causes ITK_COMPILER_SUPPORTS_SSE2_64 to be set for 32-bits x86.
```
/usr/local/include/ITK-5.3/itkMathDetail.h:317:10: error: use of undeclared identifier '_mm_cvtsd_si64'
return _mm_cvtsd_si64(_mm_set_sd(x));
^
/usr/local/include/ITK-5.3/itkMathDetail.h:326:10: error: use of undeclared identifier '_mm_cvtss_si64'; did you mean '_mm_cvtss_si32'?
return _mm_cvtss_si64(_mm_set_ss(x));
^
/usr/lib/clang/14.0.5/include/xmmintrin.h:1306:1: note: '_mm_cvtss_si32' declared here _mm_cvtss_si32(__m128 __a)
^
2 errors generated.
```
Minimal example:
_CMakeLists.txt:_
```
cmake_minimum_required(VERSION 3.11)
project(TEST)
set(CMAKE_C_FLAGS ${CMAKE_C_FLAGS} " -msse2")
set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} " …
```

BUG: ITK_COMPILER_SUPPORTS_SSE2_64 incorrectly set for 32-bit x86

---

Modules/ThirdParty/ZLIB/src/itkzlib-ng/crc32_braid.c

Port of: https://github.com/zlib-ng/zlib-ng/pull/1371
To address:
```
D:\a\bld\ITK\Modules\ThirdParty\ZLIB\src\itkzlib-ng\crc32_braid.c(128): warning C4311: 'type cast': pointer truncation from 'const uint8_t *' to 'unsigned long'
```
in https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/pull/402

COMP: zlib crc32_braid.c cast to smaller integer type

---

Modules/Core/Common/include/itkMacro.h

The macro definition does not do any floating point comparison.

STYLE: Do not suppress clang "-Wfloat-equal" inside `itkSetObjectMacro`

---

Modules/Core/Common/include/itkHexahedronCell.h
Modules/Core/Common/include/itkLineCell.h
Modules/Core/Common/include/itkQuadraticEdgeCell.h
Modules/Core/Common/include/itkQuadraticTriangleCell.h
Modules/Core/Common/include/itkQuadrilateralCell.h
Modules/Core/Common/include/itkTetrahedronCell.h
Modules/Core/Common/include/itkTriangleCell.h
Modules/Core/Common/include/itkVertexCell.h

@arnaudgelas Do you still remember why you changed TriangleCell::m_PointIds from fixed-size array of 3 elements to resizable std::vector, with commit 8bbb15afa41e14b1cffe2a881a00d41d8e66999c ?

Declare `m_PointIds` of Cell types `std::array`

---

Modules/Filtering/AnisotropicSmoothing/include/itkScalarAnisotropicDiffusionFunction.hxx
Modules/Filtering/AnisotropicSmoothing/include/itkVectorAnisotropicDiffusionFunction.hxx
Modules/Filtering/BinaryMathematicalMorphology/include/itkObjectMorphologyImageFilter.hxx
Modules/Filtering/Convolution/include/itkNormalizedCorrelationImageFilter.hxx
Modules/Filtering/DisplacementField/include/itkDisplacementFieldJacobianDeterminantFilter.hxx
Modules/Filtering/ImageFeature/include/itkBilateralImageFilter.hxx
Modules/Filtering/ImageFeature/include/itkCannyEdgeDetectionImageFilter.hxx
Modules/Filtering/ImageFeature/include/itkSimpleContourExtractorImageFilter.hxx
Modules/Filtering/ImageFeature/include/itkZeroCrossingImageFilter.hxx
Modules/Filtering/ImageFilterBase/include/itkMaskNeighborhoodOperatorImageFilter.hxx
Modules/Filtering/ImageFilterBase/include/itkNeighborhoodOperatorImageFilter.hxx
Modules/Filtering/ImageFilterBase/include/itkNoiseImageFilter.hxx
Modules/Filtering/ImageFilterBase/include/itkVectorNeighborhoodOperatorImageFilter.hxx
Modules/Filtering/ImageGradient/include/itkGradientMagnitudeImageFilter.hxx
Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.hxx
Modules/Filtering/MathematicalMorphology/include/itkGrayscaleGeodesicDilateImageFilter.hxx
Modules/Filtering/MathematicalMorphology/include/itkGrayscaleGeodesicErodeImageFilter.hxx
Modules/Filtering/MathematicalMorphology/include/itkMorphologyImageFilter.hxx
Modules/Filtering/MathematicalMorphology/include/itkReconstructionImageFilter.hxx
Modules/Filtering/Smoothing/include/itkBoxUtilities.h
Modules/Nonunit/Review/include/itkAttributeMorphologyBaseImageFilter.hxx
Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.hxx
Modules/Nonunit/Review/include/itkWarpHarmonicEnergyCalculator.hxx
Modules/Numerics/Statistics/include/itkScalarImageToCooccurrenceListSampleFilter.hxx
Modules/Segmentation/LabelVoting/include/itkBinaryMedianImageFilter.hxx
Modules/Segmentation/LabelVoting/include/itkVotingBinaryHoleFillingImageFilter.hxx
Modules/Segmentation/LabelVoting/include/itkVotingBinaryImageFilter.hxx
Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.hxx
Modules/Segmentation/LevelSets/include/itkSparseFieldLevelSetImageFilter.hxx

Instead of default-initializing those `faceList` variables and assigning the `ImageBoundaryFacesCalculator` result afterwards.
Following C++ Core Guidelines, September 23, 2022, "Don’t introduce a variable (or constant) before you need to use it" and "Don’t declare a variable until you have a value to initialize it with", http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines

STYLE: Initialize `faceList` directly by ImageBoundaryFacesCalculator

---

Wrapping/Generators/CastXML/CMakeLists.txt

Also required, as reported by Simon Rit.
xref:
- https://github.com/CastXML/CastXMLSuperbuild/issues/50
- https://github.com/InsightSoftwareConsortium/ITK/pull/3767
Co-authored-by: Simon Rit <simon.rit@creatis.insa-lyon.fr>

COMP: Use newer CastXML binary for latest versions of Windows 10

---

Modules/Core/Common/include/itkHexahedronCell.hxx
Modules/Core/Common/include/itkLineCell.hxx
Modules/Core/Common/include/itkPolyLineCell.hxx
Modules/Core/Common/include/itkPolygonCell.hxx
Modules/Core/Common/include/itkQuadraticEdgeCell.hxx
Modules/Core/Common/include/itkQuadraticTriangleCell.hxx
Modules/Core/Common/include/itkQuadrilateralCell.hxx
Modules/Core/Common/include/itkTetrahedronCell.hxx
Modules/Core/Common/include/itkTriangleCell.hxx
Modules/Core/Common/include/itkVertexCell.hxx

Replaced manual `for` loops inside the `SetPointIds(PointIdConstIterator)` member functions of ten "Cel" types by equivalent `std::copy_n` calls. Addresses a few warnings from Clang Tidy (LLVM 15.0.4), saying:
> warning: use range-based for loop instead [modernize-loop-convert]
Note that in these cases, using `std::copy_n` appears even better than using range-based `for` loops!

STYLE: Replace `for` loops SetPointIds(PointIdConstIterator) by copy_n

---

Documentation/Doxygen/DoxygenFooter.html

Put all link content on a single line and reduce vertical space usage.

DOC: Improve doxygen footer formatting

---

Testing/ContinuousIntegration/AzurePipelinesBatch.yml
Testing/ContinuousIntegration/AzurePipelinesLinux.yml
Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml
Testing/ContinuousIntegration/AzurePipelinesMacOS.yml
Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
Testing/ContinuousIntegration/AzurePipelinesWindows.yml
Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml

Update the available testing data following the 5.3.0 release.

ENH: Bump Azure Testing ExternalDataVersion to 5.3.0

---

Documentation/Doxygen/DoxygenFooter.html

DOC: Add link to 5.3 documentation in Doxygen footer

---

Modules/Core/Common/include/itkPolygonCell.hxx
Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshPolygonCell.h
Modules/Filtering/ImageFeature/include/itkZeroCrossingImageFilter.hxx
Modules/IO/TransformBase/src/itkTransformFileWriterSpecializations.cxx
Modules/Numerics/Statistics/test/itkMaximumRatioDecisionRuleTest.cxx
Modules/Segmentation/RegionGrowing/include/itkIsolatedConnectedImageFilter.hxx

The expression `x.front()` appears slightly more readable in these cases, because it does not have the `*` at the beginning.

STYLE: Replace `*x.begin()` with `x.front()`

---

Modules/Core/Common/include/itkImageBufferRange.h

PixelReferenceWrapper is itself already private, nested inside QualifiedIterator, which is private as well, nested inside ImageBufferRange.
Fixed a LLVM 15.04 clang-tidy warning:
> member variable 'm_Pixel' has public visibility [misc-non-private-member-variables-in-classes]

STYLE: Make data of PixelReferenceWrapper (in ImageBufferRange) private

---

Modules/Bridge/VTK/include/itkVTKImageImport.h
Modules/Bridge/VTK/include/itkVTKImageImport.hxx
Modules/Core/Common/include/itkCommand.h

Using `nullptr` as default-member-initializer of all their internal pointers.
Following C++ Core Guidelines, September 23, 2022, "Prefer in-class initializers to member initializers in constructors for constant initializers", https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-in-class-initializer

STYLE: In-class default-member-initialization in Command derived classes and VTKImageImport 

---

Modules/ThirdParty/VNL/src/vxl/vcl/tests/test_include.cxx
Modules/ThirdParty/VNL/src/vxl/vcl/vcl_deprecated.cxx

https://github.com/vxl/vxl.git
at commit 8169cc7697c258fd820ab4b25d13a3e98f93bb99 (master)
Aimed at fixing `CL : warning : vcl_deprecated.h, and it's associated VXL_WARN_DEPRECATED functions should be replaced with vcl_compiler.h and VXL_DEPRECATED_MSG variants. [M:\Dashboard\ITK-build\Modules\ThirdParty\VNL\src\vxl\vcl\itkvcl.vcxproj]`, see [dashboard](https://open.cdash.org/viewBuildError.php?type=1&buildid=8360676).

VXL 2022-12-23 (8169cc76)

---

Modules/ThirdParty/TBB/CMakeLists.txt
Modules/ThirdParty/TBB/itk-module-init.cmake

```
CMake Error at /Users/johnsonhj/src/BT-release/BRAINSTools-Release-5.7.0/lib/cmake/TBB/TBBTargets.cmake:61 (set_target_properties):
The link interface of target TBB::tbb contains:
Threads::Threads
but the target was not found.
```
In many builds "find_package(Threads)" is included from other third party libraries.  When requesting TBB, Threads should unconditionally be found and included.

COMP: Threads package is required by TBB

---

Modules/Core/Mesh/test/itkParametricSpaceToImageSpaceMeshFilterTest.cxx
Modules/Filtering/MathematicalMorphology/test/itkGrayscaleGeodesicErodeDilateImageFilterTest.cxx
Modules/Numerics/Optimizersv4/test/itkLBFGSBOptimizerv4Test.cxx
Modules/Numerics/Optimizersv4/test/itkPowellOptimizerv4Test.cxx
Modules/Registration/Common/test/itkImageToSpatialObjectRegistrationTest.cxx
Modules/Registration/Metricsv4/test/itkANTSNeighborhoodCorrelationImageToImageMetricv4Test.cxx
Modules/Segmentation/LevelSets/test/itkParallelSparseFieldLevelSetImageFilterTest.cxx

Use the `ITK_TRY_EXPECT_EXCEPTION` and `ITK_TRY_EXPECT_NO_EXCEPTION`
macros in tests in lieu of `try/catch` blocks for the sake of
readability and compactness, and to save typing/avoid boilerplate code.
Remove unnecessary print messages that inform about the method being
called.

STYLE:  Prefer using exception macros in tests

---

Documentation/Maintenance/Release.md
Utilities/Maintenance/DownloadLinksCookieCutter/cookiecutter.json
Utilities/Maintenance/DownloadLinksCookieCutter/{{cookiecutter.output_directory}}/ReleaseDownloadLinks.html

Notes:
- Remove Sphinx Epub, Pdf for simplicity
- Doxygen HTML is now small enough to be hosted on GitHub Releases
- Versioned Doxygen upload process has changed
- Wheel build artifact uploads have changed (more manylinux, macos ARM)

DOC: Release process updates for 5.3.0

---

Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx

Remove immediately modified, unnecessary ivar assignment in class constructor.

PERF: Remove immediately modified ivar assignment

---

Modules/Numerics/Optimizers/src/itkOnePlusOneEvolutionaryOptimizer.cxx
Modules/Numerics/Optimizers/test/itkOnePlusOneEvolutionaryOptimizerTest.cxx
Modules/Numerics/Optimizersv4/test/itkOnePlusOneEvolutionaryOptimizerv4Test.cxx

- BUG: Set ivar to appropriate value when condition is met
- ENH: Increase coverage for `itk::OnePlusOneEvolutionaryOptimizer`
- STYLE: Prefer using exception macros in tests
- STYLE: Remove unnecessary test starting message

ENH: Increase coverage for `itk::OnePlusOneEvolutionaryOptimizer`

---

Modules/Filtering/Convolution/test/itkConvolutionImageFilterStreamingTest.cxx

Fix missing initialization braces warning in Convolution test.
Fixes:
```
/Users/builder/externalModules/Filtering/Convolution/test/itkConvolutionImageFilterStreamingTest.cxx:37:30:
warning: suggest braces around initialization of subobject [-Wmissing-braces]
KernelSizeType kernelSize{ 3, 5 };
^~~~
{   }
```
reported in:
https://open.cdash.org/viewBuildError.php?type=1&onlydeltap&buildid=8376254
Left behind in 5834520.

COMP: Fix missing initialization braces warning in Convolution test

---

Modules/Filtering/Smoothing/include/itkRecursiveGaussianImageFilter.h
Modules/Filtering/Smoothing/test/CMakeLists.txt
Modules/Filtering/Smoothing/test/itkRecursiveGaussianImageFilterOnTensorsTest.cxx
Modules/Filtering/Smoothing/test/itkRecursiveGaussianImageFilterOnVectorImageTest.cxx
Modules/Filtering/Smoothing/test/itkRecursiveGaussianImageFilterTest.cxx

- STYLE: Use canonical naming in itkRecursiveGaussianImageFilter tests
- ENH: Add boolean macro to across-scale normalization ivar
- ENH: Increase coverage for `itk::RecursiveGaussianImageFilter`

ENH: Increase coverage for `itk::RecursiveGaussianImageFilter`

---

Modules/Core/Common/include/itkObjectFactoryBase.h
Modules/Core/Common/src/itkObjectFactoryBase.cxx

`OverrideInformation` is just an internal implementation class type of `ObjectFactorBase`, so it is not meant to be part of the interface of ObjectFactorBase.

STYLE: Move ObjectFactorBase `OverrideInformation` to unnamed namespace

---

Modules/Core/Common/include/itkMemoryUsageObserver.h
Modules/Core/Common/include/itkMetaDataObject.h

Fixed Visual Studio 2019 Code Analysis warnings from both `MetaDataObject` and `WindowsMemoryUsageObserver`, saying:
> warning C26495: Variable is uninitialized. Always initialize a member variable (type.6)

Fix MSVC warning C26495: `ZwQuerySystemInformation`, `m_MetaDataObjectValue` uninitialized

---

Modules/Core/Common/include/itkShapedNeighborhoodIterator.h
Modules/Segmentation/LevelSets/include/itkShapePriorSegmentationLevelSetFunction.h

Originally reported by Astha, March 14, 2022, and further discussed at "ITK build Error in itk::ShapedNeighborhoodIterator", https://discourse.itk.org/t/itk-build-error-in-itk-shapedneighborhooditerator/4861

COMP: Fix MSVC error C2516: 'ConstIterator': is not a legal base class

---

Modules/Core/Common/include/itkThreadSupport.h

Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/821 commit 5715d174cd040c8c6e1fdb5060112269f730aee3
"BUG: itkConfigure.h defines ITK_DEFAULT_MAX_THREADS", Hans Johnson (@hjmjohnson) , May 6, 2019.

COMP: Do #include "itkConfigure.h" before using `ITK_USE_WIN32_THREADS`

---

Modules/Core/Common/include/itkImageConstIteratorWithIndex.h
Modules/Core/Common/include/itkImageConstIteratorWithOnlyIndex.h

Fixed VS2019 Code Analysis warnings, saying:
> warning C26495: Variable 'm_PositionIndex' is uninitialized.
> Always initialize a member variable (type.6)
Also added in-class default member initializers to three other data members that were not yet initialized by the default-constructors of ImageConstIteratorWithIndex and ImageConstIteratorWithOnlyIndex.
Note that `ImageConstIteratorWithIndex<TImage>` and `ImageConstIteratorWithIndex<TImage>` are rather "expensive" classes (having a virtual table) and their default-constructors are already non-trivial, so the extra cost of the added initialization appears relatively low.

COMP: Fix MSVC warning C26495: `m_PositionIndex` uninitialized

---

Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx

The second seed (``m_CurrentRandomClass``) was not being initialized which led to non-reproducible behavior.
- [ X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ X] Updated API documentation (or API not changed)

BUG:  Need to initialize both seeds.

---

Modules/Registration/Metricsv4/include/itkANTSNeighborhoodCorrelationImageToImageMetricv4.h

The comment said that sparse sampling was not allowed in itkANTSNeighborhoodCorrelationImageToImageMetricv4:
>  Sparse sampling is not supported by this metric. An exception will be
>  thrown if m_UseSampledPointSet is set. Support for sparse sampling
>  will require a parallel implementation of the neighborhood scanning, which
>  currently caches information as the neighborhood window moves.
This was true when the class was written, but a [sparse sampling implementation](https://github.com/InsightSoftwareConsortium/ITK/commit/651dcd0aecfb76e2c2ddcdd5e8bf38214408ad8f) was later added.

DOC: Remove outdated comment about sparse sampling

---

Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.h
Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx

Fix uninitialized value warning for
`itk::ImageRegistrationMethodv4::m_NumberOfLevels`.
Fixes:
```
UMC ==16463== Conditional jump or move depends on uninitialised value(s)
==16463==    at 0x9BD983: itk::ImageRegistrationMethodv4, itk::Image, itk::DisplacementFieldTransform, itk::Image, itk::PointSet > >::SetNumberOfLevels(unsigned long) (itkImageRegistrationMethodv4.hxx:881)
==16463==    by 0x9C44B6: itk::ImageRegistrationMethodv4, itk::Image, itk::DisplacementFieldTransform, itk::Image, itk::PointSet > >::ImageRegistrationMethodv4() (itkImageRegistrationMethodv4.hxx:103)
==16463==    by 0x9BBFA0: itk::SyNImageRegistrationMethod, itk::Image, itk::DisplacementFieldTransform, itk::Image, itk::PointSet > >::SyNImageRegistrationMethod() (itkSyNImageRegistrationMethod.hxx:41)
==16463==    by …
```

BUG: Fix uninitialized value `ImageRegistrationMethodv4::m_NumberOfLevels`

---

.github/workflows/clang-format-linter.yml

Fix `clang-format` linter workflow action warnings linked to `Node.js`: bump `actions/checkout` to `v3`.
Fixes:
```
Node.js 12 actions are deprecated.
Please update the following actions to use Node.js 16: actions/checkout@v2.
For more information see:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
https://github.com/InsightSoftwareConsortium/ITK/actions/runs/3907066020

ENH: Fix `clang-format` workflow actions warnings linked to `Node.js`

---

Modules/Filtering/DisplacementField/wrapping/test/CMakeLists.txt
Modules/Filtering/DisplacementField/wrapping/test/itkTransformToDisplacementFieldTest.py
Wrapping/Generators/SwigInterface/igenerator.py

Customize implementation since we do not have a image arg that can used to infer the filter type.
Output type is itk.Imgae[itk.Vector[itk.F, output_dim], output_dim] because that is what is wrapped.
Closes #3860

BUG: transform_to_displacement_field_filter type inference

---

Modules/IO/DCMTK/include/itkDCMTKImageIO.h

Fix the symbol exportation macro module name in the `itk::DCMTKImageIO` strongly typed enum class serialization method.

BUG: Fix symbol exportation macro module name in `itk::DCMTKImageIO`

---

Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.h
Modules/IO/GDCM/include/itkGDCMSeriesFileNames.h
Modules/IO/JPEG2000/include/itkJPEG2000ImageIO.h
Modules/IO/MeshGifti/include/itkGiftiMeshIO.h
Modules/IO/NIFTI/include/itkNiftiImageIO.h
Modules/IO/TransformHDF5/include/itkHDF5TransformIO.h
Modules/Nonunit/Review/include/itkAttributeMorphologyBaseImageFilter.h
Modules/Numerics/Optimizers/include/itkAmoebaOptimizer.h
Modules/Numerics/Optimizers/include/itkConjugateGradientOptimizer.h
Modules/Numerics/Optimizers/include/itkLBFGSBOptimizer.h
Modules/Numerics/Optimizers/include/itkLBFGSOptimizer.h
Modules/Numerics/Optimizers/include/itkLevenbergMarquardtOptimizer.h
Modules/Numerics/Optimizersv4/include/itkAmoebaOptimizerv4.h
Modules/Registration/Common/include/itkBlockMatchingImageFilter.h
Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.h
Modules/Registration/Common/include/itkMeanSquaresImageToImageMetric.h
Modules/Registration/Metricsv4/include/itkCorrelationImageToImageMetricv4HelperThreader.h
Modules/Registration/Metricsv4/include/itkJointHistogramMutualInformationGetValueAndDerivativeThreader.h

Errors showed up in (e.g.) https://my.cdash.org/viewBuildError.php?buildid=2273357
Patch 5e2c49f9eb80e78903ce8f9fd2b5952062653cab causes the following errors on GCC 7.4.1:
/usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application of ‘sizeof’ to incomplete type ‘itk::NiftiImageIO::NiftiImageProxy’ /usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application of ‘sizeof’ to incomplete type ‘itk::LBFGSBOptimizerHelper’ /usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application of ‘sizeof’ to incomplete type ‘gdcm::SerieHelper’ /usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application of ‘sizeof’ to incomplete type ‘itk::NiftiImageIO::NiftiImageProxy’ /usr/include/c++/7/bits/unique_ptr.h:76:22: error: invalid application of ‘sizeof’ to incomplete …

COMP: Remove in-class {} member initializers of unique_ptr

---

Modules/Filtering/FastMarching/test/itkFastMarchingUpwindGradientTest.cxx

Missing semicolon can cause build failure in some configurations if the _ITK_MACROEND_NOOP_STATEMENT_ macro is expanded to `static_assert(true, "")`.
https://open.cdash.org/viewBuildError.php?buildid=8412929

BUG: Added missing semicolon in FastMarchingUpwindGradientTest

---

Modules/Core/Common/test/itkImageRegionIteratorTest.cxx
Modules/Core/Common/test/itkImageReverseIteratorTest.cxx

Remove unused local variables in image iterator tests.

COMP: Remove unused local variables in image iterator tests

---

Modules/Core/Common/test/itkFixedArrayGTest.cxx

Tests that initialization by `{}` properly initializes a `FixedArray`.

ENH: Add GTest `FixedArray.ValueInitialized`

---

Modules/Core/Common/test/itkAdaptorComparisonTest.cxx
Modules/Core/Common/test/itkBoundaryConditionTest.cxx
Modules/Core/Common/test/itkNeighborhoodTest.cxx
Modules/Core/Common/test/itkNumericsTest.cxx
Modules/Core/Common/test/itkSymmetricSecondRankTensorImageWriteReadTest.cxx
Modules/Core/TestKernel/include/itkPipelineMonitorImageFilter.hxx
Modules/Filtering/ImageFilterBase/include/itkNullImageToImageFilterDriver.hxx
Modules/Filtering/ImageIntensity/test/itkMaskImageFilterTest.cxx
Modules/Filtering/ImageIntensity/test/itkMaskNegatedImageFilterTest.cxx
Modules/IO/GDCM/src/itkGDCMImageIO.cxx
Modules/IO/ImageBase/test/itkImageSeriesReaderDimensionsTest.cxx
Modules/IO/ImageBase/test/itkImageSeriesReaderVectorTest.cxx
Modules/IO/MINC/src/itkMINCImageIO.cxx
Modules/IO/MINC/test/itkMINCImageIOTest.cxx
Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
Modules/Numerics/NarrowBand/test/itkNarrowBandTest.cxx
Modules/Numerics/Optimizers/src/itkParticleSwarmOptimizerBase.cxx
Modules/Registration/Common/test/itkCorrelationCoefficientHistogramImageToImageMetricTest.cxx
Modules/Registration/Common/test/itkKullbackLeiblerCompareHistogramImageToImageMetricTest.cxx
Modules/Registration/Metricsv4/test/itkCorrelationImageToImageMetricv4Test.cxx
Modules/Segmentation/LabelVoting/include/itkMultiLabelSTAPLEImageFilter.hxx
Modules/Segmentation/MarkovRandomFieldsClassifiers/test/itkMRFImageFilterTest.cxx

Ran Notepad++ v8.4.8, Replace in Files, using Regular expression:
Find what: ^  ([ ]*)(for \(.+\)\r\n)\1    ([^ {].*;)\r\n
Replace with: $1  $2$1  {\r\n$1    $3\r\n$1  }\r\n
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3875 commit 8d12282fd753fc6404d9c738cc20e8b61a1848cc
"STYLE: Add missing braces to the substatements of `if` statements"

STYLE: Add missing braces to the substatements of `for` loops

---

Modules/ThirdParty/HDF5/src/itkhdf5/src/itk_hdf5_mangle.h

Hello, I was having trouble with an external python lib calling the itk_hdf5 function as shared below. The ?? sometimes indicates a callback but to be sure I searched all instances of H5VL_group_close and only H5G__close_cb was calling it currently unmangled. I will test this soon and report back.
<details>
```
#0  0x00007febfdaa8b49 in itk_H5CX_get_vol_wrap_ctx () from /home/gabriel/g/bin/../lib/GeoSlicer-5.1/libitkhdf5-shared-5.3.so.1
#1  0x00007febfdd23a44 in itk_H5VL_set_vol_wrapper () from /home/gabriel/g/bin/../lib/GeoSlicer-5.1/libitkhdf5-shared-5.3.so.1
#2  0x00007febfdd1870b in itk_H5VL_group_close () from /home/gabriel/g/bin/../lib/GeoSlicer-5.1/libitkhdf5-shared-5.3.so.1
#3  0x00007febfdb4b11d in ?? () from /home/gabriel/g/bin/../lib/GeoSlicer-5.1/libitkhdf5-shared-5.3.so.1
#4 …
```

[COMP] Fix unmangled type symbols on HDF5

---

Modules/Core/Common/include/itkArray.h
Modules/Core/Common/include/itkArray.hxx
Modules/Core/Common/include/itkBoundingBox.h
Modules/Core/Common/include/itkBoundingBox.hxx
Modules/Core/Common/include/itkConicShellInteriorExteriorSpatialFunction.h
Modules/Core/Common/include/itkConicShellInteriorExteriorSpatialFunction.hxx
Modules/Core/Common/include/itkFrustumSpatialFunction.h
Modules/Core/Common/include/itkFrustumSpatialFunction.hxx
Modules/Core/Common/include/itkHeavisideStepFunction.h
Modules/Core/Common/include/itkHeavisideStepFunction.hxx
Modules/Core/Common/include/itkImageDuplicator.h
Modules/Core/Common/include/itkImageDuplicator.hxx
Modules/Core/Common/include/itkPriorityQueueContainer.h
Modules/Core/Common/include/itkPriorityQueueContainer.hxx
Modules/Core/Common/include/itkTorusInteriorExteriorSpatialFunction.h
Modules/Core/Common/include/itkTorusInteriorExteriorSpatialFunction.hxx

Defaulted default-constructors that just set all data members to zero or null, and those that only just call their base class.

STYLE: Default default-constructors of class templates in Core/Common

---

Modules/IO/NIFTI/include/itkNiftiImageIO.h
Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
Modules/IO/NIFTI/test/itkNiftiImageIOTest3.cxx

NIFTI image containing displacement field (intent = NIFTI_INTENT_DISPVECT) was read as scalar volume (all 3 vector components were set to the same value). Fixed by reading it the same way as the general-purpose vector image (intent = NIFTI_INTENT_VECTOR).
The changes already improve NIFTI compatibility, but we could potentially further improve correctness if we can answer these questions:
1. Should the displacement vectors be converted from RAS (native NIFTI) to LPS coordinate system (ITK convention)? The same way as the reader changes the image origin, spacing, axis directions to be in LPS coordinate system instead RAS.
2. NIFTI distinguishes between "vector" and "displacement vector" intent. Is there a way to keep this distinction in ITK? It would be nice if we read a displacement …

BUG: Fix reading of displacement field vectors from NIFTI

---

Wrapping/Generators/Python/Tests/extras.py
Wrapping/Generators/Python/itk/support/extras.py

The Regions, BufferedRegion, LargestPossibleRegion, RequestedRegion, should all be the full image, given by the image_dict["size"]. In itk-wasm, it was observed that this could not be initialized.

BUG: SetRegions in image_from_dict

---

Modules/Core/Common/include/itkImageConstIteratorWithIndex.h
Modules/Core/Common/include/itkImageConstIteratorWithIndex.hxx
Modules/Core/Common/include/itkImageConstIteratorWithOnlyIndex.h
Modules/Core/Common/include/itkImageConstIteratorWithOnlyIndex.hxx

Defaulted the default-constructors of ImageConstIteratorWithIndex and ImageConstIteratorWithOnlyIndex. Added in-class default member initializers to their data members.

STYLE: Default default-constructor ImageConstIteratorWithIndex/OnlyIndex

---

Modules/Core/Common/include/itkMath.h
Modules/Core/Common/src/itkNumericTraits.cxx
Modules/Core/Common/test/itkMathTest.cxx
Modules/Core/Common/test/itkNumericTraitsTest.cxx

COMP: Supress warning in MSVC for non-float complex

---

Modules/Core/Common/test/itkImageIORegionGTest.cxx

Fixed a Visual C++ 2022 Code Analysis warning, saying:
> warning C6287: Redundant code.

COMP: MSVC Code Analysis warning, "redundant code" in ImageIORegionGTest

---

Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx

Remove commented code serializing to the standard output stream in `itk::LevelSetMotionRegistrationFunction`.

STYLE: Remove commented code in `itk::LevelSetMotionRegistrationFunction`

---

Modules/Core/Common/include/itkDataObject.h
Modules/Core/Transform/include/itkBSplineDeformableTransform.h
Modules/Numerics/FEM/include/itkFEMImageMetricLoad.h
Modules/Numerics/FEM/include/itkFEMLoadBC.h
Modules/Numerics/FEM/include/itkFEMLoadBCMFC.h
Modules/Numerics/FEM/include/itkFEMLoadEdge.h
Modules/Numerics/FEM/include/itkFEMLoadGrav.h
Modules/Numerics/FEM/include/itkFEMLoadLandmark.h
Modules/Numerics/FEM/include/itkFEMLoadNode.h
Modules/Numerics/FEM/include/itkFEMLoadNoisyLandmark.h
Modules/Numerics/FEM/include/itkFEMLoadPoint.h
Modules/Registration/FEM/include/itkFEMFiniteDifferenceFunctionLoad.h
Modules/Registration/Metricsv4/include/itkExpectationBasedPointSetToPointSetMetricv4.h
Modules/Registration/Metricsv4/include/itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4.h

Added in-class `{}` default member initializers to data members of classes that have a `itkSimpleNewMacro` macro call.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3851 commit 5e2c49f9eb80e78903ce8f9fd2b5952062653cab "STYLE: Add in-class `{}` member initializers to objects created by New()" (which only looked at classes that have a `itkNewMacro`).

STYLE: Add in-class `{}` initializers to classes with itkSimpleNewMacro

---

Modules/Core/SpatialObjects/include/itkTubeSpatialObject.hxx
Modules/Numerics/Optimizers/src/itkSPSAOptimizer.cxx

Prefer double forward slashes for within-method body comment blocks following the ITK SWG coding style guidelines.
Use a single whitespace between the double forward slashes and the comment sentences.
Follow-up to be6b447afc1c03ba7d6801e425e505cf65351c0b.

STYLE: Prefer double forward slashes for within-method body comments

---

Modules/Numerics/Statistics/include/itkScalarImageToRunLengthMatrixFilter.hxx

Remove `itkMath.h` duplicate include from
`itk::ScalarImageToRunLengthMatrixFilter.h`.

ENH: Remove `itkMath.h` duplicate include

---

Modules/Core/Common/include/itkLoggerThreadWrapper.hxx
Modules/Core/Common/src/itkStdStreamLogOutput.cxx
Modules/Core/Common/src/itkThreadLogger.cxx
Modules/Core/GPUCommon/include/itkGPUImageDataManager.hxx

Replaced `m_Mutex.lock()`/`m_Mutex.unlock()` pairs, following C++ Core Guidelines, September 23, 2022, "Use RAII, never plain `lock()`/`unlock()`" https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#cp20-use-raii-never-plain-lockunlock

STYLE: Use `lock_guard<mutex>` in Logger classes and GPUImageDataManager

---

Modules/Core/Common/include/itkLoggerManager.h
Modules/Core/Common/include/itkLoggerThreadWrapper.h
Modules/Core/Common/include/itkMultipleLogOutput.h
Modules/Core/Common/include/itkThreadLogger.h
Modules/Core/Common/src/itkLoggerManager.cxx
Modules/Core/Common/src/itkMultipleLogOutput.cxx

Also defaulted the default-constructor and destructor of MultipleLogOutput.

STYLE: Use range-based `for` in MultipleLogOutput and LoggerManager

---

Modules/IO/ImageBase/test/itkLargeImageWriteReadTest.cxx
Modules/IO/Meta/test/itkLargeMetaImageWriteReadTest.cxx
Modules/IO/TIFF/test/itkLargeTIFFImageWriteReadTest.cxx

Use the ellipsis properly in printed messages.

STYLE: Use the ellipsis properly in printed messages

---

Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.hxx

Fix declaration and syntax errors in Review module class `PrintSelf` method.
Fixes:
```
Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.hxx:1414:30:
error: 'm_FunctionCount' was not declared in this scope; did you mean 'SetFunctionCount'?
1414 |   for (IdCellType i = 0; i < m_FunctionCount; ++i)
|                              ^~~~~~~~~~~~~~~
|                              SetFunctionCount
```
and
```
Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.hxx:1443:52:
error: expected '>' before '(' token
1443 |       typename NumericTraits<IdCellType>::PrintType(sparsePtr->m_Index) << std::endl;
|                                                    ^
```
https://open.cdash.org/viewBuildError.php?buildid=8456002 …

COMP: Fix declaration and syntax errors in Review class `PrintSelf`

---

Modules/Numerics/FEM/include/itkImageToRectilinearFEMObjectFilter.hxx
Modules/Registration/FEM/include/itkFEMFiniteDifferenceFunctionLoad.hxx
Modules/Registration/FEM/include/itkFEMRegistrationFilter.hxx

Fix miscellaneous compiler errors in `Registration::FEM` module classes' `PrintSelf` methods.
Fixes:
```
ITK\Modules\Registration\FEM\include\itkFEMFiniteDifferenceFunctionLoad.hxx(358,3):
error C2440:
'static_cast':
cannot convert from 'const itk::fem::Solution::ConstPointer' to 'const itk::LightObject *'
```
```
ITK\Modules\Registration\FEM\include\itkFEMFiniteDifferenceFunctionLoad.hxx(358,3):
error C2039:
'Print': is not a member of 'itk::fem::Solution'
```
and
```
ITK\Modules\Numerics\FEM\include\itkImageToRectilinearFEMObjectFilter.hxx(302,22):
error C2275:
'itk::fem::Material': expected an expression instead of a type
```
```
ITK\Modules\Numerics\FEM\include\itkImageToRectilinearFEMObjectFilter.hxx(302,3):
error C3861:
'itkPrintSelfObject': identifier not found
```
and
``` …
```

COMP: Fix `Regitration::FEM` module `PrintSelf` compiler errors

---

Modules/Core/Common/include/itkImageRandomConstIteratorWithIndex.h
Modules/Core/Common/include/itkImageRandomConstIteratorWithOnlyIndex.h
Modules/Core/Common/include/itkRegularizedHeavisideStepFunction.h
Modules/Core/FiniteDifference/include/itkFiniteDifferenceImageFilter.h
Modules/Core/QuadEdgeMesh/include/itkGeometricalQuadEdge.h
Modules/Core/SpatialObjects/include/itkDTITubeSpatialObjectPoint.h
Modules/Core/SpatialObjects/include/itkLineSpatialObjectPoint.h
Modules/Core/SpatialObjects/include/itkSurfaceSpatialObjectPoint.h
Modules/Core/SpatialObjects/include/itkTubeSpatialObjectPoint.h
Modules/Filtering/DistanceMap/include/itkReflectiveImageRegionConstIterator.h
Modules/Filtering/FastMarching/include/itkFastMarchingBase.h
Modules/Filtering/FastMarching/include/itkFastMarchingStoppingCriterionBase.h
Modules/Filtering/QuadEdgeMeshFiltering/include/itkDecimationQuadEdgeMeshFilter.h
Modules/Filtering/QuadEdgeMeshFiltering/include/itkDiscretePrincipalCurvaturesQuadEdgeMeshFilter.h
Modules/Filtering/QuadEdgeMeshFiltering/include/itkLaplacianDeformationQuadEdgeMeshFilter.h
Modules/IO/XML/include/itkXMLFile.h
Modules/Segmentation/LevelSetsv4/include/itkBinaryImageToLevelSetImageAdaptor.h
Modules/Segmentation/LevelSetsv4/include/itkLevelSetContainerBase.h
Modules/Segmentation/LevelSetsv4/include/itkLevelSetEvolutionStoppingCriterion.h
Modules/Segmentation/LevelSetsv4/include/itkLevelSetImage.h

Added in-class `{}` default member initializers to data members of classes that have a destructor declared `override = default`.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3913 commit 5c97b7605e5bec4e9443b57314b50d4e090a845e
"STYLE: Add in-class `{}` initializers to classes with virtual functions"

STYLE: Add in-class `{}` initializers to classes with override = default

---

Wrapping/Generators/SwigInterface/CMakeLists.txt

Add IPFS gateways.
These files have been pinned on web3.storage and pinata.cloud.
Avoid build failures when data.kitware.com fails to provide the files.
@tbirdso another angle for more robust remote module builds.

BUG: Add other SWIG sources download URLs
