circle.yml
White list limited branches to build. This will ignore the dashboard
and hook branches.
Use standard MAKEFLAGS environment variable over MAKEJ.
Use less verbose wget bar over dot progress reporting.
Limit number of threads for testing.
Change-Id: I9d840fdd063f0ff6e2ce3f5bc73fdf8c38820ab9
=> ENH: Update CircleCI yaml file

circle.yml
The CircleCI build ctest script is returning a failure to CircleCI
even though the ctest build and testing is successful. This patch
addresses are CMake Error message produced:
Clearing build tree...
CMake Error at /home/ubuntu/ITK-dashboard/itk_common.cmake:371
(ctest_empty_binary_directory):
ctest_empty_binary_directory problem removing the binary directory:
/home/ubuntu/ITK-build
/home/ubuntu/ITK-dashboard/circleci.cmake:65 (include)
Change-Id: Ib16bcfe7b99b280614344d1d5add6f173400e304
=> WIP: Fix clearing build tree failure.

circle.yml
Use scikit-ci-addons to install a specified version of CMake add
convert the CTest XML to junit format for better displace with CircleCI.
Change-Id: Ib6ee32009a4bad339f108ebd60007c45a0eee496
=> ENH: Use scikit-ci-addons for CiricleCI CMake installation and junit

.circleci/config.yml
Take advantage of CircleCI caching, to cache the external data, and to
use ccache to cache compiled code, between builds.
Change-Id: I5c173dbcd825c5cf46138caacd686619488b8e68
=> ENH: CircleCI use ccache and cache external data

.circleci/config.yml
This suppresses warnings of the following form:
ITK/Modules/Core/Common/include/itkIndex.h:391:27: warning: array
subscript is above array bounds [-Warray-bounds]
It has been determined that this warning is coming from access of an
index variable in ImageAlgorithm::DispatchedCopy. Specifically, when
done like this "++outCurrentIndex[i + 1]". This is a false positive
warning as the code is correct.
Change-Id: Ic763930b6872f78ad51a28b9fc519a4b7aa1dd0b
=> COMP: Suppress warning on CircleCI about itkIndex out of bounds

.circleci/config.yml
Introduce Yaml anchors to enable reuse of common steps.
The previous external data circleci cache was never being updated.
Obtain the most recent commit to modify a md5 or sha512 file. The hash
of this commit message is used for the hash key of the external data
CircleCI cache.
Change-Id: I29e35b15bfd3c3d2799ce835bd4a8dedd371f49a
See the [CONTRIBUTING](CONTRIBUTING.md) guide. Specifically:
Start ITK commit messages with a standard prefix (and a space):
* BUG: fix for runtime crash or incorrect result
* COMP: compiler error or warning fix
* DOC: documentation change
* ENH: new functionality
* PERF: performance improvement
* STYLE: no logic impact (indentation, comments)
* WIP: Work In Progress not ready for merge
Provide a short, meaningful message that describes the change you made.
When …
=> ENH: Update CircleCI external data cache

.circleci/config.yml
scikit-ci-addons intall_cmake explicitly fails with CircleCI
2.0. Revert to `pip install cmake`.
ref: scikit-build/scikit-ci-addons#69
=> BUG: Use pip to install cmake

Modules/Core/Common/wrapping/vnl_c_vector.wrap, Modules/Core/Common/wrapping/vnl_diag_matrix.wrap, Modules/Core/Common/wrapping/vnl_matrix.wrap, Modules/Core/Common/wrapping/vnl_vector.wrap, Wrapping/Generators/Python/itkTemplate.py
Change-Id: Id948fe1f110d276e3e17f55b75bbb379e31c1bb4
See the [CONTRIBUTING](CONTRIBUTING.md) guide. Specifically:
Start ITK commit messages with a standard prefix (and a space):
* BUG: fix for runtime crash or incorrect result
* COMP: compiler error or warning fix
* DOC: documentation change
* ENH: new functionality
* PERF: performance improvement
* STYLE: no logic impact (indentation, comments)
* WIP: Work In Progress not ready for merge
Provide a short, meaningful message that describes the change you made.
When the PR is based on a single commit, the commit message is usually left as the PR message.
A [reference to a related issue or pull request](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests) in your repository. You can …
=> COMP: Remove vcl_complex.h from Python builds

Wrapping/Generators/Python/Tests/CMakeLists.txt
This will enable our Python CI tests to be green, which is more important for testing other work, currently. xref #96
=> BUG: Disable PythonGetNameOfClass test

CONTRIBUTING.md
Tweak location to come before "Revise a Topic".
Improve description.
=> DOC: Add Test a Topic to overview section

Documentation/Introduction.md
Also fix paths to referenced documents.
=> DOC: Update Documentation/Introduction.md for GitHub migration

Modules/Numerics/Statistics/include/itkImageToHistogramFilter.h, Modules/Numerics/Statistics/include/itkImageToHistogramFilter.hxx, Modules/Numerics/Statistics/include/itkMaskedImageToHistogramFilter.h, Modules/Numerics/Statistics/include/itkMaskedImageToHistogramFilter.hxx
http://review.source.kitware.com/#/c/23886/3
Bradley Lowekamp
Uploaded patch set 1.11:41 AM
Bradley Lowekamp
Patch Set 1: I am seeing more that a 10x speed up with 40+ threads.12:16 PM
Dzenan Zukic
12:26 PM
↩
Patch Set 1: Code-Review+2
(1 comment)
I guess this change reduces merge's computational complexity from n to log2(n). With many-core processors, that is significant. But I wouldn't have guessed that total time was dominated by the merge operation. And only that can explain a tenfold speedup.
Modules/Numerics/Statistics/include/itkImageToHistogramFilter.hxx
Line 279:
owner ship -> ownership
Kitware Build Robot
Patch Set 1: Verified-1 Build Failed: CDash filtered results: https://open.cdash.org/index.php?&project=Insight&filtercount=3&field1=buildname/string&compare1=63&value1=23886-1& …
=> Image to histogram multi thread

CMake/itkExternal_FFTW.cmake
Removed quotes from URL and URL_HASH commands that were causing build errors.
=> BUG: CMake build errors

Modules/Remote/BSplineGradient.cmake, Modules/Remote/Montage.remote.cmake
http://review.source.kitware.com/#/c/23862/
Dzenan Zukic
Uploaded patch set 1.Nov 2 9:52 AM
Dzenan Zukic
Patch Set 1: BSplineGradient is required by Ultrasound remote module. Montage is not yet finished, but it already has useful abilities.Nov 2 9:54 AM
Kitware Build Robot
Patch Set 1: Verified-1 Build Failed: CDash filtered results: https://open.cdash.org/index.php?&project=Insight&filtercount=3&field1=buildname/string&compare1=63&value1=23862-1&field2=buildstarttime/date&compare2=83&value2=2015-03-01&field3=buildstarttime/date&compare3=84&value3=2029-01-01Nov 2 10:01 AM
Jon Hait... Gorroño
Patch Set 1: Code-Review+1 Matt said a while ago that the module needed further work to be added as a remote (e.g. IJ article etc.), so it may not be completely finished so as to be included: …
=> ENH: adding new remote modules: Montage and BSplineGradient

Modules/Numerics/Statistics/include/itkImageToHistogramFilter.h
To address:
2018-11-07T00:56:29.5022052Z D:/a/1/s/Modules/Numerics/Statistics/include/itkImageToHistogramFilter.h:138:8: error: no type named 'mutex' in namespace 'std'
2018-11-07T00:56:29.5188235Z   std::mutex m_Mutex;%
=> COMP: Add missing mutex include to itkImageToHistogramFilter.h

Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h
Results in ~10% performance increase.
@N-Dekker this came up when testing the new constant boundary condition in ITKUltrasound.
=> PERF: Use initializer list in ShapedImageNeighborhoodRange operator*

Modules/Numerics/Statistics/include/itkImageToHistogramFilter.h, Modules/Numerics/Statistics/include/itkImageToHistogramFilter.hxx, Modules/Numerics/Statistics/include/itkMaskedImageToHistogramFilter.hxx
Fixes so the a ownership transfer of the histogram pointer can occur
via std::move in the ThreadedMergeHistogram method.
=> BUG: Fix move of histogram smart pointer

Modules/Core/Common/include/itkDomainThreader.h, Modules/Core/Common/include/itkDomainThreader.hxx
http://review.source.kitware.com/#/c/23864/
Bradley Lowekamp
Uploaded patch set 1.Nov 2 4:22 PM
Kitware Build Robot
Patch Set 1: Verified+1 Build Successful: CDash filtered results: https://open.cdash.org/index.php?&project=Insight&filtercount=3&field1=buildname/string&compare1=63&value1=23864-1&field2=buildstarttime/date&compare2=83&value2=2015-03-01&field3=buildstarttime/date&compare3=84&value3=2029-01-01Nov 2 5:30 PM
Hans J. Johnson
Patch Set 1: Code-Review+2Nov 3 2:02 PM
Bradley Lowekamp
9:30 AM
↩
Patch Set 1: Code-Review-1
(1 comment)
Modules/Core/Common/include/itkDomainThreader.hxx
Line 101:
This cout line needs to be deleted.
Dzenan Zukic
Patch Set 1: Code-Review+1 Looks good with the removal of the debugging output.9:39 AM
=> BUG: Add parameter which stores the requested number of work units.

Utilities/ITKv5Preparation/modernize-use-equals-delete.sh
A copy-n-paste error missed fixing the comment for this refactoring.
=> BUG: Default commit message fixed for =delete modernization

Utilities/ITKv5Preparation/prefer-type-alias-over-typedef.sh
Add script to priviledge C++11 type alias over `typedef`.
This was motivated by this topic:
http://review.source.kitware.com/#/c/23103/
And the change has been applied across many of the ITK remote modules
besides the ITK source itself.
However, the piece of code in the mentioned commit never made into a
script, and even if its use should me marginal because most related code
has been changed, it may be worthwhile to add it here so that it is
accessible if it has to be used again.
=> ENH: Add script to priviledge C++11 type alias over typedef.

Modules/Core/Common/include/itkMacro.h
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rc-zero
"Defining only the move operations or only the copy operations would have
the same effect here, but stating the intent explicitly for each special
member makes it more obvious to the reader."
=> ENH: Provide consistency with C++11 core guidelines

Modules/Core/Common/include/itkIndexRange.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkIndexRangeGTest.cxx
Added `Experimental::IndexRange`, to allow efficient iteration over
the indices of an image region or grid space by means of a C++11
range-based for-loop or Standard C++ algorithm. Added type aliases,
`ImageRegionIndexRange<Dimension>` and `ZeroBasedIndexRange<Dimension>`.
This class appears useful in combination with ShapedImageNeighborhoodRange, e.g.:
ImageRegionIndexRange<Dimension> indexRange{ imageRegion };
for (IndexType index : indexRange)
{
shapedImageNeighborhoodRange.SetLocation(index);
for (PixelType neighborPixel : shapedImageNeighborhoodRange)
// Process neighbor pixel...
}
=> ENH: Added IndexRange for efficient region and grid space iteration

Modules/Filtering/ImageFeature/include/itkHoughTransform2DCirclesImageFilter.h, Modules/Filtering/ImageFeature/include/itkHoughTransform2DCirclesImageFilter.hxx, Modules/Filtering/ImageFeature/test/itkHoughTransform2DCirclesImageTest.cxx
Added UseImageSpacing property to allow switching off the
corresponding property from both the image function
(GaussianDerivativeImageFunction) and the smoothing filter
(DiscreteGaussianImageFilter) that are internally used by
HoughTransform2DCirclesImageFilter.
HoughTransform2DCirclesImageFilter::UseImageSpacing is initialized by
'true', in order to preserve the original behavior, by default.
=> ENH: Added HoughTransform2DCirclesImageFilter::UseImageSpacing

PULL_REQUEST_TEMPLATE.md
Improve the PR template message to highlight the fact that it is a set of
guidelines that should be removed for the final PR message.
=> DOC: Advise users to delete the PR template in message.

Modules/Registration/Common/test/CMakeLists.txt, Modules/Registration/Common/test/itkEuclideanDistancePointMetricTest.cxx
Exercise basic object methods.
Exercise all Set/Get macros.
Refactor the test to accept input parameters to test all possible
conditions.
=> ENH: Improve itkEuclideanDistancePointMetric coverage.

Modules/Filtering/ImageStatistics/include/itkLabelStatisticsImageFilter.hxx
Increasing the default number of bins from 20 to 256 significantly improves
the precision of median calculation. Histogram itself is off by default.
See discussion:
https://discourse.itk.org/t/connected-component-image-filter-example/1390/
=> ENH: improve precision of median calculation by default

Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.h
To my understanding eigenvalues and PCA are the special case for a m×n matrix with n = m, i.e. a square matrix. However, the first order derivative (Jacobian) can be a non-square matrix, i.e. m ≠ n, in case the image dimension does not equal the number of vector components (channels).
The PR is meant as a discussion initiation, as I am not an expert in this field and stumbled upon this while trying to understand the math behind this filter.
=> DOC: adjusted to fit more general case n != m

Modules/Filtering/ImageFilterBase/include/itkUnaryGeneratorImageFilter.h, Modules/Filtering/ImageFilterBase/include/itkUnaryGeneratorImageFilter.hxx, Modules/Filtering/ImageFrequency/include/itkFrequencyBandImageFilter.h, Modules/Filtering/ImageFrequency/include/itkFrequencyBandImageFilter.hxx, Modules/Filtering/ImageFrequency/include/itkUnaryFrequencyDomainFilter.h, Modules/Filtering/ImageFrequency/include/itkUnaryFrequencyDomainFilter.hxx, Modules/Filtering/ImageFrequency/test/itkFrequencyBandImageFilterTest.cxx
This filter should enable custom filtering via the functor, e.g. implementing _Butterworth_ algorithm.
=> FrequencyBandImageFilter accepts lambdas for filtering frequencies

Modules/Core/Common/include/itkIndexRange.h, Modules/Core/Common/test/itkIndexRangeGTest.cxx
Fixed two types of warnings from Linux-x86_64-gcc4.8-m32:
itkIndexRange.h:298:5: warning: declaration of 'size' shadows a member of 'this' [-Wshadow]
itkIndexRangeGTest.cxx: warning: missing initializer for member 'itk::Index<2u>::m_InternalArray' [-Wmissing-field-initializers]
Reported by Hans J Johnson @hjmjohnson
=> COMP: Fixed IndexRange warnings -Wshadow -Wmissing-field-initializers

Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.hxx
Declared the unsharpenedImage iterator within N4BiasFieldCorrectionImageFilter::SharpenImage as ImageRegionConstIteratorWithIndex, instead of ImageRegionConstIterator.
Observed a significant performance improvement: 10% to 30% reduction of runtime duration on filter->Update().
=> PERF: unsharpenedImage iterator in N4Bias...Filter is now "WithIndex"

Modules/Filtering/LabelMap/include/itkShapeLabelMapFilter.hxx
Assume 0 results when the negative value of a square root is
taken. The results of the symmetric eigan analysis for eigan values
are expected to be positive. However, due to numeric issues we need to
guard against them being near zero, but negative.
=> BUG: Fix sqrt of negative values

Modules/IO/DCMTK/include/itkDCMTKFileReader.h
Missing default argument override.  When the thowException is
set to false, line 322 should act like lines 116 & 141 and
not throw an exception.
=> BUG: Missing default argment override

Modules/Filtering/ImageLabel/include/itkScanlineFilterCommon.h, Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentImageFilter.h, Modules/Segmentation/ConnectedComponents/test/CMakeLists.txt
Restoring the test which tests that.
Documentation update authored by @fijoy.
=> BUG: background label could be the same as one of the object labels

Modules/Core/Common/include/itkMacro.h
ITKv5_CONST was introduced on 2018-11-12 by commit
5141d32e39a277318ca0efbbec2e3f68980d3193.
We now define the same macro in ITK 4.13,
so the user applications can build easily
against either version 4 or 5 of the toolkit.
=> ITKv5_CONST macro for VerifyPreconditions and VerifyInputInformation

Modules/Core/Common/include/itkIndexRange.h
/scratch/dashboards/Linux-x86_64-gcc4.8-valgrindModules/Core/Common/include/itkIndexRange.h:302:46: warning: missing initializer for member 'itk::Index<1u>::m_InternalArray' [-Wmissing-field-initializers]
=> COMP: fix compiler warning in itkIndexRange.h

Modules/IO/MINC/src/itkMINCImageIO.cxx
MINC has built-in ZLIB compression as part of the underlying HDF5 file format. This is transparent and universally supported. It has pretty nice file size savings particularly in zero-background images due to the compression combined in HDF5 internal chunking. ITK already transparently handles reading these internally compressed files.
Some quick tests show a 30-50% size saving depending upon amount of background voxels.
=> PERF: Enable MINC internal compression by default

Modules/Filtering/ImageLabel/include/itkScanlineFilterCommon.h
The ScanlineFilterCommon class is used with multiple inheritance. This
class held a shared pointer to the other parent which could never be
released to the derived classes holding a reference to
themselves. Change the self pointer to a WeakPointer to avoid circular
dependencies.
=> BUG: Address valgrind leaks for classes which use ScanlineFilterCommon

Modules/Filtering/ImageFrequency/test/CMakeLists.txt, Modules/Filtering/ImageFrequency/wrapping/itkUnaryFrequencyDomainFilter.wrap
Closes #190. I could not quite properly test this today. Build succeeds on my Linux box, but the Python instantiation test fails due to runtime error in ITKCommon. And on Windows, complete build is also taking super-long.
=> ENH: adding wrapping for UnaryFrequencyDomainFilter

Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h, Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx
One of the ShapedImageNeighborhoodRange constructors had a static_assert, trying to prevent users from accidentally passing a temporary 'rvalue' as container of shape offsets. Unfortunately, this did not completely ensure that the offsets would be kept alive, as long as the range would be used. While it would prevent a valid use case.
Instead of that static_assert, a note is added to the documentation, to make users aware that the shape offsets (and the image!) should remain alive while using the range.
=> BUG: ShapedImageNeighborhoodRange should not try to avoid rvalue offsets

Modules/Filtering/ImageFeature/include/itkHoughTransform2DCirclesImageFilter.hxx
GaussianDerivativeImageFunction only computes its kernel once its input image is valid (not null). To avoid unnecessary kernel recomputation triggered by imageFunction.SetSigma and/or imageFunction.SetUseImageSpacing, just call imageFunction.SetInputImage after the other settings, in HoughTransform2DCirclesImageFilter::GenerateData().
=> BUG: Avoid premature GaussianDerivative kernel computation HoughCircles

Modules/IO/Bruker/src/itkBruker2dseqImageIO.cxx
Erroneous use of int was causing integer overflow for large files.
Swapped usage of int to ImageIOBase::SizeType.
=> BUG: Swapped int to SizeType to prevent overflow errors

Utilities/Hooks/prepare-commit-msg
This ensures the entire summary fits into GitHub's renderings.
Also reference the 78 character max enforced by Git client and pull
request hooks.
Suggest the summary, space, detailed description formatting.
Following [discussion on Discourse](https://discourse.itk.org/t/new-convention-for-commit-messages-on-github/1427/10).
=> DOC: Suggest using 72 characters or less in commit hooks

.circleci/config.yml
Fix typeo in environment variable to limit number of threads used.
=> BUG: Limit number of threads used for testing ITK

Modules/Registration/PDEDeformable/include/itkMultiResolutionPDEDeformableRegistration.h
Apparently this V3 compatibility snippets is missing const qualifier as
the return type of the method is defined as const DeformationFieldType *
GetDeformationField(void)
This patch solves this issue
https://insightsoftwareconsortium.atlassian.net/projects/ITK/issues/ITK-3653
=> COMP: added const qualifier for returning type DeformationFieldType * in itkMultiResolutionPDEDeformableRegistration.h

Modules/Core/Common/include/itkConstantBoundaryImageNeighborhoodPixelAccessPolicy.h, Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkConstantBoundaryImageNeighborhoodPixelAccessPolicyGTest.cxx
Added ConstantBoundaryImageNeighborhoodPixelAccessPolicy - a policy to get a specified constant value from ShapedImageNeighborhoodRange when a pixel value outside the image is queried. Equivalent to itk::ConstantBoundaryCondition with itk::ConstNeighborhoodIterator.
Adapted ShapedImageNeighborhoodRange to allow the user to specify an optional pixel access parameter. This parameter allows specifying the constant value for this policy. A policy class that supports this pixel access parameter must have a nested PixelAccessParameterType type.
=> ENH: Added policy for constant NeighborhoodRange values outside image

Examples/RegistrationITKv4/ImageRegistration12.cxx, Examples/RegistrationITKv4/ImageRegistration13.cxx, Examples/RegistrationITKv4/ImageRegistration14.cxx, Examples/RegistrationITKv4/ImageRegistration5.cxx, Examples/RegistrationITKv4/ImageRegistration6.cxx, Examples/RegistrationITKv4/ImageRegistration7.cxx, Examples/RegistrationITKv4/ImageRegistration9.cxx
The centered transforms are not recommended to be used because the
transforms are over parameterized, or having dependent
parameters. This makes the optimization more "difficult" and less
efficient.
In the ITKv4 examples, their usage is replaced with the regular
transforms.
=> Replace centered transforms with non-centered versions

Modules/Remote/LabelErodeDilate.remote.cmake, Modules/Remote/MeshNoise.remote.cmake, Modules/Remote/SmoothingRecursiveYvvGaussianFilter.remote.cmake
Follow remote repositories name changes: change the names of the
modules/repositories URLs following recent changes to the following
remotes:
- `LabelErodeDilate` to `ITKLabelErodeDilate`
- `DVMeshNoise` to `ITKMeshNoise`
- `SmoothingRecursiveYvvGaussianFilter` to
`ITKSmoothingRecursiveYvvGaussianFilter`
Update the git tags accordingly.
=> ENH: Follow remote repositories name changes.

Modules/Core/Common/include/itkDefaultPixelAccessor.h, Modules/Core/Common/include/itkDefaultPixelAccessorFunctor.h, Modules/Core/Common/include/itkDefaultVectorPixelAccessor.h, Modules/Core/Common/include/itkDefaultVectorPixelAccessorFunctor.h
Two small improvements for default pixel accessors:
-  PERF: Removed 'virtual' from Default Pixel Accessor destructors 
-  STYLE: AccessorFunctor::SetPixelAccessor parameter reference to const
=> Small improvements for default pixel accessors

Modules/ThirdParty/VNL/src/CMakeLists.txt
As ITKCommon depends on VNL, it is one of the libraries which are built
before main ITK code gets into compile phase. If VNL is modified,
the incremental build becomes sequential during compilation of VNL.
This enables object-level parallelism in VNL libraries.
=> ENH: compile VNL in parallel on Visual Studio

Modules/Core/Common/include/itkSymmetricEigenAnalysis.h
This looks like the same problem as in this StackOverflow question:
https://stackoverflow.com/questions/40690260/undefined-reference-error-for-static-constexpr-member
The solution is to avoid introducing static constexpr member
and using the template parameter directly.
Example error message:
Modules/Core/Common/include/itkSymmetricEigenAnalysis.h:869: error: undefined reference to 'itk::SymmetricEigenAnalysisFixedDimension<3u, itk::Matrix<double, 3u, 3u>, itk::FixedArray<double, 3u>, itk::Matrix<double, 3u, 3u> >::m_Dimension'
=> COMP: fix link errors coming from undefined static constexpr member

Modules/IO/DCMTK/src/itkDCMTKFileReader.cxx
This addresses https://issues.itk.org/jira/browse/ITK-3527
According Dicom standard (DICOM PS3.6 2016b - Data Dictionary)
(0028, 0030) indicates physical X,Y spacing inside a slice;
(0018, 0088) indicates physical Z spacing between slices;
which above are also consistent with Dcom2iix software.
In current code, the zSpace is get from (0x0018,0x0050) which
actually is the thickness from which the signal is created,
not the separation of signal samplings.
This patch set resolves the problem by updating the Z get
spacing method by using (0018, 0088) when it is available.
Supersedes #112.
=> BUG: The Z spacing was set using thickness

Modules/Core/Common/include/itkSymmetricEigenAnalysis.h, Modules/ThirdParty/Eigen3/CMakeLists.txt
COMP: Reorder variables associated find_package in Eigen3
The new order always populates `Eigen3_DIR_BUILD|INSTALL` correctly.
=> COMP: Use the right constructors for fixed eigen3 matrix

Modules/Core/Common/include/itkImageRange.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkImageRangeGTest.cxx
Added Experimental::ImageRange<TImage>: a modern C++ range of iterators to the pixels of an image. Supports any ITK image type (both itk::Image and itk::VectorImage). For "regular" image types (itk::Image), iterator::operator*() returns a reference to the current pixel. For other image types (like itk::VectorImage), iterator::operator*() returns a proxy, that behaves like a reference to the pixel.
Supports iterating over an image by a C++11 range-based for-loop, for example:
ImageRange<ImageType> imageRange{ *image };
for (auto&& pixel : imageRange)
{
pixel = pixel + 42;
}
Also supports random access to any pixel of the image:
std::size_t indexValue = std::rand() % imageRange.size();
auto&& pixel = imageRange[indexValue];
Its iterators can be passed to an algorithm from the Standard C++ …
=> ENH: Added ImageRange: a range of iterators to the pixels of an image

Modules/Numerics/Optimizersv4/src/itkLBFGS2Optimizerv4.cxx
The xItk array was not reinitialized to proper a proper size then
LBFGS2 was using multiple times or with transform adapters. This
caused a buffer over-run and segmentation fault.
=> BUG: Remove static member function variable ( back port to 4.13 )

Modules/Core/Common/include/itkImageHelper.h
Replaced old itk::Concept::Detail::UniqueType_bool within ImageHelper class definition by C++11 std::integral_constant<bool, B>, from <type_traits>.
Replaced expressions like 'x = x + a' by 'x += a', which might possibly be slightly faster.
=> STYLE: ImageHelper now doing '+=' and using C++11 std::integral_constant

Documentation/ITK5MigrationGuide.md, Modules/Core/Common/include/itkArray.h, Modules/Core/Common/include/itkImageBase.h, Modules/Core/Common/include/itkMath.h, Modules/Core/Common/include/itkMatrix.h, Modules/Core/Mesh/include/itkSimplexMesh.hxx, Modules/Core/Mesh/include/itkSimplexMeshAdaptTopologyFilter.h, Modules/Core/Mesh/src/itkSimplexMeshGeometry.cxx, Modules/IO/PhilipsREC/test/itkPhilipsRECImageIOPrintTest.cxx, Modules/Numerics/FEM/src/itkFEMLinearSystemWrapperVNL.cxx, Modules/Segmentation/DeformableMesh/include/itkDeformableSimplexMesh3DFilter.hxx
Remove conditional code that supported older versions of VXL.
There is now a stricter requirement on the newer v2.02 version of VXL.
=> Remove outdated vxl version support

Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h, Modules/Core/Common/test/itkConstantBoundaryImageNeighborhoodPixelAccessPolicyGTest.cxx
One of the constructors of the ShapedImageNeighborhoodRange iterator types did not copy the pixel access parameter. This bug might cause serious problems (undefined behavior) when using ConstantBoundaryImageNeighborhoodPixelAccessPolicy.
The bug was introduced with 0be5876ee010c46ea17521dc12ed2eaa825ddad9 (merged onto the ITK master branch on November 20, 2018).
This commit fixes this constructor and extends the GTest ConstantBoundaryImageNeighborhoodPixelAccessPolicy.YieldsSpecifiedConstantOutsideImage to test this particular issue as well. The issue occurred when using ShapedImageNeighborhoodRange::operator[].
=> BUG: Fixed ShapedImageNeighborhoodRange copying pixel access parameter

Modules/Core/Common/include/itkFloatingPointExceptions.h, Modules/Filtering/FFT/include/itkForwardFFTImageFilter.h, Modules/Filtering/ImageFrequency/include/itkUnaryFrequencyDomainFilter.h
Doxygen will implicitly pick up these references. Adding them explicitly
causes warnings in the Python wrapping, when their definition is not
available. Remove them also makes it a little easier to read the
comment.
To address:
```
/home/matt/src/ITK2/Modules/Core/Common/include/itkFloatingPointExceptions.h:50: warning: @copydetails or @copydoc target 'Enable' not found
/home/matt/src/ITK2/Modules/Core/Common/include/itkFloatingPointExceptions.h:61: warning: @copydetails or @copydoc target 'Enable' not found
[5864/6441] Building CXX object Wrapping/Modules/ITKColormap/CMakeFiles/ITKColormapPython.dir/itkScalarToRGBColormapImageFilterPython.cpp.o
/home/matt/src/ITK2/Modules/Filtering/FFT/include/itkForwardFFTImageFilter.h:44: warning: unable to resolve reference to …
```
=> COMP: Remove Doxygen \ref, \copydetails commands

Modules/Core/Common/include/itkConceptChecking.h
Use ::IsInteger, which is defined for NumericTraits< VariableLengthVector >;
std::numeric_limits< itk::VariableLengthVector >::is_integer is not
defined. For is_exact, use std::numeric_limits< typename NumericTraits<
T >::ValueType >::is_exact.
=> COMP: Fix IsFloatingPoint concept check for VariableLengthVector

Modules/Core/SpatialObjects/test/CMakeLists.txt, Modules/Filtering/AnisotropicSmoothing/test/CMakeLists.txt, Modules/Filtering/AntiAlias/test/CMakeLists.txt, Modules/Filtering/BinaryMathematicalMorphology/test/CMakeLists.txt, Modules/Filtering/CurvatureFlow/test/CMakeLists.txt, Modules/Filtering/FFT/test/CMakeLists.txt, Modules/Filtering/FastMarching/test/CMakeLists.txt, Modules/Filtering/ImageFeature/test/CMakeLists.txt, Modules/Filtering/ImageFilterBase/test/CMakeLists.txt, Modules/Filtering/ImageGradient/test/CMakeLists.txt, Modules/Filtering/ImageGrid/test/CMakeLists.txt, Modules/Filtering/ImageIntensity/test/CMakeLists.txt, Modules/Filtering/MathematicalMorphology/test/CMakeLists.txt, Modules/Filtering/Smoothing/test/CMakeLists.txt, Modules/Filtering/Thresholding/test/CMakeLists.txt, Modules/IO/GDCM/test/CMakeLists.txt, Modules/Segmentation/LevelSets/test/CMakeLists.txt, Modules/Segmentation/Watersheds/test/CMakeLists.txt
This PR addresses problems introduced when moving Python tests from the global Wrapping/Generators/Python directory to their individual module directory.
=> Bad cmake find itk wrap image dims

Testing/ContinuousIntegration/AzurePipelinesLinux.yml, Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml, Testing/ContinuousIntegration/AzurePipelinesMacOS.yml, Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml, Testing/ContinuousIntegration/AzurePipelinesWindows.yml, Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
To reduce the size of the logs, reduce the verbosity of ctest and only
show test out when the test fails.
=> ENH: On Azure DevOps only show test output on failure

Documentation/ITK5MigrationGuide.md
Updated ITK5 migration guide with HoughTransform2DCirclesImageFilter changes, as requested by @dzenanz issue #136
=> DOC: Did #136 Update migration guide with Hough transform changes

Modules/Core/Common/include/itkImageRange.h
Fixed Mac10.13-AppleClang-dbg-x86_64-static warning from https://open.cdash.org/viewBuildError.php?type=1&buildid=5660763 that said:
[CTest: warning matched] /Users/builder/externalModules/Core/Common/include/itkImageRange.h:334:53: warning: passing object of class type 'const itk::Experimental::ImageRange<itk::Image<short, 1> >::OptionalAccessorFunctorType' (aka 'const itk::Experimental::ImageRange<itk::Image<short, 1> >::EmptyAccessorFunctor') through variadic constructor [-Wclass-varargs]
The warning wasn't very severe, because the "object of class type" that was passed to this specific variadic constructor was unused anyway.
This commit fixes the warning by replacing the variadic constructor of PixelReferenceWrapper by a non-variadic one. It also adds comments to …
=> COMP: Fixed ImageRange warning, passing object to variadic constructor

Modules/Core/Common/include/itkImageRange.h, Modules/Core/Common/test/itkImageRangeGTest.cxx
Added default-constructor to ImageRange, allowing to easily create an empty range. Added ImageRange::empty(), which returns true for a default-constructed range.
Added unit tests for these two member functions.
=> ENH: Added default-constructor and empty() to ImageRange

CMakeLists.txt
Allow configuring without cmake policy developer warnings
for a range of cmake versions.
This prevents the need to explicitly enumerate every new
policy for each new cmake version.
=> ENH: Provide range for non-warned cmake versions

Modules/Core/Common/include/itkImageRange.h, Modules/Core/Common/test/itkImageRangeGTest.cxx
With this commit, the iterators of ImageRange<ImageType> are defined as raw
pointers to the pixel data, instead of 'QualifiedIterator' class type objects,
whenever this is possible. (In practice, that is when the image type is a
regular itk::Image.) A large performance gain was observed from this commit,
when calling std::copy as follows:
std::copy(imageRange.cbegin(), imageRange.cend(), std::begin(outputImageRange));
While considering the pros and cons of this change, Jason Spencer
(jasonspencer.org) helped me, quoting ISO C++ 2011 Section 24.2.1/2:
"Since iterators are an abstraction of pointers, their semantics is a
generalization of most of the semantics of pointers in C++. This ensures that
every function template that takes iterators works as well with regular
pointers."
=> PERF: Defining ImageRange iterator as raw pixel pointer, when possible

Modules/Core/TestKernel/include/itkGTestTypedefsAndConstructors.h, Modules/Core/Transform/include/itkBSplineTransform.h, Modules/Core/Transform/include/itkBSplineTransform.hxx, Modules/Core/Transform/test/CMakeLists.txt, Modules/Core/Transform/test/itkBSplineTransformGTest.cxx
When "SetFixedParameters" is called when reading a BSplineTransform, or a Clone ( SimpleITK copy-on-write), the TransformDomain* parameters are not updated.
=> BUG: Synchronize BSpline MeshTransform parameters with fixed

Modules/Core/Common/include/itkImageRange.h, Modules/Core/Common/test/itkImageRangeGTest.cxx
Added a convenience function, MakeImageRange(TImage*), to the itk::Experimental
namespace, inspired by Standard C++ Library functions like std::make_pair and
std::make_shared. Creates an ImageRange, corresponding to the image that is
passed as argument. When the argument is a nullptr, it returns an empty range.
Also added a missing itkNotUsed(...) to an unused parameter of a constructor of
the internal (implementation-only) PixelReferenceWrapper class.
=> ENH: Added Experimental::MakeImageRange(TImage*)

Modules/Remote/PhaseSymmetry.remote.cmake
This is a module for the `Insight Toolkit (ITK) <http://itk.org>`_ that
provides multi-scale steerable filters for computing phase symmetry
(PS).
Multi-scale steerable phase-symmetry filters are applied in the image Fourier
transform domain, and have been shown to be a useful pre-processing measure
for performing image registration and segmentation.
For more information, see the `Insight Journal article
<http://hdl.handle.net/10380/3330>`_::
Hatt C.
Multi-scale Steerable Phase-Symmetry Filters for ITK
The Insight Journal. July-December. 2011.
http://hdl.handle.net/10380/3330
http://www.insight-journal.org/browse/publication/846
Thanks to @jhlegarreta , who helped get the CI set up for this module and who started the wrapping configuration! :green_apple:
=> ENH: Add PhaseSymmetry remote module

Modules/Core/Transform/include/itkBSplineTransform.hxx
When the SetFixedParameters method was called, the MeshTransform
parameters were not being updated and became out of sync. This occurs
after reading a transform from disc, or from the Clone method.
Additionally the TransformDomainDirecion was not being update.
=> BUG: Synchronize BSpline MeshDomain parameters from fixed params

Modules/Core/Transform/include/itkBSplineTransform.h, Modules/Core/Transform/include/itkBSplineTransform.hxx, Modules/Core/Transform/test/itkBSplineTransformGTest.cxx
Improve consistency and efficiency of BSplineTransform's
parameters. The set of TransformDomain IVAR have been remove, and the
accessors have been replaced which directly compute the value from the
fixed parameters. The TransformDomain set methods, now call a single
method which computes the fixed parameters from all the transform
domain parameters. The use for the fixed parameters for the
authoritative value of TransformDomain values follows from the fixed
parameters being the serialized values.
Additionally the extra allocation of the CoefficientImage buffers has
been removed, and replaced with the allocation of InternalParameters
and setting of their buffers.
=> ENH: Refactor BSplineTransform

Modules/Core/Common/include/itkImageSource.hxx, Modules/Core/Common/include/itkImageToImageFilter.hxx, Modules/Core/Common/include/itkPointSetToImageFilter.hxx, Modules/Core/Common/src/itkEquivalencyTable.cxx, Modules/Core/Mesh/include/itkRegularSphereMeshSource.hxx, Modules/Core/Mesh/include/itkSimplexMesh.hxx, Modules/Core/Mesh/include/itkSimplexMeshAdaptTopologyFilter.hxx, Modules/Core/Mesh/include/itkSimplexMeshToTriangleMeshFilter.hxx, Modules/Core/Mesh/include/itkSimplexMeshVolumeCalculator.hxx, Modules/Core/Mesh/include/itkTriangleMeshToBinaryImageFilter.hxx, Modules/Core/Mesh/include/itkTriangleMeshToSimplexMeshFilter.hxx, Modules/Core/Mesh/include/itkVTKPolyDataWriter.hxx, Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshToQuadEdgeMeshFilter.h, Modules/Core/SpatialObjects/include/itkMetaMeshConverter.hxx, Modules/Numerics/Statistics/include/itkScalarImageToCooccurrenceMatrixFilter.hxx, Modules/Numerics/Statistics/include/itkScalarImageToRunLengthFeaturesFilter.hxx, Modules/Numerics/Statistics/include/itkScalarImageToRunLengthMatrixFilter.hxx, Modules/Numerics/Statistics/include/itkScalarImageToTextureFeaturesFilter.hxx, Modules/Segmentation/DeformableMesh/include/itkDeformableSimplexMesh3DFilter.hxx, Modules/Segmentation/Watersheds/include/itkWatershedSegmenter.hxx
Replaced operator++ calls of the form 'it++' by '++it', on ITK iterators.
Following the classical C++ guideline, to prefer calling the prefix form,
rather than the postfix form of such operators:
C++ Coding Standards: 101 Rules, Guidelines, and Best Practices
"Prefer the canonical form of ++ and --. Prefer calling the prefix forms"
Herb Sutter, Andrei Alexandrescu, 2004
This commit is likely to improve the performance (slightly) on many use cases.
=> PERF: Replaced postfix ++ calls on ITK iterators by the prefix ++ calls

Testing/ContinuousIntegration/AzurePipelinesLinux.yml, Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml, Testing/ContinuousIntegration/AzurePipelinesMacOS.yml, Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml, Testing/ContinuousIntegration/AzurePipelinesWindows.yml, Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
Avoid downloading files individually, which can be brittle.
Download the most recent archive from GitHub releases.
=> ENH: Download ExternalData cache for CI builds

CONTRIBUTING.md
This was used as a way to indicated branches should be merged into the
`release` branch when using Gerrit and merging directly into the `release`
branch was not possible. Now that we can merge directly into the
`release` branch, it is no longer necessary.
Closes #180
=> DOC: Remove the convention that release branches start with "release"

Modules/Core/Common/include/itkImageRegion.h, Modules/Core/Common/include/itkImageRegion.hxx
itk::ImageRegion now uses C++11 features more extensively:
- Added 'final' specifier to its class definition.
- Declared all constructors and operators 'noexcept'
- Defaulted default-constructor, copy-constructor, destructor and assignment.
- Added default member initializers ('= {{0}}') to its data members.
Also replaced assignment of data members in constructors by old-style (C++98)
data member initialization.
These changes aim to improve performance, readability, and maintainability.
=> PERF: Added C++11 final, noexcept, default, initializers to ImageRegion

CMake/ITKExternalData.cmake
We now use ITK/Utilities/UploadBinaryData.sh to generate SHA512 content
links and upload binary data. Prevent the CMake ExternalData module from
consuming binary data files.
=> BUG: Remove ExternalData MD5 content link generation

Documentation/UploadBinaryData.md, Utilities/GitSetup/setup-girder-api-key, Utilities/SetupForDevelopment.sh, Utilities/UploadBinaryData.sh
This script is a re-usable Git Setup script for use with the Kitware Git
Setup infrastructure designed by Brad King and with the
ITK/Utilities/UploadBinaryData.sh. During
./Utilities/SetupForDevelopment.sh it help the user set up a Girder API
key in the repository's Git configuration. This API key is used to
automate authenticated uploads when uploading testing data with the
UploadBinaryData.sh script via the `git data-upload` alias.
Closes #93
=> ENH: Add setup-girder-api-key Git Setup script

Modules/Core/Common/include/itkBuildInformation.h, Modules/Core/Common/include/itkIndex.h, Modules/Core/Common/include/itkOffset.h, Modules/Core/Common/include/itkSize.h
Using the `rule of zero` to this aggregate type
C++20 changes the definition of aggregate such that classes with any user-declared ctors are no longer aggregates.
Fixes: #319
=> ENH: Employ the `rule of zero` for aggregate types

Modules/Core/Common/include/itkImageRegion.h
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36) reports warning unused
arguments with default-ed members.
=> COMP: Addressed unused parameter warning in ImageRegion default

Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.h, Modules/Filtering/ImageGrid/include/itkBSplineControlPointImageFilter.h, Modules/Filtering/ImageGrid/include/itkBSplineScatteredDataPointSetToImageFilter.h
…lter
To address build error uncovered by Windows Python wrapping:
```
c:\itk\modules\filtering\biascorrection\include\itkN4BiasFieldCorrectionImageFilter.h(415): error C2397: conversion from 'double' to 'itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::RealType' requires a narrowing conversion
c:\itk\modules\filtering\imagegrid\include\itkBSplineScatteredDataPointSetToImageFilter.h(362): error C2397: conversion from 'double' to 'itk::BSplineScatteredDataPointSetToImageFilter<itk::PointSet<itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType,2,itk::DefaultStaticMeshTraits<TPixelType,2,2,float,float,TPixelType>>,itk::Image<itk::N4BiasFieldCorrectionImageFilter<ImageType,MaskImageType,ImageType>::ScalarType,2>>::RealType' requires a …
```
=> COMP: Float narrowing conversion in BSpline classes

Modules/Core/Common/include/itkImageBase.hxx
Initialized ImageBase::m_OffsetTable (a 'C array' of integers) by curly braces,
`{}`, in constructor member-initializer-list, instead of calling `memset`.
Removed check if m_RequestedRegion != region before ImageRegion assignment, as
this assignment is already very fast and `noexcept`. Note that this apparently
unnecessary 'if' was there already in 2001 (in Code/Common/itkImageBase.txx),
SHA-1: 73e22b2cb3fa156192f819c3d11706f86b6c9845
Removed dangling backslash, `\`, from PrintSelf, introduced in 2005 (in
Code/Common/itkImageBase.txx), SHA-1: 7510eae6effdf82a9b0307983dec0942d316f32b
=> STYLE: Small improvements ImageBase constructor, SetRequestedRegion, '\'

Modules/Registration/RegistrationMethodsv4/include/itkSyNImageRegistrationMethod.h, Modules/Registration/RegistrationMethodsv4/include/itkSyNImageRegistrationMethod.hxx
Initialized data members of SyNImageRegistrationMethod by C++11 default member
initializers, within the class definition, instead of within the implementation
of its default constructor. (C++11 non-static data member initialization,
"NSDMI".) This has the great advantage that its default values are included
with the class documentation, as generated by Doxygen.
Fixed issue #273: "Mismatch documentation and code SyNImageRegistrationMethod
GaussianSmoothingVarianceForTheUpdateField default value"
=> DOC: issue #273: SyNImageRegistrationMethod default member initializers

Modules/Registration/Common/include/itkImageRegistrationMethod.hxx, Modules/Registration/Common/include/itkImageToSpatialObjectRegistrationMethod.hxx, Modules/Registration/Common/include/itkMultiResolutionImageRegistrationMethod.hxx, Modules/Registration/Common/include/itkPointSetToImageRegistrationMethod.hxx, Modules/Registration/Common/include/itkPointSetToPointSetRegistrationMethod.hxx, Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx
The MakeOutput(output) member functions of six RegistrationMethod classes did
return, after throwing an exception. It appears that MakeOutput(output)
functions already did so in 2011 (for example, SimpleImageRegistrationMethod
SHA-1: 2e548c6b0f20007779ec4f74a1a13d9dbe6b7ec2). Unfortunately, these return
statements triggered Visual C++ warnings (at Warning Level 4):
itk\modules\core\common\include\itksmartpointer.h(70): warning C4702: unreachable code
This commit refactors these MakeOutput(output) member functions, avoiding the
compiler warning and simplifying the code.
=> COMP: Fix "unreachable code" MakeOutput RegistrationMethods

Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.h, Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.hxx
Adapted N4BiasFieldCorrectionImageFilter to start using ImageRange internally.
This commit yields a significant performance improvement, especially because
it replaces the (rather expensive) itk::Image::GetPixel(index) calls by
more efficient ImageRange[indexValue] calls.
Added checks to GenerateData() that the image sizes of the mask image and
confidence image (if provided) are equal to the size of the input image.
Ensured that the entire output image is computed at once, by overriding
EnlargeOutputRequestedRegion(DataObject*), as suggested by Bradley (@blowekamp).
Using VS2015 (Release), ~10% reduction of the run-time duration was observed on
a 3-D MRI volume + mask (453x340x20 voxels), provided by Denis (@dpshamonin),
at LKEB, Leiden University Medical Center.
=> PERF: N4BiasFieldCorrectionImageFilter implementation using ImageRange

Modules/Core/Common/include/itkOctree.h
Modules/Core/Common/include/itkOctree.h:173: warning: documented symbol `enum OctreePlaneType itk::Octree< TPixel, ColorTableSize, MappingFunctionType >::m_Plane' was not declared or defined.
=> DOC: trying to fix the doxygen warning

Modules/Core/Common/include/itkResourceProbe.h, Modules/Core/Common/include/itkResourceProbe.hxx
ITK 4.9 added system info to `itk::ResourceProbe` (the base class of
`itk::TimeProbe` and `itk::MemoryProbe`), by calling `GetSystemInformation()`
in its constructor. This function call appeared very time consuming.
Using Visual Studio 2017 (Release configuration), it was observed that a single
`GetSystemInformation()` function call took more than 0.1 second.
This commit removes the `this->GetSystemInformation()` function call from
ResourceProbe, deprecates the member function, removes the related data
members, and only retrieves the system info when and where it is actually being
used: in `PrintSystemInformation` and `PrintJSONSystemInformation`.
Fixes issue #350, "Major performance issue TimeProbe, ResourceProbe
constructor", which was based on the analysis of an `elastix` example
case …
=> PERF: Remove SystemInformation data from ResourceProbe, fix issue #350

Modules/Core/Common/include/itkMapContainer.h, Modules/Core/Common/include/itkVectorContainer.h
Removed unnecessary dynamic_cast's from the implementations of
`CastToSTLContainer()` and `CastToSTLConstContainer()` member functions of
`itk::MapContainer` and `itk::VectorContainer`.
Without the dynamic_cast's, these member functions will certainly never throw
an exception anymore, so this commit also declares them 'noexcept'.
=> STYLE: Remove dynamic_cast from CastToSTLContainer(), add noexcept

Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.h, Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.hxx
N4BiasFieldCorrectionImageFilter::UpdateBiasFieldEstimate now adds the points
and weights for the internally used BSplineFilter in a much faster way than
before, by:
* Reserving the memory needed to store the data beforehand.
* Directly doing `push_back` on the STL containers from the internally used
itk::PointSet and itk::VectorContainer.
Using VS2015 (Release), approximately 20% reduction of the run-time duration was
observed (from 70 down to 56 seconds) on a 3-D MRI volume + mask (453x340x20),
provided by Denis (@dpshamonin), at LKEB, Leiden University Medical Center.
=> PERF: N4BiasFieldCorrectionImageFilter adds points + weights ~20% faster 

Utilities/Debugger/ITK.natvis
I think some recent updates made interpretation of these debug visualizer definitions more strict, so inheriting and alternative naming is no longer sufficient.
=> ENH: Updating Visual Studio debug visualizer definitions

Modules/Filtering/ImageGrid/include/itkBSplineScatteredDataPointSetToImageFilter.hxx
`BSplineScatteredDataPointSetToImageFilter::GenerateData()` now does fast
assignments to the internal STL containers of `m_PointWeights`,
`m_InputPointData`, and `m_OutputPointData`, instead of calling the expensive
`itk::VectorContainer::InsertElement` member function.
Using VS2015 (Release), ~8% run-time duration reduction was observed on an
`Update()` of `BSplineScatteredDataPointSetToImageFilter`. For an `Update()`
of `N4BiasFieldCorrectionImageFilter` (which heavily uses
`BSplineScatteredDataPointSetToImageFilter`), ~7% run-time duration reduction
was observed (from 56 sec to 52 sec, on a 3-D MRI volume + mask (453x340x20),
provided by Denis (@dpshamonin), at LKEB, Leiden University Medical Center).
=> PERF: Fast assign point data, weights BSplineScatteredData filter

Modules/ThirdParty/HDF5/CMakeLists.txt
This change prevents the installed `ITKHDF5.cmake` config file from listing absolute paths when built with `ITK_USE_SYSTEM_HDF5`. Summary of how this happens, from [this comment](https://github.com/conda-forge/libitk-feedstock/issues/7#issuecomment-449040962):
In CMake's FindHDF5 routine, when building against a non-CMake HDF5 build (as in Anaconda):
1) FindHDF5 calls `h5cc -showconfig`
- among many other things, this gives `Extra libraries: -lrt -lpthread -lz -ldl -lm`
2) [FindHDF5 matches anything in the output that has `-l<...>`](https://github.com/Kitware/CMake/blob/049d324e42451fb92d9504551f3885e221f05b8a/Modules/FindHDF5.cmake#L379-L381)
- so it matches `-lrt`
3) runs `find_library` for every library identified by (2). This gives the FULL PATH to either the system library (or with …
=>  COMP: use HDF5 library names only to avoid abspaths w/ SYSTEM_HDF5

Examples/Segmentation/ShapeDetectionLevelSetFilter.cxx
Use output file names that are specific to the example invocation so
they do not not overwrite each other. Also, add it as OUTPUTS, so it is
picked up by the ITKSoftwareGuide RunExamples.py. Add it to the end of
the command line arguments list so they do not interfere with processing
the other command line arguments.
This will enable us to update the ITKSoftwareGuide to ITK 5!
=> BUG: ShapeDetectionLevelSetFilter outputs

Modules/Core/ImageFunction/include/itkBSplineDecompositionImageFilter.hxx
With this commit, `BSplineDecompositionImageFilter::CopyImageToImage()` calls
`ImageAlgorithm::Copy`, instead of doing manual iteration.
A small (~2%) performance improvement was observed, on a `filter->Update()`.
=> PERF: BSplineDecompositionImageFilter now calls ImageAlgorithm::Copy 

Modules/Core/Common/include/itkImageBufferRange.h, Modules/Core/Common/test/itkImageBufferRangeGTest.cxx
When `TImage` is a `const` image type, it is not necessary to distinguish
between the non-const `iterator` type and the `const_iterator` type of
`ImageBufferRange<TImage>`.
This commit ensures that for a `const` image, `iterator` and `const_iterator`
are the same. They were the same already for a `const itk::Image`, but now they
are also the same for a `const itk::VectorImage`. Thereby this commit will reduce
"template code bloat" (reducing the number of template instantiations).
Also fixes `ImageBufferRange<const VectorImage>` errors reported by GCC ("could
not convert from 'IteratorInitializer'") and Clang ("no viable conversion...").
=> COMP: ImageBufferRange iterator same as const_iterator, for const image

Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h, Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx
Added default-constructor to `ShapedImageNeighborhoodRange`, allowing to easily
create an empty range. Added `ShapedImageNeighborhoodRange::empty()`, which
returns true for a default-constructed range, as well as for a range that was
constructed with an empty sequence as `shapeOffsets` parameter.
Added unit tests for these two member functions.
Follow-up to SHA-1: e9d249e96525646c1e48151d79a3cc2a67a0af30 (8 December 2018)
=> ENH: Add default-constructor and empty() to ShapedImageNeighborhoodRange

Documentation/ITK5MigrationGuide.md, Modules/Core/Common/include/itkThreadPool.h
This does not have an implementation after migration to
itk::MultiThreaderBase. This causes errors on Windows and with the
Python wrapping.
Remove and make a note in the Migration Guide.
=> COMP: Remove itk::ThreadPool::GetGlobalDefaultNumberOfThreadsByPlatform

Modules/ThirdParty/Eigen3/src/itk_eigen.h.in
BUG: Fix failure of ITK_EIGEN macro expansion
DOC: Add how-to re-use internal Eigen3 in a external project
ENH: Remove EIGEN_MPL2_ONLY compile definition when using system Eigen3
When including the macro ITK_EIGEN twice in a header, the expansion was
wrong:
```cpp
ITK_EIGEN(Eigenvalues)
ITK_EIGEN(Eigenvalues)
```
The first macro would expand correctly to:
```cpp
// #include "itkeigen/Eigen/Eigenvalues"
```
but the second, will change `Eigen` for `itkeigen`, generating:
```cpp
fatal error: itkeigen/itkeigen/Eigenvalues: No such file or directory
```
Minimal working example for testing:
`CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.10.2)
project(tester)
find_package(ITK REQUIRED)
include(${ITK_USE_FILE})
add_executable(tester tester.cpp )
target_link_libraries(tester …
```
=> BUG: Fix failure of ITK_EIGEN macro expansion

Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx
To address:
/ITK/Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx:153:45: warning: unused
parameter 'name' [-Wunused-parameter]
bool DCMTKImageIO::CanWriteFile(const char *name)
=> COMP: Mark DCMTKImageIO::CanWriteFile argument as unused

Modules/Core/Common/include/itkImageBufferRange.h, Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h, Modules/Core/Common/test/itkImageBufferRangeGTest.cxx, Modules/Core/Common/test/itkRangeGTestUtilities.h, Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx
Allowed assigning one `ShapedImageNeighborhoodRange` object to another, by
declaring all of the range data members non-const.
Followed the C++ "Rule of Zero" for both `ShapedImageNeighborhoodRange`
and `ImageBufferRange`.
Tested copy and move semantics of both range template classes, introducing a
class of test utilities, `RangeGTestUtilities`, to implement these unit tests.
Triggered by a comment by @dzenanz, 3 January 2019, at pull request #362
=> ENH: Made ShapedImageNeighborhoodRange assignable and tested copy + move

Modules/Core/Common/include/itkImageBufferRange.h, Modules/Core/Common/include/itkIndexRange.h, Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h
Documented using the C++ "Rule of Zero" for the iterator classes of
`ImageBufferRange`, `ShapedImageNeighborhoodRange`, and `IndexRange`.
Removed explicitly-defaulted destructors from the iterator classes of
`ImageBufferRange` and `ShapedImageNeighborhoodRange`.
=> STYLE: C++ "Rule of Zero" for iterator classes of Range types

Modules/Core/Common/include/itkNeighborhood.h, Modules/Core/Common/include/itkNeighborhoodAllocator.h
Added fast `noexcept` move-constructor and move-assignment operator to
`itk::NeighborhoodAllocator`. A performance improvement of 50 % was observed,
when move-assigning `itk::NeighborhoodAllocator` objects, on VS2017 Release.
Added explicitly-defaulted move-constructor and move-assignment operator to
`itk::Neighborhood`. Note that these two member functions are implicitly
noexcept, when template parameter TAllocator is `NeighborhoodAllocator<TPixel>`
(which is the default).
Also removed the unconventional `const` keyword from the return type of the
copy-assignment operator of `itk::NeighborhoodAllocator`.
=> PERF: Add fast noexcept move semantics to Neighborhood and its Allocator

Modules/Core/Common/include/itkResourceProbe.hxx
Before this commit, `ResourceProbe<ValueType, MeanType>::Reset()` did assign
`DBL_MIN` (~2.2e-308) to `m_MaximumValue`, when `ValueType` = `double` (for
example, for `itk::TimeProbe`). This gave incorrect results, when all values
retrieved by `GetInstantValue()` were less than `DBL_MIN`.
This commit fixes this bug by assigning the lowest value, `NonpositiveMin()`
(instead of `min()`) to `m_MaximumValue`, within `ResourceProbe::Reset()`.
=> BUG: ResourceProbe::Reset() should set m_MaximumValue to lowest value

Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx
To address:
[CTest: warning matched] /scratch/dashboards/Linux-x86_64-gcc4.8Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx:148:57: warning: missing initializer for member 'std::array<itk::Offset<2u>, 0ul>::_M_elems' [-Wmissing-field-initializers]
const std::array<OffsetType, 0> emptyArrayOfOffsets{};
=> COMP: ShapedImageNeighborhoodRangeGTest array initialization

Modules/Core/Common/test/itkImageBufferRangeGTest.cxx, Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx
Fixed MoveAssignedRangeHasSameIterators tests from `itkImageBufferRangeGTest`
and `itkShapedImageNeighborhoodRangeGTest`, which both tested move-construction,
instead of move-assignment!
Bug found through Mac10.13-AppleClang warning: unused function template
'ExpectMoveAssignedRangeHasSameIteratorsAsOriginalBeforeMove' [-Wunused-template]
=> BUG: Fixed MoveAssignedRangeHasSameIterators GTest of two range types

Modules/Core/Common/src/itkNumberToString.cxx, Modules/ThirdParty/DoubleConversion/CMakeLists.txt
Trying to fix Microsoft/vcpkg#4334.
=> COMP: a fix for system double-conversion build

Modules/Core/Common/test/itkImageBufferRangeGTest.cxx, Modules/Core/Common/test/itkRangeGTestUtilities.h, Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx
Moved utility functions that test the expected behavior of default-constructed
ranges from itkShapedImageNeighborhoodRangeGTest.cxx and
itkImageBufferRangeGTest.cxx to itkRangeGTestUtilities.h, to reduce the amount
of duplicate code in GTest cxx files.
=> STYLE: Move test utils default-constructed ranges to RangeGTestUtilities

Modules/Core/Common/test/itkCommonTypeTraitsGTest.cxx
FixedArray satisfies `is_nothrow_move_constructible`
depending on the same property of the contained type.
The tests acts as an example showing that there is no need
to limit the flexibility of `FixedArray` adding `noexcept`
to its move constructors.
The compiler will treat the FixedArray move as noexcept or not
depending on the contained type.
Originated from discussion in #381
=> ENH: Add test checking noexcept moves in FixedArray

Modules/Core/Common/include/itkIndexRange.h, Modules/Core/Common/test/itkIndexRangeGTest.cxx
Added default-constructor to `IndexRange`, allowing to easily create an empty
range. Added `IndexRange::empty()`, which returns true for a default-constructed
range, as well as for a range that was constructed for a zero-sized region.
Added unit tests for these two member functions.
Follow-up to:
- SHA-1: e9d249e96525646c1e48151d79a3cc2a67a0af30 (8 December 2018)
- SHA-1: f4b3b39fb038b4a4f531111121010c2e38783f4b (3 January 2019)
=> ENH: Add default-constructor and empty() to IndexRange

Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx, Modules/IO/GDCM/src/itkGDCMImageIO.cxx, Modules/IO/GDCM/test/itkGDCMImageIONoCrashTest.cxx
Some images take an extremely long time to load because of GDCMImageIO::CanReadFile
takes several minutes to fail.  This is due to GDCM's default behavior of trying
to read non-compliant Dicom files that do not have the required DICM header.
This resolves #388.
NOTE:  This does break backward compatibility for default reading of degenerate Dicom files through the factory mechanism.  One can still read degenerate files by explicitly requesting the GDCM io modules.
=> PERF: DCMTK & GDCM CanRead fails very slowly for non-DICOM files.

Modules/Bridge/NumPy/wrapping/PyBuffer.i.in, Modules/Bridge/NumPy/wrapping/PyBuffer.i.init, Wrapping/Generators/Python/Tests/extras.py
The memory buffer could be lost after grafting the returned image to
another because the _ndarr member was not backed up by Graft. The added
test reproduces the problem that the patch fixes.
=> BUG: python itk.Image returned by GetImageFromArray manages its own buffer

Modules/Remote/IOSTL.remote.cmake
Jon Haitz Legarreta Gorroño (3):
ENH: Improve the `README` file.
ENH: Add CI.
DOC: Re-use `README.rst` info in `itk-module.cmake`.
Matt McCormick (1):
ENH: Enable mesh module factory registration
=> ENH: Update IOSTL to 2019-01-16 master

.circleci/config.yml
CircleCI apparently requires this file to live on the `dashboard` branch
for the branch to be ignored.
=> BUG: Add CircleCI configuration to ignore the dashboard branch

Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx, Modules/IO/GDCM/src/itkGDCMImageIO.cxx
This performance optimization returns false for DICOM files.
=> COMP: Do not use readNoPreambleDICOM with Emscripten

Testing/ContinuousIntegration/AzurePipelinesLinux.yml, Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml, Testing/ContinuousIntegration/AzurePipelinesMacOS.yml, Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml, Testing/ContinuousIntegration/AzurePipelinesWindows.yml, Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
By default, azure checks out refs/remotes/pull/<pullRequestId>/merge.
The merge changes the hash associated with the commit.
=> Fix Azure Pipelines commit checkout

Testing/ContinuousIntegration/AzurePipelinesWindows.yml, Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
The expression results in the literal "$(System.PullRequest.SourceCommitId)"
outside of pull requests.
=> BUG: Fix Azure Pipelines master checkout on Windows

Modules/IO/MeshBase/include/itkMeshFileTestHelper.h, Modules/IO/MeshBase/include/itkMeshIOBase.h, Modules/IO/MeshBase/itk-module.cmake, Modules/IO/MeshBase/src/itkMeshIOBase.cxx
Fixes the Gifti mesh IO PointDimension. The MeshIO's support a
PointDimension of 3 by default.
Add testing code and fix related bugs.
=> BUG: Default MeshIOBase PointDimension is 3

Modules/Core/Common/include/itkMatrix.h
The change allows compiling with std::complex matrices.
=> BUG: itkMatrix: Use NumericTraits::ZeroValue instead of literal 0

Modules/Filtering/ImageGrid/test/itkWarpImageFilterTest2.cxx
In
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageGrid/test/itkWarpImageFilterTest2.cxx#L111-L138
the filter is executed twice (with a different displacement field) but the outputs of each run are not disconnected from the pipeline (DisconnectPipeline), so to my understanding `result1` and `result2` point to the very same output and will always match in the following comparison which determines success of the test.
See PS in https://discourse.itk.org/t/why-resampleimagefilter-is-slow/1217/36?u=grothausmann.roman
=> BUG: avoid overwriting output in 2nd run used for comparison in test:

Wrapping/WrapITKConfig.cmake.in
`ITK_WRAP_rgba_unsigned_char` and `ITK_WRAP_rgba_unsigned_short`
were not set in `WrapITKConfig.cmake.in` which means that these variables
were not set in ITK remote modules.
=> BUG: Missing ITK_WRAP_rgba_* variables in WrapITKConfig.cmake.in

Examples/DataRepresentation/Image/Image4.cxx
Create a global definition to use inside the matrix environments,
instead of `\\`.
```latex
\gdef\NL{\\}
```
Reference:
https://tex.stackexchange.com/questions/234309/redefining-line-break-double-backslash-for-align-environment
=> COMP: Fix multi-line comment warning generated by latex notation

Documentation/ITK5MigrationGuide.md, Modules/Filtering/Thresholding/include/itkOtsuMultipleThresholdsCalculator.h, Modules/Filtering/Thresholding/include/itkOtsuMultipleThresholdsImageFilter.h, Modules/Filtering/Thresholding/include/itkOtsuThresholdCalculator.h, Modules/Filtering/Thresholding/include/itkOtsuThresholdImageFilter.h, Modules/Filtering/Thresholding/test/itkOtsuMultipleThresholdsCalculatorTest.cxx, Modules/Filtering/Thresholding/test/itkOtsuMultipleThresholdsCalculatorTest2.cxx, Modules/Filtering/Thresholding/test/itkOtsuMultipleThresholdsImageFilterTest.cxx, Modules/Filtering/Thresholding/test/itkOtsuThresholdImageFilterTest.cxx
Keep the behavior of Otsu's filters and calculators consistent with
ITKv4 when compatibility is requested with the ITKV4_COMPATIBILITY
CMake variable is enabled.
=> BUG: Use compatible ITKv4 computation

Modules/ThirdParty/Eigen3/itk-module-init.cmake
To handle missing call of find_package by other modules
in the case of ITK_USE_SYSTEM_EIGEN
Fix #357
=> ENH: Add itk-module-init.cmake to Eigen3

Modules/Core/Common/itk-module.cmake
The public dependency was imposed to avoid bogus warnings
when using Eigen headers with gcc. See related:
http://eigen.tuxfamily.org/bz/show_bug.cgi?id=640
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66472
The public dependency propagates the use of the target defined in ITKEigen3_LIBRARIES
which treats Eigen3 headers as system headers, supressing these warnings.
I have not seen these warnings with the latest release of Eigen (3.3.7),
so changing it to COMPILE_DEPENDS.
=> COMP: Make ThirdParty Eigen3 COMPILE_DEPENDS

README.md
- Focus branding on the the simpler and broader name "Insight Toolkit
(ITK)". ITK is well known as "ITK". Its use and applications go beyond
segmentation and registration on medical images. The NLM does not desire
branding of ITK.
- Add Python package installation instructions.
=> DOC: Updates to the README

Modules/Filtering/ImageGrid/test/itkResampleImageTest2.cxx
Fix `ìtkResmapleImageTest2` test failing on 32-bit systems. Fixes:
https://open.cdash.org/testDetails.php?test=728564967&build=5731782
=> BUG: Fix `ìtkResmapleImageTest2` test failing on 32-bit systems.

Modules/Filtering/ImageGrid/test/itkResampleImageTest2Streaming.cxx
There is a bug in the logic for checking if streaming did not succeed with the final commits of #392, see comments there (https://github.com/InsightSoftwareConsortium/ITK/pull/392#issuecomment-460582840).
`resample->SetInput( monitor->GetOutput() );` was called twice (https://github.com/InsightSoftwareConsortium/ITK/commit/e9f951d902f043a3eb314d7ad434735066408a26#diff-50f53fc01f72ba938548d64a1218589bL122 and https://github.com/InsightSoftwareConsortium/ITK/commit/e9f951d902f043a3eb314d7ad434735066408a26#diff-50f53fc01f72ba938548d64a1218589bL137), so removed one to avoid problems in future modifications.
Some minor changes are included as well.
=> BUG: corrected logic for checking that streaming was not used

Modules/Remote/RTK.remote.cmake
We (mainly @LucasGandel) have been working hard to make RTK a remote module of ITK for the new RTK v2.0.0 release (see SimonRit/RTK@68cb6b2). It would be an achievement to include this remote module file in the ITK repository to ease compilation of RTK for users. I'm looking forward to it!
=> ENH: add RTK as a remote module

Modules/Core/Common/include/itkMetaDataDictionary.h, Wrapping/Generators/Python/PyBase/pyBase.i
MetaDataDictionary methods are used inside the MetaDataObject class
since PR#455 so these methods need to be defined. To keep the
API the same it used to be, we do not expose them when the code is wrapped.
=> BUG: Implement but hide MetaDataDictionary iterator methods

Modules/Remote/Thickness3D.remote.cmake
This module implements filters that compute the skeleton and thickness transforms of a 3D image.
Details about the thinning/skeletonization algorithm can be found in the Insight Journal article:
Homann H.
Implementation of a 3D thinning algorithm
The Insight Journal - 2007 July - December.
http://hdl.handle.net/1926/1292
http://insight-journal.org/browse/publication/181
Medial thickness transform is a composite filter that mask the distance transform with the above thinning output.
=> ENH: Add Thickness3D Remote module.

Wrapping/Generators/Python/CMakeLists.txt
If Python library directory is not given, ITK will not find the debug Python
library when linking. It is required as this library addition is hardcoded in
pyconfig.h in the Python source code.
See https://github.com/python/cpython/blob/master/PC/pyconfig.h#L280
In theory this is only required for the debug build. But since we don't
know at configuration time if this is going to be a debug build or not,
we would need to use generator expressions which would give an empty
path if the build type is not debug. However, this is interpreted as
a relative path by CMake and is not allowed (CMP0081).
Since adding this extra path for non-debug builds is not breaking anything
we add this extra path in all cases.
Suggested-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
=> BUG: Explicitly give Python library path to ITK Python targets for MSVC

Modules/Core/Common/include/itkSymmetricEigenAnalysis.h, Modules/Core/Common/test/itkSymmetricEigenAnalysisTest.cxx
Fix `SymmetricEigenAnalysis<TMatrix, TVector, TEigenMatrix>` compile errors
when `TMatrix` = `itk::Array2D<T>`:
error C2668: 'SymmetricEigenAnalysis::GetMatrixValueType': ambiguous call to overloaded function
ITK4 already supported `Array2D<T>` as SymmetricEigenAnalysis template argument.
=> COMP: Fix SymmetricEigenAnalysis support TMatrix = itk::Array2D<T>

Modules/Core/Common/include/itkVectorContainer.h, Modules/Core/Common/include/itkVectorContainer.hxx, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkVectorContainerGTest.cxx
Fixed `itk::VectorContainer<TElementIdentifier, TElement>` compile errors
for `TElement` = `bool`:
itkVectorContainer.h(137): error C2039: 'data': is not a member of 'std::vector<TElement,std::allocator<_Ty>>'
itkVectorContainer.h(210): error C2440: 'return': cannot convert from 'std::_Vb_reference<std::_Wrap_alloc<std::allocator<std::_Vbase>>>' to 'bool &'
itkVectorContainer.hxx(40): error C2440: 'return': cannot convert from 'std::_Vb_reference<std::_Wrap_alloc<std::allocator<std::_Vbase>>>' to 'bool &'
Note: These compile errors are from Visual C++ 2017, trying to compile the added GTest before fixing `itk::VectorContainer`.
Also fixes Azure.Mac-531/Darwin-Build961 errors:
no member named 'emplace' in 'std::vector<bool>'
no member named 'emplace_back' in 'std::vector<bool>'
no matching …
=> COMP: Fix support itk::VectorContainer<TElementIdentifier, bool>

Modules/Core/Common/wrapping/itkSpatialFunction.wrap, Modules/Segmentation/SignedDistanceFunction/test/CMakeLists.txt, Modules/Segmentation/SignedDistanceFunction/wrapping/CMakeLists.txt, Modules/Segmentation/SignedDistanceFunction/wrapping/itkPCAShapeSignedDistanceFunction.wrap, Modules/Segmentation/SignedDistanceFunction/wrapping/itkShapeSignedDistanceFunction.wrap
`itkPCAShapeSignedDistanceFunction` was not wrapped. Wrap it for `double`
CoordRep (only type supported since OptimizerParameters is hardcoded as
templated over `double`)  and for the space dimensions that have been
selected by the user. It is only wrapped for the default image type which
is `itk::Image<double, VSpaceDimension>`.
=> ENH: Wrap itkPCAShapeSignedDistanceFunction

.github/stale.yml
This is the configuration for the probot-stale GitHub App:
https://probot.github.io/apps/stale/
that automatically close stale Issues and Pull Requests that tend to accumulate during a project.
=> ENH: Add probot-stale GitHub bot configuration

Testing/ContinuousIntegration/AzurePipelinesLinux.yml, Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml, Testing/ContinuousIntegration/AzurePipelinesMacOS.yml, Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml, Testing/ContinuousIntegration/AzurePipelinesWindows.yml, Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
Using scikit-ci-addons `ctest_junit_formatter`, test result
visualizations are available in the Azure Pipelines web interface in a
build's interface under the "Tests" tab.
=> ENH: Add test result analysis to Azure Pipelines web interface

Modules/Core/Common/include/itkDefaultConvertPixelTraits.h, Modules/Core/Common/include/itkMultiThreaderBase.h
Template classes and template funcitons which don't explicitly specify
linkage can create symbols with mixed linkages which results in a
warning. Add missing specification to template member functions and
classes producing warnings.
=> COMP: Address OSX Clang "direct access" linkage warnings

Modules/Core/Common/include/itkVectorContainer.hxx
Member function return types `typename VectorContainer::const_reference` and
`typename VectorContainer::reference` triggered compile errors on MSVC
(VS2017), when using /permissive- (Standards conformance), as reported by
@QuellaZhang issue #506:
itkVectorContainer.hxx(38,1): error C2244: 'itk::VectorContainer<TElementIdentifier,TElement>::ElementAt': unable to match function definition to an existing declaration
This commit declares them as trailing return types, in order to fix this issue.
=> COMP: Trailing return types (reference, const_reference) VectorContainer

Modules/Core/ImageFunction/include/itkGaussianDerivativeImageFunction.h, Modules/Core/ImageFunction/include/itkGaussianDerivativeImageFunction.hxx, Modules/Filtering/ImageFeature/include/itkHoughTransform2DCirclesImageFilter.h, Modules/Filtering/ImageFeature/include/itkHoughTransform2DCirclesImageFilter.hxx
Now using C++11 in-class default member initializers, instead of constructor
member-initializer-lists, for `m_GradientNormThreshold` and `m_UseImageSpacing`,
in `HoughTransform2DCirclesImageFilter` and `GaussianDerivativeImageFunction`.
This has the advantage the initial (default) values will appear in Doxygen
generated ITK documentation.
Follow-up to b21dbbb2938911206d9259d3777b163d257031cd
(@hjmjohnson, December 17, 2018, "STYLE: Use default member initialization")
=> STYLE: HoughTransform2DCircles, GaussianDerivativeImageFunc member init.

Wrapping/Generators/Python/CMakeLists.txt
In ITK 4.13, the Python tests have not been moved to their corresponding
module. This means that if the module the test is testing has been
disabled, the test will fail. To avoid that problem, the Python tests
are disabled if `ITK_BUILD_DEFAULT_MODULES` is OFF.
=> BUG: Disable Python tests if `ITK_BUILD_DEFAULT_MODULES` is OFF

Modules/IO/TransformBase/include/itkTransformIOBase.h, Modules/IO/TransformHDF5/include/itkHDF5TransformIO.hxx
Class instance variables should be private, unless well documented
performance issues can be overcome by allowing them to be protected.
The one location were derived class used instance variable directly
was not benefiting (performance wise) significantly to justify
making the variables protected.
=> STYLE: Instance variables should be private

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Change GitHub community template guidelines to HTML comment markup. This
allows the guidelines to be displayed when opening a PR or an issue, but
will not be part of them.
Take advantage of the commit to improve the `bug_report.md` template
guidelines.
=> DOC: Change GitHub community template guidelines to HTML comment markup.

Modules/Core/Common/include/itkWin32Header.h
itkWin32Header.h (which is included by itkMacro.h) no longer disables the
following Visual C++ warnings:
* C4800 "forcing value to bool", which is easy to avoid
* C4290 "exception specification ignored", which only occurs on deprecated
C++98 exception specifications.
* C4786 "object name was truncated", which is already off by default
=> COMP: Win32Header no longer disable MSVC warning C4800, C4290, C4786

Documentation/ITK5MigrationGuide.md, Modules/Core/ImageFunction/include/itkGaussianDerivativeImageFunction.h, Modules/Core/ImageFunction/include/itkGaussianDerivativeImageFunction.hxx, Modules/Core/ImageFunction/test/itkGaussianDerivativeImageFunctionTest.cxx
Renamed nested `GaussianDerivativeImageFunction` identifiers to improve code readability:
* `ImageDimension2` to `ImageDimension`
* `GaussianDerivativeFunctionType` to `GaussianDerivativeSpatialFunctionType`
* `GaussianDerivativeFunctionPointer` to `GaussianDerivativeSpatialFunctionPointer`
* `m_GaussianDerivativeFunction` to `m_GaussianDerivativeSpatialFunction`
=> STYLE: Improved GaussianDerivativeImageFunction identifiers

Modules/Core/Common/include/itkPrintHelper.h, Modules/Core/ImageFunction/include/itkBSplineDecompositionImageFilter.hxx, Modules/Filtering/ImageGrid/include/itkBSplineScatteredDataPointSetToImageFilter.hxx, Modules/Filtering/Thresholding/include/itkThresholdLabelerImageFilter.hxx, Modules/IO/ImageBase/src/itkImageIOBase.cxx, Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkMRFImageFilter.hxx
Add a new `itkPrintHelper.h` file to help in printing `std::vector`s.
Change-Id: I2306c8bf44cd0cec9661c3515c0a77cfbc34ea88
=> ENH: Add a PrintHelper file to overload vector printing.

Modules/IO/DCMTK/src/itkDCMTKFileReader.cxx
The change in the API of DcmDataDictionary was introduced in the commit:
https://github.com/DCMTK/dcmtk/commit/1e6aefdf8081263d192a9ed6a8241dac31401b47#diff-7f734e6993454e7b234c1f352bad0fb6
This corresponds to version 364 of DCMTK
=> BUG: Fix OFFIS_DMCTK_VERSION_NUMBER where wrunlock was introduced

Modules/Core/Common/include/itkWin32Header.h, Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/src/Core/products/Parallelizer.h
https://gitlab.kitware.com/phcerdan/eigen.git
at commit 0805e8fd8f3251a08002478b5059ec2c2be62429 (for/itk).
Fix warning:
Eigen/src/Core/products/Parallelizer.h:25:5: warning:
'm_maxThreads' was marked unused but was used [-Wused-but-marked-unused]
m_maxThreads = *v;
https://open.cdash.org/viewBuildError.php?type=1&buildid=5785448
This was reported upstream:
http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1689
Change-Id: If33ae505cc26474200851b4096c6c7488a4db2f1
=> Eigen3 2019-03-05 (0805e8fd)

Modules/Registration/Common/include/itkImageToImageMetric.h, Modules/Registration/Common/include/itkImageToImageMetric.hxx, Modules/Registration/Common/test/itkMattesMutualInformationImageToImageMetricTest.cxx
Modules/Registration/Common/include/itkImageToImageMetric.hxx:1331:3:
warning: cast from type 'const itk::ImageToImageMetric<itk::Image<float, 2u>, itk::Image<float, 2u> >::MultiThreaderParameterType*' to type 'void*' casts away qualifiers [-Wcast-qual]
=> COMP: Remove casts away qualifiers warning

Modules/Compatibility/Deprecated/include/itkConditionVariable.h, Modules/Compatibility/Deprecated/include/itkFastMutexLock.h, Modules/Compatibility/Deprecated/include/itkMutexLock.h, Modules/Compatibility/Deprecated/include/itkSimpleFastMutexLock.h
It was using the export macros from their old `Common` module.
Errors:
```
ITK-build\Modules\Compatibility\Deprecated\src\ITKDeprecated.vcxproj" (default target) (32) ->
(Link target) ->
10>itkConditionVariable.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) const itk::ConditionVariable::`vftable'" (__imp_??_7ConditionVariable@itk@@6B@) referenced in function "protected: __cdecl itk::ConditionVariable::ConditionVariable(void)" (??0ConditionVariable@itk@@IEAA@XZ) [ITK-build\Modules\Compatibility\Deprecated\src\ITKDeprecated.vcxproj] [ITK.vcxproj]
10>itkMutexLock.obj : error LNK2001: unresolved external symbol "public: virtual char const * __cdecl itk::SimpleMutexLock::GetNameOfClass(void)" (?GetNameOfClass@SimpleMutexLock@itk@@UEAAPEBDXZ) …
```
=> BUG: Fix export for ITKDeprecated classes

Modules/Core/Common/include/itkConstShapedNeighborhoodIterator.h
Removed the protected `ConstShapedNeighborhoodIterator` member function
`InitializeConstShapedNeighborhoodIterator()`, a helper function of the
user-defined constructors of the class, which only just assigned a value
to a single data member. Instead, just initialized that data member by a
C++11 in-class member initializer.
Fixes VS2017 /analyze (C++ Core Guidelines) warning C26495:
Variable 'm_CenterIsActive' is uninitialized. Always initialize a member variable (type.6).
=> STYLE: Removed InitializeConstShapedNeighborhoodIterator()

CMake/ITKSetStandardCompilerFlags.cmake, Modules/ThirdParty/VNL/src/vxl/CMakeLists.txt
String comparison is not necessarily correct.
=> BUG: Use VERSION_GREATER_EQUAL for PIE check

Modules/ThirdParty/Eigen3/src/itkeigen/CMakeLists.txt
```
git shortlog --no-merges  0805e8fd8..8a3c2d91
Pablo Hernandez-Cerdan (1):
BUG: ITK: CMake files are now installed in ITK_INSTALL_PACKAGE_DIR/Modules
```
Includes  patch:
BUG: ITK: CMake files are now installed in ITK_INSTALL_PACKAGE_DIR/Modules
Instead of hard coded path including the version.
When using `ITK_INSTALL_PACKAGE_DIR=lib/cmake/ITK`
Before (wrong):
```bash
]$ find ITK-prefix | grep Eigen3
ITK-prefix/lib/cmake/ITK-5.0/Modules/Eigen3Config.cmake
ITK-prefix/lib/cmake/ITK-5.0/Modules/Eigen3ConfigVersion.cmake
ITK-prefix/lib/cmake/ITK-5.0/Modules/ITKInternalEigen3Config.cmake
ITK-prefix/lib/cmake/ITK-5.0/Modules/ITKInternalEigen3Targets.cmake
ITK-prefix/lib/cmake/ITK-5.0/Modules/ITKInternalEigen3ConfigVersion.cmake
ITK-prefix/lib/cmake/ITK-5.0/Modules/Eigen3Targets.cmake …
```
=> BUG: Update Eigen3 to fix INSTALL_DIR problems

Modules/Filtering/Thresholding/include/itkLiThresholdCalculator.hxx
The histogram values are shifted by the minimum bin value to prevent
taking a log of a negative number.
=> BUG: Fix Li threshold calculator for negative image values

Modules/Filtering/FastMarching/include/itkFastMarchingBase.h, Modules/Filtering/FastMarching/include/itkFastMarchingImageFilter.h, Modules/Filtering/FastMarching/test/itkFastMarchingExtensionImageFilterTest.cxx, Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterBaseTest.cxx, Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterRealTest1.cxx, Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterRealTest2.cxx, Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterRealWithNumberOfElementsTest.cxx, Modules/Filtering/FastMarching/test/itkFastMarchingTest.cxx, Modules/Filtering/FastMarching/test/itkFastMarchingTest2.cxx, Modules/Filtering/FastMarching/test/itkFastMarchingUpwindGradientBaseTest.cxx, Modules/Filtering/FastMarching/test/itkFastMarchingUpwindGradientTest.cxx
Exercise basic object methods.
Test all Set/Get methods using the TEST_SET_GET_VALUE macro, and all
On/Off methods corresponding to boolean members usign the
TEST_SET_GET_BOOLEAN macro.
Use the TRY_EXPECT_NO_EXCEPTION macro to update the filter and save
tryping the try/catch blocks.
Prefer initialization over assignment in variables.
Use the itkNotUsed macro for test input arguments and hence avoid
casting argc and argv to void to avoid compiler warnings.
Remove printing the input (speed) image.
Remove the calls to the Get* methods corresponding to base class
members (specifically: m_SpeedConstant, m_TargetReachedValue, and
m_NormalizationFactor should be tested for itk::FastMarchingBase in
itkFastMarchingBaseTest.cxx; and m_StoppingValue and GetCollectPoints
should be tested for …
=> ENH: Improve coverage for itk::FastMarchingImageFilterBase.

Modules/Filtering/Thresholding/include/itkLiThresholdCalculator.hxx
This is a follow-up to:
https://github.com/InsightSoftwareConsortium/ITK/pull/135
To address:
In file included from /home/kitware/mattm/ITK/Modules/Filtering/Thresholding/include/itkLiThresholdCalculator.h:87:0,
from Wrapping/Typedefs/itkLiThresholdCalculatorSwigInterface.h:19,
from Wrapping/Modules/ITKThresholding/itkLiThresholdCalculatorPython.cpp:3371:
/home/kitware/mattm/ITK/Modules/Filtering/Thresholding/include/itkLiThresholdCalculator.hxx: In instantiation of ‘void itk::LiThresholdCalculator<THistogram, TOutput>::GenerateData() [with THistogram = itk::Statistics::Histogram<float>; TOutput = float]’:
Wrapping/Modules/ITKThresholding/itkLiThresholdCalculatorPython.cpp:8112:1:   required from here
/home/kitware/mattm/ITK/Modules/Filtering/Thresholding/include/itkLiThresholdCalculator.h …
=> COMP: Specify type in LiThresholdCalculator min call

Modules/Core/Mesh/test/itkMeshTest.cxx
Fix for #438.
When using `-O3`, GCC attempts to directly allocate an array by copying the values provided. However, a quadratic triangle expects 6 points so it reads out of bounds.
=> BUG: Initialize array with expected number of elements

Modules/IO/TIFF/src/itkTIFFImageIO.cxx
Fixes #574.
This is a known bug from [Libtiff](http://bugzilla.maptools.org/show_bug.cgi?id=2073).
=> BUG: Disable TIFF predictor

CMake/ITKSetStandardCompilerFlags.cmake
GCC version 4.0.4 had a bug in the -frename-registers
option used by -funroll-loops.
As of GCC version 4.1.0 and greater, this optimiation
was fixed.
ITK should no longer prohibit this optimization.
GCC 4.0.4 documentation
-frename-registers
Attempt to avoid false dependencies in scheduled code by making use of registers
left over after register allocation. This optimization will most benefit processors
with lots of registers. Depending on the debug information format adopted by
the target, however, it can make debugging impossible, since variables will no
longer stay in a “home register”.
*** Not enabled by default at any level because it has known bugs.
GCC 4.1.0 documentation
-frename-registers
Attempt to avoid false dependencies in scheduled code by making use of registers
left over …
=> COMP: Allow compiler option fixed in gcc 4.1.0

Documentation/ITK5MigrationGuide.md
Added overview and details on changes made to SpatialObjects as part of the refactoring.   The changes introduced by the refactoring are extensive, and so we have focused on conveying the new philosophy and style guidelines in the migration guide.
=> DOC: SpatialObject docs in migration guide

Wrapping/Generators/Python/itkTemplate.py
In Python3 the keys of an `OrderedDict` are of type `odict_keys` and cannot use indexing.
These changes allow `PythonTemplateTest.py` to pass with Python3.
=> BUG: Python3 compatibility

Modules/IO/ImageBase/include/itkImageFileReader.hxx
Simplified `ImageFileReader::GenerateData()` implementation by declaring
its local `loadBuffer` as `const std::unique_ptr<char[]>`, instead of as
a raw `char` pointer.
Removed try-catch-throw and `delete[]` statements that are no longer necessary
now, due to the C++ "RAII" idiom implemented by `std::unique_ptr`.
Replaced a `std::copy` by `std::copy_n`, to further simplify the code.
=> STYLE: ImageFileReader uses std::unique_ptr<[]>, try-catch-throw removed

Documentation/Maintenance/Release.md, Utilities/Maintenance/UpdateRemoteModules.sh
Add a script to update the remote module commit hashes.
Update the `Release.md` guide to add the remote module update step prior
to a release.
=> ENH: Add a script to update the remote module commit hashes

Utilities/Maintenance/UpdateRequiredITKVersionInFiles.sh
Add a script to update the ITK tag as required in
- `azure-pipelines.yaml` Azure pipelines configuration file.
- `setup.py` Python setup files.
usually in the `Remote` modules.
=> ENH: Add a script to update the ITK tag as required in files

Modules/Filtering/ImageGrid/test/CMakeLists.txt
relates to #0392 
and intends to not only take the return value into account but also the comparison of the output with the expected results.
@thewtex in relation to https://github.com/InsightSoftwareConsortium/ITK/pull/392#issuecomment-460892360: Since it is necessary for streaming to write to MHAs (not PNGs as originally the case), the output is uncoupled from `itkResampleImageTest2`, so I guess we do not need the `DEPENDS` property.
I am not sure though if it is critical that the second input comes from PNG `circle.png`, which is not available as MHA. I noticed that you changed the first input from PNG to MHA `cthead1.mha`. Is that necessary for successful streaming and would the same apply for the reference image?
Just using `cthead1.mha` as second input again is probably not good in …
=> ENH: compare outputs of itkResampleImageTest2Streaming to determine success

Examples/Segmentation/HoughTransform2DCirclesImageFilter.cxx, Examples/SpatialObjects/EllipseSpatialObject.cxx, Modules/Core/SpatialObjects/include/itkEllipseSpatialObject.h, Modules/Core/SpatialObjects/include/itkEllipseSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkMetaEllipseConverter.hxx, Modules/Core/SpatialObjects/test/itkEllipseSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkSpatialObjectDuplicatorTest.cxx, Modules/Core/SpatialObjects/test/itkSpatialObjectToImageStatisticsCalculatorTest.cxx, Modules/Filtering/ImageFeature/include/itkHoughTransform2DCirclesImageFilter.hxx, Modules/Filtering/ImageFeature/test/itkHoughTransform2DCirclesImageTest.cxx, Modules/IO/SpatialObjects/test/itkReadWriteSpatialObjectTest.cxx
Renamed the array of radii of `EllipseSpatialObject` from
`RadiusInObjectSpace` to `RadiiInObjectSpace`.
Thereby it can be distinguished more clearly from use cases where
there is only one radius.
=> STYLE: Renamed array of radii EllipseSpatialObject to RadiiInObjectSpace

Documentation/ITK5MigrationGuide.md
GetAxisAlignedBoundingBoxRegion has been removed and now an alternative (GetMyBoundingBoxInObjectSpace) is indicated.
=> DOC: Detail function change in ImageMaskSpatialObject

Modules/Core/Common/include/itkImageAlgorithm.h, Modules/Core/Common/include/itkImageAlgorithm.hxx, Modules/Core/Common/test/itkImageTest.cxx, Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx, Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx, Modules/Filtering/ImageGrid/test/CMakeLists.txt, Modules/Filtering/ImageGrid/test/itkResampleImageTest2Streaming.cxx, Modules/Filtering/ImageGrid/test/itkResampleImageTest4.cxx, Modules/Filtering/ImageGrid/test/itkResampleImageTest7.cxx
This PR corresponds to #82, rebased onto master, meant for inclusion into master (ITK-5 instead of ITK-4.13.1). 
Inspired by the discussion of the discourse topic [Why ResampleImageFilter is slow?](https://discourse.itk.org/t/why-resampleimagefilter-is-slow/1217), this PR is a try to realize streaming for at least some transforms for the `itkResampleImageFilter`. 
It is one of the most general filters in ITK and much used and the essential one for isotropic down-sampling of large datasets. Especially for that case it would be very helpful to have streaming capabilities, in order to generate smaller datasets for filters that cannot stream. Apart from a reduced memory footprint, streaming can lead to a significant speed up because a chunk can be processed while the next is loaded from disc, …
=> Streaming for itkResampleImageFilter in case of linear transforms

Modules/Core/Common/wrapping/itkImageDuplicator.wrap, Wrapping/WrapITKTypes.cmake
NumPyBridge uses the itkImageDuplicator filter to copy images, so all image
types need to be supported (wrapped) for this filter to be able to convert
all ITK images into NumPy arrays.
=> BUG: Wrap itkImageDuplicator for all image types

Modules/Core/Common/include/itkIntTypes.h
=> ENH: ModifiedTimeType uses 64 bits on Windows - it was 32 before

Modules/Segmentation/SignedDistanceFunction/wrapping/itkPCAShapeSignedDistanceFunction.wrap
Exposing 3rd template argument of itkPCAShapeSignedDistanceFunction
which defaults to double images in C++. This patch allows to use
another image type such as float images.
=> ENH: itkPCAShapeSignedDistanceFunction supports float images

Utilities/Maintenance/UpdateRequiredITKVersionInFiles.sh
Update the Remote module Python package version to a new major version
automatically when updating the required ITK version.
=> ENH: Update the Remote module Python package version automatically

Documentation/Maintenance/Release.md
Add Remote module PyPI update notice in Release guide.
Take advantage of the commit to add the name of the script that commit
e0fe885 left behind.
=> DOC: Add Remote module PyPI update notice in Release guide

Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.h, Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.hxx
In ContourExtractor2DImageFilter
=> STYLE: header included twice, spelling

Modules/Core/SpatialObjects/include/itkImageSpatialObject.h, Modules/Core/SpatialObjects/include/itkImageSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkMeshSpatialObject.h, Modules/Core/SpatialObjects/include/itkMeshSpatialObject.hxx
Deprecates the `GetPixelTypeName()` member functions of both
`ImageSpatialObject` and `MeshSpatialObject`. Removes their `m_PixelType` data
members, when `ITK_LEGACY_REMOVE` is enabled.
It appears that there was an inconsistency between these two member functions,
as the one for `Mesh` returned `typeid(PixelType).name()`, which is compiler
dependent, while the one for `Image` depended on a set of overloaded
`SetPixelTypeName` member functions. Both added unnecessary overhead by storing
an `std::string`. It seems that `GetPixelTypeName()` was rarely used.
=> STYLE: Remove GetPixelTypeName() from both Image and Mesh SpatialObject

Modules/Core/Common/test/itkLogTester.h, Modules/Core/Common/test/itkLoggerManagerTest.cxx, Modules/Core/Common/test/itkLoggerTest.cxx, Modules/Core/Common/test/itkLoggerThreadWrapperTest.cxx, Modules/Core/Common/test/itkThreadLoggerTest.cxx
ITK/Modules/Core/Common/test/itkLoggerThreadWrapperTest.cxx:100:7: warning: type ‘struct LogTester’ violates the C++ One Definition Rule [-Wodr]
class LogTester
^
ITK/Modules/Core/Common/test/itkThreadLoggerTest.cxx:33:7: note: a different type is defined in another translation unit
class LogTester
^
ITK/Modules/Core/Common/test/itkLoggerThreadWrapperTest.cxx:125:20: note: the first difference of corresponding definitions is field ‘m_Logger’
itk::LoggerBase* m_Logger;
^
=> COMP: Consolodate duplicate LogTester code

Modules/Core/SpatialObjects/include/itkSpatialObject.h
When building with ITK_FUTURE_LEGACY_REMOVE option, the
itkLegacyMacro leads to incorrect syntax when the code
is not explicitly skipped.
=> COMP: Support ITK_FUTURE_LEGACY_REMOVE for SpatialObjects

Modules/Segmentation/LevelSetsv4/test/itkBinaryImageToMalcolmSparseLevelSetAdaptorTest.cxx
Do not swamp standard output by default. This cuts down on test log size.
=> ENH: introduce a parameter to control level of output

Examples/Segmentation/HoughTransform2DCirclesImageFilter.cxx, Examples/SpatialObjects/EllipseSpatialObject.cxx, Modules/Core/SpatialObjects/include/itkEllipseSpatialObject.h, Modules/Core/SpatialObjects/include/itkEllipseSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkGaussianSpatialObject.h, Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.h, Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkMetaEllipseConverter.hxx, Modules/Core/SpatialObjects/include/itkSpatialObject.h, Modules/Core/SpatialObjects/test/itkEllipseSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkSpatialObjectDuplicatorTest.cxx, Modules/Core/SpatialObjects/test/itkSpatialObjectToImageStatisticsCalculatorTest.cxx, Modules/Filtering/ImageFeature/include/itkHoughTransform2DCirclesImageFilter.hxx, Modules/Filtering/ImageFeature/test/itkHoughTransform2DCirclesImageTest.cxx, Modules/IO/SpatialObjects/test/itkReadWriteSpatialObjectTest.cxx
Provide an easier path to upgrade by providing
the legacy interfaces to the SpatialObjects.
Providing warnings during initial builds allow
for more gradual migration, and fewer errors
during conversion to the new API.
=> ENH: Add legacy interface to SpatialObjects

Modules/Core/Common/include/itkImageAlgorithm.h, Modules/Core/Common/include/itkImageAlgorithm.hxx
This PR modifies PR #674 and now compiles in RTK, see [dashboard](https://my.cdash.org/buildSummary.php?buildid=1630838) . I don't think the solution is very elegant but I could not find a better solution. Other options:
- use a default template argument (e.g., itk::IdentityTransform) but no Transform is available in this module (Core/Common).
- add another templated function containing the TransformPoint line with a specialization doing nothing for a dummy type (e.g. nullptr_t).
Please have a look @thewtex @romangrothausmann. If you have another suggestion, don't hesitate! BTW, the problem does not seem to arise on linux, see [dashboard](https://my.cdash.org/buildSummary.php?buildid=1630585), I really don't know why.
=> COMP: Add backwards compatible EnlargeRegionOverBox

Modules/Core/SpatialObjects/test/CMakeLists.txt, Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectGTest.cxx
Added GoogleTest for the `ImageMaskSpatialObject` legacy member function
`GetAxisAlignedBoundingBoxRegion()`.
=> ENH: GTest for ImageMaskSpatialObject::GetAxisAlignedBoundingBoxRegion()

CMake/ITKModuleTest.cmake, CMakeLists.txt
This option allows to skip building the itkTestDrivers and therefore
can speed up compilation time. This is especially useful on CI
where the tests using these itkTestDrivers can be run for certain
builds that do not risk to time out (i.e. no wrapping).
=> ENH: Add advanced CMake option `ITK_DO_NOT_BUILD_TESTDRIVERS`

Modules/Core/Common/include/itkEventObject.h
Removed unused `EventFactoryFunction` type, in response to Sandro Queiros,
who reported VS2015 compile errors at forum topic "Build ITK 5.0 in Windows",
https://discourse.itk.org/t/build-itk-5-0-in-windows/1748 saying:
itkEventObject.h(96): error C2071: ‘itk::EventObject::EventFactoryFunction’: illegal storage class
Follow-up to the removal of an `std::map< std::string, EventFactoryFunction >`,
by Luis Ibanez, 2001-11-12, commit 16b9d79d8837b62b1d51394614b2b10aa277c58e
=> STYLE: Removed unused private EventObject::EventFactoryFunction type

Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.h, Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.hxx, Modules/Core/SpatialObjects/test/itkTubeSpatialObjectTest.cxx
This PR resolves #692 by adding the `RemovePoint( IdentifierType id )` function to `PointBasedSpatialObjects`.   Also adds tests to the `TubeSpatialObjectTest.cxx` file.
=> BUG: Adds RemovePoint() to PointBasedSpatialObjects

Modules/Core/SpatialObjects/include/itkArrowSpatialObject.h, Modules/Core/SpatialObjects/include/itkArrowSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkBoxSpatialObject.h, Modules/Core/SpatialObjects/include/itkBoxSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkContourSpatialObject.h, Modules/Core/SpatialObjects/include/itkContourSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkEllipseSpatialObject.h, Modules/Core/SpatialObjects/include/itkEllipseSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkGaussianSpatialObject.h, Modules/Core/SpatialObjects/include/itkGaussianSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkGroupSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkImageSpatialObject.h, Modules/Core/SpatialObjects/include/itkImageSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkMeshSpatialObject.h, Modules/Core/SpatialObjects/include/itkMeshSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.h, Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkPolygonSpatialObject.h, Modules/Core/SpatialObjects/include/itkPolygonSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkSpatialObject.h, Modules/Core/SpatialObjects/include/itkSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkSpatialObjectProperty.h, Modules/Core/SpatialObjects/include/itkSurfaceSpatialObject.h, Modules/Core/SpatialObjects/include/itkSurfaceSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkTubeSpatialObject.h, Modules/Core/SpatialObjects/include/itkTubeSpatialObject.hxx, Modules/Core/SpatialObjects/src/itkSpatialObjectProperty.cxx, Modules/Core/SpatialObjects/test/SpatialObjectTest.py
Added Clear() function to reset a SpatialObject to its initial
conditions, without changing Id, Parent, or Children.
Also, required removing exception if a point-based object has no points
when update() is called (as is the case when it is initialized).
=> BUG: Adding a consistent Clear() to SpatialObjects

Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectTest2.cxx
While investigating other issues that appear to be related to SpatialObject update, I have fortified this test.  This is an attempt to isolate the issue with the new spatial objects (which this patch set does not do), but is still a valuable enhancement to the test.
=> Enh make test of non orthogonal image spatial objects

azure_dashboard.cmake
`_dashboard_cache` which contains the initialization of ITK configuration
should now be done directly in the file calling azure_dashboard.cmake.
In the current setting, this means that the YML configuration files of
the CI should create a CMake file that initializes this variable and
then include `azure_dashboard.cmake`.
=> Move configuration of _dashboard_cache out of azure_dashboard.cmake

Testing/ContinuousIntegration/AzurePipelinesBatch.yml, Testing/ContinuousIntegration/AzurePipelinesLinux.yml, Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml, Testing/ContinuousIntegration/AzurePipelinesMacOS.yml, Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml, Testing/ContinuousIntegration/AzurePipelinesWindows.yml, Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
CI configuration was done through environment variables that were then
interpreted in a CTest configuration script shipped in the dashboard branch
of ITK. This implementation required to modified both the master branch
and the dashboard branch if new options had to be controled from the YML
configuration files. For ITK remote modules, the configuration is already
done directly inside the YML configuration file. This patch moves the CI
configuration for ITK inside the master branch the same way it is done for
remote modules.
=> Move CI configuration into Azure YML files

azure_dashboard.cmake
This is a follow up PR for [1] which did not remove this line
of code, but should have removed it.
[1] https://github.com/InsightSoftwareConsortium/ITK/commit/1902ab7be33b7d8b42b78a5ac5b3b319153d33f6
=> BUG: Remove setting `dashboard_cache` from environment variable.

Modules/Core/Common/include/itkMultiThreaderBase.h
Silenced "ThreadInfoStruct is deprecated" warning when the user has switched on
the ITK CMake option `ITK_LEGACY_SILENT`.
=> COMP: Support ITK_LEGACY_SILENT for ThreadInfoStruct

Modules/Core/SpatialObjects/include/itkImageSpatialObject.h
Removed unused nested type aliases from `itk::ImageSpatialObject`:
* RegionType
* TransformType
* BoundingBoxType
* PointContainerType
* PointContainerPointer
=> STYLE: Removed five unused nested types from ImageSpatialObject

Modules/Core/Common/include/itkSize.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkSizeGTest.cxx
Added static `itk::Size<VDimension>` member function `Filled(value)`,
analogue to `FixedArray::Filled(value)`.
This convenience function should ease, for example, creating an NxN
image, or an NxNxN volume.
=> ENH: Add static member function Size<VDimension>::Filled(SizeValueType)

Modules/Core/SpatialObjects/include/itkArrowSpatialObject.h, Modules/Core/SpatialObjects/include/itkArrowSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkBoxSpatialObject.h, Modules/Core/SpatialObjects/include/itkBoxSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkEllipseSpatialObject.h, Modules/Core/SpatialObjects/include/itkEllipseSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkGaussianSpatialObject.h, Modules/Core/SpatialObjects/include/itkGaussianSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.h, Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkImageSpatialObject.h, Modules/Core/SpatialObjects/include/itkImageSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkMeshSpatialObject.h, Modules/Core/SpatialObjects/include/itkMeshSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.h, Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkSpatialObject.h, Modules/Core/SpatialObjects/include/itkSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkTubeSpatialObject.h, Modules/Core/SpatialObjects/include/itkTubeSpatialObject.hxx
An essential property of the virtual member function `ComputeMyBoundingBox()`
is that it modifies the data of the `SpatialObject` (specifically, the member
function modifies its `MyBoundingBoxInObjectSpace` data member).
So even though the compiler "allows" the member function to be declared
`const`, the semantics of the member function (and its overrides) appear
logically non-const.
=> STYLE: Remove const from SpatialObject::ComputeMyBoundingBox()

Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/SharedTestLibraryA.h, Modules/Core/Common/test/SharedTestLibraryB.h
Export and Import symbols was not generated and added to the libraries
that are created for the test `itkObjectFactoryBasePrivateDestructor`.
Executable for test could not be compiled correctly on MSVC.
=> BUG: itkObjectFactoryBasePrivateDestructor was not compiling with MSVC

Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx, Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectGTest.cxx
* Extended GTest for `ImageMaskSpatialObject::GetAxisAlignedBoundingBoxRegion()`
* Fixed #734 ("Incorrect results GetAxisAlignedBoundingBoxRegion() for 2D")
=> BUG: Fix #734 and extend GTest for GetAxisAlignedBoundingBoxRegion

Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx
Made `ImageMaskSpatialObject::GetAxisAlignedBoundingBoxRegion()` many times (!)
faster than before.
The amount of the speed improvement depends on the input image: For a black 3D
image of 256x256x256, it was observed than the function runs more than 10 x
faster than before. For a 2D image of 1024x1024 with non-zero border pixels,
it was observed than the function runs even more than 100 x faster!
=> PERF: ImageMaskSpatialObject::GetAxisAlignedBoundingBoxRegion() faster

Utilities/Maintenance/UpdateRemoteModules.sh
Fixes #682 and #685.
This updated version of `UpdateRemoteModules.sh` uses more constraining parsing rules to avoid issues and removes version specific syntax to be more portable.
It also adds the option `-ongreen` to update only if the latest build was successful.
=> ENH: Update remote module maintenance script

Modules/Core/SpatialObjects/include/itkSpatialObject.h, Modules/Core/SpatialObjects/include/itkSpatialObject.hxx
Removed `const` keyword from the protected `SpatialObject` member function
`GetModifiableMyBoundingBoxInObjectSpace()`, as it allows modifying the
bounding box of the spatial object.
This is consistent with the other `GetModifiable...` member functions in ITK,
which are all non-const as well.
=> STYLE: SpatialObject GetModifiableMyBoundingBoxInObjectSpace() non-const

Modules/Segmentation/LevelSets/test/itkImplicitManifoldNormalVectorFilterTest.cxx
This is a fix for the segfaults in #713.
This test was redeclaring `NormalBandNode` but the class had since been updated. It seems that when using MinSizeRel, AppleClang was favoring this outdated declaration, causing segmentation faults when confusing attributes.
Concerning the two tests failing without segfaults in #713, I was never able to reproduce the problem.
=> BUG: Remove outdated class declaration

Examples/Filtering/SpatialObjectToImage3.cxx, Modules/Core/SpatialObjects/include/itkPolygonSpatialObject.hxx
The new implementation now defaults to "IsClosed" being true and
appropriately computes IsInside.  Previously variables (node1 and
node2) were not correctly initialized.
This PR superseeds #747 to address one comment.
=> BUG: Fix IsInsideObjectSpace function in PolygonSpatialObject

Modules/Core/Common/include/itkFixedArray.h, Modules/Core/Common/include/itkPoint.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkPointGTest.cxx
Added `explicit` `Point` and `FixedArray` constructors, allowing to specify
their elements by a C++11 `std::array`. Added `itkPointGTest` to test this
new feature.
=> ENH: Add explicit constructors Point and FixedArray for C++11 std::array

Modules/Core/Common/include/itkExtractImageFilter.hxx, Modules/Core/TestKernel/include/itkTestingExtractSliceImageFilter.hxx
The original "OutputImageDimension-InputImageDimension" computation
resulted in underflow error and a very confusing message when the output
dimension was less than the input dimension.  Provide an expanded
diagnostic message to improve the understanding of what the failure
was."
=> DOC: Improve diagnostic message from ExtractImageFilter

Modules/Core/ImageFunction/test/itkGaussianInterpolateImageFunctionTest.cxx, Modules/Core/ImageFunction/test/itkLinearInterpolateImageFunctionTest.cxx
This is a fix for the 2 failing tests without segfault in #713.
It turns out that `itkGaussianInterpolateImageFunctionTest` was always broken, but when it called its `RunTest` function, the one in `itkLinearInterpolateImageFunctionTest` was ran instead. AppleClang with MinSizeRel just happened to confuse them the other way around.
I replaced the test with a basic regression check.
=> BUG: fix gaussian interpolate test

Modules/Bridge/VtkGlue/CMakeLists.txt, Modules/Bridge/VtkGlue/src/CMakeLists.txt, Modules/Bridge/VtkGlue/test/CMakeLists.txt, Utilities/Maintenance/BuildHeaderTest.py
Enable the use of ITKVtkGlue functionality that does not require
rendering when VTK was built with VTK_RENDERING_BACKEND set to None.
Addresses #714 
@romangrothausmann additional testing would be appreciated :bowing_man: .
=> ENH: ITKVtkGlue only requires rendering libraries when needed

Modules/Core/Common/include/itkFixedArray.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkFixedArrayGTest.cxx
Added `begin()`, `end()`, `cbegin()`, `cend()`, `iterator`, and
`const_iterator` to `itk::FixedArray`. Included GTest unit tests.
This commit allows iteration over a `FixedArray` by means of a
C++11 range-based for-loop.
=> ENH: Add begin() and end() to FixedArray, support range-based for-loops

Modules/Core/ImageFunction/test/itkGaussianInterpolateImageFunctionTest.cxx
To address:
D:\ITK\src\Modules\Core\ImageFunction\test\itkGaussianInterpolateImageFunctionTest.cxx(72,25): error C2397: conversion from 'unsigned int' to 'itk::Index<2>::IndexValueType' requires a narrowing conversion
D:\ITK\src\Modules\Core\ImageFunction\test\itkGaussianInterpolateImageFunctionTest.cxx(72,25): error C2397: image->SetPixel({{i, j}}, i + j);
Closes #766
=> COMP: GaussianInterpolateImageFunction test narrowing

Examples/Segmentation/CannySegmentationLevelSetImageFilter.cxx
The advection term is negative in the test, which is require for
outward propagation of the level set.
=> DOC: Correct documented Canny Segmentation filter example

Modules/Bridge/VtkGlue/CMakeLists.txt, Modules/Bridge/VtkGlue/test/CMakeLists.txt
The targets have changed in VTK Git master.
Also call "vtk_module_autoinit" on the test driver, which is required on
recent VTK to avoid runtime errors such as;
vtkRenderWindow.cxx:35    WARN| Error: no override found for
'vtkRenderWindow'.
Closes #739
=> COMP: Update for changes to VTK target names

Documentation/ITK5MigrationGuide.md, Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.h, Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx
Added `ComputeMyBoundingBoxInIndexSpace()` to `ImageMaskSpatialObject`,
replacing the deprecated member function `GetAxisAlignedBoundingBoxRegion()`.
=> ENH: Add ImageMaskSpatialObject::ComputeMyBoundingBoxInIndexSpace()

Wrapping/Generators/Python/Tests/extras.py, Wrapping/Generators/Python/itkExtras.py
`imread()` Python function allows to read an image, either by letting the
function deduce the input image pixel type or by manually selecting the
pixel type used to read it. The image dimension is always automatically
deduced.
In certain case, the user want to use the actual image pixel type if
that is possible, and use a fallback type if the input image type is
not supported. The new `fallback_only` parameter allows this.
=> ENH: Add `fallback_only` parameter to `imread()` Python function

CONTRIBUTING.md
Based on feedback from the 50,000 Commit Hackathon, the CONTRIBUTING
document was daunting to new folks.
Remove an introductory paragraph that seems to serve no other purpose
other than to be intimidating.
Add a link to the cheat sheet as a quick start guide.
A links to other related documentation in a More Information section at
the end.
=> DOC: Add More Information section to CONTRIBUTING

Modules/Bridge/VTK/include/itkVTKImageExport.h, Modules/Bridge/VTK/include/itkVTKImageExport.hxx, Modules/Bridge/VTK/include/itkVTKImageExportBase.h, Modules/Bridge/VTK/include/itkVTKImageImport.h, Modules/Bridge/VTK/include/itkVTKImageImport.hxx, Modules/Bridge/VTK/src/itkVTKImageExportBase.cxx, Modules/Bridge/VtkGlue/include/itkImageToVTKImageFilter.hxx, Modules/Bridge/VtkGlue/include/itkVTKImageToImageFilter.hxx, Modules/Bridge/VtkGlue/test/itkImageToVTKImageFilterTest.cxx, Modules/Bridge/VtkGlue/test/itkVTKImageToImageFilterTest.cxx
Address #772:
Thanks to @fbudin69500 for helping me getting acclimated to the ITK way 🙏
=> Pass direction between itk and vtk images

Modules/Core/ImageFunction/wrapping/itkWindowedSincInterpolateImageFunction.wrap, Wrapping/Generators/Python/Tests/findEmptyClasses.py
Exclude these classes because they only expose `operator()`.
Also do not wrap with POINTER because they do not inherit from
itk.LightObject.
Closes #797
=> BUG: PythonFindEmptyClasses test for windowed-sinc functions

Modules/Core/SpatialObjects/include/itkSpatialObject.h, Modules/Core/SpatialObjects/include/itkSpatialObject.hxx
Explicitly-defaulted `SpatialObject()` default-constructor.
Added `const` to `BoundingBoxPointer` and `TransformPointer` data
members of `SpatialObject`. The aim is to ensure that these pointer
are always valid (never null) during the lifetime of the spatial object.
=> STYLE: SpatialObject() = default, const BoundingBox, Transform members

Modules/Filtering/ImageFilterBase/test/itkCastImageFilterTest.cxx, Modules/Registration/Metricsv4/include/itkImageToImageMetricv4.h, Modules/Registration/Metricsv4/include/itkImageToImageMetricv4.hxx, Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4.hxx
ENH: Identify histogram min/max for UseSampledPointSet
When UseSampledPointSet is true (i.e. A sparse sampling point set is
explicitly requested), compute the joint histogram range for the fixed
image axis from those explicilty specified points.
If m_UseSampledPointSet is true, then *ONLY* the sparse sampled points
are used for analysis of the metric, and the fixed space intensity range
values will be fixed to those values identified in the sparse sampled
points.  The fixed masked value items are not relevant when the sparse
sampling is set.
=> MI sample point histogram setting

Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx, Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectGTest.cxx
Fixed issue #785 (ImageMaskSpatialObject IsInside should not depend on
distant pixels) by removing the BoundingBox check from
`ImageMask::IsInsideInObjectSpace`
Added various GTest unit tests for `ImageMaskSpatialObject::IsInside`
=> BUG: Fix issue #785 removing BoundingBox check from ImageMask IsInside

azure_dashboard.cmake
In previous commit [1], several variables that were previously set through
environment variables were modified to be directly set in the ctest script
that starts the testing process. `dashboard_do_coverage` was one of these
variables and therefore should not be set through an environment variable
anymore. Its default value should be used if the variable has not been
defined before.
[1] 1902ab7be33b7d8b42b78a5ac5b3b319153d33f6
=> BUG: `dashboard_do_coverage` is not an environment variable anymore

Modules/Core/Common/include/itkThreadSupport.h
Missing header for definition of ITK_MAX_THREADS was affected by order
of include files in external programs using ITK.
ITK/Modules/Core/Common/include/itkThreadSupport.h:46:43: error: use of undeclared identifier 'ITK_DEFAULT_MAX_THREADS'
constexpr std::size_t ITK_MAX_THREADS = ITK_DEFAULT_MAX_THREADS;
=> BUG: itkConfigure.h defines ITK_DEFAULT_MAX_THREADS

Modules/Core/Common/include/itkHexahedronCell.hxx, Modules/Filtering/ImageGrid/include/itkResampleImageFilter.h, Modules/Filtering/ImageGrid/test/itkResampleImageFilterGTest.cxx
Support when the interpolator precision is a different type than then
transform precision type.
=> COMP: Correct continuous index type

.github/pull_request_template.md
Github uses checkboxes to indicate subtask completions
in a PR.  The current use of checkboxes in a simple PR
causes a rendering in github that often indicates that
1/8 subtasks of the PR are complete.
The current proposal uses positive and negative indications
for each checklist statement.  The negative indications are
not part of the subtasks that the PR addresses, and the
positive indications are part of the checklist.
This convention provides an quick view of the complexity of
the PR and the number of PR checklist tasks that were
addressed in the top level github views.
- 🚫 [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- 🚫 [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIB …
=> DOC: Make use of checkboxes consistent with github

Utilities/Maintenance/ApplyScriptToRemotes.sh
Add a script to apply another script to all remotes.
This script is intended to ease the extension of toolkit-wide changes that
are applied through a bash script to the remote modules that dwell in/are
referenced from the toolkit's `Modules/Remote` module.
=> ENH: Add a script to apply another script to all remotes

Testing/ContinuousIntegration/AzurePipelinesBatch.yml
In previous commit [1], a step calling `ci_addons` was added, but
`ci_addons` was not installed on the system.
[1] fdd0a6e0e06a85fae3d69a345b646da5f639315c
=> BUG: Missing `ci_addons` to convert ctest results to JUnit format

Modules/Core/SpatialObjects/include/itkSpatialObjectPoint.h
The PointSpatialObject keeps a reference to its parent spatial object
for the spatial context. This created additional reference counts for
the parent class not released. A WeakPointer is now used.
=> BUG: Address valgrid defects related to the PointSpatialObject

Examples/IO/IOPlugin.cxx
Address valgrind defect of accessing environment variable string after
memory is freed. POSIX putenv uses the provided string for
storage. Change to using portable KWSys::PutEnv which does not retain
assess to the argument.
This patch addressed the following defect:
https://open.cdash.org/viewDynamicAnalysisFile.php?id=6194649
=> BUG: Fix ownership of environment variable value

Modules/Core/SpatialObjects/include/itkArrowSpatialObject.h, Modules/Core/SpatialObjects/include/itkArrowSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkBoxSpatialObject.h, Modules/Core/SpatialObjects/include/itkBoxSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkEllipseSpatialObject.h, Modules/Core/SpatialObjects/include/itkEllipseSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkGaussianSpatialObject.h, Modules/Core/SpatialObjects/include/itkGaussianSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.h, Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkImageSpatialObject.h, Modules/Core/SpatialObjects/include/itkImageSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkLineSpatialObject.h, Modules/Core/SpatialObjects/include/itkLineSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkMeshSpatialObject.h, Modules/Core/SpatialObjects/include/itkMeshSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.h, Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkPolygonSpatialObject.h, Modules/Core/SpatialObjects/include/itkPolygonSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkSpatialObject.h, Modules/Core/SpatialObjects/include/itkSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkTubeSpatialObject.h, Modules/Core/SpatialObjects/include/itkTubeSpatialObject.hxx
Added virtual `IsInsideInObjectSpace(const PointType &)` member function
to `itk::SpatialObject`, as an overload of the original one,
`IsInsideInObjectSpace(const PointType&, unsigned depth, const std::string& name)`.
Removed the `virtual` keyword from the original member function.
Ensured that the 11 derived classes now override the new overload
(without the `name` parameter), instead of the original one. The
original member function now calls the new overload.
A major performance improvement was observed by this commit, especially
because it avoids many expensive `GetTypeName().find(name)` calls.
`IsInsideInObjectSpace` often appears more than twice (and sometimes
even more than 3 times) as fast as before.
Fixes issue #820 ("SpatialObject IsInsideInObjectSpace PERF penalty …
=> PERF: Overload SpatialObject IsInsideInObjectSpace without name argument

Modules/IO/ImageBase/test/itkRegularExpressionSeriesFileNamesTest.cxx
This test requires filenames to have numbers for sorting. The input files all ended with `.sha512` so it worked but I had a hidden `.DS_Store` file crashing the test.
The next test filters filenames without numbers anyway so no need to keep the first one.
=> BUG: Remove error prone test case

Wrapping/Generators/Python/Tests/CMakeLists.txt, Wrapping/Generators/Python/Tests/PythonTemplateTest.py, Wrapping/Generators/Python/Tests/PythonTypeTest.py, Wrapping/Generators/Python/itkExtras.py, Wrapping/Generators/Python/itkTemplate.py
This PR improves Python error messages when trying to instantiates an ITK object with template parameters that have not been wrapped. The error message relies on a new ITK Python function that prints the Python type of an ITK object in a way that can simply be copy/pasted by the user in Python instead of a C++ style.
=> Improve python wrapping error messages

Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.h, Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx, Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectTest3.cxx, Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectTest4.cxx
Enlarges the bounding box by half a pixel in each direction, to ensure
that a point (in object space) whose nearest pixel has a non-zero
value is always treated as being inside the object.
Fixes issue #753 (ImageMaskSpatialObject BoundingBox smaller than before
Spatial Object update) and issue #785 (ImageMaskSpatialObject IsInside
should not depend on distant pixels). Related to discussion topic
"ImageMaskSpatialObject IsInside less than half a pixel away?",
https://discourse.itk.org/t/imagemaskspatialobject-isinside-less-than-half-a-pixel-away/1807
=> BUG: Half a pixel margin ImageMaskSpatialObject::ComputeMyBoundingBox()

Modules/Core/Common/include/itkMacro.h
__clang_major to __clang_major__
Enables build on Clang 3.8.
=> BUG: Fix identification of Clang major version

Modules/Core/Common/include/itkFixedArray.h, Modules/Core/Common/test/itkFixedArrayGTest.cxx
=> BUG: Fix reverse iterator increment return type

Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectGTest.cxx
To address:
home/kitware/Dashboards/Tests/ITK/Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectGTest.cxx: In member function 'virtual void ImageMaskSpatialObject_AxisAlignedBoundingBoxIsEmptyWhenAllPixelsAreZero_Test::TestBody()':
[CTest: warning matched] /home/kitware/Dashboards/TestsModules/Core/SpatialObjects/test/itkImageMaskSpatialObjectGTest.cxx:156:40: warning: missing initializer for member 'itk::Index<2u>::m_InternalArray' [-Wmissing-field-initializers]
itk::ImageRegion<2>{ itk::Index<2>{}, itk::Size<2>::Filled(1) });
^
[CTest: warning matched] /home/kitware/Dashboards/TestsModules/Core/SpatialObjects/test/itkImageMaskSpatialObjectGTest.cxx:162:40: warning: missing initializer for member 'itk::Index<3u>::m_InternalArray' [-Wmissing-field-initializers] …
=> COMP: ImageMaskSpatialObjectGTest array initialization

Examples/RegistrationITKv4/DeformableRegistration10.cxx
=> COMP: ResampleImageFilter does not have SetDisplacementField method

Documentation/ITK5MigrationGuide.md, Modules/Core/Common/include/itkFixedArray.h, Modules/Core/Common/include/itkFixedArray.hxx, Modules/Core/Common/test/itkFixedArrayGTest.cxx, Modules/Core/Common/test/itkFixedArrayTest.cxx
Declared `FixedArray` member functions `rBegin()` and `rEnd()`
legacy-only, as they are superseded by `rbegin()` and `rend()'.
The new reverse iterators can be passed directly to an `std` algorithm,
e.g., `std::sort(fixedArray.rbegin(), fixedArray.rend())`. Unlike the
old reverse iterators, the new ones support random access iteration.
Deprecation suggested by @dzenanz while discussing pull request #850
=> STYLE: Deprecated FixedArray member functions rBegin() and rEnd()

Modules/Core/Common/include/itkFixedArray.h, Modules/Core/Common/include/itkIndex.h, Modules/Core/Common/include/itkOffset.h, Modules/Core/Common/include/itkSize.h
Instead of calling `std::swap_ranges`, it appears preferable to call
the dedicated C++11 `std::swap` overload for arrays, when swapping the
elements of one `m_InternalArray` and another.
=> STYLE: Replace std::swap_ranges by C++11 std::swap of m_InternalArray

Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkSpatialObject.h
Replaced the term "world space" by "object space", when describing
`PointBasedSpatialObject::ClosestPointInObjectSpace`,
`SpatialObject::IsInsideInObjectSpace`, and
`SpatialObject::ComputeMyBoundingBox()`.
=> DOC: Use the term "object space" for ObjectSpace based member functions 

Modules/Core/Common/include/itkStreamingImageFilter.hxx
Loop over named outputs which is a super-set of the index outputs.
=> BUG: Add named output support to StreamingImageFilter

Modules/Core/Common/include/itkFixedArray.h
Replaced `unsigned short` by `unsigned int` as type of `index` parameter,
for both `GetElement(index)` and `SetElement(index, value)` member
functions of `FixedArray`. This improved consistency, as `unsigned int`
is being used throughout the entire definition of `FixedArray`.
Style improvements in the implementation of `FixedArray`:
* Fixed a typo in the documentation.
* Replaced `while` loops by range-based for-loops.
* Replaced `std::copy` by C++11 `std::copy_n`.
* Removed two dangling backslashes.
=> STYLE: Replace unsigned short by unsigned int as FixedArray index type

Modules/IO/ImageBase/include/itkImageIOBase.h, Modules/IO/NRRD/src/itkNrrdImageIO.cxx
=> NRRD compression

Modules/Core/Common/include/itkDefaultVectorPixelAccessor.h, Modules/Core/Common/include/itkDefaultVectorPixelAccessorFunctor.h, Modules/Core/Common/include/itkVectorImageNeighborhoodAccessorFunctor.h
Defaulted (`= default`) the default-constructors of Vector Accessor classes,
`DefaultVectorPixelAccessor`, `DefaultVectorPixelAccessorFunctor`, and
`VectorImageNeighborhoodAccessorFunctor`.
Initialized the `m_Begin` data member of both `Functor` classes by a C++11
in-class default member initializer, `{nullptr}`.
Note: this commit ensures that these default-constructors will usually get a
non-throwing exception specification (implicitly). For example,
`noexcept(itk::DefaultVectorPixelAccessor<int>{})` was `false` before this
commit, and will be `true` after this commit.
=> STYLE: Explicitly defaulted default-constructors Vector Accessor classes

Documentation/ITK5MigrationGuide.md, Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkGaussianInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkGaussianInterpolateImageFunction.hxx, Modules/Core/ImageFunction/include/itkInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkLinearInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkNearestNeighborInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkRayCastInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.h, Modules/Core/ImageFunction/test/itkGaussianInterpolateImageFunctionTest.cxx, Modules/Core/ImageFunction/test/itkLinearInterpolateImageFunctionTest.cxx, Modules/Core/ImageFunction/test/itkNearestNeighborInterpolateImageFunctionTest.cxx, Modules/Core/ImageFunction/test/itkRayCastInterpolateImageFunctionTest.cxx, Modules/Core/ImageFunction/test/itkWindowedSincInterpolateImageFunctionTest.cxx, Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx, Modules/Filtering/ImageGrid/test/itkResampleImageTest7.cxx, Modules/Nonunit/Review/include/itkComplexBSplineInterpolateImageFunction.h
When streaming during resampling, the requested region is extended by
the domain of the interpolator. This is especially important for
consistent resampling results with interpolators other than the nearest
neighbor or linear interpolator, which use many surrounding pixels to
determine their value.
A new, abstract GetRadius method is added to InterpolateImageFunction.
This method is used by the ResampleImageFilter to extend its required
input region.
Suggested-by: Bradley Lowekamp <blowekamp@mail.nih.gov>
=> ENH: Expand ResampleImageFilter requested region by interpolator domain

Modules/Core/Common/include/itkMacro.h
https://stackoverflow.com/a/36000632/276168 says that Apple versioning
diverged from mainline at version 7.0.
The bug was introduced by f6dd46be8a7cd3b39dd03fbe23900d27abddf6aa.
=> BUG: the clang version check was overly strict on Apple platforms

Documentation/ITK5MigrationGuide.md, Examples/Filtering/RGBCurvatureAnisotropicDiffusionImageFilter.cxx, Examples/Filtering/RGBGradientAnisotropicDiffusionImageFilter.cxx, Examples/IO/VisibleHumanPasteWrite.cxx, Examples/Segmentation/WatershedSegmentation1.cxx, Modules/Compatibility/Deprecated/include/itkVectorCastImageFilter.h, Modules/Compatibility/Deprecated/test/CMakeLists.txt, Modules/Core/Common/include/itkRGBAPixel.h, Modules/Core/Common/include/itkRGBPixel.h, Modules/Filtering/DisplacementField/include/itkDisplacementFieldJacobianDeterminantFilter.hxx, Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.h, Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.hxx, Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest1.cxx, Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest2.cxx, Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest3.cxx, Modules/Filtering/ImageGrid/test/itkWarpImageFilterTest.cxx, Modules/Filtering/ImageGrid/test/itkWarpVectorImageFilterTest.cxx, Modules/Filtering/ImageIntensity/test/itkVectorExpandImageFilterTest.cxx, Modules/Nonunit/IntegratedTest/test/itkBasicFiltersPrintTest2.cxx, Modules/Registration/FEM/include/itkFEMRegistrationFilter.h, Modules/Registration/GPUPDEDeformable/test/itkGPUDemonsRegistrationFilterTest2.cxx, Modules/Registration/PDEDeformable/test/itkDemonsRegistrationFilterTest.cxx, Modules/Registration/PDEDeformable/test/itkDiffeomorphicDemonsRegistrationFilterTest.cxx, Modules/Registration/PDEDeformable/test/itkFastSymmetricForcesDemonsRegistrationFilterTest.cxx, Modules/Registration/PDEDeformable/test/itkLevelSetMotionRegistrationFilterTest.cxx, Modules/Segmentation/LevelSets/include/itkCurvesLevelSetFunction.hxx, Modules/Segmentation/LevelSets/include/itkGeodesicActiveContourLevelSetFunction.hxx, Modules/Segmentation/LevelSets/include/itkGeodesicActiveContourShapePriorLevelSetFunction.hxx, Modules/Segmentation/LevelSets/include/itkSegmentationLevelSetFunction.h, Modules/Segmentation/LevelSetsv4/include/itkLevelSetEquationAdvectionTerm.hxx
Replace VectorCastImageFilter with the generic CastImageFilter.
I only had to implement a converter from RGBPixel to Vector.
I also fixed a small mistake from the VectorResampleImageFilter deprecation.
=> ENH: Deprecate VectorCastImageFilter

Modules/Core/Common/include/itkImageSink.h, Modules/Core/Common/src/itkStreamingProcessObject.cxx
c76b193eace50ab287ac64cdd4f61d3bcb3daa03 introduces compile errors when future legacy is removed.
=> COMP: fix build failures introduced by c76b193

Modules/Core/Common/include/itkContinuousIndex.h
In order for `ContinuousIndex<TCoordRep>` to represent a continuous
index, `TCoordRep` must be a floating point type. This commit checks
this requirement at compile-time, and replaces an unsafe function-style
cast by `static_cast<TCoordRep>`.
=> STYLE: Ensure that ContinuousIndex TCoordRep is a floating point type

Modules/Core/Common/include/itkImageBase.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkImageBaseGTest.cxx
Added convenience overloads to the six `ImageBase` Transform member
functions, returning the result by value, instead of having an output
parameter:
TransformPhysicalPointToIndex
TransformPhysicalPointToContinuousIndex
TransformContinuousIndexToPhysicalPoint
TransformIndexToPhysicalPoint
TransformLocalVectorToPhysicalVector
TransformPhysicalVectorToLocalVector
These overloads allow users to have a more "functional" programming
style, or at least, place the transformation result in a `const` variable.
So instead of:
Bar bar;
image->TransformFooToBar(foo, bar);
It typically allows users to write:
const auto bar = image->TransformFooToBar(foo);
Added a unit test to itkImageBaseGTest
=> ENH: Convenience overloads for ImageBase Transform member functions

Examples/Filtering/RGBCurvatureAnisotropicDiffusionImageFilter.cxx, Examples/Filtering/RGBGradientAnisotropicDiffusionImageFilter.cxx, Examples/Filtering/ResampleImageFilter6.cxx, Modules/Core/Transform/include/itkTranslationTransform.h
The VectorResampleImageFilter has been deprecated, so remove
references to wiki pages and software guide.
=> DOC: Remove documentation references to VectorResampleImageFilter

CMake/ITKModuleRemote.cmake, Modules/Remote/WikiExamples.remote.cmake
An environmental variable ${_name}_GIT_TAG_OVERRIDE can be set
in the environment to override the value in the remote module.
The intent of the environmental variable override is to
facilitate testing of remote module branch behaviors without
requiring changes to the ITK code base.
=> ENH: Add environmental override for git tag of remote module

Modules/ThirdParty/GDCM/src/CMakeLists.txt
I cannot link anymore since the latest changes (I'm guessing d230b36). See e.g. this [dashboard result](https://my.cdash.org/viewBuildError.php?buildid=1650863). I hope this is the right patch but please check @malaterre . Thanks!
=> COMP: fix wrong GDCM library name, gdcmopenjp2 -> itkgdcmopenjp2

Documentation/ITK5MigrationGuide.md, Modules/Core/Common/include/itkBoundingBox.h, Modules/Core/Common/include/itkBoundingBox.hxx, Modules/Core/Common/test/itkBoundingBoxTest.cxx, Modules/Core/SpatialObjects/include/itkSpatialObject.hxx
Added `BoundingBox::NumberOfCorners`, evaluated at compile time, which
was used to replace a run-time `std::pow(2.0, VPointDimension)` call.
Added `BoundingBox::ComputeCorners()`, returning an `std::array` of
points, to allow users to get the corners of a bounding box without
the performance cost of dynamic memory allocation of a point container.
Adapted `GetCorners()`, now doing a `reserve` of the expected number of
points, and calling `ComputeCorners()` to compute those corner points.
Replaced calls to `GetCorners()` by `ComputeCorners()`, in the
implementation of `SpatialObject`.
=> ENH: Add NumberOfCorners and ComputeCorners() to BoundingBox

Modules/Core/Common/include/itkBoundingBox.hxx
Enable compiling in ITK_LEGACY_REMOVE mode. The problem was
introduced by 814419ae9f989c10c597a5e913166d3e8c949267.
=> COMP: follow up to 814419a (bounding box m_CornersContainer removal)

Modules/Remote/GenericLabelInterpolator.remote.cmake
Changes made necessary to build ANTs normalization tools against ITK.
=> Update generic label interpolator

Modules/IO/TIFF/test/CMakeLists.txt
When running the test in parallel, which is the norm, computer can
run out of memory. This change ensures that large TIFF tests are run
serially, in order to minimize the chance of allocation failures.
Example failure message:
```text
Trying to allocate an image of size 9346 MiB
ITK test driver caught an ITK exception:
itk::MemoryAllocationError (000000B95A0FF7D8)
Location: "unknown"
File: c:\dashboard\itk\modules\core\common\include\itkImportImageContainer.hxx
Line: 199
Description: Failed to allocate memory for image.
```
=> ENH: run large image IO tests serially

Modules/Core/Common/test/itkFixedArrayGTest.cxx
Removed a pair of curly braces, `{}`, from the declaration of a local
`std::array` variable in itkFixedArrayGTest, to avoid a warning from
GCC4, reported by @dzenanz:
> itkFixedArrayGTest.cxx:35:42: warning: missing initializer for member
> 'std::array<double, 2ul>::_M_elems' [-Wmissing-field-initializers]
After removing those curly braces, the array may no longer be initialized.
Fortunately the array does not really need to be initialized at the point
of declaration, as each array element is assigned a new value directly
after the declaration.
=> COMP: Fixed GCC4 missing-field-initializers warning on `{}` in GTest

Modules/Remote/RTK.remote.cmake
See [RTK release notes](https://github.com/SimonRit/RTK/releases/tag/v2.0.1). It would be nice to include it in ITK v5 if possible.
=> ENH: update RTK remote file with release tag v2.0.1

Modules/Core/Common/include/itkBoundingBox.h
The documentation of `BoundingBox` member functions `GetCenter()`,
`GetMinimum()`, and `GetMaximum()` incorrectly stated that these
member functions might return a `nullptr`. This commit uses the term
"a point at the origin" instead.
Also mentioned that `GetCorners()` is a legacy member function.
=> DOC: Fixed Doxygen description BoundingBox Get member functions

Modules/Core/Common/include/itkBoundingBox.hxx
When compiling ITK with ITK_LEGACY_SILENT set to ON, e.g. when compiling
with Python wrapping ON, ITK was not compiling because itkVectorContainer
class does not have a member function called `clear()` or a function called
`reserve()`. This regression was introduced in [1] and the PR is was a
follow up of.
[1] 5b508a5e88bb70ec6667569f6adcf9c915225f08
=> Follow up commit to fix itkBoundingBox with LEGACY support

Modules/Core/Common/test/itkAggregateTypesGTest.cxx, Modules/Core/TestKernel/include/itkGTestPredicate.h, Modules/Core/TestKernel/test/itkGoogleTest.cxx, Modules/Core/Transform/test/itkBSplineTransformGTest.cxx, Modules/Filtering/ImageGrid/test/itkTileImageFilterGTest.cxx, Modules/Filtering/LabelMap/test/itkShapeLabelMapFilterGTest.cxx, Modules/Segmentation/SuperPixel/test/itkSLICImageFilterGTest.cxx
Renamed the unit test macro `EXPECT_VECTOR_NEAR` to `ITK_EXPECT_VECTOR_NEAR`,
to explicitly indicate that it is an ITK specific extension to GTest.
=> STYLE: Rename ITK macro EXPECT_VECTOR_NEAR to ITK_EXPECT_VECTOR_NEAR

Modules/ThirdParty/Eigen3/CMakeLists.txt
The CMake command `find_package()` used for Eigen3 imports the Eigen3::Eigen
target, but this target is only visible in that folder and its subfolders.
For this target to be used in other ITK module, the command `find_package()`
needs to be called for each ITK modules that needs Eigen. We removed
the condition around `find_package()` that is called in
`ITKEigen3_EXPORT_CODE_BUILD` to always call `find_package()`, even when
it is done inside the ITK build tree.
=> BUG: ITK could not find Eigen3::Eigen target when using system Eigen

Modules/Core/Common/include/itkBoundingBox.h, Modules/Core/Common/include/itkBoundingBox.hxx, Modules/Core/Common/test/itkBoundingBoxTest.cxx
This is a follow up of commit [1].
The method `clear()` has been used successfully in itkBoundingBox
for more than 10 years. There is no reason to replace it with a
call of the method `Initialize()`.
[1] 3a7ce4b6d8c76e30e6b89ddc850d5745b18a45d3
=> BUG: Revert changing call to `Initialize()` with `clear()`

Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkGaussianInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkGaussianInterpolateImageFunction.hxx, Modules/Core/ImageFunction/include/itkInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkLinearInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkNearestNeighborInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkRayCastInterpolateImageFunction.h, Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.h, Modules/Core/ImageFunction/test/itkGaussianInterpolateImageFunctionTest.cxx, Modules/Core/ImageFunction/test/itkLinearInterpolateImageFunctionTest.cxx, Modules/Core/ImageFunction/test/itkNearestNeighborInterpolateImageFunctionTest.cxx, Modules/Core/ImageFunction/test/itkRayCastInterpolateImageFunctionTest.cxx, Modules/Core/ImageFunction/test/itkWindowedSincInterpolateImageFunctionTest.cxx, Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx, Modules/Filtering/ImageGrid/test/CMakeLists.txt
This function is required for streaming with ResampleImageFilter in ITK
5.0. The abstract method is hidden with ITKV4_COMPATIBILITY so classes
that derive from InterpolateImageFunction do not encounter build errors.
When compatibility is turned off interpolator authors with get a compile
time error until the method is defined to ensure correct behavior when
resampling.
=> BUG: InterpolateImageFunction::GetRadius hidden in ITKV4_COMPATIBILITY

Modules/Core/Common/src/itkPoolMultiThreader.cxx, Modules/Core/Common/src/itkTBBMultiThreader.cxx, Modules/Core/Common/test/itkThreadedIteratorRangePartitionerTest3.cxx
=> BUG: number of work units was greater than 1 even for 1 thread

Modules/Core/Common/include/itkImageSink.hxx
In ImageSinc::GenerateNthInputRequestedRegion, use superclass'
GetInput method to obtain a pointer to a DataObject then a
dynamic_cast can be used to determine if the image region can be
generated. This addresses runtime "Unable to convert input" warnings.
closes #938.
=> BUG: Use ProcessObject GetInput to obtain base pointer

Modules/Core/Common/src/itkProcessObject.cxx, Modules/Core/Common/test/itkDataObjectAndProcessObjectTest.cxx
Prevent a dereference of a nullptr when deleting "Primary" output.
=> BUG: Fix ProcessObject::RemoveOutput for null objects.

Modules/Registration/PDEDeformable/itk-module.cmake
When FFTW is enable the CurvatureRegistrationFilter is dependent upon
the ITKFFTW module.
=> COMP: Address missing fftw include in CurvatureRegistrationFilter

Modules/Filtering/ImageFilterBase/wrapping/itkCastImageFilter.wrap
A transfer of types wrapped for the VectorCastImageFilter to
the CastImageFilter.
=> BUG: Add casting for vector pixel types

Modules/Core/Common/include/itkImageSink.hxx
In ImageSinc::GenerateNthInputRequestedRegion, use superclass'
GetInput method to obtain a pointer to a DataObject then a
dynamic_cast can be used to determine if the image region can be
generated. This addresses runtime "Unable to convert input" warnings.
=> For Release: BUG: Use ProcessObject GetInput to obtain base pointer

Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx
If interpolator's `GetRadius` required an image, and it was not set
outside of resample filter, an exception `Input image required!` was raised.
=> BUG: resample filter no longer triggers unnecessary exception

Examples/RegistrationITKv4/DeformableRegistration2.cxx
For the ITK Software Guide:
Examples/RegistrationITKv4/DeformableRegistration2.cxx:317:80: warning: Line length too long for LaTeX printing
=> STYLE: DeformableRegistration2 line length warnings

Examples/SpatialObjects/SpatialObjectHierarchy.cxx
To address:
Examples/SpatialObjects/SpatialObjectHierarchy.cxx:65: warning: Line
after start of LaTeX block should be a newline -- instead got Whenever
the parameters of an object, including its parent-child
=> COMP: SpatialObjectsHierarchy Software Guide newline

Modules/Filtering/ImageFilterBase/include/itkCastImageFilter.h, Modules/Filtering/ImageFilterBase/include/itkCastImageFilter.hxx, Modules/Filtering/ImageFilterBase/test/itkCastImageFilterTest.cxx
=> Fix cast for explicit cast for release

Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h, Modules/Core/Common/src/itkImageSourceCommon.cxx, Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx, Modules/Core/GPUCommon/include/itkGPUDataManager.h
Declared internal integer data members `m_Seed` and `m_StaticDiffer`
`atomic`, and removed three locks (`std::lock_guard<std::mutex>`) from
`MersenneTwisterRandomVariateGenerator`, to improve the performance.
For performance reasons, it is in general recommended to use atomics,
instead of mutex locking, whenever possible.
=> PERF: Replace mutex by atomic in MersenneTwisterRandomVariateGenerator

Modules/Remote/SphinxExamples.remote.cmake
This updates the support for ITKv5.0.0, update python to 3.6 support,
updates submodules to working hashes, updates documentation warnings,
uses https vs http for websites that support it, and updates http addresses
that are are permanently redirected.
=> ENH: Update SphinxExamples to lastest master branch

Modules/Bridge/VtkGlue/src/QuickView.cxx
Without this, Visual Studio complained about duplicate definition with `ITKV4_COMPATIBILITY` enabled.
=> COMP: change export specification to template for un-specialized method

CMake/itkExternal_FFTW.cmake
The "Algorithm" appears to be a remnant of a prior organization of
ITK. This fixes the header installation path so it's install along
side other ITK header files, enabling the ITK FFT module to utilizes
these include.
=> BUG: Install FFTW headers in same location as ITK

Modules/Nonunit/Review/include/itkComplexBSplineInterpolateImageFunction.h
2aae174f9e445e344cc969ea5440fc07dda4a533 has put GetRadius method inside
ITKV4_COMPATIBILITY #ifdefs, but ComplexBSplineInterpolateImageFunction
in Review module was forgotten.
=> COMP: forgotten class for ITKV4_COMPATIBILITY in 2aae174

Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkMersenneTwisterRandomVariateGeneratorGTest.cxx
`MersenneTwisterRandomVariateGenerator` improvements:
- STYLE: Added `const` to `GetSeed()`
- ENH: Added GoogleTest, testing `GetIntegerVariate()`
=> ENH: MersenneTwisterRandomVariateGenerator GTest (+ const keyword)

Modules/Bridge/NumPy/test/CMakeLists.txt
To address:
CMake Error at CMake/ITKModuleEnablement.cmake:319 (add_subdirectory):
The source directory
/home/matt/src/ITK/Modules/Bridge/NumPy/test
does not contain a CMakeLists.txt file.
CMakeLists.txt:433 (include)
When BUILD_EXAMPLES, ITK_WRAP_PYTHON, and BUILD_TESTING are enabled.
=> BUG: Add test/CMakeLists.txt stub to NumPy bridge

Modules/Filtering/ImageFilterBase/include/itkCastImageFilter.h
```text
/Users/builder/externalModules/Filtering/ImageFilterBase/include/itkCastImageFilter.h:128:11: warning: '~CastImageFilter' overrides a destructor but is not marked 'override' [-Winconsistent-missing-destructor-override]
virtual ~CastImageFilter() = default;
^
```
This was introduced in 75d98250d5c87c274c87c9a33c1f442c4addab86.
=> COMP: fix warning about missing override in CastImageFilter

Modules/ThirdParty/DoubleConversion/CMakeLists.txt
This will support multiple system versions of double-conversion.
Suggested by Alexander Neumann. Closes #579. Aimed to be back-ported to 4.13.x release to address #912.
=> ENH: use double-conversion's CMake targets

Modules/Core/Common/include/itkPlatformMultiThreader.h
Trying to address the mystery of missing PlatformMultiThreader from documentation.
=> DOC: wrong class name for PlatformMultiThreader

Modules/Filtering/ImageIntensity/include/itkNormalizeImageFilter.h
Expand upon the existing caveats to clarify the intended
output values of the image.
=> DOC: Improve the documentation clarity for NormalizeImage.

Modules/Core/Mesh/include/itkWarpMeshFilter.hxx, Modules/Core/SpatialObjects/include/itkSpatialObjectToImageStatisticsCalculator.hxx, Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.hxx, Modules/Filtering/ImageGrid/include/itkShrinkImageFilter.hxx, Modules/Filtering/ImageIntensity/include/itkPolylineMask2DImageFilter.hxx, Modules/Filtering/ImageIntensity/include/itkPolylineMaskImageFilter.hxx, Modules/Filtering/LabelMap/include/itkAttributePositionLabelMapFilter.hxx, Modules/Numerics/Optimizersv4/include/itkObjectToObjectMetric.hxx, Modules/Registration/Common/include/itkBlockMatchingImageFilter.hxx, Modules/Registration/Metricsv4/include/itkImageToImageMetricv4GetValueAndDerivativeThreader.hxx, Modules/Registration/Metricsv4/include/itkJointHistogramMutualInformationComputeJointPDFThreaderBase.hxx
Replaced `image->TransformPhysicalPointToIndex(point, index)` calls by
`image->TransformPhysicalPointToIndex(point)`, which returns the index.
The `TransformPhysicalPointToIndex(point)` overload was introduced with
ITK 5.0.0. It is slightly faster than the original overload, as it does
not figure out whether or not the point is inside the image. However,
this commit is mostly intended to increase code readability.
=> STYLE: Use image->TransformPhysicalPointToIndex(point), returning index

Modules/Core/Common/include/itkImageBase.h, Modules/Core/Common/test/itkImageBaseGTest.cxx, Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.hxx, Modules/Core/ImageFunction/include/itkCentralDifferenceImageFunction.hxx, Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.hxx, Modules/Filtering/LabelMap/include/itkShapeLabelMapFilter.hxx, Modules/Registration/PDEDeformable/include/itkESMDemonsRegistrationFunction.hxx
The `ImageBase` overloads of `TransformLocalVectorToPhysicalVector` and
`TransformPhysicalVectorToLocalVector` with a single argument
(inputGradient), introduced with ITK 5.0.0, always transformed a
`FixedArray` to another `FixedArray`. This appeared to limit the
usefulness of these overloads, as they would not transform an
`itk::Vector` to another `itk::Vector`, or an `itk::CovariantVector` to
another `itk::CovariantVector`.
The first commit, 4d9dc8f6357673e87ff35ce147a10b6964ffdef5, removes this limitation. It adds support for `Vector` and
`CovariantVector` transformations, by making the overloads more generic:
their return type `TVector` will now be deduced from their argument type.
The second commit, f5bb85e3edd653d3f2c4bc26b825c816cbef757f actually uses the new single argument …
=> ENH: ImageBase Transform-Vector single argument overloads more generic

Modules/Core/Common/include/itkCovariantVector.hxx, Modules/Core/Common/include/itkFixedArray.hxx, Modules/Core/Common/include/itkRGBPixel.hxx, Modules/Core/Common/include/itkVector.hxx, Modules/Core/Common/test/itkCovariantVectorGeometryTest.cxx, Modules/Core/Common/test/itkPointGTest.cxx, Modules/Core/Common/test/itkVectorGeometryTest.cxx, Modules/Core/SpatialObjects/include/itkSpatialObject.hxx, Modules/Filtering/FastMarching/include/itkFastMarchingImageFilterBase.hxx, Modules/Filtering/ImageFrequency/include/itkFrequencyBandImageFilter.hxx, Modules/Filtering/ImageGrid/include/itkBinShrinkImageFilter.hxx, Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
Four STYLE commits that replace calls to `FixedArray::Begin()` and `FixedArray::End()`:
- `Vector(value)`, `CovariantVector(value)` constructors call base class `FixedArray(value)` instead
- `FastMarching` does a range-based for-loop instead
- Const iteration calls `cbegin()` and `cend()` instead
- itkFixedArray.hxx using std::equal, and C++11 fill_n and copy_n
=> Replace calls to FixedArray::Begin() and FixedArray::End()

Modules/Filtering/ImageFeature/include/itkHessianToObjectnessMeasureImageFilter.h, Modules/Filtering/ImageFeature/include/itkHessianToObjectnessMeasureImageFilter.hxx
This is a squash and rebase of #994.
=> BUG: Ensure strict weak ordering in HessianToObjectnessMeasure's sort

Modules/ThirdParty/DoubleConversion/CMakeLists.txt
This is a forgotten cherry-pick of b2884129bf6db53cb102137d81e7176e893c5e5f.
=> COMP: a fix for non-system double-conversion build

Utilities/Maintenance/UpdateTestingMacrosNames.sh
Add script to update ITK testing macros names.
Motivated by PR #999.
This script should ease the task to update the testing macros names in
remote modules when used together with the [`ApplyScriptToRemotes.sh`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/Maintenance/ApplyScriptToRemotes.sh) script.
- :no_entry_sign: [Adds test …
=> ENH: Add script to update ITK testing macros names

Modules/Core/Common/include/itkNumericTraits.h
To address:
[build] ../External/ITK/Modules/Core/Common/include/itkNumericTraits.h:1083:36: warning: instantiation of variable 'itk::NumericTraits<std::__1::complex<float> >::Zero' required here, but no definition is available [-Wundefined-var-template]
[build]   static Self ZeroValue() { return Zero; }
[build]                                    ^
[build] ../External/ITK/Modules/Core/Common/include/itkNumericTraits.h:1088:48: note: in instantiation of member function 'itk::NumericTraits<std::__1::complex<float> >::ZeroValue' requested here
[build]   static Self ZeroValue(const Self &) { return ZeroValue(); }
[build]                                                ^
[build] ../External/ITK/Modules/Filtering/ImageGrid/include/itkTileImageFilter.hxx:39:59: note: in instantiation of member …
=> COMP: Provide NumericTraits<complex<T>>::ZeroValue() definition

Modules/Core/Common/include/itkImageSink.h
Fixing warning:
```
[CTest: warning matched] /Users/builder/externalModules/Core/Common/include/itkImageSink.h:140:3: warning: '~ImageSink' overrides a destructor but is not marked 'override' [-Winconsistent-missing-destructor-override]
~ImageSink() = default;
^
```
This patch should be merged into the release and master branches.
=> Fix image sink override warning

Utilities/Maintenance/ApplyScriptToRemotes.sh, Utilities/Maintenance/UpdateRequiredITKVersionInRemoteModules.sh
Fix remotes maintenance scripts:
- Fix scripts input arguments `command not found` error adding the `test`
command over each argument.Fixes:
```
./Utilities/Maintenance/ApplyScriptToRemotes.sh: line 82:
UpdateTestingMacrosNames: command not found
./Utilities/Maintenance/ApplyScriptToRemotes.sh: line 82: ENH: Update
ITK testing macros names: command not found
```
and idem for `UpdateRequiredITKVersionInRemoteModules.sh`.
Avoid the script continuing its execution if not all input parameters have
been provided.
- Fix the `git add` command failing when not finding any file extension
that matches the filters. This was causing that even files whose
extension matched any of those before the missing one were not being
added. Fixes:
```
fatal: pathspec './*.c' did not match any files
fatal: …
```
=> BUG: Fix remotes maintenance scripts

Modules/Bridge/NumPy/include/itkPyBuffer.hxx, Modules/Bridge/NumPy/wrapping/test/itkPyBufferTest.py
GetArrayFromImage was refactored so the buffer is first passed to this
GetArrayViewFromImage.  In this case, it does not need to be writable.
Remove the restriction to retain used in GetArrayViewFromImage.
See also:
https://github.com/numpy/numpy/pull/11739
=> BUG: Do not require PyBUF_WRITABLE in GetArrayViewFromImage

Modules/Filtering/BiasCorrection/include/itkMRIBiasFieldCorrectionFilter.h, Modules/Filtering/BiasCorrection/include/itkMRIBiasFieldCorrectionFilter.hxx, Modules/Registration/Common/include/itkMultiResolutionPyramidImageFilter.h, Modules/Registration/Common/include/itkMultiResolutionPyramidImageFilter.hxx
Declared the `factors` parameter of `SetStartingShrinkFactors` as
pointer-to-const for both `MultiResolutionPyramidImageFilter` and
`MRIBiasFieldCorrectionFilter`, as these member functions do not
modify their argument.
Adjusted the "single factor overloads" of these member functions, to
make use of the improved const-correctness.
=> STYLE: Add const to SetStartingShrinkFactors parameter

Modules/Core/Common/include/itkGaussianDerivativeOperator.hxx, Modules/Core/Common/include/itkImageConstIteratorWithIndex.hxx, Modules/Core/Common/include/itkImageConstIteratorWithOnlyIndex.hxx, Modules/Core/Common/include/itkImportImageContainer.hxx, Modules/Core/Common/include/itkIndex.h, Modules/Core/Common/include/itkNeighborhood.h, Modules/Core/Common/include/itkNeighborhood.hxx, Modules/Core/Common/include/itkNeighborhoodAllocator.h, Modules/Core/Common/include/itkOffset.h, Modules/Core/Common/include/itkSize.h, Modules/Core/Common/include/itkVariableLengthVector.h, Modules/Core/Common/include/itkVariableLengthVector.hxx, Modules/Core/Transform/include/itkBSplineDeformableTransform.hxx, Modules/Core/Transform/include/itkBSplineTransform.hxx, Modules/Core/Transform/include/itkCompositeTransform.hxx, Modules/Core/Transform/include/itkMultiTransform.hxx, Modules/Filtering/FFT/include/itkFFTWHalfHermitianToRealInverseFFTImageFilter.hxx, Modules/IO/TIFF/src/itkTIFFImageIO.cxx, Modules/Segmentation/Classifiers/include/itkBayesianClassifierImageFilter.hxx
Replaced each call of the form `std::copy(input, input + n, output)` by
the equivalent C++11 `std::copy_n(input, n, output)` call. Added missing
`#include <algorithm>` directives.
Does simplify the code, and might in some cases improve the performance,
especially when the original code did two function calls to retrieve the
input iterator, as in `std::copy(f(), f() + n, output)`.
=> STYLE: Replace std::copy(input, input + n, output) by C++11 std::copy_n

Modules/Core/Common/include/itkMetaProgrammingLibrary.h, Modules/Filtering/ImageFilterBase/include/itkCastImageFilter.h, Modules/Filtering/ImageFilterBase/include/itkCastImageFilter.hxx
=> BUG: Use enable_if with SFINAE to dispatch

Modules/Numerics/Statistics/include/itkVectorContainerToListSampleAdaptor.h, Modules/Numerics/Statistics/include/itkVectorContainerToListSampleAdaptor.hxx
The temporary variable causes false sharing when used by multiple threads.
The temporary variables could cause unexpected behaviours if the returned reference is modified.
=> PERF: Remove Temporary Variable in GetMeasurementVector

Modules/Core/Common/include/itkSymmetricEigenAnalysis.h
m_UseEigenLibrary is initialized in place to false,
and does not need an initializer in the constructor.
=> STYLE: Prevent double initialization

Modules/Core/Common/ITKKWStyleOverwrite.txt, Modules/Core/Common/include/itkExceptionObject.h, Modules/Core/Common/include/itkMacro.h, Modules/Core/SpatialObjects/include/itkPolygonSpatialObject.hxx, Modules/Core/SpatialObjects/include/itkSpatialObject.h, Modules/Filtering/Denoising/include/itkPatchBasedDenoisingBaseImageFilter.hxx, Modules/IO/ImageBase/include/itkImageFileReaderException.h, Modules/IO/MeshBase/include/itkMeshFileReaderException.h, Modules/IO/MeshBase/include/itkMeshFileWriterException.h, Modules/Nonunit/Review/include/itkConformalFlatteningMeshFilter.hxx, Modules/Nonunit/Review/include/itkMultiphaseFiniteDifferenceImageFilter.hxx, Modules/Nonunit/Review/src/itkVoxBoCUBImageIO.cxx, Modules/Numerics/FEM/include/itkFEMObjectSpatialObject.h, Modules/Numerics/FEM/test/itkFEMGenerateMeshTest.cxx, Modules/Numerics/Optimizersv4/test/itkAutoScaledGradientDescentRegistrationOnVectorTest.cxx, Modules/Numerics/Optimizersv4/test/itkAutoScaledGradientDescentRegistrationTest.cxx, Modules/Registration/PDEDeformable/include/itkESMDemonsRegistrationFunction.hxx, Modules/Video/IO/include/itkVideoIOBase.h
The desire is that itkExceptionObject.h can only be included from
itkMacro.h, but the conditional logic allowed itkExceptionObject.h to be
included as long as itkMacro.h was included first.
Additionally the KWSys enforced style was violated because
itkExceptionObject_h was not defined at the top of the
itkExceptionObject.h file.
=> BUG: Flawed logic for itkExceptionObject.h guards

Modules/Filtering/DisplacementField/include/itkInverseDisplacementFieldImageFilter.hxx
Missing refactoring for addressing uninitialized value warnings.
In Ubuntu 18.04 with gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, a
large number of compilation uninitialized value warning were
generated related to constructing of point and vector type from C
arrays. This patch works around these warning by performing the
operation in a single line, and remove extra conversion loops or calls
to CastFrom when a constructor suffices.
=> COMP: Another work around uninitialized value warnings

Modules/Compatibility/Deprecated/test/itkSpawnThreadTest.cxx, Modules/Core/Common/include/itkThreadSupport.h, Modules/Core/Common/src/itkMemoryUsageObserver.cxx, Modules/Core/Common/test/itkTimeStampTest.cxx, Modules/Core/TestKernel/include/itkTestDriverInclude.h, Modules/IO/GE/src/Ge5xHdr.h, Modules/IO/LSM/src/itkLSMImageIO.cxx, Modules/Numerics/NarrowBand/include/itkNarrowBand.h, Modules/Registration/Metricsv4/include/itkANTSNeighborhoodCorrelationImageToImageMetricv4GetValueAndDerivativeThreader.h
Improve consistency in the code base, and provide modern
type aliasing wiht the 'using' syntax.
=> ENH: Prefer c++11 'using' to 'typedef' for structs

Documentation/Maintenance/Release.md, Modules/Bridge/VtkGlue/include/itkImageToVTKImageFilter.h, Modules/Remote/WikiExamples.remote.cmake, Utilities/Doxygen/GenerateExamplesDox.cmake
The WikiExamples have been migrated to ITKExamples
for easier maintenance, and consistent documentation.
=> DOC: Purge outdated media wiki WikiExamples

CMake/ITKSetStandardCompilerFlags.cmake
This is PR for AVX flag only. I have split my previous PR.
=> COMP: MSVC AVX flag fix

Examples/RegistrationITKv4/DeformableRegistration3.cxx, Examples/RegistrationITKv4/DeformableRegistration5.cxx, Examples/RegistrationITKv4/DeformableRegistration9.cxx, Examples/RegistrationITKv4/LandmarkWarping2.cxx
The ResampleImageFilter is a more general filter than the
WarpImageFilter and should be preferred over the WarpImageFilter.
=> ENH: Update ITKv4 registration example to use resample over warp

Modules/Core/Common/include/itkImageRegionRange.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkImageRegionRangeGTest.cxx, Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx
Added `ImageRegionRange<TImage>` to the `itk::Experimental` namespace,
supporting modern C++ iteration (bidirectional) over a range of pixels
of an image region.
Replaced the classic `ImageRegionConstIterator<ImageType>` by
`ImageRegionRange<const ImageType>`, when doing bounding box computation
in `ImageMaskSpatialObject`. A performance improvement of 5 % or more
was observed.
=> ENH: Add ImageRegionRange<TImage> to itk::Experimental namespace

Modules/Remote/FixedPointInverseDisplacementField.remote.cmake
Adds:
matt.mccormick@kitware.com (1):
STYLE: Move Python test to wrapping/test/CMakeLists.txt
This will improve the nightly Doxygen builds.
=> BUG: ITKFixedPointInverseDisplacementField wrapping test config update

Modules/Filtering/ImageIntensity/wrapping/itkVectorExpandImageFilter.wrap
This class has been deprecated in favor of ExpandImageFilter.
=> BUG: Remove VectorExpandImageFilter wrapping

Wrapping/Generators/Python/Tests/CMakeLists.txt, Wrapping/Generators/Python/Tests/lazy.py, Wrapping/Generators/Python/itkLazy.py
Define __package__ on ITKLazyModule as described:
https://stackoverflow.com/questions/21233229/whats-the-purpose-of-the-package-attribute-in-python#21233334
https://www.python.org/dev/peps/pep-0366/
=> BUG: Add PEP 366 __package__ support to ITKLazyModule

Modules/Core/Common/src/itkThreadPool.cxx
Closes #1038. @DeswingBE, please check whether this fixes your problem.
=> Respect do not wait for threads

Modules/Core/TestKernel/include/itkTestingMacros.h
This is going into the release branch, which will turn into 5.0.1. I encountered the need for this while updating ITKMontage to use `ITK_` prefix on testing macros. I compile that with all legacies disabled.
=> STYLE: Add ITK prefix to testing macros in release branch

Wrapping/Generators/Python/PyUtils/itkPyCommand.cxx, Wrapping/Generators/SwigInterface/igenerator.py
Release the Python Global Interpreter Lock (GIL) so multi-threaded
Python applications, like Dask, can run in parallel while ITK does heavy
operations.
For more information, see section 32.13 Support for Multithreaded
Applications at
http://www.swig.org/Doc4.0/Python.html#Python
Also, set `nothreadallow` as suggested in the comments
on https://github.com/swig/swig/issues/927. This avoids calls to
`PyEval_SaveThread()` and `PyEval_RestoreThread()`, which can negatively
effect performance. This change only affects module C++ code -- code
that can call Python code like ITKPyUtils does not have `threads`
enabled.
=> BUG: Release the Python Global Interpreter Lock (GIL) during execution

Modules/Core/Common/include/itkThreadPool.h
=> DOC: invocation of AddWork uses -> as instance is always a pointer

Modules/Bridge/NumPy/wrapping/PyBuffer.i.in, Modules/Bridge/NumPy/wrapping/test/itkPyBufferTest.py
If a non-continuous array is passed in, the error is not constructed properly.  It is recommended that Python errors should not just say `raise "my error message here"` but instead  `raise MyExceptionClass("my error message here")`.
I found this while investigating an error in the itk-jupyter-widgets library, detailed here: https://github.com/InsightSoftwareConsortium/itk-jupyter-widgets/issues/156. Here is the relevant part of the error traceback:
```python-traceback
~/anaconda3/envs/viz/lib/python3.7/site-packages/itk/Configuration/../itkPyBufferPython.py in GetImageViewFromArray(ndarr, is_vector)
4044             "Only arrays of 2, 3 or 4 dimensions are supported."
4045         if( not ndarr.flags['C_CONTIGUOUS'] and not ndarr.flags['F_CONTIGUOUS'] ):
-> 4046             raise "Array …
```
=> BUG: All exceptions must be derived from python's BaseException class

.gitattributes, Modules/Core/Common/ITKKWStyleOverwrite.txt, Modules/Core/Common/src/itkCommand.cxx, Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshEulerOperatorSplitEdgeFunction.h, Modules/Filtering/FastMarching/ITKKWStyleOverwrite.txt, Modules/IO/RAW/include/itkRawImageIO.hxx, Modules/Numerics/Statistics/ITKKWStyleOverwrite.txt, Modules/Remote/AnalyzeObjectMapIO.remote.cmake, Utilities/KWStyle/ITK.kws.xml
Provide initial code changes to facilitate enforcement of an ITK style that can be uniformly applied in an automated way.
These problems appeared when enforcing a consistent style with the clang-formatting tool.  It is a first step towards providing an easier code formatting style enforcement throughout ITK.
=> STYLE: Prepare for clang format style enforcement

Wrapping/Generators/Python/Tests/lazy.py, Wrapping/Generators/Python/itkLazy.py
cloudpickle is used by Dask for transmitting the state of a Python
program.
Since LazyITKModule extends types.ModuleType, a few extras are required
to support its pickling.
__reduce_ex__ is re-implemented because modules using implement this
protocol, and initialization arguments are not the same as
LazyITKModule.
__getstate__ and __setstate__ are implemented to re-constitute the
LazyITKModule after it is de-serialized. Like cloudpickle's
implementation for loading dynamically created modules and imported
modules:
https://github.com/cloudpipe/cloudpickle/blob/2db58f11991fb655e5b188d385633d63cbfd2841/cloudpickle/cloudpickle.py#L1134-L1143
We restore the LazyITKModule attributes (which can include other
LazyITKModules's, e.g. `itk.ITKCommon` (`ITKCommon` is also an
ITKLazyModule), and we …
=> BUG: Support pickling LazyITKModule with cloudpickle

Wrapping/Generators/CastXML/CMakeLists.txt
itk_wrap_module_castxml now gets the COMPILE_DEFINITIONS of the
module top directory, instead of the wrapping directory.
The old behavior wasn't respecting the add_compile_definitions
set in the CMakeLists of the module.
Triggered by:
https://github.com/InsightSoftwareConsortium/ITKTotalVariation/pull/5
This is a follow on from: e3a908b49b569be0690227614f8e230262ac7bc2
=> BUG: Fix COMPILE_DEFINITIONS of castxml

Modules/Core/Common/include/itkNumericTraitsArrayPixel.h, Modules/Core/Common/src/itkArrayOutputSpecialization.cxx, Modules/Filtering/BiasCorrection/src/itkCompositeValleyFunction.cxx, Modules/IO/MeshBase/include/itkMeshIOBase.h, Modules/Numerics/Polynomials/include/itkMultivariateLegendrePolynomial.h, Modules/Numerics/Polynomials/src/itkMultivariateLegendrePolynomial.cxx, Modules/Numerics/Statistics/include/itkMeasurementVectorTraits.h, Modules/Video/Core/include/itkRingBuffer.hxx
Fix possible loss of data on type conversion, typically from a (possibly
64-bit) `size_t` to a 32-bit integer type, as suggested by various
occurrences of VS2017 warning C4244 and C4267 (when these warnings are
not disabled):
> video\core\include\itkRingBuffer.hxx(193): warning C4244: 'initializing': conversion from 'itk::RingBuffer<itk::DataObject>::OffsetValueType' to 'unsigned int'
> Filtering\BiasCorrection\src\itkCompositeValleyFunction.cxx(26): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int'
> Numerics\Polynomials\src\itkMultivariateLegendrePolynomial.cxx(151): warning C4267: 'argument': conversion from 'size_t' to 'int'
> Core\Common\src\itkArrayOutputSpecialization.cxx(29): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int'
> …
=> BUG: Fix possible loss of data on type conversion

Documentation/ITK5MigrationGuide.md
=> note re: ITK5 SpatialObject Scene to Group change

README.md
Azure dropped GitHub credentials for these builds. A new build was
created off the YAML configuration. This bumps the `definitionId`.
=> DOC: Update ITK.Linux.Python and ITK.Coverage README badges

Modules/Remote/SkullStrip.remote.cmake
Related to examples configuration.
Changes:
Jon Haitz Legarreta Gorroño (2):
ENH: Transition the example to the ITK testing framework.
BUG: Fix wrapping.
Matt McCormick (1):
BUG: Use ITK_TEMPLATE_EXPORT macro for StripTsImageFilter
=> BUG: Update SkullStrip module to address Doxygen configuration

Modules/Core/SpatialObjects/include/itkPolygonSpatialObject.hxx
=> BUG: Regression in PolygonSpatialObject::IsInsideInObjectSpace #1082

Modules/Remote/NeuralNetworks.remote.cmake
Explicitly specify that these methods are outdated.
Provide an explicit disclaimer that this historical set of features
is likely not appropriate for modern neural network implementations
due to performance issues.  The note is intended to assist with avoiding
confusion by users looking for modern machine learning approaches with
ITK.
=> ENH: Deprecate Neuralnetwork module

Wrapping/Generators/Python/CMakeLists.txt, Wrapping/Generators/Python/ModuleLoader.py.in
The ITK_WRAP_PYTHON_LEGACY needed to support backwards compatibility
for python support in ITKv4.  This was intended to be removed.
ITKv5 no longer supports this backwards compatibility.
=> STYLE: Remove deprecated support for ITK_WRAP_PYTHON_LEGACY

Modules/Remote/NeuralNetworks.remote.cmake
The warning should not be issued if the module is not requested.
=> DOC: Only warn when Module_NeuralNetworks is selected

Modules/Core/Transform/include/itkEuler3DTransform.hxx, Modules/Core/Transform/test/itkCenteredEuler3DTransformTest.cxx
=> BUG: offset was not updated after changing Euler angle order (ZYX)

Modules/Core/Common/test/itkImageRegionRangeGTest.cxx
@dzenanz reported the following compile warning from
Mac10.13-AppleClang-dbg-x86_64-static as issue #1147:
> itkImageRegionRangeGTest.cxx:188:8: warning: unused function template
> 'Check_Range_constructor_throws_...' [-Wunused-template]
This warning occurs only with debug builds. It is fixed by surrounding
the definition of the function template by `#ifdef NDEBUG` ... `#endif`.
Closes #1147.
=> COMP: ImageRegionRangeGTest issue #1147 Unused function template warning

Modules/ThirdParty/JPEG/src/itkjpeg/itk_jpeg_mangle.h
Added 4 symbols to itk_jpeg_mangle.h
_jpeg_aritab
jinit_arith_encoder
jinit_arith_decoder
jpeg_copy_critical_parameters_
nm libitkjpeg-5.1.a | grep " [RT] " output is OK now.
Before:
```
0000000000000030 T itk_jpeg_jpeg_free_large
0000000000000010 T itk_jpeg_jpeg_free_small
0000000000000020 T itk_jpeg_jpeg_get_large
0000000000000000 T itk_jpeg_jpeg_get_small
0000000000000040 T itk_jpeg_jpeg_mem_available
0000000000000060 T itk_jpeg_jpeg_mem_init
0000000000000070 T itk_jpeg_jpeg_mem_term
0000000000000050 T itk_jpeg_jpeg_open_backing_store
0000000000000000 T itk_jpeg_jpeg_abort
00000000000000a0 T itk_jpeg_jpeg_alloc_huff_table
0000000000000080 T itk_jpeg_jpeg_alloc_quant_table
0000000000000050 T itk_jpeg_jpeg_destroy
0000000000000090 T itk_jpeg_jcopy_block_row
0000000000000030 T …
```
=> ENH: added missing symbols to JPEG mangling header

Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.hxx, Modules/Core/ImageFunction/test/itkWindowedSincInterpolateImageFunctionTest.cxx
=> ENH: support RGB image in windowed sinc interpolation

Modules/Numerics/Statistics/include/itkVectorContainerToListSampleAdaptor.h, Modules/Registration/Metricsv4/include/itkEuclideanDistancePointSetToPointSetMetricv4.h, Modules/Registration/Metricsv4/include/itkExpectationBasedPointSetToPointSetMetricv4.h, Modules/Registration/Metricsv4/include/itkJensenHavrdaCharvatTsallisPointSetToPointSetMetricv4.h, Modules/Registration/Metricsv4/include/itkPointSetToPointSetMetricv4.h, Modules/Registration/Metricsv4/include/itkPointSetToPointSetMetricv4.hxx
=> Fix multithreaded point set to point set metric thread safety issue

Modules/Core/Transform/include/itkCompositeTransform.hxx
The GetNumberOfLocalParameters can return the wrong number of paramaters
when accessed by concurrent threads.
This fix does not fix the use case when multiple threads add or remove
transforms and access GetNumberOfLocalParameters at the same time. This
does not appear to be a use case that should be considered though.
=> BUG: Fix CompositeTransform ThreadSafety

Modules/Core/Common/include/itkStreamingImageFilter.hxx, Modules/Core/Common/src/itkStreamingProcessObject.cxx, Modules/Video/Core/src/itkTemporalProcessObject.cxx
Removed an implicit conversion from `DataObjectPointerArraySizeType`
(possibly 64-bits) to `unsigned int` (usually 32-bits), fixing a usually
disabled MSVC warning:
> itkStreamingProcessObject.cxx(137): warning C4267: 'initializing':
> conversion from 'size_t' to 'unsigned int', possible loss of data
Removed `static_cast<unsigned int>` from two `GetNumberOfRequiredInputs()`
calls, which caused the same possible loss of data (without a warning).
Improved consistency by declaring three similar `ninputs` variables in
the same way.
=> COMP: Fix loss of data ProcessObject GetNumberOfValidRequiredInputs()

Testing/ContinuousIntegration/AzurePipelinesBatch.yml
=> ENH: Adding VS2019 v142, VS2017 v140 Azure Pipelines on merge

Modules/Filtering/ImageIntensity/include/itkHistogramMatchingImageFilter.h, Modules/Filtering/ImageIntensity/include/itkHistogramMatchingImageFilter.hxx, Modules/Filtering/ImageIntensity/test/itkHistogramMatchingImageFilterTest.cxx
Allow histogram matching from with either reference image or reference histogram.
-  :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
-  :no_entry_sign: Adds the License notice to new files.
-  :no_entry_sign: Adds Python wrapping.
-  :no_entry_sign: Adds tests and baseline comparison (quantitative).
-  :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- :no_entry_sign: Adds …
=> ENH: Allow histogram matching with reference histogram

Modules/Bridge/NumPy/wrapping/test/CMakeLists.txt
The required Python `resource` module is Unix-only.
=> BUG: Do not run itkPyBufferMemoryLeakTest on Windows

Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmIPPSorter.cxx, Modules/ThirdParty/VNL/src/vxl/CMakeLists.txt
On my computer, this patch is not required to build with VS2019. Should we still consider merging it?
=> ENH: back-porting #1165 to support Visual Studio 2019

Modules/Filtering/ImageGrid/include/itkSliceImageFilter.hxx, Modules/Filtering/ImageGrid/test/itkSliceImageFilterTest.cxx
=> Fix slice image filter small size

Modules/Core/SpatialObjects/include/itkTubeSpatialObject.hxx, Modules/Core/SpatialObjects/test/itkTubeSpatialObjectTest.cxx
When computing tangents and normals for a tube spatial object, these are now calculated to maintain a discrete Frenet frame.
=> ENH: Converted TubeSpatialObject ComputeTangentsAndNormals to frenet

Modules/Filtering/ImageIntensity/wrapping/test/CMakeLists.txt, Modules/Filtering/ImageIntensity/wrapping/test/itkImageFilterNumPyInputsTest.py, Wrapping/Generators/Python/PyBase/pyBase.i, Wrapping/Generators/Python/itkExtras.py, Wrapping/Generators/Python/itkHelpers.py, Wrapping/Generators/SwigInterface/igenerator.py
When a NumPy array-like is passed into Python snake_case interface to
filters, the array-like arguments or standard image keyword arguments
are converted into itk.Image views, and passed to the filter. All image
outputs are converted to NumPy ndarray's if array's were used as
inputs.
Addresses #1136
=> ENH: Support NumPy array-like inputs to image filters

Modules/Filtering/Deconvolution/include/itkTikhonovDeconvolutionImageFilter.h, Modules/Filtering/Deconvolution/include/itkWienerDeconvolutionImageFilter.h
Work around internal compiler error with the MSVS v140 compiler
apparently related to default copy constructor used in the functor
generator filter.
=> COMP: Address internal compiler error on MSVC 19.0.24234.1 (v140)

Modules/Filtering/ImageIntensity/include/itkHistogramMatchingImageFilter.h, Modules/Filtering/ImageIntensity/include/itkHistogramMatchingImageFilter.hxx
Overload the VerifyPrecondition method to check the filters inputs are
set as required before pipeline execution.
=> ENH: Add check expected input in HistogramMatchingImageFilter

Modules/Filtering/ImageGrid/include/itkSliceImageFilter.hxx
The size of the output with a non-one step was being floored, instead
include an extra index if available. For example for a size of 5 and a
step of two the filter will now produce a size of 3.
Closes #1177.
=> BUG: Address bug with small size in output of SliceImageFilter

Modules/Numerics/Statistics/test/itkWeightedCovarianceSampleFilterTest.cxx, Modules/Numerics/Statistics/test/itkWeightedCovarianceSampleFilterTest2.cxx
ITK/Modules/Numerics/Statistics/test/itkWeightedCovarianceSampleFilterTest.cxx:57:7: warning: type ‘struct WeightedCovarianceTestFunction’ violates the C++ One Definition Rule [-Wodr]
class WeightedCovarianceTestFunction :
^
ITK/Modules/Numerics/Statistics/test/itkWeightedCovarianceSampleFilterTest2.cxx:56:7: note: a type with different bases is defined in another translation unit
class WeightedCovarianceTestFunction :
^
=> COMP: Remove One Definition Rule conflict

Modules/IO/MeshBase/include/itkMeshConvertPixelTraits.h
Compilation of wrapping types with
`gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`
Ensure all integer types have specialization for Fundamental types
defined in C++11:
https://en.cppreference.com/w/cpp/language/types
In file included from /home/johnsonhj/Dashboard/src/ITK/Modules/IO/MeshBase/include/itkMeshFileReader.h:36:0,
from /home/johnsonhj/Dashboard/src/ITK-bld/Wrapping/Typedefs/itkMeshFileReaderSwigInterface.h:21,
from /home/johnsonhj/Dashboard/src/ITK-bld/Wrapping/Modules/ITKIOMeshBase/itkMeshFileReaderPython.cpp:3519:
/home/johnsonhj/Dashboard/src/ITK/Modules/IO/MeshBase/include/itkMeshConvertPixelTraits.h: In instantiation of ‘class itk::MeshConvertPixelTraits<long long unsigned int>’:
/home/johnsonhj/Dashboard/src/ITK-bld/Wrapping/Modules/ITKIOMeshBase/itkMeshFileReaderPython.cpp:10 …
=> COMP: Fix missing type specialization for `unsigned long long int`

Modules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceImageFilter.h, Modules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceImageFilter.hxx
First error message: `C:\Dev\ITK-git\Modules\Core\GPUFiniteDifference\include\itkGPUFiniteDifferenceImageFilter.hxx(63,28): error C2065:  'UNINITIALIZED': undeclared identifier`.
=> COMP: fixed enum name error when legacy is OFF and ITK_USE_GPU is ON

Modules/IO/DCMTK/include/itkDCMTKImageIO.h, Modules/IO/DCMTK/src/itkDCMTKFileReader.cxx, Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx, Modules/IO/DCMTK/test/CMakeLists.txt
The first commit fixes #1125 and removes an outdated comment.
The second commit adds a metadata read for spacing (according to already existing comments in the code) to fix failing test `itkDCMTKImageIOMultiFrameImageTest`.
=> Bugfixes in DCMTK

Modules/Core/ImageFunction/wrapping/itkWindowedSincInterpolateImageFunction.wrap, Modules/Filtering/ImageGrid/wrapping/test/ResampleImageFilterTest.py
Required to pass an instance to ResampleImageFilter.
Closes #1100
=> BUG: Wrap WindowedSincInterpolateImageFunction SmartPointer

.gitattributes, CMake/ITKModuleClangFormat.cmake, Utilities/Hooks/pre-commit-style.bash, Utilities/SetupForDevelopment.sh
Automatically run `clang-format` on changed, non-third-party C++ files at pre-commit time, and allow the developer to review and test the style changes with the standard `git mergetool` configuration (see `git help mergetool`).
This should be merged after #1191 since most of the files in the repository currently have many changes when clang-format is executed.
=> Run clang-format on pre-commit

Modules/Core/SpatialObjects/include/itkTubeSpatialObject.hxx, Modules/Core/SpatialObjects/test/itkTubeSpatialObjectTest.cxx
TubeSpatialObjects can computer their tangets and normals in a frenet
frame, but normal directions can be ambiguous along a straight line, so
heuristics are used.   This fix adds to those heuristics so that they
work on a tube that is perfectly straight in the z-direction.
Previously such cases would produce NAN normals.
=> BUG: Resolve corner case bug in ComputeTangentsAndNormals in TubeSO

Modules/Core/SpatialObjects/include/itkContourSpatialObjectPoint.hxx, Modules/Core/SpatialObjects/include/itkDTITubeSpatialObjectPoint.hxx, Modules/Core/SpatialObjects/include/itkLineSpatialObjectPoint.hxx, Modules/Core/SpatialObjects/include/itkSpatialObjectPoint.h, Modules/Core/SpatialObjects/include/itkSpatialObjectPoint.hxx, Modules/Core/SpatialObjects/include/itkSurfaceSpatialObjectPoint.hxx, Modules/Core/SpatialObjects/include/itkTubeSpatialObjectPoint.hxx
The assignment operator for SpatialObjectPoint and its derived classes
that overwrite that member function were not updated to also copy
the SpatialObject pointer maintained within those classes.  That
pointer is critical to computing object to world transforms, and error
messages are given if those transforms are attempted without the
spatial object pointer of the point being set.   This commit adds
the copy of the SpatialObject pointer.
=> BUG: operator= defined in [tube|*]SpatialObjectPoint incomplete

Modules/Remote/AnisotropicDiffusionLBR.remote.cmake, Modules/Remote/BSplineGradient.remote.cmake, Modules/Remote/BioCell.remote.cmake, Modules/Remote/GenericLabelInterpolator.remote.cmake, Modules/Remote/Montage.remote.cmake, Modules/Remote/MorphologicalContourInterpolation.remote.cmake, Modules/Remote/RLEImage.remote.cmake, Modules/Remote/SphinxExamples.remote.cmake, Modules/Remote/SubdivisionQuadEdgeMeshFilter.remote.cmake, Modules/Remote/TextureFeatures.remote.cmake, Modules/Remote/TotalVariation.remote.cmake
There are probably some other changes in some of the remotes. I didn't check whether all the modules have the new changes.
=> ENH: update remote modules to comply with new enum class style

Wrapping/Generators/CastXML/CMakeLists.txt
This version of the castxml binary was built with the devtoolset2,
compatible with CentOS 5, which is necessary for building manylinux
binary Python packages with the manylinux Docker image.
=> BUG: Use castxml binary compatible with CentOS 5

Modules/Filtering/ImageGrid/test/itkPermuteAxesImageFilterTest.cxx
Add test to verify the correct origin produced by PermuteAxesImageFilter
=> ENH: Verify computation of origin in PermuteAxesImageFilter

Modules/IO/TIFF/src/itkTIFFImageIO.cxx
- [] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [] :no_entry_sign: Adds the License notice to new files.
- [] :no_entry_sign: Adds Python wrapping.
- [] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [] :no_entry_sign: Adds Documentation. …
=> BUG: Wrong component type for non supported tiff with USHORT palette

Modules/Core/Common/include/itkMetaProgrammingLibrary.h
Fixes #1130.
This new version might not be strictly equivalent to the old one but I could not find a counter example. I am, of course, open to suggestions.
=> BUG: Re-implement is_static_castable to be compatible with gcc 8

CMake/InsightValgrind-Ubuntu1804.supp
Valgrind is detecting access to uninitialized memory, the offending
line contains a comment that the array contains "garbage" but will
never be used.
closes #895.
=> BUG: Add valgrind suppression for zlib slide_hash

Modules/Filtering/LabelMap/include/itkShapeLabelObject.h, Modules/Filtering/LabelMap/test/itkShapeLabelMapFilterGTest.cxx
=> Fix shape label object obb verticies

Modules/IO/PNG/src/itkPNGImageIO.cxx
Allocated palette needs to be freed after writing is finished,
but before destroying the png structure
Ref #1238
=> BUG: solve memory leak when allocating png palette for writing

Modules/Registration/FEM/test/itkVTKTetrahedralMeshReader.hxx
This is required to build with legacy disabled. Message was:
`m:\dashboard\itk\modules\registration\fem\test\itkVTKTetrahedralMeshReader.hxx(55): error C2039: 'CellsAllocatedDynamicallyCellByCell': is not a member of 'itk::Mesh<MeshPixelType,3,itk::DefaultStaticMeshTraits<TPixelType,3,3,float,float,TPixelType>>' [M:\Dashboard\ITK-build\Modules\Registration\FEM\test\ITKFEMRegistrationTestDriver.vcxproj]`
=> COMP: update VTKTetrahedralMeshReader to enum class

Modules/Core/Common/include/itkByteSwapper.hxx, Modules/Core/Common/src/itkObjectFactoryBase.cxx, Modules/IO/ImageBase/src/itkImageIOBase.cxx, Modules/IO/LSM/src/itkLSMImageIO.cxx, Modules/IO/TIFF/src/itkTIFFImageIO.cxx, Modules/IO/VTK/src/itkVTKImageIO.cxx, Modules/Numerics/Optimizersv4/src/itkLBFGS2Optimizerv4.cxx
Replaced `reinterpret_cast` by `static_cast`, when converting a void to
a non-void pointer type. `static_cast` is in general less unsafe than
`reinterpret_cast`.
Fixes Visual C++ 2017 Code Analysis warning C26471: Don't use
reinterpret_cast. A cast from void* can use static_cast (type.1).
=> STYLE: Remove reinterpret_cast's from void to non-void pointer

Modules/Core/ImageAdaptors/test/itkVectorImageTest.cxx
Addressing uninitialized value detected by Valgrind.
Closes #1247.
=> BUG: Explicitly initialize CovariantVector in VectorImageTest

Modules/Core/Common/include/itkMacro.h
Fixes Visual Studio 2017 Code Analysis warnings from itkMacro.h:
> warning C26477: Use 'nullptr' rather than 0 or NULL (es.47).
Note that the formatting changes in the macro definition of
`itkGPUKernelClassMacro(kernel)` are from a post-commit hook.
These are unrelated to the fixes of those VS2017 warnings.
=> STYLE: Use C++11 nullptr in itkDynamicCastInDebugMode

Modules/ThirdParty/MetaIO/src/MetaIO/src/metaArrow.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaBlob.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaContour.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaDTITube.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaEllipse.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaFEMObject.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaGaussian.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaGroup.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaImage.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaLandmark.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaLine.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaMesh.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaScene.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaSurface.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaTransform.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaTube.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaTubeGraph.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaVesselTube.cxx
From https://github.com/Kitware/MetaIO/pull/81
Previously ObjectTypeName was only set for metaObject (top level) in
the Clear() function and was set in the M_SetupWriteFields() of
derived classes. Therefore, the value was fixed at "Object" until
the write command was called or a file was read (that then set the
type).
In this fixed version, the ObjectTypeName value is set in the Clear()
function of metaObject and its derived classes (and not in the
M_SetupWriteFields() function). Therefore, its value is correct
as soon as the class is instantiated.
=> BUG: Update MetaIO with MetaIO/#81 bug fix

Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx
Explicitly compares results of `dynamic_cast` to `nullptr`, when
estimating `isSpecialCoordinatesImage`, in `ResampleImageFilter`.
Fixes a Visual Studio 2017 Code Analysis warning:
> warning C26477: Use 'nullptr' rather than 0 or NULL (es.47).
=> STYLE: Use nullptr for isSpecialCoordinatesImage in ResampleImageFilter

Modules/Core/Common/src/itkMemoryUsageObserver.cxx, Modules/Core/Common/src/itkPlatformMultiThreaderWindows.cxx, Modules/Core/Common/src/itkWin32OutputWindow.cxx, Modules/IO/ImageBase/include/itkInternationalizationIOHelpers.h
Fixes Visual Studio 2017 Code Analysis warnings:
> warning C26477: Use 'nullptr' rather than 0 or NULL (es.47).
=> STYLE: Replace 0 by nullptr when appropriate

Modules/Remote/IsotropicWavelets.remote.cmake
To address the Doxygen CMake configuration error on the location of the
Python tests.
Changes:
Matt McCormick (3):
COMP: Wrap GaussianImageSource for StructureTensor
BUG: Move Python tests to wrapping/test/CMakeLists.txt
ENH: Build against ITK 5.0.1 and bump Python package version
=> BUG: Update IsotropicWavelets module for Doxygen build

Modules/Core/Common/include/itkMemoryProbe.h, Modules/Core/Common/test/itkMemoryProbesCollecterBaseTest.cxx
I have modified the memory probe test to illustrate the problem. The test fails without the proposed modification of itkMemoryProbe.h. This problem had actually been reported a long time ago in Jira by @cyrilmory but I don't know if we have access to the former bug tracker...
=> BUG: sign memory probe to detect freed memory

Examples/GUI/CMakeLists.txt, Examples/README.md, Examples/Wrapping/CMakeLists.txt
Refine purpose to accompany the ITK Software Guide. Point to the Sphinx
examples as a more comprehensive list.
Remove empty *GUI* and *Wrapping* directories.
=> DOC: Update Examples/README.md

Modules/Filtering/ImageIntensity/wrapping/test/itkImageFilterNumPyInputsTest.py, Wrapping/Generators/Python/itkHelpers.py, Wrapping/Generators/Python/itkTemplate.py
Previously there was a whitelist on which keywords would be
automatically converted from Numpy arrays to ITK Image objects.
Now, we accept any keyword that includes the text "image" in the name.
=> BUG: Support Numpy inputs in keywords that include "image"

Wrapping/Generators/Python/itkBase.py
This is an artifact of the WrapITK import, and it is no longer used.
This is evident by the use of `execfile`, which is not available in
Python 3, and git blame.
Closes #428
=> BUG: Remove WrapITK external project initialization

Wrapping/Generators/Python/CMakeLists.txt, Wrapping/Generators/Python/itk/__init__.py.in
This is a standard attribute used to provide the version in Python
packages.
Co-authored-by: Matthew Rocklin <mrocklin@gmail.com>
=> ENH: Add itk.__version__

Modules/Core/TestKernel/src/itkTestDriverInclude.cxx
This rarely mattered, as there was always more parameters afterwards.
Closes #1289.
=> BUG: wrong number of parameters was checked in itkTestDriverInclude

Modules/Remote/PhaseSymmetry.remote.cmake
Changes:
Matt McCormick (1):
BUG: Disable the module examples since they require SEM
To fix the Doxygen build.
=> DOC: Update PhaseSymmetry for Doxygen configuration

Modules/IO/NIFTI/src/itkNiftiImageIO.cxx, Modules/IO/NIFTI/test/itkNiftiImageIOTest.h
The NiftiImageIO only read the aux_file meta-data and did not support
writing it. Now it does.
=> ENH: Adding support for writing aux_file in Nifti.

Modules/IO/GDCM/src/itkGDCMImageIO.cxx
Particular DICOM [file](https://drive.google.com/file/d/1NoxBn2c3ypCRrqeGMDAqhFhXMYLm5ofN/view?usp=sharing) crash GDCMImageIO and related applications. To reproduce drag-and-drop the file onto Slicer or ITK-Snap  window or s. test at the end of the post. It is old bug.
In fact, any 16 bits allocated/8 bits stored file will crash, such files are seldom, but not so rare, s. all _Integris_ examples (extract .Z) in [www.creatis.insa-lyon.fr/~jpr/](https://www.creatis.insa-lyon.fr/~jpr/PUBLIC/gdcm/gdcmSampleData/Philips_Medical_Images/Integris_H_3_V_11/)
The file has _Bits Allocated 16_ and _Bits Stored 8_. Crash happens because [here](https://github.com/InsightSoftwareConsortium/ITK/blob/cdca76e2a3ab7ba5f134d217a9d96e3fcac6af86/Modules/IO/GDCM/src/itkGDCMImageIO.cxx#L414) pixel type is taken …
=> BUG: GDCMIO crashes if bits allocated 16, stored 8

Modules/Core/Common/include/itkNeighborhoodAllocator.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkNeighborhoodAllocatorGTest.cxx
Made the data members of `NeighborhoodAllocator` `private`, instead of
`protected`, to prevent a derived class from taking control over its
memory allocation and deallocation, and from breaking const-correctness.
Added `data()` member functions, to compensate for the loss of
functionality from making the data `private`, and to improve conformance
with C++11 Standard Library containers.
=> ENH: Add data() member functions to NeighborhoodAllocator

Modules/Core/Common/include/itkArray.h, Modules/Core/Common/include/itkArray.hxx, Modules/Core/Common/include/itkImageSink.hxx, Modules/Core/Common/include/itkImageToImageFilter.hxx, Modules/Core/Common/include/itkMatrix.h, Modules/Core/Common/include/itkVariableSizeMatrix.h, Modules/Core/Transform/include/itkKernelTransform.hxx, Modules/Core/Transform/include/itkRigid2DTransform.hxx, Modules/Filtering/DiffusionTensorImage/include/itkDiffusionTensor3DReconstructionImageFilter.hxx, Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.hxx, Modules/Filtering/ImageFeature/include/itkMaskFeaturePointSelectionFilter.hxx, Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx, Modules/Filtering/ImageStatistics/include/itkImageMomentsCalculator.hxx, Modules/Filtering/LabelMap/include/itkShapeLabelMapFilter.hxx, Modules/Filtering/LabelMap/include/itkStatisticsLabelMapFilter.hxx, Modules/Filtering/QuadEdgeMeshFiltering/include/itkQuadEdgeMeshDecimationQuadricElementHelper.h, Modules/IO/MINC/src/itkMINCImageIO.cxx, Modules/Numerics/Optimizersv4/include/itkObjectToObjectMetric.hxx, Modules/Numerics/Optimizersv4/include/itkQuasiNewtonOptimizerv4.hxx, Modules/Segmentation/LevelSets/include/itkLevelSetFunction.hxx
vxl implicitly casts between various storage types (i.e.
from vnl_vector_fixed to vnl_vector), and many algorithms
are only written to accept vnl_[vector|matrix]<T> types.
Best practice guidelines recommend that single argument constructors
and type cast operations be made `explicit` to avoid
surprising implicit conversions.  Making vxl conform to this
best practice requires explicitly requesting the most
appropriate typecast.
Additionally, reviewing and modifying to future proof
to take advantage of move constructor/assignment by
prefering initialization to assignment.
=> ENH: Prefer explicit casting over implicit casting for vxl

Modules/IO/GDCM/src/itkGDCMImageIO.cxx
itk::Image do not carry color space information. So convert from YBR_FULL to
RGB, even if it introduce a small loss. Loss is visually imperceptible, should
only impact quantitative analysis.
=> BUG: Always convert YBR_FULL to RGB

Modules/Video/BridgeOpenCV/src/itkOpenCVVideoIO.cxx, Modules/Video/BridgeOpenCV/test/itkOpenCVImageBridgeGrayScaleTest.cxx, Modules/Video/BridgeOpenCV/test/itkOpenCVImageBridgeRGBTest.cxx, Modules/Video/BridgeOpenCV/test/itkOpenCVVideoIOFactoryTest.cxx
Ref #806.
This makes some progress, but tests still run into two compile errors of type: `error C2039: 'cvLoadImage': is not a member of 'cv'`. It looks like they removed `cvLoadImage` from OpenCV 4.
It would be good if someone more familiar with OpenCV could take over this PR.
=> OpenCV update

Modules/Core/Common/include/itkNeighborhoodAllocator.h, Modules/Core/Common/test/itkNeighborhoodAllocatorGTest.cxx
Declares `NeighborhoodAllocator::m_Data` as a `unique_ptr`, instead of
a raw pointer. Removes low level `delete[]` from `NeighborhoodAllocator`
implementation.
Fixes a potential memory leak when an ITK user would directly call
`Allocate(n)`, and a potential crash when a user would directly call
`Deallocate()`.
Added unit tests for `NeighborhoodAllocator` member functions,
`Allocate(n)` and `Deallocate()`.
Note: it appears that these functions should not be called directly, by
the end user.
=> STYLE: Modernize NeighborhoodAllocator data management

Documentation/ITK5MigrationGuide.md
=> DOC: Adding migration guide for "vector" filters

Modules/Core/Common/include/itkNumericTraitsRGBAPixel.h, Modules/Core/Common/include/itkNumericTraitsRGBPixel.h
=> ENH: add IsPositive() and friends to RGB's and RGBA's NumericTraits

Modules/IO/TransformMINC/itk-module.cmake, Modules/IO/TransformMINC/src/itkMINCTransformIO.cxx, Modules/IO/TransformMINC/test/itkIOTransformMINCTest.cxx
BUG: fixed composite transform writing to MINC .xfm
I noticed that composite transform and MINC transform API actually have different order of representing concatenated transformations. 
=> fixed composite transform writing to MINC .xfm

Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h, Modules/Core/Common/test/itkImageRegionRangeGTest.cxx, Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx
Ensured that `RangeType::iterator` and `RangeType::const_iterator` are
the same type, when the range is declared to iterate over a `const`
image:
- Added compile-time tests to `ImageRegionRange` and
`ShapedImageNeighborhoodRange`
- Adjusting `ShapedImageNeighborhoodRange::iterator` accordingly.
Note that `ImageBufferRange` was already OK.
This commit aims to improve consistency between ITK image range types.
=> STYLE: For a const image, iterator and const_iterator should be the same

Wrapping/Generators/Python/itk/__init__.py.in
Since Python 3.4, this is required for the importlib machinery per:
https://docs.python.org/3/library/importlib.html#importlib.machinery.ModuleSpec
=> BUG: Set the __spec__ attribute on the itk package

.circleci/config.yml
Free/Open source plans are limited to the default resource class.
=> BUG: Use default CircleCI resources

Documentation/ITK5MigrationGuide.md
=> DOC: Grammar fixes in vector filter section of migration guide

Modules/Remote/PhaseSymmetry.remote.cmake
* BUG: maintain image direction in internal filters. Closes #23.
* ENH: use ITKImageIO and ITKTransformIO in examples' CMakeLists.txt
* COMP: build with legacy disabled
* ENH: allow finding ITK via configuration file
=> ENH: update PhaseSymmetry remote module

Modules/Core/ImageFunction/include/itkSumOfSquaresImageFunction.h, Modules/Core/ImageFunction/include/itkSumOfSquaresImageFunction.hxx
Improved the performance of `SumOfSquaresImageFunction::EvaluateAtIndex`
by replacing its local `itk::ConstNeighborhoodIterator` variable by
an `Experimental::ShapedImageNeighborhoodRange` variable.
Using `ShapedImageNeighborhoodRange` this way will improve the
performance of `EvaluateAtIndex`, because the range does not do any
dynamic memory allocation, and because its "shape offsets",
`m_NeighborhoodOffsets` are generated beforehand (outside of
`EvaluateAtIndex`).
`ImageFunction::EvaluateAtIndex` is typically called repetitively
("for each pixel"), so it appears worth optimizing this member function.
=> PERF: Use ShapedImageNeighborhoodRange in SumOfSquaresImageFunction

Modules/Core/Common/include/itkImageKernelOperator.hxx
Improved the performance of `ImageKernelOperator::GenerateCoefficients()`,
by replacing its local `ImageRegionConstIterator` variable by an
`Experimental::ImageBufferRange`.
In general, when a function iterates over an entire image buffer,
`ImageBufferRange` is significantly faster than
`ImageRegionConstIterator`.
=> PERF: Use ImageBufferRange in ImageKernelOperator GenerateCoefficients()

Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.hxx, Modules/Core/Common/test/itkBSplineInterpolationWeightFunctionTest.cxx
The constructor of `BSplineInterpolationWeightFunction` originally
created a `tempImage`, just for `ImageRegionConstIteratorWithIndex` to
iterate over an index space of size `m_SupportSize`.
This commit replaces this use of `ImageRegionConstIteratorWithIndex` by
`ZeroBasedIndexRange`, which efficiently iterates over a zero-based
index space, without the need for a `tempImage`.
=> PERF: Use IndexRange in BSplineInterpolationWeightFunction constructor

Modules/Core/ImageFunction/test/CMakeLists.txt, Modules/Core/ImageFunction/test/itkSumOfSquaresImageFunctionGTest.cxx
Suggested by Bradley @blowekamp at pull request #1324
Triggered by commit "PERF: Use ShapedImageNeighborhoodRange in
SumOfSquaresImageFunction", SHA-1 e3fd64de1408c79c50fb17e3f046e1d5d98a89c6
=> ENH: Add GoogleTest for SumOfSquaresImageFunction

Modules/Segmentation/Watersheds/include/itkWatershedSegmenter.hxx
Improved the performance of `watershed::Segmenter::InitializeBoundary()`
by replacing its iteration over the buffered region of a face image by
a simple `Image::FillBuffer` call.
=> PERF: Call FillBuffer in watershed Segmenter::InitializeBoundary()

Modules/Core/ImageFunction/include/itkMeanImageFunction.h, Modules/Core/ImageFunction/include/itkMeanImageFunction.hxx
Improved the performance of `MeanImageFunction::EvaluateAtIndex`
by replacing its local `itk::ConstNeighborhoodIterator` variable by
an `Experimental::ShapedImageNeighborhoodRange` variable.
Similar to a previous commit:
"PERF: Use ShapedImageNeighborhoodRange in SumOfSquaresImageFunction"
SHA-1 e3fd64de1408c79c50fb17e3f046e1d5d98a89c6
=> PERF: Use ShapedImageNeighborhoodRange in MeanImageFunction

Utilities/Hooks/pre-commit-style.bash
This branch makes the clang-format version check only require the major.minor version.
Also, documentation is added to explain that `KWStyle` is built and `clang-format` is downloaded once ITK has been built with `BUILD_TESTING` enabled.
Fixes #1215
=> Style check version checks and documentation

Testing/ContinuousIntegration/AzurePipelinesBatch.yml, Testing/ContinuousIntegration/AzurePipelinesLinux.yml, Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml, Testing/ContinuousIntegration/AzurePipelinesMacOS.yml, Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml, Testing/ContinuousIntegration/AzurePipelinesWindows.yml, Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
It looks like GitHub releases is failing to serve 5.0.0 ExternalData tarballs. This may not resolve the issue, but it will not hurt.
=> ENH: Update CI ExternalDataVersion to 5.0.1

Modules/IO/GDCM/test/itkGDCMImageIONoCrashTest.cxx
This should have been part of 71c90c83de8631e655144ad9eb6a462bcf059f56.
=> COMP: compile the test with legacy disabled

Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmRescaler.cxx, Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmRescaler.h
=> Heap buffer overflow in itkImportImageContainer

Modules/Core/TestKernel/include/itkTestingStretchIntensityImageFilter.hxx
Improved the performance of `Testing::StretchIntensityImageFilter`
member function `BeforeThreadedGenerateData()` by replacing its local
`ImageRegionConstIteratorWithIndex` variable by an
`Experimental::ImageBufferRange`.
In general, when a function iterates over an entire image buffer,
`ImageBufferRange` is significantly faster than
`ImageRegionConstIteratorWithIndex`.
=> PERF: Use ImageBufferRange in Testing::StretchIntensityImageFilter

Modules/Core/Common/include/itkMacro.h
The use of the ITK_LEGACY_SILENT:BOOL=ON ITK_LEGACY_REMOVE:BOOL=OFF
created warrnings that were initially missed.  These should be
silent.
=> BUG: Warning macros for ITK_LEGACY_SILENT are wrong

Modules/Core/ImageFunction/include/itkMedianImageFunction.h, Modules/Core/ImageFunction/include/itkMedianImageFunction.hxx
Improved the performance of `MedianImageFunction::EvaluateAtIndex`
by replacing its local `itk::ConstNeighborhoodIterator` variable by
an `Experimental::ShapedImageNeighborhoodRange` variable.
Analog to recent commits on other `ImageFunction` templates:
- "PERF: Use ShapedImageNeighborhoodRange in MeanImageFunction"
SHA-1 7e6a391160df7551cb9f3da416d3ac3d3f02e441
- "PERF: Use ShapedImageNeighborhoodRange in SumOfSquaresImageFunction"
SHA-1 e3fd64de1408c79c50fb17e3f046e1d5d98a89c6
=> PERF: Use ShapedImageNeighborhoodRange in MedianImageFunction

Modules/Core/Common/include/itkChildTreeIterator.hxx, Modules/Core/Common/include/itkTreeIteratorBase.h, Modules/Core/Common/include/itkTreeIteratorBase.hxx
=> BUG: fix null deref in 'itkTreeContainerTest'. Closes #1358.

Modules/IO/NIFTI/src/itkNiftiImageIO.cxx, Modules/IO/NIFTI/test/itkNiftiReadAnalyzeTest.cxx
We noticed that after switching from old (ITK3) AnalyzeImageIO reader to
NiftiImageIO reader for Analyze files, the directions have changed
It was caused by the fact that the new NIFTI reader is ignoring
Analyze orientation code, which was breaking our tests.
Code added - more correct interpretation of Analyze header and a Unit Test
that makes sure that orientation is correctly converted to the image directions.
=> ENH: Restored behaviour of depricated Analyze reader w.r.t orientation code

Modules/Core/ImageFunction/test/itkLinearInterpolateImageFunctionTest.cxx, Modules/IO/ImageBase/include/itkImageSeriesWriter.hxx, Modules/IO/ImageBase/src/itkNumericSeriesFileNames.cxx, Modules/IO/NIFTI/test/itkNiftiImageIOTest.h, Modules/IO/NIFTI/test/itkNiftiImageIOTest3.cxx, Modules/IO/PNG/src/itkPNGImageIO.cxx
=> COMP: Properly conditionalize _snprintf hack to only old MS compilers

Modules/Filtering/QuadEdgeMeshFiltering/include/itkQuadEdgeMeshDecimationQuadricElementHelper.h
Fixes error reported in https://open.cdash.org/viewBuildError.php?buildid=6179213
Related to http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3922.html
See also https://stackoverflow.com/questions/25612262/why-does-auto-x3-deduce-an-initializer-list
=> COMP: Fixing autodeduction of type for old clang compiler

Modules/IO/GDCM/include/itkGDCMImageIO.h, Modules/IO/GDCM/src/itkGDCMImageIO.cxx
Add string buffer length argument to methods using C strings for
output.
=> BUG: Address buffer overflow with deprecated GDCM1 interface

Modules/Filtering/ImageGrid/include/itkBSplineScatteredDataPointSetToImageFilter.hxx
Use the VectorContainer's STL interface to avoid causing MTime to be
called too many time. This has reported to overflow the global time
stamp with it's a 32-bit integer.
SimpleITK/SimpleITK#750
closes #1352
=> BUG: Don't use InsertElement which modifies MTime

Modules/Core/Common/include/itkBufferedImageNeighborhoodPixelAccessPolicy.h, Modules/Filtering/Smoothing/include/itkMeanImageFilter.h, Modules/Filtering/Smoothing/include/itkMeanImageFilter.hxx
Improved the performance `MeanImageFilter`, using `ShapedImageNeighborhoodRange` with a newly added pixel access policy, `BufferedImageNeighborhoodPixelAccessPolicy`. Tested performance by:
#include <itkMeanImageFilter.h>
#include <itkImage.h>
#include <chrono>
#include <iostream>
int main()
{
using ImageType = itk::Image<char, 3>;
const auto image = ImageType::New();
const auto size = ImageType::SizeType{ 1024, 1024, 16 };
image->SetRegions(size);
image->Allocate(true);
const auto filter = itk::MeanImageFilter<ImageType, ImageType>::New();
for (int i{}; i < 8; ++i)
{
filter->SetInput(nullptr);
filter->SetInput(image);
using namespace std::chrono;
const auto timePointBeforeUpdate = high_resolution_clock::now();
filter->Update();
const auto timePointAfterUpdate = …
=> PERF: MeanImageFilter faster, using BufferedImageNeighborhoodPixelAccessPolicy

Modules/Filtering/Smoothing/test/CMakeLists.txt, Modules/Filtering/Smoothing/test/itkMeanImageFilterGTest.cxx, Modules/Filtering/Smoothing/test/itkMedianImageFilterGTest.cxx
Added GTest for `itk::MeanImageFilter` (complementary to
"itkMeanImageFilterTest.cxx"), and `itk::MeanImageFilter`
(complementary to "itkMedianImageFilterTest.cxx").
=> ENH: Add GoogleTests for MeanImageFilter and MedianImageFilter 

Modules/Remote/MinimalPathExtraction.remote.cmake
Update to version that removes deprecated throw decorator for functions.
The throw decorator was deprecated in C++11.
See:
[ITMInaimalPathExtraction Commit](https://github.com/InsightSoftwareConsortium/ITKMinimalPathExtraction/commit/322e9338d76b7dcfb98861c6c22e5645806821d7)
=> COMP: Update MinimalPathExtraction to remove warnings

Modules/Filtering/ImageGrid/include/itkResampleImageFilter.h, Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx, Modules/Filtering/ImageGrid/test/itkResampleImageFilterGTest.cxx
Using a "ReferenceImage" for the ResampleImageFilter is a two step
process requiring both 'SetReferenceImage(im)' and 'UseReferenceImageOn()'.
Failing to use both calls silently generates a resampled image of size
zero in all dimensions.
=> ENH: Improve diagnostic warnings for ResampleImage misuse

Modules/Core/Common/include/itkNeighborhoodAlgorithm.h, Modules/Core/Common/include/itkNeighborhoodAlgorithm.hxx, Modules/Filtering/Smoothing/include/itkMeanImageFilter.hxx
`NeighborhoodAlgorithm::ImageBoundaryFacesCalculator::operator()` places
the non-boundary region (at the center) in a list together with all the
boundary regions (the faces) that it has found. It appears clearer to
keep the non-boundary region and the boundary regions separate.
This commit adds a `Compute(image, region, radius)` member function
and a result type `Result` to `ImageBoundaryFacesCalculator`, which
keep them separate.
It replaces the old `operator()` call by a call to the new `Compute`, in
`MeanImageFilter`, to shorten the code and improve readability.
`operator()` is now implemented by calling `Execute`. `operator()` still
returns the list that has all regions together, as it did before.
=> ENH: Separate boundary/non-boundary regions ImageBoundaryFacesCalculator

Modules/Filtering/Smoothing/test/itkMeanImageFilterGTest.cxx, Modules/Filtering/Smoothing/test/itkMedianImageFilterGTest.cxx
Works around compilation errors (presumably because of compiler bugs) in
itkMeanImageFilterGTest and itkMedianImageFilterGTest, as two compilers
failed to deduce the size of an array that is passed by reference, from
an initializer-list argument.
Ubuntu-gcc4.6-Release:
> note: template argument deduction/substitution failed:
> note: couldn't deduce template parameter 'VNumberOfExpectedPixels'
Mac10.10-AppleClang-dbg-x86_64-static
> note: candidate template ignored: couldn't infer template argument 'VNumberOfExpectedPixels'
The fix consists of using `std::vector` instead. Which has another
advantage (compared to using a reference to a C-style array), that it
can be passed directly to the GoogleTest `EXPECT_EQ` macro.
Reported by Dženan Zukić (@dzenanz)
=> COMP: Fix GTest gcc4.6, Mac10.10 error VNumberOfExpectedPixels deduction

Modules/Filtering/Smoothing/include/itkMedianImageFilter.hxx
Improved the performance of `MedianImageFilter::Update`
by replacing its local `itk::ConstNeighborhoodIterator` variable by
`Experimental::ShapedImageNeighborhoodRange` variables, using
`BufferedImageNeighborhoodPixelAccessPolicy` for the non-boundary
(center) subregion.
~25% reduction of the run-time duration was observed on a
`filter->Update()` call, using VS2017, processing a 256x256x256 image.
For a 1024x1024x16 image, the performance improvement appeared even higher.
=> PERF: Use ShapedImageNeighborhoodRange in MedianImageFilter

Modules/Filtering/Smoothing/include/itkMeanImageFilter.hxx, Modules/Filtering/Smoothing/include/itkMedianImageFilter.hxx
Fixes a warning from Mac10.14-AppleClang-dbg-ASanUBSan, reported by
Dženan Zukić @dzenanz:
> warning: loop variable 'boundaryFace' of type 'const itk::ImageRegion<3>'
> creates a copy from type 'const itk::ImageRegion<3>' [-Wrange-loop-analysis]
=> COMP: Range-based for-loops on BoundaryFaces should use reference

Modules/Core/Common/include/itkIndexRange.h, Modules/Core/Common/test/itkIndexRangeGTest.cxx
`IndexRange` did behave incorrectly when it would be constructed with an
`itk::Size` that has one or more zero values _and_ a non-zero value at
its last position, for example `Size<3>{{0, 0, 8}}`. Specifically, in
that case the iterators returned by `IndexRange::begin()` and
`IndexRange::end()` were different, while they should compare equal.
This bug caused Valgrind defects, issue #1397, reported by Bradley
@blowekamp
The bug affects both `IndexRange` specializations,
`ImageRegionIndexRange` and `ZeroBasedIndexRange`.
This bug fix ensures that a `itk::Size` that has one or more zero values
is treated the same way as a `itk::Size` that has _only_ zero values.
Fixes issue #1397 Valgrind Defects related to the MedianImageFilter
=> BUG: Fix IndexRange for itk::Size that has both zero's and non-zero's

Modules/Filtering/BinaryMathematicalMorphology/include/itkBinaryClosingByReconstructionImageFilter.hxx, Modules/Filtering/BinaryMathematicalMorphology/include/itkBinaryDilateImageFilter.h, Modules/Filtering/BinaryMathematicalMorphology/include/itkBinaryErodeImageFilter.h, Modules/Filtering/BinaryMathematicalMorphology/include/itkBinaryMorphologicalClosingImageFilter.hxx, Modules/Filtering/BinaryMathematicalMorphology/include/itkBinaryMorphologicalOpeningImageFilter.hxx, Modules/Filtering/BinaryMathematicalMorphology/include/itkBinaryOpeningByReconstructionImageFilter.hxx
The generalalization of "binary" as '0' and 'not zero'
is not used in the "Binary[Dilate|Erode]ImageFilter.
Images with values of 0 or 1 require an explicit setting
of the DilateValue or ErodeValue to 1 in order to
designate 1 as the foreground value to be dilated/eroded.
Expand the documentation to more forcefully convey this
important consideration.
=> DOC: More clearly describe foreground/background

Modules/Filtering/Smoothing/include/itkMeanImageFilter.h, Modules/Filtering/Smoothing/include/itkMeanImageFilter.hxx
Replaced `std::unique_ptr<Offset>[]>` by `std::vector<Offset>`, storing
the rectangular neighborhood shape offsets of the filter.
Replaced old-style `for` by C++11 range-based for-loop on
`ImageRegionIndexRange`.
Removed unnecessary local `ImageRegionRange` variable.
This commit aims to improve code readability, while it does not seem to
make the filter any slower. Actually, the filter seems slightly faster
than before (as observed with VS2017 Release).
=> STYLE: MeanImageFilter use vector<Offset>, range-based-for on IndexRange

Modules/Core/Common/include/itkIndex.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkIndexGTest.cxx
Added static `itk::Index` member function `Filled(value)`,
analogue to `FixedArray::Filled(value)` and `Size::Filled(value)`.
This convenience function should ease initializing a data member or a
local variable of type `itk::Index<N>` with the proper content.
Follow-up to 8d915a0fb1cb4d9c5adb6abd9c243c77e800cbf6, 2019-04-12:
"ENH: Add static member function Size<VDimension>::Filled(SizeValueType)"
=> ENH: Add static member function itk::Index::Filled(IndexValueType)

Modules/IO/BMP/src/itkBMPImageIO.cxx, Modules/IO/BMP/test/CMakeLists.txt, Modules/IO/BMP/test/itkBMPImageIOTestExtension.cxx
This change allows reading BMP files that have wrong extension.
=> BUG: BMP can't be read without proper extension

Modules/Numerics/Statistics/test/itkStatisticsAlgorithmTest.cxx
Fixes the issue for VS2015 but I don't have _MSC_FULL_VER 191025017 #1287
=> BUG: Workaround for segfault in itkStatisticsAlgorithmTest (v140)

Modules/Core/Common/include/itkMacro.h, Modules/Filtering/DisplacementField/include/itkDisplacementFieldToBSplineImageFilter.hxx, Modules/IO/ImageBase/include/itkImageSeriesReader.hxx, Modules/IO/TIFF/src/itkTIFFImageIO.cxx, Modules/Numerics/Optimizersv4/src/itkLBFGS2Optimizerv4.cxx, Modules/Numerics/Optimizersv4/src/itkLBFGSBOptimizerv4.cxx, Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
See: https://wiki.sei.cmu.edu/confluence/display/c/PRE10-C.+Wrap+multistatement+macros+in+a+do-while+loop
Apparently some formatting got updated by KWStyle,clangformat on commit. 
=> COMP: Fixed itkWarningMacro and itkDebugMacro to confirm to PRE10-C

Modules/Core/Common/include/itkIndexRange.h
There was an inconsistency between the constructors of `IndexRange`, in
the way they initialized the private `m_MaxIndex` member variable for an
empty range. For example, for `IndexRange<3, true>{ itk::Size<3>() }`,
m_MaxIndex is `{-1, -1, -1}`, whereas for a default-constructed
`IndexRange<3, true>()`, m_MaxIndex used to be `{0, 0, -1}`.
This commit fixes the inconsistency by ensuring that m_MaxIndex is
filled entirely by `-1` (for 3-D, that is `{-1, -1, -1}`), when the
range is default-constructed.
It also reduces the complexity of `IndexRange::empty()` from O(n) to
O(1), as it is sufficient now to just compare the first elements of
`m_MinIndex` and `m_MaxIndex`.
=> STYLE: Fix small inconsistency between IndexRange constructors

Modules/IO/ImageBase/include/itkImageSeriesReader.h, Modules/IO/ImageBase/include/itkImageSeriesReader.hxx, Modules/IO/ImageBase/test/CMakeLists.txt, Modules/IO/ImageBase/test/itkImageSeriesReaderSamplingTest.cxx
A simple change to the ImageSeriesReader to verify spacing between consecutive images, addresses InsightSoftwareConsortium/ITK#441 , can be used to diagnose missing dicom slices. 
CC: @seanm 
=> ENH: Added code to detect non-uniform sampling in ImageSeriesReader

Modules/IO/BMP/test/itkBMPImageIOTestExtension.cxx
Fixes warning on AppleClang
https://open.cdash.org/viewBuildError.php?type=1&buildid=6201669
=> STYLE: Add additional braces around initialization of subobject

Modules/Filtering/ImageGradient/include/itkGradientImageFilter.hxx, Modules/Filtering/ImageGradient/include/itkGradientMagnitudeImageFilter.hxx
It appears unnecessary to evaluate `operator.GetRadius()[0]` for a
`DerivativeOperator` that has a default direction and a default order,
after calling `DerivativeOperator::CreateDirectional()`. The radius
value estimated that way will always be exactly one.
This information is used to simplify the implementation of
`GradientImageFilter` and `GradientMagnitudeImageFilter`.
=> STYLE: Remove run-time estimation of operator radius in gradient filters

Modules/Core/Common/include/itkNeighborhood.hxx
Simplified the implementation of the protected `Neighborhood` member
function `ComputeNeighborhoodStrideTable()`, removing an unnecessary
inner `for` loop and a local `stride` variable.
=> STYLE: Simplify Neighborhood::ComputeNeighborhoodStrideTable()

Modules/Core/Common/include/itkAnnulusOperator.h, Modules/Core/Common/include/itkDerivativeOperator.h, Modules/Core/Common/include/itkForwardDifferenceOperator.h, Modules/Core/Common/include/itkGaussianDerivativeOperator.h, Modules/Core/Common/include/itkGaussianDerivativeOperator.hxx, Modules/Core/Common/include/itkGaussianOperator.h, Modules/Core/Common/include/itkImageKernelOperator.h, Modules/Core/Common/include/itkLaplacianOperator.h, Modules/Core/Common/include/itkNeighborhoodOperator.h, Modules/Core/Common/include/itkSobelOperator.h, Modules/Core/Common/test/itkNeighborhoodOperatorTest.cxx
Adjusted `NeighborhoodOperator` and eight derived classes according to
the C++ Rule of Zero for special member functions, by removing
used-declared default-constructors, copy-constructors, and assignment
operators.
Implicitly fixed an old bug in the assignment of `LaplacianOperator`, as
it previously did not copy its `m_DerivativeScalings` data member.
This commit effectively makes move-construction and move-assignment of
those classes "noexcept", as is checked in newly added static
assertions, in itkNeighborhoodOperatorTest. It could also improves the
performance of a "move" of such a type of object.
=> STYLE: C++ Rule of Zero for Neighborhood Operators, support nothrow move

CMake/InsightValgrind-CentOS7.supp
=> ENH: Adding Valgrind suppression file for CentOS 7 system

Modules/IO/TransformHDF5/include/itkHDF5TransformIO.h, Modules/IO/TransformHDF5/itk-module.cmake, Modules/IO/TransformHDF5/src/itkHDF5TransformIO.cxx
Forward-declared `H5::PredType`, and moved the `#include "itk_H5Cpp.h"`
from itkHDF5TransformIO.h to the corresponding cxx file.
Removed `ITKHDF5` from its itk_module `TEST_DEPENDS`, as suggested by
Bradley @blowekamp
Could reduce compilation time and header file dependencies.
=> STYLE: Move #include "itk_H5Cpp.h" from itkHDF5TransformIO.h to cxx file

Modules/IO/BMP/src/itkBMPImageIO.cxx
The magic number can be check for any file now.
=> BUG: Remove noisy cerr output when magic number fails

Modules/Core/Common/wrapping/ITKCommonBase.wrap
As far as I understand, [`IterationReporter`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkIterationReporter.h) is not yet wrapped, thus is unusable from Python. This contribution should fix this.
[We are currently trying to implement iteration reporting in RTK](https://github.com/SimonRit/RTK/pull/266), and this missing wrapping prevents us from testing our code from Python.
As this is my first contribution to ITK ever, I hope I did everything alright!
=> ENH: wrap IterationReporter

Modules/IO/ImageBase/include/itkImageFileReader.hxx
We need information weather the image was flipped to compensate for the negative steps.
This fix can also help resolve the issues menioned in https://github.com/InsightSoftwareConsortium/ITK/commit/7501479a970694b0dd4a8c4bbf7cbcc033fe059c
=> ENH: Preserving information about auto-flipped negative steps in metadata

Modules/IO/ImageBase/include/itkImageIOBase.h, Modules/IO/ImageBase/src/itkImageIOBase.cxx, Modules/IO/LSM/src/itkLSMImageIO.cxx
=> BUG: Remove tiff from supported extensions for LSMImageIO

Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx
Creating a local type definition that is the same as one of the parent classes
causes compiler warnings.
=> ENH: Shadowed typedef warnings removed

Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix_ref.h, Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector.h, Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector.hxx, Modules/ThirdParty/VNL/src/vxl/vcl/CMakeLists.txt
=> Update vnl 11 21 19

Modules/Core/Common/test/itkPointGeometryTest.cxx
These two errors are getting fixed. Ref #1431.
In project ITKCommon1TestDriver, file C:\Dev\ITK-2019\Modules\Core\Common\test\itkPointGeometryTest.obj, line 1: Error LNK2019: unresolved external symbol "public: __cdecl vnl_vector_ref<double>::vnl_vector_ref<double>(unsigned int,double *)" (??0?$vnl_vector_ref@N@@QEAA@IPEAN@Z) referenced in function "public: class vnl_vector_ref<double> __cdecl itk::Point<double,3>::GetVnlVector(void)" (?GetVnlVector@?$Point@N$02@itk@@QEAA?AV?$vnl_vector_ref@N@@XZ)
In project ITKCommon1TestDriver, file C:\Dev\ITK-2019\Modules\Core\Common\test\itkPointGeometryTest.obj, line 1: Error LNK2019: unresolved external symbol "public: __cdecl vnl_vector_ref<double>::~vnl_vector_ref<double>(void)" (??1?$vnl_vector_ref@N@@QEAA@XZ) referenced in function "int __cdecl …
=> COMP: fixing a couple of VNL related linking errors

Modules/IO/TransformHDF5/src/itkHDF5TransformIO.cxx
This commit avoids copying `parameters` to a local dynamically allocated
buffer, in `WriteParameters` and `WriteFixedParameters`. This could
improve the performance, as well as exception safety.
It uses `std::unique_ptr`, instead of a raw pointer, in `ReadParameters`
and `ReadFixedParameters`, just to improve exception safety.
This commit fixes six warning C26407 messages from VS2017 Code Analysis:
> Prefer scoped objects, don't heap-allocate unnecessarily
=> PERF: Do not allocate buffer in HDF5TransformIOTemplate::WriteParameters

Modules/Core/SpatialObjects/include/itkMetaBlobConverter.hxx, Modules/Core/SpatialObjects/include/itkMetaContourConverter.hxx, Modules/Core/SpatialObjects/include/itkMetaDTITubeConverter.hxx, Modules/Core/SpatialObjects/include/itkMetaLandmarkConverter.hxx, Modules/Core/SpatialObjects/include/itkMetaLineConverter.hxx, Modules/Core/SpatialObjects/include/itkMetaMeshConverter.hxx, Modules/Core/SpatialObjects/include/itkMetaSurfaceConverter.hxx, Modules/Core/SpatialObjects/include/itkMetaTubeConverter.hxx, Modules/Core/SpatialObjects/include/itkMetaVesselTubeConverter.hxx
MetaIO allowed points to be written in scaled space - where that
space was related to physical space via ElementSpacing scale vector.
That pseudo-index space didn't preserve orientation or origin,
so it is of limited use.
With ITKv5, SpatialObjects no longer maintain a notion of index space.
Points exist in "object" space or "World" space.  Points are written
in object space.  So, the flawed/limited notation of ElementSpacing of
MetaIO should be considered on reading, but not used on writing.
This fixes reading (conversion) of MetaIO objects to spatialobjects to preserve
ElementSpacing on read and keep it as a unit scalar on write.
=> Spatial object meta io spacing

Modules/Core/Common/include/itkBackwardDifferenceOperator.h, Modules/Core/Common/test/itkNeighborhoodOperatorTest.cxx
This commit allows copying `BackwardDifferenceOperator` objects, and
also adds fast, non-throwing move-semantics. It follows the C++ "Rule
of Zero".
This is a spin-off from pull request #1417 "STYLE: C++ Rule of Zero for
Neighborhood Operators, support nothrow move", commit 85d476455d208d4bd98f573412da0915cab9c1d2
`BackwardDifferenceOperator` was missing from PR #1417, because it
disallowed copying, unlike the other neighborhood operators. Dženan
@dzenanz suggested fixing this particular neighborhood operator in a
separate pull request.
=> ENH: Allow copy and noexcept move of BackwardDifferenceOperator objects

Modules/Core/Common/include/itkLeafTreeIterator.h
=> BUG: avoid undefined behavior (dereferencing nullptr). Closes #1358

Modules/Core/Common/include/itkBackwardDifferenceOperator.hxx, Modules/Core/Common/include/itkForwardDifferenceOperator.hxx, Modules/Core/Common/include/itkMultiThreaderBase.h, Modules/Core/Common/include/itkPlatformMultiThreader.h, Modules/Core/Common/src/itkMultiThreaderBase.cxx, Modules/Core/Common/src/itkPlatformMultiThreader.cxx
=> Fixing a few of Visual Studio static analysis warnings

Modules/Core/Common/include/itkConnectedImageNeighborhoodShape.h, Modules/Core/Common/include/itkMath.h, Modules/Core/Common/test/itkMathTest.cxx, Modules/Filtering/LabelMap/include/itkShapeLabelObject.h
Added `constexpr` functions `UnsignedPower(base, exponent)` and
`UnsignedProduct(a, b)` to the `itk::Math` namespace.
Especially `UnsignedPower` appears interesting, as it allows estimating
the number of voxels of an N-dimensional hypercube at compile-time
without conversions between `unsigned` and floating point.
`UnsignedProduct` is a helper function of `UnsignedPower`, but it is also
being used in `itk::Experimental::ConnectedImageNeighborhoodShape`, with
this commit.
Allowed specifying the return type by a template argument, as requested
by Bradley @blowekamp
Replaced `ShapeLabelObject::IntegerPow` by a call to `UnsignedPower`, as
suggested by Bradley @blowekamp
=> ENH: Add UnsignedPower(base, exp) and UnsignedProduct(a, b) to itk::Math

Modules/Filtering/DistanceMap/include/itkSignedMaurerDistanceMapImageFilter.hxx
Use unique_ptr to automatically delete allocated resource when an
abort exception occurs.
Addresses Valgrind defects detected on the SimpleITK dashboard.
=> BUG: Fix leaky dynamically allocated raw point

Modules/IO/ImageBase/include/itkImageSeriesReader.hxx, Modules/IO/ImageBase/test/itkImageSeriesReaderSamplingTest.cxx
ENH: aded metadata tag for maximum deviation from expected slice spacing in ImageSeriesReader.
@seanm
=> ENH: added metadata flag to contain maximum deviation in series reader

Modules/Core/Common/include/itkImageIORegion.h, Modules/Core/Common/src/itkImageIORegion.cxx, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkImageIORegionGTest.cxx
Added fast, noexcept move-semantics, by a defaulted move-constructor and
a defaulted move-assignment operator. Also defaulted the existing
default-constructor and copy-constructor.
Adjusted the converting constructor, `ImageIORegion(unsigned int)` to
initialize the member data by a member-initializer-list.
Let assignments return `*this` (instead of `void`), which is the
"standard" return value of an assignment. Made the assignment
exception safe.
Added GoogleTest unit tests, with help from includecpp.org members.
=> STYLE: Improve ImageIORegion special member functions, move-semantics

Modules/Remote/RTK.remote.cmake
RTK has been regularly updated to account for ITK changes (master branch). I just released a new RTK version for inclusion in ITK v5.1rc01 (if it's still time).
=> ENH: use RTK v2.1.0 (remote module)

Modules/Core/Common/include/itkMath.h
RogueResearch13/Mac10.10-AppleClang-dbg-x86_64-static produced the
following warning, as reported by Dženan @dzenanz at pull request #1445:
> [CTest: warning matched] Modules/Core/Common/include/itkMath.h:802:1:
> warning: inline function `itk::Math::UnsignedPower<unsigned long>`
> is not defined [-Wundefined-inline]
It appears to be an old Clang 3.8.1 compiler issue. This commit aims to
work around the issue by passing `TReturnType` as template argument to
both of the recursive `UnsignedPower` function calls, inside the body
of `UnsignedPower`.
=> COMP: Workaround Clang 3.8 -Wundefined-inline warning Math UnsignedPower

Documentation/SupportedCompilers.md, Modules/Core/Common/test/itkImageIORegionGTest.cxx
Just removed a 'const' as suggested by Niels Dekker.
Also added a note to the supported compilers list about AppleClang.
=> COMP: fixed compilation with AppleClang 7 and 8.

Wrapping/Generators/Python/PyBase/pyBase.i
Experimentation through use has found that the use of a view
for np.asarray can result in unexpected behavior or crashes.
=> BUG: Use itk.array_from_image for __array__

Modules/Bridge/NumPy/wrapping/PyBuffer.i.in, Modules/Bridge/NumPy/wrapping/test/itkPyBufferTest.py
Instead of raising an exception when converting a NumPy array to an
itk.Image, just make the array contiguous with numpy.ascontiguousarray.
This improves ease of use, and internal conversion is a better default
behavior.
Closes #1243
=> ENH: Gracefully convert non-contiguous NumPy arrays

Wrapping/Generators/SwigInterface/CMakeLists.txt
SWIG 4.0.1 crashes when wrapping
AdaptiveHistogramEqualizationImageFilter on macOS or Linux:
$ cd /Users/kitware/Dashboards/ITK/ITKPythonPackage/ITK-3.5-macosx_x86_64/Wrapping/Typedefs/python && /Users/kitware/Dashboards/ITK/ITKPythonPackage/ITK-3.5-macosx_x86_64/Wrapping/Generators/SwigInterface/swig/bin/swig -c++ -python -O -features autodoc=1 -py3 -Werror -w302 -w303 -w312 -w314 -w361 -w362 -w350 -w383
-w384 -w389 -w394 -w395 -w467 -w508 -w509 -o /Users/kitware/Dashboards/ITK/ITKPythonPackage/ITK-3.5-macosx_x86_64/Wrapping/Modules/ITKImageStatistics/itkAdaptiveHistogramEqualizationImageFilterPython.cpp -I/Users/kitware/Dashboards/ITK/ITKPythonPackage/ITK-3.5-macosx_x86_64/Wrapping/Generators/SwigInterface/swig/share/swig/4.0.1/python …
=> COMP: Use SWIG 3.0.12 on Unix

Modules/Filtering/DistanceMap/include/itkSignedMaurerDistanceMapImageFilter.hxx
Addresses Valgrind defects:
https://open.cdash.org/viewDynamicAnalysis.php?buildid=6245494
=> BUG: Use unique_ptr::reset() to delete held pointer

Modules/IO/ImageBase/include/itkImageSeriesReader.hxx, Modules/IO/ImageBase/test/itkImageSeriesReaderSamplingTest.cxx
ENH: Now ImageSeriesReader reports only maximum deviance from expected slice thinckness for the whole volume and also per-slice information in the metadata entry ITK_non_uniform_sampling_deviation. 
=> ENH: Simplification of the ImageSeriesReader nonuniform sampling detection

Modules/Core/Common/include/itkImageIORegion.h
=> COMP: Remove unused region parameter in default copy constructor

Modules/Core/Common/include/itkInOrderTreeIterator.h
/Users/builder/external/ITK/Modules/Core/Common/include/itkInOrderTreeIterator.h:102:28: runtime error: member call on null pointer of type 'itk::TreeNode<int>'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/builder/external/ITK/Modules/Core/Common/include/itkInOrderTreeIterator.h:102:28
=> BUG: fix null pointer dereference in itkInOrderTreeIterator.h:102

Modules/Filtering/Smoothing/include/itkDiscreteGaussianImageFilter.h, Modules/Filtering/Smoothing/include/itkDiscreteGaussianImageFilter.hxx, Modules/Filtering/Smoothing/test/itkDiscreteGaussianImageFilterTest.cxx
Add boundary condition setters and getters to DiscreteGaussianImageFilter.
We are currently trying to implement a new projector in RTK, and we need to use the DiscreteGaussianImageFilter with another boundary condition than the default one. 
The difficulty here is that the DiscreteGaussianImageFilter uses intermediate filter with real pixel type. In this PR, I implemented one setter and getter for boundary condition with input pixel type and another one for boundary condition with real pixel type. However, I'm not sure it's the best way to do since the user would have to set boundary condition with two different image type. 
Can you think of a better solution?
=> ENH: Add boundary condition getters and setters

Modules/Remote/Cuberille.remote.cmake
A [patch](https://github.com/InsightSoftwareConsortium/ITKCuberille/pull/46) was recently applied to the remote Cuberille module preventing the mesh from being shifted relative to the underlying image data when the direction matrix is non-identity.  This commit updates to the most recent Cuberille git commit hash, making this patch available by default when installed as a remote module in ITK.
- :no_entry_sign: [Adds test …
=> BUG: Bump Cuberille Git Hash

Modules/Remote/SCIFIO.remote.cmake
Matt McCormick (6):
ENH: Update bundled JRE to Java 11
ENH: Bump bio-formats version to 6.3.0
ENH: Add Azure Pipelines configuration
DOC: Add Azure Pipeline CI badge to README
COMP: Avoid getenv with Visual Studio
BUG: Remove Python packages from the testing configuration
=> ENH: Update SCIFIO remote module to 2019-12-11 Git master

.github/stale.yml
Do not suggest that the issue will be closed.
`closeComment` is already set to `false`, which suggests that the issue
should not be closed. But, also set `daysUntilClose` to avoid closure.
=> ENH: Update stale-bot comment about issue closure

Utilities/GitSetup/config
The GitSetup repo on `public.kitware.com` will be removed.  Use our own repo's hooks branch.
=> BUG: Update URL for GitSetup hooks checkout

Modules/IO/ImageBase/include/itkImageSeriesReader.hxx
BUG: Replaced std::defaultfloat with std::resetiosflags to fix issue #1498 on old gcc compilers.
=> BUG: fixes issue# 1498

.circleci/config.yml
The cache store is different for forked repositories and the upstream
repository. Therefore the forks don't build the master branch. The
cache now falls back to a branch-less name so PR will fetch the
previous PR's ccache.
=> ENH: Enable CircleCI to retrieve ccache on pull requests

Documentation/Maintenance/Release.md, Utilities/Maintenance/SourceTarball.bash
Ease use inside Git Bash on Windows.
Also remove Slicer Midas3 server, which is no longer used.
=> ENH: Use curl instead of wget in SourceTarball script

.mailmap
Use consistent names in release notes, etc. by setting .mailmap entries.
See *MAPPING AUTHORS* in `git help shortlog`.
=> DOC: Update .mailmap to consolidate author identification

Modules/Filtering/QuadEdgeMeshFiltering/include/itkDelaunayConformingQuadEdgeMeshFilter.h, Modules/Filtering/QuadEdgeMeshFiltering/include/itkDelaunayConformingQuadEdgeMeshFilter.hxx, Modules/Filtering/QuadEdgeMeshFiltering/test/itkDelaunayConformingQuadEdgeMeshFilterTest.cxx
The DelaunayConformingQuadEdgeMeshFilter currently results in a
decoupling of the cell faces from their corresponding cell data.
This patch attempts to address this by re-assigning cell data
on either side of an edge to the new cell indices following the
edge flip.  In testing, this results in a dramatic improvement
in consistency.  Unfortunately, occasional inconsistencies are
still apparent.
- :no_entry_sign: [Adds test …
=> BUG: Delaunay Cell Data

Documentation/Doxygen/DoxygenHeader.html
To help browsers identify the correct language the page was written in
and prevent requests to translate.
=> DOC: Set lang attribute for Doxygen docs

.mailmap
Use consistent names in release notes, etc. by setting .mailmap entries.
See MAPPING AUTHORS in git help shortlog.
`git shortlog` now outputs the single "Stephen R. Aylward" versus a mix of "Stephen R.
Aylward" and "Stephen Aylward".
Will the real @aylward please stand up? :-)
=> DOC: Add Stephen R. Aylward to .mailmap

.mailmap
Use consistent names in release notes, etc. by setting .mailmap entries.
See MAPPING AUTHORS in git help shortlog.
`git shortlog` now outputs the single "Hans J. Johnson" versus a mix of "Hans J. Johnson" and "Hans Johnson".
Will the real @hjmjohnson  please stand up? :-)
=> DOC: .mailmap entry for Hans J. Johnson

Modules/IO/Meta/src/itkMetaImageIO.cxx
MetaDataDictionary now routinely includes itkMatrix and std::vector
data items.  These changes add support to MetaIO for those types when
parsing non-standard MetaDataDictionary fields.
=> BUG: itkMetaImageIO.cxx supports more MetaDataDictionary field types

Modules/Core/SpatialObjects/include/itkSpatialObjectToImageFilter.h
Added SetMatchImage( img ) function.   The size, spacing, directions,
etc of the image passed to this function are used to define the
output image format of the filter.
=> ENH: Adding function to SOToImageFilter simplify output definition

Modules/Core/Mesh/include/itkMesh.h, Modules/Core/Mesh/include/itkMesh.hxx, Modules/Core/Mesh/test/CMakeLists.txt, Modules/Core/Mesh/test/itkMeshCellDataTest.cxx, Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshZipMeshFunction.hxx, Modules/Filtering/QuadEdgeMeshFiltering/include/itkDecimationQuadEdgeMeshFilter.h, Modules/Filtering/QuadEdgeMeshFiltering/test/itkSquaredEdgeLengthDecimationQuadEdgeMeshFilterTest.cxx
Currently, cell data is not properly handled in the
itk::SquaredEdgeLengthDecimation filter.  This patch adds entries to
the cell data array as faces are added in the Zip filter, and then
deletes unreferenced entries in a new member function added to
itk::Mesh.
=> BUG: Handle CellData in Decimation Filter

.github/workflows/apply-clang-format.yml, .github/workflows/clang-format-linter.yml, CONTRIBUTING.md, Utilities/Maintenance/clang-format.bash
Add GitHub Actions to:
- Provide a status check that checks that the current pull request conforms to ITK's Coding Style with clang-format.
- Apply `clang-format` to a PR when the *action:ApplyClangFormat* label is added. This will run `clang-format` on all commits on the branch and force-push the branch, then remove the label. This label should be applied by someone with write access to the PR, i.e. the author or repository maintainers.
While the local Git hook catches most style changes, this provides an additional check and a convenient way to apply style updates on demand.
Moreover, these GitHub Actions can easily be applied to other repositories on GitHub.
Closes #1201
=> clang-format lint and apply GitHub Actions

Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentImageFilter.h, Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentImageFilter.hxx
=> Connected components restore zero background

CMake/ITKModuleDoxygen.cmake, CMake/ITKModuleHeaderTest.cmake, CMake/ITKModuleTest.cmake, CMakeLists.txt, Documentation/Maintenance/Release.md, Modules/Bridge/NumPy/wrapping/test/CMakeLists.txt, Modules/Core/Common/wrapping/test/CMakeLists.txt, Modules/Filtering/ImageIntensity/wrapping/test/CMakeLists.txt, Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml, Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml, Wrapping/Generators/Doc/CMakeLists.txt, Wrapping/Generators/Perl/ConfigureWrapping.cmake, Wrapping/Generators/Python/CMakeLists.txt, Wrapping/Generators/Python/Tests/pythonTestDriver.py.in, Wrapping/Generators/SwigInterface/CMakeLists.txt
The FindPython3 module is more robust for ensuring that python 3 or greater is found.
The FindPythonInterp and FindPythonLib modules are deprecated
in cmake greater than 3.12.0
The GoogleTest framework uses the deprecated FindPythonInterp, so this
the patch uses the FindPython3 module, and then uses that more robust
information to set the FindPythonInterp cmake variables so that
wrapping, google tests, documentation generation, etc.. all use the
same found a version of Python 3.
=> ENH: When using cmake > 3.12 use FindPython3 module

Modules/Core/Transform/include/itkScaleSkewVersor3DTransform.h, Modules/Core/Transform/include/itkScaleSkewVersor3DTransform.hxx, Modules/Core/Transform/test/itkScaleSkewVersor3DTransformTest.cxx
Reverts InsightSoftwareConsortium/ITK#1523, to preserve existing transform files the transform numerics and number of parameters must not change.
=> Revert "BUG: SetScale() and SetSkew() did not recompute offset: ScaleSkewVersorT"

README.md
Adds a DOI to the code for software citation. The badge points to the DOI for the latest release. According to Zenodo docs, this is updated automatically on every new GitHub release.
=> DOC: Add Zenodo DOI badge

Modules/Core/GPUCommon/include/itkGPUReduction.hxx, Modules/Core/GPUFiniteDifference/include/itkGPUDenseFiniteDifferenceImageFilter.hxx, Modules/Filtering/GPUAnisotropicSmoothing/include/itkGPUGradientNDAnisotropicDiffusionFunction.hxx, Modules/Filtering/GPUAnisotropicSmoothing/include/itkGPUScalarAnisotropicDiffusionFunction.hxx, Modules/Filtering/GPUImageFilterBase/include/itkGPUNeighborhoodOperatorImageFilter.hxx, Modules/Filtering/GPUThresholding/include/itkGPUBinaryThresholdImageFilter.hxx, Modules/Registration/GPUPDEDeformable/include/itkGPUDemonsRegistrationFunction.hxx, Modules/Registration/GPUPDEDeformable/include/itkGPUPDEDeformableRegistrationFilter.hxx
=> BUG: Remove debug console prints from GPU kernels

CONTRIBUTING.md
As of 2020-01-08, this action [currently does not work from forked
repositories](https://github.community/t5/GitHub-Actions/Token-permissions-for-forks-once-again/td-p/33839)
because the [*GITHUB_TOKEN* has limited
permissions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#permissions-for-the-github_token). Branches need to be created on the upstream repository.
=> DOC: Remove CONTRIBUTING note about ApplyClangFormat action

Modules/Remote/RTK.remote.cmake
It would be great to update RTK once again. Among other changes, note the fix SimonRit/RTK@8d213dfd5ddc81fadad313a4991985a1eaab9413 for the backward incompatible change on the ITK side which was less than one day before the release of v5.1rc01. Unfortunately, ITK v5.1rc01 does not compile with Module_RTK ON... If it makes it to v5.1rc02, I'll check that it compiles and then release RTK v2.2.0. Let me know if you prefer that I proceed differently (e.g. release RTK first, as I did for v2.1.0). Thanks for this and for the publicity in the release notes of v5.1rc01!
=> ENH: latest version of remote module RTK

Modules/Core/Transform/include/itkComposeScaleSkewVersor3DTransform.h, Modules/Core/Transform/include/itkComposeScaleSkewVersor3DTransform.hxx, Modules/Core/Transform/test/CMakeLists.txt, Modules/Core/Transform/test/itkComposeScaleSkewVersor3DTransformTest.cxx, Modules/Core/Transform/test/itkScaleSkewVersor3DTransformTest.cxx, Modules/Core/Transform/wrapping/itkComposeScaleSkewVersor3DTransform.wrap
This transform uses matrix compose to combine matrix defined by
versor, scale, and skew parameters.  Implementing the
jacobian of this transform is left as an exercise for future
developers.
=> ENH: Adding ComposeScaleSkewVersor 3D Transform

Wrapping/Generators/Python/CMakeLists.txt
This is an attempt to fix the failing Windows Python CI builds:
https://dev.azure.com/itkrobotwindowpython/ITK.Windows.Python/_build?definitionId=1&_a=summary
=> COMP: PYTHON_LIBRARY is missing for Windows configuration

Modules/Filtering/ImageGrid/include/itkCropImageFilter.h, Modules/Filtering/ImageGrid/include/itkCropImageFilter.hxx
Check that the crop size is not greater that the image size to prevent
integer underflow.
=> BUG: Prevent integer underflow in CropImageFilter

Modules/Segmentation/LabelVoting/include/itkMultiLabelSTAPLEImageFilter.hxx, Modules/Segmentation/LabelVoting/test/itkMultiLabelSTAPLEImageFilterTest.cxx
The user requested label for undecided values was ignored and the
maxLabel+1 was always used. The test also had a bug in its ground
truth values.
=> BUG: SetLabelForUndecidedPixels value ignored.

Modules/Filtering/Smoothing/include/itkMeanImageFilter.h, Modules/Filtering/Smoothing/include/itkMeanImageFilter.hxx, Modules/Filtering/Smoothing/test/itkMeanImageFilterGTest.cxx, Modules/Filtering/Smoothing/test/itkMeanImageFilterTest.cxx
closes #1377 
Add support to MeanImageFilter to support the VectorImage with it's run time variable number of components.
=> ENH: Add VectorImageSupport to MeanImageFilter

Modules/Core/Common/include/itkQuadrilateralCell.h, Modules/Core/Common/include/itkTriangleCell.h, Modules/Core/Transform/include/itkTransform.h, Modules/Core/Transform/include/itkTransformBase.h
`#ifdef` were apparently introduced to fix a bug in gcc 5.4.0 (according to the comment in itkTransformBase.h). However this is done testing `__GNUC__` macro, which can be wrong when using Clang. Clang typically defines it to 4. When ITK is compiled with gcc and then a software using ITK is compiled with clang, this leads to linking errors, such as :
```
/home/fbridault/dev/sight/src/sight/SrcLib/core/fwTools/include/fwTools/Dispatcher.hpp:201:24: note: in instantiation of function template specialization 'fwTools::Dispatcher<boost::mpl::v_mask<boost::mpl::v_mask<boost::mpl::v_mask<boost::mpl::v_mask<boost::mpl::v_mask<boost::mpl::v_mask<boost::mpl::v_mask<boost::mpl::v_mask<boost::mpl::v_item<double, boost::mpl::v_item<float, boost::mpl::vector8<signed char, unsigned char, short, …
```
=> COMP: Remove gcc #ifdef around usage of `= default`

CMakeLists.txt, Modules/IO/ImageBase/include/itkIOTestHelper.h, Modules/IO/NIFTI/include/itkNiftiImageIO.h, Modules/IO/NIFTI/src/CMakeLists.txt, Modules/IO/NIFTI/src/itkNiftiImageIO.cxx, Modules/IO/NIFTI/src/itkNiftiImageIOConfigurePrivate.h.in, Modules/IO/NIFTI/test/itkNiftiImageIOTest.cxx, Modules/IO/NIFTI/test/itkNiftiImageIOTestHelper.cxx, Modules/IO/NIFTI/test/itkNiftiReadAnalyzeTest.cxx, Modules/IO/NIFTI/wrapping/itkNiftiImageIO.wrap
Changed ITK NIFTI Reader, according to the discussion from https://discourse.itk.org/t/nifti-file-orientation-change-between-2019-08-26-and-itk-v5-1rc01/2594 .
New behaviour is to reject Analyze files, unless one of the flavours is specified:
Reject Analyze files (default) to avoid confusion:
`imageIO->SetLegacyAnalyze75Mode(itk::NiftiImageIO::AnalyzeReject);`
Use NIFTI reader behaviour introduced in ITK v4 (ignore orientation code, flip dimensions if step size is negative):
`imageIO->SetLegacyAnalyze75Mode(itk::NiftiImageIO::AnalyzeITK4);`
Simulate SPM reader, mode similar to depricated Analyze reader from ITK3 (interpret orientation code, flip dimensions if step size is negative):
`imageIO->SetLegacyAnalyze75Mode(itk::NiftiImageIO::AnalyzeSPM);`
Simulate FSL reader (respect orientation …
=> ENH: Changed NIFTI IO to support different flavors of Analyze readers

Modules/Segmentation/ConnectedComponents/include/itkRelabelComponentImageFilter.h, Modules/Segmentation/ConnectedComponents/include/itkRelabelComponentImageFilter.hxx, Modules/Segmentation/ConnectedComponents/test/itkRelabelComponentImageFilterGTest.cxx
Parallelized applying the output production step. Modernizes the use
of STL data structures and loops. Stream-lined cases. Save iterators
used for searching to exploit coherence in images.
=> PERF: Refactor RelabelComponentImageFilter

Testing/ContinuousIntegration/AzurePipelinesMacOS.yml, Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
Azure Pipelines is discontinuing support for the 10.13 images.
=> ENH: Bump macOS Azure CI images to 10.14

Wrapping/Generators/Python/CMakeLists.txt
With the Python3 CMake module, this can expand to what CMake interprets
to be multiple arguments, causing get_filename_component to fail.
=> COMP: Quote Python3_LIBRARY argument

Modules/Segmentation/ConnectedComponents/include/itkRelabelComponentImageFilter.hxx
Fixes error introduced in 234bbf38430595c49cbb195adaab6874e8d385b2 , causing compiler error: 
```
In file included from /Users/builder/externalModules/Segmentation/ConnectedComponents/include/itkRelabelComponentImageFilter.h:301:
/Users/builder/externalModules/Segmentation/ConnectedComponents/include/itkRelabelComponentImageFilter.hxx:243:33: error: no member named 'cend' in 'std::__1::__map_const_iterator<std::__1::__tree_const_iterator<std::__1::__value_type<unsigned int, unsigned int>, std::__1::__tree_node<std::__1::__value_type<unsigned int, unsigned int>, void *> *, long> >'
assert(mapIt != mapIt.cend());
```
as can be seen in https://open.cdash.org/viewBuildError.php?buildid=6324914
further development …
=> COMP: Fixes error "error: no member named 'cend' in 'std::__1::__map_const..."

Modules/Core/SpatialObjects/include/itkCastSpatialObjectFilter.h
We can rebase #1582 #1583 after merging to re-check the CI.
=> Input spatial object const

Modules/Filtering/ImageCompose/wrapping/itkComposeImageFilter.wrap
This allows for combining real and imaginary images into complex images. 
Closes #1581 …
=> ENH: Wrap ComposeImageFilter for complex types

Wrapping/Generators/Python/PyBase/pyBase.i
For functional Python ProcessObject or Filter calls, call itk.down_cast
on outputs to return the most derived type.
=> BUG: Call itk.down_cast on ProcessObject outputs in functional call

Modules/Filtering/ImageLabel/include/itkScanlineFilterCommon.h, Modules/Segmentation/ConnectedComponents/test/CMakeLists.txt, Modules/Segmentation/ConnectedComponents/test/itkConnectedComponentImageFilterGTest.cxx
Thanks to @DVigneault for finding the bug and creating a MWE for demonstrating it. Forum [thread](https://discourse.itk.org/t/incorrect-result-from-itk-connectedcomponentimagefilter/2676).
=> BUG: incorrect neighbor determination in scan-line derived filters

Modules/Video/BridgeOpenCV/include/itkOpenCVVideoCapture.hxx, Modules/Video/BridgeOpenCV/test/CMakeLists.txt, Modules/Video/BridgeOpenCV/test/itkOpenCVImageBridgeGrayScaleTest.cxx, Modules/Video/BridgeOpenCV/test/itkOpenCVImageBridgeRGBTest.cxx, Modules/Video/BridgeOpenCV/test/itkOpenCVTestHelper.cxx, Modules/Video/BridgeOpenCV/test/itkOpenCVTestHelper.h
=> COMP: Fix unit tests for OpenCV 4

Modules/Bridge/VtkGlue/include/vtkCaptureScreen.h
The member variable is changed, so the operator() can not be const.
Bug identified with clang10 compilation
=> BUG: operator() can not be const

Modules/Filtering/ImageLabel/include/itkScanlineFilterCommon.h
We are not checking difference along dimension zero,
so it is possible for diffSum to be 0 despite neighbors being different.
This is a follow-up to #1589.
=> BUG: remove assertion which frequently fails

Modules/Core/Mesh/test/itkMeshCellDataTest.cxx, Modules/Segmentation/ConnectedComponents/test/itkRelabelComponentImageFilterGTest.cxx
=> COMP: Fix suggested brace around initialization warnings

Modules/Segmentation/ConnectedComponents/include/itkRelabelComponentImageFilter.hxx
Compiling with clang++-11 compiler identified ambiguous
types for min function.
=> COMP: Need to explicitly define std::min<> template values

Modules/Remote/RTK.remote.cmake
Using explicit typecasts for future-proofing
enums.  RTK treats enum values as integers and
enumerations interchangeably for pushing onto
a stack of integers.  Using explicit static_casts
makes code future proof when enum class is used.
=> ENH: Update RTK for future proofing.

Modules/Filtering/LabelMap/include/itkBinaryNotImageFilter.h
=> BUG: set BinaryNot operator to const method

Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml
These test fail inconsistently on CI without an informative traceback.
Exclude to avoid false positives in CI development.
=> COMP: Exclude inconsistently failing Linux Python CI tests

Modules/ThirdParty/VNL/src/vxl/core/vnl/algo/tests/test_sparse_lm.cxx, Modules/ThirdParty/VNL/src/vxl/core/vnl/algo/tests/test_symmetric_eigensystem.cxx, Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_diag_matrix.h, Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_real_polynomial.cxx
Avoid new compiler warnings:
```
ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_diag_matrix.h:148:5: warning: misleading indentation; statement is not part of the previous 'if' [-Wmisleading-indentation]
```
Adding appropriate {} and indentation fixes.
=> Update vxl 20200214

Modules/Core/Common/include/itkColorTable.hxx, Modules/Filtering/ImageIntensity/test/itkClampImageFilterTest.cxx
Core/Common/include/itkColorTable.hxx:182:17:
Core/Common/include/itkColorTable.hxx:198:19:
Core/Common/include/itkColorTable.hxx:91:17:
Filtering/ImageIntensity/test/itkClampImageFilterTest.cxx:111:26:
Core/Common/include/itkColorTable.hxx:139:20: warning: implicit conversion from
'itk::NumericTraits<long long>::ValueType' (aka 'long long') to 'double'
changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-int-float-conversion]
=> COMP: Implicit conversion warnings

Modules/Compatibility/Deprecated/include/itkChildTreeIterator.hxx, Modules/Compatibility/Deprecated/include/itkInOrderTreeIterator.h, Modules/Compatibility/Deprecated/include/itkLeafTreeIterator.h, Modules/Compatibility/Deprecated/include/itkLevelOrderTreeIterator.hxx, Modules/Compatibility/Deprecated/include/itkPostOrderTreeIterator.h, Modules/Compatibility/Deprecated/include/itkPreOrderTreeIterator.h, Modules/Compatibility/Deprecated/include/itkRootTreeIterator.h, Modules/Compatibility/Deprecated/test/itkTreeContainerTest.cxx, Modules/Core/Common/include/itkCellInterface.h, Modules/Core/Common/include/itkCommonEnums.h, Modules/Filtering/Colormap/include/itkScalarToRGBColormapImageFilter.h, Modules/Video/BridgeOpenCV/include/itkOpenCVImageBridge.h
Building deprecated code and remote modules identified a few missing backward compatibility issues.
Backward compatible enumerations for Remote Modules
Build the remote modules identified missing backward compatible
names that were missing.
Incomplete refactoring for deprecated enumeration.
Incorrect type change from enumeration update
=> BUG: Missing backward compatible enumeration name

.mailmap
Use consistent names in release notes, etc. by setting
.mailmap entries.
See MAPPING AUTHORS in git help shortlog.
`git shortlog` now outputs the single "Nick Tustison"
versus a mix of "Nick Tustison" and "Nicholas Tustison", the name
associated with the wustl.edu email.
=> DOC: .mailmap entry for ntustison@wustl.edu

Wrapping/Generators/Python/Tests/extras.py, Wrapping/Generators/Python/itkExtras.py
These functions convert an itk.Image to and from an xarray.DataArray. The
xarray.DataArray preserves spatial metadata while processing in Python.
xarray enables parallel computing with Dask, machine learning, and
modern seralization with Zarr.
These interfaces are complete but experimental. They are available for
testing but are subject to possible future changes and refinements.
=> ENH: Add itk.xarray_from_image and itk.image_from_xarray

.zenodo.json
Also removing duplicate entries. ORCIDs taken from https://github.com/InsightSoftwareConsortium/ITK/pull/1597#issuecomment-586381631.
=> DOC: updating zenodo authors' ORCIDs and affiliations

Modules/Core/Mesh/wrapping/itkMeshBase.wrap
Following strongly typed enums refactoring, this is now wrapped in
ITKCommon.
To address #1636
=> BUG: Remove duplicate wrapping of itk.MeshEnums

Modules/Segmentation/ConnectedComponents/test/itkRelabelComponentImageFilterGTest.cxx
To address the dashboard warning:
Standard Error
[CTest: warning matched] /Users/builder/externalModules/Segmentation/ConnectedComponents/test/itkRelabelComponentImageFilterGTest.cxx:141:54: warning: suggest braces around initialization of subobject [-Wmissing-braces]
image->SetRegions(typename ImageType::RegionType({ 512, 512, 512 }));
^~~~~~~~~~~~~
{            }
[CTest: warning suppressed] 1 warning generated.
=> COMP: Add missing brackets to RelabelComponentsImageFilterGTest

CMake/itkExternal_Eigen3.cmake
On Windows, with the Ninja Generator and a non-default Visual Studio
toolset, the Eigen External Project will fail to build, attempting to
use MSBuild, without the generator specified.
=> BUG: Specify CMAKE_GENERATOR for Eigen external project build

CMake/itkExternal_Eigen3.cmake
Explicitly pass `CMAKE_C_COMPILER` `CMAKE_CXX_COMPILER` and
extra `CMAKE_GENERATOR_` variables to the internal Eigen configuration.
Raised here: https://github.com/InsightSoftwareConsortium/ITK/issues/66
=> BUG: Pass CMAKE_<lang>_COMPILER to Eigen configuration

Modules/Remote/TotalVariation.remote.cmake
`git shortlog --no-merges fbab38..e47fb5`
```
Hans Johnson (3):
STYLE: Remove CMake-language block-end command arguments
ENH: Add .gitattributes to allow running ITK clang-formatting scripts
DOC: Update copyright assignment to NumFOCUS
Jean-Christophe Fillion-Robin (1):
COMP: Ensure proxTV dependencies are found when building against ITK build tree
Pablo Hernandez-Cerdan (5):
BUG: Use ITKInternalEigen3_DIR to find Eigen
Revert "COMP: Ensure proxTV dependencies are found when building against ITK build tree"
COMP: CMake: Install proxTV in ITK standard folders
DOC: Remove TODOs in Readme
DOC: Update readme, remove duplicated license
```
=> COMP: Update remote module: TotalVariation

Modules/Core/Common/include/itkSmapsFileParser.hxx
Core/Common/include/itkSmapsFileParser.hxx:187:34:
warning: unused exception parameter 'excp' [-Wunused-exception-parameter]
catch (const ExceptionObject & excp)
=> COMP: Named exception not passed along to next exception

Modules/IO/ImageBase/include/itkImageSeriesReader.h, Modules/IO/ImageBase/include/itkImageSeriesReader.hxx
BUG: Related to #1607, now only one warning per series is emitted, when maximum 
slice sampling error is greater then 1e-6
=> BUG: reduced number of warnings for non-uniform sampling

Modules/Core/Common/include/itkSmapsFileParser.hxx
To address:
[CTest: warning matched] /Users/builder/externalModules/Core/Common/include/itkSmapsFileParser.hxx:128:34: warning: unused exception parameter 'excp' [-Wunused-exception-parameter]
catch (const ExceptionObject & excp)
^
=> COMP: Unused exception object in SmapsFileParser::ReadFile

Modules/Registration/GPUPDEDeformable/include/itkGPUPDEDeformableRegistrationFilter.hxx
`C:\Dev\ITK-git\Modules\Registration\GPUPDEDeformable\include\itkGPUPDEDeformableRegistrationFilter.hxx(336,1): error C2440: 'initializing': cannot convert from 'size_t' to 'unsigned long &'`
=> COMP: fix type conversion error in GPUPDEDeformableRegistrationFilter

CMake/itkImageIOFactoryRegisterManager.h.in, CMake/itkMeshIOFactoryRegisterManager.h.in, CMake/itkTransformIOFactoryRegisterManager.h.in
Three "IOFactoryRegisterManager.h.in" files each declared an array of function
pointers, "IOFactoryRegisterRegisterList", which was terminated by `0`. This
triggered a Visual C++ (VS2017) Code Analysis warning:
> warning C26477: Use 'nullptr' rather than 0 or NULL (es.47).
Fixed by replacing `0` by `nullptr`.
=> COMP: Use nullptr rather than 0 in IOFactoryRegisterRegisterList (3x)

Modules/Core/GPUCommon/include/itkGPUImageOps.h
GPUImageOps wrapping requires public constructor
and destructor default implementations.  They can
not be private or deleted.
=> BUG: Wrapping the GPUImageOps in python

Documentation/Maintenance/Release.md
Bugs in the FindPython3 module prevent successful Python package builds.
=> DOC: Windows Python package builds now require CMake 3.16

Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/src/Geometry/AlignedBox.h, Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/src/Geometry/AngleAxis.h, Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/src/Geometry/ParametrizedLine.h, Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/src/Geometry/Quaternion.h, Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/src/Geometry/Transform.h, Modules/ThirdParty/Eigen3/src/itkeigen/Eigen/src/Geometry/Translation.h
=> COMP: remove Eigen3 shadow warnings with GCC 4.8.5

Modules/Filtering/ImageStatistics/include/itkLabelStatisticsImageFilter.h
=> BUG: fix crash with multiple update in LabelStatisticsImageFilter

CMake/ITKModuleRemote.cmake, Modules/Remote/CMakeLists.txt
There were bugs in the previous implementation
of the module COMPLIANCE level filtering.  The
COMPLIANCE level filtering was confounded with
the module ON/OFF status.
=> BUG: Module COMPLIANCE level processing improved

Modules/ThirdParty/PNG/UpdateFromUpstream.sh
The change was accidental commit in
b644f1a3818c9dbbc9aa5751a311f01a109f4174.
=> BUG: restoring libPNG branch name for UpdateFromUpstream.sh

Modules/Remote/TubeTK.remote.cmake
Needed to fix paths in CMakeLists.txt files throughout TubeTK
to support its use as with a remote module that is built during
the compilation of ITK or that is built externally, after ITK has been built.
See [TubeTK#1161](https://github.com/KitwareMedical/ITKTubeTK/pull/1161)
=> ENH: Bump TubeTK to support internal and extern remote module

CMake/ITKModuleExternal.cmake, CMake/ITKSetPython3Vars.cmake, CMakeLists.txt
The code needed to find python3 packages has been consolidated
so that it may be reused for external modules.
This attempts to address the issues identified in #1700 by re-using a previous paradigm for the case of external module dependency on python.
@SimonRit This solution has not been tested with RTK
=> COMP: Conditional python3 package finding

CMake/ITKSetPython3Vars.cmake
The FindPython3 module has required half a dozen work arounds for broken
behavior and is still causing a failing Windows CI build.
=> DOC: Remove FindPython3 robust remark

Modules/Core/Common/test/itkTimeStampTest.cxx
Resolves #1711
ITK/Modules/Core/Common/test/itkTimeStampTest.cxx:27:35: warning:
anonymous non-C-compatible type given name for linkage purposes by alias
declaration; add a tag name here [-Wnon-c-typedef-for-linkage] using
TimeStampTestHelper = struct
^
TimeStampTestHelper
Due to a recent (but retroactive) C++ rule change, only sufficiently
C-compatible classes are permitted to be given a typedef name for
linkage purposes. Add an enabled-by-default warning for these cases, and
rephrase existing error for the case where we encounter the typedef
name for linkage after we've already computed and used a wrong linkage
in terms of the new rule.
=> COMP: non-C-compatible type given name for linkage

Modules/Core/Common/include/itkMacro.h, Modules/Numerics/Statistics/include/itkScalarImageToRunLengthMatrixFilter.hxx, Modules/Registration/Common/include/itkLandmarkBasedTransformInitializer.hxx
Update exception macros to use anonymous exceptions for clang.
=> Macro ignore extra semi colon and use anonymous exception passing

Modules/Core/Common/include/itkExceptionObject.h, Modules/Core/Common/include/itkMacro.h, Modules/Core/Common/include/itkSymmetricEigenAnalysis.h, Modules/Core/Common/src/itkExceptionObject.cxx, Modules/Video/IO/src/itkVideoIOFactory.cxx
https://stackoverflow.com/questions/53412425/throw-temporary-instead-of-local-variable-why
Fix warning about exception passing by named
values.  Make the derived exceptions have similar
interface to ExceptionObject.  Consolidate duplicated
code.  Prefer move semantics for constructors for
added efficiency.
=> ENH: Fix anonymous exception passing

Modules/ThirdParty/DCMTK/DCMTKGitTag.cmake
These are required to use the name-mangled ITK internal third party
libraries and add Emscripten support.
=> COMP: Add ITK patches for DCMTK

CMake/ITKSetStandardCompilerFlags.cmake
To address:
clang-6.0: warning: argument unused during compilation:
'-march=corei7' [-Wunused-command-line-argument]
with Emscripten toolchain 1.39.4
=> COMP: Do not add -mcorei7 with Emscripten

Modules/Core/Common/include/itkImageRegionConstIteratorWithIndex.hxx
This commit fixes the following warning 3D Slicer warning:
```
In file included from /path/to/Slicer-Release/ITK/Modules/Core/Common/include/itkImageRegionConstIteratorWithIndex.h:196:0,
from /path/to/Slicer-Release/ITK/Modules/Core/Common/include/itkImageRegionExclusionConstIteratorWithIndex.h:21,
from /path/to/Slicer-Release/ITK/Modules/Core/Common/include/itkImageRegionExclusionIteratorWithIndex.h:21,
from /path/to/Slicer-Release/ITK/Modules/Filtering/ImageGrid/include/itkPadImageFilterBase.hxx:24,
from /path/to/Slicer-Release/ITK/Modules/Filtering/ImageGrid/include/itkPadImageFilterBase.h:120,
from /path/to/Slicer-Release/ITK/Modules/Filtering/ImageGrid/include/itkPadImageFilter.h:21,
from /path/to/Slicer-Release/ITK/Modules/Filtering/ImageGrid/include/itkConstantPadImageFilter.h:21, …
```
=> COMP: Fix -Wstrict-overflow warning in itkImageRegionConstIteratorWithIndex

Modules/Core/Common/wrapping/itkImageSource.wrap, Modules/Core/Common/wrapping/itkImageToImageFilterA.wrap, Modules/Core/Common/wrapping/itkNumericTraits.wrap, Modules/Filtering/ImageFilterBase/wrapping/itkCastImageFilter.wrap, Modules/IO/ImageBase/wrapping/itkImageFileReader.wrap, Modules/IO/ImageBase/wrapping/itkImageFileWriter.wrap, Wrapping/Generators/Python/Tests/PythonTemplateTest.py
Support reading and writing unsigned integer images. unsigned long long
is wrapped since this is supported by the IO classes and 64-bit across
platforms.
An image can be read with:
image = itk.imread('filepath.mha', itk.ULL)
and cast for further processing.
=> ENH: Wrap unsigned long long for image reading writing

Modules/Filtering/Thresholding/include/itkMaximumEntropyThresholdCalculator.hxx, Modules/Filtering/Thresholding/include/itkMomentsThresholdCalculator.hxx, Modules/Filtering/Thresholding/include/itkShanbhagThresholdCalculator.hxx, Modules/Filtering/Thresholding/include/itkYenThresholdCalculator.hxx
Fix `threshold` local variable type and default to a zero value in
histogram threshold calculator classes.
Also, assign the default value when the variable is declared.
Fixes the runtime exception error mentioned in [this
comment](https://github.com/InsightSoftwareConsortium/ITK/pull/511#issuecomment-496063122)
and [this other
one](https://github.com/InsightSoftwareConsortium/ITK/pull/511#issuecomment-601404461).
=> BUG: Fix threshold variable type/value in histogram threshold calc classes

Modules/Filtering/Thresholding/include/itkIntermodesThresholdImageFilter.h
Change the `m_MaxSmoothingIterations` ivar name in
`itk::IntermodesThresholdImageFilter`
to `m_MaximumSmoothingIterations`
so that the Set/Get methods match the ones previous to the change in
6dc4948017858006200d57491459c49b3cbc5765.
=> ENH: Change ivar name in `itk::IntermodesThresholdImageFilter`

Modules/Filtering/Thresholding/include/itkHistogramThresholdImageFilter.h, Modules/Filtering/Thresholding/include/itkHistogramThresholdImageFilter.hxx
Refactor `itk::HistogramThresholdImageFilter` to avoid duplicated code,
and thus prevent potential bugs that can go unnoticed.
=> ENH: Avoid duplicated code in `itk::HistogramThresholdImageFilter`

Modules/Filtering/Thresholding/include/itkHistogramThresholdImageFilter.h
Make the `itk::HistogramThresholdImageFilter::SetUpHistogramGenerator`
method introduced in commit 4217cc0 be `private`: no child classes should
be able to call the method since it is an essential step in the parent's
`GenerateData` method.
=> ENH: Make the histogram generator set up method private

Wrapping/Generators/CastXML/CMakeLists.txt
Address:
C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/include\intrin0.h(255,36): error G7F5978A3: constexpr declaration of '__builtin_assume_aligned' follows non-constexpr declaration
With an update to CastXML 2020-03-31 Git master and LLVM 10.0.0.
=> COMP: Update CastXML binary for Visual Studio 2019

Modules/Filtering/ImageIntensity/include/itkShiftScaleImageFilter.hxx
ITKv5/Modules/Filtering/ImageIntensity/include/itkShiftScaleImageFilter.hxx:97:22:
warning: implicit conversion from 'itk::NumericTraits<unsigned long>::ValueType' (aka 'unsigned long') to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-int-float-conversion]
else if (value > NumericTraits<OutputImagePixelType>::max())
~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ITKv5/Modules/Filtering/ImageIntensity/include/itkShiftScaleImageFilter.h:105:3:
note: in instantiation of member function 'itk::ShiftScaleImageFilter<itk::Image<int, 3>, itk::Image<unsigned long, 3> >::ThreadedGenerateData' requested here
ShiftScaleImageFilter();
^
=> COMP: Suppress compiler warning about value trucation

Modules/Core/Transform/include/itkComposeScaleSkewVersor3DTransform.hxx, Modules/Core/Transform/test/itkComposeScaleSkewVersor3DTransformTest.cxx
Computed Jacobian using SymPy.  See comments in code for computation
script.
Added test to verify Jacobian with finite difference results.
=> ENH: Added jacobian computation to ComposeScaleSkewVersorTransform

Modules/IO/Meta/include/itkMetaImageIO.h, Modules/IO/Meta/src/itkMetaImageIO.cxx
Fixes #1753. The warning has been introduced by 0a1fd9e. 9e76e34
addressed it for 2D and 3D images but not for other dimensions.
This patch adresses it for dimensions 1D to 6D.
Other options to remove the warning would be:
- Implement the same thing but without the templated function but copy pasting following what's been started by @aylward if templated function is not desirable in this code.
- Remove the original direction matrix from the metadata dictionary since it's not used in ITK (I'm not sure where it's used @vfonov?).
- Put the original direction matrix in the metadata dictionary as an std::vector<double> instead of an itk::Matrix which would work for any dimension but requires a conversion to the adequate matrix type when it's used. …
=> BUG: remove warning when writing 1D, 4D, 5D and 6D images read from disk

Modules/Core/Transform/test/itkComposeScaleSkewVersor3DTransformTest.cxx
Modules/Core/Transform/test/itkComposeScaleSkewVersor3DTransformTest.cxx:560:37: warning: unused variable 'pntT' [-Wunused-variable]
TransformType::InputPointType pntT = idT->TransformPoint(pnt);
^
=> COMP: Unused variable warning

Modules/IO/DCMTK/include/itkDCMTKImageIO.h
Modules/IO/DCMTK/include/itkDCMTKImageIO.h:31: error: "\ingroup non" not set in class DCMTKImageIOEnums.
Modules/IO/DCMTK/include/itkDCMTKImageIO.h:38: error: "\ingroup ITKIODCMTK" not set in class LogLevel.
1/1 Test #850: ITKIODCMTKInDoxygenGroup .........***Failed    0.04 sec
=> DOC: Fix missing \ingroup ITKIODCMTK

Modules/Core/Common/src/CMakeLists.txt
The "itkAbortProcessObjectTest" fails unless all compilation
units successfully pass exceptions.
The following tests FAILED:
413 - itkAbortProcessObjectTest (Failed)
➜  ITKv5-RelWithDebInfo-build ctest -V -R itkAbortProcessObjectTest
UpdateCTestConfiguration  from :/Users/johnsonhj/src/BRAINSTools-sysclang-RelWithDebInfo/ITKv5-RelWithDebInfo-build/DartConfiguration.tcl
Parse Config file:/Users/johnsonhj/src/BRAINSTools-sysclang-RelWithDebInfo/ITKv5-RelWithDebInfo-build/DartConfiguration.tcl
Start 413: itkAbortProcessObjectTest
413: Test command: /Users/johnsonhj/src/BRAINSTools-sysclang-RelWithDebInfo/BRAINSTools-RelWithDebInfo-EPRelWithDebInfo-build/bin/ITKCommon1TestDriver "itkAbortProcessObjectTest"
413: Test timeout computed to be: 1500
413: ExtractImageFilter (0x7fbb8ef54430)
413: …
=> BUG: TBB build requires consistent exception options

Modules/IO/GDCM/ITKKWStyleOverwrite.txt, Modules/IO/GDCM/include/itkGDCMSeriesFileNames.h, Modules/IO/GDCM/itk-module.cmake, Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx
Make the third partly library a private dependency, for the ITK GDCM
ImageIO modules. This follows best practices of data encapsulation.
Move the implementation of the destructor to the cxx file as a best
practice as it ensure intonation of the vtable in the library.
=> BUG: Use GDCM as private dependency in ITKIOGDCM

Modules/Remote/RTK.remote.cmake
The current RTK version does not compile with ITK master due to the change in the ITKGDCM dependency. We are still investigating issue SimonRit/RTK#340 so I would suggest to merge this PR only if the tagging of ITK v5.1 is not postponed. `git shortlog cf109ba..f43ecb2 | grep -v "Merge pull request"` gives:
Antoine Robert (8):
BUG: Use real image type as input of Hilbert filter
COMP: Fix wrapping when building ITK with dimension 1
ENH: wrap image file reader and writer for dimension 1
ENH: wrap NumpyBridge for dimension 1
ENH: Add quadratic penalization to OSEM algorithm
STYLE: Use override instead of ITK_OVERRIDE
STYLE: Use default member initialization
BUG: Change member type from float to double in Zeng projectors
Aurélien Coussat (7):
PERF: reduced size of application tests
STYLE: …
=> ENH: update remote module RTK

Wrapping/Generators/Python/itkExtras.py
Prevent floating point precision issues from generating the incorrect
number of coords.
=> BUG: Use linspace for coords in xarray_from_image

Wrapping/Generators/Python/itkTemplate.py
To prevent errors like:
File "/home/matt/bin/ITK-Wrap-MinSizeRel/Wrapping/Generators/Python/itkTemplate.py",
line 515, in New
if not input_type:
UnboundLocalError: local variable 'input_type' referenced before assignment
Also, improve corresponding error message to include the `ttype` keyword
parameter option.
=> BUG: Provide initial input_type value in itkTemplate

Modules/Bridge/NumPy/wrapping/PyBuffer.i.in, Modules/Bridge/NumPy/wrapping/PyBuffer.i.init, Modules/Bridge/NumPy/wrapping/PyVnlVectorBuffer.i.in, Modules/Bridge/NumPy/wrapping/test/itkPyBufferTest.py
Prevent the view'ed image from going out of scope by holding a reference
in a new class, NDArrayITKBase. The object is kept in the `itk_base`
attributed -- the typical `base` attribute NumPy uses for this purpose
is not writable. The class is created according to the documentation
here:
https://numpy.org/doc/stable/user/basics.subclassing.html
=> BUG: Keep itk.Image reference in NumPy array views

Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Defl.c, Modules/ThirdParty/HDF5/src/itkhdf5/src/H5win32defs.h
H5_HAVE_VISUAL_STUDIO may be defined if Visual Studio is present on the
build system even if MinGW-w64 is the currently used compiler.
=> COMP: Condition HDF5 HDopen on _MSC_VER definition

Wrapping/Generators/Python/itkHelpers.py
Following #1774, it is safe to return a NumPy array view of the output
itk.Image. This prevents an extra memory allocation and copy.
@jni no more unneeded copies when operating on NumPy arrays :hand: :five:
=> BUG: Filters avoid extra copies when operating on NumPy arrays

Modules/Bridge/NumPy/wrapping/PyBuffer.i.in, Modules/Bridge/NumPy/wrapping/test/itkPyBufferTest.py, Wrapping/Generators/Python/PyBase/pyBase.i, Wrapping/Generators/Python/itkHelpers.py, Wrapping/Generators/Python/itkTypes.py
This provide the same values when converted to a np.ndarray with
itk.array_view_from_image. They are used to identify data types that
provide a NumPy array-like interface.
=> ENH: ndim, shape, and dtype attributes for itk.Image

Modules/Filtering/ImageGrid/test/itkResampleImageTest8.cxx
To address:
[CTest: warning matched] /Users/builder/externalModules/Filtering/ImageGrid/test/itkResampleImageTest8.cxx:114:3: warning: '~ProjectTransform' overrides a destructor but is not marked 'override' [-Winconsistent-missing-destructor-override]
~ProjectTransform() = default;
^
[CTest: warning matched] /Users/builder/externalModules/Core/Transform/include/itkTransform.h:559:3: note: overridden virtual function is here
~Transform() override = default;
^
=> COMP: itkResampleImageTest8 ~ProjectTransform mark as override

Modules/Filtering/FFT/wrapping/itkFFTWGlobalConfiguration.wrap, Modules/Registration/PDEDeformable/include/itkCurvatureRegistrationFilter.h, Modules/Registration/PDEDeformable/include/itkCurvatureRegistrationFilter.hxx
Conditional in .h file did not implement intended logic (resulting in compilation error when used, e.g., with Python wrapping enabled) and logic was not duplicated in .hxx file (resulting in .hxx definitions without a corresponding .h).
=> BUG: CurvatureRegistrationFilter fix logic re: depends on FFTW

Modules/Remote/TubeTK.remote.cmake
Update TubeTK tag to use latest version.
Highlights:
* Add support for FFTW(cufft) - make it a public dependency of TubeTK
* Support for python packaging (Thanks Matt!)
=> ENH: Bump TubeTK to support CUFFTW

Modules/Remote/TubeTK.remote.cmake
Also enables building TubeTK's applications.
=> ENH: Bump TubeTK to version that removes ArrayFire (replaced by cufft)

Modules/Registration/Metricsv4/test/itkMattesMutualInformationImageToImageMetricv4Test.cxx
Add a simple regression test to ensure that the metric returned
values are consistent over time.
When run before recently merged "double normalization bug" fix the following results were obtained.
```bash
2018: 	[FAILED] known values for metric values not computed correctly.-10.50833512288329 != -1.297994750907097
2018: 	[FAILED] known values for metric values not computed correctly.-10.50833574913326 != -1.297995377157083
2018: 	[FAILED] known values for metric values not computed correctly.-10.50833482019903 != -1.297994448222851
2018: 	[FAILED] known values for metric values not computed correctly.-10.508336072699 != -1.297995700722833
```
=> ENH: Add test to monitor metric result value

Modules/Core/Common/include/itkSTLConstContainerAdaptor.h
Need to `#include <itkMacro.h>` for definition
of ITK_DISALLOW_COPY_AND_ASSIGN.
=> COMP: Missing defition of ITK_DISALLOW_COPY_AND_ASSIGN

Modules/ThirdParty/HDF5/CMakeLists.txt, Modules/ThirdParty/HDF5/itk-module-init.cmake
Reset BUILD_SHARED_LIBS to the root project initial state in case
this option is modified before processing the configuration of
a third-party module.
Closes #1658
=> BUG: Fix BUILD_SHARED_LIBS state consistency for HDF5

Modules/Bridge/NumPy/wrapping/PyBuffer.i.in
Allow the use of the function GetImageFromArray with arrays of dimension
1.
The previous assert prevented the use of the Numpy bridge for the
dimension 1 even if this dimension was wrapped.
This change is motivated by the [pull request](https://github.com/SimonRit/RTK/pull/344) of @LucasGandel to extend itkPyBuffer available types for [RTK](https://github.com/SimonRit/RTK) python wrapping.  
=> ENH: Use Numpy bridge with array of dimension 1

Modules/Bridge/VtkGlue/wrapping/itkViewImage.wrap
Instead of hard-coded `2;3` dimensions
=> BUG: Use ITK_WRAP_IMAGE_DIMS in ViewImage.wrap

Modules/Core/Common/include/itkFixedArray.h, Modules/Core/Common/include/itkFixedArray.hxx, Modules/Core/Common/test/itkFixedArrayGTest.cxx
This unifies the interface of FixedArray with std containers.
New names for already existing functionality:
- `data()` is exactly the same as `GetDataPointer()`
- `size()` the same as `Size()`
And as a result of this common interface, we can use the python
utility method `itk.GetArrayViewFromVnlVector` in `itk.Point`,
and all other classes derived from `FixedArray`.
- [NA] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [NA] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)
=> ENH: Add data() and size() member functions to FixedArray

.github/workflows/apply-clang-format.yml
The default fetch depth is 1.
To prevent:
reference is not a tree: 518349019984699b8d35a953bf4fc8a4324897fa
Git checkout failed on shallow repository, this might because of git fetch with depth '1' doesn't include the checkout commit '518349019984699b8d35a953bf4fc8a4324897fa'.
=> BUG: Fetch full depth in apply-clang-format action

Modules/ThirdParty/MetaIO/src/MetaIO/src/metaArray.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaArrow.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaCommand.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaCommand.h, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaContour.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaDTITube.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaFEMObject.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaFEMObject.h, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaForm.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaImage.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaImage.h, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaMesh.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaObject.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaOutput.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaScene.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaTypes.h, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaUtils.cxx, Modules/ThirdParty/MetaIO/src/MetaIO/src/metaVesselTube.cxx
Update to MetaIO tag f473b7b86a15dc2f3578f1e82b5544ef7776e2e7
from May 11, 2020.
ENH: Parse() should handle char *argv[] as const (#91)
=> ENH: Bump MetaIO to address style and const params

Modules/Registration/Metricsv4/include/itkPointSetToPointSetMetricv4.hxx
change index type to SizeValueType in functor for ParallelizeArray
also change start/end index type to SizeValueType.
=> COMP: Fix warning in PointSetToPointSetMetricv4

Modules/Filtering/ImageNoise/include/itkAdditiveGaussianNoiseImageFilter.h, Modules/Filtering/ImageNoise/include/itkAdditiveGaussianNoiseImageFilter.hxx, Modules/Filtering/ImageNoise/include/itkSaltAndPepperNoiseImageFilter.h, Modules/Filtering/ImageNoise/include/itkSaltAndPepperNoiseImageFilter.hxx, Modules/Filtering/ImageNoise/include/itkShotNoiseImageFilter.h, Modules/Filtering/ImageNoise/include/itkShotNoiseImageFilter.hxx, Modules/Filtering/ImageNoise/include/itkSpeckleNoiseImageFilter.h, Modules/Filtering/ImageNoise/include/itkSpeckleNoiseImageFilter.hxx
With the TBB threader the results were dependent on how the regions
were dynamically split.
The noise filters are designed to be reproducible for a fixed seed and
a number of threads. The implementation requires that the image is
split into fix deterministic regions.
Closes #1794.
=> BUG: Disable dynamic threading in noise filter.

.github/FUNDING.yml, GOVERNANCE.md, README.md
Add NumFOCUS-related contents to README:
- Add `powered by NumFOCUS` badge.
- Add text indicating ITK is a NumFOCUS sponsored project.
- Add donation page link and exact text.
- Add fiscal sponsor README attribution, including the required
`GOVERNANCE.md` file.
Take advantage of the commit to add to `.github/FUNDING.yml` the custom
link for donating directly to ITK through NumFOCUS.
=> DOC: Add NumFOCUS-related contents to README

Modules/Core/Transform/include/itkCompositeTransform.hxx, Modules/Core/Transform/test/itkCompositeTransformTest.cxx
When the CompositeTransform contains no transform is should behave
like an identity transform. This patches address loop iteration issues
that would cause a segmentation fault due to invalid indexing of
transforms when there composite was empty.
=> BUG: Fix additional segmentation faults with empty Composite - For Release

Modules/Core/Common/include/itkMapContainer.h, Modules/Core/Common/include/itkVectorContainer.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkVectorContainerTest.cxx, Modules/Core/SpatialObjects/include/itkContourSpatialObjectPoint.h, Modules/Core/SpatialObjects/include/itkContourSpatialObjectPoint.hxx, Modules/Core/SpatialObjects/include/itkDTITubeSpatialObjectPoint.h, Modules/Core/SpatialObjects/include/itkDTITubeSpatialObjectPoint.hxx, Modules/Core/SpatialObjects/include/itkLineSpatialObjectPoint.h, Modules/Core/SpatialObjects/include/itkLineSpatialObjectPoint.hxx, Modules/Core/SpatialObjects/include/itkSpatialObjectPoint.h, Modules/Core/SpatialObjects/include/itkSpatialObjectPoint.hxx, Modules/Core/SpatialObjects/include/itkSurfaceSpatialObjectPoint.h, Modules/Core/SpatialObjects/include/itkSurfaceSpatialObjectPoint.hxx, Modules/Core/SpatialObjects/include/itkTubeSpatialObjectPoint.h, Modules/Core/SpatialObjects/include/itkTubeSpatialObjectPoint.hxx, Modules/Core/SpatialObjects/test/CMakeLists.txt, Modules/Core/SpatialObjects/test/itkContourSpatialObjectPointTest.cxx, Modules/Core/SpatialObjects/test/itkDTITubeSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkLineSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkSurfaceSpatialObjectTest.cxx
This addresses warnings in itk::MapContainer and
itk::VectorContainer regarding deprecation of implicitly defined
operator= (with explicitly defined copy constructor) or vice
versa.  This begins to address GitHub Issue #1302.  There
remain a number of warnings in SpatialObjects, so this patch
does not completely resolve the issue.
=> Address Wdeprecated-copy warnings on gcc 9.3

Modules/Filtering/Thresholding/test/CMakeLists.txt, Modules/Numerics/Statistics/include/itkHistogram.hxx
This method was introduced by fb95a5e613362e956788ab0cdb444cc8e7f6a211,
but it never worked properly, always returning 1.
=> BUG: fix Statistics::Histogram::Mean calculation

Wrapping/Generators/CastXML/CMakeLists.txt
Add support for GCC 10. Re: https://discourse.itk.org/t/weird-compile-errors-when-setting-dcmake-cxx-standard-17/3094/6
The CastXML binaries were built against LLVM 10 as opposed to LLVM 6 for improved C++ syntax support.
=> COMP: Bump CastXML to 0.3.4

Wrapping/Generators/Python/itkHelpers.py
Example:
In [1]: import itk
In [2]: import torch
In [3]: import numpy as np
In [4]: a = np.random.rand(50,50)
In [5]: t = torch.from_numpy(a)
In [6]: r = itk.median_image_filter(t)
In [7]: r
Out[7]:
tensor([[0.8428, 0.3881, 0.3881,  ..., 0.3222, 0.3953, 0.3408],
[0.7785, 0.3881, 0.1350,  ..., 0.3953, 0.4557, 0.5307],
[0.4023, 0.4023, 0.3787,  ..., 0.4440, 0.5307, 0.6666],
...,
[0.4938, 0.4938, 0.6298,  ..., 0.4480, 0.1807, 0.1341],
[0.3539, 0.4938, 0.7471,  ..., 0.4480, 0.1618, 0.1341],
[0.3539, 0.3539, 0.6298,  ..., 0.1618, 0.1618, 0.1618]],
dtype=torch.float64)
Suggested-by: Stephen R. Aylward <stephen.aylward@kitware.com>
=> ENH: Add torch.Tensor input/output support for ITK filters

Modules/Remote/TubeTK.remote.cmake
Disable wrapping of classes that depend on VTK, if TubeTK_USE_VTK is
not set to True.
=> BUG: Bump TubeTK to isolate wrapping on vtk-dependent classes

Modules/IO/GDCM/include/itkGDCMImageIO.h
Correct the doc string for ReadImageInformation() in Modules/IO/GDCM/include/itkGDCMImageIO.h.
=> STYLE: Correct doc for ReadImageInformation

Modules/IO/GDCM/src/itkGDCMImageIO.cxx
In InternalReadImageInformation:
When pixel type is larger than the output type, it is likely
something wrong in the dataset currently being read.
An example is if the following two headers are "out-of-sync"
(0028,0100) BitsAllocated
(0028,0101) BitsStored
Instead of ignoring this sanity check in release-mode,
it is better to throw an exception. That way, the caller
can handle the error instead of seeing the application crash.
Please note the following warning in
Documentation/ReleaseNotes/3.14.md
"when using itkAssertInDebugOrThrowInReleaseMacro do not
terminate with a ;"
Signed-off-by: Niklas Johansson <raphexion@gmail.com>
=> ENH: Prevent segfault by failing fast in itkGDCMImageIO

.github/labeler.yml, .github/workflows/label-pr.yml
Applies a PR based the title prefix, which defaults to the commit prefix
for single-commit topics.
Closes #60
Note: this will be currently limited to PR's created from `InsightSoftwareConsortium/ITK` branches (requires repository write permission) per:
- https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token
- https://github.com/actions/labeler/issues/12
We could experiment with developers with write access creating PR's from the ITK repository.
=> ENH: Add Label PR GitHub Action

Modules/Numerics/Statistics/include/itkExpectationMaximizationMixtureModelEstimator.hxx
The `#include` for `itkExpectationMaximizationMixtureModelEstimator.h` from `Modules/Numerics/Statistics/include/itkExpectationMaximizationMixtureModelEstimator.hxx` was to an incorrect path.
Details are enumerated in the GitHub Issue
Closes #1907.
Short summary is that it causes this error when compiling the ITKExamples.
```
Scanning dependencies of target 2DGaussianMixtureModelExpectMax
[ 97%] Building CXX object src/Numerics/Statistics/2DGaussianMixtureModelExpectMax/CMakeFiles/2DGaussianMixtureModelExpectMax.dir/Code.cxx.o
In file included from /tmp/local/include/ITK-5.1/itkExpectationMaximizationMixtureModelEstimator.h:246,
from /tmp/bennetsw/build/ITK/BuildIt/ITKExamples/src/Numerics/Statistics/2DGaussianMixtureModelExpectMax/Code.cxx:21: …
```
=> BUG: Fixing #include for itkExpectationMaximizationMixtureModelEstimator.h

CMake/itkExternal_FFTW.cmake
On Centos 7.5 the internal CMAKE_INSTALL_LIBDIR
is 'lib64' instead of 'lib'.  Ensure that the
internal glob for installing the shared
libraries uses the platform specific
CMAKE_INSTALL_LIBDIR for installing the
shared libraries.
=> BUG: Centos internal lib64 lib path

Modules/Core/Common/wrapping/itkImageToImageFilterA.wrap, Modules/Core/Common/wrapping/itkInPlaceImageFilterA.wrap, Modules/Filtering/ImageFilterBase/wrapping/itkCastImageFilter.wrap
Feasibility for working with segmentation outputs.
=> BUG: Support casting unsigned long pixel types in Python

Wrapping/Generators/Python/PyBase/pyBase.i, Wrapping/Generators/Python/Tests/extras.py, Wrapping/Generators/Python/itkTypes.py
Similar to the numpy.ndarray.astype, supporting itk PixelType's and
numpy dtype's.
More convenient than itk.cast_image_filter, similar to
numpy.ndarray.astype. itk.Image PixelType's are supported along with
scalar numpy dtype's. itkType.itkCType.GetCTypeForDType is added to
support conversion.
=> ENH: Add image.astype(pixel_type) for casting

Wrapping/Generators/Python/Tests/extras.py, Wrapping/Generators/Python/itkExtras.py
Related the [issue](https://github.com/InsightSoftwareConsortium/ITK/issues/1137) and [PR](https://github.com/InsightSoftwareConsortium/ITKExamples/pull/149). The screenshot of a test result is shown as follows.
=> ENH: Add a convenient function to get/set the number of threads.

Wrapping/Generators/Python/itkHelpers.py
Required for returning the (registered_image, transform_parameters)
output when ndarray's is passed for the fixed and moving image in
itk-elastix.
=> BUG: Add missing enumerate with multi-ndarray-output itk filters

Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx
With the Emscripten-upstream compiler:
In file included from /ITK/Modules/Core/Common/src/itkFloatingPointExceptions.cxx:127:
/ITK/Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx:140:22: error: use of undeclared identifier 'FE_DIVBYZERO'
itk_feenableexcept(FE_DIVBYZERO);
^
/ITK/Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx:141:22: error: use of undeclared identifier 'FE_INVALID'
itk_feenableexcept(FE_INVALID);
=> COMP: Do not reference FE_DIVBYZERO FE_INVALID with Emscripten

Modules/Core/Common/include/itkImageSource.hxx, Modules/Core/Common/src/itkMultiThreaderBase.cxx, Modules/Core/Common/src/itkPoolMultiThreader.cxx, Modules/Core/Common/src/itkTBBMultiThreader.cxx
Implementing the suggestion made in [a forum post](https://discourse.itk.org/t/no-progress-reporting-in-itk5/2630/33?u=dzenanz). Related to #1673.
=> ENH: progress reporting does not stall with PoolMultiThreader

Testing/ContinuousIntegration/AzurePipelinesMacOS.yml, Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
To address recent failures:
File "/usr/local/lib/python3.8/site-packages/anyci/ctest_junit_formatter.py", line 4, in <module>
from lxml import etree
ModuleNotFoundError: No module named 'lxml'
=> COMP: Add lxml to macOS CI environment

CMake/itkExternal_FFTW.cmake, CMakeLists.txt
Resolves: #1930 for mac builds
The found fftw libraries locations were not pass
to ITK builds when using the system installed fftw.
=> BUG: Fix fftw linkage issue with system fftw

Modules/Remote/AnalyzeObjectLabelMap.remote.cmake, Modules/Remote/AnisotropicDiffusionLBR.remote.cmake, Modules/Remote/BSplineGradient.remote.cmake, Modules/Remote/BioCell.remote.cmake, Modules/Remote/BoneEnhancement.remote.cmake, Modules/Remote/Cuberille.remote.cmake, Modules/Remote/GenericLabelInterpolator.remote.cmake, Modules/Remote/HigherOrderAccurateGradient.remote.cmake, Modules/Remote/IOScanco.remote.cmake, Modules/Remote/MGHIO.remote.cmake, Modules/Remote/MinimalPathExtraction.remote.cmake, Modules/Remote/Montage.remote.cmake, Modules/Remote/MultipleImageIterator.remote.cmake, Modules/Remote/PerformanceBenchmarking.remote.cmake, Modules/Remote/RTK.remote.cmake, Modules/Remote/SCIFIO.remote.cmake, Modules/Remote/SimpleITKFilters.remote.cmake, Modules/Remote/SphinxExamples.remote.cmake, Modules/Remote/SubdivisionQuadEdgeMeshFilter.remote.cmake, Modules/Remote/TextureFeatures.remote.cmake, Modules/Remote/TotalVariation.remote.cmake, Modules/Remote/TubeTK.remote.cmake, Modules/Remote/TwoProjectionRegistration.remote.cmake
Update remote modules.
Used the `/Utilities/Maintenance/UpdateRemoteModules.sh` script to update
the modules.
Manually remove the double quotes for the commit hash before update for
the the `RTK` and `TubeTK` modules to allow the script to work as
expected.
Take advantage of the commit to do minor manual editions on the `RTK` and
`TubeTK` remote files concerning the style.
=> ENH: Update remote modules

Modules/Video/BridgeOpenCV/include/itkOpenCVImageBridge.h, Modules/Video/BridgeOpenCV/test/itkOpenCVImageBridgeGrayScaleTest.cxx, Modules/Video/BridgeOpenCV/test/itkOpenCVImageBridgeRGBTest.cxx, Modules/Video/BridgeOpenCV/test/itkOpenCVTestHelper.cxx
This fixes Issue #1929 as well as compile warnings introduced in the update (unused method parameter and signed/unsigned comparison)
In addition, this fixes the tests' compile errors due tu deprecated assignment of cv::Mat to IplImage
=> COMP: fix errors and warnings in OpenCV bridge

Examples/Segmentation/GeodesicActiveContourImageFilter.cxx, Examples/Segmentation/GeodesicActiveContourShapePriorLevelSetImageFilter.cxx, Examples/Segmentation/IsolatedConnectedImageFilter.cxx, Examples/Segmentation/VectorConfidenceConnected.cxx
Fix SW Guide examples multi-line comment warnings.
Fixes:
```
/home/kitware/Dashboards/TestsExamples/Segmentation/GeodesicActiveContourShapePriorLevelSetImageFilter.cxx:1030:3:
warning: multi-line comment [-Wcomment]
//  \includegraphics[width=0.10\textwidth]{CorpusCallosumModePlus2} \\
^
```
and
```
/home/kitware/Dashboards/TestsExamples/Segmentation/IsolatedConnectedImageFilter.cxx:268:3:
warning: multi-line comment [-Wcomment]
//  Adjacent Structures & Seed1 & Seed2 & Lower & Isolated value found
//  \\
^
```
and
```
/home/kitware/Dashboards/TestsExamples/Segmentation/VectorConfidenceConnected.cxx:276:3:
warning: multi-line comment [-Wcomment]
//  Structure & Seed Index & Multiplier & Iterations & Output Image …
```
=> COMP: Fix SW Guide examples multi-line comment warnings

Examples/SpatialObjects/TubeSpatialObject.cxx, Modules/Core/SpatialObjects/include/itkSpatialObjectPoint.h, Modules/Core/SpatialObjects/include/itkTubeSpatialObject.h, Modules/Core/SpatialObjects/include/itkTubeSpatialObject.hxx, Modules/Core/SpatialObjects/test/itkDTITubeSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkTubeSpatialObjectTest.cxx
TubeSpatialObject::ComputeTangent(s)AndNormals() would result in
certain normals not being unit vectors.  This fixes and tests for
those errors.
COMP: Fixes a spelling mistake in ComputeTangentAndNormals by
making Tangents plural, as it should be.  This function is primarily
used by internal methods so chances of breaking backward compartibility
are slim.
=> BUG: TubeSpatialObject normals not unit vectors

Modules/Filtering/Thresholding/test/itkThresholdImageFilterTest.cxx
Improve `itk::ThresholdImageFilter` class coverage:
- Exercise the Set/Get methods using the `ITK_TEST_SET_GET_VALUE` macro.
=> ENH: Improve `itk::ThresholdImageFilter` class coverage

Modules/Core/SpatialObjects/include/itkPolygonSpatialObject.hxx
Fix ivar print value in `itk::PolygonSpatialObject`.
=> STYLE: Fix ivar print value in `itk::PolygonSpatialObject`

Modules/Video/IO/test/CMakeLists.txt, Modules/Video/IO/test/itkVideoFileReaderWriterTest.cxx
Improve the `itk::VideoFileWriter` class coverage:
- Use the `ITK_TRY_EXPECT_NO_EXCEPTION` macro when updating the filters.
- Exercise the Set/Get methods using the `ITK_TEST_SET_GET_VALUE` macro.
- Add arguments to the test to improve the class testing of the additional
ivars.
=> ENH: Improve the `itk::VideoFileWriter` class coverage.

Modules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceImageFilter.h, Modules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceImageFilter.hxx
Remove unnecessary inherited member re-definitions.
Add the missing call to its CPU superclass `PrintSelf` method.
Fixes
```
/Users/builder/externalModules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceImageFilter.h:145:3:
warning: 'SetMaximumRMSError' overrides a member function but is not
marked 'override' [-Winconsistent-missing-override]
/Users/builder/externalModules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceImageFilter.h:146:3:
warning: 'GetMaximumRMSError' overrides a member function but is not
marked 'override' [-Winconsistent-missing-override]
```
and
```
/Users/builder/externalModules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceImageFilter.h:150:3:
warning: 'SetRMSChange' overrides a member function but is not marked
'override' …
```
=> COMP: Remove unnecessary inherited member re-definitions

Modules/IO/DCMTK/test/CMakeLists.txt, Modules/IO/DCMTK/test/itkDCMTKSeriesReadImageWrite.cxx
Improve `itk::DCMTKSeriesFileNames` class coverage:
- Use the `ITK_TRY_EXPECT_NO_EXCEPTION` macro when updating the filters.
- Exercise the Set/Get methods using the `ITK_TEST_SET_GET_VALUE` macro.
- Add arguments to the test to improve the class testing of the additional
ivars.
=> ENH: Improve `itk::DCMTKSeriesFileNames` class coverage

Modules/Filtering/ImageStatistics/test/itkStandardDeviationProjectionImageFilterTest.cxx
Avoid `try`/`catch` boilerplate code in updating writer by using the
`ITK_TRY_EXPECT_NO_EXCEPTION` macro.
=> STYLE: Avoid `try`/`catch` boilerplate code in updating writer

Modules/Filtering/DiffusionTensorImage/include/itkTensorFractionalAnisotropyImageFilter.h, Modules/Filtering/DiffusionTensorImage/include/itkTensorRelativeAnisotropyImageFilter.h
Fix typos in DTI module's anisotropy image filter classes.
=> DOC: Fix typos in DTI module's anisotropy image filter classes

Modules/Filtering/SpatialFunction/include/itkSpatialFunctionImageEvaluatorFilter.h, Modules/Filtering/SpatialFunction/include/itkSpatialFunctionImageEvaluatorFilter.hxx
Add the `PrintSelf` method to the `itk::SpatialFunctionImageEvaluatorFilter`
class.
=> ENH: Add the `PrintSelf` method to `itk::SpatialFunctionImageEvaluatorFilter`

Modules/Core/SpatialObjects/include/itkSpatialObjectToImageFilter.hxx
Remove unnecessary comment lines separating methods definitions.
=> STYLE: Remove unnecessary comment lines

Modules/Filtering/DiffusionTensorImage/test/CMakeLists.txt, Modules/Filtering/DiffusionTensorImage/test/itkDiffusionTensor3DReconstructionImageFilterTest.cxx, Modules/Filtering/DiffusionTensorImage/test/itkTensorFractionalAnisotropyImageFilterTest.cxx, Modules/Filtering/DiffusionTensorImage/test/itkTensorRelativeAnisotropyImageFilterTest.cxx
Improve the DTI module classes coverage
- Increase the ability of the testing for the
`itk::DiffusionTensor3DReconstructionImageFilterTest` class by adding an
input argument to the test.
=> ENH: Improve the DTI module classes coverage

Modules/Filtering/SpatialFunction/test/itkSpatialFunctionImageEvaluatorFilterTest.cxx
Improve coverage for `SpatialFunction` module classes:
Take advantage of improve consistency in variable naming.
=> ENH: Improve coverage for `SpatialFunction` module classes

Modules/Core/SpatialObjects/include/itkContourSpatialObject.hxx
Fix `itk::ContourSpatialObject` ivar initialization value type: avoid
unnecessary casting from `float`/`double` to `unsigned int`.
=> COMP: Fix `itk::ContourSpatialObject` ivar initialization value type

Modules/Core/SpatialObjects/test/itkArrowSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkBlobSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkBoxSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkCastSpatialObjectFilterTest.cxx, Modules/Core/SpatialObjects/test/itkContourSpatialObjectPointTest.cxx, Modules/Core/SpatialObjects/test/itkContourSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkDTITubeSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkEllipseSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkGaussianSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectTest2.cxx, Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectTest3.cxx, Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectTest4.cxx, Modules/Core/SpatialObjects/test/itkImageSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkLandmarkSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkLineSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkMeshSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkMetaArrowConverterTest.cxx, Modules/Core/SpatialObjects/test/itkMetaGaussianConverterTest.cxx, Modules/Core/SpatialObjects/test/itkNewMetaObjectTypeTest.cxx, Modules/Core/SpatialObjects/test/itkPolygonSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkSpatialObjectDuplicatorTest.cxx, Modules/Core/SpatialObjects/test/itkSpatialObjectToImageFilterTest.cxx, Modules/Core/SpatialObjects/test/itkSpatialObjectToImageStatisticsCalculatorTest.cxx, Modules/Core/SpatialObjects/test/itkSpatialObjectToPointSetFilterTest.cxx, Modules/Core/SpatialObjects/test/itkSurfaceSpatialObjectTest.cxx, Modules/Core/SpatialObjects/test/itkTubeSpatialObjectTest.cxx
Improve coverage for `SpatialObjects` module classes:
- Remove explicit calls to the `Print` method and rely on the basic method
exercising macro call.
- Use the C++ ITK style in variable naming.
- Remove unnecessary comment in files about their purpose.
=> ENH: Improve coverage for `SpatialObjects` module classes.

Modules/Filtering/MathematicalMorphology/test/CMakeLists.txt, Modules/Filtering/MathematicalMorphology/test/itkTopHatImageFilterTest.cxx
Improve `itk::BlackTopHatImageFilter` and `itk::WhiteTopHatImageFilter`
classes coverage:
- Use the `ITK_TRY_EXPECT_NO_EXCEPTION` macro when updating the filters.
- Exercise the Set/Get methods using the `ITK_TEST_SET_GET_VALUE` macro.
- Refactor the test to reduce boilerplate code.
- Add arguments to the test to improve the class testing of the additional
ivars.
=> ENH: Improve TopHatImageFilter classes coverage

Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
Fixed Visual Studio 2019 Code Analysis (C++ Core Guidelines) warning
C26454 in `MersenneTwisterRandomVariateGenerator::reload()`, saying:
> Arithmetic overflow: '-' operation produces a negative unsigned result
> at compile time (io.5).
Declared the `index` variable `constexpr`.
=> COMP: Fix arithmetic overflow MersenneTwisterRandomVariateGenerator

Modules/Core/Common/include/itkImage.hxx
Trying to fix the [warning](https://open.cdash.org/viewBuildError.php?type=1&buildid=6756465):
```text
In file included from /Users/builder/externalModules/Core/ImageFunction/test/itkSumOfSquaresImageFunctionGTest.cxx:22:
In file included from /Users/builder/externalModules/Core/Common/include/itkImage.h:346:
[CTest: warning matched] /Users/builder/externalModules/Core/Common/include/itkImage.hxx:152:46: warning: variable 'p' is uninitialized when passed as a const reference argument here [-Wuninitialized-const-reference]
return NumericTraits<PixelType>::GetLength(p);
^
[CTest: warning matched] /Users/builder/externalModules/Core/Common/include/itkImage.h:322:3: note: in instantiation of member function 'itk::Image<double, 2>::GetNumberOfComponentsPerPixel' requested here
Image();
^ …
```
=> COMP: variable is uninitialized when passed as a const reference

Modules/Remote/TubeTK.remote.cmake
Changes include
* Update to use ComputeTangentsAndNormals()
* Fix to image registration
* New way to read and write 4D images from a set of 3D images in python and via command line
=> ENH: Bump TubeTK to version that works with updated Spatial Objects

Modules/Core/Common/include/itkWeakPointer.h, Modules/Core/Common/test/CMakeLists.txt, Modules/Core/Common/test/itkWeakPointerGTest.cxx
Small WeakPointer improvements:
- Defaulted default-constructor (allowing the compiler to consider it
"constexpr" and "noexcept")
- Removed the other user-defined special functions (Rule Of Zero)
- Removed redundant user-defined `operator=(ObjectType*)`
- Added converting constructor, WeakPointer(std::nullptr_t).
No longer allowed implicit conversion from the integer zero.
Included GoogleTest unit tests.
=> STYLE: Allow conversion from nullptr to WeakPointer, not from zero

Modules/Core/Common/include/itkSmartPointer.h
Defaulted the default-constructor of `SmartPointer`. Slightly simplified
the implementation of `SmartPointer(std::nullptr_t)` and its destructor.
=> STYLE: Add in-class default member initializer to SmartPointer m_Pointer

Modules/Filtering/BinaryMathematicalMorphology/include/itkBinaryDilateImageFilter.h, Modules/Filtering/BinaryMathematicalMorphology/include/itkBinaryErodeImageFilter.h, Modules/Filtering/BinaryMathematicalMorphology/include/itkBinaryMorphologyImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkBasicDilateImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkBasicErodeImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleFunctionDilateImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleFunctionErodeImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleGeodesicDilateImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalClosingImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalOpeningImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkMorphologicalGradientImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkMovingHistogramDilateImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkMovingHistogramErodeImageFilter.h
Improve documentation of classes in `BinaryMathematicalMorphology` and
`MathematicalMorphology` modules:
- Fix class brief descriptions to match the purpose of the filter.
- Remove wrong descriptions/descriptions corresponding to other filters.
- Fix spelling of `grayscale`.
- Capitalize the `\brief` description as a sentence and use punctuation.
=> DOC: Improve math morphology class documentation

Modules/ThirdParty/HDF5/CMakeLists.txt
This does not make a difference wrt #1971 on my computer.
=> ENH: append properties instead of overwrite in HDF5

Modules/Core/Common/src/itkDataObject.cxx
The filters that rely on DataObject class, eg. itk::MaskImageFilter corrupt the input image (clears it) despite that both global and filter relative setting to release data is set to false.
Submitted by @urosvovk1. Closes #2023.
=> BUG: Filter inputs are erroneously released

Modules/Filtering/MathematicalMorphology/CMakeLists.txt, Modules/Filtering/MathematicalMorphology/include/itkBlackTopHatImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkBlackTopHatImageFilter.hxx, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleDilateImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleDilateImageFilter.hxx, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleErodeImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleErodeImageFilter.hxx, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalClosingImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalClosingImageFilter.hxx, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalOpeningImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkGrayscaleMorphologicalOpeningImageFilter.hxx, Modules/Filtering/MathematicalMorphology/include/itkMathematicalMorphologyEnums.h, Modules/Filtering/MathematicalMorphology/include/itkMorphologicalGradientImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkMorphologicalGradientImageFilter.hxx, Modules/Filtering/MathematicalMorphology/include/itkWhiteTopHatImageFilter.h, Modules/Filtering/MathematicalMorphology/include/itkWhiteTopHatImageFilter.hxx, Modules/Filtering/MathematicalMorphology/itk-module.cmake, Modules/Filtering/MathematicalMorphology/src/CMakeLists.txt, Modules/Filtering/MathematicalMorphology/src/itkMathematicalMorphologyEnums.cxx, Modules/Filtering/MathematicalMorphology/test/itkGrayscaleDilateImageFilterTest.cxx, Modules/Filtering/MathematicalMorphology/test/itkGrayscaleErodeImageFilterTest.cxx, Modules/Filtering/MathematicalMorphology/test/itkGrayscaleMorphologicalClosingImageFilterTest2.cxx, Modules/Filtering/MathematicalMorphology/test/itkMapGrayscaleDilateImageFilterTest.cxx, Modules/Filtering/MathematicalMorphology/test/itkMapGrayscaleErodeImageFilterTest.cxx, Modules/Filtering/MathematicalMorphology/test/itkMapGrayscaleMorphologicalClosingImageFilterTest.cxx, Modules/Filtering/MathematicalMorphology/test/itkMapGrayscaleMorphologicalOpeningImageFilterTest.cxx, Modules/Filtering/MathematicalMorphology/test/itkMorphologicalGradientImageFilterTest2.cxx, Modules/Filtering/MathematicalMorphology/test/itkTopHatImageFilterTest.cxx, Modules/Filtering/MathematicalMorphology/wrapping/itkMathematicalMorphologyEnums.wrap
Use strongly typed enums for the `Algorithm` type in math morphology.
=> ENH: Use strongly typed enums for the `Algorithm` type in math morphology

Modules/Numerics/Optimizersv4/test/itkAmoebaOptimizerv4Test.cxx, Modules/Numerics/Optimizersv4/test/itkConjugateGradientLineSearchOptimizerv4Test.cxx, Modules/Numerics/Optimizersv4/test/itkExhaustiveOptimizerv4Test.cxx, Modules/Numerics/Optimizersv4/test/itkGradientDescentLineSearchOptimizerv4Test.cxx, Modules/Numerics/Optimizersv4/test/itkGradientDescentOptimizerBasev4Test.cxx, Modules/Numerics/Optimizersv4/test/itkGradientDescentOptimizerv4Test.cxx, Modules/Numerics/Optimizersv4/test/itkGradientDescentOptimizerv4Test2.cxx, Modules/Numerics/Optimizersv4/test/itkLBFGS2Optimizerv4Test.cxx, Modules/Numerics/Optimizersv4/test/itkLBFGSBOptimizerv4Test.cxx, Modules/Numerics/Optimizersv4/test/itkLBFGSOptimizerv4Test.cxx, Modules/Numerics/Optimizersv4/test/itkMultiGradientOptimizerv4Test.cxx, Modules/Numerics/Optimizersv4/test/itkMultiStartOptimizerv4Test.cxx, Modules/Numerics/Optimizersv4/test/itkObjectToObjectMetricBaseTest.cxx, Modules/Numerics/Optimizersv4/test/itkObjectToObjectOptimizerBaseTest.cxx, Modules/Numerics/Optimizersv4/test/itkOnePlusOneEvolutionaryOptimizerv4Test.cxx, Modules/Numerics/Optimizersv4/test/itkPowellOptimizerv4Test.cxx, Modules/Numerics/Optimizersv4/test/itkRegistrationParameterScalesEstimatorTest.cxx, Modules/Numerics/Optimizersv4/test/itkRegistrationParameterScalesFromIndexShiftTest.cxx, Modules/Numerics/Optimizersv4/test/itkRegistrationParameterScalesFromJacobianTest.cxx, Modules/Numerics/Optimizersv4/test/itkRegistrationParameterScalesFromPhysicalShiftTest.cxx, Modules/Numerics/Optimizersv4/test/itkRegularStepGradientDescentOptimizerv4Test.cxx, Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx
```
Modules/Numerics/Optimizersv4/test/itkObjectToObjectOptimizerBaseTest.cxx:95:16:
error: ISO C++17 does not allow dynamic exception specifications
95 |   Initialize() throw(itk::ExceptionObject) override
```
=> COMP: Remove dynamic exception specifications in tests

Modules/Core/Common/include/itkFrustumSpatialFunction.hxx, Modules/Nonunit/IntegratedTest/test/itkCommonPrintTest.cxx
`FrustumSpatialFunction` deals with a pyramid and doesn't really accept `VDimension < 3`.
However, it was used in itkCommonPrintTest with `VDimension = 2`,
raising a correct `-Warray-bounds` warning.
This fix:
- Add a static_assert to the Evaluate function.
- Change the print test to use `VDimension = 3`
Fix warning:
```
Building CXX object Modules/Nonunit/IntegratedTest/t...Files/ITKIntegratedTestTestDriver.dir/itkCommonPrintTest.cxx.o
In file included from Modules/Core/Common/include/itkFrustumSpatialFunction.h:147,
from Modules/Nonunit/IntegratedTest/test/itkCommonPrintTest.cxx:43:
Modules/Core/Common/include/itkFrustumSpatialFunction.hxx: In member function ‘itk::FrustumSpatialFunction<VDimension, TInput>::OutputType itk::FrustumSpatialFunction<VDimension, TInput>::Evaluate(const …
```
=> COMP: Avoid Dimension < 3 in FrustumSpatialFunction

Modules/Core/Common/include/itkPriorityQueueContainer.hxx
For some types, 0 won't do in the constructor.  Instead we need, e.g., `NumericTraits<TElement>::ZeroValue()`.  This will help Seg3D to compile.
=> BUG: MinPriorityQueueElementWrapper constructor needs ZeroValue()

Modules/Bridge/NumPy/wrapping/test/CMakeLists.txt, Modules/Bridge/NumPy/wrapping/test/itkImageMetaDataSetGetItem.py, Wrapping/Generators/Python/PyBase/pyBase.i
Provides a Python dictionary interface to image metadata, keys are
MetaDataDictionary entries along with 'origin', 'spacing', and
'direction' keys. The later reverse their order to be consistent with
the NumPy array index order resulting from array views of the image. The
entries can be accesses and set directly on the image, e.g.
print(image['0008|0008'])
image['origin'] = [4.0, 2.0, 2.0]
or a dictionary can be retrieved with:
meta_dict = dict(image)
For example:
```
In [3]: dict(image)
Out[3]:
{'0008|0005': 'ISO IR 100',
'0008|0008': 'ORIGINAL\\PRIMARY\\AXIAL',
'0008|0016': '1.2.840.10008.5.1.4.1.1.2',
'0008|0018': '1.3.12.2.1107.5.8.99.484849.834848.79844848.2001082217554549',
'0008|0020': '20010822',
'0008|0021': '20010822',
'0008|0022': '20010822',
'0008|0023': '20010822', …
```
=> ENH: Add Image dict and pixel set/get Python interfaces

Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshBaseIterator.h
C++17 related warning.
Solved adding a default copy constructor.
```
Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshBaseIterator.h:304:7: warning: implicitly-declared ‘constexpr itk::QuadEdgeMeshBaseIterator<itk::GeometricalQuadEdge<long unsigned int, long unsigned int, bool, bool, true> >::QuadEdgeMeshBaseIterator(const itk::QuadEdgeMeshBaseIterator<itk::GeometricalQuadEdge<long unsigned int, long unsigned int, bool, bool, true> >&)’ is deprecated [-Wdeprecated-copy]
304 | class QuadEdgeMeshConstIterator : public QuadEdgeMeshBaseIterator<TQuadEdge>
```
=> COMP: Fix warning -Wdeprecated-copy in itkQuadEdgeMeshBaseIterator

Modules/Core/Common/include/itkConstSliceIterator.h, Modules/Core/Common/include/itkExceptionObject.h, Modules/Core/Common/include/itkSliceIterator.h, Modules/Core/Common/src/itkExceptionObject.cxx, Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshFrontIterator.h, Modules/Numerics/Statistics/include/itkHistogram.h, Modules/Numerics/Statistics/include/itkImageToListSampleAdaptor.h, Modules/Numerics/Statistics/include/itkImageToNeighborhoodSampleAdaptor.h, Modules/Numerics/Statistics/include/itkJointDomainImageToListSampleAdaptor.h, Modules/Numerics/Statistics/include/itkListSample.h, Modules/Numerics/Statistics/include/itkMembershipSample.h, Modules/Numerics/Statistics/include/itkPointSetToListSampleAdaptor.h, Modules/Numerics/Statistics/include/itkSubsample.h, Modules/Numerics/Statistics/include/itkVectorContainerToListSampleAdaptor.h
Fix ambiguous overloaded operator != triggered in Apple Clang 12.
Reported here: https://discourse.itk.org/t/c-20-comparison-operators/3506
```
ITK-5.1/itkImageToHistogramFilter.hxx:294:18: error: use of overloaded operator '!=' is ambiguous (with operand types 'HistogramIterator' (aka 'itk::Statistics::Histogram<double, itk::Statistics::DenseFrequencyContainer2>::ConstIterator') and 'HistogramIterator')
while (hit != end)
~~~ ^  ~~~
vcpkg_installed/x64-osx-asan/include/ITK-5.1/itkHistogram.h:405:5: note: candidate function
operator!=(const ConstIterator & it)
^
vcpkg_installed/x64-osx-asan/include/ITK-5.1/itkHistogram.h:411:5: note: candidate function
operator==(const ConstIterator & it)
```
- [ x ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING …
=> COMP: Fix const-correctness of iterators in multiple classes

CMake/ITKModuleTest.cmake, Wrapping/Generators/Python/CMakeLists.txt, Wrapping/Generators/Python/WrapITK.pth.in
For multi-configuration CMake generators, e.g. Visual Studio, all Python
package related files are placed with the package layout into
ITK-build/Wrapping/Generators/Python/${config} where ${config} is the
configuration, e.g. Release or Debug.
=> ENH: Support Python debugging with Visual Studio

Wrapping/Generators/Python/CMakeLists.txt
Fix for ```LINK : fatal error LNK1104: cannot open file 'python38.lib'``` when using Python Wrapping with MSVC in VS2019 and CMake >=3.18.
Closes #2049
=> BUG: Fix Python Wrapping with MSVC and CMake >= 3.18, Closes #2049

Modules/Filtering/ImageGrid/test/itkPasteImageFilterGTest.cxx
Fix missing initialization braces warnings.
Fixes:
```
/Users/builder/externalModules/Filtering/ImageGrid/test/itkPasteImageFilterGTest.cxx:121:33:
warning: suggest braces around initialization of subobject
[-Wmissing-braces]
filter->SetDestinationIndex({ 11, 13 });
^~~~~~
{     }
```
and warnings of the same kind reported at:
https://open.cdash.org/viewBuildError.php?type=1&buildid=6799229
=> COMP: Fix missing initialization braces warnings

Wrapping/Generators/Python/Tests/lazy.py, Wrapping/Generators/Python/Tests/nolazy.py, Wrapping/Generators/Python/itkLazy.py
Recent refactorings broke the ability
to pickle the itk module.  Name change
missed refactoring fixed.
=> BUG: Pickling of itk module was broken
