- .git-blame-ignore-revs
> ENH: Ignore more bulk changes for git blame

- Modules/Remote/GrowCut.remote.cmake
- Modules/Remote/HASI.remote.cmake
> Add HASI and GrowCut remote modules

- Modules/ThirdParty/VNL/src/vxl/CMakeLists.txt
- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_matrix.cxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_matrix_fixed.cxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.hxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix_fixed.hxx
- Modules/ThirdParty/VNL/src/vxl/vcl/CMakeLists.txt
- Modules/ThirdParty/VNL/src/vxl/vcl/compilers/VXL_COMPILER_INFO_AppleClang_CXX.h
- Modules/ThirdParty/VNL/src/vxl/vcl/compilers/VXL_COMPILER_INFO_Clang_CXX.h
- Modules/ThirdParty/VNL/src/vxl/vcl/compilers/VXL_COMPILER_INFO_GNU_CXX.h
- Modules/ThirdParty/VNL/src/vxl/vcl/compilers/VXL_COMPILER_INFO_Intel_CXX.h
- Modules/ThirdParty/VNL/src/vxl/vcl/compilers/VXL_COMPILER_INFO_MSVC_CXX.h
- Modules/ThirdParty/VNL/src/vxl/vcl/compilers/VXL_COMPILER_INFO_SunPro_CXX.h
- Modules/ThirdParty/VNL/src/vxl/vcl/vcl_compiler.h.in
- Modules/ThirdParty/VNL/src/vxl/vcl/vcl_compiler_detection.h
vxl/vxl.git
at commit d8888fd569207d21a634bd998401143c714810d5 (master).
> Update VNL to 2021-07-15 (d8888fd5)

- Modules/Core/Common/include/itkBufferedImageNeighborhoodPixelAccessPolicy.h
- Modules/Core/Common/include/itkConnectedImageNeighborhoodShape.h
- Modules/Core/Common/include/itkConstantBoundaryImageNeighborhoodPixelAccessPolicy.h
- Modules/Core/Common/include/itkImageBufferRange.h
- Modules/Core/Common/include/itkImageRegion.h
- Modules/Core/Common/include/itkImageRegionRange.h
- Modules/Core/Common/include/itkIndexRange.h
- Modules/Core/Common/include/itkMapContainer.h
- Modules/Core/Common/include/itkMath.h
- Modules/Core/Common/include/itkNeighborhoodAllocator.h
- Modules/Core/Common/include/itkRectangularImageNeighborhoodShape.h
- Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h
- Modules/Core/Common/include/itkVectorContainer.h
- Modules/Core/Common/include/itkZeroFluxNeumannImageNeighborhoodPixelAccessPolicy.h
- Modules/Core/Common/test/itkCommonTypeTraitsGTest.cxx
- Modules/Core/Common/test/itkImageNeighborhoodOffsetsGTest.cxx
- Modules/Core/Common/test/itkNeighborhoodAllocatorGTest.cxx
- Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.h
This is final completion of work dependant on #2573
> Cmake320policies use language directly Extends #2573 

- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_math.cxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_na.cxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_quaternion.cxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_rational.cxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_rotation_matrix.cxx
https://github.com/vxl/vxl.git
at commit 22f874db61407f087795521884a0c407274b789d (master).
Closes #2651.
> Update VNL to 2021-07-19 (22f874db)

- Modules/Core/Common/include/itkMacro.h
> COMP: directly use [[deprecated]] in itkLegacyMacro - C++14 allows that

- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaArrow.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaBlob.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaContour.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaDTITube.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaEllipse.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaFEMObject.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaGaussian.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaGroup.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaImage.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaLandmark.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaLine.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaMesh.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaScene.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaSurface.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaTransform.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaTube.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaTubeGraph.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaUtils.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaUtils.h
> ENH: Bump `MetaIO`

- Modules/Numerics/Optimizersv4/include/itkExhaustiveOptimizerv4.h
- Modules/Numerics/Optimizersv4/include/itkExhaustiveOptimizerv4.hxx
> Updates of ExhaustiveOptimizerv4

- Modules/IO/Meta/test/CMakeLists.txt
- Modules/IO/TIFF/test/CMakeLists.txt
- Modules/Registration/Common/test/RegistrationITKv3/test/CMakeLists.txt
- Modules/Registration/RegistrationMethodsv4/test/CMakeLists.txt
> ENH: Made a few slow tests run serially, so they won't timeout

- Modules/Filtering/DistanceMap/test/CMakeLists.txt
- Modules/Filtering/DistanceMap/test/itkDirectedHausdorffDistanceImageFilterTest1.cxx
- Modules/Filtering/DistanceMap/test/itkDirectedHausdorffDistanceImageFilterTest2.cxx
ENH: Split Hausdorff distance test
Resolves #2445
The test `itkHausdorffDistanceImageFilterTest` previously covered two classes, `HausdorffDistanceImageFilter` and `DirectedHausdorffDistanceImageFilter`.
The `DirectedHausdorffDistanceImageFilter` have been split off into a new test, `itkDirectedHausdorffDistanceImageFilterTest1`.
The test formerly named `itkDirectedHausdorffDistanceImageFilterTest` is now called `itkDirectedHausdorffDistanceImageFilterTest2`.
The latter test is sort of trivial, but covers slightly different aspects of `DirectedHausdorffDistanceImageFilter` and so it may be worth keeping. I simplified its code a bit, so that it doesn't appear to promise to test more than what it actually does.
As for the output file of `itkDirectedHausdorffDistanceImageFilterTest2`, it …
> ENH: Split Hausdorff distance test

- Wrapping/Generators/Python/PyBase/pyBase.i
Fixes #2705.  Calls to PySequence_GetItem have been updated in pyBase.i to decrement the reference count correctly.
> BUG: fixed reference leak when SWIG passing tuples or lists

- Modules/Core/ImageFunction/test/itkLinearInterpolateImageFunctionTest.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest.h
- Modules/IO/NIFTI/test/itkNiftiImageIOTest3.cxx
- Modules/ThirdParty/NIFTI/src/nifti/CMakeLists.txt
> Minor fixes

- Modules/Remote/Shape.remote.cmake
Adds [`ITKShape`](https://github.com/slicersalt/itkshape) as a remote module to be built with ITK as requested by @thewtex .
Note that pending [Issue 22](https://github.com/slicersalt/ITKShape/issues/22) the module will build under the CMake project name `Mesh3DProcrustesAlignFilter` (its original name).
Closes https://github.com/slicersalt/ITKShape/issues/22.
> ENH: Add ITKShape as a remote module

- Modules/Core/Common/include/itkLoggerBase.h
- Modules/Core/Common/include/itkLoggerThreadWrapper.h
- Modules/Core/Common/include/itkLoggerThreadWrapper.hxx
- Modules/Core/Common/include/itkThreadLogger.h
- Modules/Core/Common/src/itkLoggerBase.cxx
- Modules/Core/Common/src/itkThreadLogger.cxx
- Modules/Core/FiniteDifference/include/itkDenseFiniteDifferenceImageFilter.hxx
- Modules/Core/GPUFiniteDifference/include/itkGPUDenseFiniteDifferenceImageFilter.hxx
- Modules/IO/GDCM/test/itkGDCMImageIOTest2.cxx
> TSan fixes

- Modules/ThirdParty/MetaIO/UpdateFromUpstream.sh
- Modules/ThirdParty/MetaIO/src/MetaIO/.gitattributes
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaObject.cxx
- Utilities/Maintenance/update-third-party.bash
@codeling The script runs on Linux without major deletions but still does not seem to work properly.
>  MetaIO: Update to 2021-09-28 (5e87f062) 

- .github/labeler.yml
- ENH: Add further regexes for the issue/PR labeler
- STYLE: Sort the infrastructure regexes in labeler dictionary
> ENH: Add further label regexes for labeler

- Modules/Core/Common/include/itkNeighborhood.h
Remove duplicate, commented implementation file manual instantiation
guard.
> STYLE: Remove unnecessary implementation file manual instantiation guard

- Modules/Core/Common/src/itkPoolMultiThreader.cxx
- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkMultiThreaderExceptionsTest.cxx
Exception thrown in most threads were not caught. Fixes #2776.
> BUG: fix exception handling in itk::PoolMultiThreader

- CMake/InsightValgrind-Ubuntu2004.supp
The CloneFileContent function was moved to the SystemTools class,
update the existing suppression for this.
> COMP: Update suppress for KWSYS change

- CMake/FindFFTW.cmake
Small update to how we find the Intel Math Kernel Library on systems (when requested by the user):
- The default Windows installation path appears to have changed when MKL is installed from [https://www.intel.com/content/www/us/en/develop/documentation/oneapi-programming-guide/top/api-based-programming/intel-oneapi-math-kernel-library-onemkl.html](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-programming-guide/top/api-based-programming/intel-oneapi-math-kernel-library-onemkl.html).
- `FFTW_INCLUDE_PATH` is now prioritized in defining the search path if the user supplies it at the command line. Note that we assume the path structure `<mkl>/include/fftw` which is supported by existing logic in [Line 48](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CMake …
> ENH: Update Windows MKL path and prioritize user path if supplied

- Modules/Remote/CudaCommon.remote.cmake
Follows the discourse discussion https://discourse.itk.org/t/external-module-bypass-itkdata/4202. We (@LucasGandel and I) have extracted from [RTK](https://github.com/SimonRit/RTK) the CudaCommon module (with git history), added a test and setup a Linux CI with a self-hosted agent. When this PR is merged and released, the corresponding code will be removed from RTK. We shall quickly add a Windows self-hosted agent and the python package for a specific Cuda version. Compliance level has been set to 3 since it's been used and tested for a long time in RTK but I don't mind unticking some things and downgrading it to level 2. cc @Thibault-Pelletier
> ENH: add CudaCommon remote module

- .circleci/config.yml
> ENH: CircleCI use large resource class

- Modules/Filtering/LabelMap/include/itkStatisticsLabelMapFilter.h
- Modules/Filtering/LabelMap/include/itkStatisticsLabelMapFilter.hxx
itkStatisticsLabelMapFilter.hxx(77): warning C4293: '<<': shift count
negative or too big, undefined behavior
> COMP: Fix bit shift overflow warning

- Modules/Core/Common/include/itkMultiThreaderBase.h
- Modules/Core/Common/include/itkThreadPool.h
- Modules/Core/Common/src/itkImageSourceCommon.cxx
- Modules/Core/Common/src/itkMultiThreaderBase.cxx
- Modules/Core/Common/src/itkSingleton.cxx
- Modules/Core/Common/src/itkThreadPool.cxx
> TSan fixes2

- Modules/Core/Common/test/itkBSplineInterpolationWeightFunctionTest.cxx
> Fix minor style

- Modules/Core/Common/include/itkConceptChecking.h
- Modules/Core/Common/include/itkMath.h
- Modules/Core/Common/include/itkNumericTraits.h
- Modules/Core/Common/include/itkNumericTraitsArrayPixel.h
- Modules/Core/Common/include/itkNumericTraitsCovariantVectorPixel.h
- Modules/Core/Common/include/itkNumericTraitsDiffusionTensor3DPixel.h
- Modules/Core/Common/include/itkNumericTraitsPointPixel.h
- Modules/Core/Common/include/itkNumericTraitsRGBAPixel.h
- Modules/Core/Common/include/itkNumericTraitsRGBPixel.h
- Modules/Core/Common/include/itkNumericTraitsStdVector.h
- Modules/Core/Common/include/itkNumericTraitsTensorPixel.h
- Modules/Core/Common/include/itkNumericTraitsVariableLengthVectorPixel.h
- Modules/Core/Common/include/itkNumericTraitsVectorPixel.h
- Modules/Core/Common/test/itkNumericTraitsTest.cxx
- Modules/Filtering/ImageFeature/include/itkUnsharpMaskImageFilter.hxx
- Modules/Filtering/ImageFeature/test/itkUnsharpMaskImageFilterTest.cxx
- Modules/Filtering/ImageFeature/test/itkUnsharpMaskImageFilterTestSimple.cxx
- Modules/Filtering/ImageIntensity/include/itkArithmeticOpsFunctors.h
- Modules/IO/ImageBase/include/itkConvertPixelBuffer.h
- Modules/IO/ImageBase/include/itkConvertPixelBuffer.hxx
- Modules/Segmentation/Watersheds/include/itkWatershedSegmenter.hxx
Prefer built-in C++11 language features for identifying signed types.
> Replace is integer

- Modules/Numerics/Optimizersv4/wrapping/itkConjugateGradientLineSearchOptimizerv4.wrap
- Modules/Numerics/Optimizersv4/wrapping/itkGradientDescentLineSearchOptimizerv4.wrap
Python wrapping for ConjugateGradientLineSearchOptimizerv4 needed to complete the Thin Shell Demons python pipeline.
Base class GradientDescentLineSearchOptimizerv4 wrapping also added in separate file.
- Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
> ENH: Adding python wrapping for ConjugateGradientLineSearchOptimizerv4

- Modules/Core/Common/src/itkMultiThreaderBase.cxx
Addresses the following compilation warnings with GNU 8.3.0:
ITK/Modules/Core/Common/src/itkMultiThreaderBase.cxx:513:55: warning:
declaration of 'using WorkUnitInfo = struct
itk::MultiThreaderBase::WorkUnitInfo' shadows a previous local
[-Wshadow]
ITK/Modules/Core/Common/src/itkMultiThreaderBase.cxx:568:55: warning:
declaration of 'using WorkUnitInfo = struct
itk::MultiThreaderBase::WorkUnitInfo' shadows a previous local
[-Wshadow]
> COMP: fix WorkUnitInfo shadow warning

- Modules/Core/Mesh/include/itkTriangleMeshCurvatureCalculator.h
- Modules/Core/Mesh/include/itkTriangleMeshCurvatureCalculator.hxx
- Modules/Core/Mesh/src/CMakeLists.txt
- Modules/Core/Mesh/src/itkTriangleMeshCurvatureCalculator.cxx
- Modules/Core/Mesh/test/CMakeLists.txt
- Modules/Core/Mesh/test/itkTriangleMeshCurvatureCalculatorTest.cxx
- Modules/Core/Mesh/wrapping/itkTriangleMeshCurvatureCalculator.wrap
Gaussian curvature is needed for Thin shell Demons. 
Designed it in a form of the Calculator Design Pattern to avoid creating new mesh as required in a Filter design pattern. 
Only the memory for the curvature data will be allocated. Curvature data is stored in the Double vector container.
Meshes with custom point data can also be supported this way.
Mean, Max, and Min curvature will be added later as they are not required for now.
Easy to extend this code for them.
> ENH: Adding Gaussian Curvature Calculator in ITK Mesh with tests

- Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.hxx
Removed `#if 1`, and the entire `#else ... #endif` block from the
definition of `BSplineInterpolateImageFunction` member functions,
`EvaluateAtContinuousIndex`, `EvaluateDerivativeAtContinuousIndex`,
and `EvaluateValueAndDerivativeAtContinuousIndex`.
These pieces of code have been there for reviewing purposes, from commit
6abbc7969a90786c4c73f5d191f634db536c2d1d "Made USE_OPTIMIZED_REGISTRATION the default",
Hans Johnson (@hjmjohnson), 6 August 2010. This review should be considered done by now.
The old code from the `#else ... #endif` blocks was no longer kept in
sync with the new code anyway.
> STYLE: Remove dead code (#else...#endif) BSplineInterpolateImageFunction

- Modules/Core/Mesh/include/itkTriangleMeshCurvatureCalculator.h
- Modules/Core/Mesh/test/itkTriangleMeshCurvatureCalculatorTest.cxx
To remove legacy code "itkGetObjectMacro should be replaced with itkGetModifiableObjectMacro or itkGetConstObjectMacro".
> COMP: Read Only access to GaussCurvatureData

- Modules/Registration/Common/include/itkImageToImageMetric.h
- Modules/Registration/Common/include/itkImageToImageMetric.hxx
Following C++ Core Guidelines, August 19, 2021:
"Use unique_ptr or shared_ptr to avoid forgetting to delete objects created using new"
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-smart
Defaulted (`= default`) its destructor.
> STYLE: Use `unique_ptr` for `ImageToImageMetric` data members

- Modules/Core/Common/include/itkImageBase.h
- Modules/Core/ImageAdaptors/include/itkImageAdaptor.h
- Modules/Core/Mesh/include/itkTriangleMeshToBinaryImageFilter.h
Fix typos and improve grammar.
> DOC: Fix typos and improve grammar

- CMake/ITKModuleHeaderTest.cmake
Use the more modern explicit keyword-style.
> STYLE: Use keyword style for HeaderTest target_link_libraries

- Modules/Registration/Metricsv4/test/itkImageToImageMetricv4Test.cxx
- ENH: Avoid setting a negative spacing to test exception
- DOC: Fix typo in comment
- ENH: Increase code coverage
> ENH: Avoid setting a negative spacing to test exception

- Modules/Registration/Common/include/itkGradientDifferenceImageToImageMetric.h
Remove declared but undefined method from
`itk::GradientDifferenceImageToImageMetric`.
Fixes:
```
Loading ITKRegistrationCommon... Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/vsts/work/1/s-build/Wrapping/Generators/Python/itk/support/lazy.py", line 137, in __getattribute__
base.itk_load_swig_module(module, namespace)
File "/home/vsts/work/1/s-build/Wrapping/Generators/Python/itk/support/base.py", line 102, in itk_load_swig_module
itk_load_swig_module(dep, namespace)
File "/home/vsts/work/1/s-build/Wrapping/Generators/Python/itk/support/base.py", line 110, in itk_load_swig_module
l_module = loader.load(swig_module_name)
File "/home/vsts/work/1/s-build/Wrapping/Generators/Python/itk/support/base.py", line 259, in load …
```
> BUG: Remove declared but undefined method

- Modules/Core/Common/include/itkImageBase.hxx
> BUG: negative spacing is not supported, but check did not enforce that

- Modules/Core/Mesh/include/itkMesh.hxx
- Modules/Core/Mesh/test/itkMeshCellDataTest.cxx
- STYLE: Move type declaration into itkMeshCellDataTest function
- BUG: Create CellData when requested in Mesh::GetCellData
> mesh default cell data

- Modules/Core/Common/include/itkMath.h
Break dependance of older vxl versions by directly providing newer vxl
version compatible implementations directly in ITK.
> COMP: Allow use of older system vxl

- Modules/Core/Common/src/itkConfigure.h.in
Rely instead on preprocesor flags __SSE2__ and _M_IX86_FP (microsoft).
> BUG: Do not unconditionally assume SSE2 when building on i386

- Modules/IO/Meta/src/itkMetaImageIO.cxx
This is a follow-up to 76ccfdcae1677bc1031594ea4fd100768e58379e.
> ENH: reduce code duplication by reusing code from ImageIOBase

- Modules/Core/Common/include/itkMacro.h
- Modules/Core/Common/include/itkMultiThreaderBase.h
> Reserved identifier

- Wrapping/Generators/Python/Tests/extras.py
- Wrapping/Generators/Python/itk/support/extras.py
fixes #2972 
adds a `np.asarray` step to `GetMatrixFromArray` if needed 
> ENH: GetMatrixFromArray to accept ArrayLike sequences

- Modules/IO/MeshBase/include/itkMeshFileReader.h
- Modules/IO/MeshBase/include/itkMeshFileWriter.h
- Modules/IO/MeshBase/test/CMakeLists.txt
- Modules/IO/MeshBase/test/itkMeshFileReaderTest.cxx
- Modules/IO/MeshBase/test/itkMeshFileReaderWriterTest.cxx
- ENH: Add itk::ReadMesh
- ENH: Add itk::WriteMesh
> mesh read write

- Modules/Registration/RegistrationMethodsv4/wrapping/itkImageRegistrationMethodv4.wrap
- Modules/Registration/RegistrationMethodsv4/wrapping/itkSyNImageRegistrationMethod.wrap
- Wrapping/Generators/SwigInterface/igenerator.py
Needed for ThinShellDemons Registration. Example usage are added in the ITKThinShellDemons repo.
> ENH: Adding Python Wrapping for SyNImageRegistrationMethod for Mesh

- Modules/Filtering/DisplacementField/include/itkInvertDisplacementFieldImageFilter.h
- Modules/Filtering/DisplacementField/test/CMakeLists.txt
- Modules/Filtering/DisplacementField/test/itkInvertDisplacementFieldImageFilterTest.cxx
- Modules/Filtering/DistanceMap/include/itkContourMeanDistanceImageFilter.h
- Modules/Filtering/DistanceMap/test/CMakeLists.txt
- Modules/Filtering/DistanceMap/test/itkContourMeanDistanceImageFilterTest.cxx
- Modules/Filtering/ImageFeature/include/itkHessianRecursiveGaussianImageFilter.h
- Modules/Filtering/ImageFeature/test/CMakeLists.txt
- Modules/Filtering/ImageFeature/test/itkHessianRecursiveGaussianFilterTest.cxx
- Modules/Filtering/ImageGradient/include/itkGradientMagnitudeRecursiveGaussianImageFilter.h
- Modules/Filtering/ImageGradient/test/CMakeLists.txt
- Modules/Filtering/ImageGradient/test/itkGradientMagnitudeRecursiveGaussianFilterTest.cxx
Add boolean macros to miscellaneous boolean ivars.
Exercise the boolean macros and the boolean ivar Set/Get methods.
> ENH: Add boolean macros to miscellaneous boolean ivars

- Modules/IO/JPEG/src/itkJPEGImageIO.cxx
The warning was triggered by GCC 7.4.1
warning: variable ‘num_comp’ might be clobbered by ‘longjmp’ or ‘vfork’
[-Wclobbered]
See
https://my.cdash.org/viewBuildError.php?type=1&buildid=2111692
> COMP: fix warning triggered by setjmp

- Modules/Core/Mesh/include/itkConnectedRegionsMeshFilter.h
- Modules/Core/Mesh/include/itkConnectedRegionsMeshFilter.hxx
itkConnectedRegionsMeshFilter was giving 0 connected components as **m_RegionList** list was 
not used while propagating.
Also when cells are extracted in **SpecifiedRegions** mode, flag for checking the region id is not reset which caused cells from other regions getting extracted.
Fixes #3023.
> BUG: Fix for incorrect cell extraction in itkConnectedRegionsMeshFilter

- Wrapping/Generators/Python/itk/support/helpers.py
A string pixel identifier and size-identifying component type is used
during serialization, consistent with itk-wasm.
> ENH: Use literate identifiers in Dask serialization.

- CMake/UseITK.cmake
Generate FFT factory register manager when
ITK_NO_IO_FACTORY_REGISTER_MANAGER is set to 1.
> BUG: Enable using only FFT Factory Register Manager

- Modules/IO/ImageBase/include/itkStreamingImageIOBase.h
- Modules/IO/VTK/include/itkVTKImageIO.h
Fix Insight Journal reference typos.
> DOC: Fix Insight Journal reference typos

- CMake/itkApple.cmake
Modern CMake now has such an option itself.
> COMP: removed obsolete option for Objective-C++ flags

- Modules/Filtering/LabelMap/include/itkLabelMapToLabelImageFilter.h
- Modules/Filtering/LabelMap/include/itkLabelMapToLabelImageFilter.hxx
> ENH: Simplify LabelMapToLabelImageFilter slightly

- Modules/Filtering/FFT/itk-module.cmake
- Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
Explicitly adds ITKImageIntensity as a test dependency of ITKFFT to resolve Windows Python failure where `itk.ComplexToRealImageFilter` is not found after building ITKCommon (see #3057).
> COMP: Enable filtering group for Windows Python CI

- Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
For windows Python CI adding ITKThresholding module.
> ENH: Adding Module dependency for Windows Python CI

- Modules/Filtering/Thresholding/include/itkThresholdLabelerImageFilter.h
> PERF: Use binary search for threshold in ThresholdLabelerImageFilter

- Modules/Core/TestKernel/src/itkTestDriver.cxx
- Modules/Core/TestKernel/src/itkTestDriverInclude.cxx
- Modules/Core/TestKernel/src/itkTestDriverIncludeRequiredFactories.cxx
- Modules/Filtering/AnisotropicSmoothing/test/itkGradientAnisotropicDiffusionImageFilterTest2.cxx
- Modules/Filtering/ImageFeature/test/itkBilateralImageFilterTest2.cxx
- Modules/Filtering/ImageFeature/test/itkBilateralImageFilterTest3.cxx
- Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest2.cxx
- Modules/Filtering/ImageGradient/test/itkVectorGradientMagnitudeImageFilterTest3.cxx
- Modules/Filtering/MathematicalMorphology/test/itkGrayscaleMorphologicalClosingImageFilterTest2.cxx
- Modules/Filtering/MathematicalMorphology/test/itkGrayscaleMorphologicalOpeningImageFilterTest2.cxx
- Modules/IO/ImageBase/test/itkImageFileReaderTest1.cxx
- Modules/IO/ImageBase/test/itkImageFileWriterTest2.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest.h
- Modules/IO/NIFTI/test/itkNiftiImageIOTest10.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest11.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest12.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest2.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest3.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest4.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest5.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest6.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest7.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest8.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest9.cxx
- Modules/Nonunit/Review/test/itkFastApproximateRankImageFilterTest.cxx
- Modules/Numerics/FEM/test/itkFEMElementTest.cxx
- Modules/Numerics/FEM/test/itkFEMSolverHyperbolicTest.cxx
> STYLE: Standardize parameter names to argc and *argv[], replace ac/av

- Modules/Core/Common/test/itkSTLThreadTest.cxx
- Modules/Registration/Metricsv4/include/itkANTSNeighborhoodCorrelationImageToImageMetricv4GetValueAndDerivativeThreader.h
- Modules/Registration/Metricsv4/include/itkANTSNeighborhoodCorrelationImageToImageMetricv4GetValueAndDerivativeThreader.hxx
- Modules/Segmentation/LevelSetsv4/include/itkLevelSetEquationTermContainer.h
- Modules/Segmentation/LevelSetsv4/include/itkLevelSetEquationTermContainer.hxx
> TSan-fixes4

- Modules/Core/Mesh/include/itkImageToParametricSpaceFilter.h
- Modules/Core/Mesh/test/itkImageToParametricSpaceFilterTest.cxx
- Modules/Core/TestKernel/include/itkTestingComparisonImageFilter.h
- Modules/Filtering/ImageCompare/test/CMakeLists.txt
- Modules/Filtering/ImageCompare/test/itkTestingComparisonImageFilterTest.cxx
- Modules/Numerics/Optimizers/include/itkFRPROptimizer.h
- Modules/Numerics/Optimizers/test/itkFRPROptimizerTest.cxx
- Modules/Numerics/Optimizersv4/include/itkOnePlusOneEvolutionaryOptimizerv4.h
- Modules/Numerics/Optimizersv4/include/itkPowellOptimizerv4.h
- Modules/Numerics/Optimizersv4/test/CMakeLists.txt
- Modules/Numerics/Optimizersv4/test/itkOnePlusOneEvolutionaryOptimizerv4Test.cxx
- Modules/Numerics/Optimizersv4/test/itkPowellOptimizerv4Test.cxx
Add missing getter/boolean macro methods to boolean ivars across
miscellaneous classes.
> ENH: Add missing getter/boolean macro methods

- Modules/ThirdParty/HDF5/src/itkhdf5/config/cmake_ext_mod/HDFMacros.cmake
Submitted upstream: https://github.com/HDFGroup/hdf5/pull/1380
> BUG: Do not let HDF5 set the CMAKE_INSTALL_PREFIX

- Modules/ThirdParty/HDF5/src/itkhdf5/c++/src/H5Location.h
I have a patch pending for upstream HDF5 too.
> COMP: added override keyword on a dtor

- Wrapping/Generators/Python/CMakeLists.txt
- Wrapping/Generators/Python/PyBase/pyBase.i
- Wrapping/Generators/Python/PyUtils/itkPyImageFilter.h
- Wrapping/Generators/Python/PyUtils/itkPyImageFilter.hxx
- Wrapping/Generators/Python/PyUtils/itkPyImageFilter.wrap
- Wrapping/Generators/Python/Tests/CMakeLists.txt
- Wrapping/Generators/Python/Tests/PyImageFilterTest.py
- ENH: Wrap PyImageFilter for all wrapped scalar pixel types
- ENH: Pass in the class instance to the PyImageFilter PyGenerateData
- ENH: Add SetPyGenerateInputRequestedRegino to PyImageFilter
> py image filter self

- Wrapping/Generators/Python/PyUtils/itkPyImageFilter.h
- Wrapping/Generators/Python/PyUtils/itkPyImageFilter.hxx
- Wrapping/Generators/Python/Tests/PyImageFilterTest.py
- ENH: Add SetPyGenerateOutputInformation to PyImageFilter
- ENH: Add SetPyEnlargeOutputRequestedRegion to PyImageFilter
> py image filter update output information

- Examples/RegistrationITKv4/ImageRegistration5.py
- Modules/Core/Mesh/wrapping/test/itkMeshArrayPixelTypeTest.py
- Modules/Filtering/ImageGrid/wrapping/test/ResampleImageFilterTest.py
- Utilities/Doxygen/datetime.py
- Utilities/Maintenance/BuildHeaderTest.py
- Wrapping/Generators/Python/Tests/PyImageFilterTest.py
- Wrapping/Generators/Python/Tests/PythonTypeTest.py
- Wrapping/Generators/Python/Tests/extras.py
- Wrapping/Generators/Python/itk/__init__.py
- Wrapping/Generators/Python/itk/support/base.py
- Wrapping/Generators/Python/itk/support/extras.py
- Wrapping/Generators/Python/itk/support/helpers.py
- Wrapping/Generators/SwigInterface/igenerator.py
Apply `black` command, with no command line parameters, to each Python file.
> STYLE: Apply `black` Python formatting.

- Modules/Numerics/Optimizers/include/itkExhaustiveOptimizer.h
- Modules/Numerics/Optimizers/src/itkExhaustiveOptimizer.cxx
- Modules/Numerics/Optimizers/src/itkGradientDescentOptimizer.cxx
- Modules/Numerics/Optimizers/src/itkRegularStepGradientDescentBaseOptimizer.cxx
- Modules/Numerics/Optimizers/src/itkSPSAOptimizer.cxx
- Modules/Registration/Common/include/itkHistogramImageToImageMetric.hxx
- Modules/Registration/Common/include/itkMatchCardinalityImageToImageMetric.hxx
Follow-up to pull request #3102 and pull request #3118, both by Jon Haitz Legarreta Gorroño (@jhlegarreta).
> STYLE: In-class default member initializers for ExhaustiveOptimizer data

- Modules/Remote/TubeTK.remote.cmake
ITKTubeTK v 1.1rc01
=============
Supports CTP processing as used by https://github.com/KitwareMedical/ITKTubeTK-StrokeCollateralVessels
- Supports ITK 5.3rc03
- Improved radius estimation for vessels
- Vessel-based registration framework completed
- Had to refactor the ImageMath API due to memory constraints during wheel building.  ImageMath in python is now only templated over Input Image Type.  It is no longer has a second template argument for Output Image type.
- Python wrapping now supports 2D image registration (RegisterImages function)
* ENH: Upgrade wheels to use ITK53rc02 by @aylward in https://github.com/InsightSoftwareConsortium/ITKTubeTK/pull/92
* ENH: Provide a demo of manipulating the radius of tubes in python by @aylward in …
> ENH: Bump TubeTK to v1.1rc01 which is targeted for ITKv5.3rc03

- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
> STYLE: Fix typo in debug macro

- Examples/Segmentation/GeodesicActiveContourImageFilter.cxx
@thewtex if you have time to review
> STYLE: Wrong order of the arguments for the ITK book

- CMake/ITKModuleMacros.cmake
Resolves: #3168
This warning should not be possible when using ITK's targets:
ITK-5.3/itkConfigure.h:59:6: warning:
\#warning "WARNING:  The current project is configured to use a C++ standard version older than the C++ standard used for this build of ITK" [-Wcpp]
The CMake targets indicate that at least C++14 is required.
> COMP: Usage requirements should include C++14

- Utilities/Doxygen/itkgroup.pl
Fix many methods being documented in Doxygen with wrong strings.
The the processes performed in the itkgroup.pl is fixed to produce the
proper indents for the modified auto-groupings.
Co-authored-by: Dave Chen <dchen@mail.nih.gov>
> BUG: Fix bad doxygen strings

- Modules/ThirdParty/HDF5/src/itkhdf5/src/itk_hdf5_mangle.h
Building my own app against both vtk master and itk master results in link errors because both the libraries fail to mangle these 7 symbols.
> COMP: added missing HDF5 symbol mangling

- Modules/Video/BridgeOpenCV/CMakeLists.txt
Slicer was integrating OpenCV where ITK is built as shared and OpenCV built statically. This PR fixes build issues that were being observed. See the following discussion thread for more details. Hoping to have this included into the final ITK 5.3.
https://github.com/Slicer/SlicerOpenCV/pull/70#issuecomment-1034471469
Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
> COMP: Pass Windows specific OpenCV options to `ITKBridgeOpenCV`

- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
- Modules/IO/GDCM/test/itkGDCMImageOrientationPatientTest.cxx
The DICOM standard requires that "The row and column direction cosine
vectors shall be orthogonal, i.e., their dot product shall be
zero. The row and column direction cosine vectors shall be normal,
i.e., the dot product of each direction cosine vector with itself
shall be unity."
ITK images support arbitrary affine matrices as the direction
cosine. When they are not compliant with the DICOM requirements GDCM
write silently changes the direction cosine to be compliant. This
commit enforces the requirement in ITK so the user can choose if they want to
explicitly modify the matrix to comply with the DICOM requirements or
possibly write using a different format which supports affine matrices
for direction cosine. …
> BUG: GDCMImageIO accepted images with non-orthogonal direction cosine.

- .git-blame-ignore-revs
Add entry to `.git-blame-ignore-revs`.
> STYLE: Ignore git commit that is only STYLE

- Modules/Core/Common/include/itkSpatialOrientation.h
- Modules/Filtering/ImageGrid/include/itkOrientImageFilter.hxx
- Modules/IO/GE/src/itkGE4ImageIO.cxx
- Modules/IO/GE/src/itkGEAdwImageIO.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest4.cxx
- Modules/IO/NIFTI/test/itkNiftiReadAnalyzeTest.cxx
- Modules/IO/PhilipsREC/src/itkPhilipsRECImageIO.cxx
- Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx
> Follow-up to SpatialOrientationEnums refactoring

- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
- Modules/Segmentation/SuperPixel/test/itkSLICImageFilterGTest.cxx
Fixed to use a measurement vector of real type over the pixel
type. This issues was discovered in a SimpleITK test failing on a
linux ARM 64 system.
Co-authored-by: Dave Chen <dchen@mail.nih.gov>
> BUG: Fix numeric overflow in SLIC initialization

- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMParser.cxx
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMParser.h
> STYLE: ThirdParty Module DICOMParser, Member method DICOMParser::CloseFile added

- Modules/Remote/TubeTK.remote.cmake
Supports CTP processing as used by https://github.com/KitwareMedical/ITKTubeTK-StrokeCollateralVessels
- Supports ITK 5.3rc03
- Improved radius estimation for vessels
- Vessel-based registration framework completed
- Had to refactor the ImageMath API due to memory constraints during wheel building.  ImageMath in python is now only templated over Input Image Type.  It is no longer has a second template argument for Output Image type.
- Python wrapping now supports 2D image registration (RegisterImages function)
* ENH: Upgrade wheels to use ITK53rc02 by @aylward in https://github.com/InsightSoftwareConsortium/ITKTubeTK/pull/92
* ENH: Provide a demo of manipulating the radius of tubes in python by @aylward in https://github.com/InsightSoftwareConsortium/ITKTubeTK/pull/91
* ENH: Add support …
> ENH: Bump TubeTK to v1.1

- Modules/ThirdParty/DICOMParser/.clang-format
- Modules/ThirdParty/DICOMParser/src/DICOMParser/CMakeLists.txt
- Modules/ThirdParty/DICOMParser/src/DICOMParser/Copyright.txt
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMAppHelper.cxx
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMAppHelper.h
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMBuffer.cxx
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMBuffer.h
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMCallback.h
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMConfig.h
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMFile.cxx
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMFile.h
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMParser.cxx
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMParser.h
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMParserMap.h
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMSource.cxx
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMSource.h
- Modules/ThirdParty/DICOMParser/src/DICOMParser/DICOMTypes.h
This is an initial synchronization with VTK codebase of DICOMParser.  The two code bases have diverged, and each has bug fixes that are not captured in the other.
This PR only includes style changes that were identified when comparing the two code bases.
Future work should be done to bring both the VTK and the ITK versions of the code inline with each other.
See https://github.com/InsightSoftwareConsortium/ITK/issues/3233.
> STYLE: Synchronize with vtk codebase

- Modules/Filtering/GPUAnisotropicSmoothing/wrapping/test/itkGPUGradientAnisotropicDiffusionImageFilterTest.py
- Modules/Filtering/GPUImageFilterBase/wrapping/test/itkGPUNeighborhoodOperatorImageFilterTest.py
- Modules/Filtering/GPUSmoothing/wrapping/test/itkGPUMeanImageFilterTest.py
- Utilities/Doxygen/mcdoc.py
- Utilities/ITKv5Preparation/replaceClassWithTypename.py
- Utilities/Maintenance/ArchiveTestingDataOnAzure.py
- Utilities/Maintenance/ArchiveTestingDataOnGirder.py
- Utilities/Maintenance/AuthorsChangesSince.py
- Utilities/Maintenance/BuildHeaderTest.py
- Utilities/Maintenance/FindRedundantHeaderIncludes.py
- Utilities/Maintenance/JREUpdate.py
- Utilities/Maintenance/ParallelStripIncludes.py
- Utilities/Maintenance/StripIncludes.py
- Utilities/Maintenance/UpdateCopyrightStatementsInITK.py
- Utilities/Maintenance/VCL_ModernizeNaming.py
- Utilities/Maintenance/VNL_ModernizeNaming.py
- Utilities/Maintenance/VerifyURLs.py
- Utilities/Maintenance/VisualizeTestTimes.py
- Utilities/Maintenance/WhatModulesITK.py
- Wrapping/Generators/Python/Tests/PyImageFilterTest.py
- Wrapping/Generators/Python/Tests/returnedTypeCoverage.py
- Wrapping/Generators/Python/Tests/wrappingCoverage.py
- Wrapping/Generators/Python/itk/support/base.py
- Wrapping/Generators/Python/itk/support/extras.py
- Wrapping/Generators/Python/itk/support/helpers.py
- Wrapping/Generators/Python/itk/support/lazy.py
- Wrapping/Generators/Python/itk/support/template_class.py
- Wrapping/Generators/SwigInterface/igenerator.py
Created with
```sh
cd git/ITK
find . -name "*.py" | fgrep -v ThirdParty | xargs pyupgrade --py37-plus
git diff --name-only | xargs black
```
Replaces #3243.
> STYLE: Invoke pyupgrade --py37-plus on Python files

- Modules/Remote/BoneMorphometry.remote.cmake
- Modules/Remote/HASI.remote.cmake
- Modules/Remote/MorphologicalContourInterpolation.remote.cmake
- Modules/Remote/MultipleImageIterator.remote.cmake
- Modules/Remote/PhaseSymmetry.remote.cmake
- Modules/Remote/RTK.remote.cmake
- Modules/Remote/Strain.remote.cmake
- Modules/Remote/Ultrasound.remote.cmake
A few remote modules were updated recently.
> ENH: Updating remote modules using the script

- Modules/Filtering/FFT/include/itkFFTImageFilterFactory.h
Exposes parameters for input/output image types to use for FFT factory initialization overloads. This will allow FFT filters to define overrides over unconventional image types (`itk::SpecialCoordinatesImage`, etc).
Also adds clarifying documentation for `itk::FFTImageFilterFactory`.
> ENH: Expose FFT factory image template parameters

- Utilities/SetupForDevelopment.sh
f8badc3d66f782332e640b68a941d84541ebfa97 updated git hooks.
Bumping the version here to remind everyone to update.
Closes #3229.
> ENH: Git hooks were updated

- Modules/Filtering/DisplacementField/include/itkComposeDisplacementFieldsImageFilter.hxx
- Modules/Filtering/DisplacementField/include/itkGaussianExponentialDiffeomorphicTransform.hxx
- Modules/Filtering/DisplacementField/include/itkGaussianSmoothingOnUpdateDisplacementFieldTransform.hxx
- Modules/Filtering/DisplacementField/include/itkGaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform.hxx
- Modules/Filtering/DisplacementField/include/itkInvertDisplacementFieldImageFilter.hxx
- Modules/Filtering/DisplacementField/test/itkInvertDisplacementFieldImageFilterTest.cxx
- Modules/Filtering/QuadEdgeMeshFiltering/test/itkLaplacianDeformationQuadEdgeMeshFilterWithHardConstraintsTest.cxx
- Modules/Filtering/QuadEdgeMeshFiltering/test/itkLaplacianDeformationQuadEdgeMeshFilterWithSoftConstraintsTest.cxx
- Modules/Registration/Common/include/itkTimeVaryingBSplineVelocityFieldTransformParametersAdaptor.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkBSplineSyNImageRegistrationMethod.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkSyNImageRegistrationMethod.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkTimeVaryingBSplineVelocityFieldImageRegistrationMethod.hxx
- Modules/Registration/RegistrationMethodsv4/test/itkBSplineExponentialImageRegistrationTest.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkBSplineSyNImageRegistrationTest.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkBSplineSyNPointSetRegistrationTest.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkExponentialImageRegistrationTest.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkSimpleImageRegistrationTest.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkSimpleImageRegistrationTestWithMaskAndSampling.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkSyNImageRegistrationTest.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkSyNPointSetRegistrationTest.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkTimeVaryingBSplineVelocityFieldImageRegistrationTest.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkTimeVaryingBSplineVelocityFieldPointSetRegistrationTest.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkTimeVaryingVelocityFieldImageRegistrationTest.cxx
> Use constexpr zero vector

- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaImage.cxx
at commit 0b8c5284f3fe126968fd66c24639fd70b88e8788 (master).
> MetaIO 2022-03-10 (0b8c5284)

- Modules/IO/TIFF/src/itkTIFFImageIO.cxx
Enable LZW compression in TIFF images now that its patent has expired.
fixes #3277
> ENH: Enable LZW compression

- Wrapping/WrapITKTypes.cmake
Refer Issue# [3312](https://github.com/InsightSoftwareConsortium/ITK/issues/3312)
Warnings are seen in the Windows compiler with those additional wrappings for UL (for sign inversion-related code). 
On clean compilation, we find that those wrappings are not needed.
> COMP: Remove un-necessary wrapping to remove Windows warnings

- CMake/ExternalData.cmake
- CMake/ExternalData_config.cmake.in
- CMake/ITKExternalData.cmake
- Modules/Remote/WebAssemblyInterface.remote.cmake
- ENH: Add support for IPFS CID ExternalData content links
- ENH: Add WebAssemblyInterface remote module
> wasm remote

- Modules/Core/Common/include/itkPointSet.h
- Modules/Core/Common/test/itkBSplineInterpolationWeightFunctionTest.cxx
- Modules/Core/Common/test/itkPointSetTest.cxx
- Modules/Core/ImageFunction/test/itkMedianImageFunctionTest.cxx
- Modules/Core/ImageFunction/test/itkRayCastInterpolateImageFunctionTest.cxx
- Modules/Core/Mesh/test/CMakeLists.txt
- Modules/Core/Mesh/test/itkBinaryMask3DMeshSourceTest.cxx
- Modules/Core/Mesh/test/itkMeshTest.cxx
- Modules/Core/Mesh/test/itkRegularSphereMeshSourceTest.cxx
- Modules/Core/Mesh/test/itkTransformMeshFilterTest.cxx
- Modules/Core/Mesh/test/itkVTKPolyDataReaderTest.cxx
- Modules/Core/Mesh/test/itkVTKPolyDataWriterTest01.cxx
- Modules/Core/Mesh/test/itkVTKPolyDataWriterTest02.cxx
- Modules/Core/QuadEdgeMesh/test/CMakeLists.txt
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorSplitFaceTest.cxx
- Modules/Filtering/BiasCorrection/test/itkMRIBiasFieldCorrectionFilterTest.cxx
- Modules/IO/GDCM/test/itkGDCMImageReadSeriesWriteTest.cxx
- Modules/IO/XML/test/itkDOMTest1.cxx
- Modules/IO/XML/test/itkDOMTest2.cxx
- ENH: Remove unnecessary/unused include statements
- STYLE: Use the `itkNameOfTestExecutableMacro` macro in tests 
- STYLE: Prefer using `ITK_TRY_EXPECT_NO_EXCEPTION` macro in tests 
- STYLE: Improve style in tests
- ENH: Increase coverage for miscellaneous classes
- BUG: Set mesh to join facet function in split facet function test
- BUG: Fix Superclass name in RTTI macro
> ENH: Increase coverage for miscellaneous classes

- Modules/Core/Common/include/itkNumberToString.h
- Modules/Core/Common/src/itkArrayOutputSpecialization.cxx
- Modules/Core/Common/test/itkNumberToStringGTest.cxx
- Modules/IO/MeshBYU/include/itkBYUMeshIO.h
- Modules/IO/MeshBase/include/itkMeshIOBase.h
- Modules/IO/MeshOBJ/include/itkOBJMeshIO.h
- Modules/IO/MeshVTK/include/itkVTKPolyDataMeshIO.h
- Modules/IO/TransformInsightLegacy/src/itkTxtTransformIO.cxx
Offers full precision conversion from number to string, just like an `itk::NumberToString` function object, but having a convenient function interface, like `std::to_string`.
> Add `itk::ConvertNumberToString(val)` convenience function template

- Modules/Filtering/FastMarching/include/itkFastMarchingUpwindGradientImageFilter.h
- Modules/Filtering/FastMarching/test/itkFastMarchingUpwindGradientTest.cxx
- BUG: Set number of targets for FMUG image filter
- STYLE: Improve style in FMUG filter test file
> BUG: Set number of targets for FMUG image filter

- Modules/Core/Common/include/itkPointSet.h
- Modules/Core/Common/include/itkPointSet.hxx
- Modules/Core/Mesh/include/itkMesh.h
- Modules/Core/Mesh/include/itkMesh.hxx
- DOC: Document methods in header file
- STYLE: Remove unnecessary empty comment blocks
- ENH: Remove duplicate, commented `ITK_MANUAL_INSTANTIATION` guard
> DOC: Document methods in header file

- README.md
To resolve in PyPI package rendering.
> DOC: Use full URL logo in README

- Modules/Filtering/FastMarching/include/itkFastMarchingUpwindGradientImageFilter.h
- ENH: Remove unreachable condition in FMUG all target reached mode
- ENH: Refactor FMUG filter target reached mode verification
> ENH: Remove unreachable condition in FMUG all target reached mode

- Modules/Filtering/FastMarching/test/itkFastMarchingBaseTest.cxx
- Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterRealTest1.cxx
- Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterRealTest2.cxx
- STYLE: Add a missing parameter message in test
- STYLE: Improve the `itkFastMarchingBaseTest.cxx` style
- ENH: Increase `itk::FastMarchingBase` class coverage
> ENH: Increase `itk::FastMarchingBase` class coverage

- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkXMLFileOutputWindowTest.cxx
Increase `itk::XMLFileOutputWindow` class coverage.
> ENH: Increase `itk::XMLFileOutputWindow` class coverage

- Utilities/Doxygen/CMakeLists.txt
The DOXYGEN_INPUT variable had inconsistent mark up for elements. This
PR removes the mark up for DOXYGEN_INPUT and DOXYGE_TEST_DIRS, to
consistently allow the Doxygen CMake modules to handle the rendering
of list of string.
> BUG: Remove doxygen syntax markup for cmake lists

- Documentation/Doxygen/Geometry.dox
- Documentation/Doxygen/Modules.dox
- Documentation/Doxygen/Registration.dox
- DOC: Add `Writers` group to Doxygen documentation
- DOC: Prefer using ITK class names for syntax highlighting in Doxygen
- DOC: Fix typos and improve Doxygen related pages documentation
> DOC: Doxygen documentation related pages misc improvements

- Modules/Core/Common/include/itkMacro.h
This commit addresses a Slicer macOS build error reported on Discourse
(see https://discourse.slicer.org/t/slicer-build-on-macos-monterey/21940)
and on GitHub (see comments on issue Slicer/Slicer#5944).
The `_POSIX_SOURCE` preprocessor identifier is defined in several places
including by Python and several ITK ThirdParty modules. It looks like
this definition is causing unintended side effects when building `vtkITK`.
When `itkMacro.h` is #included in `vtkITK`, `_POSIX_SOURCE` causes conditional
inclusion of code using `__assert_fail` and `__ASSERT_FUNCTION`, which are
only defined on Linux and not on macOS. This results in a compile error.
This commit fixes the error by checking for the `__linux` preprocessor
identifier instead of `__POSIX_SOURCE`. …
> COMP: Fix Slicer vtkITK build on macOS

- Modules/Core/Common/test/itkXMLFileOutputWindowTest.cxx
Fix `itkXMLFileOutputWindowTest` regression: delete the contents of the
target file prior to writing new lines when no filename is given.
When no filename is provided, the `itk::XMLFileOutputWindow` class uses
a hard-coded filename to flush the buffer contents. If the CI builds do
not clean the target folder, as the append flag is set to `On`, lines
will be appended to the existing file, and the check on the written
lines will fail.
Removing the contents of the file is preferred over computing the
difference of the existing line count with respect to the new line
count, since the file will otherwise grow without bounds.
Fixes:
```
Error in numLinesRead == numLinesExpected
In ITK/Modules/Core/Common/test/itkXMLFileOutputWindowTest.cxx, line 86
lh: 47
rh: 7
Expression is not equal
``` …
> BUG: Fix `itkXMLFileOutputWindowTest` regression

- Modules/Remote/Cleaver.remote.cmake
ITK module wrapping Cleaver functionalities used for MultiMaterial
Tetrahedral Meshing.
Cleaver is a free multimaterial tetrahedral meshing tool developed by
the NIH Center for Integrative Biomedical Computing at the University of
Utah Scientific Computing and Imaging (SCI) Institute.
> ENH: Add Cleaver remote module

- Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.h
Delete non-virtual `DisplacementFieldTransform::SetDisplacementField(nullptr_t)` signature to address #3388.
Valid:
```
displacementFieldTrasnform->SetDisplacementField(static_cast<DisplacementFieldType *>(nullptr))
```
Invalid:
```
displacementFieldTransform->SetDisplacementField(nullptr);
```
results in the compiler error
>  error C2280: 'void itk::DisplacementFieldTransform<TParametersValueType,2>::SetDisplacementField(std::nullptr_t)': attempting to reference a deleted function
> BUG: Delete non-virtual function in DisplacementFieldTransform

- Modules/Remote/AnisotropicDiffusionLBR.remote.cmake
- Modules/Remote/Cleaver.remote.cmake
- Modules/Remote/MeshToPolyData.remote.cmake
- Modules/Remote/RTK.remote.cmake
- Modules/Remote/Shape.remote.cmake
- Modules/Remote/SphinxExamples.remote.cmake
- Modules/Remote/SplitComponents.remote.cmake
- Modules/Remote/Ultrasound.remote.cmake
- Modules/Remote/VkFFTBackend.remote.cmake
- Modules/Remote/WebAssemblyInterface.remote.cmake
- Utilities/Maintenance/UpdateRemoteModules.sh
* use authenticated Git protocol
* handle both master and main branches (closes #2699)
* update remotes to latest versions
> Improve UpdateRemoteModules.sh script

- Modules/Filtering/Convolution/include/itkFFTConvolutionImageFilter.hxx
Compilation errors (introduced by #3387) are only triggered with
ITK_FUTURE_LEGACY_REMOVE which does not seem to be set in any ITK CI.
> COMP: add missing trailing semicolon after itkExceptionMacro

- Wrapping/Generators/Python/itk/support/extras.py
First fixed parameters should be set and then parameters as
based on fixed parameters additional calculations are done.
TODO: Tests with real transforms need to be added.
> BUG: First set fixed parameters then parameters

- Wrapping/Generators/Python/itk/support/extras.py
The first cell was getting corrupted when de-serializing the mesh.
On de-bugging found that creating a copy was working fine always and the error was due to array_view.
The **root cause is not yet known**, but this approach solves the problem.
Should we replace array_view with the array at all places where dict is created ?
> BUG: Solves intermittent corrupted cells during de-serialization

- Modules/Filtering/Smoothing/include/itkDiscreteGaussianImageFilter.h
- Modules/Filtering/Smoothing/include/itkDiscreteGaussianImageFilter.hxx
- Modules/Filtering/Smoothing/test/itkDiscreteGaussianImageFilterTest.cxx
Exposes methods in `itk::DiscreteGaussianImageFilter` public interface
for getting details on the separable Gaussian kernel to be used in
smoothing. This is useful for handling cases such as image padding and
overlap for convolution.
Adapted from similar methods in derived class [https://github.com/InsightSoftwareConsortium/ITKVkFFTBackend/blob/master/include/itkVkDiscreteGaussianImageFilter.h#L122](https://github.com/InsightSoftwareConsortium/ITKVkFFTBackend/blob/master/include/itkVkDiscreteGaussianImageFilter.h#L122) that have proven useful in practice.
Note that `itk::DiscreteGaussianImageFilter` generates its own kernel internally from set user parameters including max kernel width, max error, and variance. Without these methods it is difficult to get insight into kernel size for …
> ENH: Add kernel helper methods to `itk::DiscreteGaussianImageFilter`

- Wrapping/Generators/Python/itk/support/extras.py
Similar to: https://github.com/InsightSoftwareConsortium/ITK/commit/d244d4bf71be396e6d0007f87a92b2e926230adf
> BUG: Prevent Image corruption in Dask serialization

- .git-blame-ignore-revs
> COMP: Add 9cd0f2053f0cf18 to .git-blame-ignore-revs

- Modules/Filtering/Smoothing/test/itkDiscreteGaussianImageFilterTest.cxx
> COMP: Resolve `itkDiscreteGaussianImageFilter` warnings

- Modules/Core/Common/wrapping/test/itkPointSetSerializationTest.py
- Modules/Core/Mesh/wrapping/test/itkMeshSerializationTest.py
- Wrapping/Generators/Python/itk/support/extras.py
- BUG: Add missing name to image_to_dict
- BUG: Remove extra dimension member from Mesh, PointSet dict's
> wasm dict members

- Modules/Remote/IOMeshSWC.remote.cmake
Read meshes from SWC files, a format for representing neuron morphology.
> ENH: Add IOMeshSWC remote module.

- Wrapping/CMakeLists.txt
- Wrapping/Generators/Python/itk/pyi_generator.py
- Wrapping/GlobalIdxFilesList.txt.in
- Wrapping/macro_files/itk_end_wrap_module.cmake
Work-in-progress for updating CMake wrapping build structure so that stub files are generated correctly.
Resolved so far:
- The `itk-stub-files` target command exceeded the maximum Windows command length (159,771 characters vs 8,192 allowed) and always failed with MSVC generator. This was the result of grouping .idx files for every ITK class together into one variable `GLOBAL_IdxFilesList`. The `index_files` argument is replaced with a `index_list_files` argument pointing to a file configured with CMake to have contents equivalent to the list of index files previously passed on the command line. This file is read into the `pyi_generator.py` script to allow execution to proceed as normal.
- `.pkl` and `.index.txt` files that existed in the build tree were not found by `pyi_generator.py` …
> COMP: Fix Python stub file generation on Windows

- Modules/Registration/Metricsv4/test/itkObjectToObjectMultiMetricv4Test.cxx
- Modules/Registration/PDEDeformable/test/itkMultiResolutionPDEDeformableRegistrationTest.cxx
- STYLE: Increase test style consistency 
- BUG: Match iterations array size value to number of levels
- ENH: Increase coverage for miscellaneous classes
> ENH: Increase coverage for registration classes

- Modules/Core/Common/wrapping/itkPointSet.wrap
- Modules/Registration/Common/wrapping/itkBlockMatchingImageFilter.wrap
Moving vector wrapping from itkBlockMatchingImageFilter.wrap to PointSet.wrap 
to consolidate PointSet wrapping in one place.
> ENH: Moving PointSet Vector wrapping to itkPointSet.wrap

- Documentation/Maintenance/Release.md
- Wrapping/macro_files/itk_auto_load_submodules.cmake
- BUG: Remove wrapping configuration loading debug statement
- DOC: Update Linux aarch Python wheel base image for manylinux_2_28
> wrapping manylinux 2 28

- Modules/Registration/Common/wrapping/itkPointsLocator.wrap
- Modules/Registration/Common/wrapping/test/CMakeLists.txt
- Modules/Registration/Common/wrapping/test/itkPointsLocatorTest.py
> ENH: Adding Python wrapping for itkPointsLocator

- Wrapping/ConfigureWrapping.cmake
- Wrapping/Generators/Python/PyBase/pyBase.i
- Wrapping/Generators/Python/Tests/PythonTypemapsTest.py
- Wrapping/Generators/Python/Tests/build_options.py
- Wrapping/Generators/Python/Tests/multiprocess_lazy_loading.py
- Wrapping/Generators/Python/Tests/returnedTypeCoverage.py
- Wrapping/Generators/Python/Tests/simple_pipeline.py
- Wrapping/Generators/Python/Tests/wrappingCoverage.py
- Wrapping/Generators/Python/itk/__init__.py
- Wrapping/Generators/Python/itk/pyi_generator.py
- Wrapping/Generators/Python/itk/support/extras.py
- Wrapping/Generators/Python/itk/support/lazy.py
- Wrapping/Generators/Python/itk/support/template_class.py
- Wrapping/Generators/SwigInterface/igenerator.py
- Wrapping/TypedefMacros.cmake
- Wrapping/WrappingOptions.cmake
Found via `codespell -q 3 -S ./Modules/ThirdParty,./Documentation/ReleaseNotes -L inout`
> DOC: Fix typos in `Wrapping/` subdirectory

- Modules/Filtering/ImageStatistics/include/itkLabelOverlapMeasuresImageFilter.h
- Modules/Filtering/ImageStatistics/include/itkLabelOverlapMeasuresImageFilter.hxx
- Modules/Filtering/ImageStatistics/test/CMakeLists.txt
- Modules/Filtering/ImageStatistics/test/itkLabelOverlapMeasuresImageFilterGTest.cxx
- Modules/Filtering/ImageStatistics/test/itkLabelOverlapMeasuresImageFilterTest.cxx
> Label overlap measures update

- Modules/Core/SpatialObjects/include/itkTubeSpatialObject.hxx
- Modules/Core/SpatialObjects/test/CMakeLists.txt
- Modules/Core/SpatialObjects/test/itkDTITubeSpatialObjectTest.cxx
- Modules/Core/SpatialObjects/test/itkTubeSpatialObjectTest.cxx
The DTITubeSpatialObject test code was not run due to a bug in the CMakeLists.txt file.
> BUG: Spatial object testing

- Modules/ThirdParty/NIFTI/src/nifti/cmake/nifti_macros.cmake
> Update nifti fix install

- Modules/IO/NIFTI/test/itkNiftiWriteCoerceOrthogonalDirectionTest.cxx
This addresses valgrind defects.
> BUG: initialize image buffer in Nifti direction test

- Modules/Video/BridgeOpenCV/include/itkOpenCVVideoIO.h
- Modules/Video/BridgeOpenCV/src/itkOpenCVVideoIO.cxx
- Modules/Video/BridgeVXL/include/itkVXLVideoIO.h
- Modules/Video/BridgeVXL/src/itkVXLVideoIO.cxx
Change last few usages of pre ITK v5 IOComponentType enums to
IOComponentEnum enum classes to make ITK compile with ITK_LEGACY_REMOVE.
We use a patched version of ITK v5.2.1 with these changes in MITK for a while now.
It seems like these two classes were partially overlooked when transitioning from ITK v4 to v5.
They are the last few occurrences of IOComponentType in ITK.
> COMP: Change IOComponentType to IOComponentEnum

- Modules/Registration/Common/include/itkLandmarkBasedTransformInitializer.h
- Modules/Registration/Common/include/itkLandmarkBasedTransformInitializer.hxx
- Modules/Registration/Common/test/itkLandmarkBasedTransformInitializerTest.cxx
For adding iso-tropic scaling in the transformation matrix along with Rotation and Translation when using landmarks for transform initialization.
Moved some common code from VersorRigid3DTransform and Similarity3DTransform and created **ComputeCentroid** and **CreateMatrix**.
Introduced a PointType3D to handle the compilation issue when wrapping.
> ENH: Add Similarity3DTransform in itkLandmarkBasedTransformInitializer

- .github/workflows/first-interaction.yml
> DOC: Add First Interaction GitHub Action

- Modules/Filtering/ImageGrid/include/itkBinShrinkImageFilter.hxx
- Modules/IO/MINC/src/itkMINCImageIO.cxx
- Modules/IO/MRC/src/itkMRCImageIO.cxx
- Modules/IO/MeshBase/include/itkMeshFileReader.hxx
Did use `unique_ptr<T[]>` to cleanup code that had the very same `delete[]` on
multiple function exit paths, for example:
catch (...)
{
delete[] buffer;
throw;
}
delete[] buffer;
In this example, the catch clause can be removed entirely, when declaring the
buffer as a `unique_ptr<T[]>`.
---
Tip: When reviewing, you may want to hide whitespace changes: https://github.com/InsightSoftwareConsortium/ITK/pull/3577/files?w=1
> STYLE: Use unique_ptr to avoid the same delete[] on multiple exit paths

- .github/workflows/first-interaction.yml
Improve the first interaction message style:
- Remove the section header markup (`#`) and avoid an excessively large
font/avoid making the interaction message prevail over the issue/PR
text itself.
- Use the YAML literal block style syntax (`|`) and remove the newline
explicit markup.
> STYLE: Improve the first interaction message style

- Modules/Nonunit/Review/include/itkAttributeMorphologyBaseImageFilter.h
- Modules/Nonunit/Review/include/itkAttributeMorphologyBaseImageFilter.hxx
- Modules/Nonunit/Review/include/itkDirectFourierReconstructionImageToImageFilter.hxx
Suggested by Bradley Lowekamp (@blowekamp) at https://github.com/InsightSoftwareConsortium/ITK/pull/3599#issuecomment-1238166774
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3590 commit 15d09d6c756b46b4d1c296d8bb13b85f82654ef9
"STYLE: Replace `new T[n]` with `make_unique_for_overwrite` in cxx files"
> STYLE: Use unique_ptr and make_unique_for_overwrite in Review module

- Modules/Numerics/Statistics/test/itkUniformRandomSpatialNeighborSubsamplerTest.cxx
- STYLE: Improve `itkUniformRandomSpatialNeighborSubsamplerTest` style
- ENH: Increase `itk::UniformRandomSpatialNeighborSubsampler` coverage
> ENH: Increase `itk::UniformRandomSpatialNeighborSubsampler` coverage

- Modules/Filtering/ImageCompare/test/CMakeLists.txt
- Modules/Filtering/ImageCompare/test/itkSTAPLEImageFilterTest.cxx
- STYLE: Make flow control variables have a local scope 
- STYLE: Conform to ITK style in variable naming in tests
- STYLE: Declare variables closer to where they are instantiated
- ENH: Increase `itk::STAPLEImageFilter` coverage
-
> ENH: Increase `itk::STAPLEImageFilter` coverage

- Modules/Core/Mesh/include/itkMesh.hxx
Aims to simplify, and possibly speed up `itk::Mesh` member functions, `GetCellBoundaryFeatureNeighbors` and `GetCellNeighbors`
> STYLE: Allocate local variables (cells) Mesh on the stack, without `new`

- Modules/Numerics/Optimizersv4/include/itkGradientDescentOptimizerBasev4.h
- Modules/Numerics/Optimizersv4/test/itkRegularStepGradientDescentOptimizerv4Test.cxx
- STYLE: Use the superclass name in itkTypeMacro
- STYLE: Remove unnecessary message in argumentless test
- STYLE: Use `ITK_TRY_EXPECT_NO_EXCEPTION` macro in tests
- ENH: Increase `itk::RegularStepGradientDescentOptimizerv4` coverage
> ENH: Increase `itk::RegularStepGradientDescentOptimizerv4` coverage

- Modules/Segmentation/Classifiers/include/itkImageGaussianModelEstimator.h
- Modules/Segmentation/Classifiers/include/itkImageGaussianModelEstimator.hxx
Also defaulted the destructor of `ImageGaussianModelEstimator`.
> STYLE: Declare `ImageGaussianModelEstimator::m_Covariance` as unique_ptr

- Modules/Remote/TubeTK.remote.cmake
Major improvement is support for Python 3.10
Other updates described in the release notes:
https://github.com/InsightSoftwareConsortium/ITKTubeTK/releases
> ENH: Bump TubeTK to v1.3.3

- Modules/Core/Common/src/itkOutputWindow.cxx
Address segmentation fault uncounted with SimpleITK when the first call to SimpleITK/ITK are concurrently in threads. This follow the existing pattern in ITK which has mutex locks around initializing global instances.
Addresses segmentation fault in provided crash.py in SimpleITK/SimpleITK#74 
> BUG: Fix OutputWindow thread-safety GetInstance

- Modules/Core/Common/include/itkLightObject.h
- Modules/Core/Common/include/itkOctreeNode.h
- Modules/Core/ImageFunction/include/itkGaussianBlurImageFunction.h
- Modules/Core/SpatialObjects/include/itkContourSpatialObject.h
- Modules/Core/Transform/include/itkTransformGeometryImageFilter.h
- Modules/Filtering/BiasCorrection/include/itkMRASlabIdentifier.h
- Modules/Filtering/ImageFrequency/include/itkFrequencyBandImageFilter.h
- Modules/Filtering/ImageGrid/include/itkBSplineScatteredDataPointSetToImageFilter.h
- Modules/Filtering/ImageIntensity/include/itkSinImageFilter.h
- Modules/Filtering/ImageStatistics/include/itkStatisticsImageFilter.h
- Modules/IO/HDF5/include/itkHDF5ImageIO.h
- Modules/IO/ImageBase/include/itkStreamingImageIOBase.h
- Modules/IO/MeshBYU/include/itkBYUMeshIO.h
- Modules/IO/MeshFreeSurfer/include/itkFreeSurferAsciiMeshIO.h
- Modules/IO/MeshFreeSurfer/include/itkFreeSurferBinaryMeshIO.h
- Modules/IO/MeshGifti/include/itkGiftiMeshIO.h
- Modules/IO/MeshOBJ/include/itkOBJMeshIO.h
- Modules/IO/MeshOFF/include/itkOFFMeshIO.h
- Modules/IO/MeshVTK/include/itkVTKPolyDataMeshIO.h
- Modules/IO/NIFTI/include/itkNiftiImageIO.h
- Modules/Numerics/Optimizersv4/include/itkRegistrationParameterScalesFromJacobian.h
- Modules/Registration/Metricsv4/include/itkObjectToObjectMultiMetricv4.h
- Modules/Segmentation/RegionGrowing/include/itkConfidenceConnectedImageFilter.h
- DOC: Fix argument names in method Doxygen documentation
- DOC: Fix unexpected token in class documentation]
- DOC: Fix Doxygen automatic link to member function 
- DOC: Fix `itk::MRASlabIdentifier` class documentation list syntax
- DOC: Fix links to ITK Sphinx examples in class documentation
- DOC: Remove Sphinx link to non-existing example
- DOC: Provide a name for the `FitSplineIntoPointSet` Sphinx example
- DOC: Improve Sphinx example displayed names
> DOC: Fix Doxygen warnings

- Modules/IO/MeshVTK/src/itkVTKPolyDataMeshIO.cxx
Use CastWithRangeCheck to safely convert size_t to int.
> COMP: Fix comparison of integer expressions of different signedness

- CMake/ITKGroups.cmake
- CMake/ITKModuleRemote.cmake
- Modules/Core/Common/itk-module.cmake
- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshFunctionBase.h
- Modules/Core/QuadEdgeMesh/itk-module.cmake
- Modules/Core/SpatialObjects/itk-module.cmake
- Modules/Filtering/Colormap/itk-module.cmake
- Modules/Filtering/FastMarching/itk-module.cmake
- Modules/IO/ImageBase/itk-module.cmake
- Modules/IO/MeshBase/itk-module.cmake
- Modules/IO/NRRD/itk-module.cmake
- Modules/Numerics/Statistics/itk-module.cmake
- Modules/Remote/HigherOrderAccurateGradient.remote.cmake
- Modules/ThirdParty/NrrdIO/itk-module.cmake
- Modules/Video/Core/itk-module.cmake
- Modules/Video/IO/itk-module.cmake
- DOC: Use Doxygen automatic class links in module descriptions
- DOC: Fix NRRD links in module descriptions
- DOC: Fix typos and improve wording in module descriptions
> DOC: Use doxygen autolinks in module description

- Modules/Numerics/Optimizers/include/itkAmoebaOptimizer.h
- Modules/Numerics/Optimizers/include/itkConjugateGradientOptimizer.h
- Modules/Numerics/Optimizers/include/itkLBFGSBOptimizer.h
- Modules/Numerics/Optimizers/include/itkLBFGSOptimizer.h
- Modules/Numerics/Optimizers/include/itkLevenbergMarquardtOptimizer.h
- Modules/Numerics/Optimizers/src/itkAmoebaOptimizer.cxx
- Modules/Numerics/Optimizers/src/itkConjugateGradientOptimizer.cxx
- Modules/Numerics/Optimizers/src/itkLBFGSBOptimizer.cxx
- Modules/Numerics/Optimizers/src/itkLBFGSOptimizer.cxx
- Modules/Numerics/Optimizers/src/itkLevenbergMarquardtOptimizer.cxx
- Modules/Numerics/Optimizersv4/include/itkAmoebaOptimizerv4.h
- Modules/Numerics/Optimizersv4/src/itkAmoebaOptimizerv4.cxx
Also "defaulted" the destructors of those optimizer classes.
> STYLE: Declare `m_VnlOptimizer` from Optimizers as unique_ptr

- Modules/Core/Common/include/itkImageToImageFilter.h
- Modules/Core/Common/include/itkProcessObject.h
- Modules/IO/ImageBase/include/itkStreamingImageIOBase.h
Use Doxygen syntax to create automatic links to members.
According to the relevant Doxygen documentation:
https://doxygen.nl/manual/autolink.html
> DOC: Use Doxygen syntax to create automatic links to members

- Modules/IO/BMP/src/itkBMPImageIO.cxx
Similar to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3619 commit e2b7445fc98f08170dc528fe10a3045cb650f547 "STYLE: Declare local `buffer` in `GE5ImageIO::ReadHeader` as unique_ptr"
> STYLE: Declare local `value` in `BMPImageIO::Read` as unique_ptr<char[]>

- Modules/Filtering/AnisotropicSmoothing/itk-module.cmake
- Modules/Filtering/CurvatureFlow/itk-module.cmake
- Modules/Filtering/GPUAnisotropicSmoothing/itk-module.cmake
- DOC: Fix module names in module description ref links 
- DOC: Link groups in Doxygen in module description
> DOC: Fix module links in module descriptions

- Wrapping/Generators/Python/itk/support/extras.py
A list of slices or DICOM series can be provided.
> BUG: Add type specification for imread image series

- Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.h
- Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.hxx
Move common code chunk to a private member function that can be shared.
> STYLE: Consolidate duplicated code

- Modules/Remote/FPFH.remote.cmake
ITKFPFH is a remote module to compute point feature. The computed feature could be used to obtain salient points while performing registration of two point clouds.
> ENH: Add FPFH as remote module

- Modules/Remote/RANSAC.remote.cmake
ITK RANSAC is a remote module to perform point cloud registration. It supports feature based registration as well.
> ENH: Add RANSAC as ITK remote module

- Documentation/Maintenance/Release.md
May be related to manylinux image now being based on Alpine.
> DOC: sudo required in ARM wheel builds

- Modules/Registration/Metricsv4/include/itkEuclideanDistancePointSetToPointSetMetricv4.h
- Modules/Registration/Metricsv4/include/itkEuclideanDistancePointSetToPointSetMetricv4.hxx
- Modules/Registration/Metricsv4/test/CMakeLists.txt
- Modules/Registration/Metricsv4/test/itkEuclideanDistancePointSetMetricTest3.cxx
Points beyond the DistanceThreshold parameter are skipped in the derivative and value calculation.
The code change has no impact on existing APIs as the default value is negative which will include all the points in the calculation. Only when a positive value is used as the DistanceThreshold we see a change in behavior. 
This change is to make the ICP registration similar to the Open3D API (**max_correspondence_distance**).
> ENH: Add DistanceThreshold parameter in EuclideanDistance Metricv4

- Modules/Registration/Metricsv4/include/itkImageToImageMetricv4.hxx
Implements the change suggested in #3501, credit to @eurotomania, @cookpa
> BUG: add SetNumberOfWorkUnits to SetMaximumNumberOfWorkUnits

- Wrapping/Generators/CastXML/CMakeLists.txt
Addresses #3745
Also switching to GitHub Releases for reliability / longevity.
> COMP: Bump CastXML for Linux ARM build

- .zenodo.json
via   ./Utilities/Maintenance/UpdateZenodo.py
> DOC: Update .zenodo for 5.3.0

- Modules/Remote/CudaCommon.remote.cmake
- Modules/Remote/RTK.remote.cmake
> ENH: Upgrade RTK and CudaCommon with new RTKConsortium repository

- Testing/ContinuousIntegration/AzurePipelinesBatch.yml
- COMP: Install the `lxml` Python package for the `Batch` Azure CI build
- ENH: Use windows-2019 image v141 toolchain in `Batch` Azure CI matrix
> ENH: Fix `Batch` CI config errors

- Modules/IO/ImageBase/include/itkImageFileReader.h
- Modules/IO/ImageBase/include/itkImageFileReader.hxx
- Modules/Video/IO/include/itkVideoFileReader.h
- Modules/Video/IO/include/itkVideoFileReader.hxx
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3778 commit c28be8ba007e9fb167e4cef54e552b0ca1d1cb91
"STYLE: Add `const` to `inputData` parameters of `ConvertPixelBuffer`"
> STYLE: Add `const` to `inputData` of `DoConvertBuffer` member functions

- Modules/Remote/MinimalPathExtraction.remote.cmake
- Modules/Remote/README.md
- Modules/Remote/TubeTK.remote.cmake
Resolves an issue where MinimalPathExtraction and TubeTK could not be
checked out via recent tags.
CMake config error addressed by this change:
```
fatal: Needed a single revision
CMake Error at CMake/ITKModuleRemote.cmake:81 (message):
Failed to get the hash for tag
```
> BUG: Use hashes instead of tags for remote modules

- Modules/IO/MeshFreeSurfer/test/CMakeLists.txt
- Modules/IO/MeshFreeSurfer/test/itkFreeSurferMeshIOTest.cxx
> BUG: fixed valgrind defect in FreeSurfer mesh test

- Wrapping/Generators/Python/Tests/extras.py
- Wrapping/Generators/Python/itk/support/helpers.py
Likely copy/paste error from similar Mesh function.
> BUG: pointset_type_from_wasm_type return a PointSet

- Utilities/Maintenance/AuthorsChangesSince.py
Use the Git repository to increase discoverability.
> DOC: Include links to updated remote modules in release notes

- Documentation/Doxygen/DoxygenFooter.html
To be updated with each minor release.
> DOC: Add links to previous versions in the Doxygen footer

- Documentation/Maintenance/Release.md
> DOC: Add a reminder to update API docs link to older version

- Documentation/ReleaseNotes/5.3.md
- Documentation/ReleaseNotes/5.3rc01.md
- Documentation/ReleaseNotes/5.3rc02.md
- Documentation/ReleaseNotes/5.3rc03.md
- Documentation/ReleaseNotes/5.3rc04.md
Copies of the release notes for historical reference.
> DOC: Add archives of 5.3 release notes

- Utilities/Maintenance/BuildHeaderTest.py
> STYLE: Convert a tab indent into spaces in BuildHeaderTest.py

- README.md
> DOC: add Homebrew instructions

- Modules/Numerics/Statistics/include/itkKdTreeBasedKmeansEstimator.h
- Modules/Numerics/Statistics/test/CMakeLists.txt
- Modules/Numerics/Statistics/test/itkKdTreeBasedKmeansEstimatorTest.cxx
- ENH: Add boolean macro to use cluster labels
- STYLE: Prefer using local counters in loops
> ENH: Add boolean macro to use cluster labels

- Modules/Bridge/VtkGlue/include/itkImageToVTKImageFilter.h
- Modules/Core/Mesh/include/itkMeshSource.hxx
- Modules/Core/Mesh/include/itkMeshToMeshFilter.hxx
- Modules/Core/Mesh/include/itkParametricSpaceToImageSpaceMeshFilter.hxx
- Modules/Filtering/LabelMap/include/itkLabelObject.h
- Modules/IO/ImageBase/include/itkStreamingImageIOBase.h
- Modules/IO/MeshBase/include/itkMeshIOBase.h
- Modules/IO/MeshFreeSurfer/include/itkFreeSurferBinaryMeshIO.h
- Modules/Numerics/Optimizersv4/test/itkPowellOptimizerv4Test.cxx
- Modules/Registration/Metricsv4/include/itkPointSetFunction.hxx
- Modules/Video/Filtering/test/itkDecimateFramesVideoFilterTest.cxx
- Modules/Video/Filtering/test/itkFrameAverageVideoFilterTest.cxx
- Modules/Video/Filtering/test/itkImageFilterToVideoFilterWrapperTest.cxx
- DOC: Fix class names in documentation and comments
- DOC: Fix typos in documentation
- DOC: Remove unnecessary or empty implementation file method doc blocks
> DOC: Miscellaneous documentation fixes

- Modules/Numerics/Statistics/test/itkKdTreeBasedKmeansEstimatorTest.cxx
Fix input argument indices when creating the corresponding variables.
> BUG: Fix input argument indices in test

- Modules/Filtering/LabelMap/test/itkBinaryReconstructionLabelMapFilterTest.cxx
- Modules/Filtering/LabelMap/test/itkLabelShapeOpeningImageFilterTest1.cxx
- ENH: Increase coverage for `itk::AttributeSelectionLabelMapFilter`
- STYLE: Improve style in miscellaneous `LabelMap` module tests
> ENH: Increase coverage for `itk::AttributeSelectionLabelMapFilter`

- Modules/Filtering/ImageIntensity/include/itkBoundedReciprocalImageFilter.h
- Modules/Filtering/LabelMap/include/itkAttributePositionLabelMapFilter.hxx
- Modules/Filtering/LabelMap/include/itkAttributeSelectionLabelMapFilter.h
- Modules/Filtering/LabelMap/include/itkChangeRegionLabelMapFilter.hxx
- Modules/Filtering/LabelMap/include/itkInPlaceLabelMapFilter.hxx
- Modules/Filtering/LabelMap/include/itkStatisticsPositionLabelMapFilter.hxx
- Modules/Segmentation/DeformableMesh/include/itkDeformableSimplexMesh3DFilter.h
- Modules/Segmentation/DeformableMesh/include/itkDeformableSimplexMesh3DFilter.hxx
- DOC: Document methods in header file
- DOC: Make class description be a complete sentence
- DOC: Fix grammar in documentation
- DOC: Restrict the class authorship to the Doxygen documentation
> DOC: Miscellaneous documentation improvements

- Modules/Filtering/ImageIntensity/include/itkMaskImageFilter.h
- Modules/Filtering/ImageIntensity/include/itkMaskNegatedImageFilter.h
- Modules/Filtering/ImageIntensity/test/itkMaskNegatedImageFilterTest.cxx
> Mask negate vector

- .github/workflows/first-interaction.yml
Visually communicate our welcoming culture.
> DOC: Add emojis to the first-interaction message

- Modules/Filtering/FastMarching/include/itkFastMarchingUpwindGradientImageFilter.h
- Modules/Filtering/FastMarching/include/itkFastMarchingUpwindGradientImageFilter.hxx
- Modules/Filtering/FastMarching/test/itkFastMarchingUpwindGradientTest.cxx
Check that the target reach mode and expected number of target point are value in VerifyPreconditions instead of when setting expected number of targets.
This restores prior behavior of being able to set the target reach mode before setting the target points.
> BUG: Restore setting TargetPoints after ReachMode

- Modules/Core/Common/include/itkImageRandomNonRepeatingConstIteratorWithIndex.hxx
- Modules/Core/GPUCommon/include/itkGPUReduction.hxx
- Modules/Core/ImageFunction/include/itkCentralDifferenceImageFunction.hxx
- Modules/Core/ImageFunction/include/itkVectorLinearInterpolateImageFunction.hxx
- Modules/Core/ImageFunction/include/itkVectorLinearInterpolateNearestNeighborExtrapolateImageFunction.hxx
- Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.hxx
- Modules/Core/ImageFunction/test/itkVectorInterpolateImageFunctionTest.cxx
- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshEulerOperatorJoinVertexFunction.hxx
- Modules/Core/Transform/include/itkEuler3DTransform.hxx
- Modules/Filtering/DisplacementField/include/itkBSplineExponentialDiffeomorphicTransform.hxx
- Modules/Numerics/Optimizersv4/include/itkGradientDescentOptimizerBasev4.hxx
- Modules/Numerics/Optimizersv4/include/itkMultiGradientOptimizerv4.hxx
- Modules/Numerics/Optimizersv4/include/itkMultiStartOptimizerv4.hxx
- Modules/Numerics/Optimizersv4/include/itkObjectToObjectMetric.hxx
- Modules/Numerics/Optimizersv4/include/itkRegistrationParameterScalesEstimator.hxx
- Modules/Registration/Common/include/itkImageToImageMetric.hxx
- Modules/Registration/GPUPDEDeformable/include/itkGPUDemonsRegistrationFilter.hxx
- Modules/Registration/GPUPDEDeformable/include/itkGPUDemonsRegistrationFunction.hxx
- Modules/Registration/GPUPDEDeformable/include/itkGPUPDEDeformableRegistrationFilter.hxx
- Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFilter.hxx
- Modules/Registration/PDEDeformable/include/itkDiffeomorphicDemonsRegistrationFilter.hxx
- Modules/Registration/PDEDeformable/include/itkFastSymmetricForcesDemonsRegistrationFilter.hxx
- Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFilter.hxx
- Modules/Segmentation/Classifiers/include/itkImageClassifierBase.hxx
- Modules/Segmentation/KLMRegionGrowing/include/itkKLMRegionGrowImageFilter.hxx
- Modules/Segmentation/LevelSets/include/itkShapePriorMAPCostFunction.hxx
- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkMRFImageFilter.hxx
- STYLE: Prefer double forward slashes for within-method body comments
- STYLE: Remove commented output stream messages
- STYLE: Remove unnecessary within-method body comments
> STYLE: Miscellaneous comment cleanup

- Wrapping/Generators/Python/itk/support/extras.py
> ENH: Improve itk.imread error message when the input file doesn't exist

- Modules/Core/Common/include/itkConstantBoundaryCondition.h
- Modules/Core/Common/include/itkExceptionObject.h
- Modules/Core/Common/include/itkLightObject.h
- Modules/Core/Common/include/itkPeriodicBoundaryCondition.h
- Modules/Core/Common/include/itkZeroFluxNeumannBoundaryCondition.h
- Modules/Core/Common/src/itkLightObject.cxx
- Modules/Core/SpatialObjects/include/itkSpatialObjectPoint.h
Use ITK macros to print runtime type information.
> ENH: Use ITK macros to print runtime type information

- Modules/IO/TransformMINC/include/itkMINCTransformIO.h
Address issue with MSVC when shared libraries enable. The following warning is emitted:
itkMINCTransformIO.h(137,88): warning C4910: 'itk::MINCTransformIOTemplate<float>': '__declspec(dllexport)' and 'extern' are incompatible on an explicit instantiation
> COMP: fix linkage for MINCTransformIO

- Modules/IO/TransformMINC/include/itkMINCTransformIO.h
This is release version of #3922.
> Fix linkage for MINCTransformIO

- Modules/Core/Common/include/itkMath.h
- Modules/Core/Common/src/itkNumericTraits.cxx
- Modules/Core/Common/test/itkMathTest.cxx
- Modules/Core/Common/test/itkNumericTraitsTest.cxx
> COMP: Supress warning in MSVC for non-float complex

- Modules/Core/Common/test/itkFloodFillIteratorTest.cxx
- Modules/Core/Common/test/itkFloodFilledSpatialFunctionTest.cxx
- Modules/Filtering/BinaryMathematicalMorphology/include/itkBinaryMorphologicalClosingImageFilter.hxx
- Modules/Filtering/ImageFeature/include/itkBilateralImageFilter.hxx
- Modules/Filtering/ImageFeature/include/itkLaplacianSharpeningImageFilter.hxx
- Modules/Filtering/ImageGradient/include/itkGradientImageFilter.hxx
- Modules/Filtering/ImageGradient/test/itkDifferenceOfGaussiansGradientTest.cxx
- Modules/Filtering/MathematicalMorphology/include/itkFlatStructuringElement.hxx
- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
- Modules/Numerics/FEM/include/itkFEMObject.hxx
- Modules/Numerics/FEM/include/itkMetaFEMObjectConverter.hxx
- Modules/Registration/Common/include/itkLandmarkBasedTransformInitializer.hxx
- Modules/Segmentation/Watersheds/include/itkIsolatedWatershedImageFilter.hxx
Using the following regular expressions:
Find what:  (\w[^ ]+)[ ]+(\w+) = \1(\([^\)]+\);)
Find what:  (\w[^ ]+)[ ]+(\w+) = \1(\([^\)]+\)\);)
Find what:  (\w[^ ]+)[ ]+(\w+) = \1(\(.+,.+\);)
Find what:  (\w[^ ]+)[ ]+(\w+) =\r\n[ ]+\1(\(.+,.+\);)
Find what:  (\w[^ <]+<.+>)[ ]+(\w+) =\r\n[ ]+\1(\([^\)]+\);)
Find what:  (\w[^ <]+<.+>)[ ]+(\w+) =\r\n[ ]+\1(\(.+,.+\);)
Replace with:  $1 $2$3
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3946
commit 9e5dda54257cedd49dae0e9439bd1dbead31fbba
> STYLE: Construct local variables by passing arguments directly (part 2)

- Modules/IO/Meta/test/itkLargeMetaImageWriteReadTest.cxx
ITK/Modules/IO/TIFF/test/itkLargeTIFFImageWriteReadTest.cxx:143:5:
runtime error: implicit conversion from type 'int' of value 65536 (32-bit, signed) to type 'PixelType' (aka 'unsigned short') changed the value to 0 (16-bit, unsigned)
```
-fsanitize=undefined -fsanitize=integer -fsanitize=nullability -fno-sanitize-recover=undefined 
```
> BUG: implicit conversion undefined behavior

- Wrapping/Generators/Python/itk/support/template_class.py
The prefix was accidentally removed during refactoring of the Python wrapping in 53e4fe066fa0955a2a4ee5899b400477ff93f198.
> BUG: Add missing Python string prefix in wrapping warning

- Modules/ThirdParty/NIFTI/src/nifti/niftilib/nifti1_io.c
- Modules/ThirdParty/NIFTI/src/nifti/niftilib/nifti1_test.c
- Modules/ThirdParty/NIFTI/src/nifti/niftilib/nifti1_tool.c
- Modules/ThirdParty/NIFTI/src/nifti/znzlib/znzlib.c
This updates nifti to the current upstream master.
> Nifticlib 2023 03 29

- Modules/Core/Common/test/itkImageRegionExclusionIteratorWithIndexTest.cxx
- Modules/Filtering/Smoothing/include/itkBinomialBlurImageFilter.hxx
- Modules/IO/MINC/src/itkMINCImageIO.cxx
- Modules/Numerics/Statistics/test/itkScalarImageToRunLengthMatrixFilterTest.cxx
- Modules/Registration/Metricsv4/test/itkANTSNeighborhoodCorrelationImageToImageMetricv4Test.cxx
- Modules/Registration/Metricsv4/test/itkANTSNeighborhoodCorrelationImageToImageRegistrationTest.cxx
- Modules/Registration/Metricsv4/test/itkCorrelationImageToImageMetricv4Test.cxx
- Modules/Registration/Metricsv4/test/itkMeanSquaresImageToImageMetricv4RegistrationTest2.cxx
- Modules/Segmentation/Voronoi/include/itkVoronoiDiagram2DGenerator.hxx
Variables that are never read can be removed.
> COMP: Remove unused variables

- Modules/Filtering/FFT/src/CMakeLists.txt
Reinstate itkFFTWFFTImageFilterInitFactory.cxx to ITKFFT_SRCS generally. Call to FFTWFFTImageFilterInitFactory is required for the python wrapped FFT module in cases where ITK_USE_CUFFTW is defined.
> COMP: itkFFTWFFTImageFilterInitFactory.cxx is required for ITK_USE_CUFFTW

- CMake/ITKModuleMacros.cmake
Change the default output path for modules testing data to include the
module name as a directory.
This prevents the same file name in defferent modules clobbering one
another causing intermediate testing failures.
> ENH: Set ITK_TEST_OUTPUT_DIR with module path

- Wrapping/Generators/Python/Tests/helpers.py
- Wrapping/Generators/Python/itk/support/helpers.py
> BUG: wasm_type_from_image_type for VariableLengthVector

- Modules/Filtering/FastMarching/src/itkFastMarchingUpwindGradientImageFilter.cxx
- Modules/Filtering/FastMarching/test/itkFastMarchingUpwindGradientTest.cxx
Fixed printing of default constructed FastMarchingUpwindGradient
containing: "INVALID VALUE FOR
itk::FastMarchingUpwindGradientImageFilterEnums::TargetCondition" for
m_TargetReachedMode member.
> BUG: Add missing string value for NoTargets enum

- Modules/Core/Common/include/itkConceptChecking.h
- Modules/Core/Common/test/itkNumericTraitsTest.cxx
- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshLineCell.h
Use default initialization instead of initialization with 0, which does not work for all numeric pixel type.
Addresses issue raised in discourse: https://discourse.itk.org/t/concept-checking-in-multiresolutionpyramidimagefilter/5929/3
> COMP: Address HasNumericTraits failure for Vector pixel type.

- Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary/dicomhdr.html
https://github.com/malaterre/GDCM.git
at commit 2ea6fd871157bbb33c690c27217090769d7f4dc7 (release).
- [z] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [z] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
> GDCM 2023-06-02 (2ea6fd87)

- CONTRIBUTING.md
Suggested-by: Jean-Christophe Fillion-Robin <jcfr@kitware.com>
> DOC: Add contributing graph to CONTRIBUTING.md

- Modules/Filtering/ImageFeature/include/itkLaplacianSharpeningImageFilter.hxx
Replaced a sequence of math filter with a lambda function used by a binary generator image filter. Additionally, replace the intensity windowing filter with the original math computed in a unary generator using a lambda function.
Additionally, a non-filter calculator was replaced with the MinimumMaximumImageFilter. Filters are deleted by setting the pointer to nullptr after usage.
> ENH: Use generator/lambda ITK filter for pixel computation

- Examples/Filtering/LaplacianSharpeningImageFilter.cxx
- Modules/Filtering/ImageFeature/include/itkLaplacianSharpeningImageFilter.h
- Modules/Filtering/ImageFeature/include/itkLaplacianSharpeningImageFilter.hxx
Revert to using the a laplacian neighborhood operator over the recursive laplacian filter which requires real pixel types for input and output.
> ENH: Restore integer support for laplacian sharpening

- Modules/Core/Transform/include/itkMultiTransform.hxx
Simplified the implementation of `MultiTransform` member functions, by using range-based `for` loops to iterate over its `m_TransformQueue` data member.
> STYLE: MultiTransform iterate over m_TransformQueue by range-based `for`

- Modules/Core/Common/include/itkMacro.h
To address resolution in client code. #4074
> COMP: Use full ::itk namespace in itkMacro.h

- Modules/Numerics/Statistics/include/itkHistogramToRunLengthFeaturesFilter.h
- Modules/Numerics/Statistics/include/itkScalarImageToRunLengthFeaturesFilter.h
- Modules/Numerics/Statistics/include/itkScalarImageToRunLengthMatrixFilter.h
Remove class self reference in Doxygen `\sa` command.
> DOC: Remove class self reference in Doxygen `\sa` command

- Modules/Core/Common/include/itkNeighborhood.h
- Modules/Core/ImageAdaptors/test/itkVectorImageToImageAdaptorTest.cxx
- Modules/Filtering/FFT/include/itkComplexToComplexFFTImageFilter.h
- Modules/Filtering/FFT/include/itkFFTWComplexToComplexFFTImageFilter.h
- Modules/Filtering/ImageStatistics/include/itkAdaptiveHistogramEqualizationImageFilter.h
- Modules/Filtering/MathematicalMorphology/include/itkBinaryBallStructuringElement.h
- Modules/Filtering/MathematicalMorphology/include/itkBinaryCrossStructuringElement.h
- Modules/Filtering/MathematicalMorphology/include/itkFlatStructuringElement.h
- Modules/Nonunit/Review/include/itkScalarChanAndVeseDenseLevelSetImageFilter.h
- Modules/Nonunit/Review/include/itkScalarChanAndVeseSparseLevelSetImageFilter.h
- Modules/Segmentation/LevelSets/include/itkSegmentationLevelSetImageFilter.h
- Modules/Video/BridgeOpenCV/include/itkOpenCVImageBridge.h
- Modules/Video/BridgeOpenCV/include/itkOpenCVVideoCapture.h
Remove duplicate "type" in alias documentation.
> DOC: Remove duplicate "type" in alias documentation

- Modules/ThirdParty/VNL/src/vxl/CMakeLists.txt
- Modules/ThirdParty/VNL/src/vxl/core/CMakeLists.txt
- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_matrix.cxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_matrix_fixed.cxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_vector.cxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_bignum_traits.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_decnum_traits.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.hxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix_fixed.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix_fixed.hxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_numeric_traits.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_polynomial.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_polynomial.hxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_rational_traits.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_sparse_matrix.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_sparse_matrix.hxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector.hxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector_fixed.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector_fixed_ref.h
https://github.com/vxl/vxl.git
at commit 4332fd7409a6d26902c0477fe2991a3185282e45 (master).
> VXL 2023-06-18 (4332fd74)

- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaImage.cxx
at commit 556864f5a7bb2853466d0d22068b268e49137e52 (master).
> MetaIO 2023-07-16 (556864f5)

- Modules/Video/BridgeOpenCV/include/itkOpenCVVideoCapture.h
- Modules/Video/BridgeVXL/include/vidl_itk_istream.h
- STYLE: Conform to ITK comment style for within code in OpenCVVideoCapture
- DOC: Make the RTTI method documentation consistent in module `Video`
> STYLE: Conform to ITK comment style for within code in OpenCVVideoCapture

- .github/workflows/first-interaction.yml
- CODE_OF_CONDUCT.md
- README.md
- DOC: Add a note to the `README` about issues vs. questions
- DOC: Add a note to the first interaction workflow about its nature
- DOC: Refer to ITK's discussion space in a consistent manner
- DOC: Reword the copyright holder sentence in the code of conduct
- DOC: Link the Creative Commons license page in the code of conduct
> DOC: Miscellaneous community doc improvements

- Modules/Numerics/Optimizers/test/itkRegularStepGradientDescentOptimizerTest.cxx
- ENH: Increase coverage for `RegularStepGradientDescentBaseOptimizer`
- STYLE: Prefer using the `ITK_TRY_EXPECT` macros in test
- STYLE: Conform to ITK style guidelines in test
- STYLE: Conform to ITK SWG style guidelines in test ending message
> ENH: Increase coverage for `RegularStepGradientDescentBaseOptimizer`

- README.md
Improve consistency when referring to the issue tracker in the `README` file: use the same term and add a link.
> DOC: Improve consistency when referring to the issue tracker in README

- Modules/IO/TransformBase/test/itkTransformFileReaderTemplateTest.cxx
- Modules/IO/TransformBase/test/itkTransformFileWriterTemplateTest.cxx
Remove test input argument checking if no arguments are required by the test beyond the test name.
> STYLE: Remove test input argument checking if no argument is required

- Modules/Numerics/Statistics/test/itkHistogramTest.cxx
- STYLE: Use testing macros in `itkHistogramTest.cxx`
- STYLE: Make non-macro comparison blocks consistent in itkHistogramTest
- DOC: Improve comments in `itkHistogramTest.cxx`
> STYLE: Improve `itk::Histogram` test syle

- Wrapping/Generators/Python/module_ext.i.in
SWIG v 4.1.0+ use PyObject instead of PySliceObject after https://github.com/swig/swig/commit/e683168018558f4e73dc26629c4bbec224d23438
This adds the definition of SWIGPY_SLICEOBJECT.
Closes #3782
> BUG: define SWIGPY_SLICEOBJECT

- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.h
> DOC: Fixed spelling in itkRGBGibbsPriorFilter.h

- Modules/IO/TransformMINC/test/itkIOTransformMINCTest.cxx
> BUG: Fix incorrectly specified expected result in itkIOTransformMINCTest

- Documentation/Maintenance/Release.md
- DOC: Remove François Budin from GPG key holder ITK maintainer's list
- DOC: Remove updating ResearchGate ITK project from release tasks
- DOC: Explain better the release announcement in NumFOCUS newsletter
> DOC: Update release procedure doc

- Documentation/Doxygen/DoxygenLayout.xml
Closes #3666. Build in progress on `blaster`.
> DOC: Move detailed description to the top of class documentation page

- Modules/IO/TransformMINC/README
- Modules/IO/TransformMINC/include/itkMINCTransformIO.h
- Modules/IO/TransformMINC/include/itkMINCTransformIOFactory.h
- Modules/IO/TransformMINC/test/README
- DOC: Remove unnecessary `ITKIOTransformMINC` `README` files
- DOC: Improve `ITKIOTransformMINC` class documentation
> DOC: Miscellaneous `ITKIOTransformMINC` doc improvements

- CMake/ITKGroups.cmake
- CMake/ITKModuleEnablement.cmake
Addresses https://github.com/InsightSoftwareConsortium/ITK/issues/4248 where the ITKTestKernel module was not enabled as part
of ITKGroup_Core.
> Multiline module group definition

- Documentation/docs/contributing/code_of_conduct.md
- Documentation/docs/contributing/enforcement.md
- DOC: Add missing closing bracket in contributing enforcement insert
- DOC: Fix diversity statement link in code of conduct
> DOC: Fix diversity statement link in code of conduct

- Modules/ThirdParty/VNL/src/vxl/CMakeLists.txt
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_sparse_matrix.hxx
- Modules/ThirdParty/VNL/src/vxl/vcl/vcl_msvc_warnings.h
Updated using the script. Closes #4276.
> VXL 2023-11-01 (6456d120)

- README.md
Add link to documentation in `README`.
> DOC: Add link to documentation in `README`

- Documentation/docs/README.md
Add intro, explain how to check GitHub UI change build previews, and use sphinx-autobuild.
> DOC: Improve documentation contribution documents

- Documentation/docs/README.md
Small change to indicate that the `requirements.txt` installation step listed in "Option 1" for building docs is also required for autobuilding in "Option 2".
Under the existing structure it is easy to miss that "Option 1" dependencies are also required for "Option 2" (i.e. I missed this at first).
> DOC: Clarify requirements installation for docs autobuild

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- Documentation/docs/index.md
- Documentation/docs/migration_guides/index.md
- Documentation/docs/migration_guides/itk_5_migration_guide.md
Move the ITK 5 migration guide to Sphinx.
> Migration guide sphinx

- Documentation/docs/contributing/index.md
- Documentation/docs/contributing/module_workflows.md
Add discussion to reference the ITKRemoteModuleBuildTestPackageAction GitHub project for reusable CI workflows for ITK external modules.
> DOC: Add external module continuous integration discussion

- Modules/Filtering/QuadEdgeMeshFiltering/test/itkDiscreteGaussianCurvatureQuadEdgeMeshFilterTest.cxx
- Modules/IO/XML/test/itkDOMTest7.cxx
- Modules/Segmentation/LevelSets/test/itkParallelSparseFieldLevelSetImageFilterTest.cxx
- STYLE: Improve PSFLSIF test style
> STYLE: Improve style across miscellaneous tests

- Documentation/docs/index.md
> DOC: Add CDash link

- Wrapping/Generators/Python/PyBase/pyBase.i
- Wrapping/Generators/Python/Tests/extras.py
> BUG: Add pickle support for itk.Matrix and itk.ImageRegion

- Documentation/docs/README.md
- Documentation/docs/conf.py
- Documentation/docs/contributing/index.md
Also fix `cd` order for sphinx-autobuild.
> DOC: Add documentation contribution docs to the docs

- Documentation/Maintenance/Release.md
- Documentation/docs/README.md
Document the creation of major.minor versioned branches in the release process re: #4300.
> Versioned branch RTD creation

- Modules/IO/GIPL/include/itkGiplImageIO.h
Improve `itk::GIPLImageIO` brief explanation: capitalize the file format acronym and add the long name.
> DOC: Improve `itk::GIPLImageIO` brief explanation

- Modules/Core/Mesh/include/itkMeshRegion.h
- Modules/Core/Mesh/test/CMakeLists.txt
- Modules/Core/Mesh/test/itkMeshRegionTest.cxx
- DOC: Fix the `itk::MeshRegion::SetRegion` method doc description
- ENH: Add test for `itk::MeshRegion`
> ENH: Add test for `itk::MeshRegion`

- Documentation/docs/download.md
Description:
https://packages.guix.gnu.org/packages/insight-toolkit/5.0.0/
> DOC: Add GNU Guix package installation instruction

- Documentation/Maintenance/Release.md
Remove unnecessary whitespaces in Release documentation code blocks: increases consistency in code blocks across the Markdown documentation.
> STYLE: Remove unnecessary whitespaces in Release doc code blocks

- Documentation/docs/index.md
- Documentation/docs/learn/python_quick_start.md
Incorporated from the ITKPythonPackage repository.
> DOC: Add Python Quick Start guide

- Documentation/docs/learn/python_quick_start.md
- STYLE: Fix verbatim code syntax in Python quick start documentation
- STYLE: Use inline verbatim code style for Python supported pixel types
> STYLE: Python quick start guide style improvements

- Documentation/docs/learn/faq.md
- DOC: Fix ITK class Doxygen documentation link Markdown syntax in FAQs
- DOC: Remove deprecated combined ITK/VTK use doc section in FAQs
> DOC: Misc FAQ doc fixes

- Documentation/docs/learn/faq.md
- Documentation/docs/scientific_ecosystem/itk_ecosystem.md
Honor `ITK-Wasm`'s case in documentation files.
> DOC: Honor `ITK-Wasm`'s case in documentation files

- Documentation/docs/learn/faq.md
- DOC: Fix FAQ documentation heading typo
- DOC: Remove mention to deprecated `itk::DICOMImageIO` class in FAQs
> DOC: Miscellaneous FAQ documentation fixes

- Documentation/docs/index.md
- Documentation/docs/learn/faq.md
Transfer the wiki HU page to Markdown documentation: https://itk.org/Wiki/ITK_Hounsfield_Units
Rename the document and title to honor the contents.
> DOC: Transfer the wiki HU page to Markdown documentation

- Documentation/docs/index.md
Remove non-existing file from documentation TOC.
Inadvertently left in commit b4c1154.
> DOC: Remove non-existing file from documentation TOC

- Documentation/docs/index.md
- Documentation/docs/learn/dicom.md
Transfer the wiki DICOM page to Markdown documentation: https://itk.org/Wiki/ITK/DICOM.
> DOC: Transfer the wiki DICOM page to Markdown documentation

- Documentation/docs/learn/faq.md
- Documentation/docs/learn/fda_sw_development_guidelines.md
Rename the FDA software development guidelines documentation file, and change the corresponding cross-reference in the FAQ document.
Take advantage of the commit to rename the headings to match the original Wiki contents, and use sentence style case.
> DOC: Rename the FDA SW development guidelines doc file

- Documentation/docs/contributing/documenting_itk.md
- DOC: Fix reStructuredText link syntax in `Documenting ITK` doc file
- STYLE: Prefer regular font in `Documenting ITK` doc file link text
> DOC: Miscellaneous `Documenting ITK` doc file fixes

- Modules/Numerics/FEM/include/itkFEMSpatialObjectReader.h
- Modules/Numerics/FEM/include/itkFEMSpatialObjectWriter.h
Fix name of class assertion failure for
`itk::FEMSpatialObjectReader` and `FEMSpatialObjectWriter`: use the correct class name.
Relates to https://github.com/InsightSoftwareConsortium/ITK/issues/4399
> COMP: Fix compilation of optional FEM module

- Modules/Core/Common/include/itkImageRandomConstIteratorWithIndex.h
- Modules/Core/Common/include/itkImageRandomConstIteratorWithIndex.hxx
- Modules/Core/Common/include/itkImageRandomConstIteratorWithOnlyIndex.h
- Modules/Core/Common/include/itkImageRandomConstIteratorWithOnlyIndex.hxx
- Modules/Core/Common/include/itkImageRandomNonRepeatingConstIteratorWithIndex.h
- Modules/Core/Common/include/itkImageRandomNonRepeatingConstIteratorWithIndex.hxx
- Modules/Filtering/LabelMap/include/itkLabelMap.h
- Modules/Filtering/LabelMap/include/itkLabelMap.hxx
Fix https://github.com/InsightSoftwareConsortium/ITK/issues/4399
> Fix FEM module compilation with VS2019

- Modules/Filtering/LabelMap/include/itkLabelMap.h
- Modules/Filtering/LabelMap/include/itkLabelMap.hxx
LabelMap code clean-up, inspired by LabelMap code changes from pull request #4400
> Use std::next in LabelMap, and other style improvements

- Documentation/docs/contributing/upload_binary_data.md
- Documentation/docs/releases/5.4rc02.md
- Documentation/docs/releases/index.md
- Utilities/Maintenance/DownloadLinksCookieCutter/{{cookiecutter.output_directory}}/ReleaseDownloadLinks.md
And related documentation updates.
> 5.4 RC 2 release notes

- CMake/itkExternal_Eigen3.cmake
> ENH: Improve messages when ITKInternalEigen3 fails to configure

- Modules/Core/Common/include/itkMacro.h
> ENH: Allow using std::vector<T> in itkSetMacro and friends

- Utilities/KWStyle/BuildKWStyle.cmake
See https://github.com/Kitware/KWStyle/issues/107
> COMP: Update KWStyle to fix build warnings with MacOSX13.1.sdk

- Wrapping/Generators/Python/PyBase/pyBase.i
> STYLE: Fix code indentation in pyBase.i to aid understanding

- Modules/Compatibility/Deprecated/include/itkVectorResampleImageFilter.hxx
- Modules/Core/Common/include/itkBoundingBox.hxx
- Modules/Core/Common/src/itkPlatformMultiThreaderPosix.cxx
- Modules/Core/Common/src/itkPlatformMultiThreaderSingle.cxx
- Modules/Core/Common/src/itkPlatformMultiThreaderWindows.cxx
- Modules/Filtering/DisplacementField/include/itkInverseDisplacementFieldImageFilter.hxx
- Modules/Filtering/DisplacementField/include/itkLandmarkDisplacementFieldSource.hxx
- Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx
- Modules/Filtering/ImageIntensity/include/itkIntensityWindowingImageFilter.hxx
- Modules/Filtering/ImageIntensity/include/itkNaryMaximumImageFilter.h
- Modules/Filtering/Smoothing/include/itkBoxUtilities.h
- Modules/Numerics/Optimizersv4/include/itkRegistrationParameterScalesFromShiftBase.hxx
- Modules/Segmentation/RegionGrowing/include/itkConfidenceConnectedImageFilter.hxx
Simplified the code by using `std::min` and `std::max`. Using Notepad++, Replace in Files:
Find what: ([ ]+)if \(([^ ]+) > ([^ ]+\))\)\r\n\1{\r\n\1  \2 = \3;\r\n\1}
Replace with: \1\2 = std::min\(\2, \3\);
Find what: ([ ]+)if \(([^ ]+) < ([^ ]+\))\)\r\n\1{\r\n\1  \2 = \3;\r\n\1}
Replace with: \1\2 = std::max\(\2, \3\);
Filters: itk*.hxx;itk*.h;itk*.cxx
[v] Match case
> Replace `if (x > f()) x = f()` with `x = std::min(x, f())`, and `if (x < f()) x = f()` with `x = std::max(x, f())`

- Modules/Core/Common/include/itkRGBPixel.h
> DOC: Fix typo in itkRGBPixel.h

- Modules/Core/Common/include/itkImageBase.h
- Modules/Core/Common/include/itkImageBase.hxx
- Modules/Core/Common/include/itkImageToImageFilter.hxx
> ENH: Add SameImageGridAs convenience method to ImageBase

- Modules/Core/Common/include/itkPoint.h
- Modules/Core/Common/include/itkRGBAPixel.hxx
- Modules/Core/Common/include/itkRGBPixel.hxx
Similar to the implementation of `Vector::operator==`.
> STYLE: Let Point, RGBPixel, RGBAPixel operator== just call the BaseArray

- Modules/Numerics/Optimizers/include/itkExhaustiveOptimizer.h
- Modules/Numerics/Optimizersv4/include/itkExhaustiveOptimizerv4.h
Update the language used to describe using the Exhaustive Optimizer.
Minor refinements and additions to the description of how the Exhaustive Optimizer parameter space is configured and explored.
> Doc exhaustive optimizer parameter setting clarification

- Modules/Core/Transform/wrapping/itkAffineTransform.wrap
- Modules/Numerics/Optimizersv4/include/itkRegistrationParameterScalesEstimator.hxx
- Modules/Segmentation/SignedDistanceFunction/wrapping/test/itkPCAShapeSignedDistanceFunction.py
> Wrap AffineTransform for float parameters

- Modules/Core/Common/include/itkImageBase.h
- Modules/Core/Common/include/itkMacro.h
- Modules/Core/Common/src/itkImageToImageFilterCommon.cxx
Consolidates constants used for default tolerances into the itkMacro.h header file.
> STYLE: Introduce constants for the default tolerances

- Modules/Numerics/Optimizersv4/include/itkLBFGS2Optimizerv4.h
- Modules/Numerics/Optimizersv4/src/itkLBFGS2Optimizerv4.cxx
- Modules/Numerics/Optimizersv4/wrapping/itkLBFGS2Optimizerv4.wrap
The new optimizer is based on modern c++ code rather than converted fortran code.  The new optimizer also has a few interesting modes that are not available in the original fortran implementation.
> ENH: Wrap new variant of itkLBFGS2Optimizerv4

- Modules/IO/DCMTK/src/itkDCMTKFileReader.cxx
- Modules/IO/DCMTK/test/CMakeLists.txt
- Modules/IO/DCMTK/test/Input/MultiFrameMRIZSpacing.dcm.cid
- Modules/IO/DCMTK/test/itkDCMTKImageIOSpacingTest.cxx
- Modules/IO/GDCM/test/Baseline/itkGDCMImageReadWriteTest_MultiFrameMRIZSpacingBaseline.mha.cid
- Modules/IO/GDCM/test/CMakeLists.txt
- Modules/IO/GDCM/test/Input/MultiFrameMRIZSpacing.dcm.cid
> BUG: itkDCMTKFileReader Spacing Issue

- CMake/pre-commit
Now built from the documentation in ITK/Documentation/docs/.
> DOC: Update SetupForDevelopment.sh link to contributing documentation

- Documentation/docs/contributing/upload_binary_data.md
Fix grammar in binary data upload documentation file: remove wrong `an`.
> DOC: Fix grammar in binary data upload documentation file

- Modules/Core/Transform/wrapping/itkIdentityTransform.wrap
> COMP: Wrap IdentityTransform for float

- Modules/Filtering/Thresholding/include/itkThresholdImageFilter.h
- Modules/Filtering/Thresholding/include/itkThresholdImageFilter.hxx
> DOC: Clarify ThresholdImageFilter behavior

- Documentation/docs/scientific_ecosystem/itk_ecosystem.md
Added a link and short description of SimpleITK to the ITK ecosystem documentation.
> DOC: Adding pointer to SimpleITK in the ecosystem.

- Modules/Remote/FastBilateral.remote.cmake
> ENH: Add FastBilateral remote module

- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaImage.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaImage.h
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaObject.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaObject.h
- Modules/ThirdParty/MetaIO/src/MetaIO/src/tests/testMeta3Image.cxx
at commit ea08147a91e7676c47a9741baae0edd8eecf3c2f (master).
> MetaIO 2024-04-03 (ea08147a)

- Modules/IO/JPEG/include/itkJPEGImageIO.h
- Modules/IO/JPEG/src/itkJPEGImageIO.cxx
> BUG: Make JPEGImageIO const correct with m_FileName

- Modules/Core/TestKernel/include/itkRandomImageSource.hxx
- Modules/Core/Transform/include/itkEuler3DTransform.h
- Modules/Core/Transform/include/itkScaleTransform.h
- Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.h
- Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4.h
Minor changes to improve documentation
Minor changes to localize and make constant variables in random image source funciton
> DOC: Minor documentation refinements

- Modules/ThirdParty/DoubleConversion/src/double-conversion/bignum.cc
- Modules/ThirdParty/DoubleConversion/src/double-conversion/double-to-string.cc
- Modules/ThirdParty/DoubleConversion/src/double-conversion/double-to-string.h
https://github.com/google/double-conversion
at commit 15b7e306433dd899585f92758f7776a37a9c25ff (master).
> DoubleConversion 2023-11-01 (15b7e306)

- Wrapping/Generators/CastXML/CMakeLists.txt
Better compiler and C++ standard compatibilty.
> COMP: Bump CastXML to 0.6.5, LLVM to 18.1.3

- Modules/Core/Common/test/itkImageGTest.cxx
> COMP: Add testing of IsCongruentImageGeometry IsSameImageGeometryAs

- Modules/Core/Common/test/itkImageGTest.cxx
> Image geometry compare test

- Documentation/docs/releases/5.4rc04.md
- Documentation/docs/releases/index.md
Note: 5.4 RC 3 was not announced because a fix was created immediately
after.
> DOC: Add 5.4 Release Candidate 4 release notes

- Documentation/Maintenance/Release.md
More specifics on macOS package builds, Linux ARM builds.
> DOC: ITK 5.4 RC 3 release documentation updates

- Modules/Remote/MeshToPolyData.remote.cmake
- Modules/Remote/Montage.remote.cmake
- Modules/Remote/MorphologicalContourInterpolation.remote.cmake
- Modules/Remote/RTK.remote.cmake
- Modules/Remote/SphinxExamples.remote.cmake
- Modules/Remote/TubeTK.remote.cmake
- Modules/Remote/WebAssemblyInterface.remote.cmake
> ENH: Update remote modules using a script

- Modules/ThirdParty/KWSys/src/KWSys/CONTRIBUTING.rst
- Modules/ThirdParty/KWSys/src/KWSys/CommandLineArguments.cxx
- Modules/ThirdParty/KWSys/src/KWSys/Directory.cxx
- Modules/ThirdParty/KWSys/src/KWSys/MD5.c
- Modules/ThirdParty/KWSys/src/KWSys/SystemInformation.cxx
- Modules/ThirdParty/KWSys/src/KWSys/SystemTools.cxx
- Modules/ThirdParty/KWSys/src/KWSys/Terminal.c
- Modules/ThirdParty/KWSys/src/KWSys/testSystemTools.cxx
https://gitlab.kitware.com/utils/kwsys.git
at commit bc0706e73e38c043e14223621a6329ed1038095e (master).
Upstream Shortlog
-----------------
Brad King (1):
3c922475 Convert http URLs to https
Christoph Grüninger (3):
d3f3c38b Use prefix ++ operators for non-primitive types
9fd52415 Range-for loop with const reference
2310be95 Make variable more local
scivision (1):
6624edf2 SystemTools:FileIs{Directory,Executable,FIFO}: refactor for simplicity
> KWSys 2024-03-08 (bc0706e7)

- Utilities/KWStyle/BuildKWStyle.cmake
> ENH: Update KWStyle [GCC 13.2 output buffer size truncation warnings]

- Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.h
Command: ./Utilities/Maintenance/clang-format.bash --clang-format /home/matt/bin/ITK3-Wrap-Release/ClangFormat-prefix/src/ClangFormat/clang-format --tracked
> STYLE: Apply clang-format to LabelGeometryImageFilter

- Modules/Remote/RTK.remote.cmake
Several improvements:
git shortlog 1a2ca55..bfdca5b
Simon Rit (6):
COMP: Fix ramp filter redefinition of itkSetMacro
COMP: Remove deprecated inclusion of CUDA's math_functions.h
ENH: Rename lp_solve library according to ITK's conventions
BUG: Use size_t to compute CUDA memory length
ENH: Use 64-bit cublas for CUDA 12
ENH: Avoid single component intermediate CUDA array for scalar images
Should fix #4031.
> ENH: update remote module RTK

- CMake/CTestCustom.cmake.in
> COMP: Suppress LabelGeometryImageFilter deprecated warning

- Modules/Bridge/NumPy/wrapping/itkPyVectorContainer.wrap
- Wrapping/Generators/Python/PyBase/pyBase.i
- Wrapping/Generators/Python/Tests/extras.py
- Wrapping/Generators/Python/itk/support/extras.py
- Wrapping/TypedefMacros.cmake
This needs to be set to double. Previous values result in a value like
SL, which results in incorrect values.
> BUG: ElementType with PolyLineParametricPath ContinuousIndex

- CMake/ITKModuleRemote.cmake
- Modules/ThirdParty/GDCM/src/gdcm/CMakeLists.txt
- Modules/ThirdParty/GDCM/src/gdcm/Utilities/gdcmopenjpeg/CMakeLists.txt
Mark advanced CMake variables as advanced. Closes #4629 
Corresponding GDCM PR: https://github.com/malaterre/GDCM/pull/175
> cmake advanced mac

- Modules/Core/Common/include/itkImageSource.h
- Modules/Core/Common/include/itkImageSource.hxx
Removal of ITKV4 API conditional code makes this easier to initialize consistently.
> COMP: Prefer initialization over constructor assignment

- Modules/ThirdParty/MetaIO/src/MetaIO/src/CMakeLists.txt
- Modules/ThirdParty/MetaIO/src/MetaIO/src/localMetaConfiguration.h
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaArray.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaArray.h
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaArrow.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaArrow.h
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaBlob.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaCommand.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaContour.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaEllipse.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaForm.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaForm.h
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaImage.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaImage.h
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaLandmark.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaLine.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaMesh.h
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaObject.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaObject.h
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaScene.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaSurface.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaUtils.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaUtils.h
- Modules/ThirdParty/MetaIO/src/MetaIO/src/tests/testMeta2Object.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/tests/testMeta4Tube.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/tests/testMeta5Blob.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/tests/testMeta6Surface.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/tests/testMeta7Line.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/tests/testMeta9Landmark.cxx
at commit eb952d5b2dbbccc27a99cc1b4cb27410f5267981 (master).
Supersedes #4738. Closes #4738.
> MetaIO 2024-06-20 (eb952d5b)

- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
Addresses issue #4711.
When RelabelConnectedRegion is called by ThreadedConnectivity, both outputLabel and requeredLabel are the same value. Don't re-write the same value.
> BUG: Address race condition

- Documentation/docs/contributing/index.md
- DOC: Update release branch merge instructions
- DOC: Add note about using Squash and merge for new contributors
> squash and merge

- Modules/Core/Common/include/itkArray.h
> COMP: Swap should be marked noexception

- Modules/Core/Common/include/itkMacro.h
Rename deprecated macros and prepare for removal
at some future time.
> ENH: Move ITK_FUTURE_LEGACY_REMOVE to ITK_LEGACY_REMOVE

- Modules/Remote/TubeTK.remote.cmake
Features pypi wheels that work!
> ENH: Bump TubeTK to 1.4.0

- Documentation/Maintenance/Release.md
Add a note about the need to update the remote modules when a new ITK mjor/minor version is released.
> DOC: Add note about ITK release and remote module compatibility

- Modules/Filtering/FFT/include/itkFFTPadImageFilter.h
> DOC: Correct Documentation for FFTPadImageFilter::SizeGreatestPrimeFactor

- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaScene.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaUtils.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaUtils.h
at commit d269b3972910919ad22f2b179a13c189b176deef (master).
> MetaIO 2024-07-03 (d269b397)

- Modules/Filtering/FFT/include/itkFFTPadImageFilter.h
- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
> Fix Additional Thread Sanitizer issue in SLICImageFilter

- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaUtils.cxx
at commit 918ad45f911fb11c4d66965040201b7678c9c8be (master).
> MetaIO 2024-07-13 (918ad45f)

- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaUtils.cxx
at commit 1a031fd8223c4846e2f90f50216cbcb415d52018 (master).
> MetaIO 2024-07-19 (1a031fd8)

- Modules/ThirdParty/Eigen3/src/itk_eigen.h.in
- Modules/ThirdParty/VNL/src/vxl/CMakeLists.txt
- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_matrix_fixed.cxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_vector.cxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_alloc.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix.hxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix_fixed.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_matrix_fixed.hxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector.hxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector_fixed.h
- Modules/ThirdParty/VNL/src/vxl/core/vnl/vnl_vector_fixed.hxx
@hjmjohnson @andrei-sandor this pulls in the recent removal of extra semicolons (and more of course).
> Update Vxl to 2024-07-24

- Modules/Filtering/FFT/test/itkComplexToComplexFFTImageFilterTest.cxx
- Modules/Filtering/FFT/test/itkFFTWComplexToComplexFFTImageFilterTest.cxx
- Modules/IO/Bruker/src/itkBruker2dseqImageIOFactory.cxx
- Modules/IO/PhilipsREC/src/itkPhilipsPAR.cxx
- Modules/IO/PhilipsREC/src/itkPhilipsRECImageIO.cxx
- Modules/IO/PhilipsREC/src/itkPhilipsRECImageIOFactory.cxx
- Modules/Nonunit/Review/src/itkVoxBoCUBImageIO.cxx
- Modules/Nonunit/Review/src/itkVoxBoCUBImageIOFactory.cxx
Correct broken links to use new DOI.
> DOC: Correct broken links referencing midas.

- Examples/RegistrationITKv4/ImageRegistration11.cxx
- Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h
- Modules/Core/Common/include/itkGaussianKernelFunction.h
- Modules/Core/SpatialObjects/include/itkSpatialObject.h
- Modules/Registration/Common/include/itkSimpleMultiResolutionImageRegistrationUI.h
- Modules/Registration/Common/test/RegistrationITKv3/ImageRegistration11.cxx
Remove the semi-colon after method definitions.
> COMP: Fix remaining -Wextra-semi

- Modules/Filtering/ImageNoise/include/itkAdditiveGaussianNoiseImageFilter.h
- Modules/Filtering/ImageNoise/include/itkSaltAndPepperNoiseImageFilter.h
- Modules/Filtering/ImageNoise/include/itkShotNoiseImageFilter.h
- Modules/Filtering/ImageNoise/include/itkSpeckleNoiseImageFilter.h
- Modules/Filtering/ImageNoise/itk-module.cmake
Address error in DOI which was updated in the large change of insight-journal links.
> DOC: Error in specific DOI.

- Modules/Filtering/ImageStatistics/include/itkLabelOverlapMeasuresImageFilter.h
> DOC: Remove repeated word in itkLabelOverlapMeasuresImageFilter.h

- Modules/ThirdParty/TIFF/CMakeLists.txt
> BUG: Enable system TIFF with modern TIFF and cmake - release patch

- Modules/IO/TIFF/src/itkTIFFImageIO.cxx
- Modules/ThirdParty/TIFF/CMakeLists.txt
- Modules/ThirdParty/TIFF/src/itk_tiff.h.in
Remove macros and try compiles to support old libtif versions.
> ENH: Require libtiff >=4.0.3

- Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.h
> BUG: Silence LabelGeometry deprecation

- Modules/Bridge/NumPy/include/itkPyBuffer.hxx
The C++ function `PyBuffer::_GetImageViewFromArray` cannot support a non-contiguous Python buffer as input, because the buffer is imported into an `itk::Image`, via `itk::ImportImageContainer::SetImportPointer`.
Note that the Python function `GetImageViewFromArray` (from Modules/Bridge/NumPy/wrapping/PyBuffer.i.in) _does_ support a non-contiguous NumPy array as input, by calling `numpy.ascontiguousarray`:
https://github.com/InsightSoftwareConsortium/ITK/blob/d36dfc65c7c3734872dc1bfedf16ce388e4ef33c/Modules/Bridge/NumPy/wrapping/PyBuffer.i.in#L90-L91
> BUG: PyBuffer _GetImageViewFromArray should reject non-contiguous buffer

- .gitattributes
- .gitignore
- Documentation/docs/contributing/build_test_itk.md
- Documentation/docs/contributing/index.md
- pixi.lock
- pyproject.toml
Initial [pixi](https://pixi.sh) configuration, supporting easy, reproducible builds for development and testing.
Cross-platform build and test configuration utilizing Ninja and
cross-platform conda-forge toolchains. And Python build and test
configuration. These are specified by `cxx` and `python` environments.
The following tasks are defined:
- build           Build ITK
- build-debug     Build ITK - Debug
- build-debug-python Build ITK Python - Debug
- build-python    Build ITK Python
- build-release   Build ITK - Release
- clean           Clean the repository
- configure       Configure ITK
- configure-debug Configure ITK - Debug
- configure-debug-python Configure ITK Python - Debug
- configure-python Configure ITK Python
- configure-release Configure ITK - Release
- test …
> Initial Pixi configuration

- Documentation/docs/contributing/document_itk.md
- Documentation/docs/contributing/index.md
Use active over passive voice.
Order section roughly by most commonly used to least commonly used.
> DOC: Contribute to ITK presentation tweaks

- Modules/IO/PhilipsREC/src/itkPhilipsRECImageIO.cxx
The SpatialOrientationEnums conversion is marked for future deprecations and can not be used.
> BUG: Use Anatomical Orientation in PhilipsRECIO

- Modules/IO/TIFF/src/itkTIFFImageIO.cxx
Addresses a warning was being produced in TIFFImageIOInfoTest for the EXIFIFDOffset tag about being an unsupported type.
> BUG: Handle 8-byte tiff tags

- Modules/Filtering/ImageGrid/include/itkOrientImageFilter.h
- Modules/Filtering/ImageGrid/include/itkOrientImageFilter.hxx
- Modules/Filtering/ImageGrid/test/itkOrientImageFilterTest.cxx
- Modules/Filtering/ImageGrid/test/itkOrientImageFilterTest2.cxx
- Modules/Filtering/ImageGrid/wrapping/test/OrientImageFilterTest.py
Preserve compatibility with SpatialOrientation enums with implicit converstion. Additionally both the PositiveEnum and NegativeEnum are supported.
> Use AnatomicalOrientation in  OrientImageFilter

- Modules/Core/Common/test/itkAnatomicalOrientationGTest.cxx
> COMP: Fix compile error when ITK_USE_FLOAT_SPACE_PRECISION=ON

- Modules/IO/TIFF/src/itkTIFFImageIO.cxx
- Modules/IO/TIFF/src/itkTIFFReaderInternal.cxx
- Modules/IO/TIFF/src/itkTIFFReaderInternal.h
- Modules/ThirdParty/TIFF/src/itktiff/tif_dirread.c
- Modules/ThirdParty/TIFF/src/itktiff/tif_open.c
- Modules/ThirdParty/TIFF/src/itktiff/tiffiop.h
> Use future libtiff reentrant safe message handling to ITK messaging.

- Modules/Filtering/ImageGrid/test/CMakeLists.txt
- Modules/Filtering/ImageGrid/test/itkOrientImageFilterTest.cxx
Support ITK_FUTURE_LEGACY_REMOVE for OrientImageFilter tests. Update itkOrientImageFilterTest.cxx to use new AnatomicalOrientation enums, and mark itkOrientImageFilterTest2.cxx to be removed.
> COMP: Fix OrientImageFilter tests with options

- .github/workflows/pixi.yml
- pixi.lock
- pyproject.toml
Pixi and GitHub Actions configuration for Intel and ARM Mac.
> Pixi mac for release

- Modules/Core/TestKernel/include/itkTestingComparisonImageFilter.h
- Modules/Core/TestKernel/include/itkTestingComparisonImageFilter.hxx
- Modules/Core/TestKernel/test/CMakeLists.txt
- Modules/Core/TestKernel/test/itkTestingComparisonImageFilterGTest.cxx
> Comparison filter update

- Modules/Core/Common/include/itkImageSink.hxx
- Modules/Core/Common/include/itkImageToImageFilter.hxx
Added explicit [[fallthrough]] annotations to make code easier to understand.
Added space in diagnostic messages to make errors easier to read.
> STYLE: Minor style and readability changes

- Modules/IO/TIFF/src/itkTIFFReaderInternal.cxx
> COMP: There is no GlobalErrorDisplay only warning

- Modules/Registration/FEM/include/itkFEMRegistrationFilter.hxx
Wrap variable that is not used unless debugging is enabled.
> COMP: Suppress unused variable warning when not debugging.

- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaImage.cxx
at commit 56c9257467fa901e51e67ca5934711869ed84e49 (master).
> MetaIO 2024-11-29 (56c92574)

- Examples/Filtering/DiffusionTensor3DReconstructionImageFilter.cxx
Scan values directly into the desired locations
instead of having temporary alias variables.
> STYLE: Remove alias variables used in sscanf

- Modules/IO/TIFF/src/itkTIFFReaderInternal.cxx
Addresses the follow warning on the dashboard:
https://open.cdash.org/viewBuildError.php?type=1&buildid=10069379
> COMP: suppress format string is not a string literal warning

- Modules/ThirdParty/JPEG/src/itkjpeg-turbo/CMakeLists.txt
> COMP: libjpeg-turbo: Add object libraries as source files

- .pre-commit-config.yaml
- Modules/Filtering/Smoothing/wrapping/test/MedianImageFilterTest.py
- Utilities/Doxygen/mcdoc.py
- Wrapping/Generators/Python/Tests/multiprocess_lazy_loading.py
- Wrapping/Generators/Python/itk/pyi_generator.py
- Wrapping/Generators/Python/itk/support/base.py
- Wrapping/Generators/Python/itk/support/build_options.py
- Wrapping/Generators/Python/itk/support/extras.py
- Wrapping/Generators/Python/itk/support/template_class.py
- Wrapping/Generators/Python/itk/support/types.py
- Wrapping/Generators/Python/itk/support/xarray.py
- Wrapping/Generators/SwigInterface/igenerator.py
Only python3.9 and greater are supported, so remove
conditional code supporting <python3.9 statements.
Prefer native-supported type hints rather than
separate imports from the typing library.
Remove the redundant "r" designation for the default
file open behavior.
> STYLE: Prefer python39+ coding style recommendations

- Modules/IO/Meta/include/itkMetaImageIO.h
- Modules/IO/Meta/src/itkMetaImageIO.cxx
Address warnings identified for itkMetaImageIO.  This is several small code improvements.
> Followup on meta image io bug

- Documentation/docs/contributing/index.md
- README.md
Demonstrate community activity and motivate involvement.
Add to the README and ReadTheDocs Contributing index.
> DOC: Add repobeats stats to README, contributing docs

- Modules/Filtering/ImageCompose/include/itkComposeImageFilter.h
- Modules/Filtering/ImageCompose/include/itkComposeImageFilter.hxx
> Performance improvements to ComposeImageFilter

- Documentation/docs/contributing/index.md
- README.md
To demonstrate that this is an active project with a large community.
> DOC: Link repobeats image to GitHub monthly pulse

- Modules/Core/Common/include/itkImageIORegion.h
- Modules/Core/Common/include/itkIndex.h
- Modules/Core/Common/include/itkNeighborhoodOperator.h
- Modules/Core/Common/src/itkImageIORegion.cxx
Replace non-portable "long" type with "int".
> Use unsigned int for indexing into number of image dimensions

- Modules/IO/SpatialObjects/include/itkSpatialObjectReader.h
- Modules/IO/SpatialObjects/include/itkSpatialObjectReader.hxx
- Modules/IO/SpatialObjects/include/itkSpatialObjectWriter.h
- Modules/IO/SpatialObjects/include/itkSpatialObjectWriter.hxx
Find and remove redundant void argument lists.
> STYLE: Remove redundant void argument lists

- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkMRFImageFilter.hxx
> DOC: Fix typo itkMRFImageFilter.hxx

- Utilities/KWStyle/BuildKWStyle.cmake
Reduces number of compile warnings on Clang compiler.
> COMP: Update KWStyle

- Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentImageFilter.h
Removing language suggesting the filter is "experimental". Dženan Zukić says it "is one of the most used and well tested filters in ITK".  https://discourse.itk.org/t/connectedcomponentimagefilter-vs-hardconnectedcomponentimagefilter/7379/2
Added a note on connectivity.
> DOC: Revise class documentation, remove term 'experimental'

- .github/workflows/macos-arm.yml
- .github/workflows/pixi.yml
- Testing/ContinuousIntegration/AzurePipelinesBatch.yml
- Testing/ContinuousIntegration/AzurePipelinesLinux.yml
- Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml
- Testing/ContinuousIntegration/AzurePipelinesMacOS.yml
- Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
- Testing/ContinuousIntegration/AzurePipelinesWindows.yml
- Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
Use the updated testing data tarball.
> ENH: Update ExternalDataVersion in CI to 5.4.0

- Documentation/Maintenance/Release.md
In the release process documentation. Follow-up to #5142.
> DOC: Clarify MAJOR_VERSION is a variable

- Documentation/docs/releases/5.4.0.md
> DOC: Remove duplicate new author name (Matthieu LAURENDEAU)

- Documentation/docs/contributing/dashboard.md
> DOC: Update link to dashboard

- Modules/Core/Common/test/ClientTestLibraryA.cxx
- Modules/Core/Common/test/ClientTestLibraryB.cxx
- Modules/Core/Common/test/ClientTestLibraryC.cxx
- Modules/Filtering/ImageCompose/include/itkJoinImageFilter.h
- Modules/Filtering/LabelMap/test/itkStatisticsLabelMapFilterGTest.cxx
- Modules/IO/ImageBase/test/itkFileFreeImageIO.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaContour.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaFEMObject.cxx
- Modules/ThirdParty/MetaIO/src/MetaIO/src/metaObject.cxx
- Modules/ThirdParty/VNL/src/vxl/core/vnl/tests/test_math.cxx
> STYLE: Remove whitespace before scope resolution operator

- Documentation/docs/contributing/index.md
Fixes https://github.com/InsightSoftwareConsortium/ITK/issues/5156.
> BUG: Fix broken link on the contributing docs

- Modules/Numerics/Optimizers/src/itkGradientDescentOptimizer.cxx
- Modules/Numerics/Optimizers/src/itkRegularStepGradientDescentBaseOptimizer.cxx
- Modules/Numerics/Optimizersv4/src/itkLBFGSBOptimizerv4.cxx
- Modules/Numerics/Optimizersv4/src/itkLBFGSOptimizerv4.cxx
Removed non member variables used in printSelf method of Optimizer classes
resolves #3070
> STYLE: Modified Optimizer classes to avoid printing non-self member variables

- Utilities/Doxygen/DoxygenConfig.cmake
- Wrapping/DoxygenConfig.cmake
Added an additional layer of escaping to make sure the escaping required by Doxygen itself survives.
These changes fix the errors reported in the ITKDoxygen issue:
https://github.com/InsightSoftwareConsortium/ITKDoxygen/issues/5
and also reported in:
#3655
I found two files where these Doxygen aliases are passed via CMake:
https://github.com/InsightSoftwareConsortium/ITK/blob/1090d31e0360022b4414d0c3cbf27927a7d55901/Utilities/Doxygen/DoxygenConfig.cmake
https://github.com/InsightSoftwareConsortium/ITK/blob/1090d31e0360022b4414d0c3cbf27927a7d55901/Wrapping/DoxygenConfig.cmake
These files are very similar, but there are some differences that look like they should've been copied over to the other file.
Finally, I see that the live documentation at https://itk.org/Doxygen/html/index.html does …
> COMP: Fixed how Doxygen aliases are passed via CMake.

- Utilities/Doxygen/DoxygenConfig.cmake
- Wrapping/DoxygenConfig.cmake
> DOC: Remove HTML <br> tags in title section

- Modules/Filtering/ImageStatistics/include/itkMaximumProjectionImageFilter.h
- Modules/Filtering/ImageStatistics/include/itkMinimumProjectionImageFilter.h
- Modules/Filtering/ImageStatistics/include/itkProjectionImageFilter.hxx
- Modules/Filtering/ImageStatistics/test/CMakeLists.txt
- Modules/Filtering/ImageStatistics/test/itkMaximumProjectionImageFilterTest4.cxx
Update the ProjectionImageFilter base class to propagate the number of components to the output image.
Add multi-component support to max and min projection filters by performing operation on per commonents with initialization support for VariableLengthVectors.
> ENH: Add support for VectorImages to Projection filters

- Documentation/Doxygen/doxygen.bib
> DOC: Fix mix-up of URL and DOI in two references

- Modules/IO/ImageBase/include/itkStreamingImageIOBase.h
- Modules/IO/MRC/include/itkMRCHeaderObject.h
- Modules/IO/MRC/include/itkMRCImageIO.h
- Modules/IO/MRC/include/itkMRCImageIOFactory.h
- Modules/IO/MRC/src/itkMRCImageIOPrivate.h
- Modules/IO/VTK/include/itkVTKImageIO.h
- Modules/Remote/Ultrasound.remote.cmake
Proposed in https://github.com/InsightSoftwareConsortium/ITK/issues/3662#issuecomment-2648157595.
> DOC: Fix wrong DOI links for "olkmog" type of references in the code

- Modules/Core/Common/include/itkFixedArray.h
- Modules/Core/Common/test/itkFixedArrayGTest.cxx
> ENH: Add value_type to FixedArray

- Modules/Core/Transform/include/itkBSplineTransformInitializer.hxx
- Modules/Filtering/AnisotropicSmoothing/include/itkAnisotropicDiffusionImageFilter.hxx
- Modules/Filtering/AnisotropicSmoothing/include/itkCurvatureAnisotropicDiffusionImageFilter.h
- Modules/Filtering/AnisotropicSmoothing/include/itkVectorCurvatureAnisotropicDiffusionImageFilter.h
- Modules/Filtering/GPUAnisotropicSmoothing/include/itkGPUAnisotropicDiffusionImageFilter.hxx
- Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/5252
> Replace various `std::pow(2.0, x)` calls with `1ULL << x`

- .github/workflows/scorecard.yml
Based on:
https://github.com/ossf/scorecard/blob/9c2d4b23e7e488f8747b2ea9305f83a299e49c90/.github/workflows/scorecard-analysis.yml
> COMP: Update Security Scorecard GitHub Action

- Modules/Remote/MeshToPolyData.remote.cmake
Adds CoordType -> CoordinateType typename alias.
> COMP: Bump MeshToPolyData Remote Module to 2024-03-14 main

- Documentation/docs/migration_guides/itk_6_migration_guide.md
- Modules/Core/Common/itk-module.cmake
- Modules/Core/Common/src/CMakeLists.txt
- Modules/ThirdParty/VNLInstantiation/CMakeLists.txt
- Modules/ThirdParty/VNLInstantiation/itk-module.cmake
- Modules/ThirdParty/VNLInstantiation/src/CMakeLists.txt
- Modules/ThirdParty/VNLInstantiation/src/libraryplaceholder.cxx
This library only exists for compatibility. ITKv6 is a good time to remove it.
> ENH: Remove dummy VNLInstantiation library

- Modules/Filtering/DisplacementField/include/itkDisplacementFieldToBSplineImageFilter.h
- Modules/Filtering/DisplacementField/include/itkDisplacementFieldToBSplineImageFilter.hxx
The GetDisplacementFieldControlPointLattice method does not compile and is not used. The compilation error is related to the non-const GetOutput being called in a const method.
Addtionally, grafting is added for the output to ensure proper pipeline execution.
> Remove non-compilable PhiLattice get output

- Examples/Statistics/BayesianClassifier.cxx
- Examples/Statistics/BayesianClassifierInitializer.cxx
- Examples/Statistics/ImageEntropy1.cxx
- Examples/Statistics/ImageHistogram1.cxx
- Examples/Statistics/ImageHistogram2.cxx
- Examples/Statistics/ImageHistogram3.cxx
- Examples/Statistics/ImageHistogram4.cxx
- Examples/Statistics/ImageMutualInformation1.cxx
- Examples/Statistics/ScalarImageKmeansClassifier.cxx
- Examples/Statistics/ScalarImageKmeansModelEstimator.cxx
- Examples/Statistics/ScalarImageMarkovRandomField1.cxx
This commit addresses the review comments from PR #5223  related to issue #2802  . In this commit, examples related to Statistics have been enclosed with try catch block.
Refactored the Statistics examples by moving core logic into ExampleMain() function, try/catch handling is now done only in main(), which calls ExampleMain(). Original try blocks within the examples are removed.
Some comments in the software guide present in the src suggest enclosing specific operations (such as reading data or updating) within a try/catch block. Since these comments are part of the software guide, I’m unsure whether they should be removed or updated to reflect the new code structure.
Would it be appropriate to leave these comments as they are, or should I modify them to suggest that the try/catch block …
> STYLE: Centralize exception handling in Statistics examples

- Modules/Filtering/DisplacementField/include/itkInvertDisplacementFieldImageFilter.hxx
> ENH: Add named input to invert displacement field filter

- .github/workflows/itk_dict.txt
- Modules/Core/ImageFunction/include/itkBSplineDecompositionImageFilter.hxx
Three little style commits for `BSplineDecompositionImageFilter`
> Use `SizeValueType` in `for` loops in BSplineDecompositionImageFilter and other style commits

- Modules/Core/Common/test/itkColorTableTest.cxx
Increase `itk::ColorTable` test input argument check consistency:
- Increase consistency in the missing argument check message: follow the ITK SW guide coding guidelines. Specifically, add the missing parameters message.
>  STYLE: Increase `itk::ColorTable` test argument check consistency

- Modules/IO/NIFTI/test/itkNiftiImageIOTest.cxx
Exercise miscellaneous `itk::NiftiImageIO` methods in test.
> ENH: Exercise miscellaneous `itk::NiftiImageIO` methods

- .github/workflows/macos-arm.yml
Additional testing will ensure future proof with newer versions of CMake.
Addressed #5300
> ENH: Update GHA macOS-Python to use CMake 4.0.1

- Modules/Remote/LabelErodeDilate.remote.cmake
Addressed compilation warning related to unused local variable.
> COMP: Update LabelErodeDilate remote

- CMake/InsightValgrind-Ubuntu2204.supp
Addresses the following false positive:
https://open.cdash.org/viewDynamicAnalysisFile.php?id=11303601
Tested yesterday: 
https://github.com/SimpleITK/SimpleITK/pull/2298
> ENH: Add valgrind suppression file for Ubuntu 22.04 LTS

- Modules/Core/ImageFunction/include/itkLabelImageGaussianInterpolateImageFunction.hxx
In addressing the following warning:
note: parameter passing for argument of type 'std::pair<double, double>' when C++17 is enabled changed to match C++14 in GCC 10.
due to one argment being const and the other not. Code is updated to do only one search.
> Improve efficiency and address warning

- Modules/Core/Common/include/itkFloatingPointExceptions.h
- Wrapping/Generators/Python/Tests/extras.py
- Wrapping/Generators/Python/itk/support/extras.py
- Wrapping/Generators/Python/itk/support/init_helpers.py
The `uint8_t` type is defined here and since GCC 15 this header is not included implicitly through other header files.
> COMP: Include needed cstdint header

- .clang-tidy
- Examples/RegistrationITKv4/ImageRegistration11.cxx
- Examples/RegistrationITKv4/ImageRegistration14.cxx
- Examples/RegistrationITKv4/ImageRegistration15.cxx
- Examples/RegistrationITKv4/ImageRegistration16.cxx
- Examples/RegistrationITKv4/ImageRegistration17.cxx
- Examples/RegistrationITKv4/ImageRegistrationHistogramPlotter.cxx
- Modules/Bridge/VTK/include/itkVTKImageExportBase.h
- Modules/Bridge/VTK/src/itkVTKImageExportBase.cxx
Add Examples directory to clang-tidy autofixes.
> Manual default updates examples

- Documentation/docs/migration_guides/itk_6_migration_guide.md
Document preferred usage of the new class, and the need for explicit conversion in ITK Python.
Addresses: #5381
> DOC: Add migration documentation for AnatomicalOrientation

- Modules/IO/NIFTI/include/itkNiftiImageIO.h
- Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
The prior implementation had two members holding pointer, without clear or consitent practices with keeping the pointers valid or manually deleting them. This caused memory leaks detected by valgrind.
Refactor to use one RIAA unique_pointer for the nifti_image object. Modify the nifti anonymous structure to allow for forward declaration.
Addresses #5415.
> Use unique_pointer with nifti deleter

- Documentation/docs/learn/faq.md
> Add ImageJ2 and Fiji to common tools

- Documentation/docs/releases/5.4.4.md
> DOC: Fix links to 5.4.4 release artifacts

- Documentation/Doxygen/NeighborhoodIterators.dox
- Modules/Core/Common/include/itkImageBase.h
- Modules/IO/MeshBase/include/itkMeshFileReader.h
- Modules/Segmentation/Watersheds/include/itkWatershedSegmenter.h
Correcting missing and superfluous backtics.
> DOC: Incorrect use of backticks

- Utilities/Hooks/kw-commit-msg.py
- STYLE: Miscellaneous fixes to import statements in commit msg hook
- DOC: Add license header to commit msg hook script
> STYLE: Miscellaneous fixes to commit msg hook script

- Utilities/Hooks/post-commit
> DOC: Add missing thrid-party subtree directories to hook

- Modules/Remote/IOScanco.remote.cmake
Manually update to reflect recent work in the module.
> ENH: Update IOScanco remote module

- Wrapping/Generators/Python/itk/support/base.py
If a module had more than two factories (as e.g. RTK), the list was truncated to the first two values which seemed to be arbitrary.
> BUG: Allow auto registering more than two factories in Python modules

- .github/workflows/itk_dict.txt
- Documentation/docs/download.md
> DOC: Change version number in download.md from 5.4.3 to 5.4.4

- CODE_OF_CONDUCT.md
Following the content recommendation of the NumFOCUS Code of Conduct Working
Group.
> DOC: Update CODE_OF_CONDUCT.md

- Modules/ThirdParty/DCMTK/CMakeLists.txt
- Modules/ThirdParty/DCMTK/itk-module-init.cmake
> STYLE: Remove some unnecessary named cmake else clauses in DCMTK

- .github/workflows/itk_dict.txt
- .pre-commit-config.yaml
- Modules/Core/Common/include/itkHexahedronCell.hxx
- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
- Modules/Core/Common/include/itkQuadrilateralCell.hxx
- Modules/Core/Common/test/itkCommandObserverObjectTest.cxx
- Modules/Core/Common/test/itkRangeGTestUtilities.h
- Modules/Core/Common/test/itkVariableLengthVectorTest.cxx
- Modules/Core/ImageFunction/include/itkRayCastInterpolateImageFunction.hxx
- Modules/Core/Mesh/test/itkNewTest.cxx
- Modules/Filtering/Denoising/include/itkPatchBasedDenoisingImageFilter.hxx
- Modules/Filtering/FastMarching/include/itkFastMarchingBase.h
- Modules/Filtering/ImageGrid/include/itkBSplineControlPointImageFunction.h
- Modules/IO/GE/src/Ge4xHdr.h
- Modules/IO/GE/src/itkGE5ImageIO.cxx
- Modules/IO/JPEG2000/src/itkJPEG2000ImageIO.cxx
- Modules/IO/MeshOFF/src/itkOFFMeshIO.cxx
- Modules/Numerics/FEM/include/itpack.h
- Modules/Numerics/FEM/src/itkFEMElement3DC0LinearTriangularLaplaceBeltrami.cxx
- Modules/Numerics/FEM/test/itkFEMLoadBCMFCTestUser.cxx
- Modules/Numerics/Statistics/src/itkChiSquareDistribution.cxx
- Modules/Numerics/Statistics/src/itkNormalVariateGenerator.cxx
- Modules/Numerics/Statistics/test/itkSpatialNeighborSubsamplerTest.cxx
- Modules/Registration/Common/test/RegistrationITKv3/ImageRegistration1.cxx
- Modules/Video/Core/src/itkTemporalProcessObject.cxx
The latest version of CommenSpellCheck, v0.4.4, has a spell-check-disable command
that allows spell checking to be temporarily disabled within a file.  This PR updates the 
pre-commit to use this latest version.
With this new ability, I have disabled spell checking in some of the sections of code.
For instance, there were some ascii image comments that resulted in meaningless
ascii strings such as "ooooooooooooo" being entered into the spelling dictionary.
Also code that was commented out often required variable names to be entered.
These type workarounds are no longer required.
There are certainly more such clean ups that can be done in the ITK codebase.
> STYLE: Spelling disable update
