- Wrapping/Generators/Python/PyUtils/itkPyCommand.cxx
- Wrapping/Generators/Python/PyUtils/itkPyCommand.h
M:\Dashboard\ITK\Wrapping\Generators\Python\PyUtils\itkPyCommand.cxx(117,31): warning C4996: 'PyEval_CallObjectWithKeywords': deprecated in 3.9 [M:\Dashboard\ITK-build\Wrapping\Generators\Python\PyUtils\ITKPyUtilsPython.vcxproj]
> COMP: Fix deprecation warning for PyEval_CallObject

- Modules/Core/Common/include/itkProcessObject.h
GCC 7.4.1 raised the following errors on Linux:
Modules/Core/Common/include/itkSmartPointer.h:214:18: error: invalid use of incomplete type ‘using ObjectType = class itk::MultiThreaderBase {aka class itk::MultiThreaderBase}’
This is a compiler bug (as discussed in
https://github.com/InsightSoftwareConsortium/ITK/pull/3877#issuecomment-1398456306) and the same issue has been fixed for unique_ptr by 719c3ce349a0529f908b56817d02a33e7fb8ccde.
> COMP: Remove in class init of SmartPointer of forward declaration

- Modules/Remote/MinimalPathExtraction.remote.cmake
- Modules/Remote/TubeTK.remote.cmake
Updates TubeTK and MinimalPathExtraction to the versions built with same linux kernel for compatibility.   Without this update, no TubeTK or MinimalPathExtraction versions will work with ITKv5.3.0
> ENH: Bump TubeTK to v1.3.5 and MinimalPathExtraction to v1.2.6

- Modules/Core/Common/include/itkResourceProbe.h
- Modules/Core/Common/include/itkResourceProbe.hxx
- Modules/Core/Common/include/itkTimeProbe.h
- Modules/Core/Common/src/itkTimeProbe.cxx
- Modules/Core/GPUCommon/src/itkGPUDataManager.cxx
- Modules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceImageFilter.hxx
- Modules/Filtering/GPUAnisotropicSmoothing/include/itkGPUGradientAnisotropicDiffusionImageFilter.h
- Modules/Filtering/GPUAnisotropicSmoothing/test/itkGPUGradientAnisotropicDiffusionImageFilterTest.cxx
- Modules/Registration/GPUPDEDeformable/include/itkGPUPDEDeformableRegistrationFilter.h
- Modules/Registration/GPUPDEDeformable/include/itkGPUPDEDeformableRegistrationFilter.hxx
- COMP: Restore `PrintSelf` in itkGPUPDEDeformableRegistrationFilter.h
- COMP: Provide prefix-less member name to `itkPrintSelfObjectMacro`
- COMP: Fix boolean member print statement in `itk::GPUDataManager`
- ENH: Provide printing ability to time resource classes
- COMP: Add Superclass alias to GPUGradientAnisotropicDiffusionImageFilter
> COMP: Fix GPU modules `PrintSelf` compiler errors

- Testing/ContinuousIntegration/AzurePipelinesLinux.yml
- Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml
- Testing/ContinuousIntegration/AzurePipelinesMacOS.yml
- Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
- Testing/ContinuousIntegration/AzurePipelinesWindows.yml
- Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
- Utilities/Maintenance/README.md
Excluded various files and directories from triggering a CI run, according to Azure Pipelines "trigger definition" at https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/trigger?view=azure-pipelines#trigger-batch-branches-paths-tags
These are files that are not tested by the CI anyway.
This pull request aims to avoid running the virtual machines of the CI unnecessarily, to save energy and to reduce the time waiting for the CI.
> COMP: Exclude README, Utilities/Maintenance and other files from AZP CI

- Modules/Core/ImageFunction/include/itkRayCastInterpolateImageFunction.h
- Modules/Core/ImageFunction/include/itkRayCastInterpolateImageFunction.hxx
Put the RayCastInterpolateImageFunction helper class that is not meant to be exposed to the user inside RayCastInterpolateImageFunction, as a private nested type, instead of in an unnamed namespace. Header files (including *.hxx files) just shouldn't use an unnamed namespace.
Avoids a Clang-Tidy 17.0.0 warning saying:
> warning G253035D5: do not use unnamed namespaces in header files [google-build-namespaces]
Following C++ Core Guidelines, September 23, 2022 "Don’t use an unnamed (anonymous) namespace in a header",
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf21-dont-use-an-unnamed-anonymous-namespace-in-a-header
> COMP: Move RayCastHelper from unnamed namespace to private class section

- Modules/Core/Transform/include/itkKernelTransform.h
- Modules/Filtering/AnisotropicSmoothing/include/itkCurvatureNDAnisotropicDiffusionFunction.h
- Modules/Filtering/AnisotropicSmoothing/include/itkGradientNDAnisotropicDiffusionFunction.h
- Modules/Filtering/AnisotropicSmoothing/include/itkVectorGradientNDAnisotropicDiffusionFunction.h
- Modules/Filtering/GPUAnisotropicSmoothing/include/itkGPUGradientNDAnisotropicDiffusionFunction.h
- Modules/Numerics/Optimizers/include/itkSPSAOptimizer.h
- Modules/Numerics/Optimizers/test/itkParticleSwarmOptimizerTestFunctions.h
- Modules/Registration/FEM/include/itkFEMRegistrationFilter.h
Previous commits that added `{}` initializers to data members by means of regular expressions had overlooked three-letter identifiers, like `m_E` and `m_I`.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3851 commit 5e2c49f9eb80e78903ce8f9fd2b5952062653cab
"STYLE: Add in-class `{}` member initializers to objects created by New()"
> STYLE: Add in-class `{}` member initializers to 3-letter data members

- Utilities/Maintenance/UpdateRequiredITKVersionInRemoteModules.sh
GitHub has updated Git protocol security, and the usage of the unencrypted git protocol has been retired permanently on March 15th 2022. But, there are few instances of such in `UpdateRequiredITKVersionInRemoteModules.sh`. Hence, may lead to bunch of unauthenticated git protocol errors.
Use https protocol in place of unencrypted git protocol
`git://github.com/InsightSoftwareConsortium/ITKPythonBuilds.git` should be changed to
`https://github.com/InsightSoftwareConsortium/ITKPythonBuilds.git`
and `git://github.com/InsightSoftwareConsortium/ITK.git` should be changed to
`https://github.com/InsightSoftwareConsortium/ITK.git`
https://github.blog/2021-09-01-improving-git-protocol-security-github/
Fixes  #3942
> BUG: Update UpdateRequiredITKVersionInRemoteModules.sh script to remove unencrypted git protocol 

- Wrapping/Generators/SwigInterface/CMakeLists.txt
Prevent complexities when cross-compiling for ARM and avoid the need to build from source in wrapping and remote module builds.
Build portability notes:
- Built with the dockcross/manylinux2014-x64 toolchain
- PRCE built static: ./pcre-8.44/configure --prefix=${PWD}/PCRE --disable-shared make make install
- SWIG built with static libstdc++ and against the static pcre export CXXFLAGS=-static-libstdc++ export PCRE_CONFIG=/work/pcre/PCRE/bin/pcre-config ./configure --prefix=/work/swiglinux-4.0.2 --with-prce-prefix=/work/pcre/PCRE make make install
> COMP: Use pre-built swig for Linux/x86_64

- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshLineCell.h
- Modules/IO/NRRD/src/itkNrrdImageIO.cxx
- Modules/IO/NRRD/test/itkNrrdImageIOTest.h
ENH: Added saving metadata in NRRD file in more data types
Added a test case for checking if metadata is saved as expected
Addresses: #3940
> ENH: Added saving metadata in NRRD file in more data types

- Modules/Filtering/DisplacementField/include/itkInverseDisplacementFieldImageFilter.hxx
- Modules/Filtering/DisplacementField/include/itkLandmarkDisplacementFieldSource.hxx
- Modules/Filtering/FastMarching/include/itkFastMarchingImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkInterpolateImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkShrinkImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkSliceImageFilter.hxx
- Modules/Filtering/ImageIntensity/include/itkVectorExpandImageFilter.hxx
- Modules/Filtering/ImageSources/include/itkGaussianImageSource.hxx
Looked for iterations in "Modules/Filtering" of the following form:
OutputIterator outIt(...);
while (!outIt.IsAtEnd())
{
...
++outIt;
}
And replaced them with the corresponding `for` loops:
for (OutputIterator outIt(...); !outIt.IsAtEnd(); ++outIt)
{
...
}
Such `for` loops appear preferable because they limits the scope of those `outIt` variables to where they are actually being used.
> STYLE: Replace `while (!outIt.IsAtEnd())` with `for` loops, in Filtering

- Modules/Core/Common/include/itkIndexRange.h
- Modules/Filtering/MathematicalMorphology/include/itkFlatStructuringElement.hxx
- Modules/Filtering/MathematicalMorphology/test/itkFlatStructuringElementTest.cxx
- Modules/IO/XML/include/itkStringTools.hxx
Avoided mentioning the very same type twice in a single variable declaration. Did so using Notepad++ v8.4.8, Find in Files, Regular expression:
Find what:  (\w[^ ]*)[ ]+(\w+) = \1(\(\);)
Replace with:  $1 $2{};
> STYLE: Replace `T var = T()` with modern `T var{}` value-initialization

- Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx
Reduced the scope of local `Point` and `ContinuousIndex` variables within `NonlinearThreadedGenerateData`. Note that these variables are very lightweight, so moving their declarations into a `for` loop won't harm the run-time performance.
> STYLE: Reduce scope ResampleImageFilter::NonlinearThreadedGenerateData

- Modules/Core/Transform/include/itkCompositeTransform.h
- Modules/Core/Transform/include/itkCompositeTransform.hxx
- Modules/Core/Transform/include/itkMultiTransform.h
- Modules/Core/Transform/include/itkMultiTransform.hxx
These default-constructors just simply either zero-initialized, cleared or default-constructed all of their data members.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3878 commit c2c67ac48cdd0206a103ee00962757dafb0714a8
"STYLE: Default default-constructors of class templates in Core/Common"
> STYLE: Default default-constructors MultiTransform, CompositeTransform

- Modules/ThirdParty/HDF5/src/itkhdf5/src/H5detect.c
Similar to work previously done: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/4370
The H5detect.c code is used to interrogate the compiler and hardware features.  The tests must be allowed to violate the ubsan checks during the interrogations.
Found when compiling with:
-fsanitize=undefined -fsanitize=integer -fsanitize=nullability -fno-sanitize-recover=undefined
[14/1947] Linking C executable bin/H5detect
ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5detect.c:1277:5: runtime error: store to misaligned address 0x60000211c061 for type 'short', which requires 2 byte alignment 0x60000211c061: note: pointer points here
00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00
^
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior …
> COMP: Suppress ubsan in H5detect.c code

- Utilities/Maintenance/AddEmptyDefaultMemberInitializers.cxx
The script that was used for the following pull requests:
- pull request #3851
- pull request #3913
- pull request #3917
- pull request #3941
- pull request #3945
> ENH: Add C++ script to add in-class `{}` member initializers to ITK

- Modules/Numerics/Statistics/include/itkHistogram.hxx
- Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.h
- Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.hxx
- COMP: Fix itkParallelSparseFieldLevelSetImageFilter uninitialized memory 
- COMP: Fix `itk::Histogram` uninitialized memory
- STYLE: Remove an unnecessary static_cast from Histogram::PrintSelf
- STYLE: Prefer in-class `{}` member initializers
- STYLE: Make `PrintSelf` implementation style consistent
- STYLE: Remove duplicate statement in `itk::Histogram::Initialize`
> COMP: Fix uninitialized memory Valgrind defects

- Modules/Core/Common/test/itkFactoryTestLib.cxx
Replaced the use of `std::allocator` by the equivalent `new Element[]` and `delete[]` statements. Renamed `m_MemoryAllocatedByAllocator` to `m_MemoryAllocatedByTestImportImageContainer`.
Aims to simplify the code, and make it easier to upgrade to C++17 and further. C++17 has deprecated the `std::allocator::allocate` and `std::allocator::destroy` function calls that are removed with this commit.
Aims to supersede commit "COMP: Replace std::allocator member function calls deprecated in C++17" from pull request #3969 
For the record, `std::allocator` was added to TestImportImageContainer with commit 1a3d16d5962be36a1598aed04efb1504aedab697, by Tom Vercauteren (@tvercaut), April 2, 2009.
> STYLE: Remove std::allocator from TestImportImageContainer (Common/test)

- Wrapping/Generators/Python/itk/support/types.py
For:
`np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
> COMP: Replace numpy.bool8 with np.bool_

- Modules/Core/Common/include/itkConstNeighborhoodIterator.h
- Modules/Core/Common/include/itkConstNeighborhoodIteratorWithOnlyIndex.h
- Modules/Core/Common/include/itkOffset.h
- Modules/Core/Common/include/itkSliceIterator.h
- Modules/Core/Common/include/itkVariableSizeMatrix.h
Declared those member functions `const`, to allowed evaluating an expression of the form `lhs @ rhs` (for an operator `@`), even when `lhs` is a `const` object or a `const` reference.
> Add missing `const` to binary operators implemented as member function

- CMake/ITKInitializeCXXStandard.cmake
- CMake/itkCompilerChecks.cmake
- CMakeLists.txt
- Documentation/SupportedCompilers.md
- Modules/Core/Common/include/itkMacro.h
- Modules/Core/Common/include/itkThreadPool.h
- Modules/Core/Common/test/itkSizeGTest.cxx
- Wrapping/macro_files/itk_auto_load_submodules.cmake
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2563 commit daec0fdd703b1bca16aeb07bc4e0a01101da950a "ENH: Upgrade ITK from C++11 to C++14"
Suggested by Dženan Zukić (@dzenanz) 😃 at https://github.com/InsightSoftwareConsortium/ITK/pull/3933#discussion_r1128770848 Still to be discussed.
More information about C++17:
- https://en.cppreference.com/w/cpp/17
- https://en.wikipedia.org/wiki/C%2B%2B17 
- https://isocpp.org/files/papers/p0636r0.html
- https://www.cppstories.com/2017/11/cpp17summary/
- etc...!
Discussion "Shall we start using C++17 at the master branch?" opened at https://discourse.itk.org/t/shall-we-start-using-c-17-at-the-master-branch/5828
> ENH: Upgrade ITK from C++14 to C++17

- Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h
- Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.hxx
With C++17, it is deprecated to redeclare a `constexpr` static data member outside the class definition (although it was required for C++11 and C++14).
This reverts pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2859 commit ad86850385455cecb1e3ce952ebfb0eb1c270809 "BUG: Fix constexpr linkage issue", Hans Johnson (@hjmjohnson), November 11, 2021.
> STYLE: Remove pre-C++17 definition constexpr data member `SupportSize`

- Modules/Filtering/ImageIntensity/include/itkRescaleIntensityImageFilter.h
GCC 5.2 was dropped with commit 45407f3560d91af247c95a1f48d21cbbb8ff6b8d "COMP: Require compiler versions that support C++17"
This reverts commit 114b902aac9282505efc386f93eeb46b3c5945c5 "BUG: Avoid an unexpected output of static_cast" by Hyun Jae Kang, September 29, 2015.
> STYLE: Remove GCC 5.2 specific code from IntensityLinearTransform

- Modules/Core/Common/include/itkImageBufferRange.h
- Modules/Core/Common/include/itkImageRegionRange.h
- Modules/Core/Common/test/itkImageRegionRangeGTest.cxx
- Modules/Core/ImageFunction/test/itkSumOfSquaresImageFunctionGTest.cxx
- Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx
- Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectGTest.cxx
- Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.hxx
- Modules/Filtering/Smoothing/include/itkMeanImageFilter.hxx
- Modules/Filtering/Smoothing/include/itkMedianImageFilter.hxx
- Modules/Filtering/Smoothing/test/itkMeanImageFilterGTest.cxx
- Modules/Filtering/Smoothing/test/itkMedianImageFilterGTest.cxx
Removed the template argument from the initialization of `ImageBufferRange` and `ImageRegionRange` objects, using C++17 class template argument deduction (CTAD).
> Use C++17 class template argument deduction for `ImageBufferRange` and `ImageRegionRange`

- Modules/Core/Common/include/itkGaussianDerivativeOperator.h
- Modules/Core/Common/include/itkTriangleHelper.hxx
- Modules/Filtering/Denoising/include/itkPatchBasedDenoisingImageFilter.hxx
- Modules/IO/VTK/test/itkVTKImageIOStreamTest.cxx
- Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.hxx
- Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.hxx
- Modules/Segmentation/LevelSets/include/itkSparseFieldLevelSetImageFilter.hxx
The `clamp` algorithm was added to the Standard Library of C++17 as proposed by the paper `An algorithm to "clamp" a value between a pair of boundary values`, 2015-05-17, by Martin Moene (@martinmoene) and Niels Dekker (who happens to be the author of this commit 😸): https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4536.html
> STYLE: Replace `std::min` and `std::max` calls with C++17 `std::clamp`

- Modules/Core/Common/include/itkLoggerThreadWrapper.hxx
- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
- Modules/Core/Common/include/itkSimpleFilterWatcher.h
- Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx
- Modules/Core/Common/src/itkMultiThreaderBase.cxx
- Modules/Core/Common/src/itkOutputWindow.cxx
- Modules/Core/Common/src/itkStdStreamLogOutput.cxx
- Modules/Core/Common/src/itkThreadLogger.cxx
- Modules/Core/GPUCommon/include/itkGPUImageDataManager.hxx
- Modules/Filtering/DisplacementField/include/itkInvertDisplacementFieldImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkDirectedHausdorffDistanceImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkIsoContourDistanceImageFilter.hxx
- Modules/Filtering/FFT/include/itkFFTWCommon.h
- Modules/Filtering/FFT/include/itkFFTWCommonExtended.h
- Modules/Filtering/ImageIntensity/include/itkShiftScaleImageFilter.hxx
- Modules/Filtering/ImageLabel/include/itkScanlineFilterCommon.h
- Modules/Filtering/ImageStatistics/include/itkMinimumMaximumImageFilter.hxx
- Modules/Filtering/ImageStatistics/include/itkStatisticsImageFilter.hxx
- Modules/Filtering/LabelMap/include/itkBinaryImageToLabelMapFilter.hxx
- Modules/Filtering/LabelMap/include/itkChangeRegionLabelMapFilter.hxx
- Modules/Filtering/LabelMap/include/itkLabelMapFilter.hxx
- Modules/IO/ImageBase/src/itkImageIOBase.cxx
- Modules/IO/ImageBase/src/itkImageIOFactory.cxx
- Modules/Numerics/Statistics/include/itkImageToHistogramFilter.hxx
- Modules/Numerics/Statistics/include/itkMaskedImageToHistogramFilter.hxx
- Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4.hxx
- Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentImageFilter.hxx
- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
Removed the template argument from `std::lock_guard<Mutex>` variable declarations, and declared all of them `const`.
Note that it does not appear necessary to replace C++11 `std::lock_guard` by C++17 `std::scoped_lock`, as `lock_guard` is still appreciated for its simplicity. For details, check Stack Overflow [std::lock_guard or std::scoped_lock?](https://stackoverflow.com/questions/43019598/stdlock-guard-or-stdscoped-lock) reply by Howard Hinnant at https://stackoverflow.com/a/60172828 (edited October 31, 2020), saying:
> For the common case that one needs to lock exactly one mutex, `std::lock_guard` has an API that is a little safer to use than `scoped_lock`.
> Declare lock_guard variables `const`, use C++17 class template argument deduction (CTAD)

- Examples/DataRepresentation/Path/PolyLineParametricPath1.cxx
- Modules/Core/Common/include/itkImageBase.h
- Modules/Core/Common/include/itkPhasedArray3DSpecialCoordinatesImage.h
- Modules/Core/Common/test/itkImageTransformTest.cxx
- Modules/Core/Common/test/itkPhasedArray3DSpecialCoordinatesImageTest.cxx
- Modules/Core/ImageAdaptors/include/itkImageAdaptor.h
- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
It would usually be a mistake when a user would unintentionally ignore the return value of those member functions. Specifically, the overloads of `TransformPhysicalPointToIndex` and `TransformPhysicalPointToContinuousIndex` that have two parameters both return a `bool` value. If this return value can be ignored, it is preferable (for performance reasons) to call the corresponding overload that has one parameter instead.
The compiler may now produce a warning when the return value of any of those member functions is unintentionally ignored.
> ENH: Add C++17 `[[nodiscard]]` to Image "Transform" member functions

- Modules/Filtering/Smoothing/include/itkMeanImageFilter.hxx
- Modules/Filtering/Smoothing/include/itkMedianImageFilter.hxx
Removed a few cases of class template argument deduction, because of compile errors from [RogueResearch17/Mac10.15-AppleClang-rel](https://open.cdash.org/viewBuildError.php?buildid=8602009), saying:
> error: member reference base type 'ImageRegionRange' is not a structure or union
Caused by clang Bug 39663 "Class template argument deduction with deduced type fails when accessing member", reported by Baruch, 2018-11-14 at https://bugs.llvm.org/show_bug.cgi?id=39663 and fixed on 2020-10-08. The fix appears to be included with LLVM Clang 12.0.0.
This partially reverts pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3989 commit 8ee4d9a410556cd1619c188e8e588710805b2da8 "STYLE: Use C++17 CTAD for `ImageRegionRange`"
> COMP: Remove CTAD because of clang "error: member reference base" bug

- Modules/Core/GPUCommon/src/itkOpenCLUtil.cxx
- Modules/IO/ImageBase/test/itkConvertBufferTest.cxx
- Modules/IO/ImageBase/test/itkImageIOBaseTest.cxx
- Modules/IO/LSM/src/itkLSMImageIO.cxx
By Visual Studio, Replace in Files, using the following regular expression:
Find what: sizeof\((\w+)\) / sizeof\(\1\[0\]\)
Find what: sizeof\((.+)\) / sizeof\(\*\1\)
Find what: sizeof\((\w+)\) / sizeof\(.*\)
Replace with: std::size($1)
(The third regular expression, `sizeof\((\w+)\) / sizeof\(.*\)` was only applied to itkConvertBufferTest.cxx, as it cannot be generally applied).
`std::size(array)` appears to be a more readable and safer way to retrieve the number of elements of a C-style array. It is also `constexpr`.
> STYLE: Replace `sizeof(array) / sizeof(array[0])` with C++17 `std::size`

- Modules/Core/Common/include/itkLoggerThreadWrapper.hxx
- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
- Modules/Core/Common/include/itkSimpleFilterWatcher.h
- Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx
- Modules/Core/Common/src/itkMultiThreaderBase.cxx
- Modules/Core/Common/src/itkOutputWindow.cxx
- Modules/Core/Common/src/itkStdStreamLogOutput.cxx
- Modules/Core/Common/src/itkThreadLogger.cxx
- Modules/Core/GPUCommon/include/itkGPUImageDataManager.hxx
- Modules/Filtering/DisplacementField/include/itkInvertDisplacementFieldImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkDirectedHausdorffDistanceImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkIsoContourDistanceImageFilter.hxx
- Modules/Filtering/FFT/include/itkFFTWCommon.h
- Modules/Filtering/FFT/include/itkFFTWCommonExtended.h
- Modules/Filtering/ImageIntensity/include/itkShiftScaleImageFilter.hxx
- Modules/Filtering/ImageLabel/include/itkScanlineFilterCommon.h
- Modules/Filtering/ImageStatistics/include/itkMinimumMaximumImageFilter.hxx
- Modules/Filtering/ImageStatistics/include/itkStatisticsImageFilter.hxx
- Modules/Filtering/LabelMap/include/itkBinaryImageToLabelMapFilter.hxx
- Modules/Filtering/LabelMap/include/itkChangeRegionLabelMapFilter.hxx
- Modules/Filtering/LabelMap/include/itkLabelMapFilter.hxx
- Modules/IO/ImageBase/src/itkImageIOBase.cxx
- Modules/IO/ImageBase/src/itkImageIOFactory.cxx
- Modules/Numerics/Statistics/include/itkImageToHistogramFilter.hxx
- Modules/Numerics/Statistics/include/itkMaskedImageToHistogramFilter.hxx
- Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4.hxx
- Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentImageFilter.hxx
- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
Addressed `-Wctad-maybe-unsupported` warnings from Mac10.15-AppleClang-rel (AppleClang 12.0.0.12000032), saying:
> warning: 'lock_guard' may not intend to support class template argument deduction [-Wctad-maybe-unsupported]
Revert pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3986 commit 3bfdc2890844900e703d69a9cc435a21321bcc91 "STYLE: Use C++17 class template argument deduction (CTAD) for lock_guard"
> COMP: Remove use of C++17 CTAD from `lock_guard` variable declarations

- Modules/Core/Common/include/itkImageBufferRange.h
- Modules/Core/Common/include/itkImageRegionRange.h
Addressed `-Wctad-maybe-unsupported` warnings from Mac10.15-AppleClang-rel (AppleClang 12.0.0.12000032), saying:
> warning: 'ImageBufferRange' may not intend to support class template argument deduction [-Wctad-maybe-unsupported]
> note: add a deduction guide to suppress this warning
> COMP: Add CTAD deduction guides to ImageBufferRange and ImageRegionRange

- Modules/Compatibility/Deprecated/include/itkVectorResampleImageFilter.hxx
- Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.h
- Modules/Core/ImageFunction/include/itkImageFunction.h
- Modules/Nonunit/Review/include/itkMultiphaseDenseFiniteDifferenceImageFilter.hxx
- Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.hxx
- Modules/Nonunit/Review/include/itkRegionBasedLevelSetFunctionData.hxx
- Modules/Nonunit/Review/include/itkScalarChanAndVeseDenseLevelSetImageFilter.hxx
- Modules/Nonunit/Review/include/itkScalarChanAndVeseSparseLevelSetImageFilter.hxx
- Modules/Nonunit/Review/test/itkDiscreteGaussianDerivativeImageFunctionTest.cxx
- Modules/Nonunit/Review/test/itkDiscreteGradientMagnitudeGaussianImageFunctionTest.cxx
- Modules/Nonunit/Review/test/itkDiscreteHessianGaussianImageFunctionTest.cxx
- Modules/Registration/FEM/include/itkFEMFiniteDifferenceFunctionLoad.hxx
- Modules/Registration/FEM/test/itkFEMFiniteDifferenceFunctionLoadTest.cxx
Replacing `TransformPhysicalPointToIndex(point, index)` with `index = TransformPhysicalPointToIndex(point)` appeared to be a no-brainer, while replacing the `TransformPhysicalPointToContinuousIndex` calls was somewhat more challenging... but still no rocket science.
> Fix TransformPhysicalPointToIndex, TransformPhysicalPointToContinuousIndex  `[[nodiscard]]` warnings

- Modules/Nonunit/Review/test/itkDiscreteGradientMagnitudeGaussianImageFunctionTest.cxx
- Modules/Nonunit/Review/test/itkDiscreteHessianGaussianImageFunctionTest.cxx
Fixed compile errors saying:
> error C2065: 'cindex': undeclared identifier
and:
> error C2039: 'ContinuousIndexType': is not a member of 'itk::ContinuousIndex'
These compile errors were introduced by pull request #4000 commit 7cda5badd0ae7802103421b6625e46bc956f6cb9 "COMP: Fix TransformPhysicalPointToContinuousIndex `nodiscard` warnings"
> Fix Nonunit/Review/test compile errors introduced by pull request 4000 

- Modules/Filtering/Smoothing/include/itkBinomialBlurImageFilter.hxx
Fixed Debug compilation erors saying:
> error C2065: 'num_reps': undeclared identifier
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3996 commit cd97879e6bfec6cd9a33a3dd374d68cf4ff4303e "COMP: Remove unused variables"
The `itkDebugMacro` statement that got this error does not seem to be of interest anymore.
> COMP: Fix BinomialBlurImageFilter error, num_reps undeclared identifier

- Modules/Core/Common/include/itkImageBufferRange.h
- Modules/Core/Common/include/itkImageRegionRange.h
Both `ImageBufferRange` and `ImageRegionRange` support CTAD for their `TImage` template parameter. This PR aims to make it clearer which of their constructors support CTAD. And it aims to use `TImage` consistently (instead of _sometimes_ using an `ImageType` alias) for both of them.
> Remove private `ImageBufferRange::ImageType` alias, add note to CTAD supporting constructors

- Modules/Nonunit/Review/test/itkDiscreteGradientMagnitudeGaussianImageFunctionTest.cxx
- Modules/Nonunit/Review/test/itkDiscreteHessianGaussianImageFunctionTest.cxx
Added missing `template` keywords to TransformPhysicalPointToContinuousIndex calls in Nonunit/Review tests.
Addressed compile errors from Ubuntu-22.04-gcc11.2-TBB-Debug saying:
> error: expected primary-expression before '>' token
These compile errors were introduced by pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4000 commit 7cda5badd0ae7802103421b6625e46bc956f6cb9
"COMP: Fix TransformPhysicalPointToContinuousIndex `nodiscard` warnings"
- Follow-up to pull request #4004
> COMP: Add `template` to TransformPhysicalPointToContinuousIndex in tests

- Wrapping/Generators/Python/PyBase/pyBase.i
Replaced calls to TransformPhysicalPointToIndex(point, idx) and TransformPhysicalPointToContinuousIndex(point, idx) by the corresponding faster overloads.
Aims to address warnings at Windows_NT-Build3495-master-Python https://open.cdash.org/viewBuildError.php?type=1&buildid=8615447 saying:
> s-build\Wrapping\Modules\ITKCommon\itkImagePython.cpp: warning C4834:
> discarding return value of function with 'nodiscard' attribute
----
Please note: I don't really know how this Python wrapping code works, so I'm basically just _guessing_ how it should be fixed! So please review with extra care 😃!
> PERF: Use faster TransformPhysicalPointToIndex/ContinuousIndex in Python

- CMake/ITKSetStandardCompilerFlags.cmake
Enabled a compiler warning from both GCC and Clang on possibly unintended use of CTAD.
Triggered by our discussions at
- https://github.com/InsightSoftwareConsortium/ITK/pull/3997
- https://github.com/InsightSoftwareConsortium/ITK/pull/3986
> COMP: Enable warning on C++17 class template argument deduction (CTAD)

- Modules/Nonunit/Review/include/itkMultiphaseDenseFiniteDifferenceImageFilter.hxx
- Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.hxx
- Modules/Nonunit/Review/include/itkScalarChanAndVeseDenseLevelSetImageFilter.hxx
- Modules/Nonunit/Review/include/itkScalarChanAndVeseSparseLevelSetImageFilter.hxx
Declared local "IndexType" variables in "Nonunit/Review" that are initialized by the result of a TransformPhysicalPointToIndex(point) call `const`.
Follow-up to commit 49ece7f60841b79c306b9a709ffcee228ce9c347 "COMP: Fix TransformPhysicalPointToIndex `nodiscard` warnings"
Suggested by Matt McCormick (@thewtex) at https://github.com/InsightSoftwareConsortium/ITK/pull/4000#discussion_r1160226814
> STYLE: Add `const` to TransformPhysicalPointToIndex results in "Review"

- Modules/Core/Common/test/itkPointSetToImageFilterTest1.cxx
- Modules/Filtering/Deconvolution/include/itkProjectedIterativeDeconvolutionImageFilter.hxx
- Modules/Filtering/ImageFeature/test/itkZeroCrossingImageFilterTest.cxx
- Modules/Registration/FEM/test/itkVTKTetrahedralMeshReader.hxx
- Modules/Registration/Metricsv4/include/itkJointHistogramMutualInformationGetValueAndDerivativeThreader.hxx
- Modules/Registration/Metricsv4/test/itkEuclideanDistancePointSetMetricRegistrationTest.cxx
- Modules/Registration/Metricsv4/test/itkObjectToObjectMultiMetricv4Test.cxx
- Modules/Segmentation/KLMRegionGrowing/test/itkRegionGrow2DTest.cxx
- Modules/Segmentation/LevelSets/test/itkSparseFieldFourthOrderLevelSetImageFilterTest.cxx
Replaced initialization by `NumericTraits<T>::ZeroValue()` with empty `{}` initializers. Did so by Replace in Files, using regular expressions:
Find what: (.+)([ ]+\w+) = NumericTraits<\1>::ZeroValue\(\);
Find what: (.+)([ ]+\w+) = itk::NumericTraits<\1>::ZeroValue\(\);
Find what: (.+)([ ]+\w+) =\r\n[ ]+NumericTraits<\1>::ZeroValue\(\);
Find what: (.+)([ ]+\w+) =\r\n[ ]+itk::NumericTraits<\1>::ZeroValue\(\);
Replace with: $1$2{};
Follow-up to pull request #3958 commit 42b0bfc0771652ade6a1055b00efbcf94376c20b "STYLE: Replace `T var = NumericTraits<T>::ZeroValue()` with `T var{}`" (which did not yet address initializations of which the specification of `T` has one or more spaces inside, and initializations that took multiple lines of code.)
> STYLE: Replace `T var = NumericTraits<T>::ZeroValue()` having whitespace

- Modules/Core/Common/include/itkImageHelper.h
- Modules/Core/Common/include/itkImageRegionRange.h
Used "constexpr if" instead of overloading helper functions for `std::true_type` and `std::false_type` (tag dispatching), in order to simplify the code.
> Use C++17 "constexpr if" in `ImageRegionRange` and `ImageHelper` instead of  `true_type`/`false_type` tag dispatching

- Modules/Core/Common/include/itkAnnulusOperator.h
- Modules/Filtering/DistanceMap/include/itkDirectedHausdorffDistanceImageFilter.h
- Modules/Filtering/ImageIntensity/include/itkMaskImageFilter.h
- Modules/Filtering/ImageIntensity/include/itkMaskNegatedImageFilter.h
- Modules/Filtering/ImageIntensity/include/itkShiftScaleImageFilter.h
- Modules/Filtering/LabelMap/include/itkStatisticsLabelMapFilter.h
Replaced brace-initialization by `NumericTraits<T>::ZeroValue()` with empty `{}` initializers. Did so by Replace in Files, using regular expressions:
Find what: (\w.+)( .+){ NumericTraits<\1>::ZeroValue\(\) };
Replace with:  $1$2{};
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3958 commit 42b0bfc0771652ade6a1055b00efbcf94376c20b
"STYLE: Replace `T var = NumericTraits<T>::ZeroValue()` with `T var{}`"
> STYLE: Replace `T var{ NumericTraits<T>::ZeroValue() }` with `T var{}`

- Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.hxx
- Modules/Core/Transform/include/itkAffineTransform.hxx
- Modules/Core/Transform/include/itkAzimuthElevationToCartesianTransform.hxx
- Modules/Core/Transform/include/itkCompositeTransform.hxx
- Modules/Core/Transform/include/itkRigid2DTransform.h
- Modules/Numerics/Statistics/include/itkHistogram.hxx
- Modules/Numerics/Statistics/include/itkImageToNeighborhoodSampleAdaptor.hxx
This fixes some of the compile errors on VS2017.
They were introduced around the time C++17 was enabled. The first error message was:
```log
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): error C2244: 'itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::GetMeasurementVector': unable to match function definition to an existing declaration
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(473): note: see declaration of 'itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::GetMeasurementVector'
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): note: definition
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): note: 'const …
```
> STYLE: Change some declarations to use trailing return type

- Modules/Core/Common/include/itkImageScanlineConstIterator.h
- Modules/Filtering/DisplacementField/include/itkTransformToDisplacementFieldFilter.hxx
- Modules/Filtering/ImageGrid/include/itkBinShrinkImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkExpandImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx
- Modules/Filtering/ImageLabel/include/itkBinaryContourImageFilter.hxx
- Modules/Filtering/ImageLabel/include/itkLabelContourImageFilter.hxx
- Modules/Filtering/LabelMap/include/itkBinaryImageToLabelMapFilter.hxx
- Modules/Filtering/Thresholding/include/itkThresholdImageFilter.hxx
- Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentImageFilter.hxx
- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
Removed the local type aliases of `ImageScanlineIterator` and `ImageScanlineConstIterator` that were previously only used to declare a single local variable, and used C++17 class template argument deduction instead.
> Remove local ImageScanlineIterator type aliases, using C++17 CTAD, and extend `ImageScanlineConstIterator` deduction guide

- Modules/Core/Common/include/itkSimpleDataObjectDecorator.h
- Modules/Core/Common/include/itkSimpleDataObjectDecorator.hxx
Removed obsolete "-Wmaybe-uninitialized" and Purify UMR (uninitialized memory read) workarounds.
The Purify workaround is from commit 7001c5ceefb92ffc5745682d61960368dfab6585 "FIX: attempt at purify UMR fix", Jim Miller, March 18, 2004. The "-Wmaybe-uninitialized" workaround is from commit 3495d7f60afafc0c05809ea8ea8ec98125ec1334 "COMP: Suppress maybe-uninitialized in SimpleDataObjectDecorator Component", Matt McCormick (@thewtex), May 11, 2018. Neither of these two workarounds should be necessary anymore, now that `m_Component` has an in-class `{}` default member initializer.
> STYLE: Default default-constructor SimpleDataObjectDecorator

- Modules/Core/Common/include/itkResourceProbe.hxx
- Modules/Core/Transform/include/itkAffineTransform.hxx
- Modules/Core/Transform/include/itkBSplineBaseTransform.hxx
- Modules/Core/Transform/include/itkMatrixOffsetTransformBase.hxx
- Modules/Core/Transform/include/itkScaleTransform.hxx
- Modules/Filtering/Smoothing/include/itkDiscreteGaussianImageFilter.hxx
- Modules/Numerics/Optimizersv4/include/itkLBFGS2Optimizerv4.hxx
- Modules/Numerics/Statistics/include/itkHistogram.hxx
- Modules/Numerics/Statistics/include/itkMembershipSample.hxx
- Modules/Numerics/Statistics/include/itkSubsample.hxx
This is a follow-up to b18668b639becf9e3dc6324ca68f915ab7bf0a1e and b37ac532060361739a2653bbbd2176dee0282d09.
It reapplied regex replace from b18668b639becf9e3dc6324ca68f915ab7bf0a1e.
> STYLE: Use trailing return type instead of typename + dependent type

- Modules/Filtering/DisplacementField/include/itkTransformToDisplacementFieldFilter.hxx
- Modules/Filtering/DistanceMap/include/itkApproximateSignedDistanceMapImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkBinShrinkImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkExpandImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkFlipImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkPasteImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkResampleImageFilter.hxx
- Modules/Filtering/ImageIntensity/include/itkNaryFunctorImageFilter.hxx
- Modules/Filtering/ImageLabel/include/itkBinaryContourImageFilter.hxx
- Modules/Filtering/ImageLabel/include/itkLabelContourImageFilter.hxx
- Modules/Filtering/LabelMap/include/itkBinaryImageToLabelMapFilter.hxx
- Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentImageFilter.hxx
Looked for iterations of the following form:
ImageScanlineIterator outIt(output, outputRegionForThread);
while (!outIt.IsAtEnd())
{
...
outIt.NextLine();
}
And replaced them with the corresponding `for` loops.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3957 commit 31c713eb105eff4ba87a457a24a23ef4a6eb3071 "STYLE: Replace `while (!outIt.IsAtEnd())` with `for` loops, in Filtering"
> Replace ImageScanlineIterator `while` loops with `for` loops, move iterator declarations into `for` loop init-statements

- Modules/Core/Common/include/itkResourceProbe.h
- Modules/Core/Common/include/itkResourceProbe.hxx
Follow-up to:
"PERF: Remove SystemInformation data from ResourceProbe, fix issue #350"
Pull request https://github.com/InsightSoftwareConsortium/ITK/pull/351
Commit 747f3d143359cf15c3c4ed9e266125f96d198f8d, 2018-12-24
> STYLE: Remove empty ResourceProbe legacy function GetSystemInformation()

- CMake/itkCompilerChecks.cmake
- Documentation/SupportedCompilers.md
- Modules/Core/Common/include/itkMacro.h
Enabling C++17 broke VS2017 due to its numerous bugs. See discussion: https://discourse.itk.org/t/c-17-breaks-visual-studio-2017-drop-support/5884
> ENH: Drop support for MSVC toolset v141 aka Visual Studio 2017

- Testing/ContinuousIntegration/AzurePipelinesBatch.yml
This is a follow-up to 140f3c249fbb20c4f4a1607e563e19ee9a9cbd78. Thanks to @issakomi for pointing out the oversight. As VS2017 has been broken for a month, this CI test not longer gets triggered.
> ENH: Update ContinuousIntegration Batch test to use VS2022

- Wrapping/Generators/Python/Tests/CMakeLists.txt
- Wrapping/Generators/Python/Tests/extras.py
- Wrapping/Generators/Python/itk/support/extras.py
Typical usage:
`img = itk.imread(filename="./my_dicom_dir", series_uid="1.2.3.456.789.101112.1314")`
If filename is a directory of DICOM files, and series_uid is a string, it will read the DICOM series that matches this series_uid name.  If series_uid is an integer, it will read the series_uid'th DICOM series in the directory (using python notation, e.g., -1 is the last DICOM series in the directory). If unspecified, it will read the first series in the directory.
This does represent a change in the default behavior in that it used to raise an exception if a DICOM directory with more than one series was passed to imread, and now it will read the first series in that directory.
Closes #4038 
- Extends API of imread() in wrapping/generators/python/itk/support/extras.py to have series_uid as …
> ENH: Add series_uid arg to imread() for dicom series selection

- Modules/Filtering/MathematicalMorphology/include/itkMathematicalMorphologyEnums.h
Using gcc-13 ITK does not compile as discussed in this form entry: (https://discourse.itk.org/t/building-itk-error-with-algorithim-module/5927/9). Was able to be fixed thanks to @dzenanz with the inclusion of  <cstdint> to itkMathematicalMorphologyEnums.h and specifying std::uint8_t on line 41.
> COMP: gcc-13 compatability

- Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h
Addresses complation warning with clang-1316.0.21.2.5:
definition of implicit copy constructor for 'QualifiedIterator<true>' is deprecated because it has a user-declared copy assignment operator
> COMP: Add explicit default copy constructor

- Utilities/KWStyle/ITKOverwrite.txt
*.cxx files may have an unnamed namespace, instead of `namespace itk`, as their first namespace. For example Wrapping/Generators/Python/PyUtils/itkPyCommand.cxx This would cause undeserved failures of the `Namespace` check of KWStyle.
----
Aims to supersede (i.e. replace) pull request #4047:
- #4047
Based on a comment from @thewtex at https://github.com/InsightSoftwareConsortium/ITK/pull/4047#issuecomment-1552084915
> COMP: Disable KWStyle check "error: namespace is wrong" on *.cxx files

- Modules/Registration/RegistrationMethodsv4/test/CMakeLists.txt
- Modules/Registration/RegistrationMethodsv4/test/itkExponentialImageRegistrationTest.cxx
Increase coverage for `itk::ConstantVelocityFieldTransform`:
- Exercise other getter method by printing the output to the std output.
Add the values for the ivars of the filter as arguments to the test.
> ENH: Increase coverage for `itk::ConstantVelocityFieldTransform`

- Modules/Core/Common/include/itkImageBufferRange.h
- Modules/Core/Common/include/itkImageRegionRange.h
- Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h
Used SFINAE (`enable_if`) to implement non-const to const conversion for the iterator types of `ImageBufferRange` and `ImageRegionRange`. Followed the Rule of Zero for those types.
Prevents potential clang warnings, as reported before (pull request #4049) by Bradley Lowekamp (@blowekamp):
> definition of implicit copy constructor for 'QualifiedIterator<true>'
> is deprecated because it has a user-declared copy assignment operator
Documented that the iterator types of `ShapedImageNeighborhoodRange` now unconditionally follow the Rule of Zero, and did the same for the iterator types of `ImageBufferRange` and `ImageRegionRange`.
Follow-up to pull request #4049 commit df6aa66e40c6e4ce91c05df95f5364f3558ab43a "COMP: QualifiedIterator follow rule of zero", merged on 19 May, 2023
> COMP: Rule of Zero, SFINAE for ImageBufferRange, ImageRegionRange iterators, update ShapedImageNeighborhoodRange documentation

- Modules/Filtering/MathematicalMorphology/src/itkMathematicalMorphologyEnums.cxx
With GCC 13.1.1 `<cstdint>` is no longer implicitly included causing build failure
```
/home/fabio/Dev/AURNEW/insight-toolkit/src/InsightToolkit-5.3.0/Modules/Filtering/MathematicalMorphology/include/itkMathematicalMorphologyEnums.h:23:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
22 | #include "ITKMathematicalMorphologyExport.h"
+++ |+#include <cstdint>
23 | 
```
> COMP: add missing header with GCC 13.1.1

- CMake/ITKSetStandardCompilerFlags.cmake
This reverts commit b50647bf5e73517fd9645803d756bd1dd045629a.
Originally this flag was added to sppress inline warnings on gcc compilers from 2011 (which are no longer supported).
The `-funit-at-a-time` flag is a default flag for all optimization levels -O1 and above on gcc compilers that support it.
New versions of clang compiler do not support this flag: "clang: warning: optimization flag '-funit-at-a-time' is not supported"
The removal of this flag returns all the default compiler flags to flags related to warnings only.
> COMP: Remove clang unsupported compiler flag from default

- Modules/Filtering/ImageFeature/include/itkLaplacianSharpeningImageFilter.h
Consolidate `itk::LaplacianSharpeningImageFilter` `UseImageSpacing` ivar documentation: group together the `itkBooleanMacro` macro and the `Set/Get` methods, and document them at a single place.
> DOC: Consolidate `LaplacianSharpeningImageFilter` `UseImageSpacing` doc

- Modules/Core/Common/include/itkExtractImageFilter.hxx
- Modules/Core/Common/include/itkVectorContainer.h
- Modules/Core/Common/include/itkVectorContainer.hxx
- Modules/Filtering/ImageGrid/include/itkInterpolateImageFilter.h
- Modules/Filtering/ImageGrid/include/itkInterpolateImageFilter.hxx
- Modules/Nonunit/Review/include/itkDirectFourierReconstructionImageToImageFilter.hxx
- Modules/Segmentation/LevelSets/include/itkLevelSetNeighborhoodExtractor.hxx
Clean up method Doxygen documentation:
- Consolidate documentation so that methods are documented in the header files.
- Remove the documentation of trivial methods: constructors, destructors, `PrintSelf` methods, etc.
- Remove empty method documentation blocks from implementation file.
Follow-up to d58bf56.
> DOC: Clean up method Doxygen documentation

- Modules/Numerics/Optimizersv4/include/itkRegistrationParameterScalesEstimator.h
- Modules/Numerics/Optimizersv4/test/itkAutoScaledGradientDescentRegistrationOnVectorTest.cxx
Add getter and boolean macros to
`itk::RegistrationParameterScalesEstimator` ivars.
Check the expected values in the test using the appropriate itk testing macros.
> ENH: Add macros to `itk::RegistrationParameterScalesEstimator` ivars

- Modules/Numerics/Optimizersv4/test/itkAutoScaledGradientDescentRegistrationOnVectorTest.cxx
Increase coverage for
`itk::RegistrationParameterScalesFromPhysicalShift`:
- Exercise basic object methods using the `ITK_EXERCISE_BASIC_OBJECT_METHODS` macro. Remove redundant calls to print the filter: rely on the basic method exercising macro call.
> ENH: Increase `RegistrationParameterScalesFromPhysicalShift` coverage

- Modules/Numerics/Optimizersv4/test/itkAutoScaledGradientDescentRegistrationOnVectorTest.cxx
Add missing semicolon after `ITK_EXERCISE_BASIC_OBJECT_METHODS` macro call in test.
Fixes:
```
itkAutoScaledGradientDescentRegistrationOnVectorTest.cxx:130:116: error: expected ';' after 'static_assert'
shiftScalesEstimator, RegistrationParameterScalesFromPhysicalShift, RegistrationParameterScalesFromShiftBase)
^
;
```
Reported in:
https://open.cdash.org/viewBuildError.php?buildid=8785957
Oversight introduced in commit 165fb5b6fed0f7f9f0669570472905b9931e64b4.
> BUG: Add semicolon after `ITK_EXERCISE_BASIC_OBJECT_METHODS` call

- Modules/Core/Common/include/itkMacro.h
- Modules/IO/XML/include/itkDOMNode.h
- Modules/IO/XML/include/itkDOMTextNode.h
Avoids an unnecessary copy (possibly involving memory allocation) of the argument of a Set member function.
Note that `itkSetMacro` calls that define a Set member function which passes the argument by const-reference must explicitly specify the `const` keyword now.
> PERF: Use `std::move` inside `itkSetMacro`, declare parameter non-const

- Modules/Nonunit/Review/include/itkAttributeMorphologyBaseImageFilter.hxx
- Modules/Nonunit/Review/include/itkConformalFlatteningMeshFilter.hxx
- Modules/Nonunit/Review/include/itkMiniPipelineSeparableImageFilter.hxx
- Modules/Remote/Ultrasound.remote.cmake
Change the Insight Journal handle links to insight-journal links or remove handle links where insight-journal links were already present: handle links are no longer valid.
Remove completely the documentation blocks containing the handle links from implementation files as the corresponding blocks containing the insight-journal links are already present in the header files.
Left behind in commit e936cabc7aaef3764de27880fd1fe7846d0ba768.
> DOC: Change the Insight Journal handle links to insight-journal links

- Modules/Filtering/ImageStatistics/include/itkLabelStatisticsImageFilter.h
- Modules/Filtering/ImageStatistics/include/itkLabelStatisticsImageFilter.hxx
Make `itk::LabelStatisticsImageFilter::PrintSelf` implementation style consistent following the ITK SWG coding style guideline and the available ITK macros:
- Print only the class instance variables.
- Use the `os << indent << "{ivarName}: " << m_ivarName << std::endl` recipe: do not print the leading `m_` of the ivar; use a colon after printing its name; leave a whitespace between the colon and the printed value of the ivar.
- For boolean ivars print `On`/`Off` according to their values using the ternary operator.
- Take advantage of the output stream `<<` insertion operator overload for `std::vector` types in the `itk::print_helper` namespace defined in `itkPrintHelper.h` to print such types consistently.
- Cast custom types to their numerical values using `itk::NumericTraits::PrinType` …
> STYLE: Increase `itk::LabelStatisticsImageFilter::PrintSelf` consistency

- Modules/Nonunit/Review/include/itkConformalFlatteningMeshFilter.h
- Modules/Nonunit/Review/include/itkConformalFlatteningMeshFilter.hxx
Clean up method Doxygen documentation for
`itk::ConformalFlatteningMeshFilter`:
- Consolidate documentation so that methods are documented in the header files.
- Remove empty method documentation blocks from implementation file.
Take advantage of the commit to make the modified method documentation
blocks have a consistent line length.
Follow-up to d58bf56fe2320fe3c7a451c96e3d8cd5e7c68358.
> DOC: Clean up `itk::ConformalFlatteningMeshFilter` Doxygen documentation

- CMake/itkTargetLinkLibrariesWithDynamicLookup.cmake
From https://open.cdash.org/build/8807486/configure
```log
...
-- Check the value of the 22nd bit of a 32-bit quiet-NaN - 1 CMake Warning (dev) at /home/vsts/work/1/s-build/Wrapping/CMakeTmp/ITK_UNDEFINED_SYMBOLS_ALLOWED/CMakeLists.txt:2 (project):
cmake_minimum_required() should be called prior to this top-level project()
call.  Please see the cmake-commands(7) manual for usage documentation of
both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Performing Test ITK_UNDEFINED_SYMBOLS_ALLOWED - Success ...
```
> Avoid CMake warning caused by feature test

- Modules/Core/Common/include/itkVertexCell.hxx
Fix method parameter bound mismatch warning in `itk::VertexCell`: do not specify the dimensionality of the array in the implementation file so that it matches the method declaration, and they match the `itk::CellInterface` superclass method declaration.
Fixes:
```
Core/Common/include/itkVertexCell.hxx:172:72:
warning: argument 'pcoord' of type 'CoordRepType[2]' with mismatched bound [-Warray-parameter]
CoordRepType              pcoord[2],
^
Core/Common/include/itkVertexCell.h:111:32:
note: previously declared as 'CoordRepType[]' here
CoordRepType[],
^
```
raised, for example, in:
https://open.cdash.org/viewBuildError.php?type=1&buildid=8832331
> COMP: Fix method parameter bound mismatch warning in `itk::VertexCell`

- Modules/Core/Common/include/itkTetrahedronCell.hxx
- Modules/Core/Common/include/itkTriangleCell.hxx
Fix method parameter bound mismatch warning in `itk::TriangleCell` and `itk::TetrahedronCell`: do not specify the dimensionality of the array in the implementation file so that it matches the method declaration, and they match the `itk::CellInterface` superclass method declaration.
Fixes:
```
Modules/Core/Common/include/itkTriangleCell.hxx:452:74:
warning: argument 'pcoord' of type 'CoordRepType[3]' with mismatched bound [-Warray-parameter]
CoordRepType              pcoord[3],
^
Modules/Core/Common/include/itkTriangleCell.h:130:32:
note: previously declared as 'CoordRepType[]' here
CoordRepType[],
^
```
and
```
Modules/Core/Common/include/itkTetrahedronCell.hxx:85:77:
warning: argument 'pcoord' of type …
```
> COMP: Fix method parameter bound mismatch warning in misc cell classes

- Modules/Core/Common/include/itkTetrahedronCell.h
- Modules/Core/Common/include/itkTetrahedronCell.hxx
- Modules/Core/Common/include/itkTriangleCell.h
- Modules/Core/Common/include/itkTriangleCell.hxx
- Modules/Core/Common/include/itkVertexCell.h
- Modules/Core/Common/include/itkVertexCell.hxx
Document miscellaneous cell class methods in header files: Doxygen picks the method documentation from the header files, and leaves the method documentation empty if it does not find it there.
Increase consistency in the characters used for documentation blocks and follow the ITK SW Guideline: prefer using single-line comments for separation of logical blocks.
Take advantage of the commit to fix typos in the method documentation.
> DOC: Document miscellaneous cell class methods in header files

- Modules/Core/Common/include/itkConicShellInteriorExteriorSpatialFunction.h
Avoid documenting ivar default values in
`itk::ConicShellInteriorExteriorSpatialFunction` since:
- All ivar values should be initialized to some default value.
- When default values are changed, it is easy to forget about updating the documentation and making it inconsistent with the actual value in the code.
> DOC: Avoid documenting ivar default values in SpatialFunction class

- Modules/IO/TransformFactory/include/itkTransformFactory.h
Instead of call it three times on the same transform.
Also removed the `t` variable and replaced `1` with `true` as a `bool` argument.
> STYLE: Call GetTransformTypeAsString() just once, in `TransformFactory`

- Modules/Core/Common/include/itkObjectFactoryBase.h
- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkObjectFactoryBaseGTest.cxx
Follow-up to commit 8e3c544ae5b331577f3b7c923886d1de77d5fd8e "BUG: The ability to override classes with factories was not working", Bill Lorensen (@lorensen), Nov 8, 2007.
----
FYI Here inside `ObjectFactoryBase::CreateInstance` is where the reference count is incremented to `2`: https://github.com/InsightSoftwareConsortium/ITK/blob/aaae66375b1bf66baea509bf2fe95278eff43789/Modules/Core/Common/src/itkObjectFactoryBase.cxx#L202
> Note that object returned by `CreateInstance` has reference count 2, add test

- Modules/Core/Common/include/itkImageSourceCommon.h
- Modules/Core/Common/src/itkImageSourceCommon.cxx
Ensure a shared instance across binaries via itk::Singleton.
> BUG: GetGlobalDefaultSplitter to a global singleton

- Modules/Filtering/AnisotropicSmoothing/test/itkCurvatureAnisotropicDiffusionImageFilterTest.cxx
- Modules/Filtering/AnisotropicSmoothing/test/itkGradientAnisotropicDiffusionImageFilterTest.cxx
- Modules/Filtering/AnisotropicSmoothing/test/itkGradientAnisotropicDiffusionImageFilterTest2.cxx
- Modules/Filtering/BinaryMathematicalMorphology/test/itkBinaryDilateImageFilterTest2.cxx
- Modules/Filtering/BinaryMathematicalMorphology/test/itkErodeObjectMorphologyImageFilterTest.cxx
- Modules/Filtering/ImageFeature/test/itkBilateralImageFilterTest.cxx
- Modules/Filtering/ImageFeature/test/itkBilateralImageFilterTest2.cxx
- Modules/Filtering/ImageFeature/test/itkBilateralImageFilterTest3.cxx
- Modules/Filtering/MathematicalMorphology/test/itkGrayscaleMorphologicalClosingImageFilterTest2.cxx
- Modules/Filtering/MathematicalMorphology/test/itkGrayscaleMorphologicalOpeningImageFilterTest2.cxx
- Modules/Filtering/MathematicalMorphology/test/itkObjectMorphologyImageFilterTest.cxx
- Modules/IO/ImageBase/test/itkNoiseImageFilterTest.cxx
- Modules/Nonunit/Review/test/itkFastApproximateRankImageFilterTest.cxx
- Modules/Segmentation/RegionGrowing/test/CMakeLists.txt
- Modules/Segmentation/RegionGrowing/test/itkIsolatedConnectedImageFilterTest.cxx
Use macros in tests:
- Use `ITK_TRY_EXPECT_NO_EXCEPTION` macro when updating filters in lieu of `try/catch` blocks for the sake of readability and compactness, and to save typing/avoid boilerplate code.
- Only place with the macro the code that might raise exceptions.
- Test the Set/Get methods using the `ITK_TEST_SET_GET_VALUE` macro: make them quantitative instead of just calling the getter methods, or printing the returned values.
Take advantage of the commit to remove unnecessary/uninformative comments and messages where the code has been modified.
> STYLE: Use macros in tests

- Modules/Core/Common/include/itkConstShapedNeighborhoodIterator.hxx
- Modules/Core/Common/include/itkNeighborhood.hxx
- Modules/Core/Transform/include/itkCompositeTransform.hxx
- Modules/Filtering/MathematicalMorphology/include/itkFlatStructuringElement.hxx
- Modules/Numerics/Statistics/include/itkHistogram.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx
- Modules/Segmentation/Classifiers/include/itkClassifierBase.hxx
Improve ivar printing style. Specifically:
- Use `indent.GetNextIndent()` to get the next indent value when printing the elements of a list or array.
- Add missing calls to indentation.
- Do not print unnecessary characters (e.g. `">>>>>>>>>"`).
> STYLE: Improve ivar printing style

- Modules/Filtering/AnisotropicSmoothing/test/itkGradientAnisotropicDiffusionImageFilterTest2.cxx
- Modules/Filtering/ImageFeature/test/itkBilateralImageFilterTest2.cxx
- Modules/Filtering/ImageFeature/test/itkBilateralImageFilterTest3.cxx
- Modules/Filtering/MathematicalMorphology/test/itkGrayscaleMorphologicalClosingImageFilterTest2.cxx
- Modules/Filtering/MathematicalMorphology/test/itkGrayscaleMorphologicalOpeningImageFilterTest2.cxx
- Modules/IO/ImageBase/test/itkNoiseImageFilterTest.cxx
- Modules/Nonunit/Review/test/itkFastApproximateRankImageFilterTest.cxx
- Modules/Segmentation/RegionGrowing/test/itkIsolatedConnectedImageFilterTest.cxx
Increase consistency in the missing argument check message, following the ITK SW guide coding guidelines. Specifically:
- Return `EXIT_FAILURE` instead of `-1`.
- State explicitly that arguments are missing.
- Use `std::endl` instead of `\n` to introduce new lines.
> STYLE: Increase consistency in test argument check message

- Modules/Core/Common/include/itkTriangleCell.hxx
Remove unnecessary single-comment, empty lines when introducing comment blocks in `itk::TriangleCell` implementation.
> STYLE: Remove empty comment lines in `itk::TriangleCell` implementation

- Modules/Numerics/Optimizers/test/itkCumulativeGaussianOptimizerTest.cxx
- Modules/Numerics/Optimizers/test/itkOptimizersHierarchyTest.cxx
Increase coverage for classes in the `Optimizers` module: call the cost function derivative getter method.
> ENH: Increase `Optimizers` classes coverage: get cost function derivate

- Modules/Core/Common/src/itkProcessObject.cxx
Let ProcessObject member functions just call `GetPrimaryOutput()` once, and store the pointer in a local variable.
> STYLE: Remove redundant GetPrimaryOutput() calls from `ProcessObject`

- Modules/Core/Common/src/itkProcessObject.cxx
Removed redundant checks of required named inputs, which were performed already in the previous lines of code.
Partially reverts commit bf6f1065a07037fe27d290f72adf81c81ed408ec "BUG: VerifyPreconditions checks required named inputs", April 23, 2013.
----
Please compare the code that is removed by this PR with the code just above it:
https://github.com/InsightSoftwareConsortium/ITK/blob/bc1025b1c00d8cd99d98646c6a59072edf0488f9/Modules/Core/Common/src/itkProcessObject.cxx#L1332-L1341
Isn't it basically just doing the same check?
> STYLE: Remove redundant checks in `ProcessObject::VerifyPreconditions()`

- Modules/Core/Common/include/itkMacro.h
Fixed documentation about itkGetObjectMacro, itkGetConstObjectMacro, and itkGetModifiableObjectMacro, following commit 7ae9b9356838d7ba5b7e5e0e2172cafff1bdaac4 "ENH: Use of SmartPointers reduced. GetInput() GetOutput() methods return now raw pointers. Only methods creating new objects will return SmartPointers.", Luis Ibanez (@luisibanez), 2002-05-11.
> DOC: itkGetObjectMacro member functions return a raw (not smart) pointer

- Modules/Core/Common/include/itkMetaDataObject.h
- DOC: Fix `MetaDataObject::EncapsulateMetaData` empty return doc warning
- DOC: Document `MetaDataObject::EncapsulateMetaData` parameters
> DOC: Fix `MetaDataObject::EncapsulateMetaData` empty return doc warning

- Modules/Registration/GPUPDEDeformable/test/itkGPUDemonsRegistrationFilterTest2.cxx
Return from test with an exit failure in case the test argument check detects that an insufficient number of arguments is provided.
> BUG: Return exit failure when insufficient test arguments are provided

- Modules/Filtering/FFT/test/itkFFTWComplexToComplexFFTImageFilterTest.cxx
- Modules/IO/PhilipsREC/test/itkPhilipsRECImageIOOrientationTest.cxx
- Modules/IO/PhilipsREC/test/itkPhilipsRECImageIOPrintTest.cxx
- Modules/IO/PhilipsREC/test/itkPhilipsRECImageIOTest.cxx
- Modules/Nonunit/IntegratedTest/test/itkBioRadImageIOTest.cxx
- Modules/Nonunit/IntegratedTest/test/itkImageToHistogramFilterTest4.cxx
- Modules/Nonunit/IntegratedTest/test/itkMaskedImageToHistogramFilterTest1.cxx
- Modules/Numerics/FEM/test/itkFEMSolverHyperbolicTest.cxx
- Modules/Registration/PDEDeformable/test/itkDemonsRegistrationFilterTest.cxx
- Modules/Registration/PDEDeformable/test/itkFastSymmetricForcesDemonsRegistrationFilterTest.cxx
- Modules/Video/BridgeOpenCV/test/itkOpenCVImageBridgeRGBTest.cxx
Use exception checking macros in tests:
- Use `ITK_TRY_EXPECT_NO_EXCEPTION` and `ITK_TRY_EXPECT_EXCEPTION` macros when updating filters in lieu of `try/catch` blocks for the sake of readability and compactness, and to save typing/avoid boilerplate code.
- Only place the code that might raise exceptions within the macro.
> STYLE: Use exception checking macros in tests

- Modules/Nonunit/IntegratedTest/test/itkBioRadImageIOTest.cxx
Fix ITK coding style inconsistency linter error.
Fixes:
```
Error: Code is inconsistent with ITK Coding Style.
Add the *action:ApplyClangFormat* PR label to correct.
Changes required:
Files:
Modules/Nonunit/IntegratedTest/test/itkBioRadImageIOTest.cxx
Changes:
diff --git a/Modules/Nonunit/IntegratedTest/test/itkBioRadImageIOTest.cxx
b/Modules/Nonunit/IntegratedTest/test/itkBioRadImageIOTest.cxx
index 813d8b00..af2ea2b8 100644
--- a/Modules/Nonunit/IntegratedTest/test/itkBioRadImageIOTest.cxx
+++ b/Modules/Nonunit/IntegratedTest/test/itkBioRadImageIOTest.cxx
@@ -63,6 +63,5 @@ itkBioRadImageIOTest(int argc, char * argv[])
ITK_TRY_EXPECT_NO_EXCEPTION(writer->Update());
-
return EXIT_SUCCESS;
}
```
raised, for example, at:
https://github.com/InsightSoftwareConsortium/ITK/actions/runs/580250209 …
> STYLE: Fix ITK coding style inconsistency linter error

- Wrapping/Generators/Python/Tests/extras.py
Follow-up of 336be62d3d (ENH: Better support for multi-component images in image_from_vtk_image) integrated through:
* https://github.com/InsightSoftwareConsortium/ITK/pull/4142
cc: @dzenanz @thewtex
> ENH: Ensure 3D multi-components conversion in image_from_vtk_image is tested

- Modules/Core/Common/include/itkPoint.h
- Modules/Core/Common/include/itkVector.h
The original `assertSameType` lambda's appeared to trigger compile errors from MSVC, as reported by Dženan Zukić at https://github.com/InsightSoftwareConsortium/ITK/issues/4153 "ITK does not compile with VS2022 17.7.0", like:
> Modules\Core\Common\include\itkPoint.h(369,45): error C2187: syntax error: 'attribute specifier' was unexpected here
> Modules\Core\Common\test\itkPointGTest.cxx(63,57): message : see reference to function template instantiation 'auto itk::MakePoint<int,>(const TValue)' being compiled
> Modules\Core\Common\include\itkPoint.h(367,1): error C2938: 'itk::MakePoint::<lambda_706d090a84c31981802e12f4e9361bdf>::<lambda_typedef_cdecl>' : Failed to specialize alias template
> Modules\Core\Common\include\itkPoint.h(367,1): message : see reference to alias template …
> COMP: Adjust check that all arguments of MakePoint/Vector have same type

- Wrapping/Generators/Python/itk/support/base.py
To address:
```
../../../../../../bin/micromamba/envs/itk-wasm/lib/python3.11/site-packages/itk/support/base.py:26
pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
../../../../../../bin/micromamba/envs/itk-wasm/lib/python3.11/site-packages/pkg_resources/__init__.py:2871
Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
```
This was brought it by https://github.com/InsightSoftwareConsortium/ITK/commit/b7b6638b7a083fa5220d261753c50dd1dbdaf014 to work around an xarray import issue, but with xarray-2023.8.0, the …
> COMP: Remove pkg_resources import from base.py

- Modules/Core/Common/src/itkImageSourceCommon.cxx
Added an in-class default member initializer to the data member of `ImageSourceCommonGlobals`. Removed its default-constructor, following the C++ "Rule of Zero".
----
Aims to clarify our discussion at https://github.com/InsightSoftwareConsortium/ITK/pull/4122#discussion_r1272163516
> STYLE: ImageSourceCommonGlobals default member initializer, Rule of Zero

- Modules/Core/Common/include/itkThreadPool.h
- Modules/Core/Common/src/itkThreadPool.cxx
A `std::lock_guard` is more lightweight than a `std::unique_lock`, so for simple use cases, `std::lock_guard` appears preferable.
----
Note that `std::lock_guard` is already used extensively in within ITK (I counted 79 times), so this proposed change would be consistent with the existing code  😃
> STYLE: Replace `std::unique_lock` with `std::lock_guard` in ThreadPool

- Modules/Filtering/ImageStatistics/include/itkLabelOverlapMeasuresImageFilter.hxx
- Modules/Filtering/ImageStatistics/include/itkLabelStatisticsImageFilter.hxx
- Modules/Numerics/Statistics/include/itkImageToHistogramFilter.hxx
- Modules/Segmentation/ConnectedComponents/include/itkRelabelComponentImageFilter.hxx
Removed explicit `unlock()` calls. Instead, just made sure that the `lock_guard` variables go out of scope as soon as other threads are allowed to merge data.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4168 commit 1094cdde9ae725ad257d5d77308fffaa3dd6e0fe
"STYLE: Replace `std::unique_lock` with `std::lock_guard` in ThreadPool"
----
When reviewing, you might want to suppress whitespace changes: https://github.com/InsightSoftwareConsortium/ITK/pull/4172/files?w=1
> STYLE: Replace std::unique_lock with std::lock_guard in Filter.hxx files

- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshPolygonCellTest.cxx
- BUG: Fix dynamically allocated memory management
- ENH: Test the const point iterators in `itk::QuadEdgeMeshPolygonCell`
> BUG: Fix `itk::QuadEdgeMeshPolygonCell` test valgrind defect

- Modules/Core/Common/src/itkPlatformMultiThreaderPosix.cxx
- Modules/Core/Common/src/itkPlatformMultiThreaderWindows.cxx
A few style improvements in the implementation of `PlatformMultiThreader`.
> Use `lock_guard` in PlatformMultiThreader classes, remove unused `threadId` variables, remove duplicate assignment

- Modules/Core/Common/src/itkIndent.cxx
Document `itk::Indent` class methods in header file only: Doxygen picks the method documentation from the header files, and leaves the method documentation empty if it does not find it there. So remove the method documentation from the implementation file.
> DOC: Document `itk::Indent` class methods in header file only

- Modules/Core/Common/src/itkPlatformMultiThreaderWindows.cxx
- Modules/Registration/GPUPDEDeformable/include/itkGPUDemonsRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkESMDemonsRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkFastSymmetricForcesDemonsRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx
- Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.hxx
Following C++ Core Guidelines, April 13, 2023, [Use RAII, never plain `lock()`/`unlock()`](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#cp20-use-raii-never-plain-lockunlock)
Follow-up to pull request #4173 commit c4c3710d5fad0c1e4590896647d0e69f8c5a6c79 "STYLE: Use `lock_guard<mutex>` in `PlatformMultiThreader` classes"
>  Use `lock_guard<mutex>` in itkPlatformMultiThreaderWindows, ParallelSparseFieldLevelSetImageFilter, and PDEDeformable Registration

- Modules/Core/ImageFunction/include/itkExtrapolateImageFunction.h
- Modules/Core/ImageFunction/include/itkVectorInterpolateImageFunction.h
- Modules/Core/ImageFunction/include/itkVectorNearestNeighborInterpolateImageFunction.h
Remove `PrintSelf` re-implementations across miscellaneous interpolation/extrapolation image function classes that do not contain instance variable members as their parent class re-implementation prints the necessary information.
Follow-up to d2ff311.
> ENH: Remove ivar memberless `PrintSelf` implementation

- Modules/Core/Common/test/itkDecoratorTest.cxx
- Modules/Core/ImageFunction/test/itkNeighborhoodOperatorImageFunctionTest.cxx
- Modules/Core/Mesh/test/itkCellInterfaceTest.cxx
- Modules/Filtering/BinaryMathematicalMorphology/test/itkBinaryDilateImageFilterTest.cxx
- Modules/Filtering/BinaryMathematicalMorphology/test/itkBinaryErodeImageFilterTest.cxx
- Modules/Filtering/Denoising/test/itkPatchBasedDenoisingImageFilterDefaultTest.cxx
- Modules/Filtering/ImageIntensity/test/itkVectorExpandImageFilterTest.cxx
- Modules/Filtering/MathematicalMorphology/test/itkGrayscaleFunctionDilateImageFilterTest.cxx
- Modules/Filtering/MathematicalMorphology/test/itkGrayscaleFunctionErodeImageFilterTest.cxx
- Modules/Segmentation/DeformableMesh/test/itkDeformableSimplexMesh3DGradientConstraintForceFilterTest.cxx
- STYLE: Declare variables close to where they are used in tests
- STYLE: Declare and use test image dimensionality as `constexpr`
- STYLE: Do not declare a test status variable that is only used once
- ENH: Allow `itkCellInterfaceTest` to run as long as possible
- STYLE: Use exception checking macros in itkVectorExpandImageFilterTest
- STYLE: Prefer setting the input once all ivars have been set in test
> STYLE: Improve miscellaneous tests' style

- Modules/IO/TransformMINC/test/itkIOTransformMINCTest.cxx
- STYLE: Use `ITK_TRY_EXPECT_NO_EXCEPTION` macro in `IOTransformMINC` test
- STYLE: Prefer using `ITK_TEST_EXPECT_EQUAL` lh and rh comparison macro
- STYLE: Prefer using `itk::Math::FloatAlmostEqual` in comparisons
- STYLE: Add vertical space for readability in `itkIOTransformMINCTest`
> STYLE: Improve `itkIOTransformMINCTest.cxx` style

- Modules/Core/Common/include/itkMath.h
Fix typo in `itk::Math` function parameter documentation: use the singular form instead of plural to refer to the parameter at issue.
> DOC: Fix typo in `itk::Math` function parameter documentation

- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkMRFImageFilter.hxx
Print the superclass object in `itk::MRFImageFilter::PrintSelf` method.
> ENH: Print the superclass object in `itk::MRFImageFilter::PrintSelf`

- Modules/Segmentation/MarkovRandomFieldsClassifiers/test/CMakeLists.txt
- Modules/Segmentation/MarkovRandomFieldsClassifiers/test/itkRGBGibbsPriorFilterTest.cxx
Honor the `itk::RGBGibbsPriorFilter` classname in its test filename.
> STYLE: Honor `itk::RGBGibbsPriorFilter` classname in its test filename

- Modules/Core/ImageFunction/include/itkBSplineDecompositionImageFilter.h
- Modules/Core/ImageFunction/include/itkBSplineDecompositionImageFilter.hxx
- Modules/Core/ImageFunction/test/itkBSplineDecompositionImageFilterTest.cxx
Use an unsigned integer instead of a signed to store the number of poles
in `itk::BSplineDecompositionImageFilter`: the number of poles cannot be
negative.
Take advantage of the commit to use `ITK_TEST_EXPECT_EQUAL` in the
corresponding check as an exact comparisons can be performed, ensures
that the lh and rh arguments have the exact same types at compile time,
and since it improves readability, and avoids boilerplate code.
> STYLE: Use an unsigned integer to store the number of poles

- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.h
- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.hxx
Prefer using setter macro for `itk::RGBGibbsPriorFilter` ivar.
> STYLE: Prefer using setter macro for `itk::RGBGibbsPriorFilter` ivar

- Modules/Core/Common/include/itkConnectedImageNeighborhoodShape.h
- Modules/Core/Common/include/itkMath.h
From C++14, the standard `assert` supports being called directly from inside a `constexpr` function, as was already mentioned in Andrzej's C++ blog entry https://akrzemi1.wordpress.com/2017/05/18/asserts-in-constexpr-functions The `ITK_X_ASSERT` workaround for GCC 4 is no longer needed, as ITK now requires at least GCC 7 (and also at least C++17).
This reverts commit 9ff8f9fcdef345a11a47320253d96438a60d5859 "COMP: Fix C++11 compatibility with assert in constexpr" by Bradley Lowekamp (@blowekamp), June 25, 2018.
> STYLE: Remove `ITK_X_ASSERT`, just use `assert` in `constexpr` functions

- Modules/Core/Common/include/itkSingleton.h
- Modules/Core/Common/src/itkSingleton.cxx
Note that `SetGlobalInstance` has always just returned `true`, from the very first commit, pull request #118 commit a66337ec215c88f4900a2caf419b055483c42085 _ENH: Synchronize factories across modules in Python_ by Francois Budin (@fbudin69500) and Hans Johnson (@hjmjohnson), February 2019.
Looking at the initial (2019) version of `SetGlobalInstance` and `SetGlobalInstancePrivate`:
https://github.com/InsightSoftwareConsortium/ITK/blob/a66337ec215c88f4900a2caf419b055483c42085/Modules/Core/Common/include/itkSingleton.h#L62-L64
https://github.com/InsightSoftwareConsortium/ITK/blob/a66337ec215c88f4900a2caf419b055483c42085/Modules/Core/Common/src/itkSingleton.cxx#L97-L104
> Document and use the fact that `SingletonIndex::SetGlobalInstance` always returns true

- Modules/Core/Common/include/itkImageRandomConstIteratorWithIndex.hxx
- Modules/Core/Common/include/itkImageRandomConstIteratorWithOnlyIndex.hxx
The constructors of `ImageRandomConstIteratorWithIndex` and `ImageRandomConstIteratorWithOnlyIndex` that support two arguments (image and region) accidentally still assigned their data members, while they were already initialized by in-class default member initialization. This in-class default member initialization was added as part of pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3929 commit 4e46cb6ef56658353c14bd58e6b28b63c410f1c8 "STYLE: Default default-constructor of ImageRandom ConstIterator classes", merged on February 24, 2023 and included with tag ITK v5.4rc01.
This caused extra `MersenneTwisterRandomVariateGenerator::New()` calls, which changed the seeds of random number generation. These changes can possibly cause regression failures in unit tests of client …
> BUG: ImageRandomIteratorWithIndex should not assign data in constructor

- Examples/Statistics/ScalarImageKmeansModelEstimator.cxx
- STYLE: Use standard return codes in example
- STYLE: Increase consistency in example argument check message
> STYLE: Use standard return codes in example

- Modules/Core/Common/test/itkBSplineKernelFunctionTest.cxx
- Modules/Core/Common/test/itkGaussianSpatialFunctionTest.cxx
- Modules/Core/ImageFunction/test/itkBSplineDecompositionImageFilterTest.cxx
- Modules/Core/SpatialObjects/test/itkImageSpatialObjectTest.cxx
- Modules/Core/Transform/test/itkEuler2DTransformTest.cxx
- Modules/Core/Transform/test/itkSimilarity2DTransformTest.cxx
- Modules/Filtering/DisplacementField/test/itkDisplacementFieldJacobianDeterminantFilterTest.cxx
- Modules/Filtering/DisplacementField/test/itkDisplacementFieldTransformTest.cxx
- Modules/Filtering/ImageGrid/test/itkExpandImageFilterTest.cxx
- Modules/Filtering/ImageGrid/test/itkExpandImageFilterTest2.cxx
- Modules/Filtering/ImageGrid/test/itkWarpImageFilterTest.cxx
- Modules/Filtering/ImageGrid/test/itkWarpImageFilterTest2.cxx
- Modules/Filtering/ImageGrid/test/itkWarpVectorImageFilterTest.cxx
- Modules/Filtering/ImageIntensity/test/itkVectorExpandImageFilterTest.cxx
- Modules/Filtering/ImageSources/test/itkGaborKernelFunctionTest.cxx
- Modules/Nonunit/Review/test/itkDiscreteHessianGaussianImageFunctionTest.cxx
- Modules/Nonunit/Review/test/itkRobustAutomaticThresholdCalculatorTest.cxx
- Modules/Nonunit/Review/test/itkRobustAutomaticThresholdImageFilterTest.cxx
- Modules/Registration/Common/test/itkRecursiveMultiResolutionPyramidImageFilterTest.cxx
- Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx
Make non-macro comparison conditional blocks consistent in tests: adhere to the ITK SWG guidelines:
- Report the messages to `std::cerr`.
- Make the printed messages be consistent.
- Declare and re-use epsilon/tolerance values.
> STYLE: Make non-macro comparison conditional blocks consistent in tests

- Modules/Core/Common/test/itkBSplineKernelFunctionTest.cxx
- Modules/Core/Common/test/itkGaussianSpatialFunctionTest.cxx
- Modules/Core/SpatialObjects/test/itkImageSpatialObjectTest.cxx
- Modules/Filtering/DisplacementField/test/itkDisplacementFieldTransformTest.cxx
- Modules/Filtering/ImageGrid/test/itkExpandImageFilterTest.cxx
- Modules/Filtering/ImageGrid/test/itkExpandImageFilterTest2.cxx
- Modules/Filtering/ImageGrid/test/itkWarpImageFilterTest.cxx
- Modules/Filtering/ImageGrid/test/itkWarpImageFilterTest2.cxx
- Modules/Filtering/ImageGrid/test/itkWarpVectorImageFilterTest.cxx
- Modules/Filtering/ImageSources/test/itkGaborKernelFunctionTest.cxx
- Modules/Numerics/Statistics/test/itkHistogramTest.cxx
- Modules/Registration/Common/test/itkRecursiveMultiResolutionPyramidImageFilterTest.cxx
- Modules/Registration/PDEDeformable/test/itkSymmetricForcesDemonsRegistrationFilterTest.cxx
- Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx
- STYLE: Increase consistency in test argument check message
- STYLE: Prefer using `constexpr <type>` over `struct` for image dimension
- STYLE: Conform to ITK comment style for within-code comments (tests)
- STYLE: Remove empty comment lines in tests
- STYLE: Remove uninformative standard output message in itkHistogramTest
- STYLE: Remove uninformative comments in tests
- STYLE: Do not allow lonely std output endl statements in misc tests
- STYLE: Increase consistency in newline character use in tests
- STYLE: Remove blank lines in excess in miscellaneous tests
> STYLE: Improve style in miscellaneous tests

- Modules/Segmentation/SuperPixel/test/itkSLICImageFilterGTest.cxx
- Modules/Segmentation/SuperPixel/test/itkSLICImageFilterTest.cxx
- STYLE: Prefer using macros for `itk::SLICImageFilter` basic methods
- STYLE: Use standard exit return code in `itk::SLICImagetFilter` test
- STYLE: Conform to ITK SWG style guidelines in test ending message
> STYLE: Use macros in `itk::SLICImageFilter` test

- Modules/Registration/PDEDeformable/test/itkSymmetricForcesDemonsRegistrationFilterTest.cxx
- Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx
Add missing semicolon to macro statement end in tests.
Fixes:
```
Modules/Registration/PDEDeformable/test/itkSymmetricForcesDemonsRegistrationFilterTest.cxx:252:49:
error: expected ';' after static_assert
ITK_TEST_EXPECT_TRUE(numPixelsDifferent <= 10)
^
;
Modules/Registration/PDEDeformable/test/itkSymmetricForcesDemonsRegistrationFilterTest.cxx:279:29:
error: expected ';' after static_assert
ITK_TEST_EXPECT_TRUE(fptr)
^
;
2 errors generated.
```
and
```
Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx:718:101:
error: expected ';' after static_assert
ITK_TEST_EXPECT_EQUAL(itk::TemporalProcessObjectTest::m_CallStack.size(), correctCallStack.size())
^
;
Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx:754:101:
error: expected ';' after static_assert …
```
> COMP: Add missing semicolon to macro statement end in tests

- Modules/Core/Common/include/itkSingleton.h
- Modules/Core/Common/include/itkSingletonMacro.h
- Modules/Core/Common/src/itkSingleton.cxx
No longer stored the `func` parameter from `SingletonIndex::SetGlobalInstance`, and from `Singleton(globalName, func, deleteFunc)`, as it was never actually retrieved from `m_GlobalObjects` afterwards.
Deprecated the `SingletonIndex::SingletonData` type alias, as it is no longer used internally anymore, and it should not be public either.
----
Note that even with the initial commit a66337ec215c88f4900a2caf419b055483c42085 (pull request #118, Francois Budin (@fbudin69500) and Hans Johnson (@hjmjohnson), February 2019), the value of the `func` parameter was never retrieved from `SingletonIndex::m_GlobalObjects`, looking at:
https://github.com/InsightSoftwareConsortium/ITK/blob/a66337ec215c88f4900a2caf419b055483c42085/Modules/Core/Common/src/itkSingleton.cxx …
> STYLE: SingletonIndex does not need to store the unused `func` parameter

- Modules/Numerics/FEM/include/itkFEMSolverCrankNicolson.h
- Modules/Numerics/FEM/include/itkFEMSolverHyperbolic.h
Do not use the superclass template parameters in `itk::fem` classes RTTI macros.
> STYLE: Do not use superclass template parameters in `itk::fem` RTTI

- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.hxx
Use the `itkPrintSelfObjectMacro` macro to print smart pointers: the macro deals with the situation where such objects can be null. Using the macro also saves typing and avoids boilerplate code.
> ENH: Use `itkPrintSelfObjectMacro` to print smart pointers

- Modules/Filtering/ImageIntensity/include/itkAddImageFilter.h
- Modules/Filtering/ImageIntensity/include/itkPowImageFilter.h
Hopefully this will help with the Doxygen XML issues discussed at:
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/pull/411.
> STYLE: Separate \ingroup for MultiThreaded with AddImageFilter, PowImageFilter

- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.h
- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.hxx
- DOC: Use Doxygen math syntax for math notation in class documentation
- DOC: Document `RGBGibbsPriorFilter` class methods in header file only
- DOC: Use proper Doxygen documentation style in `RGBGibbsPriorFilter`
- STYLE: Prefer double forward slashes for within-method body comments
> DOC: Improve `itk::RGBGibbsPriorFilter` documentation

- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.h
- Modules/Segmentation/MarkovRandomFieldsClassifiers/test/itkRGBGibbsPriorFilterTest.cxx
Add getter methods to `itk::RGBGibbsPriorFilter` ivars. Change the documentation to mention the getter methods. Add the corresponding checks in the filter`s test file.
> ENH: Add getter methods to `itk::RGBGibbsPriorFilter` ivars

- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.hxx
Confom to the ITK SWG style guidelines and use the `this` pointer to address self methods in `itk::RGBGibbsPriorFilter`.
> STYLE: Use `this` to address self methods in `RGBGibbsPriorFilter`

- Modules/Filtering/FFT/src/itkFFTWGlobalConfiguration.cxx
When calling `lock()` and `unlock()` explicitly, throwing an exception between between those two calls would leave the mutex locked, which appears undesirable. Used `std::lock_guard` to solve this problem.
Following C++ Core Guidelines, April 13, 2023, "Use RAII, never plain `lock()`/`unlock()`" https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#cp20-use-raii-never-plain-lockunlock
Also replaced manual creation of an exception with an `itkGenericExceptionMacro` call.
> BUG: Use `lock_guard<mutex>` in FFT configuration to deal with exception

- Modules/Filtering/ImageStatistics/include/itkLabelOverlapMeasuresImageFilter.h
- Modules/Filtering/ImageStatistics/include/itkLabelOverlapMeasuresImageFilter.hxx
This filter is typically instantiated with unsigned char pixel type, which leads to output which needs deciphering, such as:
```log
WARNING: In C:\P\IPP\ITK-source\ITK\Modules\Filtering\ImageStatistics\include\itkLabelOverlapMeasuresImageFilter.hxx, line 233
LabelOverlapMeasuresImageFilter (000001FF7CF72F80): Label  not found.
WARNING: In C:\P\IPP\ITK-source\ITK\Modules\Filtering\ImageStatistics\include\itkLabelOverlapMeasuresImageFilter.hxx, line 233
LabelOverlapMeasuresImageFilter (000001FF7CF72F80): Label  not found.
WARNING: In C:\P\IPP\ITK-source\ITK\Modules\Filtering\ImageStatistics\include\itkLabelOverlapMeasuresImageFilter.hxx, line 233
LabelOverlapMeasuresImageFilter (000001FF7CF72F80): Label  not found.
WARNING: In C:\P\IPP\ITK-source\ITK\Modules\Filtering\ImageStatistics\incl …
```
> ENH: Improve warning messages (label numbers as ints instead of chars)

- Modules/Numerics/FEM/include/itkFEMFactoryBase.h
When calling `lock()` and `unlock()` explicitly, throwing an exception between between those two calls would leave the mutex locked, which appears undesirable. Used `std::lock_guard` to solve this problem.
Also replaced manual creation of an exception with an `itkGenericExceptionMacro` call.
Follow-up to:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4181 commit a00eb3914d0ab4e4973180f295db56b736aa1ef4
"BUG: Use `lock_guard<mutex>` in FFT configuration to deal with exception"
> BUG: Use `lock_guard<mutex>` in FEMFactoryBase to deal with exception

- Modules/Core/Common/include/itkSingleton.h
- Modules/Core/Common/include/itkSingletonMacro.h
- Modules/Core/Common/src/itkObjectFactoryBase.cxx
Added overloads of `SetGlobalInstance` and `Singleton` without the unused `func` parameter. Let the new `SetGlobalInstance` overload just return `void`, instead of `bool`. Deprecated the original overloads.
Follow-up to:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4164 commit 6d1c4c7ab7f688bd0a4563bacbe788212a039769
"STYLE: SingletonIndex does not need to store the unused `func` parameter"
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4162 commit 6ec6328ed2383fb474ace88fbd10c3f1be6bfaba
"STYLE: Let `Singleton` assume that SetGlobalInstance always returns true"
> STYLE: Remove unused parameter from `SetGlobalInstance` and `Singleton`

- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
- Modules/Core/Common/include/itkPlatformMultiThreader.h
- Modules/Core/Common/src/itkMultiThreaderBase.cxx
- Modules/Core/Common/src/itkPlatformMultiThreader.cxx
- Modules/Core/Common/src/itkPlatformMultiThreaderPosix.cxx
- Modules/Core/Common/src/itkPlatformMultiThreaderWindows.cxx
- Modules/Filtering/FFT/include/itkFFTWGlobalConfiguration.h
- Modules/Filtering/FFT/src/itkFFTWGlobalConfiguration.cxx
- Modules/IO/ImageBase/src/itkImageIOBase.cxx
- Modules/IO/ImageBase/src/itkImageIOFactory.cxx
- Modules/Numerics/FEM/include/itkFEMFactoryBase.h
- Modules/Numerics/FEM/src/itkFEMFactoryBase.cxx
- Modules/Registration/GPUPDEDeformable/include/itkGPUDemonsRegistrationFunction.h
- Modules/Registration/GPUPDEDeformable/include/itkGPUDemonsRegistrationFunction.hxx
- Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4.h
- Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4.hxx
- Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.h
- Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkESMDemonsRegistrationFunction.h
- Modules/Registration/PDEDeformable/include/itkESMDemonsRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkFastSymmetricForcesDemonsRegistrationFunction.h
- Modules/Registration/PDEDeformable/include/itkFastSymmetricForcesDemonsRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.h
- Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.h
- Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx
Follow-up to commit d0a853468fac32a87159bd30466695f155db50ec "ENH: using standard library's mutex primitives", Dženan Zukić (@dzenanz), October 31, 2018.
> Rename instances of `std::mutex` from "Lock" to "Mutex"

- Modules/Core/Common/include/itkImageRandomConstIteratorWithIndex.hxx
- Modules/Core/Common/include/itkImageRandomConstIteratorWithOnlyIndex.hxx
Removed unnecessary local `randomPosition` variables, reduced scope of `residual`, avoided redundant `m_Region.GetSize()` calls, etc.
> STYLE: Code cleanup ImageRandomConstIteratorWith(Only)Index RandomJump()

- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
- Modules/Core/Common/include/itkSimpleFilterWatcher.h
- Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx
- Modules/Core/Common/src/itkMultiThreaderBase.cxx
- Modules/Core/Common/src/itkOutputWindow.cxx
- Modules/Filtering/DisplacementField/include/itkInvertDisplacementFieldImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkDirectedHausdorffDistanceImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkIsoContourDistanceImageFilter.hxx
- Modules/Filtering/FFT/include/itkFFTWCommon.h
- Modules/Filtering/FFT/include/itkFFTWCommonExtended.h
- Modules/Filtering/ImageIntensity/include/itkShiftScaleImageFilter.hxx
- Modules/Filtering/ImageLabel/include/itkScanlineFilterCommon.h
- Modules/Filtering/ImageStatistics/include/itkMinimumMaximumImageFilter.hxx
- Modules/Filtering/ImageStatistics/include/itkStatisticsImageFilter.hxx
- Modules/Filtering/LabelMap/include/itkBinaryImageToLabelMapFilter.hxx
- Modules/Filtering/LabelMap/include/itkChangeRegionLabelMapFilter.hxx
- Modules/Filtering/LabelMap/include/itkLabelMapFilter.hxx
- Modules/IO/ImageBase/src/itkImageIOBase.cxx
- Modules/IO/ImageBase/src/itkImageIOFactory.cxx
- Modules/Numerics/Statistics/include/itkImageToHistogramFilter.hxx
- Modules/Numerics/Statistics/include/itkMaskedImageToHistogramFilter.hxx
- Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4.hxx
- Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentImageFilter.hxx
- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
For the sake of consistency: ITK already has lot of local `std::lock_guard` variables named "lockGuard".
Using Notepad++, Find in Files (Regular expression), doing:
Find what:  const std::lock_guard<([^ ]+)>[ ]+\w+\(
Replace with:  const std::lock_guard<$1> lockGuard\(
> STYLE: Rename local `std::lock_guard` variables "lockGuard"

- Modules/Core/Common/include/itkObjectFactoryBase.h
- Modules/Core/Common/src/itkObjectFactoryBase.cxx
`ObjectFactoryBase::InitializeFactoryList()` has become unnecessary from pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3641 commit 48d0cb0eed8a0ceb0f29115302f9972cc691ecb8 "STYLE: Remove pointer indirection from lists of ObjectFactoryBasePrivate"
> STYLE: Remove private ObjectFactoryBase member `InitializeFactoryList()`

- Modules/Core/Common/include/itkVectorContainer.h
- Modules/Core/Common/test/itkVectorContainerGTest.cxx
Moved the `protected` section to the end of the `VectorContainer` definition, allowing it to use `size_type` from the `public` section.
Tested that all nested types of `std::vector` are directly accessible from `itk::VectorContainer`.
> ENH: Make VectorContainer::size_type public, test nested `vector` types

- .git-blame-ignore-revs
Updating based on two large, automated changes to apply cmake formatting
and change the content links to .cid.
- f3899ce8c6d53fc077c4e0bfa2c6f1fe56166b57
- efa749515db840b54f7329b261d3ec4c3a575f83
> DOC: Update .git-blame-ignore-revs for cmake-format, .cid content links

- Modules/Core/Common/include/itkThreadPool.h
Inspired by pull request https://github.com/SimpleITK/SimpleITK/pull/1994 commit https://github.com/SimpleITK/SimpleITK/commit/0dc078f88fbde2f773a9c09c4ad96f2d772725c6 "Use clang-tidy with modernize-avoid-bind", by Bradley Lowekamp (@blowekamp).
> STYLE: Replace `std::bind` in ThreadPool::AddWork with lambda expression

- Modules/Core/Common/include/itkObjectFactoryBase.h
- Modules/Core/Common/src/itkObjectFactoryBase.cxx
`ObjectFactoryBase::RegisterInternal()` was only called by `Initialize()` anyway.
Avoided a redundant `itkInitGlobalsMacro(PimplGlobals)` call, and replaced `clear` and `push_back` calls by a simple assignment to `m_RegisteredFactories`.
> STYLE: Remove private ObjectFactoryBase member `RegisterInternal()`

- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
- Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx
- Modules/Core/Common/test/itkMersenneTwisterRandomVariateGeneratorGTest.cxx
Allows generating a reproducible sequence of pseudo-random numbers.
----
FYI, I would like to use this member function to write reproducible unit tests for elastix Random Sampler, which internally uses ITK's `ImageRandomConstIteratorWithIndex`. The problem is that `ImageRandomConstIteratorWithIndex` creates a new MersenneTwisterRandomVariateGenerator, and each `MersenneTwisterRandomVariateGenerator::New()` "get the next seed", by calling `GetNextSeed()`: https://github.com/InsightSoftwareConsortium/ITK/blob/75b99671a89a9ef6ba1ad8fda62ba3843ad61b54/Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx#L65
The proposed `ResetNextSeed()` would allow multiple `MersenneTwisterRandomVariateGenerator` objects (created by `New()`) to generate the very same sequence of numbers.
> ENH: Add `MersenneTwisterRandomVariateGenerator::ResetNextSeed()`

- Documentation/docs/download.md
Download is now the second page of the new docs site (docs.itk.org), so an update to it is in order. The direct link is: https://docs.itk.org/en/latest/download.html
> DOC: Update ITK version mentioned in download.md from 4.13.1 to 5.3.0

- Modules/Compatibility/Deprecated/include/itkTreeIteratorClone.h
- Modules/Core/Common/include/itkFloatingPointExceptions.h
- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshScalarDataVTKPolyDataWriter.h
- Modules/Core/Transform/include/itkTransformBase.h
- Modules/Filtering/ImageGrid/include/itkBSplineCenteredL2ResampleImageFilterBase.h
- Modules/Numerics/FEM/include/itkFEMLoadNoisyLandmark.h
- DOC: Remove `itk` prefix to class names in Doxygen `class` command
- DOC: Fix `QuadEdgeMeshScalarDataVTKPolyDataWriter` Doxygen `class` name
> DOC: Fix Doxygen class names

- Modules/Core/Common/include/itkSingleton.h
- Modules/Core/Common/src/itkSingleton.cxx
Passing `initializedGlobalSingletonIndex` to a dummy function (`Unused`) may not always avoid being optimized out. Instead, the C++ `volatile` keyword is really meant to be used to avoid such optimization.
Added the C++17 `[[maybe_unused]]` attribute to avoid possible warnings.
Removed the claim that `Unused` ensures that its parameter is not optimized out.
> STYLE: Use `volatile` to avoid global SingletonIndex being optimized out

- Modules/Core/Common/include/itkPoint.h
- Modules/Core/Common/include/itkVector.h
The previous approach, using the class template argument deduction guide of std::array appeared to trigger compile errors from  AppleClang 10.0.0.10001044, as Mihail Isakov (@issakomi) remarked at https://github.com/InsightSoftwareConsortium/ITK/pull/4154#discussion_r1292840598, like:
> Modules/Core/Common/include/itkPoint.h:371:20: error: no viable constructor or deduction guide for deduction of template arguments of 'array'
>   const std::array stdArray{ firstValue, otherValues... };
>                   ^
> [CTest: warning matched] Modules/Core/Common/test/itkPointGTest.cxx:63:46: note: in instantiation of function template specialization 'itk::MakePoint<int>' requested here
>   static_assert(std::is_same_v<decltype(itk::MakePoint(0))::ValueType, int> &&
---
The proposed approach is …
> COMP: Use conjunction_v to check argument types of MakePoint, MakeVector

- Modules/Bridge/NumPy/wrapping/PyBuffer.i.in
- Modules/Bridge/NumPy/wrapping/test/itkPyBufferTest.py
- Wrapping/Generators/Python/itk/support/extras.py
If an itk.Image's memory has not been allocated return None from itk.array_view_from_image.
Pickle and unpickles an unallocated itk.Image to support sending the image's metadata with Dask. #4267.
> BUG: Support serialization of an empty itk.Image

- Modules/Numerics/FEM/include/itkFEMScatteredDataPointSetToImageFilter.h
Add run-time type information to
`itk::FEMScatteredDataPointSetToImageFilter`.
> ENH: Add RTTI to `itk::FEMScatteredDataPointSetToImageFilter`

- Testing/ContinuousIntegration/AzurePipelinesLinux.yml
- Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml
- Testing/ContinuousIntegration/AzurePipelinesMacOS.yml
- Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
- Testing/ContinuousIntegration/AzurePipelinesWindows.yml
- Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
- Utilities/Debugger/ITK.natvis
- Utilities/Debugger/default.natstepfilter
The ITK Debug Visualizers for Visual Studio do not seem to work when the XML namespace name starts with "https" (rather than just "http"). This was found by setting the option "Natvis diagnostic messages" to "Verbose", in either Visual Studio 2019 (version 16.11.31) or Visual Studio 2022 (version 17.7.6). It says:
> ITK.natvis(4,2): Fatal error: Expected element with namespace 'http://schemas.microsoft.com/vstudio/debugger/natvis/2010'.
Reverts the change of this particular file from pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3428 commit 9cd0f2053f0cf181ec4412bf896301faf0cc2092 "ENH: Use https instead of http when https works", May 18, 2022.
-- With help from colleagues of mine at LKEB, Leiden University Medical Center.
Also excluded changes in "Utilities/Debugger" …
> Fix XML namespace of Natvis file, exclude Utilities/Debugger from CI

- Modules/Numerics/Statistics/include/itkListSample.hxx
Make `itk::ListSample::PrintSelf` implementation style consistent following the ITK SWG coding style guideline and the available ITK macros:
- Print only the class instance variables.
- Use the `os << indent << "{ivarName}: " << m_ivarName << std::endl` recipe.
> STYLE: Increase `itk::ListSample::PrintSelf` consistency

- Modules/Core/Transform/test/itkBSplineTransformInitializerTest1.cxx
Increase coverage for `ìtk::BSplineTransformInitializer`: test exceptions.
> ENH: Increase coverage for `ìtk::BSplineTransformInitializer`

- Modules/Filtering/QuadEdgeMeshFiltering/test/itkDiscreteGaussianCurvatureQuadEdgeMeshFilterTest.cxx
- Modules/Numerics/Optimizersv4/test/itkAutoScaledGradientDescentRegistrationTest.cxx
- Modules/Numerics/Optimizersv4/test/itkGradientDescentOptimizerBasev4Test.cxx
Prefer using testing macros in miscellaneous tests:
- Use the `ITK_TRY_EXPECT_EXCEPTION` macro in lieu of `try/catch` blocks to check for expected exceptions for the sake of readability and compactness, and to save typing/avoid boilerplate code.
- Use the `ITK_TEST_SET_GET_VALUE``macro to check for expected values for the sake of readability and compactness, and to save typing/avoid boilerplate code. Take advantage of the commit to make testing the getter methods quantitative by checking their return value.
> STYLE: Prefer using testing macros in miscellaneous tests

- Modules/Numerics/Optimizers/test/itkAmoebaOptimizerTest.cxx
- Modules/Numerics/Optimizersv4/test/itkAmoebaOptimizerv4Test.cxx
- Modules/Numerics/Optimizersv4/test/itkGradientDescentOptimizerBasev4Test.cxx
- ENH: Increase `itk::SingleValuedNonLinearVnlOptimizer` coverage
- ENH: Increase coverage for   `itk::ObjectToObjectOptimizerBaseTemplate`
> ENH: Increase optimizer classes coverage

- Modules/Core/Common/test/itkMersenneTwisterRandomVariateGeneratorGTest.cxx
`MersenneTwisterRandomVariateGenerator::GetNextSeed()` is a static member function, so there is no need to call it via an instance of the generator, in the `MersenneTwisterRandomVariateGenerator.ResetNextSeed` unit test.
The commit also adds some documentation to the unit test.
Suggested by clang-tidy:
https://clang.llvm.org/extra/clang-tidy/checks/readability/static-accessed-through-instance.html
----
Obviously it was my own fault  😸 introduced with:
- https://github.com/InsightSoftwareConsortium/ITK/pull/4247
> STYLE: ResetNextSeed GTest should not use instance for GetNextSeed call

- Modules/Core/Transform/test/itkTransformGeometryImageFilterTest.cxx
Increase coverage for `itk::TransformGeometryImageFilter`: test raising an exception when attempting to use a non-linear transform.
> ENH: Increase coverage for `itk::TransformGeometryImageFilter`

- Modules/Core/Common/include/itkSmartPointer.h
- Modules/Core/Common/test/itkSmartPointerGTest.cxx
Eases code that uses both `itk` and `std` smart pointers. Also serves as a convenient shorter alternative to the somewhat lengthy "GetPointer()".
> ENH: Add `get()` member function to itk::SmartPointer

- Modules/Segmentation/ConnectedComponents/wrapping/itkConnectedComponentImageFilter.wrap
Currently, by default, `ConnectedComponentImageFilter` can output: US, SS, and UL pixel types, while `RelabelComponentImageFilter` does not accept UL as input, and accepts US, SS, and ULL (IdentifierType). Cast filter is also not wrapped for UL -> ULL conversion. That makes the following code unworkable on Windows:
```python
ul_type = itk.Image[itk.UL, 3]
cc_filter = itk.ConnectedComponentImageFilter[type(foreground), ul_type].New(foreground) cc_filter.SetFullyConnected(True)
cc_filter.Update()
components = cc_filter.GetOutput()
sorted_components = itk.relabel_component_image_filter(components.astype(itk.ULL))
```
> ENH: Add ULL type to ConnectedComponentImageFilter wrapping

- Documentation/docs/contributing/index.md
- Documentation/docs/contributing/module_workflows.md
- Documentation/docs/contributing/python_packaging.md
Migrate documentation for building ITK Python distributions and build archives with ITKPythonPackage.
Original source: https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/master/docs/Build_ITK_Python_packages.rst
Includes updates for ITK v5.3.0 and removed obsolete `sdist` instructions.
> DOC: Migrate and update docs for building ITK Python wheels

- Documentation/docs/index.md
- Documentation/docs/supported_compilers.md
Move supported compiler docs to sphinx and reorganize sections.
> Compiler docs

- Modules/Filtering/QuadEdgeMeshFiltering/test/itkDiscreteGaussianCurvatureQuadEdgeMeshFilterTest.cxx
- STYLE: Use medial capitals to name variables in test
- ENH: Increase itk::DiscreteGaussianCurvatureQuadEdgeMeshFilter coverage
> ENH: Increase `itk::DiscreteGaussianCurvatureQuadEdgeMeshFilter` coverage

- Modules/IO/XML/test/CMakeLists.txt
- Modules/IO/XML/test/itkFancyStringTest.cxx
- STYLE: Rename test to honor the tested class
- ENH: Increase coverage for `itk::FancyString`
- STYLE: Use testing macros in `itkFancyStringTest.cxx`
> ENH: Increase coverage for `itk::FancyString`

- Modules/Core/Common/include/itkShapedImageNeighborhoodRange.h
- Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx
Allowed the shape of a neighborhood to be specified by a C-array of offset, by using C++17 `std::data` and `std::size` internally, instead of `data()` and `size()` member functions.
> ENH: ShapedImageNeighborhoodRange support C-array of offsets (by C++17)

- .github/workflows/itk_dict.txt
- Modules/Core/Common/include/itkDeref.h
- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkDerefGTest.cxx
- Modules/IO/MeshVTK/test/itkVTKPolyDataMeshIOGTest.cxx
`Deref(ptr)` throws an exception when its argument (`ptr`) is null.
A similar function template is being used internally in elastix for quite a while: https://github.com/SuperElastix/elastix/blob/f64965f09eb0903e7bf1da4a112d914c7ac2ce22/Common/elxDeref.h
> Add `Deref(T *)`, to ease dereferencing a pointer safely

- Modules/Numerics/Optimizersv4/src/itkSingleValuedNonLinearVnlOptimizerv4.cxx
Fix `itk::SingleValuedNonLinearVnlOptimizerv4::CachedCurrentPosition` ivar initialization numeric trait template argument type.
> BUG: Fix `CachedCurrentPosition` ivar initialization numeric traits arg

- Modules/Numerics/Optimizersv4/test/itkAmoebaOptimizerv4Test.cxx
- Modules/Numerics/Optimizersv4/test/itkLBFGSOptimizerv4Test.cxx
Increase the code coverage for the
`itk::SingleValuedNonLinearVnlOptimizerv4` class: exercise the `GetCachedDerivative` and `GetCachedPosition` methods and test their values against the expected values.
> ENH: Increase the `itk::SingleValuedNonLinearVnlOptimizerv4` coverage

- Modules/Filtering/LabelMap/test/itkShapeOpeningLabelMapFilterTest1.cxx
Increase `itk::ShapeOpeningLabelMapFilter` coverage: exercise basic object methods using the `ITK_EXERCISE_BASIC_OBJECT_METHODS` macro.
> ENH: Increase `itk::ShapeOpeningLabelMapFilter` coverage

- Modules/Core/Common/test/itkImageRegionGTest.cxx
Added three GoogleTest unit tests:
- CropReturnsFalseWithoutChangingAnythingWhenItCannotCrop
- CropDoesNotChangeRegionToBeCroppedWhenCropRegionIsEqual
- CropLargerToSmallerRegionAndViceVersa
> ENH: Add `Crop` unit tests to itkImageRegionGTest

- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkXMLFilterWatcherTest.cxx
Add test for `itk::XMLFilterWatcher`: the watcher is applied to an image reading filter, and the progress updates written to the standard output by the filter are redirected to a text file through the CMake `--redirectOutput` option.
> ENH: Add test for `itk::XMLFilterWatcher`

- Modules/Core/Common/include/itkMultiThreaderBase.h
- Modules/Filtering/FFT/test/itkFFTWComplexToComplexFFTImageFilterTest.cxx
- Modules/Filtering/LabelMap/include/itkStatisticsLabelObject.h
By doing Notepad++ Replace in Files, having:
Find what:  return (.*);\r\n [ ]* break;
Replace with:  return $1;
Filters: itk*.h;itk*.hxx;itk*.cxx
[v] Match case
> STYLE: Remove unreachable `break` statements after `return` statements

- Modules/Core/Common/src/itkMultiThreaderBase.cxx
- Modules/Core/Common/src/itkProgressTransformer.cxx
- Modules/Filtering/Colormap/include/itkColormapFunction.h
- Modules/Filtering/Colormap/include/itkHSVColormapFunction.hxx
- Modules/Filtering/Colormap/include/itkHotColormapFunction.hxx
- Modules/Filtering/Colormap/include/itkJetColormapFunction.hxx
- Modules/Filtering/ImageGrid/include/itkSliceImageFilter.hxx
Follow-up to:
- pull request #3992
- pull request #4182
Use cases mostly found by Notepad++ regular expression `(.+) = std::m..\(.+;\r\n\1 = std::m..\(`.
> Replace `std::min` and `std::max` calls with `std::clamp`,  in "Colormap", `ProgressTransformer`, `SliceImageFilter`, and `MultiThreaderBase`.

- Documentation/docs/README.md
The link definition was never added.
> DOC: Add missing sphinx-autobuild link

- Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx
Replaced `std::recursive_mutex` with the more lightweight `std::mutex` as type of `MersenneTwisterGlobals::m_StaticInstanceLock`. This mutex is only used by `MersenneTwisterRandomVariateGenerator::GetInstance()`. This member function does not call itself, so the mutex does not need to be "recursive".
Renamed `MersenneTwisterGlobals::m_StaticInstanceLock` to `MersenneTwisterGlobals::m_StaticInstanceLock`
- following pull request #4217 commit 0150e469240879e8181ec10e919107061baca87e _STYLE: Rename private and internal data members from "Lock" to "Mutex"_
> `MersenneTwisterGlobals` replace `std::recursive_mutex` with `std::mutex`, rename data member from "Lock" to "Mutex"

- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkImageRandomConstIteratorWithIndexGTest.cxx
Tests that `ImageRandomConstIteratorWithIndex` is deterministic when the initial seed _and_ the next seed of the global `MersenneTwisterRandomVariateGenerator` are reset.
----
Follow-up to:
- PR https://github.com/InsightSoftwareConsortium/ITK/pull/4247
> ENH: Add `itkImageRandomConstIteratorWithIndexGTest` unit test

- Modules/IO/TransformBase/include/itkTransformFileWriter.h
- Modules/IO/TransformBase/src/itkTransformFileWriterSpecializations.cxx
- Modules/IO/TransformBase/test/itkTransformFileWriterTemplateTest.cxx
Add the boolean macro to the
`itk::RegistrationParameterScalesEstimator::m_AppendMode` ivar.
Use the setter and getter macros for the ivar.
Deprecate the old API of the ivar.
Check the expected values in the test using the appropriate testing macros.
> ENH: Add boolean macro to `TransformFileWriterTemplate::m_AppendMode`

- Modules/Core/Common/test/itkImageRegionGTest.cxx
The use of `std::numeric_limits<itk::IndexValueType>::max()` as `indexValue` in `ImageRegion.CropLargerToSmallerRegionAndViceVersa` caused signed integer overflow (undefined behavior). Mac14.x-AppleClang test failures were reported by Jon Haitz Legarreta Gorroño (@jhlegarreta). and debug output was provide by Alexandru Ciobanu (@devbanu), at pull request #4310
> BUG: Remove `numeric_limits<IndexValueType>::max` from ImageRegion GTest

- Modules/Core/Common/include/itkMultiThreaderBase.h
Detected by Coverity 2023.6.2.
In my tests (Linux, GCC 12.2) this avoids copy of `32 bytes * number of threads` for multi-threaded filters.
```
330  template <unsigned int VDimension>
331  ITK_TEMPLATE_EXPORT void
332  ParallelizeImageRegion(const ImageRegion<VDimension> &           requestedRegion,
333                         TemplatedThreadingFunctorType<VDimension> funcP,
334                         ProcessObject *                           filter)
335  {
336    this->ParallelizeImageRegion(
337      VDimension,
338      requestedRegion.GetIndex().m_InternalArray,
339      requestedRegion.GetSize().m_InternalArray,
CID 315595 (1-2 of 2): COPY_INSTEAD_OF_MOVE (COPY_INSTEAD_OF_MOVE)1. copy_constructor_call:
funcP is copied in call to copy constructor std::function<void …
```
> PERF: Fixed COPY_INSTEAD_OF_MOVE in MultiThreaderBase

- Modules/Core/Common/include/itkZeroFluxNeumannBoundaryCondition.hxx
- Modules/Core/SpatialObjects/test/itkSpatialObjectToImageStatisticsCalculatorTest.cxx
- Modules/Filtering/BinaryMathematicalMorphology/include/itkBinaryDilateImageFilter.hxx
- Modules/Filtering/BinaryMathematicalMorphology/include/itkBinaryErodeImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkMirrorPadImageFilter.hxx
- Modules/Filtering/ImageGrid/test/itkResampleImageTest8.cxx
- Modules/Filtering/ImageStatistics/include/itkProjectionImageFilter.hxx
- Modules/Numerics/Statistics/include/itkUniformRandomSpatialNeighborSubsampler.hxx
- Modules/Registration/Common/include/itkCompareHistogramImageToImageMetric.hxx
- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
- Modules/Segmentation/Watersheds/include/itkWatershedSegmenter.hxx
- Modules/Video/Core/test/itkImageToVideoFilterTest.cxx
- Modules/Video/Core/test/itkVectorImageToVideoTest.cxx
Fixed ITK.macOS/Darwin/Xcode_13.2.1/clang-1300.0.29.30 warnings that appear when `ImageRegion` is made trivially copyable, saying:
> warning: unused variable 'region' [-Wunused-variable]
Removed an obsolete type alias from itkResampleImageTest8.cxx, to avoid a warning, saying:
> warning: unused type alias 'OutputImageRegionType' [-Wunused-local-typedef]
----
This is in fact a "spin-off" (by-product) of pull request #4344: The "unused variable" warnings only appeared _after_ making `ImageRegion` trivially copyable.
> STYLE: Remove unused local `ImageRegion` variables

- Modules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceFilterEnum.h
Fixes build on gcc 13.2 and clang 17 (tested on Fedora 39), see also https://discourse.itk.org/t/build-error-with-g-13-2
> COMP: Add missing include (gcc13.2/clang17 build)

- Documentation/docs/index.md
- Documentation/docs/scientific_ecosystem/itk_ecosystem.md
Add ITK scientific ecosystem section to documentation:
- Include other tools developed around ITK that allow to leverage its use beyond its natural boundaries.
- Transition the wiki command line tools page: https://itk.org/Wiki/ITK/CommandLineTools
- Mention `ITKApps` as a set of legacy tools that leveraged ITK's capabilities without completely transitioning the corresponding https://itk.org/Wiki/ITK/Insight_Applications wiki page, as the instructions refer to old releases and tools.
> DOC: Add ITK scientific ecosystem section to documentation

- Documentation/docs/index.md
- Documentation/docs/learn/faq.md
Transfer the wiki FAQ page to Markdown documentation: https://itk.org/Wiki/ITK/FAQ
Add the corresponding entry in the `Learn` section of the documentation index.
Take advantage of the transition to:
- Update URLs, including changing `http` to `https`, fixing broken URLs,
etc.
- Link ITK and VTK classes to their Doxygen documentation pages.
- Highlight parts (e.g. class names) using Markdown syntax.
- Refactor the data format section to: include mesh and point set, and
transform file format sections, mention other file formats potentially
supported by remote modules. Add links to the file format reference
pages, and the Doxygen documentation of the ITK IO classes involved.
- Make the BibTeX list style consistent, remove broken URLs pointing to
old versions of the SW Guide or all pointing …
> DOC: Transfer the wiki FAQ page to Markdown documentation

- Modules/Core/Common/include/itkImageRegion.h
- Modules/Core/Common/include/itkImageRegion.hxx
- Modules/Core/Common/test/itkImageRegionGTest.cxx
Made all member functions of `ImageRegion` non-virtual, and removed its inheritance from `Region`.
The size of `ImageRegion<2>` was observed to go down from 40 bytes (before this commit) to 32 bytes (after this commit), on Visual C++ 2022 (x64). A run-time performance improvement of more than 25% on default-constructing and destructing a sequence of `ImageRegion` objects was observed, by benchmarking `std::make_unique<itk::ImageRegion<2>[]>(n)`.
> PERF: Make `ImageRegion` trivially copyable, remove inheritance (`ITK_FUTURE_LEGACY_REMOVE`)

- Modules/Filtering/LabelMap/test/Baseline/fillhole_test_3D_0.nrrd.cid
- Modules/Filtering/LabelMap/test/Baseline/fillhole_test_3D_1.nrrd.cid
- Modules/Filtering/LabelMap/test/CMakeLists.txt
- Modules/Filtering/LabelMap/test/Input/fillhole_test_3D.nrrd.cid
- Modules/Filtering/LabelMap/test/itkBinaryFillholeImageFilterTest1.cxx
- Modules/Filtering/LabelMap/wrapping/test/BinaryFillholeImageFilterTest.py
- Modules/Filtering/LabelMap/wrapping/test/CMakeLists.txt
> ENH: Add a 3D regression test for FillholeImageFilter

- Documentation/docs/contributing/dashboard.md
- Documentation/docs/contributing/data.md
- Documentation/docs/contributing/index.md
- Documentation/docs/contributing/python_packaging.md
- Documentation/docs/contributing/updating_third_party.md
- Documentation/docs/contributing/upload_binary_data.md
- Documentation/docs/learn/python_quick_start.md
Remove prompt symbol and spaces in Markdown documentation bash blocks: allows to copy and paste the commands directly.
> STYLE: Remove prompt and spaces in Markdown documentation bash blocks

- Modules/Core/Common/include/itkImportImageContainer.h
- Modules/Core/Common/include/itkImportImageContainer.hxx
- Modules/Core/Common/include/itkVectorImage.h
- Modules/Core/Common/include/itkVectorImage.hxx
Comments and the parameter _UseValueInitialization_ better describe the behavior of the
_ImportImageContainer_.
The same parameter in _VectorImage_ has also been updated.
Also removed comment from AllocateElements about 'new' and throwing
or not throwing an exception if allocation fails.
Closes #4359
> STYLE: Update comments and parameter in the ImportImageContainer

- Modules/Filtering/ImageLabel/wrapping/itkScanlineFilterCommon.wrap
Trying to address:
`itkConnectedComponentImageFilter: warning(4): ITK type not wrapped, or currently not known: itk::ScanlineFilterCommon< itk::Image< short, 2 >, itk::Image< unsigned long long, 2 > >`
Introduced by 89edcf37641f794938ea4f08d4ae24f1f68d685c from PR #4294.
> COMP: Add ULL wrapping for ScanlineFilterCommon

- Documentation/docs/learn/faq.md
Remove mentions to deprecated `ITKApps` from FAQs.
Take advantage of the commit to adapt the text as necessary: fix typos and remove meaningless passages.
> DOC: Remove mentions to deprecated `ITKApps` from FAQs

- Documentation/docs/contributing/documenting_itk.md
- Documentation/docs/contributing/index.md
Transfer the wiki documenting ITK page to Markdown documentation: https://itk.org/Wiki/ITK/Doxygen_Documentation.
Complete the documentation about linking to ITK Sphinx examples, and remove the empty/no longer relevant maintainance and Doxygen warning section.
Enhance the syntax for an improved highlighting.
> DOC: Transfer the wiki documenting ITK page to Markdown documentation

- Wrapping/Generators/Python/itk/support/helpers.py
- Wrapping/Generators/Python/itk/support/types.py
https://discourse.itk.org/t/torch-import-time/6354
Torch takes time to import. In types.py torch is imported to check if it's present or not in the environment, but it's never used.
Now, torch is detected with importlib.metadata.
> PERF: Do not import torch to reduce itk import time

- Modules/Core/Common/include/itkMultiThreaderBase.h
Style improvements `MultiThreaderBase::ParallelizeImageRegionRestrictDirection`:
- Replaced an "if" with "constexpr if", allowing to simplify the initialization of `SplitDimension`
- Removed the two `continue` statements, following [C++ Core Guidelines, "Minimize the use of `break`
and `continue` in loops"](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es77-minimize-the-use-of-break-and-continue-in-loops)
- Replaced the local `splitRegion` variable with more lightweight `splitIndex` and `splitSize` variables
- Replaced the default capture `[&]` of the local lambda with an explicit capture list, capturing `restrictedDirection` by value instead of by reference
> Use "constexpr if" in `MultiThreaderBase::ParallelizeImageRegionRestrictDirection`, and other style improvements

- Documentation/docs/index.md
- Documentation/docs/learn/third_party_applications.md
Transfer the wiki 3rd party applications page to Markdown documentation: https://itk.org/Wiki/ITK/Third_Party_Applications.
Update the links and explanations as necessary.
Remove the mention of ITK packages for Ubuntu, as they no longer exist.
> DOC: Transfer the wiki 3rd party apps page to Markdown documentation

- Documentation/docs/learn/faq.md
Redirect the transferred wiki links to their corresponding current locations in the `docs` folder.
> DOC: Redirect to current location in docs transferred wiki links

- Modules/Core/Common/include/itkImageRegion.hxx
- Modules/Core/Common/include/itkNeighborhood.hxx
- Modules/Core/Common/include/itkSize.h
- Modules/Core/Common/test/itkSizeGTest.cxx
Added `CalculateProductOfElements()`, as a convenience function of `Size`, typically useful to determine the total number of pixels (2D) or voxels (3D).
Let `ImageRegion::GetNumberOfPixels()` and `Neighborhood::SetRadius` call `Size::CalculateProductOfElements()`.
> Add `Size::CalculateProductOfElements()`, let it be called by `ImageRegion::GetNumberOfPixels()`, `Neighborhood::SetRadius`

- .github/workflows/itk_dict.txt
- Modules/Core/Common/include/itkImageRegion.h
- Modules/Core/Common/test/itkImageRegionGTest.cxx
Added `get()` member functions and specializations of `std::tuple_size` and `std::tuple_element` for ImageRegion, in order to support structured binding, for example:
auto [index, size] = image.GetRequestedRegion();
> ENH: `ImageRegion` support C++17 structured binding

- Examples/Filtering/CompositeFilterExample.cxx
- Examples/IO/XML/itkParticleSwarmOptimizerDOMReader.h
- Examples/IO/XML/itkParticleSwarmOptimizerDOMWriter.h
- Examples/IO/XML/itkParticleSwarmOptimizerSAXReader.h
- Examples/IO/XML/itkParticleSwarmOptimizerSAXWriter.h
- Examples/RegistrationITKv4/ModelToImageRegistration1.cxx
- Examples/Statistics/WeightedSampleStatistics.cxx
- Wrapping/Generators/Python/PyUtils/itkPyCommand.h
- Wrapping/Generators/Python/PyUtils/itkPyImageFilter.h
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4373 commit 2c264ea2ef62e916c6ef947599ce659cc8fce5fe
"STYLE: Replace itkTypeMacro calls with `itkOverrideGetNameOfClassMacro`"
----
Addresses "ITK_FUTURE_LEGACY_REMOVE" compile errors from RogueResearch19/Mac12.x-AppleClang-dbg-Universal at https://open.cdash.org/viewBuildError.php?buildid=9269183 saying:
```
/Users/builder/externalExamples/Filtering/CompositeFilterExample.cxx:89:3: error: static_assert failed "In a future revision of ITK, the macro `itkTypeMacro(thisClass, superclass)` will be removed. Please call `itkOverrideGetNameOfClassMacro(thisClass)` instead!"
itkTypeMacro(CompositeExampleImageFilter, ImageToImageFilter);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[CTest: warning …
```
> Examples, PyUtils: Replace itkTypeMacro with itkOverrideGetNameOfClassMacro

- Modules/Core/Common/include/itkImageRegion.h
- Modules/Core/Common/test/itkImageRegionGTest.cxx
Simplified the definition of `IndexType` and `SizeType` in order to add CTAD support to `ImageRegion`. Added a deduction guide, to avoid compiler warnings.
Supports declaring a region, without explicitly specifying its dimension, e.g.:
itk::ImageRegion region(index, size);
> ENH: Add class template argument deduction (CTAD) support to ImageRegion

- Modules/Core/Common/include/itkMacro.h
- Modules/Numerics/Optimizers/test/itkAmoebaOptimizerTest.cxx
- Modules/Numerics/Optimizers/test/itkLBFGSOptimizerTest.cxx
- Modules/Segmentation/LevelSetsv4/include/itkBinaryImageToLevelSetImageAdaptor.h
Added a compile-time check on the `thisClass` argument of both `itkVirtualGetNameOfClassMacro` and `itkOverrideGetNameOfClassMacro`. Fixed the class name returned by three `GetNameOfClass()` overrides, including `BinaryImageToLevelSetImageAdaptor::GetNameOfClass()`
> Check `thisClass` argument of `GetNameOfClass` macro calls, fix class name returned by `GetNameOfClass()` overrides

- Modules/Core/Common/include/itkConnectedImageNeighborhoodShape.h
- Modules/Core/Common/include/itkSpatialOrientation.h
- Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx
- Modules/Filtering/MathematicalMorphology/include/itkMathematicalMorphologyEnums.h
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3250 commit c173dfd803acf943d9ab80683ac4133fea29cdf5 "STYLE: Remove `std::` prefix from types that work without it" by Lee Newberg (@Leengit), March 6, 2022.
---
Mentioned at https://discourse.itk.org/t/itkmathematicalmorphologyenums-h-compile-error-with-gcc-13-on-linux/6377/4
> Remove `std::` prefix from uint8_t in MathematicalMorphologyEnums, replace `<cstdint>` with "itkIntTypes.h"

- .github/workflows/itk_dict.txt
- Modules/Core/Common/include/itkCopy.h
- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkCopyGTest.cxx
Intended to be used to make the act of copying explicit, and to avoid warnings like:
- Microsoft Visual Studio 2022, IntelliSense Code Linter [lnt-accidental-copy] "`auto` doesn't deduce references. A possibly unintended copy is being made" (https://learn.microsoft.com/en-us/cpp/ide/lnt-accidental-copy)
- Microsoft Visual Studio 2022, Warning C26820, "This is a potentially expensive copy operation. Consider using a reference unless a copy is required (p.9)" (https://learn.microsoft.com/en-us/cpp/code-quality/c26820?view=msvc-170)
- Synopsys Coverity 2023.6.2, "CID 331225:  Performance inefficiencies  (AUTO_CAUSES_COPY)", "Using the `auto` keyword without an `&` causes the copy of an object...".
- SonarSource static code analysis, "Unnecessary expensive copy should be avoided when using …
> ENH: Add `itk::Copy(const T & original)`, which simply returns a copy

- Modules/Remote/Montage.remote.cmake
Addressing:
```log
M:\Dashboard\ITK\Modules\Remote\Montage\test\itkMontagePCMTestSynthetic.cxx(42,3): error C3203: 'Image': unspecialized class template can't be used as a template argument for template parameter '<unnamed-symbol>', expected a real type [M:\Dashboard\ITK-build\Modules\Remote\Montage\test\MontageTestDriver.vcxproj]
M:\Dashboard\ITK\Modules\Remote\Montage\test\itkMontagePCMTestSynthetic.cxx(42,3):
the template instantiation context (the oldest one first) is
M:\Dashboard\ITK\Modules\Remote\Montage\test\itkMontagePCMTestSynthetic.cxx(363,12):
see reference to function template instantiation 'int PhaseCorrelationRegistration<3,double,double>(int,char *[])' being compiled
M:\Dashboard\ITK\Modules\Remote\Montage\test\itkMontagePCMTestSynthetic.cxx(152,1):
see reference to class …
```
> ENH: Update Montage remote module

- Modules/Numerics/FEM/include/itkFEMLinearSystemWrapper.h
Fix name of class assertion failure for
`itk::fem::FEMExceptionLinearSystemBounds`: use the correct class name.
Fixes:
```
M:\Dashboard\ITK\Modules\Numerics\FEM\include\itkFEMLinearSystemWrapper.h(586,3):
error C2607: static assertion failed
[M:\Dashboard\ITK-build\Modules\Numerics\FEM\src\ITKFEM.vcxproj]
```
Raised for example in:
https://open.cdash.org/viewBuildError.php?buildid=9299844
> COMP: Fix name of class assertion failure in FEM module

- Modules/Core/Common/include/itkMacro.h
The added error message could be helpful when doing fixes like
- https://github.com/InsightSoftwareConsortium/ITK/pull/4398 (by @jhlegarreta)
> Add error message to static_assert in `GetNameOfClass()` macro, add `itkInternalGetNameOfClassImplementationMacro`

- Utilities/Hooks/pre-commit-style.bash
git hook commit error message if clang-format is not found needs to mention CMake flag ITK_USE_CLANG_FORMAT=True
> DOC: Fix git hook commit error message if clang-format is not found

- Utilities/ClangFormat/DownloadClangFormat.cmake
Example message:
```log
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.25/Modules/ExternalProject.cmake:3074 (message):
The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
not set.  The policy's OLD behavior will be used.  When using a URL
download, the timestamps of extracted files should preferably be that of
the time of extraction, otherwise code that depends on the extracted
contents might not be rebuilt if the URL changes.  The OLD behavior
preserves the timestamps from the archive instead, but this is usually not
what you want.  Update your project to the NEW behavior or specify the
DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
robustness issue.
C:/Program …
```
> COMP: Fix Warning for CMP0135 in remote modules (DownloadClangFormat)

- Modules/Bridge/VtkGlue/wrapping/CMakeLists.txt
Python wrapping of VTKGlue Bridge crashed during compilation and native bridge exists. Discussed here https://discourse.itk.org/t/itk-5-3-0-5-4rc-build-errors-shared-libs-python-wrappings-itkvtkglue-vs-2022-win11.
> COMP: Skip Python-Wrapping of ITKVtkGlue

- Modules/Core/Transform/include/itkCenteredSimilarity2DTransform.hxx
- Modules/Core/Transform/include/itkMatrixOffsetTransformBase.hxx
- Modules/Core/Transform/include/itkSimilarity2DTransform.hxx
- Took `GetInverseMatrix()` calls out of `for` loops
- Used previously ignored return values of initial `GetInverseMatrix()` calls
----
_Note:_ This PR may in some cases yield a performance improvement, but I just did not measure.  🤷 That's why I simply marked the commits "STYLE", rather than "PERF".
> Remove redundant `MatrixOffsetTransformBase::GetInverseMatrix()` calls

- Modules/Numerics/Optimizersv4/include/itkRegistrationParameterScalesEstimator.h
- Modules/Registration/Common/include/itkImageToImageMetric.h
- Modules/Registration/Metricsv4/include/itkImageToImageMetricv4.h
It is not useful to have both `itkSetObjectMacro(name, type)` and `itkSetConstObjectMacro(name, type)` with the very same `name` and `type`, in one and the same class.
Replaced the `itkSetObjectMacro` calls with the corresponding Set member functions, implemented by simply calling the "const" overload (as defined by the corresponding `itkSetConstObjectMacro` calls). Intended to remove those member functions in the future.
Found by regular expression:
^([ ]*)itkSetObjectMacro\((.+)\);\r\n\1itkSetConstObjectMacro\(\2\);
> STYLE: Remove itkSetObjectMacro if itkSetConstObjectMacro is also there

- Modules/Core/Common/include/itkSingleton.h
- Modules/Core/Common/src/itkPlatformMultiThreader.cxx
- Modules/Core/Common/src/itkPoolMultiThreader.cxx
- Modules/Core/Common/src/itkSingleton.cxx
- Modules/Core/Common/src/itkTBBMultiThreader.cxx
It's common practice to _move_ rather than to _copy_ `std::function` objects, when possible, as it might yield a performance gain.
> Let SetSingleMethod and Singleton _move_ their `std::function` argument

- Modules/Core/Common/include/itkMath.h
Enforced compile-time evaluation of conditions, when rounding and when doing `CastWithRangeCheck`.
> STYLE: Replace old `if` by "constexpr if" in `itk::Math` implementation

- Modules/Filtering/DisplacementField/include/itkTimeVaryingVelocityFieldIntegrationImageFilter.hxx
Warnings were raised here: https://open.cdash.org/viewBuildError.php?type=1&buildid=9322560
Message of the first one:
```log
Modules/Filtering/DisplacementField/include/itkTimeVaryingVelocityFieldIntegrationImageFilter.hxx:140:98: warning: instantiation of variable 'itk::NumericTraits<itk::Vector<double, 2>>::Zero' required here, but no definition is available [-Wundefined-var-template]
```
> COMP: Address clang warnings in a remote module

- Modules/Numerics/FEM/include/itkFEMSpatialObjectWriter.h
Fix `itk::FEMSpatialObjectWriter` Doxygen `brief` description: honor the purpose of the class.
> DOC: Fix `itk::FEMSpatialObjectWriter` Doxygen `brief` description

- Utilities/KWStyle/BuildKWStyle.cmake
Closes #4426. Integrates changes from https://github.com/Kitware/KWStyle/pull/108.
> ENH: Update KWStyle to avoid a CMake warning during its configure step

- Modules/Core/Common/include/itkSingleton.h
- Modules/Core/Common/src/itkSingleton.cxx
A simple `struct` appears more readable than an `std::tuple`, in this case, especially because the struct has a name for each data element (`Instance` and `DeleteFunc`), whereas each tuple data element is only accessed by its number.
---
Inspired by a discussion on `std::tuple` versus `struct`, at:
- https://github.com/isocpp/CppCoreGuidelines/pull/2166
> STYLE: Replace tuple with private GlobalObject struct, in SingletonIndex

- Modules/Numerics/FEM/test/itkFEMObjectTest.cxx
- Modules/Numerics/FEM/test/itkFEMObjectTest2.cxx
Remove unnecessary `itkFEMSpatialObjectWriter.h` includes in `FEM` object tests and apply the "include-what-you-use" principle.
> COMP: Remove unnecessary `itkFEMSpatialObjectWriter.h` includes

- Modules/Core/Common/include/itkVariableLengthVector.hxx
- Modules/Core/Common/test/itkImageIteratorWithIndexTest.cxx
- Modules/Core/Common/test/itkMathCastWithRangeCheckTest.cxx
- Modules/Core/Transform/include/itkScalableAffineTransform.hxx
- Modules/Filtering/BiasCorrection/test/itkCompositeValleyFunctionTest.cxx
- Modules/Filtering/DistanceMap/include/itkSignedMaurerDistanceMapImageFilter.hxx
- Modules/Filtering/FastMarching/include/itkFastMarchingImageFilter.h
- Modules/Filtering/FastMarching/include/itkFastMarchingImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkBSplineControlPointImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkBSplineScatteredDataPointSetToImageFilter.hxx
- Modules/Filtering/ImageGrid/test/itkWarpImageFilterTest.cxx
- Modules/Filtering/LabelMap/include/itkStatisticsLabelMapFilter.hxx
- Modules/Filtering/Thresholding/include/itkHuangThresholdCalculator.hxx
- Modules/Numerics/Optimizersv4/test/itkLBFGSBOptimizerv4Test.cxx
- Modules/Numerics/Optimizersv4/test/itkLBFGSOptimizerv4Test.cxx
- Modules/Registration/Metricsv4/test/itkJointHistogramMutualInformationImageToImageMetricv4Test.cxx
- Modules/Segmentation/KLMRegionGrowing/include/itkKLMSegmentationBorder.h
- Modules/Segmentation/RegionGrowing/include/itkIsolatedConnectedImageFilter.hxx
17 files had `#include "itkMath.h"` twice and one file 3 times.
> STYLE: remove duplicated itkMath.h headers

- Modules/Filtering/Denoising/include/itkPatchBasedDenoisingImageFilter.hxx
- Modules/Segmentation/LevelSets/include/itkThresholdSegmentationLevelSetFunction.hxx
- Modules/Segmentation/LevelSets/include/itkVectorThresholdSegmentationLevelSetFunction.hxx
- Modules/Segmentation/LevelSets/test/itkVectorThresholdSegmentationLevelSetImageFilterTest.cxx
Unused and unnecessary _itkImageFileWriter.h_ in _Filtering_ and _Segmentation_ modules.
> STYLE: remove unnecessary itkImageFileWriter.h header

- Modules/Filtering/Denoising/include/itkPatchBasedDenoisingImageFilter.hxx
- Modules/Filtering/ImageNoise/include/itkNoiseBaseImageFilter.hxx
The ~~three~~ two commits (out of five) from pull request #4409 that seem uncontroversial.
The idea is that _even_ if we do not (yet?) add a compile-time check against using a floating point type as `TReturn` template argument, we should still _avoid_ using a floating point type for `TReturn`! As documented:
https://github.com/InsightSoftwareConsortium/ITK/blob/66ab5b14c476d057ed46a4daba05b710681160e6/Modules/Core/Common/include/itkMath.h#L170-L172
Originally documented 15 years ago:
https://github.com/InsightSoftwareConsortium/ITK/blob/17269cbe9e620c308bf614a13f6acbbb4cc89e48/Code/Common/itkMath.h#L151-L153
> Fix `Math::Round` calls that have a floating point type as template argument

- Modules/Core/SpatialObjects/include/itkSpatialObject.h
- Modules/Core/SpatialObjects/include/itkSpatialObject.hxx
Replaced `this->GetObjectToWorldTransformInverse()` calls with direct access to m_ObjectToWorldTransformInverse. A performance improvement greater than 6% was observed, from more than 0.74 sec. down to less than 0.69 sec, when calling `IsInsideInWorldSpace` 2^25 times (as tested on VS2019 Release).
> PERF: Let SpatialObject directly access m_ObjectToWorldTransformInverse

- Modules/Core/SpatialObjects/include/itkSpatialObject.h
Replaced SpatialObject examples of virtual functions that one may override, as `ValueAtInWorldSpace`,
`IsEvaluableAtInWorldSpace`, and `IsInsideInWorldSpace` may not need to be overridden. Actually it appears that none of the thirteen derived SpatialObject classes of ITK itself does override any of those three member functions!
Used the word "override" more consistently, and removed the term "pure virtual function".
> Documentation improvements on overriding `SpatialObject` member functions

- Modules/Core/SpatialObjects/include/itkSpatialObject.h
- Modules/Core/SpatialObjects/include/itkSpatialObject.hxx
- Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectGTest.cxx
A performance improvement of more than 35% was observed, from more than 0.62 sec. to less than 0.38 sec. when calling IsInsideInWorldSpace(point) 2^25 times, using VS2022 Release.
----
Of course, this may yield a performance improvement for all classes that call `IsInsideInWorldSpace(point)`, including:
- SpatialObjectToImageStatisticsCalculator
- DiffusionTensor3DReconstructionImageFilter
- ImageMomentsCalculator
- HistogramImageToImageMetric
- ImageToImageMetric
- KappaStatisticImageToImageMetric
- MatchCardinalityImageToImageMetric
- MattesMutualInformationImageToImageMetric
- MeanReciprocalSquareDifferenceImageToImageMetric
- MutualInformationImageToImageMetric
- NormalizedCorrelationImageToImageMetric
- JointHistogramMutualInformationImageToImageMetricv4
- …
> PERF: Add SpatialObject IsInsideInWorldSpace(const PointType &) overload

- Modules/Core/SpatialObjects/include/itkSpatialObject.hxx
Suppressed the virtual call mechanism for
`m_ObjectToWorldTransformInverse->TransformPoint(point)` by explicit qualification with the `TransformType` scope, in the five `SpatialObject` "InWorldSpace" member functions.
A performance improvement of more than 13 % was observed, from more than 0.36 sec. (before this commit) to less than 0.31 sec. (after this commit) when calling IsInsideInWorldSpace(point) 2^25 times, using VS2022 Release.
---
Some background info:
`TransformType` is an alias for `AffineTransform<ScalarType, VDimension>`: https://github.com/InsightSoftwareConsortium/ITK/blob/2ca2351340a1a008beee2a2531c44117a9cfb19a/Modules/Core/SpatialObjects/include/itkSpatialObject.h#L99
`m_ObjectToWorldTransformInverse` is a `const` pointer, meaning that it always points to the very same …
> PERF: Make `m_ObjectToWorldTransformInverse->TransformPoint` non-virtual

- Modules/Core/Transform/wrapping/itkCompositeTransform.wrap
- Modules/Core/Transform/wrapping/itkMultiTransform.wrap
- Modules/Registration/RegistrationMethodsv4/wrapping/itkImageRegistrationMethodv4.wrap
For the use case of a float32 displacement vector field.
> ENH: Wrap CompositeTransform for float32 parameters

- Modules/Core/SpatialObjects/include/itkSpatialObject.h
Made a first step towards removing the `virtual` keyword from four `SpatialObject` "InWorldSpace" member functions, in the future:
ValueAtInWorldSpace
IsInsideInWorldSpace
IsEvaluableAtInWorldSpace
DerivativeAtInWorldSpace
These member functions are not really meant to be overridden. Removing these `virtual` keyword may yield a run-time performance improvement.
Following C++ Core Guidelines, October 12, 2023, "Don’t make a function `virtual` without reason",
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-virtual
---
Note that none of the thirteen derived SpatialObject classes of ITK does override any of those four member functions. So it appears that they really don't need to be declared `virtual`.
> STYLE: FUTURE_LEGACY_REMOVE virtual SpatialObject InWorldSpace functions

- Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx
- Modules/Core/SpatialObjects/include/itkImageSpatialObject.h
- Modules/Core/SpatialObjects/include/itkImageSpatialObject.hxx
- Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectGTest.cxx
`SpatialObject` stores the image regions of the spatial object. It appears reasonable for its derived class `ImageSpatialObject` to keep them up-to-date, in accordance with its image.
A significant performance improvement of `ImageMaskSpatialObject` is then achieved by using the buffered region and the requested region as cached in its base class, instead of calling the virtual functions `GetBufferedRegion()` and `GetRequestedRegion()` from its image.
----
It's interesting to see that the common base class `itk::SpatialObject` already has those data members to cache the image regions (`m_LargestPossibleRegion`, `m_RequestedRegion`, `m_BufferedRegion`), but it looks like they weren't used anywhere, as far as I can see:
https://github.com/InsightSoftwareConsortium/ITK/blob/436423d798e63e7244 …
> Let `ImageSpatialObject` update the image regions of its base class, let `ImageMaskSpatialObject` use these image regions

- Modules/Core/SpatialObjects/include/itkSpatialObject.h
`MaximumDepth` should just be "as high as possible" (or as _deep_ as possible), in order for a function call like `IsInsideInObjectSpace(point, MaximumDepth)` to go _as deep as possible_.
----
This pull request replaces `9999999` with `std::numeric_limits<unsigned int>::max()`, which is typically `4294967295`  (assuming 32-bit int). That's obviously a lot more than `9999999`, but in practice the depth won't go _near_ either of those two numbers. So I consider this to be a style improvement, not an enhancement.
> STYLE: Replace magic number SpatialObject `MaximumDepth = 9999999`

- Modules/Core/Common/include/itkMacro.h
Three little style improvements:
- Let `x::CreateAnother()` just return `x::New().GetPointer()`
- Let itkFactorylessNewMacro directly initialize its `smartPtr`
- Let itkFactorylessNewMacro(x) just call itkCreateAnotherMacro(x)
> Simplify itkCreateAnotherMacro(x) and itkFactorylessNewMacro(x)

- Modules/Core/Common/src/itkPlatformMultiThreaderSingle.cxx
The top of MultipleMethodExecute() in itkPlatformMultiThreaderSingle.cxx was outdated. I have copied two lines from itkPlatformMultiThreaderWindows.cxx in order to fix it. This problem was mentioned in as an issue but not yet fixed: https://github.com/InsightSoftwareConsortium/ITK/issues/3163.
> COMP: Fix MultiThreaderSingle typos

- Documentation/docs/supported_compilers.md
Provide more background and guidance on the standard per-operating system compilers and pointers on how to install them.
> DOC: More background for supported compilers

- Modules/Core/SpatialObjects/include/itkSpatialObject.hxx
Two little style improvements:
- Let `SpatialObject` directly access `m_ObjectToWorldTransform` (similar to pull request #4435)
- Use `std::transform` for `transformedCorners`
> Let `SpatialObject` directly access `m_ObjectToWorldTransform`, use `std::transform` for `transformedCorners`

- Modules/Core/Common/include/itkNumericTraitsCovariantVectorPixel.h
- Modules/Core/Common/include/itkNumericTraitsDiffusionTensor3DPixel.h
- Modules/Core/Common/include/itkNumericTraitsFixedArrayPixel.h
- Modules/Core/Common/include/itkNumericTraitsPointPixel.h
- Modules/Core/Common/include/itkNumericTraitsRGBAPixel.h
- Modules/Core/Common/include/itkNumericTraitsRGBPixel.h
- Modules/Core/Common/include/itkNumericTraitsTensorPixel.h
- Modules/Core/Common/include/itkNumericTraitsVectorPixel.h
- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkCovariantVectorGTest.cxx
- Modules/Core/Common/test/itkDiffusionTensor3DGTest.cxx
- Modules/Core/Common/test/itkPointGTest.cxx
- Modules/Core/Common/test/itkRGBAPixelGTest.cxx
- Modules/Core/Common/test/itkRGBPixelGTest.cxx
- Modules/Core/Common/test/itkSymmetricSecondRankTensorGTest.cxx
- Modules/Core/Common/test/itkVectorGTest.cxx
Tested that a "value-initialized" object of one of the `FixedArray` derived types, `CovariantVector` `DiffusionTensor3D`, `RGBAPixel`, `RGBPixel`, `SymmetricSecondRankTensor`, `Point`, or `Vector` is zero-filled.
Replaced `MakeFilled<Self>(NumericTraits<T>::ZeroValue())` with `Self{}` in the `ZeroValue()` implementation of `NumericTraits` specializations.
----
Used the syntax `T{}` to create "value-initialized" objects of each of those types, see also: https://en.cppreference.com/w/cpp/language/value_initialization
> Add ValueInitializedIsZeroFilled tests, replace `MakeFilled<Self>(NumericTraits<T>::ZeroValue())` with `Self{}`

- Modules/Core/Common/include/itkImageRegion.h
After pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4367 commit 72aa9a602bd92b665acc915d8df4bd00a27c98f0 (ENH: `ImageRegion` support C++17 structured binding), a few unimportant `-Wmismatched-tags` warnings appeared from Mac10.13-AppleClang-rel-x86_64, at
https://open.cdash.org/build/9256915 as was reported to me by mail, from Dženan Zukić (@dzenanz) and Sean McBride (@seanm).
This commit locally disables those warnings, following https://github.com/Naios/continuable/blob/121265df7123cf672ea8db917eaca2d0fbd9aef5/include/continuable/continuable-result.hpp#L291-L308 by Denis Blank (@Naios).
> COMP: Locally ignore Clang `-Wmismatched-tags` warnings in `ImageRegion`

- Modules/Core/Common/test/itkCovariantVectorGTest.cxx
- Modules/Core/Common/test/itkDiffusionTensor3DGTest.cxx
- Modules/Core/Common/test/itkPointGTest.cxx
- Modules/Core/Common/test/itkRGBAPixelGTest.cxx
- Modules/Core/Common/test/itkRGBPixelGTest.cxx
- Modules/Core/Common/test/itkRangeGTestUtilities.h
- Modules/Core/Common/test/itkSymmetricSecondRankTensorGTest.cxx
- Modules/Core/Common/test/itkVectorGTest.cxx
Added `ExpectEachElementIsZero(const TRange &)` to the internal utilities of `itk::RangeGTestUtilities`.
Removed duplicated lambda definitions from the `ValueInitializedIsZeroFilled` unit tests that were introduced by pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4454 commit aa38dce1a520efde6120d6ed5c939f568581b8f6 (by myself, honestly, accidentally violating [the DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)  😸).
> STYLE: Replace `expectZeroFilled` lambda's with ExpectEachElementIsZero

- Modules/IO/MeshBYU/src/itkBYUMeshIO.cxx
- Modules/IO/MeshFreeSurfer/src/itkFreeSurferAsciiMeshIO.cxx
- Modules/IO/MeshFreeSurfer/src/itkFreeSurferBinaryMeshIO.cxx
- Modules/IO/MeshOFF/src/itkOFFMeshIO.cxx
- Modules/IO/MeshVTK/src/itkVTKPolyDataMeshIO.cxx
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4460 commit 5d746cc0bc5efa6655580ee63c36cefde156a3c2
"STYLE: Replace `NumericTraits<unsigned int>::ZeroValue()` with `0U`"
> STYLE: Replace `itk::NumericTraits<unsigned int>::OneValue()` with `1`

- Modules/Compatibility/Deprecated/test/itkSpawnThreadTest.cxx
- Modules/Core/Common/src/itkMultiThreaderBase.cxx
- Modules/Core/Common/src/itkPlatformMultiThreader.cxx
- Modules/Core/Common/test/itkCMakeConfigurationTest.cxx
- Modules/Core/SpatialObjects/include/itkMetaImageConverter.h
- Modules/Core/SpatialObjects/include/itkMetaSceneConverter.hxx
- Modules/Core/SpatialObjects/test/itkTubeSpatialObjectTest.cxx
- Modules/Filtering/ImageFeature/test/itkMaskFeaturePointSelectionFilterTest.cxx
- Modules/Filtering/Smoothing/include/itkBoxUtilities.h
- Modules/IO/ImageBase/include/itkImageIOFactory.h
- Modules/IO/MeshBase/include/itkMeshIOFactory.h
- Modules/IO/TransformInsightLegacy/test/itkIOTransformTxtTest.cxx
- Modules/IO/TransformMINC/src/itkMINCTransformIO.cxx
- Modules/Registration/GPUPDEDeformable/test/itkGPUDemonsRegistrationFilterTest.cxx
- Modules/Registration/Metricsv4/test/itkDemonsImageToImageMetricv4RegistrationTest.cxx
Found using Notepad++ v8.6.2, Find in Files:
Find what: ^(#include "[^ ]+").+^\1
Find what: ^(#include <[^ ]+>).+^\1
Filters: itk*.hxx;itk*.h;itk*.cxx
[v] Match case
[v] . matches newline
Following pull requests like:
- https://github.com/InsightSoftwareConsortium/ITK/pull/4436 commit 3cafe87c588969d7e567aac053cdf2aeab83fd31
"STYLE: remove duplicated itkMath.h headers", by Mihail Isakov (@issakomi)
- https://github.com/InsightSoftwareConsortium/ITK/pull/3904 commit 48025bd985d17c53cb11ca4dc739cb83d4cc4802
"ENH: Remove `itkMath.h` duplicate include", by Jon Haitz Legarreta Gorroño (@jhlegarreta)
> STYLE: Remove duplicate `#include` directives

- Modules/Core/Common/include/itkRGBAPixel.h
- Modules/Core/Common/include/itkRGBPixel.h
- Modules/Core/Common/test/itkCommonTypeTraitsGTest.cxx
Will make `image.Allocate()` and `image.Allocate(false)` calls much, much
faster, for RGB and RGBA images, when `ITK_FUTURE_LEGACY_REMOVE` is enabled.
An `Allocate()` call on a 1024x1024x1024 RGB image was observed to take more than
1.3 sec. before this commit, and less than 0.001 sec. after this commit, having
`ITK_FUTURE_LEGACY_REMOVE=ON`, using Visual C++ 2019 Release. Even
`image.Allocate(true)` (`initializePixels` = true) appears slightly faster now
with `ITK_FUTURE_LEGACY_REMOVE`.
Adjusted unit tests tests from itkCommonTypeTraitsGTest, because `RGBPixel` and
`RGBAPixel` become "trivial" types when they get defaulted default-constructors.
> PERF: FUTURE: Default default-constructors of `RGBPixel` and `RGBAPixel`

- Modules/Core/ImageFunction/include/itkNearestNeighborExtrapolateImageFunction.h
- Modules/Filtering/ImageGrid/test/itkZeroFluxNeumannPadImageFilterTest.cxx
Aims to improve code readability, and might improve the performance of `NearestNeighborExtrapolateImageFunction`
member functions `EvaluateAtIndex` and `EvaluateAtContinuousIndex`.
> NearestNeighborExtrapolateImageFunction: use `std::clamp` and move GetStartIndex(), GetEndIndex() calls out of its `for` loops 

- Modules/Core/Common/include/itkSymmetricSecondRankTensor.h
- Modules/Core/Common/test/itkCommonTypeTraitsGTest.cxx
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4469 commit 755cd10e5421d41f4004be101c888d5ba24be8e4
"PERF: FUTURE: Default default-constructors of `RGBPixel` and `RGBAPixel`"
> PERF: FUTURE: Default default-constructor of `SymmetricSecondRankTensor`

- Modules/Core/Common/include/itkNeighborhoodAlgorithm.hxx
- Modules/Core/ImageFunction/include/itkLinearInterpolateImageFunction.h
- Modules/Core/ImageFunction/include/itkLinearInterpolateImageFunction.hxx
- Modules/Core/ImageFunction/include/itkVectorLinearInterpolateImageFunction.hxx
- Modules/Core/Mesh/include/itkTriangleMeshToBinaryImageFilter.hxx
- Modules/Core/SpatialObjects/include/itkContourSpatialObject.hxx
- Modules/Core/SpatialObjects/include/itkPolygonSpatialObject.hxx
- Modules/Core/SpatialObjects/include/itkSpatialObjectToImageStatisticsCalculator.hxx
- Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.hxx
- Modules/Filtering/DistanceMap/include/itkDanielssonDistanceMapImageFilter.hxx
- Modules/Filtering/ImageSources/include/itkGridImageSource.hxx
- Modules/Filtering/ImageStatistics/include/itkLabelStatisticsImageFilter.hxx
- Modules/Filtering/Smoothing/include/itkBinomialBlurImageFilter.hxx
- Modules/IO/Meta/test/itkMetaImageStreamingWriterIOTest.cxx
- Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.hxx
- Modules/Numerics/Optimizersv4/include/itkRegistrationParameterScalesEstimator.hxx
- Modules/Numerics/Optimizersv4/include/itkRegistrationParameterScalesFromShiftBase.hxx
- Modules/Numerics/Optimizersv4/test/itkRegistrationParameterScalesEstimatorTest.cxx
- Follow-up to pull request #4470
> Replace `if (x > a[i]) x = a[i]` with `x = std::min(x, a[i])`, and `if (x < a[i]) x = a[i]` with `x = std::max(x, a[i])`

- Modules/Core/Common/include/itkCovariantVector.hxx
- Modules/Core/Common/include/itkPoint.hxx
- Modules/Core/Common/include/itkVector.hxx
The three "const" overloads of `GetVnlVector()` return an vnl_vector, not a vnl_vector_ref, so it is not necessary for these overloads to internally create a temporary vnl_vector_ref.
----
For the record, the original approach for those overloads to create a vnl_vector_ref and convert it to a vnl_vector was by commit a1cd655268082d6a1125ca7c83bbaf59bc0f32ed, "OPT: optimizations", Jim Miller, 2004.
> STYLE: Remove temporary vnl_vector_ref from const GetVnlVector overloads

- Modules/Compatibility/Deprecated/include/itkImageTransformer.h
- Modules/Core/Common/include/itkImageToImageFilter.h
Replaced these member functions with the equivalent using-declarations, as they only just forwarded to their `Superclass` anyway.
Aims to address their lack of coverage, at
https://open.cdash.org/viewCoverageFile.php?buildid=9419378&fileid=57778588
----
Inspired by @jhlegarreta https://discourse.itk.org/t/concerning-coverage-drops/6479 and issue #4486
> STYLE: Replace `PushBackInput`, `PushFrontInput` with using-declarations

- Modules/Core/Common/include/itkImageBase.hxx
- Modules/Core/Common/include/itkImageSink.hxx
- Modules/Core/Common/include/itkImageToImageFilter.hxx
- Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.hxx
- Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx
- Modules/Numerics/Optimizersv4/include/itkObjectToObjectMetric.hxx
The `vnl_matrix_fixed::as_ref()` calls are no longer necessary, now that `vnl_matrix_fixed` directly supports `is_equal`:
- VXL pull request https://github.com/vxl/vxl/pull/317 commit https://github.com/vxl/vxl/commit/aa373fc84efa2d0e2ae3c0b3716bbf8dda554e71 "ENH: Encourage unified container interface.", Davis Vigneault (@sudomakeinstall), June 16, 2016
> STYLE: Remove `as_ref()` when calling `is_equal` on direction matrices

- Modules/Filtering/DisplacementField/include/itkConstantVelocityFieldTransform.hxx
- Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.hxx
- Modules/Filtering/DisplacementField/include/itkVelocityFieldTransform.hxx
- Modules/Filtering/FastMarching/include/itkFastMarchingImageFilterBase.hxx
- Modules/Filtering/ImageFeature/include/itkLaplacianRecursiveGaussianImageFilter.hxx
- Modules/Filtering/ImageGradient/include/itkGradientMagnitudeRecursiveGaussianImageFilter.hxx
- Modules/Filtering/ImageGrid/include/itkBSplineScatteredDataPointSetToImageFilter.hxx
- Modules/Filtering/LabelMap/include/itkShapeLabelMapFilter.hxx
- Modules/Nonunit/Review/include/itkDiscreteGaussianDerivativeImageFunction.hxx
- Modules/Nonunit/Review/include/itkDiscreteGradientMagnitudeGaussianImageFunction.hxx
- Modules/Nonunit/Review/include/itkDiscreteHessianGaussianImageFunction.hxx
- Modules/Registration/Common/include/itkTimeVaryingBSplineVelocityFieldTransformParametersAdaptor.hxx
- Modules/Registration/Metricsv4/include/itkJointHistogramMutualInformationComputeJointPDFThreaderBase.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkBSplineSyNImageRegistrationMethod.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkSyNImageRegistrationMethod.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkTimeVaryingBSplineVelocityFieldImageRegistrationMethod.hxx
- Modules/Segmentation/LevelSets/include/itkCollidingFrontsImageFilter.hxx
- Modules/Segmentation/LevelSetsv4/include/itkLevelSetContainer.h
- Modules/Segmentation/LevelSetsv4/include/itkLevelSetDomainMapImageFilter.hxx
- Modules/Segmentation/RegionGrowing/include/itkConfidenceConnectedImageFilter.hxx
- Modules/Segmentation/RegionGrowing/include/itkConnectedThresholdImageFilter.hxx
- Modules/Segmentation/RegionGrowing/include/itkIsolatedConnectedImageFilter.hxx
- Modules/Segmentation/RegionGrowing/include/itkVectorConfidenceConnectedImageFilter.hxx
- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
- Modules/Segmentation/Watersheds/include/itkTobogganImageFilter.hxx
Replaced lines of code of the form
image>Allocate();
image>FillBuffer(zero);
With `image->AllocateInitialized();`.
Cases found by the regular expression `^(.+->)Allocate.+;\r\n\1FillBuffer`.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4479 commit 47fe345cd81c8126e1a50d43c751cc67d6ebfc47
"ENH: Add `AllocateInitialized()` to ImageBase"
> STYLE: Replace `Allocate(); FillBuffer(0)` with `AllocateInitialized()`

- Modules/Core/ImageFunction/include/itkLinearInterpolateImageFunction.h
Two little `LinearInterpolateImageFunction` coding style improvements.
> Combine assignments to `basei[i]` in LinearInterpolateImageFunction, remove `&` from `distance` variables

- Modules/IO/GE/src/itkGE4ImageIO.cxx
This just prevents finding them when periodically checking that no new sprintf snuck in.
> ENH: Replaced a few remaining sprintf (comments only)

- Utilities/Doxygen/DoxygenConfig.cmake
Currently, the itkVirtualGetNameOfClassMacro and itkOverrideGetNameOfClassMacro calls do not get expanded properly by Doxygen. This commit aims to fix the output from Doxygen at https://itk.org/Doxygen/html/
> DOC: Add `GetNameOfClass` macro's to DOXYGEN_PREDEFINED

- Modules/Core/ImageFunction/wrapping/itkNearestNeighborInterpolateImageFunction.wrap
Adding support for vector, RGB, and RGBA pixel types in wrapping
of itkNearestNeighborInterpolateImageFunction.   This will allow,
for example, the wrapped ResampleImageFilter to be called with
an RGB/RGBA pixel type image and use an nearestneighbor interpolator.
Currently only the linear interpolator had RGB/RGBA wrapping.
No C++ code changes were needed.  
Examples and tests already exist, e.g., ResampleImageFilterTest5 for RGBPixel type.
> ENH: Extend NearestNeighborInterpolateImageFunc wrapping for RGB

- Modules/IO/GE/src/itkGE4ImageIO.cxx
- Modules/IO/GE/src/itkGE5ImageIO.cxx
Enabling `VERBOSE_DEBUGGING` would cause compilation errors (for example, about `debugbuf` being undeclared), which suggests that the option has not been used for a long time. It seems that those `RGEDEBUG` macro calls were only useful during the initial development of `GE4ImageIO`, more than 20 years ago.
"itkGE5ImageIO.cxx" also defined `RGEDEBUG`, but it did not call the macro anyway.
- Triggered by a discussion at https://github.com/InsightSoftwareConsortium/ITK/pull/4492
> STYLE: Remove outdated VERBOSE_DEBUGGING/RGEDEBUG support from "IO/GE"

- Modules/Core/Common/include/itkArray2D.h
- Modules/Core/Common/include/itkArray2D.hxx
- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkArray2DGTest.cxx
- Modules/Filtering/BiasCorrection/include/itkMRIBiasFieldCorrectionFilter.hxx
- Modules/Registration/Common/include/itkMultiResolutionPyramidImageFilter.hxx
- Modules/Registration/Common/test/itkMultiResolutionPyramidImageFilterTest.cxx
Added a `Array2D(numberOfRows, numberOfCols, initialValue)` constructor, which just calls the corresponding `vnl_matrix` constructor. Added a few use cases, which aim to simplify resetting `ScheduleType` objects.
Updated the documentation of `Array2D`.
> Add `Array2D(numberOfRows, numberOfCols, initialValue)` constructor

- Modules/Compatibility/Deprecated/include/itkVectorCentralDifferenceImageFunction.h
- Modules/Compatibility/Deprecated/include/itkVectorCentralDifferenceImageFunction.hxx
- Modules/Core/FiniteDifference/include/itkFiniteDifferenceImageFilter.h
- Modules/Core/FiniteDifference/include/itkFiniteDifferenceImageFilter.hxx
- Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.h
- Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.hxx
- Modules/Core/ImageFunction/include/itkCentralDifferenceImageFunction.h
- Modules/Core/ImageFunction/include/itkCentralDifferenceImageFunction.hxx
- Modules/Core/ImageFunction/include/itkGaussianBlurImageFunction.h
- Modules/Core/ImageFunction/include/itkGaussianBlurImageFunction.hxx
- Modules/Filtering/DisplacementField/include/itkDisplacementFieldJacobianDeterminantFilter.h
- Modules/Filtering/DisplacementField/include/itkDisplacementFieldJacobianDeterminantFilter.hxx
- Modules/Filtering/DistanceMap/include/itkContourDirectedMeanDistanceImageFilter.h
- Modules/Filtering/DistanceMap/include/itkContourDirectedMeanDistanceImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkContourMeanDistanceImageFilter.h
- Modules/Filtering/DistanceMap/include/itkContourMeanDistanceImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkDanielssonDistanceMapImageFilter.h
- Modules/Filtering/DistanceMap/include/itkDanielssonDistanceMapImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkHausdorffDistanceImageFilter.h
- Modules/Filtering/DistanceMap/include/itkHausdorffDistanceImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkSignedDanielssonDistanceMapImageFilter.h
- Modules/Filtering/DistanceMap/include/itkSignedDanielssonDistanceMapImageFilter.hxx
- Modules/Filtering/ImageGradient/include/itkGradientImageFilter.h
- Modules/Filtering/ImageGradient/include/itkGradientImageFilter.hxx
- Modules/Filtering/ImageGradient/include/itkGradientRecursiveGaussianImageFilter.h
- Modules/Filtering/ImageGradient/include/itkGradientRecursiveGaussianImageFilter.hxx
- Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.h
- Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.hxx
- Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.h
- Modules/Registration/PDEDeformable/include/itkLevelSetMotionRegistrationFunction.hxx
Removed `m_UseImageDirection = true` and `m_UseImageSpacing = true` assignment from the function body of the corresponding constructors.
Following C++ Core Guidelines, ["Prefer initialization to assignment in constructors"](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c49-prefer-initialization-to-assignment-in-constructors)
Default member initializers also have the advantage that those default values will be shown in the API documentation. For example, https://itk.org/Doxygen/html/classitk_1_1GradientImageFilter.html now still says:
bool 	m_UseImageDirection {}
bool 	m_UseImageSpacing {}
But it will show the default value `true` for those member variables, once this pull request is processed.
> Use `true` as default member initializer for m_UseImageDirection and m_UseImageSpacing

- Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx
- Modules/IO/DCMTK/test/CMakeLists.txt
- Modules/IO/DCMTK/test/Input/no_preamble.dcm.cid
- Modules/IO/DCMTK/test/Input/preamble.dcm.cid
- Modules/IO/GDCM/test/Baseline/no_preamble.mha.cid
- Modules/IO/GDCM/test/Baseline/preamble.mha.cid
- Modules/IO/GDCM/test/CMakeLists.txt
- Modules/IO/GDCM/test/Input/no_preamble.dcm.cid
- Modules/IO/GDCM/test/Input/preamble.dcm.cid
A previous optimization didn't take into account the preamble of a dicom file.  This adds a check.
Fixes #4108
> BUG: DCMTK reader wrongly rejects file with preamble

- Modules/Core/Transform/include/itkMatrixOffsetTransformBase.hxx
- Modules/Core/Transform/test/itkEuler3DTransformGTest.cxx
- Modules/Core/Transform/test/itkSimilarity2DTransformTest.cxx
When setting a transform to represent an Identity mapping, it is crucial that the stationary component of the transform is preserved.
```python
tfm.SetCenter( [1,2,3] );
tfm.SetIdentity();
out=tfm.GetCenter();
assert( out == [1,2,3] );
```
files (if any)
> Fixed parameter preservation after identity

- Modules/Registration/Common/include/itkImageToImageMetric.h
- Modules/Registration/Common/include/itkImageToImageMetric.hxx
- Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.hxx
m_TransformIsBSpline is always just equal to `m_BSplineTransform != nullptr`, and m_InterpolatorIsBSpline is always just equal to `m_BSplineInterpolator != nullptr`, so these Boolean data members are redundant and not really necessary.
> FUTURE_LEGACY_REMOVE ImageToImageMetric members m_InterpolatorIsBSpline and m_TransformIsBSpline

- Modules/Filtering/AnisotropicSmoothing/include/itkAnisotropicDiffusionImageFilter.hxx
- Modules/Filtering/DisplacementField/include/itkDisplacementFieldJacobianDeterminantFilter.hxx
- Modules/Filtering/GPUAnisotropicSmoothing/include/itkGPUAnisotropicDiffusionImageFilter.hxx
- Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.hxx
- Modules/Filtering/Smoothing/include/itkDiscreteGaussianImageFilter.hxx
- Modules/Nonunit/Review/include/itkAreaClosingImageFilter.h
- Modules/Nonunit/Review/include/itkAreaOpeningImageFilter.h
- Modules/Nonunit/Review/include/itkMultiphaseFiniteDifferenceImageFilter.hxx
- Modules/Nonunit/Review/include/itkWarpHarmonicEnergyCalculator.hxx
- Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.hxx
- Modules/Segmentation/LevelSets/include/itkSparseFieldLevelSetImageFilter.hxx
Avoided calling `GetSpacing()` repetitively in a `for` loop, by using a local `spacing` variable.
Cases found by the following regular expressions:
if \(m_UseImageSpacing\).+    for .+->GetSpacing\(\)\[
if \(this->GetUseImageSpacing\(\)\).+    for .+->GetSpacing\(\)\[
Aims to improve code readability.
> STYLE: Move `GetSpacing()` calls out of `for` loops

- Modules/Filtering/ImageGradient/include/itkGradientImageFilter.h
- Modules/Filtering/ImageGradient/include/itkGradientImageFilter.hxx
Following C++ Core Guidelines, ["Use `unique_ptr` or `shared_ptr` to avoid forgetting to `delete` objects created using `new`"](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-smart).
Defaulted the destructor of `GradientImageFilter`.
> STYLE: Use std::unique_ptr for GradientImageFilter::m_BoundaryCondition

- Modules/Filtering/ImageFeature/include/itkZeroCrossingImageFilter.hxx
- Modules/Filtering/ImageGradient/include/itkGradientImageFilter.hxx
- Modules/Filtering/ImageGradient/include/itkGradientMagnitudeImageFilter.hxx
Added a local variable, `neighborhoodSize`, to clarify that the size of the neighborhood is in these cases always simply 3^N for an N-dimensional image.
Following Scott Meyers, Effective Modern C++ (2014), "Use `constexpr` whenever possible" and C++ Core Guidelines, ["Use `constexpr` for values that can be computed at compile time"](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rconst-constexpr)
> STYLE: Declare local `radius`, `center` variables in Filtering constexpr

- Modules/Core/Common/include/itkConstShapedNeighborhoodIterator.h
- Modules/Core/Common/include/itkConstShapedNeighborhoodIterator.hxx
- Modules/Core/Common/itk-module.cmake
- Modules/Core/Common/test/itkShapedNeighborhoodIteratorTest.cxx
Allow interoperability of FlatStructuringElement and ShapedNeighborhoodIterator to allow compilation of the following code:
```cpp
using SE2Type = itk::FlatStructuringElement<2>;
SE2Type::RadiusType r2 = SE2Type::RadiusType::Filled(5);
SE2Type k2 = SE2Type::Ball(r2);
itk::ShapedNeighborhoodIterator<TImage> iterator(r2, image, image->GetBufferedRegion());
iterator.CreateActiveListFromNeighborhood(k2); // this now compiles
```
> ENH: FlatStructuringElement and ShapedNeighborhoodIterator Interop

- Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.h
- Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.hxx
Intensity values were cast to integers, thus making the computation imprecise.
Images below show centroids in red and weighted centroids in green.
Before this PR:
After this PR:
> BUG: Fix computation of weighted centroid in LabelGeometryImageFilter

- .gitattributes
nifti2_io.c was removed by:
- pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2630 commit 68221fdd30fb9ba89219a4bd5a47870b2d1cf7e6
"ENH: Prepare for update to NIFTILIB3.0.1", 9 July 2021
The two doxygen.config.in files were removed by:
- pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3311 commit a96d03fb5f4a4bb470516aa623dbc9b4aaaa6e4f
"COMP: Use modern doxygen_add_docs command ITK_WRAP_DOCS", 11 March 2022
- pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4500 commit 0c5c63890b2a417708b2fbcc4ebdb4e98247ef9f
"STYLE: Remove doxygen.config.in (superseded by DoxygenConfig.cmake)", 12 March 2024
> STYLE: No longer set `hooks-max-size` for nifti2_io.c, doxygen.config.in

- Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.h
Its docstring spills into the next method's doxygen docstring. The method itself lacked an implementation, commented out or otherwise.
> DOC: Remove commented-out `GetAllCounts` method declaration

- Modules/Core/Transform/include/itkAffineTransform.hxx
- Modules/Core/Transform/include/itkCenteredAffineTransform.hxx
- Modules/Core/Transform/include/itkCenteredEuler3DTransform.hxx
- Modules/Core/Transform/include/itkCenteredRigid2DTransform.hxx
- Modules/Core/Transform/include/itkCenteredSimilarity2DTransform.hxx
- Modules/Core/Transform/include/itkCompositeTransform.hxx
- Modules/Core/Transform/include/itkEuler2DTransform.hxx
- Modules/Core/Transform/include/itkMatrixOffsetTransformBase.hxx
- Modules/Core/Transform/include/itkRigid2DTransform.hxx
- Modules/Core/Transform/include/itkScalableAffineTransform.hxx
- Modules/Core/Transform/include/itkScaleTransform.hxx
- Modules/Core/Transform/include/itkSimilarity2DTransform.hxx
- Modules/Core/Transform/include/itkTransform.h
- Modules/Core/Transform/include/itkTranslationTransform.hxx
- Modules/Core/Transform/include/itkv3Rigid3DTransform.h
- Modules/Filtering/DisplacementField/include/itkConstantVelocityFieldTransform.hxx
- Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.hxx
- Modules/Filtering/DisplacementField/include/itkVelocityFieldTransform.hxx
- Added a static, protected helper function, `Transform::InvertTransform`
- Let derived `GetInverseTransform()` member functions just call `Transform::InvertTransform`
Aims to simplify the code, and reduce code duplication.
> Add helper function, `Transform::InvertTransform`, simplifying `GetInverseTransform()`

- Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx
- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
- Modules/IO/GDCM/test/CMakeLists.txt
- Modules/IO/GDCM/test/Input/image32bitsStoredTest.dcm.cid
- Modules/IO/GDCM/test/itkGDCMImageIO32bitsStoredTest.cxx
Fix crash in ITK DICOM reader when attempting to read an unusual but valid DICOM file, which has 32 bits allocated.
Fixes the error reported at https://discourse.slicer.org/t/slicer-crashes-while-trying-to-load-dicom-files/34931/3
> Fix 32bits dicom read crash

- Wrapping/Generators/Python/module_ext.i.in
We now only support Python 3.8+.
> COMP: Only support SWIG slice workaround for Python >= 3.2

- Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx
- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
To address:
```
/Users/builder/externalModules/IO/GDCM/src/itkGDCMImageIO.cxx:191:3: error: invalid use of 'this' outside of a non-static member function
itkDebugMacro(<< "No DICOM magic number found, but the file appears to be DICOM without a preamble.");
^
[CTest: warning matched] /Users/builder/externalModules/Core/Common/include/itkMacro.h:504:11: note: expanded from macro 'itkDebugMacro'
if (this->GetDebug() && ::itk::Object::GetGlobalWarningDisplay())        \
^
/Users/builder/externalModules/IO/GDCM/src/itkGDCMImageIO.cxx:191:3: error: invalid use of 'this' outside of a non-static member function
[CTest: warning matched] /Users/builder/externalModules/Core/Common/include/itkMacro.h:508:19: note: expanded from macro 'itkDebugMacro'
<< this->GetNameOfClass() << " (" << this << "): " …
```
> COMP: Remove use of itkDebugMacro in static method

- Modules/IO/Meta/src/itkMetaImageIO.cxx
- Modules/IO/Meta/test/itkMetaImageIOTest.cxx
The modality of a meta image is not stored as part of the metadata dictionary and was not copied into the ITK metadata dictionary. This change addresses the issue.
> BUG: Missing modality tag when reading meta-image format.

- Modules/Video/BridgeOpenCV/test/itkOpenCVImageBridgeRGBTest.cxx
Fix `ITK_TRY_EXPECT_NO_EXCEPTION` macro spelling in `itkOpenCVImageBridgeRGBTest.cxx`.
Fixes:
```
Error when building the ITK-5.4rc02:
C:\lib\ITK-5.4rc02\Modules\Video\BridgeOpenCV\test\itkOpenCVImageBridgeRGBTest.cxx(156,3):
error C3861: ITK_TRY_EXPECT_NO_EXCEPTIION
identifier not found
```
Fixes #4550.
> COMP: Fix macro spelling in `itkOpenCVImageBridgeRGBTest.cxx`

- Modules/Bridge/NumPy/include/itkPyBuffer.hxx
- Modules/Segmentation/SignedDistanceFunction/wrapping/itkPCAShapeSignedDistanceFunction.wrap
- Wrapping/Generators/Python/CMakeLists.txt
- Wrapping/Generators/Python/PyBase/CMakeLists.txt
- Wrapping/Generators/Python/PyBase/pyBase.i
- Wrapping/Generators/Python/PyUtils/itkPyImageFilter.hxx
- Wrapping/Generators/SwigInterface/CMakeLists.txt
- Wrapping/TypedefMacros.cmake
- Wrapping/macro_files/itk_end_wrap_module.cmake
- Supports more modern C++
- More Pythonic interfaces, e.g. Python Iterator Protocol
- Python Limited ABI
There were duplicate definition errors due to double inclusion of
%template(vectoritkImageXX, std::vector< itkImageXX >)
via itkImage_ext.i in PCAShapeSignedDistanceFunction. Remove
itkImage_ext.i from the latter but still provide the required typemaps
by adding DECL_PYTHON_STD_VEC_RAW_TO_SMARTPTR_TYPEMAP in
itkPCAShapeSignedDistanceFunction.wrap.
Remove -py3 because it is no longer supported (the default).
Remove "ios_base*" config templates because they are no longer emitted.
Bump PCRE. SWIG and PCRE are now built via CMake instead of autotools.
Closes https://github.com/InsightSoftwareConsortium/ITK/issues/4536
Closes https://github.com/InsightSoftwareConsortium/ITK/issues/3364 …
> ENH: Bump SWIG to 2024-03-26-master

- Modules/Filtering/Convolution/include/itkConvolutionImageFilterBase.h
- Modules/Filtering/Convolution/include/itkFFTConvolutionImageFilter.h
- Modules/Filtering/FFT/include/itkFFTPadImageFilter.h
- Modules/Filtering/ImageGrid/include/itkPadImageFilter.h
- Modules/Filtering/ImageGrid/include/itkPadImageFilterBase.h
- Modules/Filtering/ImageGrid/include/itkPadImageFilterBase.hxx
`BoundaryConditionPointerType` is just a type alias for  `BoundaryConditionType *`. It appears much clearer to directly use `BoundaryConditionType *`, to explicitly make clear when using a _raw_ pointer, rather than a _smart_ pointer.
>  `FUTURE_LEGACY_REMOVE` BoundaryConditionPointerType, replace with `BoundaryConditionType *`

- Modules/Core/Common/include/itkSparseFieldLayer.h
- Modules/Core/Common/include/itkSparseFieldLayer.hxx
Following C++ Core Guidelines, ["Use unique_ptr or shared_ptr to avoid forgetting to delete objects created using new"](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-smart)
Also defaulted the destructor of `SparseFieldLayer`.
> STYLE: Use (const) unique_ptr for `SparseFieldLayer::m_HeadNode`

- Modules/Core/ImageFunction/test/itkNeighborhoodOperatorImageFunctionTest.cxx
- Modules/Registration/Common/include/itkMultiResolutionPyramidImageFilter.hxx
- Modules/Registration/Common/include/itkRecursiveMultiResolutionPyramidImageFilter.hxx
- Modules/Registration/PDEDeformable/include/itkPDEDeformableRegistrationFilter.hxx
Following C++ Core Guidelines, ["Prefer scoped objects, don’t heap-allocate unnecessarily"](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r5-prefer-scoped-objects-dont-heap-allocate-unnecessarily)
> STYLE: Allocate local GaussianOperator objects (`oper`) on the stack

- Modules/Numerics/Optimizers/include/itkCumulativeGaussianCostFunction.h
- Modules/Numerics/Optimizers/src/itkCumulativeGaussianCostFunction.cxx
It appears unnecessary to manually manage the memory pointed to by its members, m_OriginalDataArray and m_MeasurePointer.
Defaulted its default-constructor and its destructor.
> STYLE: Do not declare CumulativeGaussianCostFunction data as pointer

- Modules/Numerics/FEM/src/itkFEMElement2DC0LinearTriangular.cxx
- Modules/Numerics/FEM/src/itkFEMElement2DC0QuadraticTriangular.cxx
- Modules/Numerics/FEM/src/itkFEMElement3DC0LinearTriangular.cxx
- Modules/Numerics/FEM/src/itkFEMElementBase.cxx
Note that the type of these local matrices is `MatrixType = vnl_matrix<Float>`, so such a matrix is just empty, when default-constructed.
Following C++ Core Guidelines, February 15, 2024, ["Prefer scoped objects, don’t heap-allocate unnecessarily"](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r5-prefer-scoped-objects-dont-heap-allocate-unnecessarily)
> STYLE: Put local matrix variables in FEM on the stack, remove new/delete

- Modules/IO/GIPL/include/itkGiplImageIO.h
- Modules/IO/GIPL/src/itkGiplImageIO.cxx
- Modules/IO/MINC/include/itkMINCImageIO.h
- Modules/IO/MINC/src/itkMINCImageIO.cxx
Both "pimpl-like" pointers were already `private` anyway.
- Following C++ Core Guidelines, ["Use unique_ptr or shared_ptr to avoid forgetting to delete objects created using new"](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-smart)
- Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4539
@thewtex This PR obviously does not affect the public API. It just aims to make the code more secure, by removing two more cases of manual memory management. Would it still be in time for ITK 5.4.0?
> Use unique_ptr for the "pimpl pointers" of GiplImageIO and MINCImageIO

- Utilities/KWStyle/BuildKWStyle.cmake
To address:
```
:
/home/matt/src/KWStyle/Utilities/boost/throw_exception.hpp:233:105: warning: predefined identifier is only valid inside function [-Wpredefined-identifier-outside-function]
template<class E> BOOST_NORETURN void throw_with_location( E && e, boost::source_location const & loc = BOOST_CURRENT_LOCATION )
^
/home/matt/src/KWStyle/Utilities/boost/assert/source_location.hpp:104:79: note: expanded from macro 'BOOST_CURRENT_LOCATION'
^
/home/matt/src/KWStyle/Utilities/boost/current_function.hpp:37:33: note: expanded from macro 'BOOST_CURRENT_FUNCTION'
```
> COMP: Bump KWStyle to silence boost predefined-identifier warning

- Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
The LowerToUpperOrder function is not part of the API, and is never used.
> STYLE: Remove unused function

- Examples/Filtering/test/CMakeLists.txt
Coordinate computations for nearest neighbor are computed at the limits of numerical precision for this image during resampling.  arm64 and x86_64 compute input continuous index coordinates as 105.39999999999999 vs 105.4 which requires a slight tolerance acceptance in the comparisons
Add --compareRadiusTolerance 1 to test validation.
https://open.cdash.org/tests/1506666894
> COMP: Numerical computation precision limit in resampling

- .github/workflows/macos-arm.yml
Also remove unused Python package installs.
> ENH: Add macOS ARM Python CI

- Modules/IO/GE/src/itkGE5ImageIO.cxx
The use of std::remove was not correctly implemented. After removing '-' from the string and shuffling items forward into the space, the remaining items
in the string need to be explicitly erased.
> BUG: Fix removal of '-' from patientId

- .github/workflows/apply-clang-format.yml
- .github/workflows/clang-format-linter.yml
- .github/workflows/spell-check-comments.yml
Fix format linter and spell check workflow actions warnings linked to `Node.js`: bump `actions/checkout` to `v4` and `actions/setup-python` to v5.
Fixes:
```
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20:
actions/checkout@v3, actions/setup-python@v4.
For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
https://github.com/InsightSoftwareConsortium/ITK/actions/runs/8655098674
> ENH: Fix workflow actions warnings linked to `Node.js`

- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorDeleteCenterVertexTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorJoinFacetTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorJoinVertexTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorSplitEdgeTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorSplitVertexTest.cxx
The result of GetNameOfClass() was ignored in the tests. The value is now checked to ensure that the correct values are used.
> TEST: Add test for correct value of GetNameOfClass()

- Modules/IO/ImageBase/test/itkImageIOBaseTest.cxx
Use c++17 features to enforce compile-time
sanity checks on array lengths.
> COMP: Simplify static array length checking

- Modules/IO/GDCM/test/Baseline/Lily.mha.cid
- Modules/IO/GDCM/test/Baseline/itkGDCMImageIOSecondaryCaptureSpacingTestBaseline.mha.cid
- Modules/IO/GDCM/test/CMakeLists.txt
- Modules/IO/GDCM/test/Input/image_slice0.dcm.cid
- Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageHelper.cxx
- ENH: Add more tests for DICOM Secondary Capture Spacing
- BUG: Check for Secondary Capture spacing following DICOM Part 3 Sect A.8.1.3
> secondary capture spacing

- Modules/Core/Common/include/itkMacro.h
- Modules/Filtering/DistanceMap/include/itkFastChamferDistanceImageFilter.hxx
- Modules/IO/Bruker/src/itkBruker2dseqImageIO.cxx
- Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
[[fallthrough]](C++17)	indicates that the fall through from the previous case label is intentional and should not be diagnosed by a compiler that warns on fall-through (attribute specifier)
Remove complicated #ifdef macro logic to enforce compiler specific behaviors.
> COMP: Use the c++ 17 common [[fallthrough]] attribute

- Modules/Core/Transform/include/itkCompositeTransform.h
Re-wrote the example code to avoid assumptions about the gender of the developer using the documentation.
> STYLE: Use gender-neutral language for example documentation

- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorDeleteCenterVertexTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorJoinFacetTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorJoinVertexTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorSplitEdgeTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorSplitVertexTest.cxx
Prefer using `ITK_TEST_EXPECT_EQUAL` to compare class names in `QuadEdgeMesh` tests.
-
> STYLE: Use `ITK_TEST_EXPECT_EQUAL` to compare class names in QEMesh

- .github/workflows/macos-arm.yml
Fix macOS ARM workflow actions warnings linked to `Node.js`: bump `actions/setup-python` to v5.
Fixes:
```
Node.js 16 actions are deprecated.
Please update the following actions to use Node.js 20:
actions/setup-python@v4.
For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
https://github.com/InsightSoftwareConsortium/ITK/actions/runs/8676305102
> ENH: Fix macOS ARM workflow actions warnings linked to `Node.js`

- Modules/Core/Transform/wrapping/test/itkTransformSerializationTest.py
- Wrapping/Generators/Python/itk/support/extras.py
This is to be more consistent with `pixelType`, etc. for Image, Mesh,
PolyData representations.
> STYLE: Use transformType in transform dict representation

- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorDeleteCenterVertexTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorJoinFacetTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorJoinVertexTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorSplitEdgeTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorSplitVertexTest.cxx
Prevented potential static analysis warnings, like Clang-Tidy:
> C-style casts are discouraged; use static_cast [google-readability-casting]
And JetBrains ReSharper:
> C-style cast is used instead of a C++ cast
Note that `std::string_view` is more lightweight than `std::string`.
- Follow-up to pull request #4583
> STYLE: Replace `(const std::string)` casts with C++17 `std::string_view`

- Documentation/docs/releases/4.11.md
- Modules/Core/Common/test/itkImageTest.cxx
> STYLE: Spelling Trasform->Transform fixes.

- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
This has not been released in GDCM, yet. Avoid build errors for a system
GDCM. There will be a difference in behavior, which will be flagged with
failing tests.
Co-authored-by: Mihail Isakov <mihail.isakov@gmail.com>
> COMP: Add GDCM system version check for SetSecondaryCaptureImagePlaneModule

- .github/workflows/macos-arm.yml
It intermittedly passes / fails.
> COMP: Exclude itkPyBufferMemoryLeak test from macOS ARM CI

- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
Follow up https://github.com/InsightSoftwareConsortium/ITK/pull/4601
GDCM master branch is currently at version **3.1.0**.
Updated check to include versions 3.1+.
P.S.
Maybe GDCM will change its approach in the future and not insist on `SecondaryCaptureImagePlaneModule=true` for _reading_ at all.  ImagePlaneModule for SC is a part of the standard now. But it is still there. The variable could be useful for _writing_ in the future.
> COMP: Update GDCM system version check for SetSecondaryCaptureImagePlaneModule

- Modules/Core/SpatialObjects/include/itkSpatialObjectProperty.h
The dictionary used by SpatialObjectProperties is queried using functions that return the dictionary value in a variable that is passed by reference: https://itk.org/Doxygen/html/classitk_1_1SpatialObjectProperty.html#aff2b1c659a8e77bdb6afeef0bab037fb
bool itk::SpatialObjectProperty::GetTagScalarValue ( const std::string & tag, double & value ) const
This function is not correctly wrapped by SWIG, and cannot be used from within python.
Here is a snippet of code that demonstrates the issue:
In [1]: import itk
In [2]: so = itk.TubeSpatialObject[3].New()
In [3]: so.GetProperty().SetTagScalarValue("foo",1) In [4]: ret = 0.0
In [5]: so.GetProperty().GetTagScalarValue("foo",ret)
---------------------------------------------------------------------------
TypeError …
> BUG: Fix SpatialObjectProperties.GetTag*Value() to return values in python

- Utilities/Maintenance/AuthorsChangesSince.py
Versions can be available in the *.remote.cmake files of the form:
GIT_TAG abc123
and
GIT_TAG
abc123)
in the history. Support both.
> BUG: AuthorsChangesSince.py support both single and multiline

- Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.h
This filter is buggy, and sometimes produces wrong results. Follow-up to: #4530.
> DOC: Add See Also entries for alternatives to LabelGeometryImageFilter

- .clang-format
- Modules/Core/Common/include/itkExtractImageFilter.hxx
- Modules/Core/Common/include/itkMacro.h
- Modules/Core/Common/include/itkMultiThreaderBase.h
- Modules/Core/Common/include/itkNeighborhood.h
- Modules/Core/Common/include/itkNeighborhoodOperator.h
- Modules/Core/Common/test/itkShapedImageNeighborhoodRangeGTest.cxx
- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorSplitEdgeTest.cxx
- Modules/Filtering/ImageFusion/include/itkLabelMapContourOverlayImageFilter.hxx
- Modules/Filtering/ImageIntensity/include/itkSymmetricEigenAnalysisImageFilter.h
##
Fixes for 100's of warnings presented by the gcc 13.2 compiler under the upcoming Ubuntu 24.04  LTS release.
This does not fix all of the issues, but is for comparison against the master branch build 
https://open.cdash.org/builds/9565813
Related to issue #4607 
These new compiler warnings are due to increased default security settings in Ubuntu 24.04.
https://ubuntu.com/blog/whats-new-in-security-for-ubuntu-24-04-lts#:~:text=Overall%2C%20the%20vast%20range%20of,most%20secure%20release%20to%20date.
> COMP:  Ubuntu2404 fixes issue 4607

- Examples/Filtering/DiffusionTensor3DReconstructionImageFilter.cxx
Suppress `-Wformat-nonliteral` warning in diffusion tensor reconstruction image filter example.
Fixes:
```
/Users/builder/externalExamples/Filtering/DiffusionTensor3DReconstructionImageFilter.cxx:254:46:
warning: format string is not a string literal [-Wformat-nonliteral]
snprintf(filename, sizeof(filename), fn.c_str(), referenceImageIndex);
^~~~~~~~~~
/Users/builder/externalExamples/Filtering/DiffusionTensor3DReconstructionImageFilter.cxx:260:46:
warning: format string is not a string literal [-Wformat-nonliteral]
snprintf(filename, sizeof(filename), fn.c_str(), i);
^~~~~~~~~~
[CTest: warning suppressed] 2 warnings generated.
```
https://open.cdash.org/viewBuildError.php?type=1&onlydeltap&buildid=9582771
Left behind …
> COMP: Suppress `-Wformat-nonliteral` warning in diff tensor example

- Modules/Core/Common/include/itkRegion.h
Use the compiler-proved default implementations for `itk::Region` copy constructor, copy assignment, move constructor, and move assignment functions.
As noted in [1], the C++ standard deprecated the implicit generation of copy and assignment operators.
Fixes:
```
[CTest: warning matched] /Users/builder/externalModules/Core/Common/include/itkRegion.h:91:11:
warning: definition of implicit copy assignment operator for 'Region' is deprecated because it has a user-declared destructor [-Wdeprecated]
virtual ~Region() = default;
^
[CTest: warning matched] /Users/builder/externalModules/Core/Common/include/itkImageIORegion.h:117:30:
note: in implicit copy assignment operator for 'itk::Region' first required here
operator=(Self &&) = default;
^ …
```
> COMP: Use default copy and move construct and assign in `itk::Region`

- Modules/Core/Common/include/itkRealTimeStamp.h
Use the compiler-proved default implementations for `itk::RealTimeStamp` copy constructor, copy assignment, move constructor, and move assignment functions.
As noted in [1], the C++ standard deprecated the implicit generation of copy and assignment operators.
Fixes:
```
[CTest: warning matched] /Users/builder/externalModules/Core/Common/include/itkRealTimeStamp.h:56:3:
warning: definition of implicit copy assignment operator for 'RealTimeStamp' is deprecated because it has a user-declared destructor [-Wdeprecated]
~RealTimeStamp();
^
[CTest: warning matched] /Users/builder/externalModules/Core/Common/include/itkDataObject.h:452:3:
note: in implicit copy assignment operator for 'itk::RealTimeStamp' first required here
itkSetMacro(RealTimeStamp, RealTimeStamp);
^ …
```
> COMP: Use default copy, move for construc, assign `RealTimeStamp`

- Modules/Core/Common/include/itkPrintHelper.h
Addresses:
```
FAILED: Wrapping/castxml_inputs/itkImageSource.xml /home/matt/bin/ITK-Wrap-Release/Wrapping/castxml_inputs/itkImageSource.xml
cd /home/matt/bin/ITK-Wrap-Release/Wrapping/Modules/ITKCommon && /home/matt/bin/ITK-Wrap-Release/Wrapping/Generators/CastXML/castxml/bin/castxml -o /home/matt/bin/ITK-Wrap-Release/Wrapping/castxml_inputs/itkImageSource.xml --castxml-gccxml --castxml-start _wrapping_ --castxml-cc-gnu "(" /usr/bin/c++ -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -Wno-strict-overflow -Wno-deprecated -Wno-invalid-offsetof -Woverloaded-virtual -Wctad-maybe-unsupported -Wstrict-null-sentinel -fno-sized-deallocation -msse2 -fno-sized-deallocation -msse2 -std=c++17 ")" -w …
```
> COMP: GCC 13 CastXML vector include workaround

- Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.h
The LabelGeometryImageFilter has known computational inefficiencies and bugs such as some attributes are not computed with respect to image geometry.
This class is currently in the Review module and is planned to be moved to the Compatibility group under the Deprecated module.
> BUG: Mark LabelGeometryImageFilter as deprecated

- Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.h
- Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx
- Modules/Core/SpatialObjects/test/CMakeLists.txt
- Modules/Core/SpatialObjects/test/itkImageMaskSpatialObjectTest5.cxx
Nominally an ImageMaskSpatialObject considers any non-zero pixel to indicate that the object is present at that point.
With this change, it is possible to specify a MaskValue and to enable the use of that MaskValue (via the UseMaskValue functions) so that a specific pixel value is needed to indicate the presence of that object.
This is particularly useful when a single mask image defines multiple
objects via different values.   That single image can be assigned
to multiple ImageMaskSpatialObjects, each using a different MaskValue.  This reduces memory requirements, etc.
A new set of tests were added to confirm proper function.
Default behaviour is unchanged.
> ENH: Optionally limit an ImageMask to a specific pixel value

- Modules/IO/NIFTI/include/itkNiftiImageIO.h
- Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
- Modules/IO/NIFTI/test/CMakeLists.txt
- Modules/IO/NIFTI/test/Input/xyzt_units_test_scl.nii.gz.cid
- Modules/IO/NIFTI/test/Input/xyzt_units_test_scl_mm_s.nii.gz.cid
- Modules/IO/NIFTI/test/itkNiftiImageIOTest14.cxx
Previously, the correct xyzt code was assigned to the 'xyz_units' variable, but time gets masked out because it's only for space units, resulting in xyzt_units=2.
Fix by setting 'time_units' to NIFTI_UNITS_SEC.
This produces images with xyzt_units == 10, which is correct for ITK output (NIFTI_UNITS_MM | NIFTI_UNITS_SEC)
- [*] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [*] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [*] Added test (or behavior not changed)
- [*] Updated API documentation (or API not changed)
- [*] Added …
> BUG: Set NIFTI header xyzt_units field correctly in output

- Modules/Core/Transform/wrapping/test/itkTransformSerializationTest.py
- Wrapping/Generators/Python/PyBase/pyBase.i
- Wrapping/Generators/Python/Tests/extras.py
- Wrapping/Generators/Python/itk/support/extras.py
Encapsulate the "transformParameterization", "parametersValueType",
"inputDimension", "outputDimension", which are static, into a
"transformType" member, similar to "imageType", "meshType" for Images,
Meshes. "transformParameterization" is the string name of the ITK transform
class, less the trailing "Transform".
Example serialization:
```py
{
'transformType': {'transformParameterization': 'Translation', 'parametersValueType': 'float64', 'inputDimension': 3, 'outputDimension': 3},
'name': '',
'inputSpaceName': '',
'outputSpaceName': '',
'parameters': array([3., 2., 8.]),
'fixedParameters': array([], dtype=float64),
'numberOfParameters': 3,
'numberOfFixedParameters': 0
}
```
```py
[
{
'transformType': {'transformParameterization': 'Translation', 'parametersValueType': 'float64', …
```
> BUG: Make dict_from_transform more consistent with other dict representations

- Modules/Bridge/NumPy/wrapping/PyBuffer.i.in
- Wrapping/Generators/Python/Tests/extras.py
- Wrapping/Generators/Python/itk/support/extras.py
Optional specification of the BufferedRegion, which is a subset of the
LargestPossibleRegion. Addresses #4267.
The LargestPossibleRegion's Index is assumed to be trivial (zeros).
Also update the NumPy bridge to correctly use the BufferedRegion instead
of the LargestPossibleRegion for the array shape.
> BUG: Add bufferedRegion to dict_from_image representation

- Modules/IO/ImageBase/include/itkImageFileReaderException.h
- Modules/IO/ImageBase/include/itkImageFileWriter.h
- Modules/IO/MeshBase/include/itkMeshFileReaderException.h
- Modules/IO/MeshBase/include/itkMeshFileWriterException.h
Fix implicit copy constructor definition deprecation warnings in image/mesh file reader exception classes by using explicitly the compiler-provided default implementation (together with the assignment
assignment and move semantics).
Fixes:
```
/Users/builder/externalModules/IO/ImageBase/include/itkImageFileReaderException.h:54:3:
warning: definition of implicit copy constructor for 'ImageFileReaderException' is deprecated because it has a user-declared destructor [-Wdeprecated]
~ImageFileReaderException() noexcept override;
^
```
and
```
/Users/builder/externalModules/IO/ImageBase/include/itkImageFileWriter.h:57:3:
warning: definition of implicit copy constructor for 'ImageFileWriterException' is deprecated because it has a user-declared …
```
> COMP: Fix implicit copy constructor definition deprecation warnings

- Wrapping/Generators/Python/Tests/extras.py
- Wrapping/Generators/Python/itk/support/extras.py
This is a common use case. Without this patch, a segfault results.
> BUG: Support passing a single transform to transform write

- Modules/IO/NIFTI/test/itkNiftiImageIOTest14.cxx
Fixes a test failure introduced by #4595 
@jhlegarreta, this works on my machine, but then so did the previous test. According to the error message here
https://open.cdash.org/tests/1540861560
```
** ERROR (nifti_image_write_engine): cannot open output file '/a_blatantly_obvious/bad_file_path/that/should/never/exist/on/the/computer/xyzt_units_output_check.nii'
Correctly caught exception for attempting to write to an invalid file.
Caught an exception: 
itk::ImageFileReaderException (0x6000037a4620)
Location: "unknown" 
File: /Users/runner/work/ITK/ITK/Modules/IO/ImageBase/include/itkImageFileReader.hxx
Line: 135
Description:  Could not create IO object for reading file xyzt_units_output_check.nii
The file doesn't exist. 
Filename = xyzt_units_output_check.nii …
```
> BUG: Fix path to write itkNiftiImageIOTest14 data

- Modules/Bridge/NumPy/wrapping/PyBuffer.i.in
- Modules/Bridge/NumPy/wrapping/test/itkPyBufferTest.py
- Wrapping/Generators/Python/PyBase/pyBase.i
A VectorImage with one component should have a shape with a value of 1
for the component. Also make the ndim consistent.
Closes #4646
> BUG: array_from_image shape for VectorImage with 1 component

- Modules/Core/Common/include/itkMacro.h
Brought back #define CLANG_SUPPRESS_Wfloat_equal for compatibility with third party code using this as public API.
While here, also prefixed some other defines with ITK to indicate they are from ITK.
> COMP: restored old spelling of CLANG_SUPPRESS_Wfloat_equal

- Modules/IO/NIFTI/test/CMakeLists.txt
- Modules/IO/NIFTI/test/itkNiftiImageIOTest.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest.h
- Modules/IO/NIFTI/test/itkNiftiImageIOTest14.cxx
When the tests are run in parallel they can try to write to or remove
the same file from different processes, causing intermittent failures.
Also add `const` where it is missing.
Also use full paths as tests inputs, instead of changing directories,
which is more explicit.
> BUG: Use unique filenames for Nifti tests

- Modules/Core/Common/include/itkVector.h
- Modules/Core/Common/include/itkVector.hxx
- Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.hxx
Fix compiler warnings issues with python building turned on.
> COMP: Gcc13.2 compiler warnings

- .github/workflows/itk_dict.txt
- Modules/Core/Common/include/itkMacro.h
- Modules/Core/Common/include/itkRealTimeStamp.h
- Modules/Core/Common/include/itkRegion.h
- Modules/IO/ImageBase/include/itkImageFileReaderException.h
- Modules/IO/ImageBase/include/itkImageFileWriter.h
- Modules/IO/MeshBase/include/itkMeshFileReaderException.h
- Modules/IO/MeshBase/include/itkMeshFileWriterException.h
Aims to address issue #4645 "Defaulting copy constructor, copy assignment, move constructor, and move
assignment functions", reported by Jon Haitz Legarreta Gorroño (@jhlegarreta).
> Add `ITK_DEFAULT_COPY_AND_MOVE` and replace "manually" defaulted copy and move member function declarations

- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshEulerOperatorSplitEdgeTest.cxx
- Modules/IO/JPEG/src/itkJPEGImageIO.cxx
- Modules/Numerics/Optimizersv4/test/itkObjectToObjectMetricBaseTest.cxx
Fixed the following warnings
-Wimplicit-fallthrough
-Wzero-as-null-pointer-constant
-Wdeprecated-dynamic-exception-spec
> COMP: Fixed Cpp Warnings

- Modules/Core/Common/include/itkCommonEnums.h
- Modules/Filtering/ImageIntensity/include/itkArithmeticOpsFunctors.h
- Modules/Filtering/ImageIntensity/include/itkDivideOrZeroOutImageFilter.h
- Modules/IO/GDCM/include/itkGDCMImageIO.h
- Modules/Numerics/Statistics/include/itkMeasurementVectorTraits.h
Remove \brief without something after
> COMP: Remove \brief with nothing after

- Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h
- Modules/Core/Transform/include/itkBSplineDeformableTransform.hxx
C++17 allows using a static constexpr member variable like `SupportSize`, without being "redeclared". The workaround of copying `SupportSize` into a local variable is no longer necessary.
Reverts pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2742 commit 27e4815bb816c2cebe3abd0b9aca85afda8101c6
"COMP: Copy BSplineInterpolationWeightFunction::SupportSize within lambda"
> STYLE: Revert C++14 workaround when using the constexpr `SupportSize`

- Modules/Core/Common/test/itkSmartPointerGTest.cxx
- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshFrontIterator.h
This is to fix Wzero-as-null-pointer-constant warnings by either warning suppression or nullptr usage
> COMP: Fix zero as null pointer constant

- Modules/ThirdParty/Eigen3/src/itk_eigen.h.in
These 4 warnings occur nowhere else in the ITK codebase, so suppressing them here allows them to be enabled on CI.
> COMP: suppress 5 clang warnings from eigen headers

- Modules/Core/Common/include/itkIndex.h
- Modules/Core/Common/include/itkOffset.h
- Modules/Core/Common/include/itkSize.h
- Modules/Core/Common/test/itkIndexGTest.cxx
- Modules/Core/Common/test/itkOffsetGTest.cxx
- Modules/Core/Common/test/itkRangeGTestUtilities.h
- Modules/Core/Common/test/itkSizeGTest.cxx
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3236 commit 47bce264791a53853020a3911dd94d060cfbd655
"ENH: Declare begin(), end() of FixedArray, Index, Offset, Size constexpr"
> ENH: Declare `front()` and `back()` of Index, Offset, and Size constexpr

- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
The original code requested `gdcm::DataSet` to search for one and the same data element three times in a row, by calling both FindDataElement and GetDataElement for the very same tag. With this commit, the search is only performed once.
Issue found by Mihail Isakov (@issakomi):
https://github.com/InsightSoftwareConsortium/ITK/pull/4636#discussion_r1593789757
----
For the record, the redundant searches appear introduced with commit 168c457e840c3ca9e7c0b6d4df4a25252a5ddc7a, June 5, 2014: https://github.com/InsightSoftwareConsortium/ITK/blob/168c457e840c3ca9e7c0b6d4df4a25252a5ddc7a/Modules/IO/GDCM/src/itkGDCMImageIO.cxx#L384-L387
> PERF: Avoid redundant searches for a data element in a `gdcm::DataSet`

- Modules/Core/Common/include/itkIntTypes.h
Officially, we may not assume that `ptrdiff_t` and `size_t` are defined in the global namespace.
----
Motivation: Both `ptrdiff_t` and `size_t` are already commonly being used inside the `itk` namespace, without specifying their `std` namespace:
https://github.com/InsightSoftwareConsortium/ITK/blob/487da6d086b341808147c71e8dd1eb1f57371ea6/Modules/IO/ImageBase/include/itkConvertPixelBuffer.h#L64
https://github.com/InsightSoftwareConsortium/ITK/blob/487da6d086b341808147c71e8dd1eb1f57371ea6/Modules/Video/IO/src/itkFileListVideoIO.cxx#L64
It just compiles, so far! However, compilers may become more picky, as those types are not guaranteed to remain available in the global namespace.
> COMP: Add type aliases of ptrdiff_t and size_t to the `itk` namespace

- Modules/Core/Common/include/itkObject.h
- Modules/Core/Common/src/itkObject.cxx
- Modules/Filtering/ImageGrid/test/itkBasicArchitectureTest.cxx
Exposes a const version of `RemoveObserver() API` just like the already existing `AddObserver()` API [here](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/src/itkObject.cxx#L467) . 
Helps with application architecture when building observer design pattern with itkObject as subject.
@mentions: @thewtex - I apologize for mentioning you without any sort of prior discussion. I'm a new contributor, and would be very grateful for some feedback on this PR!
Thanks for reviewing this change!
> ENH: allow calling RemoveObserver() from a const itkObject

- Modules/Filtering/ImageStatistics/test/itkLabelStatisticsImageFilterTest.cxx
- Modules/Registration/Metricsv4/include/itkANTSNeighborhoodCorrelationImageToImageMetricv4GetValueAndDerivativeThreader.hxx
- Modules/Registration/Metricsv4/include/itkJointHistogramMutualInformationComputeJointPDFThreaderBase.hxx
- Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.hxx
This is to fix the -Wconditional-uninitialized warning from clang. The compiler produces this warning in the following scenarios.
1. Variable is declared. Used inside a try clause and processed after the try/catch clause.
2. Variable is declared and used inside a if statement
For scenario 1, for itkANTSNeighborhoodCorrelationImageToImageMetricv4GetValueAndDerivativeThreader.hxxTo, the compiler complains about movingImageValue. This variable is declared and used inside the try clause. After the try clause, it is used. The compiler doesn't seem to catch that it is used in the try clause. To fix scenario 1, the code after the try/catch clause is brought inside the try statement. The two blocks depend on pointIsValid which is used inside the if statements. Hence, everything is found inside …
> COMP: Fix Unitialized scenarios

- .clang-format
- Modules/Core/Common/include/itkMath.h
This is to see if the following changes regarding the -Wextra-semi (semi = semicolon) warning of clang can be done throughout the repository.
This is for a macro that is not function-like. It should not contain a semicolon. It is a method that is declared and defined in a header so no semi colon is needed.
Are these following changes accepted to proceed with the other cases in the repository?
> COMP: Fix -Wextra-semi Warnings for Macro

- Modules/Core/Common/include/itkImageRegion.h
- Modules/Core/Common/test/itkImageRegionGTest.cxx
Replaced `ITK_FUTURE_LEGACY_REMOVE` with `ITK_LEGACY_REMOVE`, regarding its inheritance from `itk::Region`.
A run-time performance improvement of more than 25% on default-constructing and destructing a sequence of `ImageRegion` objects was observed.
- Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4344 commit 1f3bbb658698556ff0d437c4effb9c1e42acc7c2
> PERF: Make `ImageRegion` trivially copyable (LEGACY_REMOVE)

- Documentation/docs/migration_guides/index.md
- Documentation/docs/migration_guides/itk_6_migration_guide.md
This document provides information for developers on how to migrate from
ITK 5 to ITK 6. It contains information on what backwards-incompatible
changes were made, such as the removal of deprecated code, why they made,
and how to migrate old code no the new code.
Developers making backwards-incompatible changes for ITK 6 should add
entries to this document as the changes are made.
The ITK 6 migration guide is similar to the ITK 5 migration guide with the
following modifications:
- The current and previous migration guide are now developed on GitHub
and published to the ITK Sphinx Documentation.
- We now have the consistent and simpler ITK_LEGACY_REMOVE and
ITK_FUTURE_LEGACY_REMOVE options without the additional
*_COMPATIBILITY option.
- We have "most" instead of "all" ITK_LEGACY_REMOVE, …
> DOC: Start ITK 6 migration guide

- Modules/Core/Common/include/itkHexahedronCell.h
- Modules/Core/Common/include/itkIsNumber.h
- Modules/Core/Common/include/itkLineCell.h
- Modules/Core/Common/include/itkMetaProgrammingLibrary.h
- Modules/Core/Common/include/itkPolyLineCell.h
- Modules/Core/Common/include/itkPolygonCell.h
- Modules/Core/Common/include/itkPromoteType.h
- Modules/Core/Common/include/itkQuadraticEdgeCell.h
- Modules/Core/Common/include/itkQuadraticTriangleCell.h
- Modules/Core/Common/include/itkQuadrilateralCell.h
- Modules/Core/Common/include/itkTetrahedronCell.h
- Modules/Core/Common/include/itkVariableLengthVector.h
- Modules/Core/Common/include/itkVertexCell.h
- Modules/Core/Common/src/itkOctreeNode.cxx
Contains the following fixes
- Remove parameters in documentation that are not in the class
- Remove \return when no return statement
- Remove \param when no parameter
- Fix small typo
> WparamReturn

- Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h
- Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.hxx
- Modules/Core/Common/include/itkIndexRange.h
- Modules/Core/Common/test/itkIndexRangeGTest.cxx
- Added constexpr to many IndexRange functions
- Estimated the OffsetToIndexTable of BSplineInterpolationWeightFunction at compile-time
> Add constexpr to IndexRange, and let BSplineInterpolationWeightFunction make use of it

- CMake/itkVersion.cmake
Following the process outlined in the Release documentation.
Clarify for developers and for users that they are working with the
in-progress ITK 6 development code.
> ENH: Bump ITK's CMake version to 6.0.0

- Modules/Core/Common/include/itkDynamicLoader.h
- Modules/Core/Common/include/itkSmapsFileParser.h
COMP: Replaced comments above what they describe
> COMP: Replaced comments above what they describe

- Documentation/Maintenance/Release.md
Add more details to Archive ExternalData section
- [NA] Added test (or behavior not changed)
- [NA] Updated API documentation (or API not changed)
- [NA] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [NA] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [NA] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)
> DOC: Update Release.md

- Modules/Numerics/Statistics/include/itkSubsample.h
I tested with AppleClang 10, the oldest AppleClang submitting to cdash, and this false positive seems to have been fixed long ago.
> COMP: remove suppression of -Winconsistent-missing-override

- Modules/Filtering/LabelMap/ITKKWStyleOverwrite.txt
- Modules/Filtering/LabelMap/include/itkAttributeUniqueLabelMapFilter.hxx
- Modules/Filtering/LabelMap/include/itkShapeUniqueLabelMapFilter.h
- Modules/Filtering/LabelMap/test/CMakeLists.txt
- Modules/Filtering/LabelMap/test/itkStatisticsUniqueLabelMapFilterTest1.cxx
- Modules/Filtering/LabelMap/test/itkUniqueLabelMapFiltersGTest.cxx
Address bugs in unique label map filters
Two bugs were addressed which could cause overlapping and/or errouneous
outputs.
1. When a line we trimmed in the front, it is not placed back into the
queue to ensure that it is still the first one, and the asserted
assumptions of the order remain true.
2. Fix comparisons between start and ends to be correct for an
interval of pixels where the start+length is not included.
closes #4655 
closes #3031
> Fix Unique LabelMap filters producing non-unique labels and causing concurrent pixel writes.

- Modules/Registration/Metricsv4/test/itkJointHistogramMutualInformationImageToImageRegistrationTest.cxx
- Modules/Registration/Metricsv4/test/itkMeanSquaresImageToImageMetricv4RegistrationTest.cxx
- Modules/Registration/Metricsv4/test/itkMeanSquaresImageToImageMetricv4VectorRegistrationTest.cxx
- Modules/Registration/Metricsv4/test/itkMultiGradientImageToImageMetricv4RegistrationTest.cxx
This is a comment to fix the -Wunreachable-code warning generated by clang.
This fix simply removes if (false) clauses. An investigation was done to see why these clause exist. This change was done 10 years ago. The clauses at that time were if(0).
> COMP: Fix ununsed code ( if(false) )

- Modules/IO/ImageBase/test/itkWriteImageFunctionGTest.cxx
Addresses creation of test1.mha file in wrong place.
Fix the variable name and the preprocessor stringification.
> BUG: fix output path for WriteImage test

- Examples/RegistrationITKv4/DeformableRegistration17.cxx
- Modules/Core/Common/test/itkMultithreadingTest.cxx
- Modules/Core/TestKernel/src/itkTestDriverInclude.cxx
- Modules/Filtering/Path/test/itkContourExtractor2DImageFilterTest.cxx
- Modules/Numerics/Optimizers/test/itkParticleSwarmOptimizerTest.cxx
- Modules/Numerics/Optimizersv4/test/itkPowellOptimizerv4Test.cxx
- Modules/Numerics/Statistics/test/itkWeightedCovarianceSampleFilterTest.cxx
- Modules/Numerics/Statistics/test/itkWeightedCovarianceSampleFilterTest2.cxx
- Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx
COMP: Fix missing declarations of unused variables.
This is to fix the -Wmissing-variable-declarations warning of clang.
This is simply related that the variable in question is not used in the file
---------------------------------------------------------------------------
COMP: Fix missing variables declaration (static)
This is a fix about -Wmissing-variable-declarations warning of clang
This is about the static case. A lot of variables were marked as warning due to non declaration. The static keyword was added when it makes sense that the variable is used internally.
> Wmissing variable declaration

- .github/workflows/macos-arm.yml
- Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml
Added to the macOS, Linux Python CI builds.
Re: #4700
> COMP: Test NumPy pre-releases (NumPy 2.0 RC) in CI

- Modules/Video/Core/test/itkTemporalProcessObjectTest.cxx
Simple variable name change for style.
> STYLE: Change variable name to meet ITK style.

- .github/workflows/itk_dict.txt
Add a commonly used word to dictionary "natively"
> ENH: Add missing spelling word.

- Documentation/docs/releases/5.1.md
- Documentation/docs/scientific_ecosystem/itk_ecosystem.md
- Modules/Core/Common/include/itkMacro.h
- Modules/Remote/Deprecated/NeuralNetworks.remote.cmake
- Utilities/ITKv5Preparation/CheckForOutdatedDefines.sh
The ITK_MACROEND_NOOP_STATEMENT is always supported in compilers, 
and allows macros to be used with
semi-colons without warnings or clang-format
inconsistencies.
related to #4699 
NOTE: Does require ';' at the end of ITK macros when used.  This greatly simplifies meeting the clang-format desired formatting behaviors in the code base.
> ENH: Default to allow ITK_MACROEND_NOOP_STATEMENT

- Modules/Core/Common/CMake/itkCheckHasFenvtStructMember.cxx
`[[maybe_unused]]` may not need to used in this case.
----
Using `static_assert`, as I suggested before at https://github.com/InsightSoftwareConsortium/ITK/pull/4581#discussion_r1565667280
@hjmjohnson What do you think?
> STYLE: Use `static_assert` to check `fenv_t` members

- Wrapping/macro_files/itk_end_wrap_module.cmake
If initially configured with python >= 3.11 before selecting a python version <3.11 as the python environment, then the state of the ITK_USE_PYTHON_LIMITED_API was incorrectly cached to retain the compiler settings desired for building with the original 3.11 python version.
Py_buffer is only included as part of the limited
Python API in 3.11 or greater versions.
Compilation would fail due to building with
-DPy_LIMITED_API to restrict the Python interfaces available.
> COMP: Fix python wrapping build state to match python version

- Modules/Core/Common/include/itkConstNeighborhoodIteratorWithOnlyIndex.h
- Modules/Core/Common/include/itkConstNeighborhoodIteratorWithOnlyIndex.hxx
- Modules/Core/Common/include/itkImageConstIteratorWithOnlyIndex.h
- Modules/Core/Common/include/itkImageConstIteratorWithOnlyIndex.hxx
- Modules/Core/Common/include/itkImageIterator.h
- Modules/Core/Common/include/itkImageIterator.hxx
- Modules/Core/Common/include/itkImageIteratorWithIndex.h
- Modules/Core/Common/include/itkImageIteratorWithIndex.hxx
Replaced hand-written copy-constructors and assignment operators of four iterators with the equivalent `ITK_DEFAULT_COPY_AND_MOVE` macro calls.
----
- Follow-up to pull request #4652
> Default copy and move of iterators, using `ITK_DEFAULT_COPY_AND_MOVE`

- Modules/Core/Common/include/itkProcessObject.h
- Modules/Filtering/DistanceMap/include/itkDanielssonDistanceMapImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkSignedDanielssonDistanceMapImageFilter.hxx
- Modules/Numerics/Eigen/include/itkEigenAnalysis2DImageFilter.hxx
- Modules/Numerics/Statistics/include/itkCovarianceSampleFilter.h
- Modules/Numerics/Statistics/include/itkCovarianceSampleFilter.hxx
- Modules/Numerics/Statistics/include/itkStandardDeviationPerComponentSampleFilter.h
- Modules/Numerics/Statistics/include/itkStandardDeviationPerComponentSampleFilter.hxx
- Modules/Registration/Common/include/itkBlockMatchingImageFilter.h
- Modules/Registration/Common/include/itkBlockMatchingImageFilter.hxx
- Modules/Segmentation/Watersheds/include/itkWatershedSegmenter.hxx
- Intended to supersede pull request #4687
> Add and use `ProcessObject::MakeRequiredOutputs`

- Modules/Core/Common/include/itkArray2D.h
- Modules/Core/Common/test/itkArray2DGTest.cxx
Added a `noexcept` move-constructor and move-assignment operator to `Array2D`, which both _move_ the data of the `Array2D`.
Previously, an attempt to "move" an `Array2D` would have done an expensive copy.
> PERF: Add fast `noexcept` "move semantics" to `Array2D`

- itk_common.cmake
Combined single failure mode makes it difficult
to identify where the failure occurs.
Separate the failure conditions in messaging.
> ENH: Present mode of failure for diagnostic

- Modules/Core/Common/include/itkImage.h
- Modules/Core/Common/include/itkVector.h
- Modules/Core/Common/include/itkVectorImage.h
- Modules/Core/ImageAdaptors/include/itkImageAdaptor.h
- Modules/Core/Transform/include/itkMatrixOffsetTransformBase.h
- Modules/Filtering/ImageFilterBase/include/itkCastImageFilter.h
Added ITK_DEPRECATED when \deprecated is used in a comment. They must both come together. Applied to structs, classes and functions
> Wdeprecated

- Testing/ContinuousIntegration/AzurePipelinesMacOS.yml
- Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
The macOS-11 environment is deprecated and scheduled to be removed on June 28th, 2024.
https://learn.microsoft.com/en-us/azure/devops/release-notes/features-timeline-released
> COMP: macOS-11 Azure CI environment EOL

- Modules/Core/Common/include/itkArray2D.h
- Modules/Core/Common/include/itkArray2D.hxx
- Modules/Core/Common/include/itkCompensatedSummation.h
- Modules/Core/Common/include/itkCompensatedSummation.hxx
- Modules/Core/Common/include/itkVersor.h
- Modules/Core/Common/include/itkVersor.hxx
- Replaced the hand-written copy-constructor and copy-assignment of `Array2D` and `CompensatedSummation` with `= default`.
- Simply removed them from `Versor`, following the "Rule of Zero"
The hand-written copy-constructors were found with regular expression `^(\w+)<.+>::\1\(const Self`
> `Array2D`, `CompensatedSummation`, `Versor`: remove hand-written copy-constructor and assignment

- Modules/Core/SpatialObjects/include/itkArrowSpatialObject.hxx
- Modules/Core/SpatialObjects/include/itkMetaArrowConverter.hxx
- Modules/Core/SpatialObjects/include/itkMetaConverterBase.h
- Modules/Core/SpatialObjects/include/itkMetaConverterBase.hxx
- Modules/Core/SpatialObjects/include/itkMetaImageConverter.hxx
- Modules/Core/SpatialObjects/include/itkMetaSceneConverter.h
- Modules/Core/SpatialObjects/include/itkMetaSceneConverter.hxx
- Modules/Core/SpatialObjects/test/itkMetaArrowConverterTest.cxx
- Modules/IO/SpatialObjects/include/itkSpatialObjectReader.h
- Modules/IO/SpatialObjects/include/itkSpatialObjectReader.hxx
- Modules/IO/SpatialObjects/include/itkSpatialObjectWriter.h
- Modules/IO/SpatialObjects/include/itkSpatialObjectWriter.hxx
When reading/writing spatial objects via Meta, provide the option
of using MetaIO version 1, which fixes bugs in the original MetaIO
and SpatialObject implementations.
Specifically,
- ElementOrigin, ElementDirection, and ElementSpacing are used for the image index to physical space transform specification
- TransformMatrix, Position, and CenterOfRotation are used for the object-to-parent transform in the spatialobject scene graph.
> ENH: Update SpatialObjects for MetaIO v1

- Modules/Filtering/FFT/test/itkFFTWF_FFTTest.cxx
- Modules/Filtering/FFT/test/itkFFTWF_RealFFTTest.cxx
- Modules/Filtering/FFT/test/itkVnlFFTWF_FFTTest.cxx
- Modules/Filtering/FFT/test/itkVnlFFTWF_RealFFTTest.cxx
When building FFTW and not CUFFTW the tests use the argc and argv variables that are otherwise ignored.
> COMP: Conditional compilations missing variables

- Modules/Core/Common/include/itkMacro.h
Make macros look like statements in the code
Remove warnings about unnecessary ; use at end of macros that
are blocks of code rather than simple statements.
The do {} while(0) idiom can be replaced with a compile time
use of the ITK_MACROEND_NOOP_STATEMENT to be consistent and
to allow compile time removal of unused statements.
> Macro noop consistency

- Modules/Core/SpatialObjects/include/itkContourSpatialObjectPoint.h
- Modules/Core/SpatialObjects/include/itkContourSpatialObjectPoint.hxx
- Modules/Core/SpatialObjects/include/itkDTITubeSpatialObjectPoint.h
- Modules/Core/SpatialObjects/include/itkDTITubeSpatialObjectPoint.hxx
- Modules/Core/SpatialObjects/include/itkLineSpatialObjectPoint.h
- Modules/Core/SpatialObjects/include/itkLineSpatialObjectPoint.hxx
- Modules/Core/SpatialObjects/include/itkSpatialObjectPoint.h
- Modules/Core/SpatialObjects/include/itkSpatialObjectPoint.hxx
- Modules/Core/SpatialObjects/include/itkSurfaceSpatialObjectPoint.h
- Modules/Core/SpatialObjects/include/itkSurfaceSpatialObjectPoint.hxx
- Modules/Core/SpatialObjects/include/itkTubeSpatialObjectPoint.h
- Modules/Core/SpatialObjects/include/itkTubeSpatialObjectPoint.hxx
- Modules/Core/SpatialObjects/test/CMakeLists.txt
- Modules/Core/SpatialObjects/test/itkSpatialObjectPointGTest.cxx
Replaced hand-written copy-constructors and assignment operators by `ITK_DEFAULT_COPY_AND_MOVE` macro calls, in `SpatialObjectPoint` and its derived classes.
Will make the (compiler-generated) move-assignment operator of these classes `noexcept`, as tested.
----
- For the record, the `ITK_DEFAULT_COPY_AND_MOVE` macro was introduced with ITK 5.4, by pull request #4652
> PERF: Add fast "move semantics" to SpatialObjectPoint classes

- Modules/Core/Common/include/itkConstNeighborhoodIterator.h
- Modules/Core/Common/include/itkConstNeighborhoodIteratorWithOnlyIndex.h
- Modules/Core/Common/include/itkConstShapedNeighborhoodIterator.h
- Modules/Core/Common/include/itkMacro.h
- Modules/Core/Common/include/itkNeighborhoodIterator.h
- Modules/Core/Common/include/itkShapedNeighborhoodIterator.h
With ITKv5 several methods for Image Iterators have been devirtualized for performance reasons.
The temporary definitions provided legacy compatibility. Error messages are now triggered to help detect
virtualized iterators.
Methods that were non-const in ITKv4, compile-time conditionally const in ITKv5, are now unconditionally const for itkv6.
> ENH: Finalize ITKv5 API changes for ITKv6

- Modules/IO/XML/src/itkStringTools.cxx
- Modules/Numerics/Optimizers/src/itkOptimizer.cxx
ENH: Fix algorithm to better match data types
Update stl algorithm based on suggestions which explictly warns against the anti-pattern used for toupper and tolower string manipulations.
https://en.cppreference.com/w/cpp/string/byte/toupper with std algorithms
> Fix algorithm usage

- Modules/IO/TransformHDF5/src/itkHDF5TransformIO.cxx
- BUG: ElementType with PolyLineParametricPath ContinuousIndex
- ENH: Add dict_from_polyline, polyline_from_dict
- COMP: Remove \brief with nothing after
- COMP: Fixed Cpp Warnings
- BUG: VTKPolyDataMeshIO support for reading VTK 5.1 format
- BUG: Mark GDCM macOS CMake variables as advanced
- BUG: Mark Module_FastBilateral as advanced
- BUG: Wrap SymmetricEigenAnalysisImageFilter with CovariantVector Image output
- BUG: Check output of StatisticsUniqueLabelMapFilterTest1
- BUG: Address bugs in unique label map filters
- BUG: Remove dilation output in test
- ENH: A GTest for LabelUniqueLabelMapFilter
- DOC: Update .zenodo
- COMP: macOS-11 Azure CI environment EOL
- BUG: HDF5TransformIO throw exception instead of segfault
> hdf5 empty transform list

- Modules/Core/Common/include/itkCellInterface.h
- Modules/Core/Common/include/itkMacro.h
- Modules/Core/Common/include/itkNumericTraits.h
- Modules/Core/Common/include/itkNumericTraitsFixedArrayPixel.h
- Modules/Core/Common/include/itkProcessObject.h
- Modules/Core/Common/include/itkPromoteType.h
- Modules/Core/Common/include/itkSymmetricEigenAnalysis.h
- Modules/Core/Common/include/itkVectorContainer.h
- Modules/Core/Transform/include/itkBSplineTransform.h
- Modules/Filtering/Convolution/include/itkConvolutionImageFilterBase.h
- Modules/Filtering/DisplacementField/include/itkVelocityFieldTransform.h
- Modules/Filtering/ImageFilterBase/include/itkNullImageToImageFilterDriver.hxx
- Modules/Filtering/ImageFrequency/include/itkFrequencyShiftedFFTLayoutImageRegionConstIteratorWithIndex.h
- Modules/Filtering/ImageIntensity/include/itkArithmeticOpsFunctors.h
- Modules/IO/IPL/include/itkIPLFileNameList.h
- Modules/Numerics/Optimizersv4/include/itkLBFGS2Optimizerv4.h
- Modules/Registration/Common/include/itkTransformParametersAdaptor.h
- Modules/Registration/Metricsv4/include/itkPointSetToPointSetMetricWithIndexv4.h
- Modules/Registration/Metricsv4/include/itkPointSetToPointSetMetricv4.h
Decided to remove semicolon from struct and not from where the function-like macro is used. Is this a fix that is acceptable? Can we proceed with similar fixes?
> COMP: -Wextra-semi new fix proposed

- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
- Wrapping/macro_files/itk_auto_load_submodules.cmake
We may bump the standard version in the future or remote modules may use a different standard version.
> COMP: Set CastXML flag based on CMAKE_CXX_STANDARD

- Modules/Core/SpatialObjects/include/itkPolygonSpatialObject.hxx
- Modules/Filtering/Denoising/include/itkPatchBasedDenoisingBaseImageFilter.hxx
- Modules/Filtering/Denoising/include/itkPatchBasedDenoisingImageFilter.hxx
- Modules/Filtering/ImageSources/include/itkGaborImageSource.hxx
- Modules/IO/DCMTK/src/itkDCMTKSeriesFileNames.cxx
- Modules/IO/ImageBase/include/itkImageFileWriter.hxx
- Modules/IO/ImageBase/include/itkImageSeriesWriter.hxx
- Modules/IO/ImageBase/src/itkImageIOBase.cxx
- Modules/IO/MeshBase/include/itkMeshFileWriter.hxx
- Modules/Registration/FEM/include/itkMIRegistrationFunction.hxx
Improve ivar printing in `PrintSelf` methods:
- Use the `itkPrintSelfObjectMacro` macro to avoid boilerplate code when printing smart pointers/objects that can be null pointers.
- Rely on the enum classes ostream insertion operator overload to directly print such variables. Avoid boilerplate code.
- Increase consistency when printing boolean ivars: use the `({ivar} ? "On" : "Off")`  recipe in agreement with the ITK SW Guide.
- Do not check whether `std::string` types ivars are empty to conditionally print their contents; rely on the ostream insertion operator overload to print the appropriate content.
- Print the member variable names verbatim to conform to the ITK SW Guide.
- Prefer using `std::endl` instead of `\n` to add a new line for the sake of consistency.
Take advantage of the …
> STYLE: Improve ivar printing in `PrintSelf` methods

- Modules/Core/SpatialObjects/include/itkMetaSceneConverter.h
- Modules/Core/SpatialObjects/include/itkMetaSceneConverter.hxx
The ITK I/O methods for SpatialObjectRead and SpatialObjectWrite have functions for setting the MetaIO version to use when reading/writing files.  See the MetaIO commit: https://github.com/Kitware/MetaIO/commit/eb952d5b2dbbccc27a99cc1b4cb27410f5267981
However, in multi-object MetaIO files (i.e., metaScene files) the user specification of the MetaIO version was not propagated to the readers used for the components objects of the file - resulting in warnings and errors.
This update and a corresponding MetaIO update (https://github.com/Kitware/MetaIO/pull/129) address this error.
> BUG: Propogate MetaIOVersion to child objects in scene I/O

- Modules/Core/Common/src/itkProcessObject.cxx
Improve ivar printing in `itk::ProcessObject` `PrintSelf` method:
- Print the member variable names verbatim to conform to the ITK SW Guide.
- Avoid printing data other than ivars (e.g. values obtained through `Get` methods).
> STYLE: Improve ivar printing in `itk::ProcessObject` `PrintSelf` method

- Wrapping/Generators/Python/Tests/verifyGetOutputAPIConsistency.py
Meant to address:
```log
> python "M:/Dashboard/ITK/Wrapping/Generators/Python/Tests/verifyGetOutputAPIConsistency.py"
...
File "M:\Dashboard\ITK\Wrapping\Generators\Python\Tests\verifyGetOutputAPIConsistency.py", line 104, in <module>
tot, w = checkGetOutputConsistency(o, t)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "M:\Dashboard\ITK\Wrapping\Generators\Python\Tests\verifyGetOutputAPIConsistency.py", line 83, in checkGetOutputConsistency
i.GetOutput()
TypeError: itkPhaseCorrelationOptimizerF2.GetOutput() missing 1 required positional argument: 'index' itkTestDriver: Process exited with return value: 1
```
> COMP: Add ITKMontage's PhaseCorrelationOptimizer to API ignore list

- Documentation/docs/conf.py
Specify the Read The Docs custom domain in the documentation config file.
Read the Docs is deprecating Sphinx context injection at build time starting Monday, Oct 7, 2024, so any custom domain specified in the Read the Docs admin needs to be defined in the configuration file.
Documentation:
https://about.readthedocs.com/blog/2024/07/addons-by-default/
> ENH: Specify rtd custom domain in the documentation config file

- Modules/Core/Common/include/itkImageBase.hxx
- Modules/Core/Common/include/itkMatrix.h
- Modules/Core/Transform/include/itkMatrixOffsetTransformBase.hxx
Add Matrix::PrintSelf method which uses ITK's indent object to allow proper indenting of nested objects.
Fixes left aligned matrix values when printing the Image classes.
> ENH: Add indent to image's matrix printing

- Testing/ContinuousIntegration/AzurePipelinesLinux.yml
- Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml
Avoid unrelated `importlib_metadata` errors reported in #4781
> COMP: Remove unused setuptools upgrade in Linux builds

- Modules/Core/SpatialObjects/include/itkSpatialObjectToImageFilter.hxx
Improve `itk::SpatialObjectToImageFilter::PrintSelf` ivar printing:
- Print the member variable names verbatim to conform to the ITK SW Guide style guidelines.
- Do not add an extra white space after the variable name to conform to the ITK SW Guide style guidelines.
- Use the `itkPrintSelfBooleanMacro` macro to print boolean objects.
> STYLE: Improve `SpatialObjectToImageFilter::PrintSelf` ivar printing

- Modules/Numerics/FEM/test/itkFEMElement3DTest.cxx
Fix input argument count check in FEM test: set the appropriate value to the number of expected arguments.
This test has never required three input arguments since its introduction in commit 23f10a989aca2146ba1f2782fa92fdca4fd7d280.
The number of required input arguments was set mistakenly to three in commit 60067a656d0d67c3bcdb4d1c3f3a6d300edca781.
Fixes:
```
Missing parameters.
Usage: itkFEMElement3DTest inputFileName
```
reported for example in:
https://open.cdash.org/viewTest.php?onlyfailed&buildid=9768301
Addresses some of the issues reported in #4782.
> BUG: Fix input argument count check in FEM test

- Modules/Registration/Metricsv4/include/itkANTSNeighborhoodCorrelationImageToImageMetricv4GetValueAndDerivativeThreader.hxx
Found with thread sanitizer (TSan) running the `itkANTSNeighborhoodCorrelationImageToImageRegistrationTest` unit test.
There was already a `m_ANTSAssociateOnceFlag` flag for use with `std::call_once`, so I just used that in this place too (it's already used elsewhere).
Partial backtrace from TSan:
```
WARNING: ThreadSanitizer: data race (pid=79176)
Write of size 8 at 0x000108f02240 by thread T2:
#0 void itk::ANTSNeighborhoodCorrelationImageToImageMetricv4GetValueAndDerivativeThreader<itk::ThreadedIndexedContainerPartitioner, itk::ImageToImageMetricv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<double, 2u>, itk::Image<double, 2u>, itk::Image<double, 2u>, double>>, …
```
> BUG: fixed race condition setting m_ANTSAssociate

- Documentation/Doxygen/MainPage.dox
Scaled original image by 50% in height and width. Changed because original image was too large.
Closes PR #4785 
> DOC: Reduced main image size

- Modules/IO/GE/src/itkGE4ImageIO.cxx
- Modules/IO/GE/src/itkGE5ImageIO.cxx
- Modules/IO/GE/src/itkGEAdwImageIO.cxx
"new" throws an exception when it fails.
> BUG: Remove check for nullptr after new

- .clang-format
- Modules/Core/Common/include/itkBoundingBox.h
- Modules/Core/Common/include/itkFixedArray.h
- Modules/Core/Common/include/itkMacro.h
- Modules/Core/Common/include/itkMultiThreaderBase.h
- Modules/Core/Common/include/itkPlatformMultiThreader.h
- Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.h
- Modules/Core/SpatialObjects/include/itkSurfaceSpatialObject.h
- Modules/Core/Transform/include/itkTransform.h
- Modules/Filtering/ImageGrid/include/itkResampleImageFilter.h
- Modules/Filtering/Smoothing/include/itkDiscreteGaussianImageFilter.h
Previously, some places *required* a trailing semi and some places required *no* trailing semi.
For example, I see no way to force this kind of usage to have a trailing semi, because that would stick a semi right before the function definition, which isn't allowed:
```
itkLegacyMacro(static ThreadIdType GetGlobalDefaultNumberOfThreads())
{
"can affect all MultiThreaderBase's derived classes in ITK");
return Superclass::GetGlobalDefaultNumberOfThreads();
}
```
Such existing uses only work if inside `#if !defined(ITK_LEGACY_REMOVE)` because only that variation of the definition of the `itkLegacyMacro` macro doesn't require a trailing semi.
It's rather strange for users to both require and forbid traling semis, so this change chooses the only way that can work in all cases.
Fixes various …
> COMP: change itkLegacyMacro to never require a trailing semi colon

- Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest3.cxx
The nifti descrip field is currently only read and exposed via the ITK_FileNotes metadata dictionary variable. Setting the ITK_FileNotes via the metadata dictionary has no effect while writing. This commit writes the contents of the ITK_FileNotes variable if it is found in the metadata dictionary.
> BUG: Missing writing of the nifti descrip field.

- Modules/Remote/TotalVariation.remote.cmake
CMake fixes to address CMake IMPORTED target:
The link interface of target "proxTV" contains:
OpenMP::OpenMP_CXX
but the target was not found.  Possible reasons include:
* There is a typo in the target name.
* A find_package call is missing for an IMPORTED target. * An ALIAS target is missing.
> COMP: Bump ITKTotalVariation remote module

- Modules/ThirdParty/DCMTK/CMakeLists.txt
- Modules/ThirdParty/DCMTK/DCMTKGitTag.cmake
The dsr2html tool uses a hardcoded literal string as a hyperlink prefix for refrenced composite objects (images, waveforms, etc.) in rendering the Key Object Selection documents.
Replace this literal with a string argument that will be passed by a calling application / function.
Pushed upstream: DCMTK/dcmtk#108
> dicom structured report prefix

- Modules/Core/Common/include/itkMacro.h
The error was:
```
Modules/Core/GPUCommon/include/itkGPUImageOps.h:26:1: error: expected ';' after class
itkGPUKernelClassMacro(GPUImageOpsKernel);
^
```
> COMP: fixed compiler error with ITK_USE_GPU = YES

- Modules/Core/Common/include/itkMetaDataObject.h
- Modules/Core/Common/include/itkMetaDataObject.hxx
- Modules/Core/Common/test/itkMetaDataObjectTest.cxx
Also removes dead code related to METADATAPRINT
Does not currently add printing for std::vector.
Fix #1454
Near duplicate of: #4368
Co-Author: Pablo Hernandez-Cerdan <pablo.hernandez.cerdan@outlook.com>
> BUG: Fix printing of values in MetaDataObject

- Modules/Core/Common/include/itkMetaDataObject.hxx
- Modules/Core/Common/include/itkMetaDataObjectDetail.h
Move meta programming details from unnamed namespace to separate file and header.
> STYLE: move details to MetaDataObjectDetail

- Modules/Core/Common/include/itkImageConstIterator.h
- Modules/Core/Common/include/itkImageConstIteratorWithIndex.h
- Modules/Core/Common/include/itkImageConstIteratorWithOnlyIndex.h
- Modules/Core/Common/include/itkImageIterator.h
- Modules/Core/Common/include/itkImageIteratorWithIndex.h
- Modules/Core/Common/include/itkImageLinearConstIteratorWithIndex.h
- Modules/Core/Common/include/itkImageLinearIteratorWithIndex.h
- Modules/Core/Common/include/itkImageRegionConstIterator.h
- Modules/Core/Common/include/itkImageRegionConstIteratorWithIndex.h
- Modules/Core/Common/include/itkImageRegionConstIteratorWithOnlyIndex.h
- Modules/Core/Common/include/itkImageRegionExclusionConstIteratorWithIndex.h
- Modules/Core/Common/include/itkImageRegionExclusionIteratorWithIndex.h
- Modules/Core/Common/include/itkImageRegionIterator.h
- Modules/Core/Common/include/itkImageRegionIteratorWithIndex.h
- Modules/Core/Common/include/itkImageRegionReverseConstIterator.h
- Modules/Core/Common/include/itkImageRegionReverseIterator.h
- Modules/Core/Common/include/itkImageReverseConstIterator.h
- Modules/Core/Common/include/itkImageReverseIterator.h
- Modules/Core/Common/include/itkImageScanlineConstIterator.h
- Modules/Core/Common/include/itkImageScanlineIterator.h
- Modules/Core/Common/include/itkImageSliceConstIteratorWithIndex.h
- Modules/Core/Common/include/itkImageSliceIteratorWithIndex.h
- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkImageRegionIteratorGTest.cxx
Documented that `Iterator(image, region)` constructors initialize the iterator at the beginning of the region. Added a GoogleTest unit test to checks this added specification.
> Document that Iterator(image, region) constructors initialize at the begin, add GTest unit test

- Modules/Registration/GPUPDEDeformable/include/itkGPUPDEDeformableRegistrationFilter.hxx
Warning was:
```
/Modules/Registration/GPUPDEDeformable/include/itkGPUPDEDeformableRegistrationFilter.hxx:102:7: warning: comparison of array 'this->m_GPUSmoothingKernels' not equal to a null pointer is always true [-Wtautological-pointer-compare]
if (m_GPUSmoothingKernels != nullptr)
^~~~~~~~~~~~~~~~~~~~~    ~~~~~~~
```
> Fix clang -Wtautological-pointer-compare warnings

- Wrapping/Generators/Python/PyUtils/CMakeLists.txt
Sample error message:
```log
/Users/svc-dashboard/D/Support/ITK-rwdi/Wrapping/castxml_inputs/itkPyCommand.cxx /Users/svc-dashboard/D/Support/ITK-rwdi/Wrapping/castxml_inputs/itkPyCommand.cxx:16:10: fatal error: 'itkPyCommand.h' file not found
16 | #include "itkPyCommand.h"
|          ^~~~~~~~~~~~~~~~
1 error generated.
```
> COMP: Fix missing include files

- Modules/Filtering/ImageFrequency/include/itkFrequencyFFTLayoutImageRegionConstIteratorWithIndex.h
- Modules/Filtering/ImageFrequency/include/itkFrequencyFFTLayoutImageRegionIteratorWithIndex.h
- Modules/Filtering/ImageFrequency/include/itkFrequencyHalfHermitianFFTLayoutImageRegionConstIteratorWithIndex.h
- Modules/Filtering/ImageFrequency/include/itkFrequencyHalfHermitianFFTLayoutImageRegionIteratorWithIndex.h
- Modules/Filtering/ImageFrequency/include/itkFrequencyShiftedFFTLayoutImageRegionConstIteratorWithIndex.h
- Modules/Filtering/ImageFrequency/include/itkFrequencyShiftedFFTLayoutImageRegionIteratorWithIndex.h
- Modules/Filtering/ImageFrequency/test/itkFrequencyIteratorsGTest.cxx
- Follow-up to pull request #4815
- Note: `FrequencyImageRegionIteratorWithIndex` and `FrequencyImageRegionConstIteratorWithIndex` are excluded from this pull request, because they do not yet compile. (As is observed by #4828)
> Document that Iterator(image, region) constructors of "ImageFrequency" initialize at the begin, add GTest unit test

- Modules/Core/Common/include/itkObject.h
- Modules/Core/Common/src/itkObject.cxx
- Wrapping/Generators/Python/PyBase/pyBase.i
The `const` overload of `Object::AddObserver` can serve both "const" and "non-const" instances of and references to an `itk::Object`, so the non-const overload should not be necessary.
Note: this is an ABI change, and it might affect the SWIG output, but it should be acceptable for ITK 6.
----
Related pull requests:
- #3636
- #3669
- #4685 by Piyush Aggarwal (@tm9k1)
> STYLE: Remove redundant non-const `Object::AddObserver` overload

- Modules/Numerics/FEM/test/itkImageToRectilinearFEMObjectFilter2DTest.cxx
- Modules/Numerics/FEM/test/itkImageToRectilinearFEMObjectFilter3DTest.cxx
Fix ImageToRectilinearFEM tests arg checks:
- Fix the value for the `argc` comparison.
- Define the test data dimension as a constant so that it can be reused.
- Add additional checks to test that the provided node and element argument numbers match the expected numbers.
Fixes #4782.
> BUG: Fix ImageToRectilinearFEM tests arg checks

- Modules/Core/Common/include/itkImageBase.h
- Modules/Core/Common/include/itkImageConstIteratorWithIndex.h
- Modules/Core/Common/include/itkImageConstIteratorWithOnlyIndex.h
- Modules/Core/Common/include/itkImageRegion.h
- Modules/Core/Common/test/itkImageBaseGTest.cxx
- Modules/Core/Common/test/itkImageRegionGTest.cxx
Allowed calling `GetImageDimension()` at compile-time.
> Declare `GetImageDimension()` member functions constexpr, add compile-time tests

- Modules/Core/Common/include/itkConicShellInteriorExteriorSpatialFunction.hxx
- Modules/Core/Common/include/itkFiniteCylinderSpatialFunction.hxx
- Modules/Core/Common/include/itkVector.h
- Modules/Core/Common/test/itkVectorGTest.cxx
- Modules/Core/Transform/include/itkComposeScaleSkewVersor3DTransform.hxx
Tests that `itkVector.GetNorm()` equals `itkVector.GetVnlVector().magnitude()`.
> Add `Vector.NormEqualsVnlVectorMagnitude` unit test, add "magnitude" to documentation

- Modules/IO/MeshBase/include/itkMeshFileWriter.h
- Modules/IO/MeshBase/include/itkMeshFileWriter.hxx
- Wrapping/Generators/Python/Tests/extras.py
- Wrapping/Generators/Python/itk/support/extras.py
> Expose a binary parameter to `meshwrite` function

- Modules/Filtering/GPUImageFilterBase/wrapping/itkGPUCastImageFilter.wrap
- Modules/Filtering/GPUSmoothing/wrapping/itkGPUDiscreteGaussianImageFilter.wrap
Attempting to close #3777. As suggested in the issue, marking `itkCastImageFilter` and `itkGPUCastImageFilter` as `POINTER_WITH_SUPERCLASS` allows compiling.
---
I still encounter an issue where certain wrapped filters fail with `OpenCL Error : CL_INVALID_MEM_OBJECT`. Note the same C++ filters succeed.
This is reproducible with:
```
cmake -DITK_WRAP_PYTHON=ON -DITK_USE_GPU=ON ...
cmake --build ...
ctest -R itkGPU
```
```
Test project ...
Start  959: itkGPUGradientAnisotropicDiffusionImageFilterTest2D
1/24 Test  #959: itkGPUGradientAnisotropicDiffusionImageFilterTest2D .........   Passed    0.15 sec
Start  960: itkGPUGradientAnisotropicDiffusionImageFilterTest3D
2/24 Test  #960: itkGPUGradientAnisotropicDiffusionImageFilterTest3D .........   Passed    0.42 sec
...
Start 3151: …
```
> COMP: Fix Python GPU Wrapping

- Modules/Filtering/ImageFrequency/include/itkFrequencyImageRegionConstIteratorWithIndex.h
- Modules/Filtering/ImageFrequency/include/itkFrequencyImageRegionIteratorWithIndex.h
- Modules/Filtering/ImageFrequency/test/itkFrequencyIteratorsGTest.cxx
Test it via recently added gtest (see #4827)
Closes #4828
> BUG: Fix itkFrequencyImageRegionIterator

- Modules/Core/SpatialObjects/include/itkSpatialObjectProperty.h
- Modules/Core/SpatialObjects/src/itkSpatialObjectProperty.cxx
SWIG's binding for writable std::string objects is a "std::string *" which is not implemented.
closes #4779 
replaces #4776
> BUG: Remove SpatialObjectProperty's writable string methods from SWIG

- Modules/Core/Common/include/itkByteSwapper.h
- Modules/Core/Common/include/itkByteSwapper.hxx
- Follow-up to pull request #4835
Note: when reviewing, it may be helpful to ignore white-space changes: https://github.com/InsightSoftwareConsortium/ITK/pull/4841/files?w=1
> Replace `#ifdef`s in ByteSwapper with `if constexpr`, mention C++20 `std::endian` in documentation

- Modules/Core/Common/include/itkVectorContainer.h
- Modules/Core/Common/test/itkVectorContainerGTest.cxx
Eases making an `itk::VectorContainer` based on a specific `std::vector` instance.
> ENH: Add `itk::MakeVectorContainer(std::vector<TElement>)`

- Modules/Core/Common/include/itkPointSet.h
- Modules/Core/Common/include/itkPointSet.hxx
- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkPointSetGTest.cxx
- Added a warning to `PointSet::SetPoints(PointsVectorContainer *)`, mitigating issue #4848 
- Added `PointSet::SetPointsByCoordinates` as a safe alternative.
> Add `SetPointsByCoordinates` to PointSet, add warning to `SetPoints(PointsVectorContainer *)`

- Modules/Core/Common/include/itkBSplineInterpolationWeightFunction.h
- Modules/Core/Common/include/itkFixedArray.h
- Modules/Core/Common/include/itkMacro.h
- Modules/Core/Common/include/itkMatrix.h
- Modules/Core/Common/include/itkMultiThreaderBase.h
- Modules/Core/Common/include/itkSingleton.h
- Modules/Core/Common/test/itkSmartPointerGTest.cxx
- Modules/Core/SpatialObjects/include/itkEllipseSpatialObject.h
- Modules/Core/SpatialObjects/include/itkGaussianSpatialObject.h
- Modules/Core/SpatialObjects/include/itkImageSpatialObject.h
- Modules/Core/SpatialObjects/include/itkMeshSpatialObject.h
- Modules/Core/SpatialObjects/include/itkTubeSpatialObject.h
- Modules/Core/Transform/include/itkBSplineBaseTransform.h
- Modules/Core/Transform/include/itkBSplineTransform.h
- Modules/Filtering/Convolution/include/itkConvolutionImageFilterBase.h
- Modules/Filtering/DisplacementField/include/itkVelocityFieldTransform.h
- Modules/Filtering/ImageFilterBase/include/itkNullImageToImageFilterDriver.hxx
- Modules/Numerics/Optimizersv4/include/itkCommandIterationUpdatev4.h
- Modules/Numerics/Optimizersv4/include/itkObjectToObjectOptimizerBase.h
- Modules/Registration/Common/include/itkTransformParametersAdaptor.h
- Modules/Registration/Metricsv4/include/itkImageToImageMetricv4.h
Ran at bash:
find . -regex '.*itk.*\.\(hxx\|h\|cxx\)' -exec /f/bin/ITK/ClangFormat-prefix/src/ClangFormat/clang-format.exe -style=file -i {} \;
Manually reverted changes in ThirdParty.
At the moment, the "client side" is responsible for running clang-format.exe
Related commits:
- pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4712 commit c7e8b2506b5fecb28b5b9ab451aebbabe4bfe05f
"BUG: Remove Apply clang-format to PR", June 5, 2024
- pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4707 commit 4b0d263e955b8da9ac1284d25f3ba007e376aff9
"ENH: Remove Clang Format Linter Action", June 3 2024
> STYLE: Run clang-format.exe manually at the client side

- Modules/Bridge/NumPy/include/itkPyBuffer.hxx
- Modules/Bridge/NumPy/include/itkPyVectorContainer.hxx
- Modules/Bridge/NumPy/include/itkPyVnl.hxx
Fixed various Visual Studio 2022 Code Analysis warnings from "Bridge/NumPy": 
> warning C26493: Don't use C-style casts (type.4).
> warning C26494: Variable '...' is uninitialized. Always initialize an object (type.5).
> warning C26496: The variable '...' does not change after construction, mark it as const (con.4).
> Fix VS2022 code analysis warnings from "Bridge/NumPy", including `buffer` initializations

- .github/workflows/itk_dict.txt
- Modules/Core/Common/include/itkByteSwapper.h
- Modules/Core/Common/include/itkByteSwapper.hxx
Aims to reduce code duplication. Inspired by a suggestion from Bradley (@blowekamp) at https://github.com/InsightSoftwareConsortium/ITK/pull/4841/files#r1751777344
> STYLE: Clean-up ByteSwapper, using private `SwapBytes` helper function

- Modules/Segmentation/ConnectedComponents/include/itkRelabelComponentImageFilter.h
* Update parameter type to reflect underlying container indexing
Fixes #4865
There is a public API change as the parameter type is changed.
> COMP: Fix compilation issue when using RelabelComponentImageFilter

- Modules/Core/Common/include/itkByteSwapper.h
- Modules/Core/Common/include/itkByteSwapper.hxx
The type alias `OStreamType` just served as a workaround to an old MSVC bug. This pull request deprecates (`ITK_FUTURE_LEGACY_REMOVE`) the type alias.
This pull request also has a fix for the behavior of `SwapWriteRangeFromSystemToBigEndian` and `SwapWriteRangeFromSystemToLittleEndian`, for when `sizeof(T) == 1`. The original code did nothing, in that case. With this pull request, those member functions will in that case just write the specified range to the output stream.
> Deprecate `ByteSwapper::OStreamType`, fix "SwapWriteRange" member functions

- Modules/Bridge/NumPy/include/itkPyBuffer.hxx
- Modules/Bridge/NumPy/include/itkPyVectorContainer.hxx
- Modules/Bridge/NumPy/include/itkPyVnl.hxx
According to https://docs.python.org/3.12/c-api/buffer.html#c.PyObject_GetBuffer, `PyBuffer_Release` should only be called after a _successful_ `PyObject_GetBuffer` call.
Also fixed a few MSVC 2022 warnings:
> warning C4189: 'res': local variable is initialized but not referenced
> warning C4389: '!=': signed/unsigned mismatch
> Remove unnecessary PyBuffer_Release calls, and other "Bridge/NumPy"  style improvements

- Modules/Core/Common/include/itkSTLConstContainerAdaptor.h
- Modules/Core/Common/include/itkVectorContainer.h
- Modules/Core/Common/include/itkVectorContainer.hxx
- Modules/Core/Common/test/itkVectorContainerGTest.cxx
- Modules/Core/Mesh/include/itkMesh.h
- Modules/Core/SpatialObjects/include/itkBlobSpatialObject.h
- Modules/Core/SpatialObjects/include/itkContourSpatialObject.h
- Modules/Core/SpatialObjects/include/itkDTITubeSpatialObject.h
- Modules/Core/SpatialObjects/include/itkEllipseSpatialObject.h
- Modules/Core/SpatialObjects/include/itkLandmarkSpatialObject.h
- Modules/Core/SpatialObjects/include/itkLineSpatialObject.h
- Modules/Core/SpatialObjects/include/itkMeshSpatialObject.h
- Modules/Core/SpatialObjects/include/itkSpatialObject.h
- Modules/Core/SpatialObjects/include/itkSurfaceSpatialObject.h
- Modules/Core/SpatialObjects/include/itkTubeSpatialObject.h
- Modules/Core/Transform/include/itkKernelTransform.h
- Modules/Filtering/FastMarching/include/itkFastMarchingExtensionImageFilterBase.h
- Modules/Filtering/FastMarching/include/itkFastMarchingTraits.h
- Modules/Filtering/ImageSources/include/itkGridImageSource.h
- Modules/IO/MeshVTK/include/itkVTKPolyDataMeshIO.h
- Modules/Registration/Common/include/itkPointsLocator.h
- Modules/Registration/Metricsv4/test/itkEuclideanDistancePointSetMetricTest3.cxx
For most use cases, it appears that the index type of `itk::VectorContainer` should just be `itk::SizeValueType` (or `itk::IdentifierType`, but that's just an alias of `itk::SizeValueType`).
This pull request allows users to write `itk::VectorContainer<ElementType>` as a shorthand for `itk::VectorContainer<itk::SizeValueType, ElementType>`.
> Make the index type of VectorContainer `itk::SizeValueType` by default

- Modules/Segmentation/ConnectedComponents/test/itkRelabelComponentImageFilterTest.cxx
Add a template instantiation to check that the `itk::RelabelComponentImageFilter` class does not trigger compiler warnings with signed pixel types.
Ensures regressions are not introduced after the fix in commit 108a2cf.
> ENH: Add `itk::RelabelComponentImageFilter` signedness check

- Modules/Core/Common/include/itkOffset.h
- Modules/Core/Common/src/itkFloatingPointExceptions_unix.cxx
- Modules/Core/Common/test/itkFixedArrayTest2.cxx
- Modules/IO/BioRad/src/itkBioRadImageIO.cxx
- Modules/IO/GE/src/itkGE5ImageIO.cxx
- Modules/IO/MRC/src/itkMRCHeaderObject.cxx
- Modules/IO/MRC/src/itkMRCImageIO.cxx
- Modules/IO/PhilipsREC/src/itkPhilipsPAR.cxx
- Modules/IO/PhilipsREC/src/itkPhilipsRECImageIO.cxx
- Modules/IO/TransformMINC/src/itkMINCTransformIO.cxx
- Modules/IO/VTK/src/itkVTKImageIO.cxx
- Replaced memset calls with `{}` assignment or initialization
- Replaced memset calls after `new T` with just `()` (doing `new T()` instead)
- Removed some `memset` calls that had no effect at all
---
- Follow-up to pull request #4863 commit aaff35cc345d3a587cfb3626c8cb93d72e2b7640
> Remove zero-filling memset calls and replace them with `()` or `{}`

- Modules/Core/QuadEdgeMesh/wrapping/itkQuadEdgeMeshBase.wrap
Aims to address Windows specific wrapping failures at the CI (https://open.cdash.org/viewBuildError.php?type=1&buildid=9948358), including:
itkQuadEdgeMeshBase: warning(4): ITK type not wrapped, or currently not known: itk::QuadEdgeMeshPoint< float, 2 >
And locally, from Visual Studio 2022:
Bin\ITK\Wrapping\Typedefs\itkQuadEdgeMeshBase.i(1220): warning 401: Nothing known about base class 'itk::PointSetBase< itk::MapContainer< unsigned long long,itk::QuadEdgeMeshPoint< float,2,itk::GeometricalQuadEdge< unsigned long long,unsigned long long,bool,bool > > > >'. Ignored.
Bin\ITK\Wrapping\Typedefs\itkQuadEdgeMeshBase.i(1220): warning 401: Maybe you forgot to instantiate 'itk::PointSetBase< itk::MapContainer< unsigned long long,itk::QuadEdgeMeshPoint< float,2,itk::GeometricalQuadEdge< unsigned …
> COMP: Specify GeometricalQuadEdge in PointSetBase wrapping QuadEdgeMesh

- Modules/Core/Common/include/itkMetaDataObjectDetail.h
Missing include in tkMetaDataObjectDetail.h.
On my system (Arch Linux, GCC 14.2.1, cmake 3.30.5) it didn't compile without this edit.
> COMP: missing include in itkMetaDataObjectDetail.h

- Modules/Core/Common/include/itkDefaultStaticMeshTraits.h
- Modules/Core/Common/include/itkSTLContainerAdaptor.h
- Modules/Core/Common/test/itkModifiedTimeTest.cxx
- Modules/Core/Common/test/itkPointGeometryTest.cxx
- Modules/Core/Common/test/itkSTLContainerAdaptorTest.cxx
- Modules/Core/Common/test/itkThreadedIteratorRangePartitionerTest2.cxx
- Modules/Core/Common/test/itkVectorContainerGTest.cxx
- Modules/Core/Common/test/itkVectorContainerTest.cxx
- Modules/Filtering/FastMarching/include/itkFastMarchingTraits.h
- Modules/Nonunit/IntegratedTest/test/itkCommonPrintTest.cxx
- Modules/Numerics/Statistics/test/itkVectorContainerToListSampleAdaptorTest.cxx
- Modules/Registration/Common/test/itkPointsLocatorTest.cxx
- Following pull request #4856 commit edae0bcd6e0dcf679abd08d77792d0867c693878
Note that this pull request should not affect the API or the ABI of ITK in any way.  😇
> Remove `VectorContainer` Identifier template argument from `DefaultStaticMeshTraits`, tests, and comments 

- Modules/Bridge/NumPy/include/itkPyBuffer.h
- Modules/Bridge/NumPy/include/itkPyBuffer.hxx
- Modules/Bridge/NumPy/include/itkPyVectorContainer.h
- Modules/Bridge/NumPy/include/itkPyVectorContainer.hxx
- Modules/Bridge/NumPy/include/itkPyVnl.h
- Modules/Bridge/NumPy/include/itkPyVnl.hxx
- Following pull request #4872
> Remove top-level const from return types in "Bridge/NumPy", and other style commits

- Modules/Bridge/NumPy/include/itkPyBuffer.hxx
A few more coding style improvements of `itk::PyBuffer`.
> Remove some local variables from PyBuffer, declare others const, remove buffer pointer casts

- Modules/Bridge/NumPy/include/itkPyVectorContainer.hxx
- Modules/Bridge/NumPy/include/itkPyVnl.hxx
A few more coding style improvements in PyVectorContainer and PyVnl.
> Use `assign` in PyVectorContainer, declare `len` variables const

- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshPoint.h
- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshPoint.hxx
Defaulted the default-constructor of `QuadEdgeMeshPoint`, and added an initializer to its data member m_Edge, to ensure that an instance of this type can be properly initialized by an empty initializer list, `{}`.
Aims to fix the dynamic analysis defects reported by Jon Haitz Legarreta Gorroño (@jhlegarreta) at https://github.com/InsightSoftwareConsortium/ITK/pull/4884#issuecomment-2426580344
> BUG: `QuadEdgeMeshPoint` should be properly initialized by `{}`

- Modules/Core/Common/include/itkAnatomicalOrientation.h
- Modules/Core/Common/src/CMakeLists.txt
- Modules/Core/Common/src/itkAnatomicalOrientation.cxx
- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkAnatomicalOrientationGTest.cxx
- Modules/Core/Common/wrapping/itkAnatomicalOrientation.wrap
- Modules/IO/GE/src/itkGE4ImageIO.cxx
- Modules/IO/GE/src/itkGE5ImageIO.cxx
- Modules/IO/GE/src/itkGEAdwImageIO.cxx
- Modules/IO/IPL/include/itkGEImageHeader.h
- Modules/IO/IPL/src/itkIPLCommonImageIO.cxx
- Modules/IO/ImageBase/test/itkReadWriteImageWithDictionaryTest.cxx
- Modules/IO/Meta/src/itkMetaImageIO.cxx
- Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest.h
- Modules/IO/NIFTI/test/itkNiftiImageIOTest4.cxx
- Modules/IO/NIFTI/test/itkNiftiReadAnalyzeTest.cxx
- Modules/IO/PhilipsREC/src/itkPhilipsRECImageIO.cxx
- Modules/IO/Siemens/src/itkSiemensVisionImageIO.cxx
This PR is a WIP, and more details will be added here when ready for discussion and review.
See #4788 for this issue and discussion of these changes.
> Add AnatomicalOrientation class

- Modules/Registration/Metricsv4/test/itkEuclideanDistancePointSetMetricRegistrationTest.cxx
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4881 commit 569a8b6fe9e3945c46e13f7b21e5512ebd61afaf
"STYLE: Replace Fill(0) with {} initializer for local variables in tests"
> STYLE: Replace `Fill(static_cast<RealType>(0.0))` with `{}` in test

- Modules/Core/Common/include/itkMatrix.h
- Modules/Core/Common/test/itkMatrixGTest.cxx
Forwarded iterators and `size()` from its internal `m_Matrix`. This commit enables calling `itk::MakeFilled<MatrixType>(fillValue)` to create a filled matrix.
> ENH: Add STL-style iterators and size() member function to `itk::Matrix`

- Modules/Core/Common/wrapping/test/itkPointSetSerializationTest.py
- Modules/Core/Mesh/wrapping/test/itkMeshSerializationTest.py
- The SetPoints calls in two serialization tests appear unsafe, as was reported by issue #4848
With this commit, those tests try both using SetPointsByCoordinates and using the unsafe SetPoints overload.
----
- This pull request aims to supersede pull request #4889 as it is triggered by feedback from Matt McCormick (@thewtex) at https://github.com/InsightSoftwareConsortium/ITK/pull/4889#discussion_r1809051908
👉  It may be helpful to ignore white-space changes, when reviewing: https://github.com/InsightSoftwareConsortium/ITK/pull/4896/files?w=1
> ENH: Test Python wrapping with both SetPoints and SetPointsByCoordinates

- Modules/Core/Transform/test/itkRigid3DPerspectiveTransformTest.cxx
- Modules/Core/Transform/test/itkTransformTest.cxx
When a variable of type `OptimizerParameters` or `VariableLengthVector` is just default-constructed, it is entirely empty, and `Fill` has no effect at all. (It's different from an empty glass, in real life, that becomes non-empty when it is being filled 🍷.  )
> Do not `Fill` default-constructed empty local variables in tests

- Modules/IO/PhilipsREC/src/itkPhilipsRECImageIO.cxx
Addresses compilation errors on optional module.
> COMP: Fix AnatomicalOrientation Enum

- Modules/Registration/Metricsv4/test/itkImageToImageMetricv4RegistrationTest.cxx
- Modules/Registration/Metricsv4/test/itkObjectToObjectMultiMetricv4RegistrationTest.cxx
These matrices were just filled with `1`, but never used afterwards.
This commit prevents "unused variable" warnings, which would occur when the matrices would be filled during their initialization, instead of by calling the `Fill` member function.
----
- Addresses warnings from https://open.cdash.org/viewBuildError.php?type=1&buildid=9983771 (triggered by pull request #4891) saying _warning: unused variable 'direction' [-Wunused-variable]_
> STYLE: Remove unused "one-filled" `direction` matrices from tests

- Modules/Core/Common/include/itkPoint.hxx
- Modules/Core/ImageFunction/include/itkCentralDifferenceImageFunction.hxx
- Modules/Core/SpatialObjects/include/itkPointBasedSpatialObject.hxx
- Modules/Core/SpatialObjects/include/itkSpatialObject.hxx
- Modules/Core/SpatialObjects/include/itkTubeSpatialObject.hxx
- Modules/Filtering/ImageFusion/include/itkLabelMapContourOverlayImageFilter.hxx
- Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.hxx
- Modules/Numerics/Optimizersv4/include/itkObjectToObjectMetric.hxx
- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.hxx
Using Notepad++, Replace in Files, doing:
Find what: ^( [ ]+[^ ].* )(\w+);[\r\n]+ [ ]+\2\.Fill\(.*{}\);
Replace with: $1$2{};
Directory: D:\Src\ITK\Modules
- Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4897 commit 47335501a5a16c6eb42538a829d4b49229284dd6
"STYLE: Replace `Fill(0)` on local variables with `{}` initialization"
> STYLE: Replace `Fill(T{})` on local variables with `{}` initialization

- Modules/IO/MeshBase/include/itkMeshIOTestHelper.h
Proposed style changes to itkMeshIOTestHelper.h:
- Remove `Fill` calls on empty local variables (as in pull request #4898)
- Replace other `Fill` calls with `auto var = itk::MakeFilled<T>` (as in pull request #4891)
> Remove `Fill` on empty variables, replace other `Fill` calls with `itk::MakeFilled`, in MeshIOTestHelper

- Modules/ThirdParty/DCMTK/CMakeLists.txt
Exported targets now have the DCMTK namespace as of DCMTK/dcmtk@c684bb3.
> [!NOTE]
> Pull request submitted on behalf of @jamesobutler based on work associated with [jamesobutler/ITK@DCMTK-targets](https://github.com/jamesobutler/ITK/tree/DCMTK-targets) and done in the context of https://github.com/Slicer/Slicer/pull/6709
---------------
> COMP: Update DCMTK targets based on new DCMTK namespace

- Modules/Core/Common/test/itkPointSetGTest.cxx
Tests that `PointSet::Graft` just copies the *pointers* to the points and the data. It does not do a "deep copy".
> ENH: Add `PointSet.GraftDoesShallowCopy` GoogleTest unit test

- Modules/Bridge/NumPy/include/itkPyBuffer.h
- Modules/Bridge/NumPy/include/itkPyBuffer.hxx
- Modules/Bridge/NumPy/wrapping/PyBuffer.i.in
Aims to make the difference clearer between the C++ `itk::PyBuffer` member
function (which only supports contiguous arrays as input) and the Python method
`itkPyBuffer.GetImageViewFromArray` (which supports *both* contiguous and
non-contiguous arrays).
The new name of the member function is more Pythonic (using snake case), but it
is also more in accordance with the C++ standard (which reserves identifiers
that begin with an underscore, followed by an uppercase letter).
- Follow-up to pull request #4888
> STYLE: Rename _GetImageViewFromArray to _get_image_view_from_contiguous_array

- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
I have seen this warning message 100s of thousands of time while working with large chest X-ray data sets.
These is not problem to "warn" about the image loads as expected.
> ENH: remove repetitive monochorme1 warning

- Modules/Core/QuadEdgeMesh/test/itkQuadEdgeMeshCellInterfaceTest.cxx
- Modules/Filtering/LabelMap/include/itkLabelObjectLine.h
- Modules/Filtering/LabelMap/test/itkLabelObjectLineComparatorTest.cxx
- Modules/Filtering/LabelMap/test/itkLabelObjectLineTest.cxx
- Modules/Filtering/Thresholding/test/itkThresholdImageFilterTest.cxx
Following C++ Core Guidelines, Oct 3, 2024, ["Prefer scoped objects, don’t heap-allocate unnecessarily"](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r5-prefer-scoped-objects-dont-heap-allocate-unnecessarily)
> Place various objects in tests on the stack, instead of on the heap

- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
- Modules/IO/GDCM/test/itkGDCMImageIOTest2.cxx
When non DICOM and non standard ITK tags are in the metadata dictionary, issue a warning. This addresses the common mistake of using the comma as a separator in the group-element key instead of the pipe, which is what ITK/GDCM uses. These metadata dictionary entries were silently ignored. The warning should provide the user with a hint about what is happening.
> ENH: Change from Debug to Warning macro.

- Modules/Numerics/Optimizers/include/itkMultipleValuedNonLinearVnlOptimizer.h
- Modules/Numerics/Optimizers/include/itkSingleValuedNonLinearVnlOptimizer.h
- Modules/Numerics/Optimizers/src/itkMultipleValuedNonLinearVnlOptimizer.cxx
- Modules/Numerics/Optimizers/src/itkSingleValuedNonLinearVnlOptimizer.cxx
- Modules/Numerics/Optimizersv4/include/itkSingleValuedNonLinearVnlOptimizerv4.h
- Modules/Numerics/Optimizersv4/src/itkSingleValuedNonLinearVnlOptimizerv4.cxx
Defaulted the corresponding Optimizer destructors.
Following C++ Core Guidelines, Oct 3, 2024, ["Use `unique_ptr` or `shared_ptr` to avoid forgetting to `delete` objects created using `new`"](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-smart)
> STYLE: Use `unique_ptr` for m_CostFunctionAdaptor members in Optimizers

- Modules/Core/Common/include/itkShapedFloodFilledFunctionConditionalConstIterator.hxx
- Modules/Core/Transform/include/itkScaleTransform.hxx
- Modules/Filtering/BinaryMathematicalMorphology/include/itkObjectMorphologyImageFilter.hxx
- Modules/Filtering/Convolution/include/itkConvolutionImageFilter.hxx
- Modules/Filtering/Convolution/include/itkMaskedFFTNormalizedCorrelationImageFilter.hxx
- Modules/Filtering/DisplacementField/include/itkDisplacementFieldToBSplineImageFilter.hxx
- Modules/Filtering/FastMarching/include/itkFastMarchingImageFilter.hxx
- Modules/Filtering/FastMarching/include/itkFastMarchingImageFilterBase.hxx
- Modules/Filtering/ImageFeature/include/itkCannyEdgeDetectionImageFilter.hxx
- Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.hxx
- Modules/Filtering/MathematicalMorphology/include/itkBinaryCrossStructuringElement.h
- Modules/Nonunit/Review/include/itkMultiphaseFiniteDifferenceImageFilter.h
- Modules/Numerics/Statistics/include/itkScalarImageToCooccurrenceListSampleFilter.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx
- Modules/Segmentation/LevelSets/include/itkSegmentationLevelSetImageFilter.h
- Modules/Segmentation/LevelSetsv4/include/itkBinaryImageToLevelSetImageAdaptor.hxx
- Modules/Segmentation/LevelSetsv4/include/itkUpdateMalcolmSparseLevelSet.hxx
- Modules/Segmentation/LevelSetsv4/include/itkUpdateShiSparseLevelSet.hxx
- Modules/Segmentation/LevelSetsv4/include/itkUpdateWhitakerSparseLevelSet.hxx
Suggests evaluating its value at compile-time, rather than at runtime.
Found by regular expressions:
^( [ ]+)(auto \w+[ ]+= MakeFilled<.+>\(-?\d+\);)
^( [ ]+)(auto \w+[ ]+= MakeFilled<.+>\(\d.0\);)
^( [ ]+)(auto \w+[ ]+= MakeFilled<.+>\(false\);)
^( [ ]+)(auto \w+[ ]+= MakeFilled<.+>\(true\);)
Inspired by a comment by Hans Johnson (@hjmjohnson) at
https://github.com/InsightSoftwareConsortium/ITK/pull/4924#discussion_r1826864385
> STYLE: Add constexpr to variables initialized by MakeFilled

- Documentation/docs/contributing/build_test_itk.md
- pyproject.toml
Call `pixi run python-exe` to run a python interpreter with the locally built `itk` Python package.
Facilitates development and debugging.
I used this in testing / debugging #4895.
> Pixi python-exe task

- Documentation/docs/contributing/index.md
`git pull` should not have a slash between the remote and branch.
`git push` for the `release` branch update had the wrong branch.
> DOC: Command fixes for release branch merges

- Documentation/docs/migration_guides/itk_6_migration_guide.md
- Modules/Core/Common/include/itkPointSet.h
- Modules/Core/Common/include/itkPointSet.hxx
- Modules/Core/Common/include/itkPointSetBase.h
- Modules/Core/Common/include/itkPointSetBase.hxx
- Modules/Core/Common/test/itkPointSetGTest.cxx
Implemented InternalClone() for PointSet and PointSetBase, in order to let `PointSet::Clone()` and `PointSetBase::Clone()` do a deep copy of its points and point data.
----
- Following the suggestion from Bradley (@blowekamp) to override InternalClone(), at https://github.com/InsightSoftwareConsortium/ITK/pull/4923#discussion_r1824841850
- Intended to supersede  pull request #4923
> ENH: Let `PointSet::Clone()` do a "deep copy", instead of no copy at all

- Wrapping/Generators/Python/Tests/PythonTemplateTest.py
- Wrapping/Generators/Python/Tests/extras.py
- Wrapping/Generators/Python/itk/support/extras.py
- Wrapping/Generators/Python/itk/support/helpers.py
- Wrapping/Generators/Python/itk/support/template_class.py
Dispatch Python filter types based on the type of the first ProcessObject RequiredInputName, which is exposed in Python via GetRequiredInputName and which can be the ProcessObject PrimaryInputName.
This helps to address uses cases such as
`itk.elastix_registration_method`, where you still want to infer the filter type based on the input fixed image type, but it may be passed in as a keyword argument, such as
`itk.elastix_registration_method(moving_image=moving_image, fixed_image=fixed_image)`.
Re: #4858 https://github.com/InsightSoftwareConsortium/ITKElastix/issues/212
> ENH: Python dispatch on the first RequiredInputName

- Modules/Core/Common/test/itkLineIteratorTest.cxx
- Modules/Core/GPUCommon/src/itkOpenCLUtil.cxx
- Modules/IO/CSV/test/itkCSVArray2DFileReaderTest.cxx
- Modules/IO/ImageBase/src/itkArchetypeSeriesFileNames.cxx
- Modules/IO/MINC/src/itkMINCImageIO.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest.h
- Modules/IO/NIFTI/test/itkNiftiImageIOTest3.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest4.cxx
- Modules/IO/XML/test/itkDOMTest6.cxx
- Modules/Numerics/NarrowBand/test/itkNarrowBandTest.cxx
- Modules/Numerics/Statistics/test/itkScalarImageToCooccurrenceListSampleFilterTest.cxx
For Standard Library types that have a non-trivial default-constructor and a non-trivial assignment operator, `T var = x` is typically slightly faster than `T var; var = x`. Otherwise it's just a matter of style.
Using Notepad++, Replace in Files, doing:
Find what: ^( [ ]+)(std::[^ ]*)([ ]+)(\w+);[\r\n]+\1\4\ =
Replace with: $1$2$3$4 =
Filters: itk*.*
Directory: D:\src\ITK\Modules
[v] Match case
- Follow-up to pull request #4932 commit 5b121f493f17d61c52c197b0c5df530fe01c4f8c
> STYLE: Replace `T var; var = x` with `T var = x` for types from `std`

- Modules/Core/Common/include/itkDerivativeOperator.h
- Modules/Core/Common/include/itkLaplacianOperator.hxx
- Modules/Core/Common/include/itkSobelOperator.h
- Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.h
- Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.hxx
- Modules/Core/Transform/include/itkBSplineDeformableTransform.hxx
- Modules/Core/Transform/include/itkBSplineTransform.hxx
- Modules/Filtering/Denoising/include/itkPatchBasedDenoisingImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkContourDirectedMeanDistanceImageFilter.hxx
- Modules/Filtering/FastMarching/include/itkFastMarchingImageFilterBase.hxx
- Modules/Filtering/ImageFeature/include/itkCannyEdgeDetectionImageFilter.hxx
- Modules/Filtering/ImageFeature/include/itkMaskFeaturePointSelectionFilter.hxx
- Modules/Nonunit/Review/include/itkAttributeMorphologyBaseImageFilter.hxx
- Modules/Numerics/FEM/include/itkFEMSolver.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkTimeVaryingBSplineVelocityFieldImageRegistrationMethod.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkTimeVaryingVelocityFieldImageRegistrationMethodv4.hxx
- Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentFunctorImageFilter.hxx
- Modules/Segmentation/SuperPixel/include/itkSLICImageFilter.hxx
- Modules/Segmentation/Watersheds/include/itkMorphologicalWatershedFromMarkersImageFilter.hxx
- Follow-up to pull request #4930
> Add `constexpr` to variables initialized by `T::Filled(x)`

- Modules/Core/Common/include/itkMath.h
- Modules/Core/Common/include/itkTriangleCell.hxx
- Modules/Core/TestKernel/include/itkTestingComparisonImageFilter.hxx
- Modules/Filtering/ImageFeature/include/itkBilateralImageFilter.hxx
- Modules/Numerics/FEM/src/itkFEMElement2DC0LinearLine.cxx
- Modules/Registration/Common/include/itkEuclideanDistancePointMetric.hxx
Aims to make the code clearer. Cases found by regular expressions like ` (\w+) = -\1;` and ` \w+ \*= -1;`
Removed old comments from inside two `DistanceToLine` member functions, saying that they are "trying to avoid an expensive fabs". `std::abs` isn't that expensive anymore nowadays.
> STYLE: Use `std::abs`, instead of doing `if (x < 0) x = -x` manually

- Documentation/docs/contributing/index.md
- Modules/ThirdParty/DoubleConversion/UpdateDoubleConversionFromGoogle.sh
> Double convert 3.3.0

- Modules/Filtering/Thresholding/test/itkThresholdImageFilterTest.cxx
This is to work around build failures on Intel macOS:
> Filtering/Thresholding/test/itkThresholdImageFilterTest.cxx:79:8: error: no viable overloaded '='
os = {};
~~ ^ ~~
Also, it is more efficient to clear the std::ostringstream
object using os.str(""); rather than reinitializing it. This avoids
unnecessary reallocation and keeps the code cleaner.
> COMP: Avoid re-init of ostringstream in ThresholdImageFilterTest

- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
- Modules/IO/ImageBase/include/itkImageSeriesReader.hxx
Dicom files that do not have explicit "SliceThickness" listed can still be used.  The actual "spacing between slices" is computed from the stack of slices when multiple dicoms are provided such that the initial setting of the "SliceThickness" placeholder is not used.  (NOTE: SliceThickness is used when a single slice is read into a 3D image).
This fixes an issue when a stack of 124 dicom slices does not have "SliceThickness" fields, but does have "ImagePositionPatient" for each slice. 
The previous implementation would throw an exception prior to getting to the code that explicitly computes the slice space from the "ImagePositionPatient" values.
The new code now allows ITK to make 3D nifti volumes that are compatible with those created by the dcm2niix package.
> ENH: Fix dicom reading slices

- Modules/Core/Common/include/itkAnatomicalOrientation.h
To keep the other legacy options enabled. Closes #4950.
> COMP: Exclude AnatomicalOrientation::FromEnum warning when wrapping

- Modules/ThirdParty/TIFF/src/itktiff/tif_config.h.in
Extend the condition from commit 08bf6bec432 (COMP: Conditionalize insane "#define inline" in libtiff, 2013-10-07, v4.5rc01~139^2). Newer MSVC versions need it to avoid duplicating `__ucrt_int_to_float`.
Issue: #4820
> COMP: itktiff: Suppress C99 inline only on MSVC from VS 2013 and below - For Release Branch

- Modules/IO/ImageBase/include/itkImageSeriesReader.hxx
This reverts commit 916a40cb3cebf817f91b69ef80a428b346c46fef.
The strict tolerance is required for backward compatibility.
The commit 916a40cb3cebf817f91b69ef80a428b346c46fef caused an undesirable regression in end-user application, and was not necessary for fixing the problem described in #4955
> Revert "BUG: Reduce tolerance for same slice checks"

- Examples/DataRepresentation/Mesh/AutomaticMesh.cxx
- Examples/Filtering/DiffusionTensor3DReconstructionImageFilter.cxx
- Examples/Filtering/OrientImageFilter.cxx
- Examples/IO/DicomPrintPatientInformation.cxx
- Examples/IO/DicomSeriesReadImageWrite.cxx
- Examples/IO/XML/DOMFindDemo.cxx
- Examples/Iterators/NeighborhoodIterators6.cxx
- Examples/RegistrationITKv4/DeformableRegistration1.cxx
- Examples/RegistrationITKv4/DeformableRegistration11.cxx
- Examples/RegistrationITKv4/ImageRegistration10.cxx
- Examples/RegistrationITKv4/ImageRegistration19.cxx
- Examples/Segmentation/LaplacianSegmentationLevelSetImageFilter.cxx
- Examples/Statistics/ImageToListSampleAdaptor.cxx
- Examples/Statistics/PointSetToAdaptor.cxx
- Follow-up to pull request #4964
Triggered by a comment by Bradley Lowekamp (@blowekamp) at https://github.com/InsightSoftwareConsortium/ITK/pull/4964#issuecomment-2488760839
> Modernize initialization of local SmartPointer variables in Examples

- Modules/Filtering/ImageFilterBase/include/itkMovingHistogramImageFilterBase.hxx
- Modules/Filtering/ImageStatistics/include/itkLabelStatisticsImageFilter.hxx
- Modules/Filtering/MathematicalMorphology/include/itkSharedMorphologyUtilities.hxx
- Modules/Nonunit/Review/include/itkLabelGeometryImageFilter.hxx
- Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.hxx
- Modules/Nonunit/Review/include/itkWarpHarmonicEnergyCalculator.hxx
- Modules/Numerics/Statistics/include/itkImageToNeighborhoodSampleAdaptor.hxx
- Modules/Segmentation/ConnectedComponents/include/itkConnectedComponentFunctorImageFilter.hxx
- Follow-up to pull request #4964
> Modernize initialization of local iterators, replacing `IteratorType it; it = <expression>`

- Modules/Core/Transform/include/itkBSplineTransformInitializer.hxx
- Modules/Filtering/BiasCorrection/include/itkN4BiasFieldCorrectionImageFilter.hxx
- Modules/Filtering/DisplacementField/include/itkDisplacementFieldToBSplineImageFilter.hxx
- Modules/Filtering/FastMarching/include/itkFastMarchingImageToNodePairContainerAdaptor.hxx
- Modules/Numerics/Optimizersv4/include/itkWindowConvergenceMonitoringFunction.hxx
- Modules/Registration/Common/include/itkLandmarkBasedTransformInitializer.hxx
- Modules/Registration/Metricsv4/include/itkLabeledPointSetToPointSetMetricv4.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkBSplineSyNImageRegistrationMethod.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkImageRegistrationMethodv4.hxx
- Modules/Registration/RegistrationMethodsv4/include/itkTimeVaryingBSplineVelocityFieldImageRegistrationMethod.hxx
- Modules/Segmentation/Classifiers/include/itkBayesianClassifierInitializationImageFilter.hxx
For any ITK type `T`, `T::New()` does already initialize the object it returns.
Using Notepad++, Replace in Files, doing:
Find what:  (\w+)([ ]+= .+::New\(\);)\r\n[\r\n]* [ ]+\1->Initialize\(\);
Replace with:  $1$2
Filters: itk*.* !+\test
Directory: D:\src\ITK\Modules
[v] Match case
Manually removed an obsolete comment saying `Clear elements`.
> STYLE: Remove `p->Initialize()` calls directly after `p = T::New()`

- Modules/ThirdParty/TIFF/CMakeLists.txt
- Modules/ThirdParty/TIFF/src/itk_tiff.h.in
- Modules/ThirdParty/TIFF/src/itktiff/itk_tiff_mangle.h
- Modules/ThirdParty/TIFF/src/itktiff/tiffio.h
The update libtiff now has include that are specified as library properties and not full by ITK cmake variables.
> BUG: Update libtiff's ITK module include paths

- Modules/Segmentation/Voronoi/include/itkVoronoiSegmentationRGBImageFilter.hxx
Simplify the code by returning as soon as the condition is known to be false.
Remove unnecessary "ok" temporary variable.
> STYLE: Remove extra processing return quickly when result is known

- Modules/Numerics/Statistics/test/itkScalarImageToTextureFeaturesFilterTest.cxx
Finds and replaces integer literals which are cast to bool.
cd ${BLDDIR}
run-clang-tidy.py -extra-arg=-D__clang__ -checks=-*,modernize-use-bool-literals  -header-filter=.* -fix
> STYLE: Replace integer literals which are cast to bool.

- Modules/IO/GDCM/include/itkGDCMImageIO.h
- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
- Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx
- Modules/IO/GDCM/test/itkGDCMImageIONoCrashTest.cxx
Remove support for system installed versions of GDCM that are more than 10 years old.
This simplifies the codebase for code that has likely not been explicitly tested in a very long time.
> STYLE: Remove support for 10+ year old GDCM

- Modules/Filtering/LabelMap/test/itkBinaryReconstructionLabelMapFilterTest.cxx
- Modules/IO/MeshVTK/test/itkMeshFileWriteReadTensorTest.cxx
- Modules/IO/PhilipsREC/src/itkPhilipsRECImageIO.cxx
- Modules/IO/SpatialObjects/src/itkPolygonGroupSpatialObjectXMLFile.cxx
- Modules/IO/TransformInsightLegacy/src/itkTxtTransformIO.cxx
- Modules/Video/IO/include/itkVideoFileWriter.hxx
The emptiness of a container should be checked using the empty() method instead of the size() method. It is not guaranteed that size() is a constant-time function, and it is generally more efficient and also shows clearer intent to use empty(). Furthermore some containers may implement the empty() method but not implement the size() method. Using empty() whenever possible makes it easier to switch to another container in the future.
cd ${BLDDIR}
run-clang-tidy.py -extra-arg=-D__clang__ -checks=-*,readability-container-size-empty  -header-filter=.* -fix
> PERF: readability container size empty

- Wrapping/Generators/Python/CMakeLists.txt
cmake 3.31 does an implicit conversion of paths like:
/myvenv/site-packages//itk --> /myvenv/site-packages/itk
^^                             ^
which produces many warnings like:
```txt
ITKCommon: Creating itkAnatomicalOrientation submodule.
CMake Warning (dev) at Wrapping/Generators/Python/CMakeLists.txt:88 (install):
Policy CMP0177 is not set: install() DESTINATION paths are normalized.  Run
"cmake --help-policy CMP0177" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
Wrapping/Generators/Python/CMakeLists.txt:305 (wrap_itk_python_bindings_install)
Wrapping/Generators/Python/CMakeLists.txt:380 (itk_setup_swig_python)
Wrapping/macro_files/itk_auto_load_submodules.cmake:328 (itk_end_wrap_submodule_python) …
```
> COMP: Improve path management for python package install

- Modules/Filtering/BinaryMathematicalMorphology/include/itkObjectMorphologyImageFilter.hxx
Move copying input to output to before threaded methods, to ensure the operation has been completed before modifications.
Addresses #4969 
> BUG: Address race condition with threaded copying input to output

- Modules/IO/GDCM/include/itkGDCMImageIO.h
- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
Addresses warning about undefined GDCM_MAJOR_VERSION.
> COMP: Move GDCM version check to cxx file

- Wrapping/Generators/Python/PyUtils/itkPyCommand.wrap
This is appearing again, which means that previous solution was not thorough enough: https://github.com/InsightSoftwareConsortium/ITK/pull/4829
Sample error message:
```log
28>------ Build started: Project: ITKPyUtilsCastXML, Configuration: RelWithDebInfo x64 ------ 28>Generating ../../../castxml_inputs/itkPyCommand.xml 28>C:/Dev/ITK-py22/Wrapping/castxml_inputs/itkPyCommand.cxx:16:10: fatal error: 'itkPyCommand.h' file not found
28>   16 | #include "itkPyCommand.h"
28>      |          ^~~~~~~~~~~~~~~~
28>1 error generated.
```
> COMP: Fix 'itkPyCommand.h' file not found

- Examples/DataRepresentation/Mesh/MeshTraits.cxx
- Examples/SpatialObjects/MeshSpatialObject.cxx
- Examples/Statistics/PointSetToListSampleAdaptor.cxx
Addressed a compile error at Mac12.x-AppleClang-dbg-Universal saying:
> MeshSpatialObject.cxx:66:13: error: no type named 'CoordRepType' in
> 'itk::Mesh<float, 3, itk::DefaultDynamicMeshTraits<float, 3>>'
Reported by Jon Haitz Legarreta Gorroño (@jhlegarreta) at https://github.com/InsightSoftwareConsortium/ITK/pull/4997#issuecomment-2508979579
- Follow-up to pull request #4997 commit 15d189f513ac63e3cafc77a58b39c8862ce6e844
"STYLE: Replace CoordRepType with CoordinateType in ITK implementation"
> COMP: Replace "CoordRep" with "Coordinate" in Examples

- Modules/Core/Common/test/itkConicShellInteriorExteriorSpatialFunctionTest.cxx
- Modules/Core/Common/test/itkFrustumSpatialFunctionTest.cxx
- Modules/Core/Common/test/itkTorusInteriorExteriorSpatialFunctionTest.cxx
- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshToQuadEdgeMeshFilter.h
- Modules/Core/Transform/include/itkBSplineTransformInitializer.h
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkBorderQuadEdgeMeshFilter.h
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkBorderQuadEdgeMeshFilter.hxx
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkCleanQuadEdgeMeshFilter.h
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkCleanQuadEdgeMeshFilter.hxx
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkDelaunayConformingQuadEdgeMeshFilter.h
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkLaplacianDeformationQuadEdgeMeshFilter.h
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkLaplacianDeformationQuadEdgeMeshFilter.hxx
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkLaplacianDeformationQuadEdgeMeshFilterWithHardConstraints.h
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkLaplacianDeformationQuadEdgeMeshFilterWithHardConstraints.hxx
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkLaplacianDeformationQuadEdgeMeshFilterWithSoftConstraints.h
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkLaplacianDeformationQuadEdgeMeshFilterWithSoftConstraints.hxx
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkParameterizationQuadEdgeMeshFilter.h
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkParameterizationQuadEdgeMeshFilter.hxx
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkQuadEdgeMeshParamMatrixCoefficients.h
- Modules/Filtering/QuadEdgeMeshFiltering/test/itkCleanQuadEdgeMeshFilterTest.cxx
- Modules/Filtering/QuadEdgeMeshFiltering/test/itkLaplacianDeformationQuadEdgeMeshFilterWithSoftConstraintsTest.cxx
- Modules/IO/MeshBase/include/itkMeshFileReader.h
- Modules/Nonunit/Review/include/itkMultiphaseFiniteDifferenceImageFilter.h
- Modules/Registration/FEM/include/itkFEMRegistrationFilter.hxx
Triggered by a comment from Hans (@hjmjohnson) at https://github.com/InsightSoftwareConsortium/ITK/pull/4999#pullrequestreview-2472588270
- Follow-up to pull request #4997
> Deprecate `...CoordRepType` and replace them with `...CoordinateType`

- CMake/ITKSetPython3Vars.cmake
- Documentation/docs/contributing/python_packaging.md
- Wrapping/macro_files/itk_end_wrap_module.cmake
- pixi.lock
Python 3.8 has reached it's end-of-life.
Use cmake find_package version range limits for
valid versions of python to enforce the lower
bound of 3.9.
> ENH: Force python 3.9 or greater compliance.

- Modules/ThirdParty/GDCM/src/gdcm/CMakeLists.txt
Use cmake_minimum_required to set min and policy_max
CMake version >3.30 produce a deprecated awarning when only, a min
argument less that 3.10 is pass to cmake_minimum_required. Using the
additional policy_max version range specified the max policy setting
at the same time.
> COMP: GDCM: fix CMake Deprecation Warning

- Modules/Core/Common/include/itkImageRegion.h
- Modules/Core/Common/test/itkImageRegionTest.cxx
- Modules/Filtering/ImageGrid/include/itkInterpolateImagePointsFilter.h
- Modules/Filtering/ImageGrid/include/itkInterpolateImagePointsFilter.hxx
- Modules/Segmentation/Voronoi/include/itkVoronoiDiagram2D.h
- Modules/Segmentation/Voronoi/include/itkVoronoiDiagram2D.hxx
- Modules/Segmentation/Voronoi/include/itkVoronoiDiagram2DGenerator.h
- Modules/Segmentation/Voronoi/include/itkVoronoiDiagram2DGenerator.hxx
The postfix `Type` is unnecessary for a template parameter `TCoordinateType`, because its initial `T` already indicates that it is a type.
On the other hand, a type alias (typedef) "typically" has a `Type` postfix, but should _not_ have a `T` initial.
Triggered by a comment from Jon (@jhlegarreta) at https://github.com/InsightSoftwareConsortium/ITK/pull/4995#issuecomment-2504978482
> Remove "Type" from `TCoordinateType` template parameters, remove initial "T" from `TCoordinateType` alias

- Modules/ThirdParty/KWSys/src/KWSys/CMakeLists.txt
- Modules/ThirdParty/KWSys/src/KWSys/Configure.hxx.in
- Modules/ThirdParty/KWSys/src/KWSys/Directory.cxx
- Modules/ThirdParty/KWSys/src/KWSys/ProcessUNIX.c
- Modules/ThirdParty/KWSys/src/KWSys/ProcessWin32.c
- Modules/ThirdParty/KWSys/src/KWSys/RegularExpression.cxx
- Modules/ThirdParty/KWSys/src/KWSys/RegularExpression.hxx.in
- Modules/ThirdParty/KWSys/src/KWSys/SystemInformation.cxx
- Modules/ThirdParty/KWSys/src/KWSys/SystemTools.cxx
- Modules/ThirdParty/KWSys/src/KWSys/SystemTools.hxx.in
- Modules/ThirdParty/KWSys/src/KWSys/testConsoleBuf.cxx
https://gitlab.kitware.com/utils/kwsys.git
at commit `dfbcd769aea25157ee65a92f941d0e233fe79826` (master).
Upstream Shortlog
-----------------
```
Brad King (9):
beaf1ca1 ConsoleBuf: Fix test case when running under Windows Terminal
4feb470a SystemTools: Remove GetActualCaseForPath from CollapseFullPath
6e847d08 SystemInformation: Add missing EOF check when reading /proc/cpuinfo
741c9c96 SystemTools: Expose GetActualCaseForPathCached publicly
fdf4f2f8 SystemTools: Fix ReadSymlink for links to absolute paths on Windows
20b2c992 SystemTools: Remove unused global object
47dce1a3 SystemTools: Remove path translation map
30e9db2d SystemTools: Drop GetActualCaseForPathCached
5995fd7d SystemInformation: Ignore stderr from OS query tools
Daniel Pfeifer (1):
68e1f35d …
```
> KWSys: Update to version as of 2024-11-30

- Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
We now require 3.9 -- 3.8 is end-of-life.
> COMP: Update Azure Windows Python version to 3.11

- Modules/Core/Common/include/itkQuadrilateralCell.hxx
- Modules/Core/Common/include/itkSymmetricEigenAnalysis.hxx
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkParameterizationQuadEdgeMeshFilter.hxx
- Modules/IO/JPEG2000/src/itkJPEG2000ImageIO.cxx
- Utilities/GitSetup/setup-precommit
- Utilities/SetupForDevelopment.sh
- pixi.lock
- pyproject.toml
On Windows, Python is not available by default. The SetupForDevelopment.sh script does not complete successfully in a default build on Windows.
This uses pixi to install pre-commit, python for pre-commit, so the contribution experience works out-of-the-box for experienced and new contributors to ITK.
This also improves the isolation and maintainability of pre-commit tooling. Everything needed for a commit is local to the ITK repository. We also get more reproducible versions of Python and pre-commit via pixi's configuration in pyproject.toml and pixi.lock.
pixi is a self-contained, single-file, cross-platform Rust binary. A local version is installed to .git/hooks/pixi/bin/pixi. Pixi's python and pre-commit is installed to .pixi/.
The installation of tools is:
SetupForDevelopment.sh -> …
> ENH: Use pixi to install pre-commit, python for pre-commit

- .github/workflows/macos-arm.yml
- .github/workflows/pixi.yml
Grouping based on github.event.pull_request.head.sha, i.e. "the commit ID for the last commit to the head branch of the pull request" only cancels commits with the same SHA. With this PR, on-going workflows of the same PR would be cancelled.
See https://github.com/InsightSoftwareConsortium/ITK/pull/5019#issuecomment-2536179053.
> BUG: GHA: Cancel-in-progress event if not the same head SHA

- Modules/Core/Common/include/itkByteSwapper.h
- Modules/Core/Common/include/itkConstNeighborhoodIterator.h
- Modules/Core/Common/include/itkImageIORegion.h
- Modules/Core/Common/include/itkNeighborhoodIterator.h
- Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.h
- Modules/Core/Mesh/include/itkTriangleMeshCurvatureCalculator.h
- Modules/Core/SpatialObjects/include/itkMetaConverterBase.h
- Modules/Core/SpatialObjects/include/itkSpatialObject.h
- Modules/Core/TestKernel/include/itkTestDriverInclude.h
- Modules/Core/TestKernel/include/itkTestDriverIncludeRequiredFactories.h
- Modules/Filtering/DistanceMap/include/itkDirectedHausdorffDistanceImageFilter.h
- Modules/Filtering/FFT/include/itkForward1DFFTImageFilter.h
- Modules/Filtering/FFT/include/itkInverse1DFFTImageFilter.h
- Modules/Filtering/Path/include/itkContourExtractor2DImageFilter.h
- Modules/Registration/Common/include/itkImageToImageMetric.h
- Modules/Segmentation/LevelSetsv4/include/itkLevelSetEvolution.h
- Modules/Video/Core/include/itkImageToVideoFilter.h
Enforce consistency in large projects, where it often happens that a definition of a function is refactored, changing the parameter names, but its declaration in the header file is not updated. With this check, we can easily find and correct such inconsistencies, keeping declaration and definition always in sync.
Unnamed parameters are allowed and are not taken into account when comparing function declarations.
> STYLE: Make prototype match definition names

- Modules/Core/Common/wrapping/test/CMakeLists.txt
- Modules/Core/Common/wrapping/test/itkPointSetTest.py
Specifically tested `SetPointsByCoordinates` with a NumPy array as input argument, as was suggested by @PranjalSahu.
- Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4850 commit f43b1b8977fa05d169c14b4c6f44ce35992a3959
ENH: Add `PointSet::SetPointsByCoordinates(coordinates)`
> ENH: Add "itkPointSetTest.py" unittest, testing `SetPointsByCoordinates`

- Modules/Core/Common/include/itkImageBase.hxx
Short circuit return on first dimension test failure
There is no need to test all dimensions.
> STYLE: Return quickly on first failure

- Modules/Core/ImageFunction/include/itkRayCastInterpolateImageFunction.hxx
- Modules/Core/ImageFunction/test/itkGaussianInterpolateImageFunctionTest.cxx
- Modules/Core/Mesh/test/itkMeshTest.cxx
- Modules/Core/Transform/include/itkCompositeTransform.hxx
- Modules/Core/Transform/test/itkBSplineDeformableTransformTest.cxx
- Modules/Core/Transform/test/itkBSplineTransformTest.cxx
- Modules/Filtering/BiasCorrection/include/itkMRIBiasFieldCorrectionFilter.hxx
- Modules/Filtering/FastMarching/include/itkFastMarchingImageFilterBase.hxx
- Modules/Filtering/ImageFeature/include/itkMaskFeaturePointSelectionFilter.hxx
- Modules/Filtering/ImageGrid/test/itkExpandImageFilterTest.cxx
- Modules/Filtering/ImageGrid/test/itkWarpImageFilterTest.cxx
- Modules/Filtering/Thresholding/test/itkOtsuMultipleThresholdsCalculatorTest.cxx
- Modules/Filtering/Thresholding/test/itkOtsuMultipleThresholdsImageFilterTest.cxx
- Modules/IO/CSV/include/itkCSVArray2DDataObject.hxx
- Modules/IO/GIPL/src/itkGiplImageIO.cxx
- Modules/IO/MINC/test/itkMINCImageIOTest.cxx
- Modules/IO/NRRD/src/itkNrrdImageIO.cxx
- Modules/Numerics/Statistics/include/itkKdTreeBasedKmeansEstimator.hxx
- Modules/Registration/Common/test/itkPointSetToImageRegistrationTest.cxx
- Modules/Registration/Common/test/itkPointSetToPointSetRegistrationTest.cxx
- Modules/Segmentation/DeformableMesh/include/itkDeformableSimplexMesh3DGradientConstraintForceFilter.hxx
Only 1 commit ahead of #5025 
C++11 Range based for loops can be used in
Used as a more readable equivalent to the traditional for loop operating over a
range of values, such as all elements in a container, in the forward direction..
Range based loopes are more explicit for only computing the
end location once for containers.
> STYLE: Use range-based loops from C++11

- Modules/Core/Common/include/itkPointSetBase.h
- Modules/Core/Common/wrapping/test/CMakeLists.txt
- Modules/Core/Common/wrapping/test/itkPointSetTest.py
- Wrapping/Generators/Python/PyBase/pyBase.i
- Wrapping/TypedefMacros.cmake
- STYLE: Use Python in Common python test names
- ENH: Shaped NumPy array input to SetPointsByCoordinates
> pointsetbase set get numpy arrays

- Modules/Remote/IOMeshMZ3.remote.cmake
ITK Mesh IO for the MZ3 format, a simple, small, fast triangle mesh file format.
For more information, see the [MZ3 format specification](https://github.com/neurolabusc/surf-ice/tree/master/mz3).
> ENH: Add ITKIOMeshMZ3 remote module

- Modules/Nonunit/Review/test/itkImageFunctionTest.cxx
Sample error message:
`T:\Dashboard\ITK\Modules\Nonunit\Review\test\itkImageFunctionTest.cxx(137,17): error C2065: 'MakeFilled': undeclared identifier [T:\Dashboard\ITK-build\Modules\Nonunit\Review\test\ITKReviewTestDriver.vcxproj]`
> COMP: Fix compile error due to missing itk:: prefix for MakeFilled

- .pre-commit-config.yaml
- CMake/ITKSetStandardCompilerFlags.cmake
Adding recently added common checks to the ITK
pre-commit checking.
Of note:
no-commit-to-branch
to prevent accidently adding changes to
protected branches.
check-merge-conflict
to bring ghostflow errors to developers
environment before posting as a PR.
> ENH: Activate standard pre-commit hooks

- Examples/RegistrationITKv4/IterativeClosestPoint3.cxx
- Modules/Core/Common/test/itkImageTest.cxx
- Modules/Core/Common/test/itkImageVectorOptimizerParametersHelperTest.cxx
- Modules/Core/ImageFunction/test/itkRayCastInterpolateImageFunctionTest.cxx
- Modules/Filtering/DisplacementField/test/itkInverseDisplacementFieldImageFilterTest.cxx
- Modules/Filtering/DisplacementField/test/itkIterativeInverseDisplacementFieldImageFilterTest.cxx
- Modules/Filtering/DisplacementField/test/itkLandmarkDisplacementFieldSourceTest.cxx
- Modules/Filtering/FastMarching/test/itkFastMarchingImageFilterBaseTest.cxx
- Modules/Filtering/ImageGrid/test/itkBSplineControlPointImageFilterTest.cxx
- Modules/Filtering/ImageGrid/test/itkResampleImageTest.cxx
- Modules/Filtering/ImageGrid/test/itkResampleImageTest7.cxx
- Modules/Filtering/ImageGrid/test/itkResampleImageTest8.cxx
- Modules/Filtering/ImageSources/test/itkGridImageSourceTest.cxx
- Modules/Filtering/ImageSources/test/itkPhysicalPointImageSourceTest.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest.h
- Modules/IO/NIFTI/test/itkNiftiImageIOTest11.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest3.cxx
- Modules/Registration/Metricsv4/test/itkANTSNeighborhoodCorrelationImageToImageMetricv4Test.cxx
- Modules/Registration/Metricsv4/test/itkCorrelationImageToImageMetricv4Test.cxx
- Modules/Registration/Metricsv4/test/itkDemonsImageToImageMetricv4Test.cxx
- Modules/Registration/Metricsv4/test/itkEuclideanDistancePointSetMetricTest2.cxx
- Modules/Registration/Metricsv4/test/itkImageToImageMetricv4Test.cxx
- Modules/Registration/Metricsv4/test/itkJointHistogramMutualInformationImageToImageMetricv4Test.cxx
- Modules/Registration/Metricsv4/test/itkMeanSquaresImageToImageMetricv4OnVectorTest.cxx
- Modules/Registration/Metricsv4/test/itkMeanSquaresImageToImageMetricv4OnVectorTest2.cxx
- Modules/Registration/Metricsv4/test/itkMeanSquaresImageToImageMetricv4SpeedTest.cxx
- Modules/Registration/Metricsv4/test/itkMeanSquaresImageToImageMetricv4Test.cxx
- Modules/Registration/Metricsv4/test/itkMetricImageGradientTest.cxx
The default origin is {0.0,...} and spacing is {1.0,...},
do not reset those values explicitly in tests.
When testing the Get/Set functions, use values other
then the default values.
Prefer initializations of regions with index and size
over explicit assignment calls of SetIndex() and SetSize()
immediately after declaration.
> STYLE: Remove redundant idoms for setting origin/spacing

- Modules/Core/Common/wrapping/test/itkPointSetTest.py
Also check the return value after setting with a flat NumPy array.
In both cases the Get value is expected to have a shape of n_points x
dimension.
> ENH: Test return of GetPointsByCoordinates for set with flat array

- Modules/IO/Meta/src/itkMetaImageIO.cxx
Indexes were incorrectly accessed with pre-increment instead of post-increment
```cpp
#include <iostream>
#include <vector>
int main()
{
std::vector<int> v;
v.push_back(1);
v.push_back(2);
v.push_back(3);
{
unsigned int i = 0;
while (i < v.size() - 1)
{
std::cout << v[++i] << ' '; // wrong
}
std::cout << v[i] << std::endl;
}
{
unsigned int i = 0;
while (i < v.size() - 1)
{
std::cout << v[i++] << ' ';
}
std::cout << v[i] << std::endl;
}
return 0;
}
```
```
r@deb2:~$ ./a.out 
2 3 3
1 2 3
```
Closes #5062
> BUG: Fix ExposeMetaData<std::vector<double>> im MetaImageIO

- Modules/Core/Common/include/itkCovariantVector.h
- Modules/Core/Common/include/itkDiffusionTensor3D.h
- Modules/Core/Common/include/itkFixedArray.h
- Modules/Core/Common/include/itkIndex.h
- Modules/Core/Common/include/itkMatrix.h
- Modules/Core/Common/include/itkMetaDataDictionary.h
- Modules/Core/Common/include/itkOffset.h
- Modules/Core/Common/include/itkPoint.h
- Modules/Core/Common/include/itkRGBAPixel.h
- Modules/Core/Common/include/itkRGBPixel.h
- Modules/Core/Common/include/itkSize.h
- Modules/Core/Common/include/itkSymmetricSecondRankTensor.h
- Modules/Core/Common/include/itkVector.h
The check flags user-defined swap and iter_swap functions not marked with noexcept or marked with noexcept(expr) where expr evaluates to false (but is not a false literal itself).
When a swap or iter_swap function is marked as noexcept, it assures the compiler that no exceptions will be thrown during the swapping of two objects, which allows the compiler to perform certain optimizations such as omitting exception handling code.
> STYLE: performance-noexcept-swap clang-tidy

- Documentation/Maintenance/Release.md
@web3-storage/w3cli no longer uploads symlinks. Commit updates with datalad, then export the repository contents to a new folder with no symlinks. Upload this instead.
Do not document uploading to Kitware's IPFS server or the HTTP server. The former was never properly exposed and the latter is time consuming and unnecessary.
> DOC: Updates for release testing data uploads

- Modules/Core/Common/include/itkDefaultVectorPixelAccessor.h
- Modules/Core/ImageAdaptors/include/itkNthElementPixelAccessor.h
- Modules/Core/ImageAdaptors/include/itkVectorImageToImageAdaptor.h
Initial bug reported in SimpleITK/SimpleITK#2220.
On 64-bit windows system, truncation to 32-bit (unsigned long) was occurring when setting VectorImages with over 4GB buffers.
See #5070 for a WIP test. This test used 8GB memory and needs to ctest memory requirements to ensure there are enough resources.
> BUG: Fix 32-bit truncation on VectorImage Accessor

- Modules/Core/Common/include/itkDefaultVectorPixelAccessor.h
- Modules/Core/ImageAdaptors/include/itkNthElementPixelAccessor.h
- Modules/Core/ImageAdaptors/include/itkVectorImageToImageAdaptor.h
Initial bug reported in SimpleITK/SimpleITK#2220.
On 64-bit windows system, truncation to 32-bit (unsigned long) was occouring when setting VectorImages with over 4GB buffers.
> FOR RELEASE BUG: Fix 32-bit truncation on VectorImage Accessor

- .github/workflows/scorecard.yml
Scans repository for security issues on push to the default branch.
See also:
- https://github.com/ossf/scorecard
- https://github.com/marketplace/actions/ossf-scorecard-action
> ENH: Add OpenSSF Scorecard GitHub Action

- Documentation/docs/migration_guides/itk_6_migration_guide.md
Added note about `CoordRepType` being replaced with `CoordinateType`.
Follow-up to:
- pull request #5006 commit a68b8f67dae4466e6e0450b0be35fb5a81eb2090 "ENH: FUTURE REMOVE `...CoordRepType` in favor of `...CoordinateType`"
- pull request #4997 commit e667fa39a6914d666ae5dd0b47202ebfb2acfd1f "ENH: Deprecate (FUTURE REMOVE) CoordRepType in favor of CoordinateType"
> DOC: Note migration guide replacing `CoordinateType` with `CoordRepType`

- Modules/Core/Common/include/itkGaussianKernelFunction.h
The ivar m_Factor was a constant that did not require state to be saved.  The computation can be done at compile time, thus saving runtime computations.
Move m_Factor from an ivar to a constexpr in the one place it is used.
> PERF: Prefer compiletime computation of scale factor

- Modules/Segmentation/LevelSets/include/itkLevelSetFunction.hxx
Use if constexpr to limit the compilation of code in cases where array index access would fall outside
data structures in cases that should never be used.
Modules/Segmentation/LevelSets/include/itkLevelSetFunction.hxx:138:83: warning: array index 2 is past the end of the array (that has type 'ScalarValueType[2]' (aka 'float[2]')) [-Warray-bounds]
138 |       (gd->m_dx[i0] * gd->m_dx[i0] + gd->m_dx[i1] * gd->m_dx[i1] + gd->m_dx[i2] * gd->m_dx[i2]);
|
> COMP: Limit the 3D specialized function compilation

- CMakeLists.txt
- Examples/DataRepresentation/Image/Image4.cxx
- Modules/Core/Common/include/itkImageAlgorithm.hxx
- Modules/Filtering/ImageSources/test/itkPhysicalPointImageSourceTest.cxx
Need to match precision for types used to allow building.
In a few cases double precision was assumed for values
related to spacing precision.
> COMP: Fix building with ITK_USE_FLOAT_SPACE_PRECISION=ON

- .github/workflows/itk_dict.txt
- Modules/Core/Common/include/itkRGBAPixel.h
- Modules/Core/Common/include/itkRGBPixel.h
- Modules/Core/Common/test/itkRGBAPixelGTest.cxx
- Modules/Core/Common/test/itkRGBPixelGTest.cxx
Tested by means of `CheckConstexprBeginAndEndOfContainer()`. Note that these default-constructors were already `constexpr` _implicitly_, as implied by `= default`, when `ITK_FUTURE_LEGACY_REMOVE` would be enabled.
> ENH: Make default-constructors of RGBPixel and RGBAPixel `constexpr`

- Modules/Core/Transform/test/itkTransformTest.cxx
Core/Transform/test/itkTransformTest.cxx:224:46: error:
```txt
default initialization of an object of const type 'const
itk::itkTransformTestHelpers::TransformTester<double, 3, 3>::InputSymmetricSecondRankTensorType' (aka 'const
SymmetricSecondRankTensor<double, 3U>') without a user-provided default
constructor const InputSymmetricSecondRankTensorType ssrten;
^
{}
```
Nightly dashboards are failing https://open.cdash.org/viewBuildError.php?buildid=10098209
> COMP: Fix compilation issues

- Modules/Core/Common/include/itkAutoPointer.h
Following C++ Core Guidelines, Oct 3, 2024, ["Avoid casts"](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es48-avoid-casts)
> STYLE: Remove (void *) casts from implementation AutoPointer comparisons

- Modules/Core/Common/test/itkMultiThreaderExceptionsTest.cxx
- Modules/Core/Common/test/itkMultiThreaderTypeFromEnvironmentTest.cxx
Addresses the following build error:
https://open.cdash.org/viewBuildError.php?buildid=10099800
Do we not a TBB build in CI?
> COMP: Address non-const operations when TBB enabled in test

- Modules/Filtering/ImageGrid/include/itkShrinkImageFilter.hxx
The behavior of setting individual m_ShrinkFactor elements should be the same as setting from an array of shrinkFactors.
> BUG: Consistency of enforcing m_ShrinkFactors > 1

- Modules/Filtering/ImageSources/include/itkGenerateImageSource.hxx
- Modules/Filtering/ImageSources/test/Baseline/itkGridImageSourceTest5.mha.cid
- Modules/Filtering/ImageSources/test/CMakeLists.txt
- Modules/Filtering/ImageSources/test/itkGridImageSourceTest2.cxx
We want the same behavior as SetOutputParametersFromImage.
Without this, a crash occurs on Update().
> BUG: GenerateImageSource sets Size from ReferenceImage

- Modules/Registration/Common/include/itkMeanSquaresImageToImageMetric.hxx
- Modules/Registration/Common/test/itkMeanSquaresImageMetricTest.cxx
Weights caching is used for derivative calculation to reduce registration time with BSplineTransforms. Currently only implemented for MeanSquaresImageToImageMetric, other metrics to be added at a later date.
> PERF: Adding weights caching derivative calculation to iktMeanSquaresImageToImageMetric

- Examples/RegistrationITKv4/DeformableRegistration6.cxx
- Examples/Statistics/BayesianPluginClassifier.cxx
- Examples/Statistics/KdTreeBasedKMeansClustering.cxx
- Modules/Core/Common/src/itkProcessObject.cxx
- Modules/Core/Common/src/itkThreadLogger.cxx
- Modules/Core/Common/test/itkImageRandomConstIteratorWithIndexGTest.cxx
- Modules/Core/Common/test/itkLoggerThreadWrapperTest.cxx
- Modules/Core/Common/test/itkObjectFactoryTest3.cxx
- Modules/Core/Common/test/itkThreadLoggerTest.cxx
- Modules/Core/Mesh/include/itkTriangleMeshToBinaryImageFilter.hxx
- Modules/Core/SpatialObjects/test/itkDTITubeSpatialObjectTest.cxx
- Modules/Core/SpatialObjects/test/itkTubeSpatialObjectTest.cxx
- Modules/IO/GDCM/src/itkGDCMSeriesFileNames.cxx
- Modules/IO/ImageBase/include/itkImageSeriesWriter.hxx
- Modules/IO/ImageBase/src/itkImageIOBase.cxx
- Modules/IO/ImageBase/test/itkImageSeriesReaderDimensionsTest.cxx
- Modules/IO/ImageBase/test/itkImageSeriesReaderSamplingTest.cxx
- Modules/IO/ImageBase/test/itkImageSeriesReaderVectorTest.cxx
- Modules/IO/MeshBase/src/itkMeshIOBase.cxx
- Modules/IO/PNG/test/itkPNGImageIOTest2.cxx
- Modules/IO/XML/src/itkDOMNode.cxx
- Modules/Numerics/Optimizers/test/itkInitializationBiasedParticleSwarmOptimizerTest.cxx
- Modules/Numerics/Optimizers/test/itkParticleSwarmOptimizerTest.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkBSplineSyNPointSetRegistrationTest.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkSyNPointSetRegistrationTest.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkTimeVaryingBSplineVelocityFieldPointSetRegistrationTest.cxx
- Modules/Segmentation/Classifiers/test/itkSampleClassifierFilterTest1.cxx
- Modules/Segmentation/Classifiers/test/itkSampleClassifierFilterTest2.cxx
The check flags insertions to an STL-style container done by calling the
push_back method with an explicitly-constructed temporary of the container
element type. In this case, the corresponding emplace_back method results in
less verbose and potentially more efficient code.
> Emplace back method

- Modules/Core/Common/include/itkPyCommand.h
- Modules/Core/Common/include/itkPyImageFilter.h
- Modules/Core/SpatialObjects/include/itkTubeSpatialObject.h
- Modules/Filtering/FastMarching/include/itkFastMarchingUpwindGradientImageFilter.h
- Modules/Filtering/ImageIntensity/include/itkTernaryAddImageFilter.h
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkDiscreteCurvatureTensorQuadEdgeMeshFilter.h
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkQuadEdgeMeshParamMatrixCoefficients.h
- Modules/Numerics/Optimizersv4/include/itkLBFGS2Optimizerv4.h
Describe function overrides using the override keyword from C++11.
-----
https://stackoverflow.com/questions/39932391/virtual-override-or-both-c When you override a function you don't technically need to write either virtual or override.
The original base class declaration needs the keyword virtual to mark it as virtual.
In the derived class the function is virtual by way of having the ¹same type as the base class function.
However, an override can help avoid bugs by producing a compilation error when the intended override isn't technically an override. For instance, the function type isn't exactly like the base class function. Or that a maintenance of the base class changes that function's type, e.g. adding a defaulted argument.
In the same way, a virtual keyword in the derived class can …
> STYLE: Use override statements for C++11

- Modules/Core/Common/include/itkDerivativeOperator.hxx
- Modules/Core/Common/include/itkFloodFilledSpatialFunctionConditionalConstIterator.hxx
- Modules/IO/ImageBase/test/itkArchetypeSeriesFileNamesTest.cxx
- Modules/IO/Meta/src/itkMetaImageIO.cxx
- Modules/Numerics/Statistics/include/itkHistogram.hxx
- Modules/Numerics/Statistics/include/itkStatisticsAlgorithm.hxx
Implements detection of local variables which could be declared as const but are not. Declaring variables as const is recommended by many coding guidelines, such as: ES.25 from the C++ Core Guidelines.
cd ${BLDDIR}
run-clang-tidy.py -extra-arg=-D__clang__ -checks=-*,misc-const-correctness -header-filter=.* -fix
> STYLE: Prefer explicit const designation

- Modules/Core/Common/test/itkSliceIteratorTest.cxx
The variable name s was used as an input and a loop variable. Split the names to clearly indicate the iteration variable intent.
> STYLE: PrintSlice re-used variable name

- Modules/Core/Common/src/itkAnatomicalOrientation.cxx
- Modules/Core/Common/src/itkNumberToString.cxx
- Modules/Core/Common/src/itkProcessObject.cxx
- Modules/Core/Common/test/itkSmartPointerTest.cxx
- Modules/Core/SpatialObjects/include/itkDTITubeSpatialObjectPoint.hxx
- Modules/Filtering/ImageGrid/test/itkResampleImageTest8.cxx
- Modules/IO/ImageBase/src/itkImageIOBase.cxx
- Modules/IO/MeshBase/src/itkMeshIOBase.cxx
- Modules/IO/SpatialObjects/src/itkPolygonGroupSpatialObjectXMLFile.cxx
- Modules/IO/TransformBase/include/itkTransformIOBase.h
- Modules/Numerics/Optimizers/src/itkLBFGSOptimizer.cxx
- Modules/Numerics/Optimizersv4/src/itkLBFGSOptimizerv4Base.cxx
- Modules/Numerics/Optimizersv4/test/itkObjectToObjectOptimizerBaseTest.cxx
Replaces explicit calls to the constructor in a return with a braced initializer list. This way the return type is not needlessly duplicated in the function definition and the return statement.
> PERF: Replace explicit return calls of constructor

- Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.h
- Modules/Core/ImageFunction/include/itkWindowedSincInterpolateImageFunction.hxx
The values of m_Factor* are known at compile-
time, so compute them only at compile-time.
> STYLE: Prefer compile-time constexpr

- Modules/Filtering/FFT/include/itkComplexToComplexFFTImageFilter.h
- Modules/IO/ImageBase/include/itkIOCommon.h
Fix multiple group Doxygen warnings: enum classes cannot be members of multiple groups: remove the additional grouping command, and leave the one corresponding to the most specific group.
From the Doxygen documentation:
"Note that compound entities (like classes, files and namespaces) can be put into multiple groups, but members (like variable, functions, typedefs and enums) can only be a member of one group (...)."
https://www.doxygen.nl/manual/grouping.html#topics
Fixes:
```
Warning
Modules/IO/ImageBase/include/itkIOCommon.h:42:
warning: Member AtomicPixel found in multiple @ingroup groups!
The member will be put in group ITKIOImageBase, and not in group IOFilters
```
and
```
Warning
Modules/Filtering/FFT/include/itkComplexToComplexFFTImageFilter.h:41:
warning: Member TransformDirection …
```
> DOC: Fix multiple group Doxygen warnings

- CMakeLists.txt
The update to HDF5 #4940, added a required CMake minimum version of 3.18. Update the top-level requirement to match.
While possible to build ITK without HDF5, this is not a common configuration. The non-minimum requirement at the top level can be considered a bug. 
Note: Ubuntu 20.04 contains cmake 2.16.3, but standard support end April 2025 ( likely before the ITK 6.0 final release).
> ENH: Update CMake minimum support to 3.22.1

- Documentation/Doxygen/Iterators.dox
- Documentation/Doxygen/Modules.dox
- Documentation/Doxygen/Registration.dox
- Documentation/docs/contributing/document_itk.md
- Documentation/docs/learn/dicom.md
- Documentation/docs/learn/faq.md
- Documentation/docs/learn/fda_sw_development_guidelines.md
- Documentation/docs/migration_guides/itk_5_migration_guide.md
- Documentation/docs/migration_guides/itk_6_migration_guide.md
- Documentation/docs/scientific_ecosystem/itk_ecosystem.md
Found via `codespell -q 3 -S "./Modules/ThirdParty,./Documentation/docs/releases,./Documentation/ReleaseNotes" -L ans,ba,checkin,childrens,developpement,delte,dota,dum,fiter,indx,inout,isit,ist,iterm,lsit,listin,nd,ot,positionn,serie,te,thirdparty,unser`
> DOC: Fix various typos in Documentation/ directory

- Documentation/Maintenance/Release.md
The directory path passed to `datalad export-archive` must:
1. Note exist already
2. The directory + .tar.gz must not exist.
Or the expected archive output path is not correct.
> DOC: Remove datalad archive before regenerating

- Modules/Core/Transform/include/itkTransform.h
Fix legacy methods `itk::Transform` Doxygen warnings: protect with the `ITK_LEGACY_REMOVE` macro definition a function declared as legacy with the `itkLegacyMacro` in `itk::Transform`.
Fixes:
```
Warning
Parsing file /home/kitware/DashboModules/Core/Transform/include/itkTransform.h:535:
warning: Illegal member name found.
```
and
```
Warning
Modules/Core/Transform/include/itkTransform.h:535:
warning: no uniquely matching class member found for
itk::Transform::virtual void itk::Transform< TParametersValueType, VInputDimension, VOutputDimension >::ComputeInverseJacobianWithRespectToPosition() const &
```
Raised for example in:
https://open.cdash.org/viewBuildError.php?type=1&buildid=10124761
> DOC: Fix legacy methods `itk::Transform` Doxygen warnings

- Modules/Core/Common/include/itkHexahedronCell.hxx
- Modules/Core/Common/include/itkQuadrilateralCell.hxx
Found by cppcheck.
The nearby comment occurs elsewhere in the codebase, and there it was changed to `return false` so I did the same here.
> BUG: -1 was being returned in a function that returns bool

- Modules/ThirdParty/NIFTI/UpdateFromUpstream.sh
> ENH: switch upstream of nifti_clib to InsightSoftwareConsortium fork

- Utilities/KWStyle/BuildKWStyle.cmake
Attempting the address build warnings on Clang. Example:
```log
KWStyle/Utilities/boost/xpressive/basic_regex.hpp:200:43: note: in instantiation of member function 'boost::xpressive::regex_compiler<std::__wrap_iter<const char *>>::compile' requested here
200 |         return regex_compiler<BidiIter>().compile(begin, flags);
|                                           ^
KWStyle/kwsParser.cxx:575:32: note: in instantiation of member function 'boost::xpressive::basic_regex<std::__wrap_iter<const char *>>::compile' requested here
575 |   sregex unixNewline = sregex::compile("\r?\n|\r");
|                                ^
In file included from KWStyle/kwsParser.cxx:18:
In file included from KWStyle/Utilities/boost/xpressive/xpressive.hpp:18: …
```
> COMP: Update KWStyle

- Documentation/Doxygen/DoxygenFooter.html
Nightly tarballs and release tarballs, for all released versions of ITK,
are now available in the ITKDoxygen GitHub Releases.
> DOC: Update Doxygen footer link to tarballs

- Documentation/docs/contributing/index.md
Someone deleted the `5.4` branch from the repository. And it had not been updated in the last seven months, but a `release-5.4` branch was created and has been updated. In prior section, our documentation references `release-5.4` as the maintenance branch.
We had anticipated using the `5.4` to present stable builds of the documentation in ReadTheDocs -- their versioning recognizes `5.4` but not `release-5.4`. However, we can also build versions of the tags and present that in ReadTheDocs. And, this allows use to used tagged subproject, like `itkdoxygen`, and RTD will provide unified search over the tags. With the tags, and the `release` builds, the `X.X` RTD versions are redundant.
> DOC: Update maintenance branch for 5.4 series

- Documentation/Maintenance/Release.md
Archive tarballs on the NumFOCUS GDrive ITKReleases folder.
data.kitware.com throws bad gateway errors and Kitware said that
data.kitware.com is no longer supported and data should migrate off it.
Sign the source tarballs per OSSF Scorecard best practices:
https://github.com/ossf/scorecard/blob/49c0eed3a423f00c872b5c3c9f1bbca9e8aae799/docs/checks.md#signed-releases
Doxygen is now mostly automated via GitHub Actions and ReadTheDocs.
> DOC: Release process updates with ITK 5.4.0

- Modules/Filtering/ImageCompose/test/CMakeLists.txt
- Modules/Filtering/ImageCompose/test/itkComposeBigVectorImageFilterTest.cxx
Incorrect results are being computed on windows with the Compose filter ( and maybe other filters) and VectorImages of sizes >4GB.
See: SimpleITK/SimpleITK#2220 for details
> add test to reproduce SimpleITK issue #2220

- Documentation/Doxygen/Modules.dox
Fix `defgroup` command in Doxygen `Modules` file: do not allow any whitespace between the backward slash and `defgroup`.
The affected group, `ImageEnhancement` is not being displayed in the list of modules/groups and no filter is currently being attributed the affected group, despite some filters, e.g. `itk::ConvertLabelMapFilter`, being within that group.
Reported by: albert-github <albert.tests@gmail.com>
> DOC: Fix `defgroup` command in Doxygen `Modules` file

- Modules/Core/Common/test/itkMemoryProbesCollecterBaseTest.cxx
On macOS, itkMemoryProbesCollecterBaseTest would often fail with messages like:
Freeing memory should result in less memory but it is 262216kB instead of 262164kB
Just increased the amout of memory allocated in this test to make it more likely to pass.
Closes #4818.
> ENH: fixed issue 4818 with itkMemoryProbesCollecterBaseTest

- Modules/Core/Common/src/itkBuildInformation.cxx.in
- Modules/Filtering/GPUAnisotropicSmoothing/src/GPUGradientNDAnisotropicDiffusionFunction.cl
This is a revival of #5135. Closes #5135.
> STYLE: Removed double semicolon in C++ and OpenCL files

- Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx
- Modules/Registration/PDEDeformable/include/itkESMDemonsRegistrationFunction.hxx
Initialize miscellaneous local variables to avoid undefined behavior.
Fixes:
```
Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:308:18:
warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
308 |         point[j] += displacement[j];
|                  ^
```
and
```
Modules/Filtering/ImageGrid/include/itkWarpImageFilter.hxx:338:18:
warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
338 |         point[j] += displacement[j];
|
```
and
```
Modules/Registration/PDEDeformable/include/itkESMDemonsRegistrationFunction.hxx:331:22:
warning: iteration 2 invokes undefined behavior [-Waggressive-loop-optimizations]
331 |       mappedPoint[j] += it.GetCenterPixel()[j];
|
```
and
``` …
```
> BUG: Initialize miscellaneous local variables

- Modules/Filtering/ImageCompose/test/CMakeLists.txt
- Modules/Filtering/ImageCompose/test/itkComposeBigVectorImageFilterTest.cxx
Should fix most of https://open.cdash.org/viewTest.php?onlyfailed&buildid=10165446
Closes #5173.
> Vnl 2025 01 24

- Testing/ContinuousIntegration/AzurePipelinesLinux.yml
This fixes #3097 by adding a LinuxCxx20 job with the Azure continuous integration.
In the future, as ITK project itself adopts newer standards, it is easy to change this job to use C++23, etc.
This is essentially a clone of the Linux job with CMAKE_CXX_STANDARD set to 20 and CMAKE_CXX_STANDARD_REQUIRED enabled.
> ENH: COMP: Adding LinuxCxx20 job to Azure continuous integration.

- Modules/Registration/PDEDeformable/include/itkMultiResolutionPDEDeformableRegistration.h
- Modules/Registration/PDEDeformable/include/itkMultiResolutionPDEDeformableRegistration.hxx
- Modules/Registration/PDEDeformable/test/itkMultiResolutionPDEDeformableRegistrationTest.cxx
> BUG: Enforce consistency between MultiResolutionPDEDeformableRegistration levels and iterations

- CMake/ITKcppcheckSuppressions.txt
- Modules/IO/GE/test/itkGEImageIOTest.cxx
- Modules/IO/TransformMINC/src/itkMINCTransformIO.cxx
- Modules/IO/TransformMINC/test/itkIOTransformMINCTest.cxx
Whoops, I accidently branched this off part 2, so only look at top 5 commits here...
> 3rd round of cppcheck warning fixes

- Modules/Core/Common/include/itkCommonEnums.h
- Modules/Core/Common/include/itkOctree.h
- Modules/Core/Common/src/itkCommonEnums.cxx
- Modules/Core/Common/test/itkOctreeTest.cxx
Closes #3923.
Replace the misspelling `SAGITAL_PLANE` with `SAGITTAL_PLANE`.
Note that both spellings are accepted if _not_ `ITK_LEGACY_REMOVE`. 
However, invocation of `std::ostream &operator<<(std::ostream & out, const OctreeEnums::Octree value)` with either spelling will output a string with the correct spelling: `"itk::OctreeEnums::Octree::SAGITTAL_PLANE"`
> BUG: SAGITAL_PLANE -> SAGITTAL_PLANE, though with legacy support

- Modules/Filtering/ImageCompose/include/itkComposeImageFilter.hxx
Modules/Filtering/ImageCompose/include/itkComposeImageFilter.hxx:135:19: error: non-constant-expression cannot be narrowed from type 'PixelType' (aka 'unsigned char') to 'float' in initializer list [-Wc++11-narrowing]
135 |         oit.Set({ inputItContainer[0].Get(), inputItContainer[1].Get() });
|                   ^~~~~~~~~~~~~~~~~~~~~~~~~
Identified when building SphinxExamples remote module.
> COMP: Type matching for complex pixel data types

- Modules/Core/FiniteDifference/include/itkFiniteDifferenceImageFilter.h
- Modules/Core/GPUFiniteDifference/include/itkGPUFiniteDifferenceImageFilter.h
> DOC: Fix doxygen warnings about setters not returning anything

- Utilities/Maintenance/migrate-itk6-code-recommendations.sh
This script provides a mechanism for updating external repos to be compiant with ITK version 6 code styles that allow building when ITK uses ITK_LEGACY_REMOVE and ITK_FUTURE_LEGACY_REMOVE.
It was used to update many of the ITK/Modules/Remote, and was also applied to the BRAINTTools, ANTs, and Slicer application source trees.
> DOC: Script to assist with migrating external apps

- Modules/IO/ImageBase/test/CMakeLists.txt
Closes: https://github.com/InsightSoftwareConsortium/ITK/issues/3703
> TEST: Fix unexercised tests for large image read/write

- .git-blame-ignore-revs
Close #2623
In case this needs to be re-done in the future, I used the following script in a python environment with GitPython installed:
```py
import git
from pathlib import Path
def find_style_commits_with_large_changes(repo : git.Repo, prefix="STYLE", file_change_threshold=1000) -> list[str]:
matching_commits = []
for commit in repo.iter_commits():
if commit.message.strip().startswith(prefix):
num_files_changed = len(commit.stats.files)
if num_files_changed >= file_change_threshold:
matching_commits.append(commit.hexsha)
return matching_commits
def get_commits_already_ignored(blame_ignore_revs_path) -> list[str]:
return [
line.strip()
for line in blame_ignore_revs_path.read_text().split('\n')
if line and not line.startswith('#')
]
if __name__ == "__main__":
repo = git.Repo('.') …
```
> STYLE: Add historical bulk changes to git blame ignore

- Utilities/Doxygen/DoxygenConfig.cmake
- Wrapping/DoxygenConfig.cmake
> ENH: Speed up documentation generation by using multiprocessing

- Modules/Core/Common/include/itkGaussianDerivativeOperator.h
- Modules/Filtering/Convolution/include/itkMaskedFFTNormalizedCorrelationImageFilter.h
- Modules/Filtering/ImageGrid/include/itkBSplineResampleImageFilterBase.h
Fix incorrect `BibTeX` citation keys.
Fixes:
```
.../ITK/Modules/Filtering/ImageGrid/include/itkBSplineResampleImageFilterBase.h:47:
warning: \cite command to 'unser199' does not have an associated number
.../ITK/Modules/Core/Common/include/itkGaussianDerivativeOperator.h:80:
warning: \cite command to 'lindeberg1999' does not have an associated number
.../ITK/Modules/Filtering/Convolution/include/itkMaskedFFTNormalizedCorrelationImageFilter.h:128:
warning: \cite command to 'padfield' does not have an associated number
```
Reported by: albert-github <albert.tests@gmail.com>
Fixes #5202.
> DOC: Fix incorrect `BibTeX` citation keys

- Modules/Filtering/ImageCompose/test/itkCompose2DCovariantVectorImageFilterTest.cxx
- Modules/Filtering/ImageCompose/test/itkCompose2DVectorImageFilterTest.cxx
- Modules/Filtering/ImageCompose/test/itkCompose3DCovariantVectorImageFilterTest.cxx
- Modules/Filtering/ImageCompose/test/itkCompose3DVectorImageFilterTest.cxx
- Modules/Filtering/ImageCompose/test/itkComposeRGBAImageFilterTest.cxx
- Modules/Filtering/ImageCompose/test/itkComposeRGBImageFilterTest.cxx
- Modules/Filtering/ImageCompose/test/itkImageReadRealAndImaginaryWriteComplexTest.cxx
- Modules/Filtering/ImageCompose/test/itkImageToVectorImageFilterTest.cxx
- Modules/Filtering/ImageCompose/test/itkJoinImageFilterTest.cxx
- Modules/Filtering/ImageCompose/test/itkJoinSeriesImageFilterStreamingTest.cxx
- Modules/Filtering/ImageCompose/test/itkJoinSeriesImageFilterTest.cxx
- STYLE: Use `ITK_TRY_EXPECT_NO_EXCEPTION` macro in `ImageCompose` tests
- STYLE: Conform to ITK style guidelines in test arg check message
- STYLE: Perform first the test input argument check
- STYLE: Remove unnecessary/uninformative comment block in test
- STYLE: Do not capitalize variable first letter
> STYLE: Miscellaneous `ImageCompose` test style enhancements

- Documentation/Doxygen/DoxygenLayout.xml
With the newer versions of doxygen (i.e. 1.9.8 and newer) the old modules pages is missing. As of doxygen 1.9.8 the modules have been renamed to topics to prevent confusion with C++ modules. Closes #5212.
> DOC: Retain Modules page, which was renamed into Topics

- Documentation/Doxygen/doxygen.bib
- Modules/Core/Transform/include/itkKernelTransform.h
- Modules/Numerics/Optimizers/include/itkSPSAOptimizer.h
- Modules/Segmentation/LevelSets/include/itkShapeDetectionLevelSetImageFilter.h
- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkMRFImageFilter.h
Fourth and final PR, converting raw inline citations with various styles to using a bibliography database and the doxygen cite command.
Bibtex file was formatted using bibtex-tidy
(https://github.com/FlamingTempura/bibtex-tidy). This tool can be used as a pre-commit hook but currently does not have an option for just performing compliance checking so not added to .pre-commit-config.yaml file.
> DOC: Convert from raw in-code citations to bibtex (4/4)

- Examples/Statistics/BayesianClassifier.cxx
- Examples/Statistics/BayesianClassifierInitializer.cxx
- Examples/Statistics/ScalarImageKmeansClassifier.cxx
- Examples/Statistics/ScalarImageMarkovRandomField1.cxx
This commit addresses the review comments from PR #5163 related to issue #2802. In this commit Examples related to statistics has been changed to use itk::ReadImage and itk::WriteImage
Part of #2802. This is a re-imagining of #5214. Closes #5214.
> STYLE: Use itk::ReadImage and itk::WriteImage in Example/Statistics

- Modules/Filtering/LabelMap/include/itkLabelObjectLine.h
- Modules/Filtering/LabelMap/include/itkLabelObjectLine.hxx
- Modules/Registration/Common/include/itkEuclideanDistancePointMetric.h
- Modules/Registration/Common/include/itkEuclideanDistancePointMetric.hxx
Moved the member function definitions of `const`member functions that have an empty member function definition from their "itk*.hxx" file to the corresponding "itk*.h" file, and into their class definition.
Found by regular expression `^..[^:,].+\) const\r\n{}` in "itk*.hxx" files.
- Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/5198 commit b94770d8746133a441df1796e3d1628c6935adfc
"STYLE: Move empty member functions with empty param list from .hxx to .h"
> STYLE: Move empty `const` member functions from .hxx to .h

- Modules/IO/NRRD/src/itkNrrdImageIO.cxx
The old code was flipping left/right axis instead of anterior/posterior. The bug was introduced with the original feature on November 22, 2005: 15372e8c17ef2344d47767d47cc27c5fe9c6c17a. Closes #5207.
> BUG: Fix AP axis flipping for case LeftAnteriorSuperior in NRRDImageIO

- Documentation/Doxygen/DoxygenFooter.html
- Documentation/Doxygen/DoxygenHeader.html
- Documentation/Doxygen/doxygen.bib
The documentation used the settings (header and footer) based on the defaults of doxygen 1.8.15, now doxygen 1.13.2 is used.
Problems fixed:
* logo is not shown
* build time information is not shown
* reference to tarbal is not shown
Closes #5227. Closes #5226.
> Doc fixes: update doxygen header/footer, fix bibtex misspelling

- Documentation/docs/learn/faq.md
- a table was not rendered in the FAQ due to the fact that the line was split
- correction of some spelling errors
> DOC: Incorrect rendering table in FAQ

- Documentation/Doxygen/Iterators.dox
Improves formatting, fixes misspellings and obvious discrepancy about setting pixel value to 100 (instead of 10). Closes #5232.
> DOC: Improve iterator documentation section

- .github/workflows/pre-commit.yml
Fails the `no-commit-to-branch` check for merges, but should be
unnecessary.
> BUG: Do not run pre-commit GHA on push

- Modules/Core/Common/include/itkArray.h
- Modules/Core/Common/test/CMakeLists.txt
- Modules/Core/Common/test/itkArrayGTest.cxx
Added a deduction guide to avoid `-wctad-maybe-unsupported` compiler warnings.
Included a compile-time unit test.
> ENH: Let `itk::Array` support class template argument deduction (CTAD)

- Modules/Filtering/ImageGrid/include/itkBSplineScatteredDataPointSetToImageFilter.hxx
- Modules/Filtering/ImageGrid/test/Baseline/itkBSplineScatteredDataPointSetToImageFilterTest05_magnitude.png.cid
BUG:   Incorrect size for looping closed parametric dimension.
Bug producing an incorrect result for the specific case of a closed parametric dimension, e.g., closed loop or cylinder.  This doesn't effect the usual image output.    
> BUG:  Incorrect size for looping closed parametric dimension.

- Documentation/docs/releases/5.4.2.md
Locally ran pixi at the root of ITK source tree, as follows:
./.git/hooks/pixi/bin/pixi.exe run pre-commit-run
Output:
Pixi task (pre-commit-run in pre-commit): pre-commit run --all: (Run pre-commit hooks on all repository files)
check for added large files..............................................Passed
[...]
fix end of files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook
> STYLE: Remove empty line from doc file (pre-commit "fix end of files")

- Modules/Core/Common/include/itkSymmetricEigenAnalysis.h
- Modules/Filtering/Denoising/include/itkPatchBasedDenoisingImageFilter.h
- Modules/Filtering/ImageGrid/include/itkBSplineL2ResampleImageFilterBase.h
- Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.h
- Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4.h
- Modules/Registration/PDEDeformable/include/itkDiffeomorphicDemonsRegistrationFilter.h
On a number of lines the `\cite` command and the cite label were on different lines and that is currently not allowed in doxygen.
> DOC: Empty `\cite` label

- Modules/Core/Common/test/itkNumberToStringGTest.cxx
Aims to address test failures reported by @yurivict, at https://github.com/InsightSoftwareConsortium/ITK/issues/5245, saying:
```
/usr/ports/science/InsightToolkit/work/ITK-5.4.2/Modules/Core/Common/test/itkNumberToStringGTest.cxx:99: Failure
Expected equality of these values:
numberToString(power_of_ten)
Which is: "100000010000"
'1' + std::string(exponent, '0')
Which is: "100000000000"
Floating point type: float
...
/usr/ports/science/InsightToolkit/work/ITK-5.4.2/Modules/Core/Common/test/itkNumberToStringGTest.cxx:108: Failure
Expected equality of these values:
numberToString(power_of_ten)
Which is: "0.000009999999999999999"
"0." + std::string(-1 - exponent, '0') + '1'
Which is: "0.00001"
Floating point type: double
```
Using clang-19 on FreeBSD 14.2.
Sean McBride (@seanm) confirmed …
> BUG: Replace `pow` with `Math::UnsignedPower` in NumberToString GTest

- Modules/Core/Common/include/itkFloodFilledSpatialFunctionConditionalConstIterator.hxx
- Modules/Filtering/AnisotropicSmoothing/include/itkAnisotropicDiffusionImageFilter.hxx
- Modules/Filtering/GPUAnisotropicSmoothing/include/itkGPUAnisotropicDiffusionImageFilter.hxx
Replaced `std::pow(2.0, x)` with `1ULL << x` where `x` is either `ImageDimension` or `ImageDimension + 1`. Declared a few more variables `constexpr`.
In general, a left-shift may be faster than an `std::pow` call.
> STYLE: Replace `std::pow(2, dim)` calls with `1 << dim`

- CMakeLists.txt
- Documentation/docs/releases/5.4.2.md
- Modules/IO/MINC/include/itkMINCImageIO.h
- Modules/IO/MINC/src/CMakeLists.txt
- Modules/IO/MINC/src/itkMINCImageIO.cxx
- Modules/IO/MINC/src/itkMINCImageIOConfigurePrivate.h.in
- Modules/IO/MINC/test/CMakeLists.txt
- Modules/IO/MINC/test/itkMINCImageIOTest4.cxx
- Modules/IO/TransformMINC/include/itkMINCTransformAdapter.h
- Modules/IO/TransformMINC/include/itkMINCTransformIO.h
- Modules/IO/TransformMINC/src/CMakeLists.txt
- Modules/IO/TransformMINC/src/itkMINCImageIOConfigurePrivate.h.in
- Modules/IO/TransformMINC/src/itkMINCTransformIO.cxx
- Modules/IO/TransformMINC/test/itkIOTransformMINCTest.cxx
- Modules/IO/TransformMINC/test/itkMINCTransformAdapterTest.cxx
> BUG: Fix incorrect reading of MINC2 files, convert RAS coordinates to LPS

- Modules/Core/Common/include/itkEllipsoidInteriorExteriorSpatialFunction.hxx
- Modules/Core/Common/include/itkFiniteCylinderSpatialFunction.hxx
- Modules/Core/Common/include/itkSymmetricEllipsoidInteriorExteriorSpatialFunction.hxx
- Modules/Core/Common/include/itkTorusInteriorExteriorSpatialFunction.hxx
- Modules/Filtering/DisplacementField/include/itkIterativeInverseDisplacementFieldImageFilter.hxx
- Modules/Filtering/LabelMap/include/itkShapeLabelMapFilter.hxx
- Modules/Filtering/LabelMap/include/itkStatisticsLabelMapFilter.hxx
- Modules/Numerics/Optimizers/src/itkCumulativeGaussianCostFunction.cxx
- Modules/Numerics/Optimizers/src/itkCumulativeGaussianOptimizer.cxx
- Modules/Registration/Common/include/itkCorrelationCoefficientHistogramImageToImageMetric.hxx
- Modules/Registration/Common/include/itkMeanReciprocalSquareDifferencePointSetToImageMetric.hxx
`Math::sqr(x)` appears slightly more readable than `std::pow(x, 2)`.
> STYLE: Replace `std::pow(x, 2)` calls with `Math::sqr(x)`

- Modules/Remote/LabelErodeDilate.remote.cmake
Update remote module to v1.3.1 hash to address valgrind defects.
> BUG: Address valgrind defect in LabelErodeDilate

- Modules/Core/Common/include/itkBoundingBox.hxx
~~The use of bit-shift and modulo is a bit more elegant in this case, it may be slightly faster, and it takes away the need to do static_cast's.~~
The use of `std::bitset` is a bit clearer in this case, it may be slightly faster than those `std::pow` calls, and it takes away the need to do static_cast's.
> STYLE: Remove `std::pow` calls from `BoundingBox::ComputeCorners()`

- Modules/ThirdParty/ZLIB/src/itkzlib-ng/CMakeLists.txt
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/power/crc32_power8.c
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/power/power_intrins.h
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/riscv/riscv_features.c
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/s390/s390_functions.h
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/s390/self-hosted-builder/actions-runner
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/s390/self-hosted-builder/actions-runner-rebuild.sh
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/s390/self-hosted-builder/actions-runner.Dockerfile
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/x86/chunkset_avx2.c
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/arch/x86/chunkset_avx512.c
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/infback.c
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/inflate.c
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/inflate.h
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/trees_emit.h
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/zlib.h.in
- Modules/ThirdParty/ZLIB/src/itkzlib-ng/zutil.c
> zlib-ng 2025-02-10 (860e4cff)

- Modules/Filtering/DisplacementField/include/itkDisplacementFieldTransform.hxx
When spacing or direction differences were encountered, the original code would produce an incorrect exception message. The exception might occur when calling `DisplacementFieldTransform::SetInverseDisplacementField`.
The bug appears introduced with commit 70fd79f43c089bec068ba6f6657baca12996842d, "ENH:  Adding transform parameters adaptors.", 20 Sep 2011.
> BUG: Fix strings in DisplacementField VerifyFixedParametersInformation

- Modules/Core/Common/include/itkResourceProbe.hxx
- Modules/Core/Common/src/itkExceptionObject.cxx
Three small style improvements.
> Remove a few local `stringstream` variables from ResourceProbe and ExceptionObject 

- Modules/Core/Common/src/itkExceptionObject.cxx
- Modules/Core/Common/test/itkExceptionObjectGTest.cxx
- Triggered by encouraging feedback from Hans (@hjmjohnson) and Dženan (@dzenanz) at https://github.com/InsightSoftwareConsortium/ITK/pull/5265#discussion_r1983786150
---
With this pull request, a call like `itkGenericExceptionMacro("Oops, something horribly wrong!")` will create a "what text" like the following:
```
D:\MyProject\MySource.cxx:42: in 'void MyObject::DoMyThing(int)':
ITK ERROR: Oops, something horribly wrong!
```
So it adds something like ` in 'void MyObject::DoMyThing(int)':` to the first line.
> ENH: Add location (function) to text returned by ExceptionObject::what()

- Modules/Core/Common/test/itkExceptionObjectGTest.cxx
The try-catch wasn't meant to be part of the unit test!
> STYLE: Clean-up experimental code `ExceptionObject.TestWhat` unit test

- Modules/Core/Common/include/itkDataObject.h
- Modules/Core/Common/include/itkExceptionObject.h
- Modules/Core/Common/src/itkDataObject.cxx
- Modules/Core/Common/src/itkExceptionObject.cxx
- Modules/IO/ImageBase/include/itkImageFileReaderException.h
- Modules/IO/ImageBase/include/itkImageFileWriter.h
- Modules/IO/ImageBase/include/itkImageSeriesWriter.h
- Modules/IO/MeshBase/include/itkMeshFileReaderException.h
- Modules/IO/MeshBase/include/itkMeshFileWriterException.h
- Modules/IO/MeshBase/src/itkMeshFileReaderException.cxx
- Modules/IO/MeshBase/src/itkMeshFileWriterException.cxx
- Modules/Numerics/FEM/include/itkFEMException.h
- Modules/Numerics/FEM/include/itkFEMItpackSparseMatrix.h
- Modules/Numerics/FEM/include/itkFEMLinearSystemWrapper.h
- Modules/Numerics/FEM/include/itkFEMLinearSystemWrapperItpack.h
- Modules/Numerics/FEM/src/itkFEMException.cxx
- Modules/Numerics/FEM/src/itkFEMItpackSparseMatrix.cxx
- Modules/Numerics/FEM/src/itkFEMLinearSystemWrapper.cxx
- Modules/Numerics/FEM/src/itkFEMLinearSystemWrapperItpack.cxx
Internally, `ExceptionObject` stores its file name, description, and location as `std::string`, so the corresponding constructor parameters might as well just be of type `std::string`.
Whenever such a parameter was originally declared `const std::string &`, this commit has removed the `const` and the `&`, in order to efficiently "move" the parameters from derived exception classes to their base class.
Note that this commit drops the support for null pointers as arguments.
> STYLE: Remove Exception constructor overloads for `char *` arguments

- Modules/Core/Common/include/itkExceptionObject.h
- Modules/IO/ImageBase/include/itkImageFileReaderException.h
- Modules/IO/ImageBase/include/itkImageFileWriter.h
- Modules/IO/MeshBase/include/itkMeshFileReaderException.h
- Modules/IO/MeshBase/include/itkMeshFileWriterException.h
- Modules/Numerics/FEM/include/itkFEMException.h
It is preferable not duplicate a literal string so many times (following [the DRY principle](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)). Moreover, it appears sufficient to use an empty string value (`{}`), to indicate that the location of an exception is unspecified.
Note that an unspecified location may be "unknown", but instead, it may also be "irrelevant", or "hidden". So it may depend on the application.
- Triggered by a discussion with Bradley (@blowekamp) at https://github.com/InsightSoftwareConsortium/ITK/pull/5266#discussion_r1985469317
> STYLE: Replace "Unknown" default for exception location with `{}`

- Modules/Core/Common/include/itkExceptionObject.h
- Modules/Core/Common/src/itkExceptionObject.cxx
- Modules/IO/ImageBase/include/itkImageFileReaderException.h
- Modules/IO/ImageBase/include/itkImageFileWriter.h
- Modules/IO/MeshBase/include/itkMeshFileReaderException.h
- Modules/IO/MeshBase/include/itkMeshFileWriterException.h
- Modules/IO/MeshBase/src/itkMeshFileReaderException.cxx
- Modules/IO/MeshBase/src/itkMeshFileWriterException.cxx
Renamed the `ExceptionObject` constructor parameters for the description and the location of the exception. Also renamed the location parameters of derived exception classes.
Following ITKSoftwareGuide, CodingStyleGuide, section Naming Conventions, which says: "Names are generally spelled out; use of abbreviations is discouraged."
> STYLE: Do not abbreviate ExceptionObject parameter names (`desc`, `loc`)

- Modules/IO/ImageBase/include/itkImageSeriesReader.h
- Modules/IO/ImageBase/include/itkImageSeriesReader.hxx
No longer manually allocated the MetaDataDictionary objects of `ImageSeriesReader` on the heap. Stored them in an internal `std::vector` instead.
Declared `ImageSeriesReader::m_MetaDataDictionaryArray` private, just like `ImageSeriesWriter::m_MetaDataDictionaryArray`.
> Avoid manual memory management `ImageSeriesReader::m_MetaDataDictionaryArray`

- Modules/Bridge/VtkGlue/include/itkViewImage.hxx
- Modules/Core/Common/include/itkVariableLengthVector.hxx
- Modules/Core/Common/include/itkVariableSizeMatrix.hxx
- Modules/Core/Transform/include/itkRigid2DTransform.hxx
- Modules/Filtering/FFT/include/itkFFTShiftImageFilter.hxx
- Modules/Filtering/ImageFeature/include/itkHoughTransform2DLinesImageFilter.hxx
- Modules/Filtering/Smoothing/include/itkRecursiveGaussianImageFilter.hxx
- Modules/IO/BMP/src/itkBMPImageIO.cxx
- Modules/IO/ImageBase/include/itkImageFileReader.hxx
- Modules/IO/MINC/src/itkMINCImageIO.cxx
- Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
- Modules/IO/PhilipsREC/src/itkPhilipsRECImageIO.cxx
- Modules/Nonunit/Review/include/itkDirectFourierReconstructionImageToImageFilter.hxx
- Modules/Numerics/Optimizers/src/itkFRPROptimizer.cxx
- Modules/Numerics/Optimizers/src/itkPowellOptimizer.cxx
- Modules/Numerics/Optimizersv4/include/itkPowellOptimizerv4.hxx
- Modules/Segmentation/Voronoi/include/itkVoronoiSegmentationRGBImageFilter.hxx
Avoided specifying the same expression twice (`<expression> = -<expression>`), and avoided evaluating that expression twice.
Using the following regular expression in Visual Studio:
Find what:   (.+) = -\1;
Replace with:   $1 *= -1;
> STYLE: Flip signs by `x *= -1`, instead of by `x = -x`

- Modules/Core/Common/src/itkMultiThreaderBase.cxx
- Modules/Core/Common/test/itkMultiThreaderBaseTest.cxx
Clamp GlobalDefault threads with GlobalMaximum with initialization
We must call GetGlobalDefaultNumberOfThreads() when clamping the value
in SetGlobalMaximumNumberOfThreads, which has the side effect of
initializing static variables so the desired clamping occurs.
This issue will only be observed before a threader like the
itk::PoolMultiThreader is instantiated because
GetGlobalDefaultNumberOfThreads() is called in its constructor.
Addresses #4773.
> Global max threads during initialization

- CMake/ITKModuleTest.cmake
The check fails when using itk_python_add_test in external and remote modules as the macro is called before initializing WrapITK.pth. This check was added with 22998bd2266c1680db5152302a2e82f8f9cb228f but the file is always created and configured since
12e8d93a1c37cc26cd50d69a31ba3c1b6b82ae96 so removing the check should not harm.
> BUG: Remove check on WrapITK.pth existence in itk_python_add_test

- Modules/Numerics/Optimizersv4/include/itkConjugateGradientLineSearchOptimizerv4.h
- Modules/Numerics/Optimizersv4/include/itkConjugateGradientLineSearchOptimizerv4.hxx
- Modules/Numerics/Optimizersv4/test/itkConjugateGradientLineSearchOptimizerv4Test.cxx
When used as a local optimizer in multi-start optimization, itkConjugateGradientLineSearchOptimizerv4 gives inconsistent results because its learningRate is carried over from the end of one optimization to the beginning of the next.
Added a function to store the initial learning rate when SetLearningRate is called - this is then restored on the first iteration when StartOptimization is called.
Added a test to check that repeated optimizations with the same starting parameters converge to the same result.
> ENH: Reset conj-grad learning rate for multi-start optimization

- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
Three style improvements within `MersenneTwisterRandomVariateGenerator` member functions:
- Removed unnecessary `& 0xffffffffUL` from `Initialize`
- Replaced multiplication by `1 / 4294967296.0` with division by `double{ 1ULL << 32 }` in `GetVariateWithOpenUpperRange` and `GetVariateWithOpenRange` 
- Replaced `4294967295` with `numeric_limits<uint32_t>::max()` in `GetVariateWithClosedRange`
Following C++ Core Guidelines, [Avoid “magic constants”](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-magic)
> Remove magic numbers `0xffffffff`, `4294967295`, and `4294967296` from MersenneTwisterRandomVariateGenerator

- Modules/Nonunit/Review/include/itkMultiphaseSparseFiniteDifferenceImageFilter.h
- Modules/Segmentation/LevelSets/include/itkSparseFieldLevelSetImageFilter.h
- DOC: Fix Doxygen citation command call
- DOC: Use Doxygen citation command instead of misplaced `\par`
> DOC: Fix citations

- Modules/Filtering/MathematicalMorphology/include/itkValuedRegionalMaximaImageFilter.h
Fix Doxygen group name in math morphology class documentation: remove the duplicated "ITK" prefix.
Fixes:
```
Modules/Filtering/MathematicalMorphology/include/itkValuedRegionalMaximaImageFilter.h:28:
warning: Found non-existing group 'ITKITKMathematicalMorphology' for the command '@ingroup', ignoring command
```
https://open.cdash.org/viewBuildError.php?type=1&buildid=10297994
> DOC: Fix Doxygen group name in math morphology class documentation

- Examples/RegistrationITKv4/MultiResImageRegistration1.cxx
- Examples/RegistrationITKv4/MultiResImageRegistration2.cxx
- Examples/RegistrationITKv4/MultiResImageRegistration3.cxx
- Examples/RegistrationITKv4/MultiStageImageRegistration1.cxx
- Examples/RegistrationITKv4/MultiStageImageRegistration2.cxx
- Examples/RegistrationITKv4/ThinPlateSplineWarp.cxx
- Examples/SpatialObjects/BoundingBoxFromImageMaskSpatialObject.cxx
This commit addresses the review comments from PR #5223 related to issue #2802 . In this commit, examples related to SpatialObjects and RegistrationITKV4 have been enclosed with try catch block.
> STYLE: Enclose the majority of the main function in a try-catch block for Examples/SpatialObjects and Examples/RegistrationITKV4

- Modules/Remote/Montage.remote.cmake
This should be merged to release and master too. Trying to clean up build warnings on the nightly dashboard: https://open.cdash.org/viewBuildError.php?type=1&buildid=10305778.
> ENH: Update Montage remote module mostly to fix warnings

- Modules/Remote/MorphologicalContourInterpolation.remote.cmake
Trying to address `Modules/Remote/MorphologicalContourInterpolation/test/itkMorphologicalContourInterpolationTest.cxx:37:34: warning: unused variable 'reg' [-Wunused-variable]`, as raised here: https://open.cdash.org/viewBuildError.php?type=1&buildid=10311654
To be merged into `master` and `release-5.4` too.
> ENH: Update MorphologicalContourInterpolation module to fix warnings

- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
Following C++ Core Guidelines, [For “in” parameters, pass cheaply-copied types by value and others by reference to `const`](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rf-in)
> STYLE: Let MersenneTwisterRandomVariateGenerator pass integers by value

- Modules/IO/JPEG/src/itkJPEGImageIO.cxx
Remove constexpr for runtime value `cinfo`.
Fixed a Visual C++ x86 (32-bit) error:
```log
error C2131: expression did not evaluate to a constant
```
> COMP: Remove constexpr from check on runtime value in JPEGImageIO

- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
- Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx
A few style improvements for `MersenneTwisterRandomVariateGenerator`.
> MersenneTwisterRandomVariateGenerator: Rename `state` member variable, remove `this->`, move inline functions in-class, add `static`

- Modules/Filtering/ImageCompose/test/itkComposeBigVectorImageFilterTest.cxx
This test is timing out on nightly valgrind and coverage builds.
These changes may reduce the number of temporaries heap allocations used, and improve performance. Local test in debug mode, improve performance by more than 10%.
> PERF: Use region iterator image ComposeBigVectorImageFilter

- Modules/Core/Common/test/itkNumericTraitsTest.cxx
Include `itkNumericTraitsCovariantVectorPixelType.h` header file in test so that the appropriate definitions are available.
Fixes:
```
/Users/builder/externalModules/Core/Common/test/itkNumericTraitsTest.cxx:151:112:
warning: instantiation of variable 'itk::NumericTraits<itk::CovariantVector<char, 1> >::Zero'
required here, but no definition is available [-Wundefined-var-template]
std::cout << "\tZero: " << static_cast<typename itk::NumericTraits<T>::PrintType>((T)(itk::NumericTraits<T>::Zero))
^
/Users/builder/externalModules/Core/Common/test/itkNumericTraitsTest.cxx:430:3:
note: in instantiation of function template specialization
'(anonymous namespace)::CheckFixedArrayTraits<itk::CovariantVector<char, 1> >' requested here …
```
> COMP: Include `itkNumericTraitsCovariantVectorPixel.h` file in test

- Modules/Core/Common/include/itkResourceProbe.hxx
Replaced `this->m_` with `m_` in "itkResourceProbe.hxx". Removed parentheses
from `++(m_NumberOfStarts)` and `++(m_NumberOfStops)`.
Following [section "Accessing Members" of ITK's Coding Style Guide](https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/blob/v5.4.3/SoftwareGuide/Latex/Appendices/CodingStyleGuide.tex#L1708)
> STYLE: Remove `this->` on access to private data ResourceProbe

- Documentation/docs/index.md
- Documentation/docs/learn/faq.md
- Documentation/docs/learn/metaio.md
This adds the MetaIO documentation from the ITK MediaWiki wiki, which is
no longer available online.
The content is generated from the March 25th, 2025 Internet Archive
Wayback Machine Archive:
https://web.archive.org/web/20250324151047/https://itk.org/Wiki/ITK/MetaIO/Documentation
With Perplexity.ai, Gemini 2.5 Pro model:
https://www.perplexity.ai/search/convert-the-attached-mediawiki-JJ7Shb.OQkar6ClwXC_puA
And wordwrapping, a few updates for supported compilers, etc.
> DOC: Add MetaIO documentation from the ITK Wiki

- Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx
Five little style improvements in the implementation of MersenneTwisterRandomVariateGenerator.
> MersenneTwisterRandomVariateGenerator: Simplify `GetNextSeed()`, and other style improvements

- Modules/Core/Common/include/itkExtractImageFilter.hxx
`ExtractImageFilter::GenerateOutputInformation()` has returned already when the input is null. So the "cannot cast input" exception at the end of the member function will never occur anymore.
- Follow-up to pull request #4608 commit 6650d2ce9036f4173f41322e01a905079f9bdab8
"STYLE: Simplify code to remove unneeded dynamic_cast", Hans Johnson (@hjmjohnson), May 1, 2024
----
🤓 When reviewing, it may be helpful to ignore whitespace changes: https://github.com/InsightSoftwareConsortium/ITK/pull/5319/files?w=1
In the original code, you can see that the member function already does `return` earlier, when the input is null: https://github.com/InsightSoftwareConsortium/ITK/blob/375ee8c47a03792d0d3d5447c6b4c4be6b9f2fb4/Modules/Core/Common/include/itkExtractImageFilter.hxx#L109-L120
> STYLE: Remove redundant input check from ExtractImageFilter

- Modules/Core/Common/include/itkExtractImageFilter.hxx
- Modules/Core/Common/include/itkInPlaceImageFilter.hxx
- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshLineCell.hxx
- Modules/Core/TestKernel/include/itkTestingExtractSliceImageFilter.hxx
- Modules/Filtering/ImageCompose/include/itkJoinSeriesImageFilter.hxx
- Modules/Filtering/ImageStatistics/include/itkProjectionImageFilter.hxx
- Modules/Numerics/Statistics/include/itkHistogramToImageFilter.hxx
- Modules/Segmentation/Classifiers/include/itkImageGaussianModelEstimator.hxx
- Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.hxx
- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkMRFImageFilter.hxx
A few style commits, using the fact that dimensions are defined as `constexpr unsigned int`.
> Add `constexpr` to `if` when comparing dimensions, remove a few unnecessary `static_cast`'s

- Modules/Core/ImageFunction/include/itkBSplineDecompositionImageFilter.hxx
- Modules/Filtering/ImageFeature/include/itkCannyEdgeDetectionImageFilter.h
- Modules/Filtering/ImageFilterBase/include/itkBoxImageFilter.h
- Modules/Filtering/ImageGrid/include/itkBSplineCenteredResampleImageFilterBase.h
- Modules/Filtering/ImageGrid/include/itkPadImageFilter.h
- Modules/Filtering/ImageGrid/include/itkPadImageFilterBase.h
- Modules/Filtering/ImageStatistics/include/itkAccumulateImageFilter.hxx
- Modules/Filtering/LabelMap/include/itkBinaryImageToLabelMapFilter.h
- Replaced `using SizeValueType = typename TInputImage::SizeValueType` with `using SizeValueType = itk::SizeValueType`.
- Replaced `typename TInputImage::SizeValueType` with `SizeValueType`.
In practice, `TInputImage::SizeValueType` is always just an alias of `itk::SizeValueType` anyway.
---
Clarification: The image types of ITK are derived from `itk::ImageBase<VImageDimension>`, which defines `itk::ImageBase::SizeValueType = itk::Size<VImageDimension>::SizeValueType`, as follows:
https://github.com/InsightSoftwareConsortium/ITK/blob/0751ace2961d5bc066dbe06fab4ab007ea13efb8/Modules/Core/Common/include/itkImageBase.h#L149-L151
And `itk::Size<VImageDimension>::SizeValueType = itk::SizeValueType`, as defined at https://github.com/InsightSoftwareConsortium/ITK/blob/0751ace2961d5bc066dbe06fab4a …
> Replace `TInputImage::SizeValueType` with `itk::SizeValueType`

- Modules/Core/Common/include/itkConstNeighborhoodIterator.hxx
- Modules/Core/Common/include/itkConstNeighborhoodIteratorWithOnlyIndex.hxx
- Modules/Core/Common/include/itkFiniteCylinderSpatialFunction.hxx
- Modules/Core/Common/include/itkImportImageFilter.hxx
- Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.hxx
- Modules/Filtering/BinaryMathematicalMorphology/include/itkObjectMorphologyImageFilter.hxx
- Modules/Filtering/DistanceMap/include/itkSignedMaurerDistanceMapImageFilter.hxx
- Modules/Filtering/DistanceMap/test/itkContourMeanDistanceImageFilterTest.cxx
- Modules/Filtering/DistanceMap/test/itkDirectedHausdorffDistanceImageFilterTest1.cxx
- Modules/Filtering/DistanceMap/test/itkHausdorffDistanceImageFilterTest.cxx
- Modules/Filtering/ImageFeature/include/itkHessianRecursiveGaussianImageFilter.hxx
- Modules/Filtering/ImageGradient/include/itkGradientRecursiveGaussianImageFilter.hxx
- Modules/Filtering/LabelMap/include/itkShapeLabelMapFilter.hxx
- Modules/Filtering/MathematicalMorphology/include/itkFlatStructuringElement.hxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest.h
- Modules/IO/NIFTI/test/itkNiftiImageIOTest3.cxx
- Modules/Registration/Common/include/itkRecursiveMultiResolutionPyramidImageFilter.hxx
- Modules/Registration/GPUPDEDeformable/include/itkGPUDemonsRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkDemonsRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkESMDemonsRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkFastSymmetricForcesDemonsRegistrationFunction.hxx
- Modules/Registration/PDEDeformable/include/itkSymmetricForcesDemonsRegistrationFunction.hxx
- Modules/Segmentation/LevelSets/include/itkParallelSparseFieldLevelSetImageFilter.hxx
- Modules/Segmentation/LevelSets/include/itkSparseFieldFourthOrderLevelSetImageFilter.hxx
- Modules/Segmentation/LevelSets/include/itkSparseFieldLevelSetImageFilter.hxx
- Modules/Segmentation/Watersheds/include/itkWatershedSegmenter.hxx
Replaced `static_cast<(\w+)>\(([A-Za-z]*Dimension)\)` with `$1{ $2 }`, using regular expressions.
Excluded [`static_cast<double>(SizeAccumulateDimension)`](https://github.com/InsightSoftwareConsortium/ITK/blob/3c574f611d983e3c1f763d630a48a30c87940cd9/Modules/Filtering/ImageStatistics/include/itkAccumulateImageFilter.hxx#L162), as it is not a compile-time constant expression.
Following C++ Core Guidelines, ["Avoid casts"](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es48-avoid-casts)
----
Unlike `static_cast<T>(Dimension)`, `T{ Dimension }` checks at compile-time that the dimension can be converted losslessly, for example: https://godbolt.org/z/Eoc9fhnnz
```cpp
static constexpr unsigned int SmallDimension{ 2 };
static constexpr unsigned int LargeDimension{ UINT_MAX }; …
```
> STYLE: Replace `static_cast<T>(Dimension)` with `T{ Dimension }`

- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
- Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx
Allowed `New()`, `GetInstance()`, and the default-constructor of `MersenneTwisterRandomVariateGenerator` to initialize a
generator object without locking its `m_InstanceMutex`.
Implemented by adding two private member functions: `InitializeWithoutMutexLocking(IntegerType)` and `CreateRandomSeed()`.
> Allow initializing MersenneTwisterRandomVariateGenerator without mutex locking 

- Modules/Core/Transform/test/itkScaleTransformTest.cxx
Test the `itk::ScaleTransform::SetIdentity` method: check that after setting the scale to a non-identity value, the method effectively sets the scale to the identity.
> ENH: Test the `itk::ScaleTransform::SetIdentity` method

- Modules/IO/NIFTI/test/itkNiftiImageIOTest12.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest13.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest14.cxx
Increase NIfTI test input argument check consistency:
- Increase consistency in the missing argument check message: follow the ITK SW guide coding guidelines. Specifically, make the error message be consistent.
- Add the test name and input parameters to the error message where missing. Specifically, use the `itkNameOfTestExecutableMacro(argv)` macro call to print the test message.
> STYLE: Increase NIfTI test argument check consistency

- Modules/Core/ImageFunction/include/itkBSplineDecompositionImageFilter.hxx
Coding style improvements to `BSplineDecompositionImageFilter::SetInitialCausalCoefficient`:
- Replaced `1L` with `1`, to avoid platform dependent behavior because of `sizeof(long)`
- Replaced C-style cast, `(SizeValueType)`, with `static_cast<SizeValueType>`
- Replaced `itk::Math::abs(z)` with `std::abs(z)`
- Reduced the scope of the `horizon` variable, skipping initialization "to mirror boundaries" by returning early.
----
🤓  When reviewing, it may help to hide whitespace changes: https://github.com/InsightSoftwareConsortium/ITK/pull/5332/files?w=1
> `BSplineDecompositionImageFilter::SetInitialCausalCoefficient`: Reduced scope of local `horizon` and other style commits

- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
The original overload sets of `Initialize` and `SetSeed` made things unnecessarily compilated: `Initialize()` was implemented by `SetSeed()`. `SetSeed()` was then implemented by calling the other `SetSeed` overload. Which would call the other `Initialize` overload. Schematically: `Initialize()` &rarr; `SetSeed()` &rarr; `SetSeed(seed)` &rarr; `Initialize(seed)`.
With this pull request, there will be just one `SetSeed(seed)`, and one `Initialize(seed)`. `SetSeed` will just call `Initialize`.
Also removed the commented out member functions `load` and `save`.
Aim: simplifying the code.
> MersenneTwisterRandomVariateGenerator: Remove Initialize and SetSeed overloads, remove commented out member functions

- Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx
A minor style improvement, aiming to improve code readability.
> Remove `MersenneTwisterRandomVariateGenerator::` prefixes within its implementation

- Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmJPEG2000Codec.cxx
When an unsupported JPEG2000 encoding was encountered, resources need to be release. This addresses issue with repeated reading problematic files allocated threads until system limits were reached resulting in deadlock.
> BUG: GDCM destroy JPEG2000 structures on error

- Documentation/Maintenance/Release.md
- Documentation/docs/learn/faq.md
- Documentation/docs/releases/4.0.md
- Documentation/docs/releases/4.5.md
- Modules/Core/Common/CMakeLists.txt
- Modules/IO/ImageBase/include/itkImageFileReader.hxx
- Modules/IO/ImageBase/include/itkImageFileWriter.hxx
- Modules/IO/Meta/include/itkMetaImageIO.h
- Modules/IO/TransformBase/src/itkTransformFileReader.cxx
- Modules/IO/TransformBase/src/itkTransformFileWriterSpecializations.cxx
- Utilities/Debugger/ITK.natvis
- Utilities/Doxygen/DoxygenConfig.cmake
- Utilities/Maintenance/UpdateCopyrightStatementsInITK.py
The ITK MediaWiki instance is no longer available. Update links to point
to an archive hosted on GitHub Pages.
> DOC: Update Wiki links to GitHub Pages archive

- Documentation/docs/learn/metaio.md
Explicitly specified the number of bits of integer and floating point types.
Aims to clarify possible confusion about `MET_LONG` and `MET_ULONG`, as the size of the C++ type `long` is platform specific.
> DOC: Add table to describe MetaIO/MetaImage ElementType tag

- .github/workflows/itk_dict.txt
- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
- Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx
- Modules/Core/Common/test/itkMersenneTwisterRandomVariateGeneratorGTest.cxx
- Modules/Registration/Common/test/itkImageRegistrationMethodTest_14.cxx
- Modules/Registration/Common/test/itkImageRegistrationMethodTest_15.cxx
- Modules/Registration/Common/test/itkImageRegistrationMethodTest_17.cxx
- Modules/Registration/Common/test/itkMattesMutualInformationImageToImageMetricTest.cxx
- Modules/Registration/Common/test/itkMultiResolutionImageRegistrationMethodTest_1.cxx
- Modules/Registration/Common/test/itkMultiResolutionImageRegistrationMethodTest_2.cxx
- Modules/Registration/RegistrationMethodsv4/test/itkSimpleImageRegistrationTest.cxx
Added `MersenneTwisterRandomVariateGenerator::DefaultSeed`
It appears useful to have a named constant for this value, for ITK as well as for [elastix](https://github.com/SuperElastix/elastix).
Following C++ Core Guidelines, [Avoid “magic constants”; use symbolic constants](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es45-avoid-magic-constants-use-symbolic-constants)
> Add `DefaultSeed = 121212` to MersenneTwisterRandomVariateGenerator

- Modules/Core/ImageAdaptors/test/itkComplexConjugateImageAdaptorTest.cxx
Modernized the code. Also improved the style, by removing `static_cast<float>`s.
> STYLE: Replace `rand()` calls with `std::mt19937` in ImageAdaptor test

- Modules/Core/Common/include/itkGaussianKernelFunction.h
- Modules/Core/Common/include/itkVector.hxx
- Modules/Core/ImageFunction/include/itkMeanImageFunction.hxx
- Modules/Core/ImageFunction/include/itkSumOfSquaresImageFunction.hxx
- Modules/Core/ImageFunction/test/itkSumOfSquaresImageFunctionGTest.cxx
- Modules/Core/SpatialObjects/include/itkImageMaskSpatialObject.hxx
- Modules/Filtering/AnisotropicSmoothing/include/itkGradientNDAnisotropicDiffusionFunction.hxx
- Modules/Filtering/AnisotropicSmoothing/include/itkVectorAnisotropicDiffusionFunction.hxx
- Modules/Filtering/Colormap/include/itkCustomColormapFunction.hxx
- Modules/Filtering/ImageGradient/include/itkVectorGradientMagnitudeImageFilter.h
- Modules/Filtering/ImageGradient/test/itkGradientRecursiveGaussianFilterTest3.cxx
- Modules/Filtering/Smoothing/include/itkMeanImageFilter.hxx
- Modules/Filtering/Smoothing/test/itkMeanImageFilterGTest.cxx
- Modules/Filtering/Smoothing/test/itkMedianImageFilterGTest.cxx
- Modules/IO/TIFF/src/itkTIFFImageIO.cxx
- Modules/Segmentation/LevelSets/include/itkLevelSetFunctionWithRefitTerm.hxx
- Modules/Segmentation/LevelSets/include/itkNormalVectorDiffusionFunction.hxx
- Modules/Segmentation/LevelSets/include/itkSparseFieldFourthOrderLevelSetImageFilter.hxx
- Modules/Segmentation/LevelSets/include/itkSparseFieldLevelSetImageFilter.hxx
- Modules/Segmentation/RegionGrowing/include/itkConfidenceConnectedImageFilter.hxx
Two little style commits:
- Replace `auto var = T{}` with `T var{}`
- Replace `auto var = T{ x }` with `T var{ x }`
Note that these proposed changes are not at all in disagreement  with clang-tidy [modernize-use-auto](https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-auto.html). 😃
> Replace `auto var = T{...}` with `T var{...}`

- Modules/Core/Common/include/itkImageRandomNonRepeatingConstIteratorWithIndex.h
- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
- Modules/Core/Common/src/itkMersenneTwisterRandomVariateGenerator.cxx
- Modules/Core/Common/test/itkCompensatedSummationTest.cxx
- Modules/Core/Common/test/itkMersenneTwisterRandomVariateGeneratorTest.cxx
- Modules/Filtering/ImageNoise/include/itkSaltAndPepperNoiseImageFilter.hxx
- Modules/Filtering/ImageNoise/include/itkShotNoiseImageFilter.hxx
- Modules/Filtering/ImageNoise/include/itkSpeckleNoiseImageFilter.hxx
- Modules/Numerics/Statistics/test/itkKdTreeTest1.cxx
- Modules/Numerics/Statistics/test/itkKdTreeTest3.cxx
- Modules/Numerics/Statistics/test/itkWeightedCentroidKdTreeGeneratorTest1.cxx
- Modules/Numerics/Statistics/test/itkWeightedCentroidKdTreeGeneratorTest8.cxx
- Modules/Numerics/Statistics/test/itkWeightedCentroidKdTreeGeneratorTest9.cxx
- Modules/Registration/Common/test/itkMeanSquaresImageMetricTest.cxx
The MersenneTwisterRandomVariateGenerator member function `Initialize` behaves just like `SetSeed`, but `SetSeed` is more commonly used, and clearer.
> FUTURE REMOVE `MersenneTwisterRandomVariateGenerator::Initialize`

- Modules/Segmentation/MarkovRandomFieldsClassifiers/include/itkRGBGibbsPriorFilter.hxx
The original division of `rand()` by `32768.0` was probably meant to yield a number between `[0, 1>`. However, `rand()` returns an integer between `[​0​, RAND_MAX]`, and `RAND_MAX` may not be `32767`. In practice, when using GCC, `RAND_MAX` may be as large as `2147483647`.
The "magic number" `32768.0` was introduced on 12 Jan 2002 already, with commit 074c74f036a7faea5555a6125a2c740d1afe7caa.
> BUG: Fix random number in `RGBGibbsPriorFilter::GibbsTotalEnergy`

- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
- Modules/IO/GDCM/test/Baseline/itkGDCMImageIOTestIntToUint.mha.cid
- Modules/IO/GDCM/test/CMakeLists.txt
- Modules/IO/GDCM/test/Input/030658_001.dcm.cid
Dicomfile with signed int data (pixel rep=1) can be decoded as uint with the correct intercept. The assertion blocking this behavior has been changed to a more meaningful check.
Closes #5290
With a dicom image stored as short, which has a rescaling into the "unsigned short".
```
Bits allocated 16
Bits stored 16
High Bit 15
Pixel Representation 1
Rescale Intercept 32768
Rescale Slope 1
Rescale Type US
```
The following code was not working before this commit, and now works correctly:
```cpp
#include <iostream>
#include <itkImageFileReader.h>
#include <itkGDCMImageIO.h>
int
main(int argc, char ** argv)
{
const auto path = "<myfilepath>";
using ReaderType = itk::ImageFileReader<itk::Image<uint16_t, 2>>;
typename ReaderType::Pointer reader = ReaderType::New();
reader->SetFileName(path); …
```
> BUG: Allow rescaling int to uint of same size

- Modules/IO/ImageBase/include/itkImageSeriesReader.hxx
> ENH: Add printing of FileNames to ImageSeriesReader

- Testing/ContinuousIntegration/AzurePipelinesBatch.yml
- Testing/ContinuousIntegration/AzurePipelinesLinux.yml
- Testing/ContinuousIntegration/AzurePipelinesLinuxPython.yml
- Testing/ContinuousIntegration/AzurePipelinesMacOS.yml
- Testing/ContinuousIntegration/AzurePipelinesMacOSPython.yml
- Testing/ContinuousIntegration/AzurePipelinesWindows.yml
- Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
Azure Pipelines recently dropped ubuntu-20.04 support:
https://devblogs.microsoft.com/devops/upcoming-updates-for-azure-pipelines-agents-images/
Also bump the ExternalData version to 5.4.3.
> Linux azure images ubuntu 20.04 deprecation

- Modules/Core/Common/test/itkIndexRangeGTest.cxx
It is recommended to use C++11's random number generation facilities (like `std::mt19937`) to replace `rand()`, according to
https://en.cppreference.com/w/cpp/numeric/random/rand
> STYLE: Replace `std::rand()` with `std::mt19937` in IndexRangeGTest

- Documentation/Maintenance/Release.md
Clarify further remote module major version bumps with ITK minor releases.
> DOC: Clarify further remote module version bumps with ITK minor releases

- Modules/Remote/IOScanco.remote.cmake
Change `IOScanco` remote module GitHub organization to `InsightSoftwareConsortium` after transferring it from `KitwareMedical` by Dženan Zukić on May, 27 2025.
> STYLE: Change `IOScanco` remote module GitHub organization

- Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmRAWCodec.cxx
Replace 'assert' with `return false' for a file with erroneous BitsAllocated=12 value.
Closes [#5364](https://github.com/InsightSoftwareConsortium/ITK/issues/5364)
> BUG: fix GDCM crash due to malformed file

- Modules/IO/TIFF/include/itkTIFFImageIO.h
- Modules/IO/TIFF/src/itkTIFFImageIO.cxx
- Modules/IO/TIFF/test/Baseline/TestTIFFCompression_RGBTestImageJPEG_AdobeDeflate.tif.cid
- Modules/IO/TIFF/test/Baseline/TestTIFFCompression_cthead1_AdobeDeflate.tif.cid
- Modules/IO/TIFF/test/CMakeLists.txt
- Modules/IO/TIFF/test/itkTIFFImageIOCompressionTest.cxx
Enables addressing the following warning:
TIFFWriteDirectorySec: Warning, Creating TIFF with legacy Deflate codec identifier, COMPRESSION_ADOBE_DEFLATE is more widely supported.
> ENH: Enable Adobe Deflate Option for TIFF compression

- Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
- Modules/IO/NIFTI/test/CMakeLists.txt
- Modules/IO/NIFTI/test/itkNiftiReadWriteDirectionTest.cxx
The following error occurs occasionally that causes the test to fail.  It is very hard to replicate consistently.
```
Trying itk::WriteImage(inputImageNoSform, testFilename)
ITK test driver caught an ITK exception:
itk::ImageFileReaderException (000000CF6E0FF570)
Location: "unknown"
File: T:\Dashboard\ITK\Modules\IO\ImageBase\include\itkImageFileReader.hxx
Line: 137
Description:  Could not create IO object for reading file T:/Dashboard/ITK-build/Testing/Temporary/ITKIONIFTI/test_filled_sform.nii.gz
Tried to create one of the following:
MetaImageIO
GDCMImageIO
JPEGImageIO
VTKImageIO
PNGImageIO
TIFFImageIO
BMPImageIO
NrrdImageIO
GiplImageIO
NiftiImageIO
You probably failed to set a file suffix, or
set the suffix to an unsupported type.
```
The hypothesis is that the file is somehow cached …
> BUG:  itkNiftiReadWriteDirectionTest is unstable

- Modules/Core/Common/include/itkMacro.h
- Modules/IO/ImageBase/include/itkImageSeriesWriter.hxx
- Modules/IO/TIFF/src/itkTIFFReaderInternal.cxx
Not sure if this works with gcc...
> COMP: fixed some clang -Wformat-nonliteral warnings

- Wrapping/Generators/Python/Tests/extras.py
- Wrapping/Generators/Python/itk/support/extras.py
- Wrapping/Generators/Python/itk/support/init_helpers.py
Enforce black formatting to keep aligned with pre-commit
hook enforcements.
> STYLE: Set black formatting of python files

- Modules/IO/Bruker/src/itkBruker2dseqImageIO.cxx
- Modules/IO/ImageBase/include/itkImageFileReader.hxx
- Modules/IO/ImageBase/src/itkImageIOBase.cxx
- Modules/IO/MRC/src/itkMRCImageIO.cxx
- Modules/IO/MeshBase/include/itkMeshFileReader.hxx
- Modules/IO/MeshBase/include/itkMeshIOBase.h
- Modules/IO/MeshBase/src/itkMeshIOBase.cxx
- Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
- Modules/IO/VTK/include/itkVTKImageIO.h
- Modules/IO/VTK/src/itkVTKImageIO.cxx
- Modules/Video/IO/include/itkVideoFileReader.hxx
Follow-up to commit 2cedb035e9c35a22236c4b64de7cd621c1415b92, "ENH: Make string/type conversion functions static in ImageIOBase", David Doria, May 10, 2011.
Adjusted the calls to those member functions, following [clang-tidy static-accessed-through-instance](https://clang.llvm.org/extra/clang-tidy/checks/readability/static-accessed-through-instance.html
) ("Checks for member expressions that access static members through instances").
>  Make `GetComponentTypeAsString` and `GetPixelTypeAsString` functions static 

- Modules/Core/Common/include/itkMersenneTwisterRandomVariateGenerator.h
Deprecated.
For:
D:\a\1\s-build\Wrapping\Modules\ITKCommon\ITKCommonBasePython.cpp(35589): warning C4996: 'itk::Statistics::MersenneTwisterRandomVariateGenerator::Initialize': ITK 6 discourages using this member function. Please use `SetSeed` instead!
> COMP: Do not wrap MersenneTwisterRandomVariateGenerator::Initialize

- Testing/ContinuousIntegration/AzurePipelinesBatch.yml
- Testing/ContinuousIntegration/AzurePipelinesWindows.yml
- Testing/ContinuousIntegration/AzurePipelinesWindowsPython.yml
Refactored YAML configurations to replace `windows-2019` with `windows-2022` VM image, ensuring compatibility with updated environments.
The Azure Windows Server 2019 image will be removed on 2025-06-30. For more details, see https://github.com/actions/runner-images/issues/12045
Supersedes and closes #5412.
> ENH: Update Azure Pipelines to use windows-2022

- Modules/IO/ImageBase/include/itkImageIOBase.h
- Modules/IO/ImageBase/src/itkImageIOBase.cxx
This member function was already deprecated according to its documentation, as was committed by 6ff5fc7f01148bd11070c5ecfe0d56f643f62565, Kent Williams, Feb 9, 2011.
----
`GetComponentTypeInfo()` is somewhat redundant, because the `std::type_info` of the currently selected Component Type can be retrieved by calling `GetComponentType()` (which returns an `IOComponentEnum` value), and then figuring out which C++ type is mapped to this `IOComponentEnum` value, using `MapPixelType<TPixel>::CType` from https://github.com/InsightSoftwareConsortium/ITK/blob/7bb595b2b554a0083095022db6aae5188dbc30b2/Modules/IO/ImageBase/include/itkImageIOBase.h#L577-L580 
It's not really straightforward, but it works, most of the times.
- Aims to supersede pull request #5393
> STYLE: ITK_LEGACY_REMOVE/deprecate `ImageIOBase::GetComponentTypeInfo()`

- Modules/Filtering/ImageIntensity/include/itkHistogramMatchingImageFilter.hxx
Fix the two Valgrind-identified failures.
The incorrect manual refactoring of itkHistogramMatchingImageFilter.hxx in  1f374cfa4797cd580e1bbd1d5fbf59d996253297 changed the logic in a way
That would allow for uninitialized memory reads.
> Fix valgrind warnings

- Modules/Core/Common/include/itkThreadSupport.h
- Modules/Core/Common/src/itkPlatformMultiThreaderPosix.cxx
Use value initialization to zero-initialize thread id variable.
Fixes:
```
Core/Common/src/itkPlatformMultiThreader.cxx:35:
Core/Common/src/itkPlatformMultiThreaderPosix.cxx:172:28:
warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
172 |   pthread_t threadHandle = 0;
|                            ^
|                            nullptr
[CTest: warning suppressed] 1 warning generated.
```
https://open.cdash.org/viewBuildError.php?type=1&buildid=10477917
and
```
ITK/Modules/Core/Common/include/itkThreadSupport.h:45:55:
warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
45 | constexpr ThreadProcessIdType ITK_DEFAULT_THREAD_ID = 0;
| …
```
> COMP: Use value initialization to zero-initialize thread id variable

- Modules/Core/Common/include/itkImageRegion.h
- Modules/Core/Common/include/itkMacro.h
- Modules/IO/ImageBase/src/itkImageIOBase.cxx
- removed workaround for Xcode 10
- emit #error for AppleClang less than Xcode 12.4
- removed workaround for broken fail() added in 1fcd00774bf65728cc4c9e2e7f10750a48334ca2 in 2003. Hopefully the workaround is no longer needed. I'm not sure, but all tests pass on my arm64 macOS 15.5.
Related to issue #5369.
> COMP: removed workarounds for old Apple stuff

- Examples/Filtering/FFTImageFilter.cxx
- Examples/IO/DicomImageReadPrintTags.cxx
Replaced function calls of the form `instance->MemberFunction(x)` with `itk::T::MemberFunction(x)`, for the static member functions `GetPixelTypeAsString` and `GetComponentTypeAsString`, in Examples.
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/5391 commit 45e93bbde02a67dcaa5ed3fdb51bd6599b7a95e3
> STYLE: Don't call static TypeAsString functions via instances (Examples)

- Utilities/SetupForDevelopment.sh
Some configurations may encounter:
warning: branch.main.rebase has multiple values
error: cannot overwrite multiple values with a single value
Use a regexp, --add or --replace-all to change branch.main.rebase.
> BUG: Use --replace-all for branch.main.rebase config

- Documentation/docs/download.md
A fix for the links on download page - they were still referring to the 5.4.3 release files, while the link text already said 5.4.4; see also [ITK discourse forum post](https://discourse.itk.org/t/itk-5-4-4-has-been-released/7565/2) and [this related commit for the release itself](https://github.com/InsightSoftwareConsortium/ITK/commit/6d0bafddea40c642ed6ae5b776eeefc9e29180a8).
> DOC: Fix links to 5.4.4 release artifacts on download page

- .pre-commit-config.yaml
- Utilities/Hooks/run-pixi-python.sh
Python may not be available on Windows systems. Use a launcher script to run local Python pre-commit hooks with the Python executable we generate when bootstrapping our pre-commit hooks. The launcher script uses the local Python, which we know will be available and have a sufficient version. It also allows adjusting the path with Windows vs Unix.
> BUG: Use launcher for local Python pre-commit hooks

- Modules/IO/MeshBase/include/itkMeshIOBase.h
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/5421 commit b209c1a00f2cc042172996631d8cf5a06658fd1a
"STYLE: Remove template specializations of `ImageIOBase::MapPixelType`"
Note that `MeshIOBase::MapComponentType` supports `long double` as pixel component type, whereas `ImageIOBase::MapPixelType` does not. Moreover, `MeshIOBase::MapComponentType` unconditionally maps `char` to `CHAR`, whereas `ImageIOBase::MapPixelType` maps `char` to either `CHAR` or `UCHAR`, depending on the signedness of `char`.
> STYLE: Remove template specializations of `MeshIOBase::MapComponentType`

- Modules/Core/Common/include/itkCommonEnums.h
- Modules/Core/TestKernel/src/itkTestDriverInclude.cxx
- Modules/IO/ImageBase/include/itkImageFileReader.hxx
- Modules/IO/ImageBase/src/itkImageIOBase.cxx
- Modules/IO/MeshBase/include/itkMeshFileReader.hxx
- Modules/IO/TIFF/test/itkTIFFImageIOCompressionTest.cxx
- Modules/Video/IO/include/itkVideoFileReader.hxx
- Added a note about `IOComponent::CHAR` representing `signed char`
- Let file readers interpret the `CHAR` enum as `signed char` (instead of just plain `char`)
- Adjusted tests accordingly
Triggered by a discussion with Bradley (@blowekamp) at https://discourse.itk.org/t/long-double-support-for-imageio-meshio-pixels/7570/11 and his comment at https://github.com/InsightSoftwareConsortium/ITK/pull/5449#issuecomment-3032091149
> Let `IOComponent::CHAR` represents `signed char`

- Modules/IO/ImageBase/include/itkImageIOBase.h
- Modules/IO/ImageBase/test/itkImageIOBaseTest.cxx
- Modules/IO/Meta/src/itkMetaImageIO.cxx
Added a static member function, `ImageIOBase::GetComponentTypeFromTypeTraits(bool isFloatingPoint, bool isUnsigned, size_t numberOfBits)`, to ease retrieving the appropriate pixel component type.
Used this member function to clean up `MetaImageIO::ReadImageInformation()`, by removing the 48 `this->SetComponentType` calls from its `switch`.
> Add `ImageIOBase::GetComponentTypeFromTypeTraits(isFloatingPoint, isUnsigned, numberOfBits)`

- Modules/Core/Common/test/itkBSplineInterpolationWeightFunctionTest.cxx
- Modules/Core/Common/test/itkConstNeighborhoodIteratorWithOnlyIndexTest.cxx
- Modules/Core/Common/test/itkImageAlgorithmCopyTest.cxx
- Modules/Core/Common/test/itkImageRegionConstIteratorWithOnlyIndexTest.cxx
- Modules/Core/Common/test/itkImageVectorOptimizerParametersHelperTest.cxx
- Modules/Core/Common/test/itkMultiThreaderParallelizeArrayTest.cxx
- Modules/Core/Common/test/itkSimpleFilterWatcherTest.cxx
- Modules/Filtering/AntiAlias/test/itkAntiAliasBinaryImageFilterTest.cxx
- Modules/Filtering/ImageCompose/test/itkJoinImageFilterTest.cxx
- Modules/Filtering/ImageFrequency/test/itkFrequencyIteratorsGTest.cxx
- Modules/Filtering/ImageIntensity/test/itkShiftScaleImageFilterTest.cxx
- Modules/IO/ImageBase/test/itkImageFileReaderDimensionsTest.cxx
- Modules/IO/NIFTI/test/itkNiftiImageIOTest11.cxx
- Modules/Registration/Common/test/itkImageRegistrationMethodTest.cxx
- Modules/Registration/Common/test/itkImageRegistrationMethodTest_11.cxx
- Modules/Registration/Common/test/itkMultiResolutionImageRegistrationMethodTest.cxx
- Modules/Segmentation/LevelSets/test/itkCannySegmentationLevelSetImageFilterTest.cxx
- Modules/Segmentation/LevelSets/test/itkLaplacianSegmentationLevelSetImageFilterTest.cxx
- Modules/Segmentation/LevelSets/test/itkNarrowBandThresholdSegmentationLevelSetImageFilterTest.cxx
- Modules/Segmentation/LevelSets/test/itkThresholdSegmentationLevelSetImageFilterTest.cxx
- Modules/Segmentation/LevelSetsv4/test/itkBinaryImageToShiSparseLevelSetAdaptorTest.cxx
Replaced `itk::Image<char` with `itk::Image<signed char`, in all `"itk*Test*.cxx"` source files. Removed pixel type alias `InputDataType = char` from itkAntiAliasBinaryImageFilterTest, and directly used `signed char` instead.
The use of `char` as `TPixel` argument in tests appears to triggers test failures, when compiling with an unsigned default `char` type (GCC option `-funsigned-char` or MSVC option `/J`), for example:
[ RUN      ] FrequencyIterators.Even2D
Unequal images, with 29 unequal pixels
test/itkFrequencyIteratorsGTest.cxx:260: Failure
Value of: fullAndHermitian
Actual: false
Expected: true
It appears clearer to explicitly specify that the pixel type should be signed, by using `signed char` instead.
----
- Those test failures appeared with an experimental pull request: #5455 
- …
> STYLE: Replace `char` with `signed char` as itk::Image argument in tests

- Modules/IO/BMP/src/itkBMPImageIO.cxx
- Modules/IO/GIPL/src/itkGiplImageIO.cxx
- Modules/IO/ImageBase/src/itkRawImageIOUtilities.cxx
- Modules/IO/PhilipsREC/src/itkPhilipsRECImageIO.cxx
- Modules/IO/Stimulate/src/itkStimulateImageIO.cxx
When a buffer consists of elements of size `sizeof(char)`, the Swap member functions of `ByteSwapper` don't do anything.
> Remove unnecessary ByteSwapper Swap function calls for char types

- Modules/IO/Bruker/src/itkBruker2dseqImageIO.cxx
- Modules/IO/VTK/src/itkVTKImageIO.cxx
- Removed unnecessary `BYTE_SWAP` calls from `Bruker2dseqImageIO::SwapBytesIfNecessary`
- Removed expensive `MACRO(char)` calls from `VTKImageIO::Write`
- Follow-up to pull request #5466
> Remove byte swapping for pixel components of size 1 from Bruker2dseqImageIO and VTKImageIO

- Modules/IO/GDCM/include/itkGDCMImageIO.h
- Modules/IO/NRRD/include/itkNrrdImageIO.h
Add details on how to set metadata information that is specific to the NRRD and DICOM file formats.
> DOC: Add information to NRRD and GDCM IOs.

- Modules/Core/Common/include/itkCommonEnums.h
- Modules/Core/TestKernel/src/itkTestDriverInclude.cxx
- Modules/IO/BMP/src/itkBMPImageIO.cxx
- Modules/IO/Bruker/src/itkBruker2dseqImageIO.cxx
- Modules/IO/GDCM/src/itkGDCMImageIO.cxx
- Modules/IO/GIPL/src/itkGiplImageIO.cxx
- Modules/IO/HDF5/src/itkHDF5ImageIO.cxx
- Modules/IO/ImageBase/src/itkImageIOBase.cxx
- Modules/IO/MINC/src/itkMINCImageIO.cxx
- Modules/IO/MeshBYU/src/itkBYUMeshIO.cxx
- Modules/IO/MeshBase/include/itkMeshFileReader.hxx
- Modules/IO/MeshBase/include/itkMeshIOTestHelper.h
- Modules/IO/MeshBase/src/itkMeshIOBase.cxx
- Modules/IO/MeshFreeSurfer/src/itkFreeSurferAsciiMeshIO.cxx
- Modules/IO/MeshFreeSurfer/src/itkFreeSurferBinaryMeshIO.cxx
- Modules/IO/MeshGifti/src/itkGiftiMeshIO.cxx
- Modules/IO/MeshOBJ/src/itkOBJMeshIO.cxx
- Modules/IO/MeshOFF/src/itkOFFMeshIO.cxx
- Modules/IO/MeshVTK/src/itkVTKPolyDataMeshIO.cxx
- Modules/IO/Meta/src/itkMetaImageIO.cxx
- Modules/IO/NIFTI/src/itkNiftiImageIO.cxx
- Modules/IO/NRRD/src/itkNrrdImageIO.cxx
- Modules/IO/PhilipsREC/src/itkPhilipsRECImageIO.cxx
- Modules/IO/Stimulate/src/itkStimulateImageIO.cxx
- Modules/IO/TIFF/src/itkTIFFImageIO.cxx
- Modules/IO/TIFF/test/itkTIFFImageIOCompressionTest.cxx
- Modules/Segmentation/LabelVoting/test/itkVotingBinaryImageFilterTest.cxx
Replaced `CHAR` with `SCHAR` in `IOComponentEnum::CHAR` cases of `switch` statements.
The name `SCHAR` appears clearer than `CHAR`, because it is intended to specify a _signed_ char type. The abbreviation `SCHAR` is already used to denote `signed char` in C and C++ (`SCHAR_MAX`) as well as in HDF5 (`H5T_NATIVE_SCHAR`).
> Add `IOComponent` enum `SCHAR` for signed char (equivalent to `CHAR`)

- Modules/IO/ImageBase/include/itkImageFileReader.hxx
- Modules/IO/NRRD/include/itkNrrdImageIO.h
- Modules/IO/NRRD/itk-module.cmake
- Modules/IO/NRRD/src/itkNrrdImageIO.cxx
- Modules/IO/NRRD/test/CMakeLists.txt
- Modules/IO/NRRD/test/itkNrrd5dVectorImageReadWriteTest.cxx
- Modules/IO/NRRD/test/itkNrrdVectorImageUnitLabelReadTest.cxx
- Modules/IO/NRRD/wrapping/itkNrrdImageIO.wrap
- Testing/Data/Input/CTCardioCropped.seq.nrrd.cid
Several modern imaging devices and processing algorithms now creates 5D data sets, including:
- time sequence of 3D displacement fields (result of deformable registration of 4D images)
- time sequence of 3D velocity fields (acquired by 4D MRI flow images)
- time sequence of 3D color (RGB or RGBA) images (result of colorized volumes provided by AI segmentation)
NRRD IO can now read and write all these data types, and in general any 5D arrays (2 or 3 spatial dimensions + scalar/vector pixel type + optional list axis).
@hjmjohnson
@blowekamp
> ENH: Support 5D files in NRRD IO

- Modules/ThirdParty/Expat/src/expat/xmlparse.c
Hi Development Team,
I identified a potential integer overflow in clone functions in `Modules/ThirdParty/Expat/src/expat/xmlparse.c` sourced from [libexpat/libexpat](https://github.com/libexpat/libexpat). This issue, originally reported in [CVE-2022-22822](https://nvd.nist.gov/vuln/detail/CVE-2022-22822) to [CVE-2022-22822](https://nvd.nist.gov/vuln/detail/CVE-2022-22827), was resolved in the repository via this commit https://github.com/libexpat/libexpat/commit/9f93e8036e842329863bf20395b8fb8f73834d9e.
This PR applies the corresponding patch to fix the vulnerability in this codebase.
Please review at your convenience. Thank you!
> BUG: Prevent integer overflow in potential vulnerable cloned functions

- Modules/Bridge/VTK/include/itkVTKImageImport.hxx
- Modules/Core/Transform/include/itkBSplineBaseTransform.hxx
- Modules/Core/Transform/include/itkCompositeTransform.hxx
- Modules/Core/Transform/include/itkMultiTransform.hxx
- Modules/Core/Transform/include/itkTransform.hxx
- Modules/Core/Transform/include/itkVersorRigid3DTransform.hxx
- Modules/Filtering/DisplacementField/include/itkTimeVaryingBSplineVelocityFieldTransform.hxx
- Modules/IO/MeshBYU/src/itkBYUMeshIO.cxx
- Modules/IO/MeshFreeSurfer/src/itkFreeSurferAsciiMeshIO.cxx
- Modules/IO/MeshFreeSurfer/src/itkFreeSurferBinaryMeshIO.cxx
- Modules/IO/MeshGifti/src/itkGiftiMeshIO.cxx
- Modules/IO/MeshOBJ/src/itkOBJMeshIO.cxx
- Modules/IO/MeshOFF/src/itkOFFMeshIO.cxx
- Modules/IO/PNG/src/itkPNGImageIO.cxx
- Modules/Numerics/Optimizersv4/include/itkObjectToObjectMetric.hxx
- Modules/Registration/Common/include/itkMattesMutualInformationImageToImageMetric.hxx
- Modules/Registration/Common/include/itkMeanSquaresImageToImageMetric.hxx
- Modules/Registration/Metricsv4/include/itkMattesMutualInformationImageToImageMetricv4.hxx
It's uncommon and unnecessary to have an extra newline and flush at the end of an exception message. It is the responsibility of the one who prints the exception description to add a line break, if necessary (like `ExceptionObject::Print` does).
Note also that these `std::endl` manipulators were inserted into an `std::ostringstream`, and for `std::ostringstream`, flushing does not have any effect anyway.
Using Notepad++, Replace In Files:
Find what: (  itkExceptionMacro\([^)]+) << std::endl(\);)
Find what: (  itkExceptionMacro\([^;]+) << std::endl(\);)
Replace with: $1$2
Directory: D:\ITK\Modules\
[v] Match case
(*) Regular expression [v] . matches newline
> STYLE: Remove trailing `std::endl` inserts from itkExceptionMacro calls

- Modules/Core/Common/include/itkExceptionObject.h
- Modules/Core/Common/src/itkExceptionObject.cxx
Dropped support for an arbitrary number of arguments from this constructor. These variadic arguments were not necessary, and they were ignored anyway.
These variadic arguments were introduced with:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/5477 commit 868adae78a206e43b7f0c29b2c8fe89262bbd688
"ENH: Add object and class name to ExceptionObject constructor"
> STYLE: Remove variadic arguments (`...`) from ExceptionObject constructor

- Modules/Bridge/NumPy/include/itkPyBuffer.hxx
- Modules/Bridge/NumPy/include/itkPyVectorContainer.hxx
- Modules/Bridge/NumPy/include/itkPyVnl.hxx
No longer available in Python 3.14.
Use PySequence_GetItem. This returns a reference. In the use cases
(image dimensions), the performance impact is negligible.
> COMP: Avoid PySequence_Fast_GET_ITEM - ITK 6

- Modules/Core/Common/include/itkSymmetricEigenAnalysis.h
- Modules/Core/QuadEdgeMesh/include/itkGeometricalQuadEdge.h
- Modules/Core/QuadEdgeMesh/include/itkQuadEdge.h
- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshBaseIterator.h
- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshPoint.h
Replaced `[[nodiscard]] [[nodiscard]]` with `[[nodiscard]]`.
- Follow-up to pull request #5404 commit 85aa7bddf8d04b46cfdbfc8416301ddc301407f3 "STYLE: Use C++17 [[nodiscard]] attribute"
> STYLE: Remove accidentally duplicated `[[nodiscard]]` attributes

- Wrapping/Generators/CastXML/CMakeLists.txt
Better compiler support.
Use filenames consistent with the CastXMLSuperbuild build artifacts.
Use SHA256 hashes, which are offered by the GitHub Releases interface.
On Linux and Macos, these binaries require newer glibc and Macos
versions. These are to support updated GitHub Actions and manylinux
build environments.
> COMP: Update CastXML binaries to 2025.09.03

- Modules/Bridge/VtkGlue/itk-module-init.cmake
Commit bcb6876c7d9ed3315ed8cd2d3cdf9f0b11f3f951 introduced a configure error:
```log
CMake Error at C:/Libs/VTK-8.2.0/CMake/vtkModuleAPI.cmake:140 (message):
Requested modules not available:
vtkvtksys
Modules/Bridge/VtkGlue/itk-module-init.cmake:93 (vtk_module_config)
CMake/ITKModuleEnablement.cmake:436 (include)
CMakeLists.txt:754 (include)
-- Configuring incomplete, errors occurred!
```
> COMP: Fix error made by bcb6876: module vtkvtksys not available

- Modules/Bridge/VtkGlue/wrapping/CMakeLists.txt
- Wrapping/macro_files/itk_end_wrap_module.cmake
This is my proposition to fix the build issue introduced by #5502.
In short, it disables Python stable "limited" API when wrapping itkVtkGlue module wrapping.
Other modules are not affected by this change.
WDYT @dzenanz @hjmjohnson @thewtex
> COMP: Disable limited Python API for itkVtkGlue module wrapping

- Modules/Core/Common/include/itkIndex.h
- Modules/Core/Common/include/itkOffset.h
- Modules/Core/Common/include/itkSize.h
Improved the error messages from `std::out_of_range` exceptions thrown by the `at` member functions of `itk::Index`, `itk::Offset`, and `itk::Size`.
Example:
Out of range: `itk::Index::at` argument `pos` (which is 10) should be less than `Dimension` (which is 4)!
> Declare ExceptionThrowingBoundsCheck static, let `Index`, `Offset`, `Size` each have its own `std::out_of_range` text 

- Wrapping/Generators/CastXML/CMakeLists.txt
The GitHub Actions windows-2022 runner image for MSVC compatibility re: #5512
> COMP: Use CastXML binaries built on windows-2022

- Modules/ThirdParty/OpenJPEG/UpdateFromUpstream.sh
- Modules/ThirdParty/OpenJPEG/src/openjpeg/CMakeLists.txt
- Modules/ThirdParty/OpenJPEG/src/openjpeg/src/lib/openjp2/jp2.c
- Modules/ThirdParty/OpenJPEG/src/openjpeg/src/lib/openjp2/libopenjp2.pc.cmake.in
- Modules/ThirdParty/OpenJPEG/src/openjpeg/src/lib/openjp2/openjpeg.h
COMP: Update to openjpeg v2.5.4 (2025-09-20)
Closed issues:
CMake configure warning with CMake 3.30 and newer #1579
Merged pull requests:
pkgconfig: drop unused libraries from Libs.private #1591 (bgilbert)
Fix CMake warning: Compatibility with CMake < 3.10 will be removed #1580 (dzenanz)
code documentation updates #1576 (weanti)
Fixed ICC profile copy failure on write #1574 (mircomir)
opj_jp2_read_header: Check for error after parsing header. #1573 (sebras) (CVE-2025-54874)
> COMP: Update openjpeg to address cmake < 3.10 warning

- Wrapping/Generators/CastXML/CMakeLists.txt
These do not have GCC libraries as dependencies like the ones built with
GitHub Actions.
> COMP: Use CastXML Windows-11 built binaries

- Modules/ThirdParty/Expat/src/itkexpat/CMakeLists.txt
Expat is not tested on pre MSVC=1930 versions. A warning
idicates the lack of testing (not a lack of working).
Silence the configure-time warning.
Resolves: #5534
> COMP: Silence warning in Expat config

- Modules/Core/Common/test/itkConstNeighborhoodIteratorTest.cxx
- Modules/Core/Common/test/itkConstShapedNeighborhoodIteratorTest.cxx
- Modules/Core/Common/test/itkImageRegionIteratorTest.cxx
- Modules/Core/Common/test/itkImageScanlineIteratorTest1.cxx
- Modules/Core/QuadEdgeMesh/include/itkQuadEdgeMeshEulerOperatorsTestHelper.h
- Modules/Filtering/QuadEdgeMeshFiltering/include/itkDelaunayConformingQuadEdgeMeshFilter.hxx
- Modules/IO/JPEG/src/itkJPEGImageIO.cxx
- Modules/IO/MINC/src/itkMINCImageIO.cxx
When an std::vector is initialized by a compile-time constant, specifying its size, and the std::vector isn't resized afterwards, it appears clearer to use std::array instead. (And it may produce faster code, of course, when using std::array.) 
Cases found by the following regular expression (using Visual Studio, Find in Files...):
std::vector<[^=]+>[^=]+\([1-9][0-9]*\);
> Use `std::array` instead of `std::vector` for local variables
